// packages/lib-core/src/components/VirtualList/VirtualList.tsx
import React, {
  useCallback,
  useEffect,
  useRef,
  useState,
  useMemo,
} from "react";
import { getVirtualRange } from "@minerva/core";
import type { VirtualListItem, VirtualListProps, VirtualItem } from "./types";
import { hooks } from "../../internal/stylingHooks";
import styles from "./virtualList.module.scss";
import { useMergedRefs } from "../../internal/mergeRefs";
import { ProgressIndicator } from "../ProgressIndicator";
import { cn } from "../../utils/cn";

/**
 * 虚拟列表组件
 * @param items 列表数据项
 * @param itemHeight 列表项高度(可选,不传则自动计算)
 * @param maxHeight 最大高度
 * @param overscan 可视区域外预加载的项目数
 * @param renderItem 渲染列表项的函数
 * @param className 自定义类名
 * @param style 自定义样式
 * @param onLoadMore 加载更多的回调函数
 * @param loadMoreThreshold 触发加载更多的阈值(px)
 * @param highPerformance 是否启用高性能模式
 * @param loading 是否显示加载中状态
 * @param onItemClick 行点击回调 (提供时行可点击: 可聚焦并显示指针光标)
 * @param aria-label 列表的无障碍名称
 * @param ref 滚动容器根元素的 ref
 * @returns {React.ReactNode} 虚拟列表组件
 */
const VirtualList = ({
  items,
  itemHeight,
  maxHeight,
  overscan = 5,
  renderItem,
  className = "",
  style,
  onLoadMore,
  loadMoreThreshold = 100,
  highPerformance = false,
  loading = false,
  itemPadding = 8,
  onItemClick,
  "aria-label": ariaLabel,
  onScroll,
  ref,
  ...rest
}: VirtualListProps) => {
  const [scrollTop, setScrollTop] = useState(0);
  const [containerHeight, setContainerHeight] = useState(0);
  const lastScrollTop = useRef(0);
  const isLoadingMore = useRef(false);
  const rafRef = useRef<number | undefined>(undefined);
  const idleCallbackRef = useRef<number | undefined>(undefined);
  // Id of the item containing focus: it stays mounted when it is scrolled out
  // of the window, otherwise unmounting it would drop focus to <body>
  // (WCAG 2.4.3). Tracked by id so it follows the item when the data changes.
  const [focusedId, setFocusedId] = useState<VirtualListItem["id"] | null>(
    null,
  );
  const focusedIndex = useMemo(
    () =>
      focusedId === null
        ? null
        : items.findIndex((item) => item.id === focusedId),
    [focusedId, items],
  );

  // 测量得到的内容高度 (不含 padding), padding 在渲染时叠加,
  // 这样 itemPadding 变化后无需重新测量也能生效. 0 = 尚未测量
  const [measuredContentHeight, setMeasuredContentHeight] = useState(0);
  const needsMeasure =
    !itemHeight && measuredContentHeight === 0 && items.length > 0;

  // 容器高度: 挂载时读取并持续监听尺寸变化 (callback ref, 卸载时自动断开)
  const observeContainer = useCallback((node: HTMLDivElement | null) => {
    if (!node) return;
    setContainerHeight(node.clientHeight);
    if (typeof ResizeObserver === "undefined") return;
    const resizeObserver = new ResizeObserver((entries) => {
      for (const entry of entries) {
        setContainerHeight(entry.contentRect.height);
      }
    });
    resizeObserver.observe(node);
    return () => resizeObserver.disconnect();
  }, []);
  const containerRef = useMergedRefs(observeContainer, ref);

  // 测量首个项目的高度. 测量元素只在需要时挂载 (包括 items 稍后才加载的情况),
  // 测得高度后即被移除, observer 随之断开
  const measureItem = useCallback((node: HTMLDivElement | null) => {
    if (!node) return;
    const measure = () => {
      const height = node.offsetHeight;
      if (height > 0) setMeasuredContentHeight(height);
    };
    measure();
    if (typeof ResizeObserver === "undefined") return;
    const resizeObserver = new ResizeObserver(measure);
    resizeObserver.observe(node);
    return () => resizeObserver.disconnect();
  }, []);

  // 使用固定高度或计算出的高度
  const finalItemHeight =
    itemHeight ||
    (measuredContentHeight > 0 ? measuredContentHeight + itemPadding * 2 : 0);

  // 计算可见范围
  const visibleRange = useMemo(() => {
    // Before the first row is measured, render one row to measure it.
    if (!finalItemHeight) return { start: 0, end: 1, visibleCount: 1 };
    return getVirtualRange({
      scrollTop,
      viewportHeight: containerHeight,
      itemHeight: finalItemHeight,
      itemCount: items.length,
      overscan,
    });
  }, [scrollTop, containerHeight, finalItemHeight, overscan, items.length]);

  // 取消尚未执行的 RAF / idle 回调
  const cancelScheduled = useCallback(() => {
    if (rafRef.current !== undefined) {
      cancelAnimationFrame(rafRef.current);
      rafRef.current = undefined;
    }
    if (idleCallbackRef.current !== undefined) {
      if ("cancelIdleCallback" in window) {
        cancelIdleCallback(idleCallbackRef.current);
      }
      idleCallbackRef.current = undefined;
    }
  }, []);

  // 高性能模式下的渲染优化
  const scheduleUpdate = useCallback(
    (callback: () => void) => {
      if (highPerformance) {
        // Only the latest scroll position matters: drop pending work
        cancelScheduled();

        rafRef.current = requestAnimationFrame(() => {
          rafRef.current = undefined;
          if ("requestIdleCallback" in window) {
            idleCallbackRef.current = requestIdleCallback(
              () => {
                idleCallbackRef.current = undefined;
                callback();
              },
              { timeout: 100 },
            );
          } else {
            callback();
          }
        });
      } else {
        callback();
      }
    },
    [highPerformance, cancelScheduled],
  );

  // 生成虚拟列表项
  const virtualItems = useMemo(() => {
    const result: VirtualItem[] = [];
    for (let i = visibleRange.start; i < visibleRange.end; i++) {
      result.push({
        index: i,
        start: i * finalItemHeight,
        height: finalItemHeight,
      });
    }
    // Keep the focused item rendered (at its real position) outside the window
    if (
      focusedIndex !== null &&
      focusedIndex >= 0 &&
      (focusedIndex < visibleRange.start || focusedIndex >= visibleRange.end)
    ) {
      const focusedItem = {
        index: focusedIndex,
        start: focusedIndex * finalItemHeight,
        height: finalItemHeight,
      };
      if (focusedIndex < visibleRange.start) result.unshift(focusedItem);
      else result.push(focusedItem);
    }
    return result;
  }, [visibleRange, finalItemHeight, focusedIndex]);

  // 处理滚动
  const handleScroll = useCallback(
    (event: React.UIEvent<HTMLDivElement>) => {
      const { scrollTop, scrollHeight, clientHeight } = event.currentTarget;
      const isScrollingDown = scrollTop > lastScrollTop.current;
      lastScrollTop.current = scrollTop;

      scheduleUpdate(() => {
        setScrollTop(scrollTop);

        // 优化无限滚动触发逻辑
        if (
          isScrollingDown &&
          onLoadMore &&
          !isLoadingMore.current &&
          !loading &&
          scrollHeight - scrollTop - clientHeight < loadMoreThreshold &&
          // 添加额外检查，防止重复触发
          scrollHeight > clientHeight
        ) {
          isLoadingMore.current = true;
          // Tolerate callbacks that do not return a promise
          Promise.resolve(onLoadMore()).finally(() => {
            isLoadingMore.current = false;
          });
        }
      });
    },
    [onLoadMore, loading, loadMoreThreshold, scheduleUpdate],
  );
  const handleRootScroll = (event: React.UIEvent<HTMLDivElement>) => {
    onScroll?.(event);
    handleScroll(event);
  };

  // 卸载时清理所有待执行的 RAF / idle 回调
  useEffect(() => cancelScheduled, [cancelScheduled]);

  return (
    <div
      {...rest}
      ref={containerRef}
      // Scrollable region: focusable so keyboard users can scroll it
      role="region"
      aria-label={ariaLabel}
      tabIndex={0}
      aria-busy={loading || undefined}
      className={cn(styles.virtualList, className)}
      style={{
        ...style,
        maxHeight,
        overflow: "auto",
        position: "relative",
      }}
      onScroll={handleRootScroll}
      {...hooks("virtual-list", "root", { loading })}
    >
      {needsMeasure && (
        <div
          ref={measureItem}
          className={styles.measureItem}
          aria-hidden="true"
        >
          {renderItem(items[0], 0)}
        </div>
      )}
      <div
        style={{
          height: finalItemHeight ? items.length * finalItemHeight : "auto",
          position: "relative",
          willChange: "transform",
        }}
        className={styles.virtualListContent}
        role="list"
        aria-label={ariaLabel}
        {...hooks("virtual-list", "list")}
      >
        {finalItemHeight > 0 &&
          virtualItems.map((virtualItem) => (
            /* Clickable rows (onItemClick) stay list items for the list
               semantics, made focusable and activatable with Enter / Space
               so the click handler is not pointer-only. */
            /* eslint-disable jsx-a11y/no-noninteractive-element-interactions, jsx-a11y/no-noninteractive-tabindex */
            <div
              key={items[virtualItem.index].id}
              style={{
                position: "absolute",
                top: 0,
                transform: `translateY(${virtualItem.start}px)`,
                width: "100%",
                height: finalItemHeight,
                willChange: "transform",
                padding: itemPadding,
              }}
              className={cn(
                styles.virtualListItem,
                onItemClick && styles.clickable,
              )}
              tabIndex={onItemClick ? 0 : undefined}
              onClick={
                onItemClick
                  ? (event) =>
                      onItemClick(
                        items[virtualItem.index],
                        virtualItem.index,
                        event,
                      )
                  : undefined
              }
              onKeyDown={
                onItemClick
                  ? (event) => {
                      // Only the row itself: keys of its content are theirs
                      if (event.target !== event.currentTarget) return;
                      if (event.key !== "Enter" && event.key !== " ") return;
                      event.preventDefault();
                      onItemClick(
                        items[virtualItem.index],
                        virtualItem.index,
                        event,
                      );
                    }
                  : undefined
              }
              role="listitem"
              {...hooks("virtual-list", "item")}
              // Only a window of items is in the DOM: expose the real position
              aria-setsize={items.length}
              aria-posinset={virtualItem.index + 1}
              onFocus={() => setFocusedId(items[virtualItem.index].id)}
              onBlur={(event) => {
                if (!event.currentTarget.contains(event.relatedTarget)) {
                  setFocusedId(null);
                }
              }}
            >
              {renderItem(items[virtualItem.index], virtualItem.index)}
            </div>
            /* eslint-enable jsx-a11y/no-noninteractive-element-interactions, jsx-a11y/no-noninteractive-tabindex */
          ))}
      </div>
      {loading && (
        <div
          className={styles.loadingWrapper}
          {...hooks("virtual-list", "loading")}
        >
          <ProgressIndicator variant="wave" size="small" />
        </div>
      )}
    </div>
  );
};

export default React.memo(VirtualList);

// packages/vue/src/components/VirtualList/VirtualList.vue
<script setup lang="ts" generic="T extends VirtualListItem">
/**
 * VirtualList: a scrolling list that only renders the rows in (and around)
 * the visible area, with an optional measured row height, infinite loading
 * (`@load-more`) and clickable rows (`@item-click`). The scroll container is
 * a focusable, labelled region; rows expose their real position
 * (`aria-setsize` / `aria-posinset`) and the focused row stays mounted when
 * it is scrolled out of the window. Attributes fall through to the root.
 */
import {
  computed,
  getCurrentInstance,
  onBeforeUnmount,
  onMounted,
  ref,
  shallowRef,
  useAttrs,
  type CSSProperties,
  type StyleValue,
  type VNodeChild,
} from "vue";
import { getVirtualRange } from "@minerva/core";
import styles from "@react-styles/components/VirtualList/virtualList.module.scss";
import progressStyles from "@react-styles/components/ProgressIndicator/progressIndicator.module.scss";
import { hooks } from "../../internal/hooks";
import { IconWaveSquare } from "../../internal/icons";
import { useI18n } from "../../config/useI18n";
import type { VirtualItem, VirtualListItem, VirtualListProps } from "./types";

defineOptions({ name: "VirtualList", inheritAttrs: false });

const props = withDefaults(defineProps<VirtualListProps<T>>(), {
  itemHeight: undefined,
  itemPadding: 8,
  overscan: 5,
  renderItem: undefined,
  onLoadMore: undefined,
  loadMoreThreshold: 100,
  highPerformance: false,
  loading: false,
  "aria-label": undefined,
});

const emit = defineEmits<{
  /**
   * A row was clicked, or activated with Enter / Space while the row itself
   * has focus. Listening makes the rows clickable: focusable and shown with
   * a pointer cursor
   */
  itemClick: [item: T, index: number, event: MouseEvent | KeyboardEvent];
}>();

const slots = defineSlots<{
  /** Content of one row (wins over `renderItem`) */
  default?: (props: { item: T; index: number }) => unknown;
}>();

const attrs = useAttrs();
// `aria-label` is a declared prop: Vue stores it camelized
const ariaLabel = computed(
  () => (props as unknown as { ariaLabel?: string }).ariaLabel,
);
const instance = getCurrentInstance();
const { t } = useI18n();

// The loading row renders the DOM of the React <ProgressIndicator
// variant="wave" size="small" /> (same classes and hooks).

/** Renders the result of a render function (`renderItem`) */
const RenderContent = (p: { render: () => VNodeChild }) => p.render();
RenderContent.props = ["render"];

// Clickable rows (an @item-click listener) stay list items for the list
// semantics, made focusable and activatable with Enter / Space so the click
// handler is not pointer-only.
// (read while rendering: listeners are not reactive)
const isClickable = () => {
  const vnodeProps = instance?.vnode.props ?? {};
  return !!(vnodeProps.onItemClick || vnodeProps.onItemClickOnce);
};

const scrollTop = ref(0);
const containerHeight = ref(0);
let lastScrollTop = 0;
let isLoadingMore = false;
let rafId: number | undefined;
let idleId: number | undefined;
// Id of the item containing focus: it stays mounted when it is scrolled out
// of the window, otherwise unmounting it would drop focus to <body>
// (WCAG 2.4.3). Tracked by id so it follows the item when the data changes.
const focusedId = ref<VirtualListItem["id"] | null>(null);
const focusedIndex = computed(() =>
  focusedId.value === null
    ? null
    : props.items.findIndex((item) => item.id === focusedId.value),
);

// Measured content height (without padding); the padding is added when
// rendering so that itemPadding changes apply without measuring again.
// 0 = not measured yet.
const measuredContentHeight = ref(0);
const needsMeasure = computed(
  () =>
    !props.itemHeight &&
    measuredContentHeight.value === 0 &&
    props.items.length > 0,
);

// Container height: read on mount and observed while mounted
const root = shallowRef<HTMLDivElement | null>(null);
let containerObserver: ResizeObserver | undefined;
onMounted(() => {
  const node = root.value!;
  containerHeight.value = node.clientHeight;
  if (typeof ResizeObserver === "undefined") return;
  containerObserver = new ResizeObserver((entries) => {
    for (const entry of entries)
      containerHeight.value = entry.contentRect.height;
  });
  containerObserver.observe(node);
});

// Height of the first item. The measuring element is only mounted while
// needed (also when items arrive later) and removed once measured, which
// disconnects its observer.
let measureNode: HTMLElement | null = null;
let measureObserver: ResizeObserver | undefined;
const measureItem = (el: unknown) => {
  const node = (el as HTMLElement | null) ?? null;
  if (node === measureNode) return;
  measureObserver?.disconnect();
  measureObserver = undefined;
  measureNode = node;
  if (!node) return;
  const measure = () => {
    const height = node.offsetHeight;
    if (height > 0) measuredContentHeight.value = height;
  };
  measure();
  if (typeof ResizeObserver === "undefined") return;
  measureObserver = new ResizeObserver(measure);
  measureObserver.observe(node);
};

// Fixed or measured row height
const finalItemHeight = computed(
  () =>
    props.itemHeight ||
    (measuredContentHeight.value > 0
      ? measuredContentHeight.value + props.itemPadding * 2
      : 0),
);

const visibleRange = computed(() => {
  // Before the first row is measured, render one row to measure it.
  if (!finalItemHeight.value) return { start: 0, end: 1, visibleCount: 1 };
  return getVirtualRange({
    scrollTop: scrollTop.value,
    viewportHeight: containerHeight.value,
    itemHeight: finalItemHeight.value,
    itemCount: props.items.length,
    overscan: props.overscan,
  });
});

const virtualItems = computed(() => {
  const height = finalItemHeight.value;
  const { start, end } = visibleRange.value;
  const result: VirtualItem[] = [];
  for (let i = start; i < end; i++) {
    result.push({ index: i, start: i * height, height });
  }
  // Keep the focused item rendered (at its real position) outside the window
  const focused = focusedIndex.value;
  if (focused !== null && focused >= 0 && (focused < start || focused >= end)) {
    const item = { index: focused, start: focused * height, height };
    if (focused < start) result.unshift(item);
    else result.push(item);
  }
  return result;
});

// Cancels the pending RAF / idle callbacks
function cancelScheduled() {
  if (rafId !== undefined) {
    cancelAnimationFrame(rafId);
    rafId = undefined;
  }
  if (idleId !== undefined) {
    if ("cancelIdleCallback" in window) cancelIdleCallback(idleId);
    idleId = undefined;
  }
}

function scheduleUpdate(callback: () => void) {
  if (!props.highPerformance) {
    callback();
    return;
  }
  // Only the latest scroll position matters: drop pending work
  cancelScheduled();
  rafId = requestAnimationFrame(() => {
    rafId = undefined;
    if ("requestIdleCallback" in window) {
      idleId = requestIdleCallback(
        () => {
          idleId = undefined;
          callback();
        },
        { timeout: 100 },
      );
    } else {
      callback();
    }
  });
}

function onScroll(event: Event) {
  const {
    scrollTop: top,
    scrollHeight,
    clientHeight,
  } = event.currentTarget as HTMLDivElement;
  const isScrollingDown = top > lastScrollTop;
  lastScrollTop = top;
  scheduleUpdate(() => {
    scrollTop.value = top;
    const onLoadMore = props.onLoadMore;
    if (
      isScrollingDown &&
      onLoadMore &&
      !isLoadingMore &&
      !props.loading &&
      scrollHeight - top - clientHeight < props.loadMoreThreshold &&
      // no load-more for content that does not scroll
      scrollHeight > clientHeight
    ) {
      isLoadingMore = true;
      // Tolerate callbacks that do not return a promise
      Promise.resolve(onLoadMore()).finally(() => {
        isLoadingMore = false;
      });
    }
  });
}

onBeforeUnmount(() => {
  cancelScheduled();
  containerObserver?.disconnect();
  measureItem(null);
});

function onItemKeydown(event: KeyboardEvent, index: number) {
  // Only the row itself: keys of its content are theirs
  if (event.target !== event.currentTarget) return;
  if (event.key !== "Enter" && event.key !== " ") return;
  event.preventDefault();
  emit("itemClick", props.items[index], index, event);
}

function onItemFocusout(event: FocusEvent) {
  const row = event.currentTarget as HTMLElement;
  if (!row.contains(event.relatedTarget as Node | null)) focusedId.value = null;
}

const rootAttrs = computed(() => {
  const { class: className, style, ...rest } = attrs;
  return {
    ...rest,
    // Scrollable region: focusable so keyboard users can scroll it
    role: "region",
    "aria-label": ariaLabel.value,
    tabindex: 0,
    "aria-busy": props.loading || undefined,
    class: [styles.virtualList, className],
    style: [
      style as StyleValue,
      {
        maxHeight: `${props.maxHeight}px`,
        overflow: "auto",
        position: "relative",
      } satisfies CSSProperties,
    ],
    ...hooks("virtual-list", "root", { loading: props.loading }),
  };
});

const contentStyle = computed<CSSProperties>(() => ({
  height: finalItemHeight.value
    ? `${props.items.length * finalItemHeight.value}px`
    : "auto",
  position: "relative",
  willChange: "transform",
}));

const itemStyle = (start: number): CSSProperties => ({
  position: "absolute",
  top: 0,
  transform: `translateY(${start}px)`,
  width: "100%",
  height: `${finalItemHeight.value}px`,
  willChange: "transform",
  padding: `${props.itemPadding}px`,
});
</script>

<template>
  <div ref="root" v-bind="rootAttrs" @scroll="onScroll">
    <div
      v-if="needsMeasure"
      :ref="measureItem"
      :class="styles.measureItem"
      aria-hidden="true"
    >
      <slot v-if="slots.default" :item="items[0]" :index="0" />
      <RenderContent
        v-else-if="renderItem"
        :render="() => renderItem!(items[0], 0)"
      />
    </div>
    <div
      :style="contentStyle"
      :class="styles.virtualListContent"
      role="list"
      :aria-label="ariaLabel"
      v-bind="hooks('virtual-list', 'list')"
    >
      <template v-if="finalItemHeight > 0">
        <div
          v-for="virtualItem in virtualItems"
          :key="items[virtualItem.index].id"
          :style="itemStyle(virtualItem.start)"
          :class="[styles.virtualListItem, isClickable() && styles.clickable]"
          :tabindex="isClickable() ? 0 : undefined"
          role="listitem"
          v-bind="hooks('virtual-list', 'item')"
          :aria-setsize="items.length"
          :aria-posinset="virtualItem.index + 1"
          @click="
            isClickable() &&
            emit(
              'itemClick',
              items[virtualItem.index],
              virtualItem.index,
              $event,
            )
          "
          @keydown="isClickable() && onItemKeydown($event, virtualItem.index)"
          @focusin="focusedId = items[virtualItem.index].id"
          @focusout="onItemFocusout"
        >
          <slot
            v-if="slots.default"
            :item="items[virtualItem.index]"
            :index="virtualItem.index"
          />
          <RenderContent
            v-else-if="renderItem"
            :render="
              () => renderItem!(items[virtualItem.index], virtualItem.index)
            "
          />
        </div>
      </template>
    </div>
    <div
      v-if="loading"
      :class="styles.loadingWrapper"
      v-bind="hooks('virtual-list', 'loading')"
    >
      <div
        :class="[progressStyles.progressIndicator, progressStyles.primary]"
        role="progressbar"
        :aria-label="t('common.loading')"
        v-bind="
          hooks('progress', 'root', {
            variant: 'wave',
            size: 'small',
            color: 'primary',
          })
        "
      >
        <div
          :class="[progressStyles.waveContainer, progressStyles.small]"
          v-bind="hooks('progress', 'indicator')"
        >
          <IconWaveSquare :class="progressStyles.wave" aria-hidden="true" />
        </div>
      </div>
    </div>
  </div>
</template>
