// packages/angular/src/components/rating/rating.ts
import { NgTemplateOutlet } from "@angular/common";
import {
  ChangeDetectionStrategy,
  Component,
  ElementRef,
  ViewEncapsulation,
  booleanAttribute,
  computed,
  inject,
  input,
  model,
  numberAttribute,
  signal,
} from "@angular/core";
import {
  RATING_STAR_COUNT,
  cn,
  createRatingMachine,
  getRatingKeyValue,
  getRatingStarFills,
  type RatingMachineEvent,
  type RatingStarFill,
} from "@minerva/core";
import { logicalArrowKey } from "@minerva/dom";
import {
  MnFormValueControl,
  fieldWiring,
  injectFormField,
  provideValueAccessor,
} from "../../internal/forms";
import { MnHook } from "../../internal/hooks";
import { ICONS } from "../../internal/icon-data";
import { classOf } from "../../internal/classes";
import { connectMachine } from "../../internal/machine";
import { ratingStyles as s } from "../../internal/styles";

/** Size of the Rating stars */
export type RatingSize = "small" | "medium" | "large";

const SIZE_PX: Record<RatingSize, number> = {
  small: 12,
  medium: 16,
  large: 20,
};
const STARS = Array.from({ length: RATING_STAR_COUNT }, (_, i) => i);
// The library's Star / StarHalf icons, drawn here with React's stroke width
// (1.5) and fill (full stars are filled with `currentColor`).
const STAR_PATH = ICONS.Star.nodes[0][1]["d"];
const STAR_HALF_PATH = ICONS.StarHalf.nodes[0][1]["d"];

const toNumber = (value: unknown): number => numberAttribute(value, 0);

/**
 * Rating: displays a score as 5 stars (any 0..max scale), optionally with
 * the value and the number of ratings. Same DOM, classes and styling hooks
 * as React's Rating: the host is the root `<span>` (`role="img"`, or
 * `role="slider"` when interactive).
 *
 * Interactive (hover preview, half-star clicks, keyboard) with `interactive`
 * (React: passing `onChange`) or when bound to a form control (`ngModel`,
 * `formControl`, `formControlName`), unless read-only or disabled: arrows
 * step half a star (`max / 10`; in RTL ArrowLeft increases), PageUp /
 * PageDown one whole star (`max / 5`), Home / End jump to 0 / `max`; all
 * clamped to 0..max. The native `keydown` event bubbles to the host first:
 * call `preventDefault()` in a `(keydown)` listener to take over a key.
 *
 * Two-way binding: `[(value)]` (`valueChange` reports user changes, React's
 * `onChange`), `ngModel` or a Reactive Forms control. Inside
 * `<mn-form-control>` it takes the field's id, description, invalid /
 * required / read-only / disabled states.
 *
 * @example
 * <mn-rating [value]="8.6" showValue [ratingCount]="3214" />
 * <mn-rating interactive aria-label="Your rating" [(value)]="score" />
 * <mn-rating formControlName="score" [max]="5" />
 */
@Component({
  selector: "mn-rating",
  exportAs: "mnRating",
  imports: [MnHook, NgTemplateOutlet],
  encapsulation: ViewEncapsulation.None,
  changeDetection: ChangeDetectionStrategy.OnPush,
  providers: [provideValueAccessor(() => MnRating)],
  host: {
    "[class]": "rootClasses()",
    "data-minerva": "rating",
    "data-part": "root",
    "[attr.data-readonly]": "isInteractive() ? null : ''",
    "[attr.data-size]": "size()",
    "[attr.role]": "isInteractive() ? 'slider' : 'img'",
    "[attr.aria-label]": "label()",
    "[attr.aria-valuenow]": "isInteractive() ? current() : null",
    "[attr.aria-valuemin]": "isInteractive() ? 0 : null",
    "[attr.aria-valuemax]": "isInteractive() ? max() : null",
    "[attr.aria-required]":
      "isInteractive() && field.required() ? 'true' : null",
    "[attr.aria-invalid]": "isInteractive() && field.invalid() ? 'true' : null",
    "[attr.aria-disabled]": "isDisabled() ? 'true' : null",
    "[attr.aria-describedby]": "field.describedBy()",
    "[attr.tabindex]": "isInteractive() ? 0 : null",
    "[attr.id]": "field.id()",
    "[attr.name]": "null",
    "[attr.disabled]": "null",
    "[attr.required]": "null",
    "[attr.readonly]": "null",
    "[attr.interactive]": "null",
    "(keydown)": "onKeyDown($event)",
    "(mouseleave)": "onMouseLeave()",
    "(focusout)": "onFocusOut($event)",
  },
  template: `
    <ng-template #star let-fill>
      @if (fill === "half") {
        <span
          [class]="starClass(fill)"
          [style.width.px]="px()"
          [style.height.px]="px()"
          mnHook="rating"
          mnPart="star"
          [mnStates]="{ fill }"
        >
          <svg
            xmlns="http://www.w3.org/2000/svg"
            viewBox="0 0 24 24"
            [attr.width]="px()"
            [attr.height]="px()"
            fill="none"
            stroke="currentColor"
            stroke-width="1.5"
            stroke-linecap="round"
            stroke-linejoin="round"
            aria-hidden="true"
            focusable="false"
            [class]="s.halfBase"
          >
            <path [attr.d]="starPath" />
          </svg>
          <svg
            xmlns="http://www.w3.org/2000/svg"
            viewBox="0 0 24 24"
            [attr.width]="px()"
            [attr.height]="px()"
            fill="currentColor"
            stroke="currentColor"
            stroke-width="1.5"
            stroke-linecap="round"
            stroke-linejoin="round"
            aria-hidden="true"
            focusable="false"
            [class]="s.halfFill"
          >
            <path [attr.d]="starHalfPath" />
          </svg>
        </span>
      } @else {
        <svg
          xmlns="http://www.w3.org/2000/svg"
          viewBox="0 0 24 24"
          [attr.width]="px()"
          [attr.height]="px()"
          [attr.fill]="fill === 'full' ? 'currentColor' : 'none'"
          stroke="currentColor"
          stroke-width="1.5"
          stroke-linecap="round"
          stroke-linejoin="round"
          aria-hidden="true"
          focusable="false"
          [class]="starClass(fill)"
          mnHook="rating"
          mnPart="star"
          [mnStates]="{ fill }"
        >
          <path [attr.d]="starPath" />
        </svg>
      }
    </ng-template>

    <span [class]="s.stars" aria-hidden="true" mnHook="rating" mnPart="stars">
      @for (i of stars; track i) {
        @if (isInteractive()) {
          <button
            type="button"
            tabindex="-1"
            [class]="s.starButton"
            (click)="onStarClick($event, i)"
            (mouseenter)="send({ type: 'HOVER', index: i })"
          >
            <ng-container
              [ngTemplateOutlet]="star"
              [ngTemplateOutletContext]="{ $implicit: fills()[i] }"
            />
          </button>
        } @else {
          <ng-container
            [ngTemplateOutlet]="star"
            [ngTemplateOutletContext]="{ $implicit: fills()[i] }"
          />
        }
      }
    </span>
    @if (showValue()) {
      <span [class]="s.value" mnHook="rating" mnPart="value">
        <strong>{{ valueText() }}</strong>
        @if (ratingCount() !== undefined) {
          <span [class]="s.count" mnHook="rating" mnPart="count">{{
            countText()
          }}</span>
        }
      </span>
    }
    @if (name() && !isDisabled()) {
      <input type="hidden" [attr.name]="name()" [value]="current()" />
    }
  `,
})
export class MnRating extends MnFormValueControl<number> {
  /**
   * Current score, from 0 to max (two-way: `[(value)]`; `valueChange`
   * reports user changes, React's `onChange`)
   */
  readonly value = model<number | undefined>(undefined);
  /**
   * Initial score when `value` is not bound
   * @default 0
   */
  readonly defaultValue = input(0, { transform: toNumber });
  /**
   * Highest score; the score is always drawn on 5 stars (half stars for
   * fractions between 0.25 and 0.75 of a star)
   * @default 10
   */
  readonly max = input(10, {
    transform: (value: unknown) => numberAttribute(value, 10),
  });
  /**
   * Star size: 12px, 16px or 20px
   * @default "medium"
   */
  readonly size = input<RatingSize>("medium");
  /**
   * Shows the score (one decimal) after the stars
   * @default false
   */
  readonly showValue = input(false, { transform: booleanAttribute });
  /** Number of ratings, shown after the score when showValue is set */
  readonly ratingCount = input<number | undefined, unknown>(undefined, {
    transform: (value: unknown) =>
      value === undefined || value === null || value === ""
        ? undefined
        : numberAttribute(value),
  });
  /**
   * Makes the rating an interactive slider: hover previews, clicking the
   * left / right half of a star picks a half / full star, arrow keys step by
   * max / 10, Home / End jump to 0 / max (React: passing `onChange`). Also
   * interactive when bound to a form control (`ngModel`, `formControl`)
   * @default false
   */
  readonly interactive = input(false, { transform: booleanAttribute });
  /**
   * Forces display mode even when interactive
   * @default false
   */
  readonly readOnly = input(false, { transform: booleanAttribute });
  /**
   * Disables the control (display mode, not submitted)
   * @default false
   */
  readonly disabled = input(false, { transform: booleanAttribute });
  /**
   * The control must have a value (`aria-required`; use Angular's
   * validators for validation)
   * @default false
   */
  readonly required = input(false, { transform: booleanAttribute });
  /** Name submitted with native form data (a hidden input) */
  readonly name = input<string | undefined>(undefined);
  /**
   * Accessible label of the rating
   * @default "<value> / <max>"
   */
  readonly ariaLabel = input<string | undefined>(undefined, {
    alias: "aria-label",
  });
  /** Extra ids of elements describing the rating */
  readonly ariaDescribedby = input<string | undefined>(undefined, {
    alias: "aria-describedby",
  });

  protected readonly s = s;
  protected readonly stars = STARS;
  protected readonly starPath = STAR_PATH;
  protected readonly starHalfPath = STAR_HALF_PATH;
  private readonly host = inject<ElementRef<HTMLElement>>(ElementRef);
  /** Bound to a form control (ngModel / Reactive Forms): interactive */
  private readonly formBound = signal(false);
  protected readonly field = fieldWiring(injectFormField(), {
    describedBy: () => this.ariaDescribedby(),
    invalid: () => this.controlInvalid(),
    required: () => this.required(),
    readOnly: () => this.readOnly(),
    disabled: () => this.disabled() || this.formDisabled(),
  });
  protected readonly isDisabled = this.field.disabled;

  /** The score shown (the bound value, else the default) */
  protected readonly current = computed(
    () => this.value() ?? this.defaultValue(),
  );
  protected readonly isInteractive = computed(
    () =>
      (this.interactive() || this.formBound()) &&
      !this.field.readOnly() &&
      !this.isDisabled(),
  );

  // Hover preview, picks and keys: core's rating machine (the score stays
  // controlled by `value`).
  private readonly machine = connectMachine(
    () =>
      createRatingMachine({
        value: this.current(),
        max: this.max(),
        readOnly: !this.isInteractive(),
        onValueChange: (next) => this.commit(next),
      }),
    () => ({
      value: this.current(),
      max: this.max(),
      readOnly: !this.isInteractive(),
    }),
  );

  /** Fill of each star: fractions in 0.25..0.75 render a half star */
  protected readonly fills = computed(() =>
    getRatingStarFills(this.machine.state(), this.max()),
  );
  protected readonly px = computed(
    () => SIZE_PX[this.size()] ?? SIZE_PX.medium,
  );
  protected readonly valueText = computed(() => this.current().toFixed(1));
  protected readonly countText = computed(
    () => `(${(this.ratingCount() ?? 0).toLocaleString("en-US")})`,
  );
  protected readonly label = computed(
    () => this.ariaLabel() ?? `${this.valueText()} / ${this.max()}`,
  );
  protected readonly rootClasses = computed(() =>
    cn(
      s.rating,
      classOf(s, this.size()),
      this.isInteractive() && s.interactive,
    ),
  );

  override registerOnChange(fn: (value: number) => void): void {
    super.registerOnChange(fn);
    this.formBound.set(true);
  }

  override writeValue(value: number | null | undefined): void {
    this.value.set(value == null ? 0 : Number(value));
  }

  protected starClass(fill: RatingStarFill): string {
    return cn(s.star, s[fill as "half" | "empty"]);
  }

  protected send(event: RatingMachineEvent): void {
    this.machine.send(event);
  }

  protected onStarClick(event: MouseEvent, index: number): void {
    // Left half of a star -> half star, right half -> full star.
    const rect = (event.currentTarget as HTMLElement).getBoundingClientRect();
    const leftHalf = event.clientX - rect.left < rect.width / 2;
    this.send({ type: "PICK", index, half: leftHalf });
  }

  protected onKeyDown(event: KeyboardEvent): void {
    // Listeners of the consumer go first; preventDefault() takes over the key.
    if (event.defaultPrevented || !this.isInteractive()) return;
    // Stars follow the reading direction: in RTL ArrowLeft increases.
    const key = logicalArrowKey(event.key, this.host.nativeElement);
    if (getRatingKeyValue(key, this.current(), this.max()) === null) return;
    event.preventDefault();
    this.send({ type: "KEY", key });
  }

  protected onMouseLeave(): void {
    if (this.isInteractive()) this.send({ type: "HOVER_END" });
  }

  protected onFocusOut(event: FocusEvent): void {
    const next = event.relatedTarget as Node | null;
    if (!next || !this.host.nativeElement.contains(next)) this.notifyTouched();
  }

  private commit(next: number): void {
    this.value.set(next);
    this.notifyChange(next);
  }

  /** Focuses the rating (interactive mode) */
  focus(options?: FocusOptions): void {
    this.host.nativeElement.focus(options);
  }
}

// packages/web-components/src/components/rating/rating.ts
import { css, html, nothing } from "lit";
import { property, query } from "lit/decorators.js";
import { classMap } from "lit/directives/class-map.js";
import { styleMap } from "lit/directives/style-map.js";
import styles from "@react-styles/components/Rating/rating.module.scss?inline";
import { AriaController } from "../../internal/aria";
import { DEV, devWarn } from "../../internal/dev";
import {
  createRatingMachine,
  getRatingKeyValue,
  getRatingStarFills,
  RATING_STAR_COUNT,
  type RatingMachineEvent,
  type RatingMachineProps,
  type RatingStarFill,
} from "@minerva/core";
import { MachineController } from "../../controllers/machine";
import { logicalArrowKey } from "@minerva/dom";
import {
  FormAssociatedElement,
  type ValidityResult,
} from "../../internal/form";
import { IconStar, IconStarHalf } from "../../internal/icons";
import { LocaleController } from "../../internal/locale";
import { MinervaElement, hostStyles } from "../../internal/minerva-element";
import { itemParts } from "../../internal/styling-hooks";
import { sharedStyles } from "../../internal/styles";

export type RatingSize = "small" | "medium" | "large";

/** One dimension of a `<minerva-rating-scale>` */
export interface RatingDimension {
  /** Stable key, passed back in the change event */
  key: string;
  /** Displayed label */
  label: string;
  /** Current score of the dimension */
  value: number;
  /** Optional description, shown as the row's title tooltip */
  hint?: string;
}

const SIZE_PX: Record<RatingSize, number> = {
  small: 12,
  medium: 16,
  large: 20,
};
const STARS = Array.from({ length: RATING_STAR_COUNT }, (_, i) => i);

/** Shared star styles: the icons are 1em outlines, filled through CSS. */
const starStyles = css`
  .star svg {
    display: block;
    width: 100%;
    height: 100%;
    stroke-width: 1.5;
  }
  .full svg,
  .halfFill svg {
    fill: currentColor;
  }
`;

/**
 * A score drawn as 5 stars on any 0..max scale (`<Rating>` of React),
 * optionally followed by the value and the number of ratings.
 *
 * Display-only by default (`role="img"`), like the React component without
 * `onChange`. With `interactive`: hover previews, clicking the left / right
 * half of a star picks a half / full star, and the stars are a slider:
 * arrows step half a star (`max / 10`; in RTL ArrowLeft increases),
 * PageUp / PageDown one whole star (`max / 5`), Home / End jump to 0 /
 * `max`, all clamped to 0..max. `readonly` (or `disabled`) forces the
 * display-only version again.
 *
 * Form-associated: submits `value` under `name`; `required` makes a 0 score
 * invalid (`valueMissing`); supports `form.reset()` (restores the `value`
 * attribute), `<fieldset disabled>` and state restoration.
 *
 * @summary Star rating (display or interactive slider).
 * @tag minerva-rating
 * @csspart root - The root (role="slider", or role="img" when display-only)
 * @csspart stars - The star row
 * @csspart star - Each star
 * @csspart star--fill-full - Item state of `star`: fill full
 * @csspart star--fill-half - Item state of `star`: fill half
 * @csspart star--fill-empty - Item state of `star`: fill empty
 * @csspart value - The score and the count
 * @csspart count - The number of ratings
 * @fires change - The user changed the score
 * @fires minerva-change - The user changed the score; `detail: { value }`
 */
export class MinervaRating extends FormAssociatedElement {
  static override tagName = "minerva-rating";
  static override shadowRootOptions = {
    ...FormAssociatedElement.shadowRootOptions,
    delegatesFocus: true,
  };
  static override styles = [
    hostStyles,
    css`
      :host {
        display: inline-flex;
        vertical-align: middle;
      }
    `,
    sharedStyles(styles),
    starStyles,
  ];

  /** Current score, from 0 to max (property; the `value` attribute sets `defaultValue`) */
  @property({ attribute: false })
  value = 0;

  /** Initial score, restored by `form.reset()` (the `value` attribute) */
  @property({ type: Number, attribute: "value" })
  defaultValue = 0;

  /** Highest score; the score is always drawn on 5 stars */
  @property({ type: Number })
  max = 10;

  /** Star size: 12px, 16px or 20px */
  @property({ reflect: true })
  size: RatingSize = "medium";

  /** Shows the score (one decimal) after the stars */
  @property({ type: Boolean, attribute: "show-value" })
  showValue = false;

  /** Number of ratings, shown after the score when show-value is set */
  @property({ type: Number, attribute: "rating-count" })
  ratingCount?: number;

  /**
   * Makes the rating an interactive slider (React: passing `onChange`);
   * display-only otherwise
   */
  @property({ type: Boolean, reflect: true })
  interactive = false;

  /** Forces display mode even when `interactive` is set */
  @property({ type: Boolean, reflect: true, attribute: "readonly" })
  readOnly = false;

  @query(".rating")
  private root!: HTMLElement;

  private readonly locale = new LocaleController(this);
  private readonly aria = new AriaController(this, () => this.labels);
  private dirty = false;
  // Hover preview, picks and keys; `value` stays the source of truth (a
  // controlled value of the machine, changed through `commit`).
  private readonly rating = new MachineController(
    this,
    createRatingMachine(this.ratingProps()),
  );

  private ratingProps(): RatingMachineProps {
    return {
      value: this.value,
      max: this.max,
      readOnly: !this.isInteractive,
      onValueChange: (next) => this.commit(next),
    };
  }

  private send(event: RatingMachineEvent) {
    // properties set since the last update apply right away
    this.rating.sync(this.ratingProps());
    this.rating.send(event);
  }

  private get isInteractive(): boolean {
    return this.interactive && !this.readOnly && !this.isDisabled;
  }

  override focus(options?: FocusOptions): void {
    this.root?.focus(options);
  }

  override blur(): void {
    this.root?.blur();
  }

  protected getFormValue(): string {
    return String(this.value);
  }

  protected override getValidity(): ValidityResult {
    if (this.required && !(this.value > 0)) {
      return {
        flags: { valueMissing: true },
        message: this.locale.t("validation.valueMissing"),
        anchor: this.root,
      };
    }
    return { flags: {}, message: "" };
  }

  protected resetFormValue(): void {
    this.dirty = false;
    this.value = this.defaultValue;
  }

  protected override restoreFormState(state: unknown): void {
    if (typeof state === "string" && state.trim() !== "") {
      const n = Number(state);
      if (Number.isFinite(n)) this.value = n;
    }
  }

  protected override willUpdate(changed: Map<PropertyKey, unknown>): void {
    // first update: a value set before connecting wins over the default
    // unless the value attribute is present
    if (
      changed.has("defaultValue") &&
      !this.dirty &&
      (this.hasUpdated || this.hasAttribute("value"))
    ) {
      this.value = this.defaultValue;
    }
    if (
      DEV &&
      (changed.has("value") || changed.has("max")) &&
      (this.value < 0 || this.value > this.max)
    ) {
      devWarn(
        MinervaRating.tagName,
        `value (${this.value}) is outside 0..max (${this.max}).`,
      );
    }
    this.rating.sync(this.ratingProps());
  }

  private commit(next: number) {
    if (next === this.value) return;
    this.dirty = true;
    this.value = next;
    this.dispatchEvent(new Event("change", { bubbles: true }));
    this.emit("minerva-change", { value: next });
  }

  private handleStarClick(event: MouseEvent, index: number) {
    if (!this.isInteractive) return;
    // Left half of a star -> half star, right half -> full star.
    const rect = (event.currentTarget as HTMLElement).getBoundingClientRect();
    const leftHalf = event.clientX - rect.left < rect.width / 2;
    this.send({ type: "PICK", index, half: leftHalf });
  }

  private handleKeyDown(event: KeyboardEvent) {
    if (event.defaultPrevented || !this.isInteractive) return;
    // Stars follow the reading direction: in RTL ArrowLeft increases.
    const key = logicalArrowKey(event.key, this);
    if (getRatingKeyValue(key, this.value, this.max) === null) return;
    event.preventDefault();
    this.send({ type: "KEY", key });
  }

  protected override hookStates() {
    return { readonly: !this.isInteractive, size: this.size };
  }

  private renderStar(fill: RatingStarFill, px: number) {
    const size = styleMap({
      width: `${px}px`,
      height: `${px}px`,
      fontSize: `${px}px`,
    });
    const part = itemParts("star", { fill });
    if (fill === "half") {
      return html`<span part=${part} class="star half" style=${size}
        ><span class="halfBase">${IconStar}</span
        ><span class="halfFill">${IconStarHalf}</span></span
      >`;
    }
    return html`<span
      part=${part}
      class=${classMap({ star: true, [fill]: true })}
      style=${size}
      >${IconStar}</span
    >`;
  }

  protected override render() {
    const interactive = this.isInteractive;
    const { value, max } = this;
    // Normalize the score to 5 stars; fractions in 0.25..0.75 render a half
    // star (or the hover preview).
    const state = this.rating.machine.project(
      this.rating.state,
      this.ratingProps(),
    );
    const fills = getRatingStarFills(state, max);
    const fillOf = (i: number) => fills[i];
    const px = SIZE_PX[this.size] ?? SIZE_PX.medium;
    const label = this.aria.label ?? `${value.toFixed(1)} / ${max}`;

    const stars = html`<span class="stars" part="stars" aria-hidden="true">
      ${STARS.map((i) =>
        interactive
          ? html`<button
              type="button"
              tabindex="-1"
              class="starButton"
              @click=${(event: MouseEvent) => this.handleStarClick(event, i)}
              @mouseenter=${() => this.send({ type: "HOVER", index: i })}
            >
              ${this.renderStar(fillOf(i), px)}
            </button>`
          : this.renderStar(fillOf(i), px),
      )}
    </span>`;

    const valueNode = this.showValue
      ? html`<span class="value" part="value"
          ><strong>${value.toFixed(1)}</strong>${
            this.ratingCount !== undefined
              ? html`<span class="count" part="count"
                  >(${this.ratingCount.toLocaleString("en-US")})</span
                >`
              : nothing
          }</span
        >`
      : nothing;

    const classes = classMap({
      rating: true,
      [this.size]: true,
      interactive,
    });

    if (!interactive) {
      return html`<span
        part="root"
        class=${classes}
        role="img"
        aria-label=${label}
        aria-description=${this.aria.description ?? nothing}
        aria-disabled=${this.isDisabled ? "true" : nothing}
        >${stars}${valueNode}</span
      >`;
    }

    return html`<span
      part="root"
      class=${classes}
      role="slider"
      tabindex="0"
      aria-label=${label}
      aria-description=${this.aria.description ?? nothing}
      aria-valuenow=${value}
      aria-valuemin="0"
      aria-valuemax=${max}
      aria-required=${this.required ? "true" : nothing}
      @keydown=${this.handleKeyDown}
      @mouseleave=${() => this.send({ type: "HOVER_END" })}
      >${stars}${valueNode}</span
    >`;
  }
}

/**
 * Several labelled ratings sharing one scale, e.g. plot / characters /
 * writing (`<RatingScale>` of React). Each row is a `<minerva-rating>`;
 * rows are display-only unless `interactive` (React: passing `onChange`). Not form-associated: submit the
 * dimensions yourself, or use one named `<minerva-rating>` per dimension.
 *
 * @summary Several labelled ratings on one scale.
 * @tag minerva-rating-scale
 * @csspart root - The list of rows
 * @csspart row - Each row (a label and a rating)
 * @csspart label - The label of a row
 * @fires minerva-change - The user rated a dimension; `detail: { key, value, dimensions }` (`dimensions` is already updated)
 */
export class MinervaRatingScale extends MinervaElement {
  static override tagName = "minerva-rating-scale";
  static override dependencies = [MinervaRating];
  static override styles = [
    hostStyles,
    css`
      :host {
        display: block;
      }
    `,
    sharedStyles(styles),
  ];

  /** Dimensions to rate, one row each */
  @property({ attribute: false })
  dimensions: readonly RatingDimension[] = [];

  /** Highest score shared by every dimension */
  @property({ type: Number })
  max = 10;

  /** Star size */
  @property({ reflect: true })
  size: RatingSize = "medium";

  /** Makes the rows interactive (React: passing `onChange`) */
  @property({ type: Boolean, reflect: true })
  interactive = false;

  /** Forces display mode even when `interactive` is set */
  @property({ type: Boolean, reflect: true, attribute: "readonly" })
  readOnly = false;

  /** Hides the score at the end of each row */
  @property({ type: Boolean, attribute: "hide-value" })
  hideValue = false;

  private handleChange(event: CustomEvent<{ value: number }>, key: string) {
    // the row's own event stops here: the scale re-emits it with the key
    event.stopPropagation();
    const { value } = event.detail;
    this.dimensions = this.dimensions.map((dim) =>
      dim.key === key ? { ...dim, value } : dim,
    );
    this.emit("minerva-change", { key, value, dimensions: this.dimensions });
  }

  protected override hookStates() {
    return { readonly: !this.interactive || this.readOnly, size: this.size };
  }

  protected override render() {
    return html`<div class="scale" part="root">
      ${this.dimensions.map(
        (dim) =>
          html`<div class="scaleRow" part="row" title=${dim.hint ?? nothing}>
            <span class="scaleLabel" part="label">${dim.label}</span>
            <minerva-rating
              .value=${dim.value}
              .max=${this.max}
              .size=${this.size}
              ?show-value=${!this.hideValue}
              ?interactive=${this.interactive}
              ?readonly=${this.readOnly}
              aria-label=${`${dim.label} ${dim.value.toFixed(1)} / ${this.max}`}
              @minerva-change=${(event: CustomEvent<{ value: number }>) =>
                this.handleChange(event, dim.key)}
            ></minerva-rating>
          </div>`,
      )}
    </div>`;
  }
}

declare global {
  interface HTMLElementTagNameMap {
    "minerva-rating": MinervaRating;
    "minerva-rating-scale": MinervaRatingScale;
  }
}
