// packages/lib-core/src/components/Switch/Switch.tsx
import React, { useEffect, useRef, useState } from "react";
import { cn } from "../../utils/cn";
import { useControllableState } from "../../internal/useControllableState";
import { useMergedRefs } from "../../internal/mergeRefs";
import { pickDataAttributes } from "../../internal/dataAttributes";
import {
  useFormControlContext,
  useFormControlProps,
} from "../FormControl/context";
import type { SwitchProps } from "./types";
import styles from "./switch.module.scss";

const RIPPLE_DURATION = 400;

const placementClass = {
  start: styles.labelStart,
  end: styles.labelEnd,
  top: styles.labelTop,
  bottom: styles.labelBottom,
} as const;

const hasContent = (node: React.ReactNode) =>
  node != null && node !== false && node !== "";

/**
 * Switch: toggles between two mutually exclusive states.
 * Renders a native checkbox with role="switch"; `ref` reaches the <input>.
 * `offLabel` + `onLabel` add clickable labels on both sides of the slider, or
 * build a two-segment control with `variant="segmented"`.
 */
const Switch = ({
  checked,
  defaultChecked = false,
  disabled,
  size = "medium",
  color = "primary",
  shape = "round",
  variant = "slider",
  label,
  children,
  offLabel,
  onLabel,
  "aria-label": ariaLabel,
  "aria-labelledby": ariaLabelledBy,
  "aria-describedby": ariaDescribedBy,
  name,
  id,
  value,
  labelPlacement = "end",
  loading = false,
  ripple = true,
  className,
  style,
  trackStyle,
  thumbStyle,
  onChange,
  onFocus,
  onBlur,
  icon,
  iconPlacement = "start",
  ref,
  ...rest
}: SwitchProps) => {
  const dataAttributes = pickDataAttributes(rest);
  const [isChecked, setIsChecked] = useControllableState({
    value: checked,
    defaultValue: defaultChecked,
  });
  const [rippleActive, setRippleActive] = useState(false);
  const rippleTimer = useRef<ReturnType<typeof setTimeout> | undefined>(
    undefined,
  );
  const inputRef = useRef<HTMLInputElement>(null);
  const mergedRef = useMergedRefs(inputRef, ref);

  useEffect(() => () => clearTimeout(rippleTimer.current), []);

  // FormControl wiring; an explicit `disabled` wins (so `false` opts out).
  const fc = useFormControlContext();
  const field = useFormControlProps({
    id,
    "aria-describedby": ariaDescribedBy,
  });
  const isDisabled = disabled ?? fc?.disabled ?? false;
  const readOnly = !!fc?.readOnly;
  const blocked = isDisabled || loading || readOnly;

  const handleChange = (event: React.ChangeEvent<HTMLInputElement>) => {
    if (blocked) return;
    setIsChecked(event.target.checked);
    onChange?.(event.target.checked, event);
  };

  // Native checkboxes toggle on Space only; the switch pattern also allows Enter.
  const handleKeyDown = (event: React.KeyboardEvent<HTMLInputElement>) => {
    if (event.key !== "Enter") return;
    event.preventDefault();
    if (blocked) return;
    event.currentTarget.click();
  };

  // Clicks reach the input also when the wrapping label is clicked, and the
  // Space key fires a click too: the ripple follows every toggle.
  const handleClick = (event: React.MouseEvent<HTMLInputElement>) => {
    if (readOnly) {
      event.preventDefault();
      return;
    }
    if (!ripple || blocked) return;
    clearTimeout(rippleTimer.current);
    setRippleActive(true);
    rippleTimer.current = setTimeout(
      () => setRippleActive(false),
      RIPPLE_DURATION,
    );
  };

  // Side labels / segments set a state directly: they click the input so the
  // regular change event (and onChange) fires.
  const setState = (next: boolean) => {
    if (blocked || next === isChecked) return;
    inputRef.current?.click();
  };

  const bilateral = hasContent(offLabel) && hasContent(onLabel);
  const segmented = variant === "segmented" && bilateral;

  const input = (
    <input
      ref={mergedRef}
      type="checkbox"
      role={segmented ? undefined : "switch"}
      className={segmented ? styles.hiddenInput : undefined}
      id={segmented ? undefined : field.id}
      name={name}
      value={value}
      aria-label={segmented ? undefined : ariaLabel}
      aria-labelledby={segmented ? undefined : ariaLabelledBy}
      aria-checked={segmented ? undefined : isChecked}
      aria-disabled={segmented ? undefined : isDisabled || loading || undefined}
      aria-busy={loading || undefined}
      aria-invalid={segmented ? undefined : field["aria-invalid"]}
      aria-required={segmented ? undefined : field["aria-required"]}
      aria-readonly={segmented ? undefined : field["aria-readonly"]}
      aria-describedby={segmented ? undefined : field["aria-describedby"]}
      aria-hidden={segmented || undefined}
      tabIndex={segmented ? -1 : undefined}
      checked={isChecked}
      disabled={isDisabled || loading}
      onChange={handleChange}
      onClick={handleClick}
      onKeyDown={handleKeyDown}
      onFocus={onFocus}
      onBlur={onBlur}
    />
  );

  if (segmented) {
    return (
      // The group carries the field wiring: its name (FormControl label unless
      // named explicitly) and helper / error description (the FormControl
      // error message is referenced while invalid). aria-invalid and
      // aria-required are not supported on role="group": both states are
      // exposed as data-invalid / data-required (and by the FormControl).
      <span
        role="group"
        id={field.id}
        aria-label={ariaLabel}
        aria-labelledby={
          ariaLabelledBy ?? (fc && !ariaLabel ? fc.labelId : undefined)
        }
        aria-describedby={field["aria-describedby"]}
        aria-disabled={blocked || undefined}
        data-invalid={field["aria-invalid"] || undefined}
        data-required={fc?.required || undefined}
        {...dataAttributes}
        className={cn(
          styles.segmented,
          styles[size],
          styles[color],
          blocked && styles.disabled,
          className,
        )}
        style={style}
      >
        {input}
        {[false, true].map((segmentState) => {
          const active = isChecked === segmentState;
          return (
            <button
              key={String(segmentState)}
              type="button"
              className={cn(styles.segment, active && styles.segmentActive)}
              disabled={blocked}
              aria-pressed={active}
              onClick={() => setState(segmentState)}
            >
              {segmentState ? onLabel : offLabel}
            </button>
          );
        })}
      </span>
    );
  }

  const switchClasses = cn(
    styles.switch,
    styles[size],
    !bilateral && placementClass[labelPlacement],
    styles[color],
    {
      [styles.checked]: isChecked,
      [styles.checkedLarge]: isChecked && size === "large",
      [styles.disabled]: isDisabled,
      [styles.loading]: loading,
      [styles.square]: shape === "square",
      [styles.ripple]: ripple && rippleActive,
      [styles.bilateral]: bilateral,
    },
    className,
  );

  const control = (
    <span className={styles.switchBase}>
      {input}
      <span className={styles.track} style={trackStyle} />
      <span className={styles.thumb} style={thumbStyle}>
        {iconPlacement === "start" && icon && (
          <span className={styles.icon}>{icon}</span>
        )}
      </span>
      {ripple && <span className={styles.rippleEffect} />}
    </span>
  );
  const iconNode =
    iconPlacement === "end" && icon ? (
      <span className={styles.icon}>{icon}</span>
    ) : null;

  if (bilateral) {
    const side = (sideState: boolean) => {
      const active = isChecked === sideState;
      return (
        <button
          type="button"
          className={cn(styles.side, active && styles.sideActive)}
          disabled={blocked}
          onClick={() => setState(sideState)}
        >
          {sideState ? onLabel : offLabel}
        </button>
      );
    };
    // A <span> root: the side buttons must not sit inside the input's label.
    return (
      <span className={switchClasses} style={style} {...dataAttributes}>
        {side(false)}
        {control}
        {side(true)}
        {iconNode}
      </span>
    );
  }

  const content = label ?? children;
  const labelNode = hasContent(content) ? (
    <span className={styles.label}>{content}</span>
  ) : null;
  // Label before the control for start/top, after it for end/bottom; the
  // placement class only changes the flex direction (row vs column).
  const labelFirst = labelPlacement === "start" || labelPlacement === "top";

  return (
    // The label wraps the input, so clicking anywhere on it toggles the switch.
    <label className={switchClasses} style={style} {...dataAttributes}>
      {labelFirst && labelNode}
      {control}
      {iconNode}
      {!labelFirst && labelNode}
    </label>
  );
};

export default Switch;

// packages/vue/src/components/Switch/Switch.vue
<script setup lang="ts">
/**
 * Switch: toggles between two mutually exclusive states. Renders a native
 * checkbox with role="switch". `v-model` (or `defaultChecked`); emits
 * `change(checked, event)`. `offLabel` + `onLabel` add clickable labels on
 * both sides of the slider, or build a two-segment control with
 * `variant="segmented"`.
 */
import { computed, onBeforeUnmount, ref, useAttrs } from "vue";
import styles from "@react-styles/components/Switch/switch.module.scss";
import { hooks } from "../../internal/hooks";
import { useControllable } from "../../internal/controllable";
import {
  useFormControlContext,
  useFormControlProps,
} from "../../internal/form-control";
import { splitRootAttrs } from "../Checkbox/attrs";
import type { SwitchProps } from "./types";

defineOptions({ name: "Switch", inheritAttrs: false });

const RIPPLE_DURATION = 400;

const props = withDefaults(defineProps<SwitchProps>(), {
  modelValue: undefined,
  defaultChecked: undefined,
  disabled: undefined,
  size: "medium",
  color: "primary",
  shape: "round",
  variant: "slider",
  label: undefined,
  offLabel: undefined,
  onLabel: undefined,
  name: undefined,
  id: undefined,
  value: undefined,
  labelPlacement: "end",
  loading: false,
  ripple: true,
  trackStyle: undefined,
  thumbStyle: undefined,
  iconPlacement: "start",
});
const emit = defineEmits<{
  "update:modelValue": [checked: boolean];
  /** The user toggled the switch: the new state and the change event */
  change: [checked: boolean, event: Event];
  focus: [event: FocusEvent];
  blur: [event: FocusEvent];
}>();
const slots = defineSlots<{
  /** Label content (alternative to the `label` prop / slot) */
  default?: () => unknown;
  /** Label content (the `label` prop) */
  label?: () => unknown;
  /** Custom icon (inside the thumb or after the switch: `iconPlacement`) */
  icon?: () => unknown;
  /** Label of the "off" state (the `offLabel` prop) */
  "off-label"?: () => unknown;
  /** Label of the "on" state (the `onLabel` prop) */
  "on-label"?: () => unknown;
}>();

const attrs = useAttrs();
const inputRef = ref<HTMLInputElement | null>(null);
const rippleActive = ref(false);
let rippleTimer: ReturnType<typeof setTimeout> | undefined;
onBeforeUnmount(() => clearTimeout(rippleTimer));

const checked = useControllable<boolean>(props, "modelValue", {
  defaultProp: "defaultChecked",
  fallback: false,
  name: "Switch",
});

// FormControl wiring; an explicit `disabled` wins (so `false` opts out).
const fc = useFormControlContext();
const field = useFormControlProps(() => ({
  id: props.id,
  "aria-describedby": attrs["aria-describedby"] as string | undefined,
}));
const isDisabled = computed(
  () => props.disabled ?? fc?.disabled.value ?? false,
);
const readOnly = computed(() => !!fc?.readOnly.value);
const blocked = computed(
  () => isDisabled.value || props.loading || readOnly.value,
);

function onChange(event: Event) {
  const input = event.target as HTMLInputElement;
  /* v8 ignore next */
  if (blocked.value) return;
  const next = input.checked;
  checked.value = next;
  emit("change", next, event);
  // A controlled state wins: the DOM follows the prop, not the click.
  input.checked = checked.value;
}

// Native checkboxes toggle on Space only; the switch pattern also allows Enter.
function onKeyDown(event: KeyboardEvent) {
  if (event.key !== "Enter") return;
  event.preventDefault();
  if (blocked.value) return;
  (event.currentTarget as HTMLInputElement).click();
}

// Clicks reach the input also when the wrapping label is clicked, and the
// Space key fires a click too: the ripple follows every toggle.
function onClick(event: MouseEvent) {
  if (readOnly.value) {
    event.preventDefault();
    return;
  }
  if (!props.ripple || blocked.value) return;
  clearTimeout(rippleTimer);
  rippleActive.value = true;
  rippleTimer = setTimeout(() => {
    rippleActive.value = false;
  }, RIPPLE_DURATION);
}

// Side labels / segments set a state directly: they click the input so the
// regular change event fires.
function setState(next: boolean) {
  if (blocked.value || next === checked.value) return;
  inputRef.value?.click();
}

const hasOff = computed(() => !!props.offLabel || !!slots["off-label"]);
const hasOn = computed(() => !!props.onLabel || !!slots["on-label"]);
const bilateral = computed(() => hasOff.value && hasOn.value);
const segmented = computed(
  () => props.variant === "segmented" && bilateral.value,
);
const hasLabel = computed(
  () => !!props.label || !!slots.label || !!slots.default,
);
const labelFirst = computed(
  () => props.labelPlacement === "start" || props.labelPlacement === "top",
);

const split = computed(() => {
  const {
    "aria-label": ariaLabel,
    "aria-labelledby": ariaLabelledBy,
    "aria-describedby": _describedBy,
    ...rest
  } = attrs;
  return {
    ...splitRootAttrs(rest),
    ariaLabel: ariaLabel as string | undefined,
    ariaLabelledBy: ariaLabelledBy as string | undefined,
  };
});

const inputAttrs = computed(() => {
  const seg = segmented.value;
  const wired = field.value;
  return {
    ...split.value.control,
    type: "checkbox",
    role: seg ? undefined : "switch",
    class: seg ? styles.hiddenInput : undefined,
    id: seg ? undefined : wired.id,
    name: props.name,
    value: props.value,
    "aria-label": seg ? undefined : split.value.ariaLabel,
    "aria-labelledby": seg ? undefined : split.value.ariaLabelledBy,
    "aria-checked": seg ? undefined : checked.value,
    "aria-disabled": seg
      ? undefined
      : isDisabled.value || props.loading || undefined,
    "aria-busy": props.loading || undefined,
    "aria-invalid": seg ? undefined : wired["aria-invalid"],
    "aria-required": seg ? undefined : wired["aria-required"],
    "aria-readonly": seg ? undefined : wired["aria-readonly"],
    "aria-describedby": seg ? undefined : wired["aria-describedby"],
    "aria-hidden": seg || undefined,
    tabindex: seg ? -1 : undefined,
    checked: checked.value,
    disabled: isDisabled.value || props.loading,
    ...hooks("switch", "input"),
  };
});

const rootHooks = computed(() =>
  hooks("switch", "root", {
    state: checked.value ? "checked" : "unchecked",
    disabled: isDisabled.value,
    loading: props.loading,
    invalid: !!fc?.invalid.value,
    readonly: readOnly.value,
    required: !!fc?.required.value,
    size: props.size,
    color: props.color,
    shape: props.shape,
    variant: segmented.value ? "segmented" : "slider",
  }),
);

const placementClass = {
  start: styles.labelStart,
  end: styles.labelEnd,
  top: styles.labelTop,
  bottom: styles.labelBottom,
} as const;

const switchClasses = computed(() => [
  styles.switch,
  styles[props.size],
  !bilateral.value && placementClass[props.labelPlacement],
  styles[props.color],
  {
    [styles.checked]: checked.value,
    [styles.checkedLarge]: checked.value && props.size === "large",
    [styles.disabled]: isDisabled.value,
    [styles.loading]: props.loading,
    [styles.square]: props.shape === "square",
    [styles.ripple]: props.ripple && rippleActive.value,
    [styles.bilateral]: bilateral.value,
  },
]);

const groupAttrs = computed(() => ({
  role: "group",
  id: field.value.id,
  "aria-label": split.value.ariaLabel,
  "aria-labelledby":
    split.value.ariaLabelledBy ??
    (fc && !split.value.ariaLabel ? fc.labelId.value : undefined),
  "aria-describedby": field.value["aria-describedby"],
  "aria-disabled": blocked.value || undefined,
  ...split.value.root,
  ...rootHooks.value,
}));
</script>

<template>
  <!--
    Segmented: the group carries the field wiring (its name and description);
    aria-invalid / aria-required are exposed by the data-* hooks.
  -->
  <span
    v-if="segmented"
    :class="[
      styles.segmented,
      styles[size],
      styles[color],
      blocked && styles.disabled,
    ]"
    v-bind="groupAttrs"
  >
    <input
      ref="inputRef"
      v-bind="inputAttrs"
      @change="onChange"
      @click="onClick"
      @keydown="onKeyDown"
      @focus="emit('focus', $event)"
      @blur="emit('blur', $event)"
    />
    <button
      v-for="segmentState in [false, true]"
      :key="String(segmentState)"
      type="button"
      :class="[
        styles.segment,
        checked === segmentState && styles.segmentActive,
      ]"
      :disabled="blocked"
      :aria-pressed="checked === segmentState"
      v-bind="hooks('switch', 'segment')"
      @click="setState(segmentState)"
    >
      <slot v-if="segmentState" name="on-label">{{ onLabel }}</slot>
      <slot v-else name="off-label">{{ offLabel }}</slot>
    </button>
  </span>
  <!-- A <span> root: the side buttons must not sit inside the input's label. -->
  <component
    :is="bilateral ? 'span' : 'label'"
    v-else
    :class="switchClasses"
    v-bind="{ ...split.root, ...rootHooks }"
  >
    <button
      v-if="bilateral"
      type="button"
      :class="[styles.side, !checked && styles.sideActive]"
      :disabled="blocked"
      v-bind="hooks('switch', 'side')"
      @click="setState(false)"
    >
      <slot name="off-label">{{ offLabel }}</slot>
    </button>
    <span
      v-if="!bilateral && labelFirst && hasLabel"
      :class="styles.label"
      v-bind="hooks('switch', 'label')"
    >
      <slot name="label">
        <template v-if="label">{{ label }}</template>
        <slot v-else />
      </slot>
    </span>
    <span :class="styles.switchBase" v-bind="hooks('switch', 'control')">
      <input
        ref="inputRef"
        v-bind="inputAttrs"
        @change="onChange"
        @click="onClick"
        @keydown="onKeyDown"
        @focus="emit('focus', $event)"
        @blur="emit('blur', $event)"
      />
      <span
        :class="styles.track"
        :style="trackStyle"
        v-bind="hooks('switch', 'track')"
      />
      <span
        :class="styles.thumb"
        :style="thumbStyle"
        v-bind="hooks('switch', 'thumb')"
      >
        <span
          v-if="iconPlacement === 'start' && slots.icon"
          :class="styles.icon"
          v-bind="hooks('switch', 'icon')"
        >
          <slot name="icon" />
        </span>
      </span>
      <span v-if="ripple" :class="styles.rippleEffect" />
    </span>
    <button
      v-if="bilateral"
      type="button"
      :class="[styles.side, checked && styles.sideActive]"
      :disabled="blocked"
      v-bind="hooks('switch', 'side')"
      @click="setState(true)"
    >
      <slot name="on-label">{{ onLabel }}</slot>
    </button>
    <span
      v-if="iconPlacement === 'end' && slots.icon"
      :class="styles.icon"
      v-bind="hooks('switch', 'icon')"
    >
      <slot name="icon" />
    </span>
    <span
      v-if="!bilateral && !labelFirst && hasLabel"
      :class="styles.label"
      v-bind="hooks('switch', 'label')"
    >
      <slot name="label">
        <template v-if="label">{{ label }}</template>
        <slot v-else />
      </slot>
    </span>
  </component>
</template>
