// packages/lib-web-components/src/components/tabs/tabs.ts
import { css, html, nothing, unsafeCSS, type PropertyValues } from "lit";
import { property, query } from "lit/decorators.js";
import { classMap } from "lit/directives/class-map.js";
import type { ColorScheme } from "@minerva/core";
import styles from "@lib-core-styles/components/Tabs/tabs.module.scss?inline";
import { RovingFocusController } from "../../controllers/roving-focus";
import { AriaController } from "../../internal/aria";
import { DEV, devWarn } from "../../internal/dev";
import { getDirection } from "../../internal/dom";
import { MinervaElement, hostStyles } from "../../internal/minerva-element";

/**
 * Visual style: `line` (underline indicator), `enclosed` (browser-like
 * tabs), `soft` (segmented control) or `pills` (separated rounded tabs)
 */
export type TabsVariant = "line" | "enclosed" | "soft" | "pills";

/** Layout / keyboard direction of the tab list */
export type TabsOrientation = "horizontal" | "vertical";

/** When a focused tab becomes selected */
export type TabsActivationMode = "automatic" | "manual";

let nextId = 0;

/** The `<minerva-tabs>` owning `el` (not an outer / nested group). */
const ownerOf = (el: Element): MinervaTabs | null =>
  el.parentElement?.closest<MinervaTabs>("minerva-tabs") ?? null;

/**
 * Accessible tabs (WAI-ARIA tabs pattern, `<Tabs>` / `<TabList>` of
 * lib-core) with line / enclosed / soft / pills variants, semantic colors
 * and horizontal or vertical orientation.
 *
 * Tabs (`<minerva-tab>`) and panels (`<minerva-tab-panel>`) are light DOM
 * children paired by `value`; the element renders the `role="tablist"`
 * around the tabs (they go to the `tab` slot automatically) and wires
 * `aria-selected` / `aria-controls` / `aria-labelledby` with ids in the
 * light DOM. Arrow keys (per orientation and direction), Home and End move
 * focus among the enabled tabs (core roving focus); with
 * `activation-mode="automatic"` the focused tab is selected, with
 * `"manual"` only Enter / Space / click select.
 *
 * @summary Tabs with a tablist, roving focus and automatic or manual activation.
 * @tag minerva-tabs
 * @slot - `<minerva-tab-panel>` elements
 * @slot tab - `<minerva-tab>` elements (assigned automatically)
 * @csspart base - The root wrapper
 * @csspart tablist - The `role="tablist"` container
 * @fires minerva-change - The user selected a tab (`detail: { value }`); cancelable: `preventDefault()` keeps the current selection (controlled pattern)
 */
export class MinervaTabs extends MinervaElement {
  static override tagName = "minerva-tabs";
  static override styles = [
    hostStyles,
    css`
      :host {
        display: block;
        min-width: 0;
      }
    `,
    unsafeCSS(styles),
  ];

  /** Value of the selected tab */
  @property({ reflect: true })
  value?: string;

  /** Visual style */
  @property({ reflect: true })
  variant: TabsVariant = "line";

  /** Color of the selection */
  @property({ reflect: true })
  color: ColorScheme = "primary";

  /** Layout and arrow-key direction */
  @property({ reflect: true })
  orientation: TabsOrientation = "horizontal";

  /**
   * `automatic` selects a tab when it receives focus; `manual` only on
   * Enter / Space / click
   */
  @property({ reflect: true, attribute: "activation-mode" })
  activationMode: TabsActivationMode = "automatic";

  /** Stops arrow keys at the first / last tab instead of wrapping */
  @property({ type: Boolean, reflect: true, attribute: "no-loop" })
  noLoop = false;

  /**
   * Accessible name of the tab list (`aria-label` / `aria-labelledby` on the
   * element work too)
   */
  @property()
  label = "";

  @query('[role="tablist"]')
  private tablist!: HTMLElement;

  private readonly aria = new AriaController(this);
  private readonly baseId = `minerva-tabs-${++nextId}`;
  private rovingKey = "";
  private observer: MutationObserver | null = null;

  private readonly roving = new RovingFocusController(this, () => ({
    getItems: () => this.tabs,
    orientation: this.orientation,
    dir: getDirection(this),
    loop: !this.noLoop,
  }));

  /** The `<minerva-tab>` elements of this group (not of nested groups). */
  get tabs(): MinervaTab[] {
    return Array.from(this.querySelectorAll<MinervaTab>("minerva-tab")).filter(
      (tab) => ownerOf(tab) === this,
    );
  }

  /** The `<minerva-tab-panel>` elements of this group. */
  get panels(): MinervaTabPanel[] {
    return Array.from(
      this.querySelectorAll<MinervaTabPanel>("minerva-tab-panel"),
    ).filter((panel) => ownerOf(panel) === this);
  }

  /** Called by a tab (click / Enter / Space / focus): selects `value`. */
  select(value: string): void {
    if (value === this.value) return;
    if (!this.emit("minerva-change", { value }, { cancelable: true })) {
      // controlled: the parent keeps (or later sets) the selection
      return;
    }
    this.value = value;
  }

  override connectedCallback(): void {
    super.connectedCallback();
    if (typeof MutationObserver !== "undefined") {
      this.observer = new MutationObserver(() => this.sync());
      this.observer.observe(this, {
        childList: true,
        subtree: true,
        attributes: true,
        attributeFilter: ["value", "disabled"],
      });
    }
  }

  override disconnectedCallback(): void {
    super.disconnectedCallback();
    this.observer?.disconnect();
    this.observer = null;
    this.rovingKey = "";
  }

  protected override updated(changed: PropertyValues<this>): void {
    if (
      changed.has("value") &&
      DEV &&
      this.value !== undefined &&
      this.tabs.length > 0 &&
      !this.tabs.some((tab) => tab.value === this.value)
    ) {
      devWarn(
        MinervaTabs.tagName,
        `value "${this.value}" does not match any <minerva-tab>.`,
      );
    }
    this.sync();
  }

  /** Re-creates the roving focus when its options changed. */
  private ensureRoving() {
    if (!this.tablist) return;
    const key = `${this.orientation}|${getDirection(this)}|${this.noLoop}`;
    if (key !== this.rovingKey) {
      this.rovingKey = key;
      this.roving.detach();
      this.roving.attach(this.tablist);
    }
  }

  /** Pushes selection, ids and styles to the tabs and panels. */
  private sync() {
    if (!this.tablist) return;
    this.ensureRoving();
    const tabs = this.tabs;
    const panels = this.panels;
    for (const tab of tabs) {
      if (!tab.id) tab.id = `${this.baseId}-tab-${tab.value}`;
    }
    for (const panel of panels) {
      if (!panel.id) panel.id = `${this.baseId}-panel-${panel.value}`;
    }
    for (const tab of tabs) {
      const panel = panels.find((p) => p.value === tab.value);
      tab.sync(this, tab.value === this.value, panel?.id);
    }
    for (const panel of panels) {
      const tab = tabs.find((t) => t.value === panel.value);
      panel.sync(this, panel.value === this.value, tab?.id);
    }
    // tab stop: the selected tab, else the first enabled one
    const selected = tabs.find(
      (tab) => tab.value === this.value && !tab.disabled,
    );
    const stop = selected ?? tabs.find((tab) => !tab.disabled);
    if (stop) this.roving.setActive(stop, { focus: false });
    else this.roving.refresh();
  }

  /** Re-checks the direction before core's roving focus handles a key. */
  private handleKeyDownCapture = () => this.ensureRoving();

  /** Automatic activation: focusing a tab selects it. */
  private handleFocusIn = (event: FocusEvent) => {
    if (this.activationMode !== "automatic") return;
    const tab = this.tabs.find((t) => t === event.target);
    if (tab && !tab.disabled) this.select(tab.value);
  };

  protected override render() {
    return html`<div
      part="base"
      class=${classMap({
        tabs: true,
        [this.color]: true,
        vertical: this.orientation === "vertical",
      })}
      data-orientation=${this.orientation}
      @keydown=${{ handleEvent: this.handleKeyDownCapture, capture: true }}
    >
      <div
        part="tablist"
        role="tablist"
        aria-label=${this.label || this.aria.label || nothing}
        aria-orientation=${this.orientation}
        data-orientation=${this.orientation}
        class=${classMap({
          list: true,
          [`${this.variant}List`]: true,
          verticalList: this.orientation === "vertical",
        })}
        @focusin=${this.handleFocusIn}
      >
        <slot name="tab" @slotchange=${() => this.sync()}></slot>
      </div>
      <slot @slotchange=${() => this.sync()}></slot>
    </div>`;
  }
}

/**
 * A tab of a `<minerva-tabs>` (`<Tab>` of lib-core). The element itself is
 * the `role="tab"` (focusable, `aria-selected`, `aria-controls` pointing at
 * the panel with the same `value`).
 *
 * @summary A `role="tab"` trigger of `<minerva-tabs>`.
 * @tag minerva-tab
 * @slot - Tab content
 * @csspart base - The visual trigger
 */
export class MinervaTab extends MinervaElement {
  static override tagName = "minerva-tab";
  static override styles = [
    hostStyles,
    css`
      :host {
        display: inline-flex;
        flex: 0 0 auto;
        min-width: 0;
        max-width: 100%;
        outline: none;
      }
      :host([disabled]) {
        pointer-events: none;
      }
      .trigger {
        width: 100%;
      }
      .verticalTrigger {
        justify-content: flex-start;
      }
      :host(:focus-visible) .trigger {
        outline: var(--focus-ring-width) solid var(--tabs-accent);
        outline-offset: -2px;
      }
      :host([disabled]) .trigger {
        opacity: 0.5;
        cursor: not-allowed;
      }
    `,
    unsafeCSS(styles),
  ];

  /** Value identifying the tab and its panel (must not contain whitespace) */
  @property({ reflect: true })
  value = "";

  /** Disables the tab (skipped by arrow keys) */
  @property({ type: Boolean, reflect: true })
  disabled = false;

  /** Overrides the group color (the tab stays tinted while inactive) */
  @property({ reflect: true })
  color?: ColorScheme;

  /** Whether the tab is the selected one (set by `<minerva-tabs>`) */
  @property({ type: Boolean, reflect: true })
  selected = false;

  private group: MinervaTabs | null = null;

  /** @internal Called by the owning `<minerva-tabs>`. */
  sync(group: MinervaTabs, selected: boolean, panelId?: string): void {
    this.group = group;
    this.selected = selected;
    if (panelId) this.setAttribute("aria-controls", panelId);
    else this.removeAttribute("aria-controls");
    this.requestUpdate();
  }

  override connectedCallback(): void {
    super.connectedCallback();
    if (!this.hasAttribute("slot")) this.slot = "tab";
    this.setAttribute("role", "tab");
    this.addEventListener("mousedown", this.handleMouseDown);
    this.addEventListener("keydown", this.handleKeyDown);
    this.addEventListener("click", this.handleClick);
  }

  override disconnectedCallback(): void {
    super.disconnectedCallback();
    this.removeEventListener("mousedown", this.handleMouseDown);
    this.removeEventListener("keydown", this.handleKeyDown);
    this.removeEventListener("click", this.handleClick);
    this.group = null;
  }

  private select() {
    (this.group ?? ownerOf(this))?.select(this.value);
  }

  private handleMouseDown = (event: MouseEvent) => {
    if (this.disabled) {
      event.preventDefault();
      return;
    }
    if (event.button === 0 && !event.ctrlKey) this.select();
    // keep focus where it is on ctrl-click / other buttons (context menus)
    else event.preventDefault();
  };

  private handleKeyDown = (event: KeyboardEvent) => {
    if (event.defaultPrevented) return;
    if (this.disabled || (event.key !== "Enter" && event.key !== " ")) return;
    event.preventDefault();
    this.select();
  };

  // Assistive technologies may activate with a bare click (no mouse down).
  private handleClick = (event: MouseEvent) => {
    if (!this.disabled && event.detail === 0) this.select();
  };

  protected override updated(): void {
    this.setAttribute("aria-selected", String(this.selected));
    this.setAttribute("data-state", this.selected ? "active" : "inactive");
    if (this.disabled) {
      this.setAttribute("aria-disabled", "true");
      this.setAttribute("data-disabled", "");
    } else {
      this.removeAttribute("aria-disabled");
      this.removeAttribute("data-disabled");
    }
    const orientation = this.group?.orientation ?? "horizontal";
    this.setAttribute("data-orientation", orientation);
  }

  protected override render() {
    const group = this.group;
    const variant = group?.variant ?? "line";
    const vertical = group?.orientation === "vertical";
    return html`<span
      part="base"
      class=${classMap({
        trigger: true,
        [`${variant}Trigger`]: true,
        verticalTrigger: vertical,
        [this.color ?? ""]: !!this.color,
        colored: !!this.color,
      })}
      data-state=${this.selected ? "active" : "inactive"}
      data-orientation=${group?.orientation ?? "horizontal"}
      ><slot></slot
    ></span>`;
  }
}

/**
 * The `role="tabpanel"` content of the tab with the same `value`
 * (`<TabPanel>` of lib-core). Inactive panels are `hidden`.
 *
 * @summary A `role="tabpanel"` of `<minerva-tabs>`.
 * @tag minerva-tab-panel
 * @slot - Panel content
 * @csspart base - The panel wrapper
 */
export class MinervaTabPanel extends MinervaElement {
  static override tagName = "minerva-tab-panel";
  static override styles = [
    hostStyles,
    css`
      :host {
        display: block;
        flex: 1;
        min-width: 0;
        outline: none;
      }
      :host(:focus-visible) .panel {
        outline: var(--focus-ring-width) solid var(--primary-color);
        outline-offset: var(--focus-ring-offset);
      }
    `,
    unsafeCSS(styles),
  ];

  /** Value of the tab this panel belongs to */
  @property({ reflect: true })
  value = "";

  private orientation: TabsOrientation = "horizontal";

  /** @internal Called by the owning `<minerva-tabs>`. */
  sync(group: MinervaTabs, selected: boolean, tabId?: string): void {
    this.orientation = group.orientation;
    this.hidden = !selected;
    this.setAttribute("data-state", selected ? "active" : "inactive");
    this.setAttribute("data-orientation", group.orientation);
    if (tabId) this.setAttribute("aria-labelledby", tabId);
    else this.removeAttribute("aria-labelledby");
    this.requestUpdate();
  }

  override connectedCallback(): void {
    super.connectedCallback();
    this.setAttribute("role", "tabpanel");
    if (!this.hasAttribute("tabindex")) this.tabIndex = 0;
  }

  protected override render() {
    return html`<div
      part="base"
      class="panel"
      data-orientation=${this.orientation}
    >
      <slot></slot>
    </div>`;
  }
}

declare global {
  interface HTMLElementTagNameMap {
    "minerva-tabs": MinervaTabs;
    "minerva-tab": MinervaTab;
    "minerva-tab-panel": MinervaTabPanel;
  }
}

// packages/lib-core/src/components/Tabs/Tabs.tsx
import {
  createContext,
  useContext,
  useEffect,
  useId,
  useLayoutEffect,
  useRef,
  useState,
  type KeyboardEvent,
  type MouseEvent,
} from "react";
import { getNextIndex } from "@minerva/core";
import { cn } from "../../utils/cn";
import { useMergedRefs } from "../../internal/mergeRefs";
import { useControllableState } from "../../internal/useControllableState";
import { composeEventHandlers } from "../../internal/composeEventHandlers";
import type {
  TabListProps,
  TabPanelProps,
  TabProps,
  TabsOrientation,
  TabsProps,
  TabsVariant,
} from "./types";
import styles from "./tabs.module.scss";

interface TabsContextValue {
  baseId: string;
  value: string | undefined;
  select: (value: string) => void;
  variant: TabsVariant;
  orientation: TabsOrientation;
  dir: "ltr" | "rtl";
  activationMode: "automatic" | "manual";
}

// Each Tabs provides its own context, so nested Tabs never share selection,
// ids or styles (variant / orientation are applied on the list and the tabs
// themselves, not through descendant selectors).
const TabsContext = createContext<TabsContextValue>({
  baseId: "tabs",
  value: undefined,
  select: () => {},
  variant: "line",
  orientation: "horizontal",
  dir: "ltr",
  activationMode: "automatic",
});

/** Id of the tab whose roving tabIndex is 0 when the selected tab can't be. */
const TabStopContext = createContext<string | undefined>(undefined);

const tabId = (baseId: string, value: string) => `${baseId}-tab-${value}`;
const panelId = (baseId: string, value: string) => `${baseId}-panel-${value}`;

/** The `role="tab"` buttons owned by `list` (not those of nested Tabs). */
const getOwnTabs = (list: HTMLElement) =>
  Array.from(list.querySelectorAll<HTMLButtonElement>('[role="tab"]')).filter(
    (tab) => tab.closest('[role="tablist"]') === list,
  );

/**
 * Tabs: accessible tabs (WAI-ARIA tabs pattern) with line / enclosed / soft /
 * pills variants, semantic colors and horizontal or vertical orientation.
 */
export const Tabs = ({
  variant = "line",
  color = "primary",
  orientation = "horizontal",
  activationMode = "automatic",
  dir,
  value: valueProp,
  defaultValue,
  onChange,
  className,
  children,
  ref,
  ...rest
}: TabsProps) => {
  const baseId = useId();
  const [value, setValue] = useControllableState<string | undefined>({
    value: valueProp,
    defaultValue,
    onChange: onChange as ((value: string | undefined) => void) | undefined,
  });

  return (
    <TabsContext.Provider
      value={{
        baseId,
        value,
        select: setValue,
        variant,
        orientation,
        dir: dir ?? "ltr",
        activationMode,
      }}
    >
      <div
        ref={ref}
        dir={dir}
        data-orientation={orientation}
        className={cn(
          styles.tabs,
          styles[color],
          orientation === "vertical" && styles.vertical,
          className,
        )}
        {...rest}
      >
        {children}
      </div>
    </TabsContext.Provider>
  );
};

/**
 * TabList: the `role="tablist"` container. Arrow keys (per orientation and
 * direction), Home and End move focus among its enabled tabs. It scrolls
 * (without a visible scrollbar) and keeps the selected tab in view after
 * async option updates and resizes, without scrolling the page or moving
 * focus.
 */
export const TabList = ({
  className,
  loop = true,
  onKeyDown,
  ref,
  ...rest
}: TabListProps) => {
  const { baseId, value, variant, orientation, dir } = useContext(TabsContext);
  const listRef = useRef<HTMLDivElement>(null);
  const mergedRef = useMergedRefs(listRef, ref);
  const [fallbackStop, setFallbackStop] = useState<string>();

  // The selected tab is the tab stop; when there is none (no value, or the
  // selected tab is disabled / missing) the first enabled tab is.
  useLayoutEffect(() => {
    const list = listRef.current;
    if (!list) return;
    const update = () => {
      const tabs = getOwnTabs(list);
      const selectedId = value === undefined ? undefined : tabId(baseId, value);
      const selectedFocusable = tabs.some(
        (tab) => tab.id === selectedId && !tab.disabled,
      );
      setFallbackStop(
        selectedFocusable ? undefined : tabs.find((tab) => !tab.disabled)?.id,
      );
    };
    update();
    // Tabs added, removed or (un)disabled without a selection change.
    const observer = new MutationObserver(update);
    observer.observe(list, {
      childList: true,
      subtree: true,
      attributes: true,
      attributeFilter: ["disabled"],
    });
    return () => observer.disconnect();
  }, [baseId, value]);

  useEffect(() => {
    const list = listRef.current;
    if (!list) return;
    const reveal = () => {
      const selected = getOwnTabs(list).find(
        (tab) => tab.getAttribute("data-state") === "active",
      );
      if (!selected) return;
      // Scroll only the list (never scrollIntoView, which scrolls the page).
      const item = selected.getBoundingClientRect();
      const box = list.getBoundingClientRect();
      if (orientation === "horizontal") {
        if (item.left < box.left) list.scrollLeft += item.left - box.left;
        else if (item.right > box.right)
          list.scrollLeft += item.right - box.right;
      } else if (item.top < box.top) list.scrollTop += item.top - box.top;
      else if (item.bottom > box.bottom)
        list.scrollTop += item.bottom - box.bottom;
    };
    reveal();
    const mutations = new MutationObserver(reveal);
    mutations.observe(list, {
      childList: true,
      subtree: true,
      characterData: true,
      attributes: true,
      attributeFilter: ["data-state"],
    });
    const resize =
      typeof ResizeObserver === "undefined"
        ? undefined
        : new ResizeObserver(reveal);
    resize?.observe(list);
    return () => {
      mutations.disconnect();
      resize?.disconnect();
    };
  }, [orientation]);

  const handleKeyDown = (event: KeyboardEvent<HTMLDivElement>) => {
    const list = event.currentTarget;
    if (event.altKey || event.ctrlKey || event.metaKey) return;
    const tabs = getOwnTabs(list);
    const currentIndex = tabs.indexOf(event.target as HTMLButtonElement);
    // Keys from nested Tabs (or other descendants) are not ours.
    if (currentIndex === -1) return;
    const next = getNextIndex({
      currentIndex,
      count: tabs.length,
      key: event.key,
      orientation,
      dir,
      loop,
      isDisabled: (index) => tabs[index].disabled,
    });
    if (next === null) return;
    event.preventDefault();
    tabs[next].focus();
  };

  return (
    <TabStopContext.Provider value={fallbackStop}>
      {/* The tabs are the focusable elements, not the tablist itself. */}
      {/* eslint-disable-next-line jsx-a11y/interactive-supports-focus */}
      <div
        ref={mergedRef}
        role="tablist"
        aria-orientation={orientation}
        data-orientation={orientation}
        className={cn(
          styles.list,
          styles[`${variant}List`],
          orientation === "vertical" && styles.verticalList,
          className,
        )}
        onKeyDown={composeEventHandlers(onKeyDown, handleKeyDown)}
        {...rest}
      />
    </TabStopContext.Provider>
  );
};

/** Tab: a `role="tab"` trigger button. */
export const Tab = ({
  value,
  className,
  children,
  color,
  disabled = false,
  onMouseDown,
  onKeyDown,
  onFocus,
  onClick,
  ref,
  ...rest
}: TabProps) => {
  const {
    baseId,
    value: selectedValue,
    select,
    variant,
    orientation,
    activationMode,
  } = useContext(TabsContext);
  const fallbackStop = useContext(TabStopContext);
  const id = tabId(baseId, value);
  const selected = value === selectedValue;
  const isTabStop = fallbackStop === undefined ? selected : fallbackStop === id;

  const handleMouseDown = (event: MouseEvent<HTMLButtonElement>) => {
    if (disabled) return;
    if (event.button === 0 && !event.ctrlKey) select(value);
    // Keep focus where it is on ctrl-click / other buttons (context menus).
    else event.preventDefault();
  };

  const handleKeyDown = (event: KeyboardEvent<HTMLButtonElement>) => {
    if (disabled || (event.key !== "Enter" && event.key !== " ")) return;
    // Handled here, so suppress the native button click activation.
    event.preventDefault();
    select(value);
  };

  const handleFocus = () => {
    if (!disabled && !selected && activationMode === "automatic") select(value);
  };

  // Assistive technologies may activate with a bare click (no mouse down).
  const handleClick = (event: MouseEvent<HTMLButtonElement>) => {
    if (!disabled && event.detail === 0) select(value);
  };

  return (
    <button
      ref={ref}
      type="button"
      role="tab"
      id={id}
      aria-selected={selected}
      aria-controls={panelId(baseId, value)}
      data-state={selected ? "active" : "inactive"}
      data-orientation={orientation}
      data-disabled={disabled ? "" : undefined}
      disabled={disabled}
      tabIndex={isTabStop ? 0 : -1}
      className={cn(
        styles.trigger,
        styles[`${variant}Trigger`],
        orientation === "vertical" && styles.verticalTrigger,
        color && styles[color],
        color && styles.colored,
        className,
      )}
      onMouseDown={composeEventHandlers(onMouseDown, handleMouseDown)}
      onKeyDown={composeEventHandlers(onKeyDown, handleKeyDown)}
      onFocus={composeEventHandlers(onFocus, handleFocus)}
      onClick={composeEventHandlers(onClick, handleClick)}
      {...rest}
    >
      {children}
    </button>
  );
};

/**
 * TabPanel: the `role="tabpanel"` content of the tab with the same value.
 * Inactive panels are unmounted unless `forceMount`, which keeps them in the
 * DOM with the `hidden` attribute.
 */
export const TabPanel = ({
  value,
  className,
  forceMount = false,
  children,
  ref,
  ...rest
}: TabPanelProps) => {
  const { baseId, value: selectedValue, orientation } = useContext(TabsContext);
  const selected = value === selectedValue;
  if (!selected && !forceMount) return null;
  return (
    <div
      ref={ref}
      role="tabpanel"
      id={panelId(baseId, value)}
      aria-labelledby={tabId(baseId, value)}
      data-state={selected ? "active" : "inactive"}
      data-orientation={orientation}
      hidden={!selected}
      tabIndex={0}
      className={cn(styles.panel, className)}
      {...rest}
    >
      {children}
    </div>
  );
};
