// apps/docs/src/docs/pages/checkbox/vue/indeterminate.vue
<script setup lang="ts">
import { computed, ref } from "vue";
import { Checkbox, VStack } from "minerva-design/vue";
const fruits = ["Apple", "Banana", "Cherry"];
const selected = ref<string[]>(["Apple"]);
const allChecked = computed(() => selected.value.length === fruits.length);
const someChecked = computed(
  () => selected.value.length > 0 && !allChecked.value,
);
function toggle(fruit: string, checked: boolean) {
  selected.value = checked
    ? [...selected.value, fruit]
    : selected.value.filter((f) => f !== fruit);
}
</script>
<template>
  <VStack :gap="2" align="start"
    ><Checkbox
      label="Select all"
      :model-value="allChecked"
      :indeterminate="someChecked"
      @change="selected = $event ? [...fruits] : []" /><VStack
      :gap="2"
      align="start"
      style="padding-left: 24px"
      ><Checkbox
        v-for="fruit in fruits"
        :key="fruit"
        :label="fruit"
        :model-value="selected.includes(fruit)"
        @change="toggle(fruit, $event)" /></VStack
  ></VStack>
</template>

// apps/docs/src/docs/pages/checkbox/native/indeterminate.tsx
import { View } from "react-native";
import { useState } from "react";
import { Checkbox } from "minerva-design/native";

const fruits = ["Apple", "Banana", "Cherry"];

export default function IndeterminateDemo() {
  const [selected, setSelected] = useState<string[]>(["Apple"]);
  const allChecked = selected.length === fruits.length;
  const someChecked = selected.length > 0 && !allChecked;

  const toggle = (fruit: string, checked: boolean) =>
    setSelected((prev) =>
      checked ? [...prev, fruit] : prev.filter((f) => f !== fruit),
    );

  return (
    <View style={{ gap: 8 }}>
      <Checkbox
        label="Select all"
        checked={allChecked}
        indeterminate={someChecked}
        onChange={(checked) => setSelected(checked ? fruits : [])}
      />
      <View
        style={{
          gap: 8,
          paddingLeft: 24,
        }}
      >
        {fruits.map((fruit) => (
          <Checkbox
            key={fruit}
            label={fruit}
            checked={selected.includes(fruit)}
            onChange={(checked) => toggle(fruit, checked)}
          />
        ))}
      </View>
    </View>
  );
}
