// packages/vue/src/components/ProgressIndicator/ProgressIndicator.vue
<script setup lang="ts">
/**
 * ProgressIndicator: the indeterminate loading indicator (spinner, circle,
 * wave, bar or dotted bar). It is a `progressbar` without a value, named by
 * `aria-label`, by its visible `label`, or by the localized "Loading". It is
 * never focusable, so it can sit inside buttons. Set `decorative` when a
 * surrounding element already announces the loading state.
 */
import { computed, useAttrs, useId, type StyleValue } from "vue";
import styles from "@react-styles/components/ProgressIndicator/progressIndicator.module.scss";
import { hooks } from "../../internal/hooks";
import {
  IconCircleNotch,
  IconSpinner,
  IconWaveSquare,
} from "../../internal/icons";
import { useI18n } from "../../config/useI18n";
import type { ProgressIndicatorProps } from "./types";

defineOptions({ name: "ProgressIndicator", inheritAttrs: false });

const props = withDefaults(defineProps<ProgressIndicatorProps>(), {
  variant: "spinner",
  size: "medium",
  color: "primary",
  label: undefined,
  decorative: false,
  width: undefined,
  full: false,
});

const slots = defineSlots<{
  /** Icon displayed before the indicator */
  icon?: () => unknown;
  /** Visible label (the `label` prop) */
  label?: () => unknown;
}>();

const attrs = useAttrs();
const { t } = useI18n();
const labelId = useId();

const hasLabel = computed(
  () =>
    !!slots.label ||
    (props.label !== undefined && props.label !== null && props.label !== ""),
);
const isBar = computed(
  () => props.variant === "bar" || props.variant === "dottedBar",
);
const classes = computed(() => [
  styles.progressIndicator,
  styles[props.color],
  props.full
    ? styles.fullWidth
    : !props.width && isBar.value
      ? styles.defaultWidth
      : undefined,
]);
const rootAttrs = computed(() => {
  const ariaLabel = attrs["aria-label"] as string | undefined;
  const a11y = props.decorative
    ? { "aria-hidden": "true" as const }
    : {
        // Indeterminate progressbar (no aria-valuenow). Not focusable: it is
        // not interactive and is often rendered inside buttons.
        role: "progressbar",
        "aria-label":
          ariaLabel ?? (hasLabel.value ? undefined : t("common.loading")),
        "aria-labelledby": ariaLabel || !hasLabel.value ? undefined : labelId,
      };
  return {
    ...a11y,
    ...attrs,
    ...(!props.decorative && { "aria-label": a11y["aria-label"] }),
    style: [
      attrs.style as StyleValue,
      props.width && !props.full ? { width: props.width } : undefined,
    ],
    ...hooks("progress", "root", {
      variant: props.variant === "dottedBar" ? "dotted-bar" : props.variant,
      size: props.size,
      color: props.color,
    }),
  };
});
const indicator = hooks("progress", "indicator");
</script>

<template>
  <div :class="classes" v-bind="rootAttrs">
    <span
      v-if="slots.icon"
      :class="styles.icon"
      v-bind="hooks('progress', 'icon')"
    >
      <slot name="icon" />
    </span>
    <IconSpinner
      v-if="variant === 'spinner'"
      :class="[styles.spinner, styles[size]]"
      aria-hidden="true"
      v-bind="indicator"
    />
    <div
      v-else-if="variant === 'bar'"
      :class="[styles.barContainer, styles[size]]"
      v-bind="indicator"
    >
      <div :class="styles.bar" />
    </div>
    <div
      v-else-if="variant === 'wave'"
      :class="[styles.waveContainer, styles[size]]"
      v-bind="indicator"
    >
      <IconWaveSquare :class="styles.wave" aria-hidden="true" />
    </div>
    <IconCircleNotch
      v-else-if="variant === 'circle'"
      :class="[styles.circle, styles[size]]"
      aria-hidden="true"
      v-bind="indicator"
    />
    <div
      v-else-if="variant === 'dottedBar'"
      :class="[styles.dottedBarContainer, styles[size]]"
      v-bind="indicator"
    >
      <div :class="styles.dottedBar" />
    </div>
    <span
      v-if="hasLabel"
      :id="labelId"
      :class="styles.label"
      v-bind="hooks('progress', 'label')"
    >
      <slot name="label">{{ label }}</slot>
    </span>
  </div>
</template>

// packages/lib-core/src/components/ProgressIndicator/progressIndicator.tsx
import React from "react";
import styles from "./progressIndicator.module.scss";
import { ProgressIndicatorProps } from "./types";
import { FaSpinner, FaWaveSquare, FaCircleNotch } from "react-icons/fa";

/**
 * ProgressIndicator component
 * @param type - The type of progress indicator (spinner, bar, wave, circle, dottedBar)
 * @param size - The size of the progress indicator (small, medium, large)
 * @param icon - Optional icon to be displayed
 * @param ariaLabel - The aria-label attribute for the progress indicator, used for accessibility
 * @param className - Additional classes to be added to the progress indicator
 * @param width - The width of the progress indicator
 * @param full - Whether the progress indicator should take full width
 * @returns A progress indicator component
 */
const ProgressIndicator: React.FC<ProgressIndicatorProps> = ({
  type = "spinner",
  size = "medium",
  icon,
  ariaLabel,
  className = "",
  width,
  full = false,
}) => {
  const indicatorMap = {
    spinner: <FaSpinner className={`${styles.spinner} ${styles[size]}`} />,
    bar: (
      <div className={`${styles.barContainer} ${styles[size]}`}>
        <div className={styles.bar}></div>
      </div>
    ),
    wave: (
      <div className={`${styles.waveContainer} ${styles[size]}`}>
        <FaWaveSquare className={styles.wave} />
      </div>
    ),
    circle: <FaCircleNotch className={`${styles.circle} ${styles[size]}`} />,
    dottedBar: (
      <div className={`${styles.dottedBarContainer} ${styles[size]}`}>
        <div className={styles.dottedBar}></div>
      </div>
    ),
  };

  const widthClass = full ? styles.fullWidth : styles.defaultWidth;

  return (
    <div
      className={`${styles.progressIndicator} ${className} ${widthClass}`}
      aria-label={ariaLabel}
      role="progressbar"
      tabIndex={0}
      style={{ width: width && !full ? width : undefined }}
    >
      {icon && <span className={styles.icon}>{icon}</span>}
      {indicatorMap[type] || null}
    </div>
  );
};

export default React.memo(ProgressIndicator);
