// packages/lib-core/src/contexts/ThemeProvider.tsx
import { useCallback, useContext, useMemo } from "react";
import { ConfigContext, ConfigProvider } from "./ConfigProvider";
import type { ThemeContextValue, ThemeProviderProps } from "./types";
import type { ThemeMode } from "@minerva/core";
import { ThemeScopeContext } from "../internal/themeScope";

/**
 * Theme + palette provider with cookie persistence: a thin preset over
 * `ConfigProvider` (one source of truth), named after the common
 * `ThemeProvider` / `useTheme` pattern.
 *
 *   <ThemeProvider defaultTheme="system" defaultPalette="editorial">
 *     <App />
 *   </ThemeProvider>
 *
 * For SSR pass the request cookies as defaults
 * (`parseThemeCookies(request.headers.get("cookie"))` from
 * `@minerva/lib-core/theme-utils`) and inline `THEME_INIT_SCRIPT` in `<head>`.
 *
 * Nested inside another provider it follows the `ConfigProvider` nesting
 * rules: it inherits what it does not set, scopes `defaultTheme` /
 * `defaultPalette` to its subtree and never touches `<html>` or the cookies.
 */
export function ThemeProvider({
  defaultTheme,
  defaultPalette,
  disableStorage = false,
  locale,
  onThemeChange,
  onPaletteChange,
  children,
}: ThemeProviderProps) {
  // Root default mode; nested providers inherit what is not set
  const isRoot = useContext(ThemeScopeContext) === null;
  return (
    <ConfigProvider
      theme={defaultTheme ?? (isRoot ? "system" : undefined)}
      palette={defaultPalette}
      persist={!disableStorage}
      locale={locale}
      onThemeChange={
        onThemeChange
          ? (theme) => {
              if (theme === "light" || theme === "dark") onThemeChange(theme);
              else if (theme === "auto" || theme === "system")
                onThemeChange("system");
            }
          : undefined
      }
      onPaletteChange={onPaletteChange}
    >
      {children}
    </ConfigProvider>
  );
}

/**
 * Theme mode and palette of the closest `ThemeProvider` / `ConfigProvider`.
 * Throws outside of one.
 */
export function useTheme(): ThemeContextValue {
  const ctx = useContext(ConfigContext);
  if (!ctx) {
    throw new Error(
      "useTheme must be used within a ThemeProvider (or ConfigProvider)",
    );
  }
  const { mode, resolvedMode, palette = null, setTheme, setPalette } = ctx;
  const setMode = useCallback(
    (next: ThemeMode) => setTheme?.(next),
    [setTheme],
  );
  const changePalette = useCallback(
    (next: ThemeContextValue["palette"]) => setPalette?.(next),
    [setPalette],
  );
  return useMemo(
    () => ({
      theme: mode ?? "system",
      resolvedTheme: resolvedMode ?? "light",
      palette,
      setTheme: setMode,
      setPalette: changePalette,
    }),
    [mode, resolvedMode, palette, setMode, changePalette],
  );
}

export default ThemeProvider;

// packages/vue/src/config/ThemeProvider.vue
<script setup lang="ts">
/**
 * ThemeProvider: a `ConfigProvider` preset for light / dark / system modes
 * with persistence (cookies) on by default, like the React `ThemeProvider`.
 * The root one defaults to the system mode; nested ones inherit what they do
 * not set.
 */
import type { Palette, ThemeMode } from "@minerva/core";
import ConfigProvider from "./ConfigProvider.vue";
import { useThemeScope } from "../internal/scope";
import type { ConfigProviderTheme, Locale } from "./context";

defineOptions({ name: "ThemeProvider" });

withDefaults(
  defineProps<{
    /** Initial mode (root default: "system") */
    defaultTheme?: ThemeMode;
    /** Initial palette */
    defaultPalette?: Palette | null;
    /** Do not persist the choice in cookies. @default false */
    disableStorage?: boolean;
    /** Language of the built-in texts */
    locale?: Locale;
  }>(),
  {
    defaultTheme: undefined,
    defaultPalette: undefined,
    disableStorage: false,
    locale: undefined,
  },
);
const emit = defineEmits<{
  /** The mode changed (light / dark / system) */
  themeChange: [theme: ThemeMode];
  paletteChange: [palette: Palette | null];
}>();
defineSlots<{ default?: () => unknown }>();

const isRoot = useThemeScope() === null;
const onThemeChange = (theme: ConfigProviderTheme) => {
  if (theme === "light" || theme === "dark") emit("themeChange", theme);
  else if (theme === "auto" || theme === "system")
    emit("themeChange", "system");
};
</script>

<template>
  <ConfigProvider
    :theme="defaultTheme ?? (isRoot ? 'system' : undefined)"
    :palette="defaultPalette"
    :persist="!disableStorage"
    :locale="locale"
    @theme-change="onThemeChange"
    @palette-change="emit('paletteChange', $event)"
  >
    <slot />
  </ConfigProvider>
</template>
