// packages/lib-web-components/src/components/pagination/pagination.ts
import {
  css,
  html,
  nothing,
  type PropertyValues,
  type TemplateResult,
} from "lit";
import { property, state } from "lit/decorators.js";
import { classMap } from "lit/directives/class-map.js";
import { repeat } from "lit/directives/repeat.js";
import styles from "@lib-core-styles/components/Pagination/pagination.module.scss?inline";
import { AriaController } from "../../internal/aria";
import { DEV, devWarn } from "../../internal/dev";
import { getDirection } from "../../internal/dom";
import {
  IconChevronLeft,
  IconChevronRight,
  IconEllipsis,
} from "../../internal/icons";
import { LocaleController } from "../../internal/locale";
import { MinervaElement, hostStyles } from "../../internal/minerva-element";
import { sharedStyles } from "../../internal/styles";

/** Kind of a pagination item (`itemRender` second argument) */
export type PaginationItemType =
  "page" | "prev" | "next" | "jump-prev" | "jump-next";
export type PaginationSize = "small" | "medium" | "large";
export type PaginationShape = "circle" | "rounded" | "square";
export type PaginationVariant = "solid" | "outline" | "ghost";

/** Content returned by the render callbacks */
export type PaginationRenderResult = string | number | Node | TemplateResult;

/** Detail of `minerva-page-change` */
export interface PaginationChangeDetail {
  page: number;
  pageSize: number;
}

/** Texts of `<minerva-pagination>`; omitted entries use the localized default */
export interface PaginationLabels {
  prev?: string;
  next?: string;
  jumpPrev?: string;
  jumpNext?: string;
  page?: (page: number) => string;
  jumpTo?: string;
  jumpToInput?: string;
  pageSize?: string;
  pageSizeOption?: (size: number) => string;
  currentPage?: string;
  total?: (total: number) => string;
  nav?: string;
}

/** Number of consecutive page buttons around the current page */
const WINDOW_SIZE = 5;
/** Pages skipped by the jump-prev / jump-next items */
const JUMP_SIZE = 5;

const rangeOf = (start: number, end: number) => {
  const out: number[] = [];
  for (let i = start; i <= end; i++) out.push(i);
  return out;
};

/** Window of page numbers centered on `current`, clamped to [1, totalPages] */
const getPageRange = (current: number, totalPages: number) => {
  let start = Math.max(1, current - Math.floor(WINDOW_SIZE / 2));
  const end = Math.min(totalPages, start + WINDOW_SIZE - 1);
  if (end - start + 1 < WINDOW_SIZE) start = Math.max(1, end - WINDOW_SIZE + 1);
  return rangeOf(start, end);
};

type CompactItem = number | "ellipsis-start" | "ellipsis-end";

/** Compact page list (lib-core's getCompactItems). */
const getCompactItems = (
  totalPages: number,
  page: number,
  siblings: number,
  boundary: number,
): CompactItem[] => {
  const totalSlots = boundary * 2 + siblings * 2 + 3;
  if (totalPages <= totalSlots) return rangeOf(1, totalPages);
  const leftSibling = Math.max(page - siblings, boundary + 1);
  const rightSibling = Math.min(page + siblings, totalPages - boundary);
  const showStartGap = leftSibling > boundary + 2;
  const showEndGap = rightSibling < totalPages - boundary - 1;
  const clusterSize = boundary + siblings * 2 + 2;
  if (!showStartGap) {
    return [
      ...rangeOf(1, clusterSize),
      "ellipsis-end",
      ...rangeOf(totalPages - boundary + 1, totalPages),
    ];
  }
  if (!showEndGap) {
    return [
      ...rangeOf(1, boundary),
      "ellipsis-start",
      ...rangeOf(totalPages - clusterSize + 1, totalPages),
    ];
  }
  return [
    ...rangeOf(1, boundary),
    "ellipsis-start",
    ...rangeOf(leftSibling, rightSibling),
    "ellipsis-end",
    ...rangeOf(totalPages - boundary + 1, totalPages),
  ];
};

/** `"10, 20 50"` <-> `[10, 20, 50]` */
const numberListConverter = {
  fromAttribute: (value: string | null) =>
    (value ?? "")
      .split(/[\s,]+/)
      .map((part) => parseInt(part, 10))
      .filter((n) => !isNaN(n) && n > 0),
  toAttribute: (value: number[]) => value.join(","),
};

interface Ripple {
  x: number;
  y: number;
  id: number;
  itemKey: string;
}

interface Item {
  key: string;
  type: PaginationItemType | "ellipsis";
  target: number;
}

/**
 * Page navigation (`<Pagination>` of lib-core): page buttons with jump
 * items or a compact list with gaps, prev / next, a simple mode with a page
 * input, a quick jumper, a native page-size select and a total. Arrow keys
 * (swapped in RTL), Home and End on the page buttons change the page and
 * move focus to it; focus never gets lost when the focused button is
 * disabled or removed by a page change.
 *
 * @summary Page navigation with jumper, page size selector and total.
 * @tag minerva-pagination
 * @slot prev-icon - Icon of the previous-page button
 * @slot next-icon - Icon of the next-page button
 * @slot jump-prev-icon - Icon of the jump-backward item
 * @slot jump-next-icon - Icon of the jump-forward item
 * @csspart base - The `<nav>` landmark
 * @csspart item - Every page / prev / next / jump button
 * @csspart total - The total text
 * @csspart jumper - The quick jumper label
 * @csspart size-changer - The page size `<select>`
 * @csspart simple-input - The page input of the simple mode
 * @fires minerva-page-change - The user changed the page or the page size (`detail: { page, pageSize }`); cancelable: `preventDefault()` keeps the current page and size (controlled pattern)
 */
export class MinervaPagination extends MinervaElement {
  static override tagName = "minerva-pagination";
  static override styles = [
    hostStyles,
    css`
      :host {
        display: block;
      }
    `,
    sharedStyles(styles),
  ];

  /** Current page (1-based) */
  @property({ type: Number, reflect: true })
  current = 1;

  /** Total number of items */
  @property({ type: Number })
  total = 0;

  /** Number of items per page */
  @property({ type: Number, reflect: true, attribute: "page-size" })
  pageSize = 10;

  /** Disables the pagination */
  @property({ type: Boolean, reflect: true })
  disabled = false;

  /** Shows an input to jump to a page */
  @property({ type: Boolean, attribute: "show-quick-jumper" })
  showQuickJumper = false;

  /** Shows a page size selector (native `<select>`) */
  @property({ type: Boolean, attribute: "show-size-changer" })
  showSizeChanger = false;

  /** Options of the page size selector (attribute: `"10,20,50"`) */
  @property({ attribute: "page-size-options", converter: numberListConverter })
  pageSizeOptions: number[] = [10, 20, 50, 100];

  /** Shows the total number of items (customize it with `totalRender`) */
  @property({ type: Boolean, attribute: "show-total" })
  showTotal = false;

  /** Custom rendering of the total; `range` is the [first, last] item of the page */
  @property({ attribute: false })
  totalRender?: (
    total: number,
    range: [number, number],
  ) => PaginationRenderResult;

  /** Custom rendering of the page, prev / next and jump items */
  @property({ attribute: false })
  itemRender?: (
    page: number,
    type: PaginationItemType,
  ) => PaginationRenderResult;

  /** Pagination size */
  @property({ reflect: true })
  size: PaginationSize = "medium";

  /** Shape of the page items */
  @property({ reflect: true })
  shape: PaginationShape = "rounded";

  /** Visual style of the page items */
  @property({ reflect: true })
  variant: PaginationVariant = "solid";

  /** Simple mode: prev / next buttons with a page input */
  @property({ type: Boolean, reflect: true })
  simple = false;

  /** Pages on each side of the current one; switches to the compact list */
  @property({ type: Number, attribute: "sibling-count" })
  siblingCount?: number;

  /** Pages always shown at both ends of the compact list */
  @property({ type: Number, attribute: "boundary-count" })
  boundaryCount?: number;

  /** Hides the prev / next buttons */
  @property({ type: Boolean, attribute: "hide-edges" })
  hideEdges = false;

  /** Replaces the page buttons with a "current / total" counter */
  @property({ type: Boolean, attribute: "hide-numbers" })
  hideNumbers = false;

  /** Adapts the layout to small screens */
  @property({ type: Boolean, reflect: true })
  responsive = false;

  /** Custom texts and accessible labels (override the localized defaults) */
  @property({ attribute: false })
  labels?: PaginationLabels;

  @state()
  private jumpValue = "";

  @state()
  private simpleDraft: string | null = null;

  @state()
  private ripples: Ripple[] = [];

  private readonly aria = new AriaController(this);
  private readonly locale = new LocaleController(this);
  private nextRippleId = 0;
  private rippleTimer: ReturnType<typeof setTimeout> | undefined;
  private restoreFocus: { mode: "active" | "if-lost"; page: number } | null =
    null;

  /** Number of pages (at least 1). */
  get totalPages(): number {
    return Math.max(
      1,
      this.pageSize > 0 ? Math.ceil(this.total / this.pageSize) : 0,
    );
  }

  override disconnectedCallback(): void {
    super.disconnectedCallback();
    clearTimeout(this.rippleTimer);
  }

  /** Asks to change the page / size: emits, then applies unless canceled. */
  private request(page: number, pageSize: number): boolean {
    const detail: PaginationChangeDetail = { page, pageSize };
    if (!this.emit("minerva-page-change", detail, { cancelable: true })) {
      return false;
    }
    this.current = page;
    this.pageSize = pageSize;
    return true;
  }

  private changePage(target: number, focus: "active" | "if-lost" = "if-lost") {
    const page = this.current;
    if (
      this.disabled ||
      target === page ||
      target < 1 ||
      target > this.totalPages
    ) {
      return;
    }
    this.restoreFocus = { mode: focus, page: target };
    this.request(target, this.pageSize);
  }

  protected override willUpdate(changed: PropertyValues<this>): void {
    if (DEV && (changed.has("current") || changed.has("total"))) {
      if (this.total > 0 && this.current > this.totalPages) {
        devWarn(
          MinervaPagination.tagName,
          `current (${this.current}) is greater than the number of pages (${this.totalPages}).`,
        );
      }
    }
  }

  protected override updated(): void {
    // Focus management after a page change (the DOM is updated)
    const request = this.restoreFocus;
    this.restoreFocus = null;
    const root = this.shadowRoot;
    if (!request || !root || request.page !== this.current) return;
    const active = root.activeElement as HTMLElement | null;
    const lost = !active || (active as HTMLButtonElement).disabled === true;
    if (request.mode === "active" || lost) {
      const target =
        root.querySelector<HTMLElement>('[aria-current="page"]') ??
        root.querySelector<HTMLElement>("button:not(:disabled), input");
      target?.focus();
    }
  }

  private handleItemClick(target: number, itemKey: string, event: MouseEvent) {
    const page = this.current;
    if (
      this.disabled ||
      target === page ||
      target < 1 ||
      target > this.totalPages
    ) {
      return;
    }
    // Ripple only for pointer clicks (keyboard-triggered clicks have detail 0)
    if (event.detail > 0) {
      const rect = (event.currentTarget as HTMLElement).getBoundingClientRect();
      this.ripples = [
        ...this.ripples,
        {
          x: event.clientX - rect.left,
          y: event.clientY - rect.top,
          id: this.nextRippleId++,
          itemKey,
        },
      ];
      clearTimeout(this.rippleTimer);
      this.rippleTimer = setTimeout(() => (this.ripples = []), 1000);
    }
    this.changePage(target);
  }

  // Arrow keys / Home / End on the page buttons (inputs keep their keys)
  private handleKeyDown = (event: KeyboardEvent) => {
    let key = event.key;
    if (
      (key === "ArrowLeft" || key === "ArrowRight") &&
      getDirection(this) === "rtl"
    ) {
      key = key === "ArrowLeft" ? "ArrowRight" : "ArrowLeft";
    }
    const page = this.current;
    const destination =
      key === "ArrowLeft"
        ? page - 1
        : key === "ArrowRight"
          ? page + 1
          : key === "Home"
            ? 1
            : key === "End"
              ? this.totalPages
              : null;
    if (destination === null) return;
    event.preventDefault();
    this.changePage(destination, "active");
  };

  private handleJump = (event: KeyboardEvent) => {
    if (event.key !== "Enter") return;
    event.preventDefault();
    const value = parseInt(this.jumpValue, 10);
    if (!isNaN(value) && value >= 1 && value <= this.totalPages) {
      this.changePage(value);
      this.jumpValue = "";
      (event.target as HTMLInputElement).value = "";
    }
  };

  private handleSizeChange = (event: Event) => {
    const select = event.target as HTMLSelectElement;
    const newSize = parseInt(select.value, 10);
    if (!this.request(1, newSize)) select.value = String(this.pageSize);
  };

  private commitSimpleDraft = () => {
    const draft = this.simpleDraft;
    if (draft === null) return;
    this.simpleDraft = null;
    const value = parseInt(draft, 10);
    if (isNaN(value)) return;
    this.changePage(Math.min(Math.max(value, 1), this.totalPages));
  };

  private label(type: PaginationItemType, target: number): string {
    const labels = this.labels;
    const t = this.locale.t;
    switch (type) {
      case "prev":
        return labels?.prev ?? t("pagination.prev");
      case "next":
        return labels?.next ?? t("pagination.next");
      case "jump-prev":
        return labels?.jumpPrev ?? t("pagination.jumpPrev");
      case "jump-next":
        return labels?.jumpNext ?? t("pagination.jumpNext");
      default:
        return labels?.page?.(target) ?? t("pagination.page", { page: target });
    }
  }

  private renderItem(item: Item) {
    const { type, target, key } = item;
    if (type === "ellipsis") {
      return html`<span class="ellipsis" aria-hidden="true">…</span>`;
    }
    const page = this.current;
    const isActive = type === "page" && target === page;
    const isDisabled =
      this.disabled ||
      (type === "prev"
        ? page <= 1
        : type === "next"
          ? page >= this.totalPages
          : false);
    let content: unknown;
    switch (type) {
      case "prev":
        content = html`<slot name="prev-icon">${IconChevronLeft}</slot>`;
        break;
      case "next":
        content = html`<slot name="next-icon">${IconChevronRight}</slot>`;
        break;
      case "jump-prev":
      case "jump-next":
        content = html`<span class="jumpWrapper"
          ><slot
            name=${type === "jump-prev" ? "jump-prev-icon" : "jump-next-icon"}
            >${IconEllipsis}</slot
          ><span class="jumpHint" aria-hidden="true"
            >${this.label(type, target)}</span
          ></span
        >`;
        break;
      default:
        content = target;
    }
    if (this.itemRender) content = this.itemRender(target, type);
    return html`<button
      type="button"
      part="item"
      data-key=${key}
      class=${classMap({
        item: true,
        active: isActive,
        disabled: isDisabled,
        prev: type === "prev",
        next: type === "next",
        jump: type === "jump-prev" || type === "jump-next",
      })}
      ?disabled=${isDisabled}
      aria-label=${this.label(type, target)}
      aria-current=${isActive ? "page" : nothing}
      @keydown=${this.handleKeyDown}
      @click=${(e: MouseEvent) => this.handleItemClick(target, key, e)}
    >
      ${content}
      ${this.ripples
        .filter((ripple) => ripple.itemKey === key)
        .map(
          (ripple) =>
            html`<span
              class="ripple"
              style="left:${ripple.x}px;top:${ripple.y}px"
              aria-hidden="true"
            ></span>`,
        )}
    </button>`;
  }

  /** Items of the page list (stable keys: the focused button survives). */
  private items(): Item[] {
    const page = this.current;
    const totalPages = this.totalPages;
    const edge = (type: "prev" | "next"): Item[] =>
      this.hideEdges
        ? []
        : [{ key: type, type, target: type === "prev" ? page - 1 : page + 1 }];
    const pageItem = (p: number): Item => ({
      key: `page-${p}`,
      type: "page",
      target: p,
    });

    if (this.siblingCount !== undefined || this.boundaryCount !== undefined) {
      const compact = getCompactItems(
        totalPages,
        page,
        Math.max(0, this.siblingCount ?? 1),
        Math.max(1, this.boundaryCount ?? 1),
      );
      return [
        ...edge("prev"),
        ...compact.map((item) =>
          typeof item === "number"
            ? pageItem(item)
            : { key: item, type: "ellipsis" as const, target: 0 },
        ),
        ...edge("next"),
      ];
    }

    const range = getPageRange(page, totalPages);
    const items: Item[] = [...edge("prev")];
    if (range.length > 0 && range[0] > 1) {
      items.push(pageItem(1));
      if (range[0] > 2) {
        items.push({
          key: "jump-prev",
          type: "jump-prev",
          target: Math.max(1, page - JUMP_SIZE),
        });
      }
    }
    range.forEach((p) => items.push(pageItem(p)));
    const last = range[range.length - 1];
    if (range.length > 0 && last < totalPages) {
      if (last < totalPages - 1) {
        items.push({
          key: "jump-next",
          type: "jump-next",
          target: Math.min(totalPages, page + JUMP_SIZE),
        });
      }
      items.push(pageItem(totalPages));
    }
    items.push(...edge("next"));
    return items;
  }

  private renderPageList() {
    const page = this.current;
    const edge = (type: "prev" | "next") =>
      this.hideEdges
        ? nothing
        : this.renderItem({
            key: type,
            type,
            target: type === "prev" ? page - 1 : page + 1,
          });
    if (this.simple) {
      return html`${edge("prev")}
        <div class="simpleInput">
          <input
            part="simple-input"
            .value=${this.simpleDraft ?? String(page)}
            ?disabled=${this.disabled}
            aria-label=${
              this.labels?.currentPage ??
              this.locale.t("pagination.currentPage")
            }
            inputmode="numeric"
            @input=${(e: Event) =>
              (this.simpleDraft = (e.target as HTMLInputElement).value)}
            @keydown=${(e: KeyboardEvent) => {
              if (e.key !== "Enter") return;
              e.preventDefault();
              this.commitSimpleDraft();
            }}
            @blur=${this.commitSimpleDraft}
          />
          <span class="simpleDivider" aria-hidden="true">/</span>
          <span>${this.totalPages}</span>
        </div>
        ${edge("next")}`;
    }
    if (this.hideNumbers) {
      return html`${edge("prev")}
        <span class="counter" aria-live="polite"
          >${page} / ${this.totalPages}</span
        >
        ${edge("next")}`;
    }
    return repeat(
      this.items(),
      (item) => item.key,
      (item) => this.renderItem(item),
    );
  }

  protected override render() {
    const t = this.locale.t;
    const labels = this.labels;
    const total = this.total;
    const pageSize = this.pageSize;
    const shownPage = Math.min(Math.max(1, this.current), this.totalPages);
    const visibleRange: [number, number] =
      total > 0
        ? [
            (shownPage - 1) * pageSize + 1,
            Math.min(shownPage * pageSize, total),
          ]
        : [0, 0];
    const options = this.pageSizeOptions.includes(pageSize)
      ? this.pageSizeOptions
      : [...this.pageSizeOptions, pageSize].sort((a, b) => a - b);
    const sizeOptionLabel = (size: number) =>
      labels?.pageSizeOption?.(size) ??
      t("pagination.pageSizeOption", { size });

    return html`<nav
      part="base"
      aria-label=${this.aria.label ?? labels?.nav ?? t("pagination.nav")}
      class=${classMap({
        pagination: true,
        disabled: this.disabled,
        small: this.size === "small",
        large: this.size === "large",
        circle: this.shape === "circle",
        square: this.shape === "square",
        [this.variant]: true,
        responsive: this.responsive,
      })}
    >
      ${
        this.showTotal
          ? html`<div
              part="total"
              class="total"
              aria-live="polite"
              aria-atomic="true"
            >
              ${
                this.totalRender
                  ? this.totalRender(total, visibleRange)
                  : (labels?.total?.(total) ?? t("pagination.total", { total }))
              }
            </div>`
          : nothing
      }
      ${this.renderPageList()}
      ${
        this.showQuickJumper
          ? html`<label part="jumper" class="jumper">
              ${labels?.jumpTo ?? t("pagination.jumpTo")}
              <input
                .value=${this.jumpValue}
                ?disabled=${this.disabled}
                inputmode="numeric"
                aria-label=${labels?.jumpToInput ?? t("pagination.jumpToInput")}
                @input=${(e: Event) =>
                  (this.jumpValue = (e.target as HTMLInputElement).value)}
                @keydown=${this.handleJump}
              />
            </label>`
          : nothing
      }
      ${
        this.showSizeChanger
          ? html`<div class="sizeChanger">
              <select
                part="size-changer"
                ?disabled=${this.disabled}
                aria-label=${labels?.pageSize ?? t("pagination.pageSize")}
                @change=${this.handleSizeChange}
              >
                ${options.map(
                  (option) =>
                    html`<option
                      value=${option}
                      .selected=${option === pageSize}
                    >
                      ${sizeOptionLabel(option)}
                    </option>`,
                )}
              </select>
            </div>`
          : nothing
      }
    </nav>`;
  }
}

declare global {
  interface HTMLElementTagNameMap {
    "minerva-pagination": MinervaPagination;
  }
}

// packages/lib-core/src/components/Pagination/Pagination.tsx
import React, {
  useCallback,
  useEffect,
  useRef,
  useState,
  type KeyboardEvent,
  type MouseEvent,
} from "react";
import {
  IconChevronLeft,
  IconChevronRight,
  IconEllipsis,
} from "../../internal/icons";
import { cn } from "../../utils/cn";
import type { PaginationProps } from "./types";
import { logicalArrowKey } from "../../internal/direction";
import styles from "./pagination.module.scss";
import useI18n from "../../hooks/useI18n";
import { useControllableState } from "../../internal/useControllableState";
import { useMergedRefs } from "../../internal/mergeRefs";

type PaginationItemType = "page" | "prev" | "next" | "jump-prev" | "jump-next";

/** Number of consecutive page buttons around the current page */
const WINDOW_SIZE = 5;
/** Pages skipped by the jump-prev / jump-next items */
const JUMP_SIZE = 5;

const DEFAULT_ICONS = {
  prev: <IconChevronLeft aria-hidden="true" />,
  next: <IconChevronRight aria-hidden="true" />,
  jumpPrev: <IconEllipsis aria-hidden="true" />,
  jumpNext: <IconEllipsis aria-hidden="true" />,
};

interface Ripple {
  x: number;
  y: number;
  id: number;
  itemKey: string;
}

/** Window of page numbers centered on `current`, clamped to [1, totalPages] */
const getPageRange = (current: number, totalPages: number) => {
  let start = Math.max(1, current - Math.floor(WINDOW_SIZE / 2));
  const end = Math.min(totalPages, start + WINDOW_SIZE - 1);
  if (end - start + 1 < WINDOW_SIZE) {
    start = Math.max(1, end - WINDOW_SIZE + 1);
  }
  const range: number[] = [];
  for (let i = start; i <= end; i++) range.push(i);
  return range;
};

type CompactItem = number | "ellipsis-start" | "ellipsis-end";

const rangeOf = (start: number, end: number) => {
  const out: number[] = [];
  for (let i = start; i <= end; i++) out.push(i);
  return out;
};

/**
 * Compact page list: `boundary` pages at each end, `siblings` pages on each
 * side of the current page and "…" gaps. Every page is listed when they fit.
 */
const getCompactItems = (
  totalPages: number,
  page: number,
  siblings: number,
  boundary: number,
): CompactItem[] => {
  // boundaries + current and its siblings + two gap slots
  const totalSlots = boundary * 2 + siblings * 2 + 3;
  if (totalPages <= totalSlots) return rangeOf(1, totalPages);

  const leftSibling = Math.max(page - siblings, boundary + 1);
  const rightSibling = Math.min(page + siblings, totalPages - boundary);
  // a gap of a single page is shown as that page instead of "…"
  const showStartGap = leftSibling > boundary + 2;
  const showEndGap = rightSibling < totalPages - boundary - 1;
  const clusterSize = boundary + siblings * 2 + 2;

  if (!showStartGap) {
    return [
      ...rangeOf(1, clusterSize),
      "ellipsis-end",
      ...rangeOf(totalPages - boundary + 1, totalPages),
    ];
  }
  if (!showEndGap) {
    return [
      ...rangeOf(1, boundary),
      "ellipsis-start",
      ...rangeOf(totalPages - clusterSize + 1, totalPages),
    ];
  }
  return [
    ...rangeOf(1, boundary),
    "ellipsis-start",
    ...rangeOf(leftSibling, rightSibling),
    "ellipsis-end",
    ...rangeOf(totalPages - boundary + 1, totalPages),
  ];
};

/**
 * Pagination 分页组件
 *
 * @description 用于数据分页展示的导航组件,支持多种样式和交互方式
 *
 * @param current - 当前页（受控）
 * @param defaultCurrent - 默认当前页（非受控）
 * @param total - 总数
 * @param pageSize - 每页显示数量（受控）
 * @param defaultPageSize - 默认每页显示数量（非受控）
 * @param onChange - 页码或每页数量改变回调
 * @param disabled - 是否禁用
 * @param showQuickJumper - 是否显示快速跳转
 * @param showSizeChanger - 是否显示页码大小改变
 * @param pageSizeOptions - 页码大小选项
 * @param itemRender - 页码渲染函数
 * @param className - 组件类名
 * @param style - 组件样式
 * @param showTotal - 是否显示总数
 * @param totalRender - 总数渲染函数
 * @param size - 组件尺寸
 * @param shape - 组件形状
 * @param variant - 组件样式
 * @param simple - 是否简单模式
 * @param responsive - 是否响应式
 * @param icons - 组件图标
 * @param siblingCount - 紧凑页码列表中当前页两侧的页数
 * @param boundaryCount - 紧凑页码列表首尾保留的页数
 * @param hideEdges - 隐藏上一页 / 下一页
 * @param hideNumbers - 用「当前 / 总数」计数代替页码按钮
 * @param labels - 自定义文案（覆盖本地化的默认文案）
 * @param ref - 根 <nav> 元素的 ref
 */
const Pagination = ({
  current,
  defaultCurrent = 1,
  total = 0,
  pageSize,
  defaultPageSize = 10,
  onChange,
  disabled = false,
  showQuickJumper = false,
  showSizeChanger = false,
  pageSizeOptions = [10, 20, 50, 100],
  itemRender,
  className,
  style,
  showTotal = false,
  totalRender,
  size = "medium",
  shape = "rounded",
  variant = "solid",
  simple = false,
  responsive = false,
  icons,
  labels,
  siblingCount,
  boundaryCount,
  hideEdges = false,
  hideNumbers = false,
  ref,
  ...rest
}: PaginationProps) => {
  const { t } = useI18n();
  const navRef = useRef<HTMLElement>(null);
  const mergedRef = useMergedRefs(navRef, ref);

  const [page, setPage] = useControllableState({
    value: current,
    defaultValue: defaultCurrent,
  });
  const [currentPageSize, setPageSize] = useControllableState({
    value: pageSize,
    defaultValue: defaultPageSize,
  });

  const [jumpValue, setJumpValue] = useState("");
  // Draft text of the simple-mode page input while the user is typing
  // (null when not editing, so the input mirrors the current page)
  const [simpleDraft, setSimpleDraft] = useState<string | null>(null);
  const [ripples, setRipples] = useState<Ripple[]>([]);
  const nextRippleId = useRef(0);
  // Set when a page change should move focus to the active page button
  // (keyboard navigation, or the focused button became disabled / removed)
  const restoreFocus = useRef<{
    mode: "active" | "if-lost";
    page: number;
  } | null>(null);

  const mergedIcons = { ...DEFAULT_ICONS, ...icons };
  // There is always at least one (possibly empty) page
  const totalPages = Math.max(
    1,
    currentPageSize > 0 ? Math.ceil(total / currentPageSize) : 0,
  );

  const changePage = useCallback(
    (target: number, focus: "active" | "if-lost" = "if-lost") => {
      if (disabled || target === page || target < 1 || target > totalPages) {
        return;
      }
      restoreFocus.current = { mode: focus, page: target };
      setPage(target);
      onChange?.(target, currentPageSize);
    },
    [disabled, page, totalPages, setPage, onChange, currentPageSize],
  );

  // Focus management after a page change (runs after the DOM is updated)
  useEffect(() => {
    const request = restoreFocus.current;
    restoreFocus.current = null;
    const nav = navRef.current;
    // Skip when a controlled parent did not accept the change
    if (!request || !nav || request.page !== page) return;
    const active = nav.ownerDocument.activeElement as HTMLElement | null;
    const lost =
      !active ||
      !nav.contains(active) ||
      (active as HTMLButtonElement).disabled === true;
    if (request.mode === "active" || lost) {
      const target =
        nav.querySelector<HTMLElement>('[aria-current="page"]') ??
        nav.querySelector<HTMLElement>("button:not(:disabled), input");
      target?.focus();
    }
  });

  const handleItemClick = (
    target: number,
    itemKey: string,
    event: MouseEvent<HTMLButtonElement>,
  ) => {
    if (disabled || target === page || target < 1 || target > totalPages) {
      return;
    }
    // Ripple only for pointer clicks (keyboard-triggered clicks have detail 0)
    if (event.detail > 0) {
      const rect = event.currentTarget.getBoundingClientRect();
      const ripple: Ripple = {
        x: event.clientX - rect.left,
        y: event.clientY - rect.top,
        id: nextRippleId.current++,
        itemKey,
      };
      setRipples((prev) => [...prev, ripple]);
    }
    changePage(target);
  };

  // 清理水波纹效果
  useEffect(() => {
    if (ripples.length === 0) return;
    const timer = setTimeout(() => setRipples([]), 1000);
    return () => clearTimeout(timer);
  }, [ripples]);

  // 快速跳转
  const handleJump = (e: KeyboardEvent<HTMLInputElement>) => {
    if (e.key !== "Enter") return;
    // Enter in a text input would implicitly submit an enclosing form
    e.preventDefault();
    const value = parseInt(jumpValue, 10);
    if (!isNaN(value) && value >= 1 && value <= totalPages) {
      changePage(value);
      setJumpValue("");
    }
  };

  // 页码大小改变: 回到第一页
  const handleSizeChange = (value: string) => {
    const newSize = parseInt(value, 10);
    setPageSize(newSize);
    setPage(1);
    onChange?.(1, newSize);
  };

  // 提交简单模式输入框的页码: 有效值夹取到合法范围, 无效值还原
  const commitSimpleDraft = () => {
    if (simpleDraft === null) return;
    setSimpleDraft(null);
    const value = parseInt(simpleDraft, 10);
    if (isNaN(value) || totalPages < 1) return;
    changePage(Math.min(Math.max(value, 1), totalPages));
  };

  const itemLabel = (type: PaginationItemType, target: number) => {
    switch (type) {
      case "prev":
        return labels?.prev ?? t("pagination.prev");
      case "next":
        return labels?.next ?? t("pagination.next");
      case "jump-prev":
        return labels?.jumpPrev ?? t("pagination.jumpPrev");
      case "jump-next":
        return labels?.jumpNext ?? t("pagination.jumpNext");
      default:
        return labels?.page?.(target) ?? t("pagination.page", { page: target });
    }
  };

  const renderItem = (target: number, type: PaginationItemType) => {
    const isActive = type === "page" && target === page;
    const isDisabled =
      disabled ||
      (type === "prev"
        ? page <= 1
        : type === "next"
          ? page >= totalPages
          : false);
    // Stable keys: the focused button must survive page changes
    const itemKey = type === "page" ? `page-${target}` : type;

    let content: React.ReactNode;
    switch (type) {
      case "prev":
        content = mergedIcons.prev;
        break;
      case "next":
        content = mergedIcons.next;
        break;
      case "jump-prev":
      case "jump-next":
        content = (
          <span className={styles.jumpWrapper}>
            {type === "jump-prev" ? mergedIcons.jumpPrev : mergedIcons.jumpNext}
            <span className={styles.jumpHint} aria-hidden="true">
              {itemLabel(type, target)}
            </span>
          </span>
        );
        break;
      default:
        content = target;
    }
    if (itemRender) {
      content = itemRender(target, type);
    }

    return (
      <button
        key={itemKey}
        type="button"
        onKeyDown={handleKeyDown}
        className={cn(styles.item, {
          [styles.active]: isActive,
          [styles.disabled]: isDisabled,
          [styles.prev]: type === "prev",
          [styles.next]: type === "next",
          [styles.jump]: type === "jump-prev" || type === "jump-next",
        })}
        disabled={isDisabled}
        onClick={(e) => handleItemClick(target, itemKey, e)}
        aria-label={itemLabel(type, target)}
        aria-current={isActive ? "page" : undefined}
      >
        {content}
        {ripples
          .filter((ripple) => ripple.itemKey === itemKey)
          .map((ripple) => (
            <span
              key={ripple.id}
              className={styles.ripple}
              style={{ left: ripple.x, top: ripple.y }}
              aria-hidden="true"
            />
          ))}
      </button>
    );
  };

  const renderEdge = (type: "prev" | "next") =>
    hideEdges ? null : renderItem(type === "prev" ? page - 1 : page + 1, type);

  const renderPageList = () => {
    if (simple) {
      return (
        <>
          {renderEdge("prev")}
          <div className={styles.simpleInput}>
            <input
              value={simpleDraft ?? String(page)}
              disabled={disabled}
              aria-label={labels?.currentPage ?? t("pagination.currentPage")}
              inputMode="numeric"
              onChange={(e) => setSimpleDraft(e.target.value)}
              onKeyDown={(e) => {
                if (e.key !== "Enter") return;
                // Do not implicitly submit an enclosing form
                e.preventDefault();
                commitSimpleDraft();
              }}
              onBlur={commitSimpleDraft}
            />
            <span className={styles.simpleDivider} aria-hidden="true">
              /
            </span>
            <span>{totalPages}</span>
          </div>
          {renderEdge("next")}
        </>
      );
    }

    if (hideNumbers) {
      return (
        <>
          {renderEdge("prev")}
          <span className={styles.counter} aria-live="polite">
            {page} / {totalPages}
          </span>
          {renderEdge("next")}
        </>
      );
    }

    if (siblingCount !== undefined || boundaryCount !== undefined) {
      const compact = getCompactItems(
        totalPages,
        page,
        Math.max(0, siblingCount ?? 1),
        Math.max(1, boundaryCount ?? 1),
      );
      return [
        renderEdge("prev"),
        ...compact.map((item) =>
          typeof item === "number" ? (
            renderItem(item, "page")
          ) : (
            <span key={item} className={styles.ellipsis} aria-hidden="true">
              …
            </span>
          ),
        ),
        renderEdge("next"),
      ];
    }

    const range = getPageRange(page, totalPages);
    const items: React.ReactNode[] = [renderEdge("prev")];

    if (range.length > 0 && range[0] > 1) {
      items.push(renderItem(1, "page"));
      if (range[0] > 2) {
        items.push(renderItem(Math.max(1, page - JUMP_SIZE), "jump-prev"));
      }
    }

    range.forEach((p) => items.push(renderItem(p, "page")));

    const last = range[range.length - 1];
    if (range.length > 0 && last < totalPages) {
      if (last < totalPages - 1) {
        items.push(
          renderItem(Math.min(totalPages, page + JUMP_SIZE), "jump-next"),
        );
      }
      items.push(renderItem(totalPages, "page"));
    }

    items.push(renderEdge("next"));
    return items;
  };

  // 键盘导航 (on the page buttons only, so inputs / selects keep their own
  // keys): 方向键 / Home / End, 焦点随之移动到当前页
  // (disabled pagination: the buttons are disabled and receive no keys)
  const handleKeyDown = (e: KeyboardEvent<HTMLElement>) => {
    // RTL: the previous page is on the right, so ArrowRight goes back.
    const key = logicalArrowKey(e.key, e.currentTarget);
    const destination =
      key === "ArrowLeft"
        ? page - 1
        : key === "ArrowRight"
          ? page + 1
          : e.key === "Home"
            ? 1
            : e.key === "End"
              ? totalPages
              : null;
    if (destination === null) return;
    e.preventDefault();
    changePage(destination, "active");
  };

  const shownPage = Math.min(Math.max(1, page), totalPages);
  const visibleRange: [number, number] =
    total > 0
      ? [
          (shownPage - 1) * currentPageSize + 1,
          Math.min(shownPage * currentPageSize, total),
        ]
      : [0, 0];

  const sizeLabel = labels?.pageSize ?? t("pagination.pageSize");
  const sizeOptionLabel = (size: number) =>
    labels?.pageSizeOption?.(size) ?? t("pagination.pageSizeOption", { size });

  const sizeOptions = pageSizeOptions.includes(currentPageSize)
    ? pageSizeOptions
    : [...pageSizeOptions, currentPageSize].sort((a, b) => a - b);

  const componentClassName = cn(
    styles.pagination,
    disabled && styles.disabled,
    size === "small" && styles.small,
    size === "large" && styles.large,
    shape === "circle" && styles.circle,
    shape === "square" && styles.square,
    styles[variant],
    responsive && styles.responsive,
    className,
  );

  return (
    <nav
      aria-label={labels?.nav ?? t("pagination.nav")}
      {...rest}
      ref={mergedRef}
      className={componentClassName}
      style={style}
    >
      {showTotal !== false && (
        <div className={styles.total} aria-live="polite" aria-atomic="true">
          {typeof showTotal === "function"
            ? showTotal(total, visibleRange)
            : totalRender
              ? totalRender(total, visibleRange)
              : (labels?.total?.(total) ?? t("pagination.total", { total }))}
        </div>
      )}

      {renderPageList()}

      {showQuickJumper && (
        <label className={styles.jumper}>
          {labels?.jumpTo ?? t("pagination.jumpTo")}
          <input
            value={jumpValue}
            disabled={disabled}
            inputMode="numeric"
            onChange={(e) => setJumpValue(e.target.value)}
            onKeyDown={handleJump}
            aria-label={labels?.jumpToInput ?? t("pagination.jumpToInput")}
          />
        </label>
      )}

      {showSizeChanger && (
        <div className={styles.sizeChanger}>
          <select
            value={currentPageSize}
            disabled={disabled}
            onChange={(e) => handleSizeChange(e.target.value)}
            aria-label={sizeLabel}
          >
            {sizeOptions.map((option) => (
              <option key={option} value={option}>
                {sizeOptionLabel(option)}
              </option>
            ))}
          </select>
        </div>
      )}
    </nav>
  );
};

export default Pagination;
