// packages/angular/src/components/time-picker/time-picker.ts
import {
  ChangeDetectionStrategy,
  Component,
  ElementRef,
  ViewEncapsulation,
  afterRenderEffect,
  booleanAttribute,
  computed,
  inject,
  input,
  model,
  numberAttribute,
  signal,
  untracked,
  viewChild,
} from "@angular/core";
import {
  cn,
  formatHasSeconds,
  formatTime,
  parseTimeInput,
  resolveTimeFormat,
  startOfToday,
} from "@minerva/core";
import {
  getDirection,
  getTabbables,
  parsePlacement,
  type Placement,
  type ReadingDirection,
} from "@minerva/dom";
import { injectScope } from "../../config/scope";
import { classOf } from "../../internal/classes";
import {
  MnFormValueControl,
  fieldWiring,
  injectFormField,
  provideValueAccessor,
} from "../../internal/forms";
import { MnHook } from "../../internal/hooks";
import { MnIcon } from "../../internal/icon";
import { anchoredPosition, overlayLayer } from "../../internal/overlay";
import { MnPortal } from "../../internal/portal";
import {
  iconButtonStyles as ib,
  inputStyles as is,
  timePickerStyles as s,
} from "../../internal/styles";
import {
  MnTimePickerPanel,
  type TimePickerPanelChange,
} from "./time-picker-panel";

export type TimePickerSize = "small" | "medium" | "large";

const optionalBoolean = (value: unknown): boolean | undefined =>
  value === undefined || value === null ? undefined : booleanAttribute(value);

/**
 * The tabbable element before / after `anchor` in `container`, in document
 * order (where Tab / Shift+Tab pressed on `anchor` would go).
 */
function adjacentTabbable(
  anchor: Element,
  container: Element,
  backwards: boolean,
): HTMLElement | null {
  const tabbables = getTabbables(container).filter(
    (el) => el !== anchor && !anchor.contains(el) && !el.contains(anchor),
  );
  const follows = (el: Element) =>
    !!(anchor.compareDocumentPosition(el) & Node.DOCUMENT_POSITION_FOLLOWING);
  return backwards
    ? ([...tabbables].reverse().find((el) => !follows(el)) ?? null)
    : (tabbables.find(follows) ?? null);
}

/** Whether Tab (Shift+Tab: `backwards`) on `focused` would leave `panel` */
function tabLeavesPanel(
  panel: HTMLElement,
  focused: Element | null,
  backwards: boolean,
): boolean {
  if (!focused || !panel.contains(focused)) return false;
  const tabbables = getTabbables(panel);
  if (tabbables.length === 0) return true;
  if (backwards) return focused === panel || focused === tabbables[0];
  return focused === tabbables[tabbables.length - 1];
}

/**
 * TimePicker: type a time or pick hours / minutes / seconds (/ AM-PM) from a
 * popup panel. Clicking the input toggles the panel, ArrowDown opens it and
 * moves focus into it, Escape closes it (focus returns to the input).
 * Same DOM, classes and styling hooks as React's TimePicker (the host
 * element is the field root; the input box and the clear button render the
 * DOM and hooks of React's Input / IconButton). The panel renders nothing
 * on the server.
 *
 * Two-way binding: `[(value)]` (a `Date`, `null` when cleared), `ngModel` or
 * a Reactive Forms control; `[(open)]` for the panel. Inside
 * `<mn-form-control>` it takes the field's id, label, description, invalid /
 * required / read-only / disabled states (explicit inputs win).
 *
 * @example
 * <mn-time-picker label="Start" [(value)]="start" format="HH:mm" />
 * <mn-time-picker formControlName="time" use12Hours format="hh:mm a" />
 */
@Component({
  selector: "mn-time-picker",
  exportAs: "mnTimePicker",
  imports: [MnHook, MnIcon, MnPortal, MnTimePickerPanel],
  encapsulation: ViewEncapsulation.None,
  changeDetection: ChangeDetectionStrategy.OnPush,
  providers: [provideValueAccessor(() => MnTimePicker)],
  host: {
    "[class]": "s.timePicker",
    "[attr.id]": "null",
    "[attr.aria-label]": "null",
    "[attr.aria-labelledby]": "null",
    "[attr.aria-describedby]": "null",
    "[attr.name]": "null",
    "[attr.placeholder]": "null",
    "[attr.label]": "null",
    "[attr.disabled]": "null",
    "[attr.readonly]": "null",
    "[attr.required]": "null",
    "[attr.invalid]": "null",
    "[attr.data-minerva]": '"time-picker"',
    "[attr.data-part]": '"root"',
    "[attr.data-state]": 'isOpen() ? "open" : "closed"',
    "[attr.data-disabled]": 'isDisabled() ? "" : null',
    "[attr.data-readonly]": 'isReadOnly() ? "" : null',
    "[attr.data-invalid]": 'isInvalid() ? "" : null',
    "[attr.data-size]": "size()",
    "(click)": "onRootClick($event)",
  },
  template: `
    <div
      [class]="inputRootClass()"
      data-component="input"
      mnHook="input"
      [mnStates]="{
        disabled: isDisabled(),
        invalid: isInvalid(),
        readonly: isReadOnly(),
        required: isRequired(),
        size: size(),
        variant: 'outline',
      }"
    >
      <input
        #input
        type="text"
        [class]="is.field"
        [value]="displayValue()"
        [attr.placeholder]="placeholder() ?? scope.t('timePicker.placeholder')"
        [attr.id]="field.id()"
        [attr.aria-label]="accessibleName()"
        [attr.aria-labelledby]="labelledBy()"
        [attr.aria-describedby]="field.describedBy()"
        [attr.aria-invalid]="isInvalid() ? 'true' : null"
        [attr.aria-readonly]="isReadOnly() ? 'true' : null"
        [required]="isRequired()"
        [readOnly]="isReadOnly()"
        [attr.name]="name()"
        [disabled]="isDisabled()"
        (input)="onInput(input.value)"
        (blur)="onBlur()"
        (keydown)="onInputKeyDown($event)"
        mnHook="input"
        mnPart="input"
      />
      <span [class]="suffixClass" mnHook="input" mnPart="suffix">
        @if (showClear()) {
          <button
            type="button"
            [class]="clearClass"
            tabindex="0"
            [attr.aria-label]="scope.t('timePicker.clear')"
            (click)="clear()"
            mnHook="icon-button"
            [mnStates]="clearStates"
          >
            <span
              [class]="ib.glyph"
              aria-hidden="true"
              mnHook="icon-button"
              mnPart="icon"
            >
              <svg mnIcon="X"></svg>
            </span>
          </button>
        } @else {
          <span
            [class]="s.clockIcon"
            aria-hidden="true"
            mnHook="time-picker"
            mnPart="icon"
          >
            <svg mnIcon="Clock"></svg>
          </span>
        }
      </span>
    </div>
    @if (isOpen()) {
      <div
        *mnPortal
        #panel
        role="dialog"
        tabindex="-1"
        [attr.dir]="panelDir() ?? null"
        [attr.aria-label]="accessibleName()"
        [attr.aria-labelledby]="labelledBy()"
        [class]="s.popup"
        (keydown)="onPanelKeyDown($event)"
        mnHook="time-picker"
        mnPart="content"
        [mnStates]="contentStates()"
      >
        <mn-time-picker-panel
          [value]="panelValue()"
          [hasValue]="current() !== null"
          [use12Hours]="use12Hours()"
          [showSecond]="showSeconds()"
          [hourStep]="hourStep()"
          [minuteStep]="minuteStep()"
          [secondStep]="secondStep()"
          [minTime]="minTime()"
          [maxTime]="maxTime()"
          [visible]="isOpen()"
          [focusOnOpen]="focusPanelOnOpen()"
          (timeChange)="onTimeChange($event)"
        />
      </div>
    }
  `,
})
export class MnTimePicker extends MnFormValueControl<Date | null> {
  /**
   * Selected time (two-way: `[(value)]`); `null` means "no time". Not bound:
   * `defaultValue`.
   */
  readonly value = model<Date | null | undefined>(undefined);
  /** Initially selected time (when `value` is not bound) */
  readonly defaultValue = input<Date | null | undefined>(undefined);
  /** Whether the panel is open (two-way: `[(open)]`) @default false */
  readonly open = model(false);
  /**
   * Display format: "HH:mm:ss", "HH:mm", "hh:mm:ss a" or "hh:mm a"
   * @default "HH:mm:ss"
   */
  readonly format = input("HH:mm:ss");
  /** Uses a 12-hour clock with an AM/PM column @default false */
  readonly use12Hours = input(false, { transform: booleanAttribute });
  /** Placeholder of the input @default "Select time" (localized) */
  readonly placeholder = input<string | undefined>(undefined);
  /** Visible label of the input; without it the input is labelled "Time" (localized) */
  readonly label = input<string | undefined>(undefined);
  /** Accessible label of the input when no visible label is shown */
  readonly ariaLabel = input<string | undefined>(undefined, {
    alias: "aria-label",
  });
  /**
   * Id(s) of the element(s) labelling the input; inside a FormControl it
   * defaults to the FormLabel (unless `label` / `aria-label` is set)
   */
  readonly ariaLabelledby = input<string | undefined>(undefined, {
    alias: "aria-labelledby",
  });
  /**
   * Id(s) of the element(s) describing the input; merged with the helper /
   * error text of an enclosing FormControl
   */
  readonly ariaDescribedby = input<string | undefined>(undefined, {
    alias: "aria-describedby",
  });
  /** Id of the input; defaults to the id of an enclosing FormControl */
  readonly id = input<string | undefined>(undefined);
  /** Marks the input as required; defaults to the enclosing FormControl's state */
  readonly required = input<boolean | undefined, unknown>(undefined, {
    transform: optionalBoolean,
  });
  /**
   * Shows the value without allowing changes (typing, panel, clearing);
   * defaults to the enclosing FormControl's state
   */
  readonly readOnly = input<boolean | undefined, unknown>(undefined, {
    transform: optionalBoolean,
  });
  /**
   * Marks the input as invalid (aria-invalid); defaults to the enclosing
   * FormControl's state (and to an invalid, touched form control)
   */
  readonly invalid = input<boolean | undefined, unknown>(undefined, {
    transform: optionalBoolean,
  });
  /** Name of the input @default "time-picker" */
  readonly name = input("time-picker");
  /**
   * Disables the picker; defaults to the enclosing FormControl's (or the
   * form's) state @default false
   */
  readonly disabled = input<boolean | undefined, unknown>(undefined, {
    transform: optionalBoolean,
  });
  /** Allows clearing the value with the suffix button @default true */
  readonly clearable = input(true, { transform: booleanAttribute });
  /** Size of the input and panel @default "medium" */
  readonly size = input<TimePickerSize>("medium");
  /** Earliest selectable time; earlier options are disabled */
  readonly minTime = input<Date | undefined>(undefined);
  /** Latest selectable time; later options are disabled */
  readonly maxTime = input<Date | undefined>(undefined);
  /**
   * Shows seconds. `false` also removes the seconds token from `format`
   * ("HH:mm:ss" -> "HH:mm"): the format in use is the single source of truth
   * of the seconds column, the displayed text and parsing
   * @default true
   */
  readonly showSecond = input(true, { transform: booleanAttribute });
  /** Interval between hour options @default 1 */
  readonly hourStep = input(1, { transform: numberAttribute });
  /** Interval between minute options @default 1 */
  readonly minuteStep = input(1, { transform: numberAttribute });
  /** Interval between second options @default 1 */
  readonly secondStep = input(1, { transform: numberAttribute });

  protected readonly s = s;
  protected readonly is = is;
  protected readonly ib = ib;
  protected readonly scope = injectScope();
  private readonly fieldContext = injectFormField();
  protected readonly field = fieldWiring(this.fieldContext, {
    id: () => this.id(),
    describedBy: () => this.ariaDescribedby(),
  });
  private readonly host = inject<ElementRef<HTMLElement>>(ElementRef);
  private readonly inputRef =
    viewChild.required<ElementRef<HTMLInputElement>>("input");
  private readonly panelRef = viewChild<ElementRef<HTMLDivElement>>("panel");

  protected readonly isDisabled = computed(
    () =>
      this.disabled() ??
      (this.formDisabled() || (this.fieldContext?.disabled() ?? false)),
  );
  protected readonly isReadOnly = computed(
    () => this.readOnly() ?? this.fieldContext?.readOnly() ?? false,
  );
  protected readonly isRequired = computed(
    () => this.required() ?? this.fieldContext?.required() ?? false,
  );
  protected readonly isInvalid = computed(
    () =>
      this.invalid() ??
      ((this.fieldContext?.invalid() ?? false) || this.controlInvalid()),
  );
  protected readonly isOpen = computed(
    () => this.open() && !this.isDisabled() && !this.isReadOnly(),
  );
  protected readonly accessibleName = computed(
    () => this.label() ?? this.ariaLabel() ?? this.scope.t("timePicker.label"),
  );
  protected readonly labelledBy = computed(
    () =>
      this.ariaLabelledby() ??
      (this.fieldContext && !this.label() && !this.ariaLabel()
        ? this.fieldContext.labelId()
        : null),
  );

  /** The format in use decides the seconds column (one source of truth) */
  private readonly resolvedFormat = computed(() =>
    resolveTimeFormat(this.format(), this.showSecond()),
  );
  protected readonly showSeconds = computed(() =>
    formatHasSeconds(this.resolvedFormat()),
  );
  protected readonly current = computed<Date | null>(() => {
    const value = this.value();
    return value === undefined ? (this.defaultValue() ?? null) : value;
  });
  protected readonly panelValue = computed(
    () => this.current() ?? startOfToday(),
  );
  /** Text being typed; `null` shows the formatted value */
  private readonly draft = signal<string | null>(null);
  protected readonly displayValue = computed(() => {
    const draft = this.draft();
    if (draft !== null) return draft;
    const current = this.current();
    return current ? formatTime(current, this.resolvedFormat()) : "";
  });
  protected readonly showClear = computed(
    () =>
      this.clearable() &&
      !!this.current() &&
      !this.isDisabled() &&
      !this.isReadOnly(),
  );
  /** Opened from the keyboard: the panel moves focus into its first column */
  protected readonly focusPanelOnOpen = signal(false);
  private readonly placement = signal<Placement>("bottom-start");
  protected readonly panelDir = signal<ReadingDirection | undefined>(undefined);

  protected readonly inputRootClass = computed(() =>
    cn(
      is.root,
      is.outline,
      classOf(is, this.size()),
      this.isInvalid() && is.invalid,
      this.isDisabled() && is.disabled,
    ),
  );
  protected readonly suffixClass = cn(is.addon, is.end);
  protected readonly clearClass = cn(
    ib.iconButton,
    ib.neutral,
    ib["variant-ghost"],
    ib.small,
    ib.circle,
    s.clearButton,
  );
  protected readonly clearStates = {
    state: "inactive",
    size: "small",
    variant: "ghost",
    color: "neutral",
    shape: "circle",
  } as const;
  protected readonly contentStates = computed(() => {
    const placement = this.placement();
    const { side, align } = parsePlacement(placement);
    return { state: "open", side, align, placement };
  });

  constructor() {
    super();
    const panel = () => this.panelRef()?.nativeElement;
    anchoredPosition({
      anchor: () => this.inputRef().nativeElement,
      floating: panel,
      active: () => this.isOpen(),
      placement: "bottom-start",
      onPosition: (result) => this.placement.set(result.placement),
    });
    overlayLayer({
      element: panel,
      active: () => this.isOpen(),
      // the field (input + clear button) is part of the popup layer
      branches: () => [this.host.nativeElement],
      // non-trapping focus scope (an enclosing Modal pauses its trap)
      autoFocus: false,
      restoreFocus: () => false,
      onEscapeKeyDown: (event) => {
        if (event.defaultPrevented) return;
        const element = panel();
        const doc = element?.ownerDocument;
        if (element && doc && element.contains(doc.activeElement)) {
          this.inputRef().nativeElement.focus();
        }
      },
      onDismiss: () => this.setOpen(false),
    });
    // Portals leave the field's `dir` subtree: keep the anchor's direction
    afterRenderEffect(() => {
      const element = panel();
      if (!element || !this.isOpen()) return;
      untracked(() => {
        const anchorDir = getDirection(this.inputRef().nativeElement);
        const containerDir = element.parentElement
          ? getDirection(element.parentElement)
          : anchorDir;
        this.panelDir.set(anchorDir === containerDir ? undefined : anchorDir);
      });
    });
  }

  override writeValue(value: Date | null): void {
    this.draft.set(null);
    this.value.set(value ?? null);
  }

  /** Focuses the input */
  focus(options?: FocusOptions): void {
    this.inputRef().nativeElement.focus(options);
  }

  private setOpen(next: boolean): void {
    if (this.open() !== next) this.open.set(next);
  }

  private commit(next: Date | null): void {
    this.value.set(next);
    this.notifyChange(next);
  }

  protected onTimeChange({ type, value }: TimePickerPanelChange): void {
    const next = new Date(this.current() ?? startOfToday());
    if (type === "hour") next.setHours(value);
    else if (type === "minute") next.setMinutes(value);
    else if (type === "second") next.setSeconds(value);
    else {
      const hours = next.getHours() % 12;
      next.setHours(value === 1 ? hours + 12 : hours);
    }
    this.draft.set(null);
    this.commit(next);
  }

  protected onInput(text: string): void {
    this.draft.set(text);
    const parsed = parseTimeInput(text, this.resolvedFormat(), {
      strict: true,
      base: this.current() ?? undefined,
    });
    if (parsed) this.commit(parsed);
  }

  protected onBlur(): void {
    this.notifyTouched();
    const draft = this.draft();
    if (draft === null) return;
    const current = this.current();
    if (draft.trim() === "") {
      if (current) this.commit(null);
    } else {
      const parsed = parseTimeInput(draft, this.resolvedFormat(), {
        strict: false,
        base: current ?? undefined,
      });
      if (parsed && parsed.getTime() !== current?.getTime())
        this.commit(parsed);
    }
    this.draft.set(null);
    // the binding may keep its previous text (e.g. "" -> typed "ab" -> "")
    this.inputRef().nativeElement.value = this.displayValue();
  }

  protected clear(): void {
    this.draft.set(null);
    this.commit(null);
    this.inputRef().nativeElement.focus();
  }

  protected onRootClick(event: MouseEvent): void {
    if (event.target !== this.inputRef().nativeElement) return;
    if (this.isDisabled() || this.isReadOnly()) return;
    this.focusPanelOnOpen.set(false);
    this.setOpen(!this.open());
  }

  /** ArrowDown (also Alt+ArrowDown) opens the panel and moves focus into it */
  protected onInputKeyDown(event: KeyboardEvent): void {
    if (event.key !== "ArrowDown") return;
    event.preventDefault();
    if (this.isDisabled() || this.isReadOnly()) return;
    if (!this.open()) {
      this.focusPanelOnOpen.set(true);
      this.setOpen(true);
    } else {
      this.panelRef()
        ?.nativeElement.querySelector<HTMLElement>(
          '[role="option"][tabindex="0"]',
        )
        ?.focus();
    }
  }

  /**
   * The portalled panel sits after the input in the Tab order: Tab past its
   * last column continues after the input (its clear button, then the rest
   * of the page); Shift+Tab before its first column returns to the input.
   */
  protected onPanelKeyDown(event: KeyboardEvent): void {
    const panel = event.currentTarget as HTMLElement;
    const input = this.inputRef().nativeElement;
    if (
      event.key !== "Tab" ||
      event.altKey ||
      event.ctrlKey ||
      event.metaKey ||
      !tabLeavesPanel(panel, event.target as Element, event.shiftKey)
    )
      return;
    event.preventDefault();
    // Tab moves on within the enclosing dialog (e.g. a Modal), else the page
    const container =
      input.closest('[role="dialog"], [role="alertdialog"]') ??
      input.ownerDocument.body;
    const next = event.shiftKey
      ? input
      : (adjacentTabbable(input, container, false) ?? input);
    next.focus();
    this.setOpen(false);
  }
}

// packages/lib-web-components/src/components/time-picker/time-picker.ts
import { css, html, nothing, type PropertyValues } from "lit";
import { property, query, state } from "lit/decorators.js";
import { classMap } from "lit/directives/class-map.js";
import { live } from "lit/directives/live.js";
import inputStyles from "@lib-core-styles/components/Input/input.module.scss?inline";
import iconButtonStyles from "@lib-core-styles/components/IconButton/iconButton.module.scss?inline";
import styles from "@lib-core-styles/components/TimePicker/timePicker.module.scss?inline";
import panelStyles from "@lib-core-styles/components/TimePicker/timePickerPanel.module.scss?inline";
import {
  FloatingLayerController,
  popoverResetStyles,
} from "../../controllers/floating-layer";
import { AriaController } from "../../internal/aria";
import { DEV, devWarn } from "../../internal/dev";
import {
  FormAssociatedElement,
  type ValidityResult,
} from "../../internal/form";
import { IconClock, IconX } from "../../internal/icons";
import { LocaleController } from "../../internal/locale";
import { hostStyles } from "../../internal/minerva-element";
import {
  contains,
  getTabbables,
  logicalArrowKey,
  formatHasSeconds,
  formatTime,
  resolveTimeFormat,
  parsePlacement,
  parseTimeInput,
  parseTimeValue,
  secondsOfDay,
  startOfToday,
  toTimeValue,
} from "@minerva/core";
import { itemParts } from "../../internal/styling-hooks";
import { sharedStyles } from "../../internal/styles";

export type TimePickerSize = "small" | "medium" | "large";
/** Display formats of lib-core's TimePicker (any HH / H / hh / h / mm / m / ss / s / a pattern works) */
export type TimePickerFormat =
  "HH:mm:ss" | "HH:mm" | "hh:mm:ss a" | "hh:mm a" | (string & {});

type Kind = "hour" | "minute" | "second" | "ampm";

interface TimeUnit {
  value: number;
  disabled: boolean;
  label: string;
}

interface Column {
  kind: Kind;
  label: string;
  items: TimeUnit[];
  selected: number;
  toValue: (v: number) => number;
}

const units = (
  count: number,
  step: number,
  start = 0,
  isDisabled: (value: number) => boolean = () => false,
): TimeUnit[] => {
  const items: TimeUnit[] = [];
  for (let i = start; i < start + count; i += Math.max(1, step)) {
    items.push({
      value: i,
      disabled: isDisabled(i),
      label: String(i).padStart(2, "0"),
    });
  }
  return items;
};

/**
 * Time field (`<TimePicker>` of lib-core): type a time or pick hours /
 * minutes / seconds (/ AM-PM) from a panel of listbox columns.
 *
 * The input toggles the panel on click; ArrowDown opens it and moves focus
 * into the hours column (Up / Down / Home / End move, Enter / Space pick,
 * Left / Right switch column, Tab past the last column leaves the field,
 * Shift+Tab before the first returns to the input). Escape (topmost layer
 * only) closes the panel and returns focus to the input; a pointer down or
 * focus outside closes it too.
 *
 * Seconds have one source of truth, the format in use: `hide-second`
 * removes the seconds token from `format` ("HH:mm:ss" -> "HH:mm"), and the
 * seconds column is shown exactly when that format has seconds.
 *
 * Form-associated: submits the value (24-hour `HH:mm:ss`, or `HH:mm` when
 * the format in use has no seconds) under `name`, supports
 * `required`, `form.reset()` (restores the `value` attribute) and
 * `<fieldset disabled>`. Name it with `label`, `<label for>`, `aria-label` or
 * `aria-labelledby` (default: localized "Time").
 *
 * @summary Time field with a typable input and an hours / minutes / seconds panel.
 * @tag minerva-time-picker
 * @csspart root - The field wrapper (anchor of the panel)
 * @csspart control - The input box
 * @csspart input - The native `<input>`
 * @csspart clear-button - The clear button
 * @csspart icon - The clock icon (shown when there is no clear button)
 * @csspart content - The popup panel (`role=dialog`)
 * @csspart column - An hours / minutes / seconds / AM-PM column (`role=listbox`)
 * @csspart item - A time unit (`role=option`)
 * @csspart item--selected - Item state of `item`: selected
 * @csspart item--disabled - Item state of `item`: disabled
 * @fires minerva-change - The time was committed (picked, typed, normalized on blur or cleared), `detail: { value }` (`""` when cleared)
 * @fires minerva-input - The text of the input changed while typing, `detail: { value }` (the typed text)
 * @fires minerva-open-change - The user opened / closed the panel, `detail: { open }`; cancelable: `preventDefault()` keeps the current state
 * @fires minerva-clear - The clear button emptied the field
 * @fires change - Same as `minerva-change` (native-like, bubbles)
 */
export class MinervaTimePicker extends FormAssociatedElement {
  static override tagName = "minerva-time-picker";

  /** Name submitted with the form data (same default as the React TimePicker) */
  @property({ reflect: true })
  override name = "time-picker";
  static override shadowRootOptions = {
    ...FormAssociatedElement.shadowRootOptions,
    delegatesFocus: true,
  };
  static override styles = [
    hostStyles,
    popoverResetStyles,
    css`
      :host {
        display: inline-block;
        vertical-align: middle;
      }
      .timePicker {
        display: block;
      }
      .timePicker .root {
        width: 100%;
      }
    `,
    sharedStyles(inputStyles),
    sharedStyles(iconButtonStyles),
    sharedStyles(styles),
    sharedStyles(panelStyles),
  ];

  /** Current value: 24-hour `HH:mm:ss` / `HH:mm` (`""` = no time). The `value` attribute sets `defaultValue` */
  @property({ attribute: false })
  value = "";

  /**
   * Initial value, restored by `form.reset()` (the `value` attribute,
   * `HH:mm` or `HH:mm:ss`). Changing it also changes `value` until the user edits it
   */
  @property({ attribute: "value" })
  defaultValue = "";

  /** Whether the panel is open */
  @property({ type: Boolean, reflect: true })
  open = false;

  /** Display format (tokens HH / H / hh / h / mm / m / ss / s / a) */
  @property({ reflect: true })
  format: TimePickerFormat = "HH:mm:ss";

  /** Uses a 12-hour clock with an AM/PM column */
  @property({ type: Boolean, reflect: true, attribute: "use-12-hours" })
  use12Hours = false;

  /** Placeholder of the input (default: localized "Select time") */
  @property()
  placeholder?: string;

  /** Accessible label of the input and panel (default: aria-label, `<label>`, else localized "Time") */
  @property()
  label?: string;

  /** Height and font size */
  @property({ reflect: true })
  size: TimePickerSize = "medium";

  /** Error state; sets aria-invalid */
  @property({ type: Boolean, reflect: true })
  invalid = false;

  /** Shows the value without allowing changes (typing, panel, clearing) */
  @property({ type: Boolean, reflect: true, attribute: "readonly" })
  readOnly = false;

  /** Hides the clear button (lib-core: `clearable={false}`) */
  @property({ type: Boolean, reflect: true, attribute: "hide-clear-button" })
  hideClearButton = false;

  /** Hides the seconds column (lib-core: `showSecond={false}`) */
  @property({ type: Boolean, reflect: true, attribute: "hide-second" })
  hideSecond = false;

  /** Earliest selectable time (`HH:mm` / `HH:mm:ss`); earlier options are disabled */
  @property({ attribute: "min-time" })
  minTime?: string;

  /** Latest selectable time (`HH:mm` / `HH:mm:ss`); later options are disabled */
  @property({ attribute: "max-time" })
  maxTime?: string;

  /** Interval between hour options */
  @property({ type: Number, attribute: "hour-step" })
  hourStep = 1;

  /** Interval between minute options */
  @property({ type: Number, attribute: "minute-step" })
  minuteStep = 1;

  /** Interval between second options */
  @property({ type: Number, attribute: "second-step" })
  secondStep = 1;

  /** Text being typed; `null` = show the formatted value */
  @state()
  private draft: string | null = null;

  @query("input")
  private input?: HTMLInputElement;

  @query(".timePicker")
  private field?: HTMLElement;

  @query(".popup")
  private popup?: HTMLElement;

  private readonly locale = new LocaleController(this);
  private readonly aria = new AriaController(this, () => this.labels);
  private readonly floating = new FloatingLayerController(this, () => ({
    anchor: () => this.input,
    floating: () => this.popup,
    placement: "bottom-start",
    // the field (input + clear button) is part of the popup layer
    branches: () => [this.field],
    onDismiss: () => this.requestOpenChange(false),
    returnFocusOnEscape: () => this.input,
    focusable: true,
    onPosition: () => this.syncHookStates(),
  }));

  /** The user (or a script setting `value`) changed the value */
  private dirty = false;
  /** Opened from the keyboard: focus moves into the first column */
  private focusPanelOnOpen = false;

  /** The value as a `Date` (today's date), `null` when empty or invalid */
  get valueAsDate(): Date | null {
    return parseTimeValue(this.value);
  }

  override focus(options?: FocusOptions): void {
    this.input?.focus(options);
  }

  override blur(): void {
    this.input?.blur();
  }

  /** Opens the panel (no event) */
  show(): void {
    this.open = true;
  }

  /** Closes the panel (no event) */
  hide(): void {
    this.open = false;
  }

  /** Format in use: `hide-second` removes the seconds token */
  private get effectiveFormat(): string {
    return resolveTimeFormat(this.format, !this.hideSecond);
  }

  /** The seconds column follows the format in use (single source of truth) */
  private get withSeconds(): boolean {
    return formatHasSeconds(this.effectiveFormat);
  }

  private get interactive(): boolean {
    return !this.isDisabled && !this.readOnly;
  }

  protected getFormValue(): string {
    const current = this.valueAsDate;
    return current ? toTimeValue(current, this.withSeconds) : "";
  }

  protected override getValidity(): ValidityResult {
    if (this.required && !this.valueAsDate) {
      return {
        flags: { valueMissing: true },
        message: this.locale.t("validation.valueMissing"),
        anchor: this.input,
      };
    }
    return { flags: {}, message: "" };
  }

  protected resetFormValue(): void {
    this.dirty = false;
    this.draft = null;
    this.value = this.defaultValue;
  }

  protected override restoreFormState(state: unknown): void {
    if (typeof state === "string") this.value = state;
  }

  protected override willUpdate(changed: PropertyValues<this>): void {
    if (changed.has("value") && changed.get("value") !== undefined) {
      this.dirty = this.value !== this.defaultValue || this.dirty;
    }
    // first update: a value set before connecting wins over the default
    // unless the value attribute is present
    if (
      changed.has("defaultValue") &&
      !this.dirty &&
      (this.hasUpdated || this.hasAttribute("value"))
    ) {
      this.value = this.defaultValue;
    }
    if (DEV) this.checkUsage(changed);
  }

  private checkUsage(changed: PropertyValues<this>) {
    const tag = MinervaTimePicker.tagName;
    if (changed.has("value") && this.value && !parseTimeValue(this.value)) {
      devWarn(
        tag,
        `value "${this.value}" is not a valid time: use 24-hour "HH:mm" or "HH:mm:ss".`,
      );
    }
    if (changed.has("minTime") || changed.has("maxTime")) {
      for (const [name, text] of [
        ["min-time", this.minTime],
        ["max-time", this.maxTime],
      ] as const) {
        if (text && !parseTimeValue(text)) {
          devWarn(
            tag,
            `${name} "${text}" is not a valid time: use 24-hour "HH:mm" or "HH:mm:ss".`,
          );
        }
      }
      const min = parseTimeValue(this.minTime);
      const max = parseTimeValue(this.maxTime);
      if (min && max && secondsOfDay(min) > secondsOfDay(max)) {
        devWarn(
          tag,
          `min-time (${this.minTime}) is later than max-time (${this.maxTime}): no time can be selected.`,
        );
      }
    }
  }

  protected override updated(changed: PropertyValues<this>): void {
    super.updated(changed);
    const open = this.open && this.interactive;
    this.floating.sync(open);
    if (!open) {
      this.focusPanelOnOpen = false;
      return;
    }
    if (changed.has("open") || changed.has("disabled")) {
      const popup = this.popup;
      popup
        ?.querySelectorAll<HTMLElement>('[aria-selected="true"]')
        .forEach((el) => el.scrollIntoView?.({ block: "nearest" }));
      if (this.focusPanelOnOpen) this.focusFirstColumn();
    }
  }

  private focusFirstColumn() {
    this.popup
      ?.querySelector<HTMLElement>('[role="option"][tabindex="0"]')
      ?.focus();
  }

  /** Asks to change `open`; listeners can cancel `minerva-open-change`. */
  private requestOpenChange(open: boolean): boolean {
    if (open === this.open) return true;
    const allowed = this.emit(
      "minerva-open-change",
      { open },
      { cancelable: true },
    );
    if (allowed) this.open = open;
    return allowed;
  }

  private commit(next: Date | null) {
    this.value = next ? toTimeValue(next, this.withSeconds) : "";
    this.dispatchEvent(new Event("change", { bubbles: true }));
    this.emit("minerva-change", { value: this.value });
  }

  private handleTimeChange(type: Kind, val: number) {
    const next = new Date(this.valueAsDate ?? startOfToday());
    if (type === "hour") next.setHours(val);
    else if (type === "minute") next.setMinutes(val);
    else if (type === "second") next.setSeconds(val);
    else {
      const hours = next.getHours() % 12;
      next.setHours(val === 1 ? hours + 12 : hours);
    }
    this.draft = null;
    this.commit(next);
  }

  private handleInput(event: Event) {
    const text = (event.target as HTMLInputElement).value;
    this.draft = text;
    this.emit("minerva-input", { value: text });
    const parsed = parseTimeInput(text, this.effectiveFormat, {
      strict: true,
      base: this.valueAsDate ?? undefined,
    });
    if (parsed) this.commit(parsed);
  }

  private handleBlur() {
    const draft = this.draft;
    if (draft === null) return;
    const current = this.valueAsDate;
    if (draft.trim() === "") {
      if (current) this.commit(null);
    } else {
      const parsed = parseTimeInput(draft, this.effectiveFormat, {
        strict: false,
        base: current ?? undefined,
      });
      if (parsed && parsed.getTime() !== current?.getTime())
        this.commit(parsed);
    }
    this.draft = null;
  }

  private handleClear() {
    this.draft = null;
    this.commit(null);
    this.emit("minerva-clear");
    this.input?.focus();
  }

  private handleInputClick() {
    if (!this.interactive) return;
    this.focusPanelOnOpen = false;
    this.requestOpenChange(!this.open);
  }

  private handleInputKeyDown(event: KeyboardEvent) {
    // ArrowDown (also Alt+ArrowDown) opens the panel and moves focus into it
    if (event.key !== "ArrowDown") return;
    event.preventDefault();
    if (!this.interactive) return;
    if (!this.open) {
      this.focusPanelOnOpen = true;
      if (!this.requestOpenChange(true)) this.focusPanelOnOpen = false;
    } else {
      this.focusFirstColumn();
    }
  }

  /**
   * The panel sits after the field in the Tab order: Tab past its last
   * column continues after the input (its clear button, then the rest of the
   * page); Shift+Tab before its first column returns to the input.
   */
  private handlePanelKeyDown(event: KeyboardEvent) {
    const panel = event.currentTarget as HTMLElement;
    const input = this.input;
    if (
      !input ||
      event.key !== "Tab" ||
      event.altKey ||
      event.ctrlKey ||
      event.metaKey
    )
      return;
    const focused = this.shadowRoot?.activeElement ?? null;
    if (!focused || !panel.contains(focused)) return;
    const tabbables = getTabbables(panel);
    const leaves =
      tabbables.length === 0 ||
      (event.shiftKey
        ? focused === panel || focused === tabbables[0]
        : focused === tabbables[tabbables.length - 1]);
    if (!leaves) return;
    event.preventDefault();
    const next = event.shiftKey
      ? input
      : (this.shadowRoot?.querySelector<HTMLElement>(".clearButton") ??
        this.tabbableAfter() ??
        input);
    next.focus();
    this.requestOpenChange(false);
  }

  /** The first tabbable element of the page after this element. */
  private tabbableAfter(): HTMLElement | null {
    const all = getTabbables(this.ownerDocument.body);
    let last = -1;
    all.forEach((el, i) => {
      if (contains(this, el)) last = i;
    });
    if (last === -1) {
      return (
        all.find(
          (el) =>
            !!(
              this.compareDocumentPosition(el) &
              Node.DOCUMENT_POSITION_FOLLOWING
            ),
        ) ?? null
      );
    }
    return all.slice(last + 1).find((el) => !contains(this, el)) ?? null;
  }

  private handleColumnKeyDown(event: KeyboardEvent, columnIndex: number) {
    const column = event.currentTarget as HTMLElement;
    const target = event.target as HTMLElement;
    const options = Array.from(
      column.querySelectorAll<HTMLElement>('[role="option"]'),
    );
    const enabled = options.filter(
      (o) => o.getAttribute("aria-disabled") !== "true",
    );
    const index = enabled.indexOf(target);
    const columns =
      this.popup?.querySelectorAll<HTMLElement>('[role="listbox"]');
    const count = columns?.length ?? 0;
    const focusColumn = (i: number) =>
      columns?.[i]?.querySelector<HTMLElement>('[tabindex="0"]')?.focus();
    // RTL: columns are laid out right to left, so ArrowLeft is the next one.
    const key = logicalArrowKey(event.key, this);
    switch (key) {
      case "ArrowDown":
        event.preventDefault();
        enabled[Math.min(enabled.length - 1, index + 1)]?.focus();
        break;
      case "ArrowUp":
        event.preventDefault();
        enabled[Math.max(0, index - 1)]?.focus();
        break;
      case "Home":
        event.preventDefault();
        enabled[0]?.focus();
        break;
      case "End":
        event.preventDefault();
        enabled[enabled.length - 1]?.focus();
        break;
      case "ArrowRight":
        event.preventDefault();
        focusColumn(Math.min(count - 1, columnIndex + 1));
        break;
      case "ArrowLeft":
        event.preventDefault();
        focusColumn(Math.max(0, columnIndex - 1));
        break;
      default:
        break;
    }
  }

  private pick(column: Column, unit: TimeUnit) {
    if (!unit.disabled)
      this.handleTimeChange(column.kind, column.toValue(unit.value));
  }

  private columns(value: Date): Column[] {
    const { t } = this.locale;
    const use12Hours = this.use12Hours;
    const minTime = parseTimeValue(this.minTime);
    const maxTime = parseTimeValue(this.maxTime);
    const hour = value.getHours();
    const minute = value.getMinutes();
    const second = value.getSeconds();
    const isPM = hour >= 12;
    const toHour24 = (h: number) =>
      use12Hours ? (h % 12) + (isPM ? 12 : 0) : h;

    const hours = units(
      use12Hours ? 12 : 24,
      this.hourStep,
      use12Hours ? 1 : 0,
      (h) => {
        const h24 = toHour24(h);
        return Boolean(
          (minTime && h24 < minTime.getHours()) ||
          (maxTime && h24 > maxTime.getHours()),
        );
      },
    );
    const minutes = units(60, this.minuteStep, 0, (m) =>
      Boolean(
        (minTime && hour === minTime.getHours() && m < minTime.getMinutes()) ||
        (maxTime && hour === maxTime.getHours() && m > maxTime.getMinutes()),
      ),
    );
    const seconds = units(60, this.secondStep, 0, (s) => {
      const atMin =
        minTime &&
        hour === minTime.getHours() &&
        minute === minTime.getMinutes();
      const atMax =
        maxTime &&
        hour === maxTime.getHours() &&
        minute === maxTime.getMinutes();
      return Boolean(
        (atMin && s < minTime.getSeconds()) ||
        (atMax && s > maxTime.getSeconds()),
      );
    });

    const columns: Column[] = [
      {
        kind: "hour",
        label: t("timePicker.hours"),
        items: hours,
        selected: use12Hours ? hour % 12 || 12 : hour,
        toValue: toHour24,
      },
      {
        kind: "minute",
        label: t("timePicker.minutes"),
        items: minutes,
        selected: minute,
        toValue: (v) => v,
      },
    ];
    if (this.withSeconds) {
      columns.push({
        kind: "second",
        label: t("timePicker.seconds"),
        items: seconds,
        selected: second,
        toValue: (v) => v,
      });
    }
    if (use12Hours) {
      columns.push({
        kind: "ampm",
        label: t("timePicker.period"),
        items: [
          { value: 0, label: "AM", disabled: false },
          { value: 1, label: "PM", disabled: false },
        ],
        selected: isPM ? 1 : 0,
        toValue: (v) => v,
      });
    }
    return columns;
  }

  private renderPanel(current: Date | null, name: string) {
    const hasValue = current !== null;
    const columns = this.columns(current ?? startOfToday());
    return html`<div
      part="content"
      class="popup"
      popover="manual"
      role="dialog"
      tabindex="-1"
      aria-label=${name}
      @keydown=${this.handlePanelKeyDown}
    >
      <div class="timePickerPanel">
        <div class="timeColumns">
          ${columns.map((column, columnIndex) => {
            const firstEnabled = column.items.find((u) => !u.disabled)?.value;
            const tabStop = column.items.some(
              (u) => u.value === column.selected && !u.disabled,
            )
              ? column.selected
              : firstEnabled;
            // Roving tabindex lives on the options; the listbox is only a
            // programmatic focus target.
            return html`<div
              part="column"
              class="timeColumn"
              role="listbox"
              aria-label=${column.label}
              tabindex="-1"
              data-kind=${column.kind}
              @keydown=${(e: KeyboardEvent) =>
                this.handleColumnKeyDown(e, columnIndex)}
            >
              ${column.items.map((unit) => {
                const selected = hasValue && unit.value === column.selected;
                return html`<div
                  part=${itemParts("item", {
                    selected,
                    disabled: unit.disabled,
                  })}
                  role="option"
                  aria-selected=${selected ? "true" : "false"}
                  aria-disabled=${unit.disabled ? "true" : nothing}
                  tabindex=${unit.value === tabStop ? "0" : "-1"}
                  class=${classMap({
                    timeUnit: true,
                    selected,
                    disabled: unit.disabled,
                  })}
                  @click=${() => this.pick(column, unit)}
                  @keydown=${(e: KeyboardEvent) => {
                    if (e.key === "Enter" || e.key === " ") {
                      e.preventDefault();
                      this.pick(column, unit);
                    }
                  }}
                >
                  ${unit.label}
                </div>`;
              })}
            </div>`;
          })}
        </div>
      </div>
    </div>`;
  }

  protected override hookStates() {
    const open = this.open && !this.isDisabled && !this.readOnly;
    const placement =
      open && this.floating.isOpen
        ? this.floating.position.placement
        : undefined;
    const { side, align } = placement
      ? parsePlacement(placement)
      : { side: undefined, align: undefined };
    return {
      state: open ? "open" : "closed",
      disabled: this.isDisabled,
      readonly: this.readOnly,
      invalid: this.invalid,
      size: this.size,
      side,
      align,
      placement,
    };
  }

  protected override render() {
    const { t } = this.locale;
    const disabled = this.isDisabled;
    const readonly = this.readOnly;
    const current = this.valueAsDate;
    const name = this.label || this.aria.label || t("timePicker.label");
    const displayValue =
      this.draft ?? (current ? formatTime(current, this.effectiveFormat) : "");
    const showClear =
      !this.hideClearButton && !!current && !disabled && !readonly;

    return html`<div part="root" class="timePicker">
        <div
          part="control"
          class=${classMap({
            root: true,
            outline: true,
            [this.size]: true,
            invalid: this.invalid,
            disabled,
          })}
          data-component="input"
        >
          <input
            part="input"
            class="field"
            .value=${live(displayValue)}
            placeholder=${this.placeholder ?? t("timePicker.placeholder")}
            ?disabled=${disabled}
            ?readonly=${readonly}
            ?required=${this.required}
            autocomplete="off"
            aria-label=${name}
            aria-description=${this.aria.description ?? nothing}
            aria-invalid=${
              this.invalid || this.aria.attr("aria-invalid") === "true"
                ? "true"
                : nothing
            }
            aria-readonly=${readonly ? "true" : nothing}
            @input=${this.handleInput}
            @blur=${this.handleBlur}
            @click=${this.handleInputClick}
            @keydown=${this.handleInputKeyDown}
          />
          <span class="addon end">
            ${
              showClear
                ? html`<button
                    part="clear-button"
                    type="button"
                    class="iconButton neutral variant-ghost small circle clearButton"
                    aria-label=${t("timePicker.clear")}
                    @click=${this.handleClear}
                  >
                    ${IconX}
                  </button>`
                : html`<span part="icon" class="clockIcon" aria-hidden="true"
                    >${IconClock}</span
                  >`
            }
          </span>
        </div>
      </div>
      ${this.open && !disabled && !readonly ? this.renderPanel(current, name) : nothing}`;
  }
}

declare global {
  interface HTMLElementTagNameMap {
    "minerva-time-picker": MinervaTimePicker;
  }
}
