// packages/angular/src/internal/dialog.ts
import {
  DestroyRef,
  Directive,
  ElementRef,
  InjectionToken,
  booleanAttribute,
  computed,
  effect,
  inject,
  input,
  output,
  signal,
  untracked,
  viewChild,
  type Signal,
} from "@angular/core";
import { injectScope } from "../config/scope";
import { controllable } from "./controllable";
import { injectId } from "./ids";
import { overlayLayer } from "./overlay";
import { injectIsBrowser } from "./platform";
import { presence } from "./portal";

/** What dialog parts (header, trigger, close) need from their dialog */
export interface DialogContext {
  readonly contentId: string;
  readonly titleId: string;
  readonly descriptionId: string;
  readonly isOpen: Signal<boolean>;
  /** Opens / closes (emits the model change) */
  setOpen(open: boolean): void;
  /** A header was mounted (the dialog is labelled by it); returns the unregister */
  registerTitle(): () => void;
  /** A trigger element (focus returns to it, outside clicks on it are inside) */
  registerTrigger(element: HTMLElement): () => void;
}

/** The closest dialog (Modal, Drawer, CommandDialog...) */
export const MN_DIALOG = new InjectionToken<DialogContext>("MN_DIALOG");

/**
 * Dialog foundation of Modal, Drawer, ConfirmDialog and CommandDialog (React's
 * internal `Dialog`): the open state (`[(open)]` model, `defaultOpen`), ids
 * linking trigger / content / title / description, the presence of the
 * portalled panel during its exit animation and its behaviour (focus moved in
 * and trapped, Escape / overlay click dismissal, scroll lock, the rest of the
 * page hidden, focus returned to the opener).
 *
 * Subclasses render, inside `@if (mounted()) { <ng-container *mnPortal> }`,
 * an overlay and the panel element (`#panel`).
 */
@Directive()
export abstract class MnDialogBase implements DialogContext {
  /**
   * Open state. Bound, the parent owns it (`[(open)]`; a one-way `[open]`
   * only receives requests through `openChange`, React's controlled mode);
   * unbound, the dialog owns it (`defaultOpen`, triggers)
   */
  readonly open = input<boolean | undefined, unknown>(undefined, {
    transform: (v: unknown) =>
      v === undefined || v === null ? undefined : booleanAttribute(v),
  });
  /** The user asked to open / close (trigger, close button, Escape, overlay) */
  readonly openChange = output<boolean>();
  /**
   * Initial open state when `open` is not bound
   * @default false
   */
  readonly defaultOpen = input(false, { transform: booleanAttribute });
  /**
   * Modal mode: overlay, focus trap, scroll lock, outside pointer blocked and
   * the rest of the page hidden from assistive technology
   * @default true
   */
  readonly modal = input(true, { transform: booleanAttribute });
  /**
   * Keeps the panel mounted while closed (`data-state="closed"`)
   * @default false
   */
  readonly forceMount = input(false, { transform: booleanAttribute });

  /** Escape pressed while topmost; `preventDefault()` keeps it open */
  readonly escapeKeyDown = output<KeyboardEvent>();
  /** Pointer down outside (e.g. on the overlay); `preventDefault()` keeps it open */
  readonly pointerDownOutside = output<PointerEvent>();
  /** Before focus moves into the panel on open; `preventDefault()` keeps it */
  readonly openAutoFocus = output<Event>();
  /** Before focus returns to the opener on close; `preventDefault()` skips it */
  readonly closeAutoFocus = output<Event>();

  protected readonly scope = injectScope();
  readonly contentId = injectId("dialog");
  readonly titleId = `${this.contentId}-title`;
  readonly descriptionId = `${this.contentId}-description`;

  private readonly openState = controllable({
    bound: () => this.open(),
    initial: () => this.defaultOpen(),
    emit: (open) => this.openChange.emit(open),
  });
  /** Current open state */
  readonly isOpen = this.openState.value;
  protected readonly state = computed(() =>
    this.isOpen() ? "open" : "closed",
  );

  private readonly titleCount = signal(0);
  /** A title is mounted (`aria-labelledby`) */
  protected readonly hasTitle = computed(() => this.titleCount() > 0);
  private readonly triggers = new Set<HTMLElement>();
  private opener: HTMLElement | null = null;

  protected readonly panel = viewChild<ElementRef<HTMLElement>>("panel");
  /** The panel is rendered (open, or closing during its exit animation) */
  protected readonly mounted = presence(
    () => this.isOpen() || this.forceMount(),
    () => this.panel()?.nativeElement,
  );

  private destroyed = false;

  constructor() {
    const isBrowser = injectIsBrowser();
    inject(DestroyRef).onDestroy(() => (this.destroyed = true));
    // the element focused when opening (focus returns to it)
    effect(() => {
      if (!this.isOpen() || !isBrowser) return;
      untracked(() => {
        const active = document.activeElement;
        const panel = this.panel()?.nativeElement;
        if (!active || !panel?.contains(active))
          this.opener =
            active instanceof HTMLElement && active !== document.body
              ? active
              : null;
      });
    });
    overlayLayer({
      element: () => this.panel()?.nativeElement,
      active: () => this.isOpen(),
      modal: () => this.modal(),
      restoreFocus: () => this.opener ?? [...this.triggers][0] ?? true,
      branches: () => [...this.triggers],
      onEscapeKeyDown: (event) => {
        this.escapeKeyDown.emit(event);
        return event.defaultPrevented ? false : undefined;
      },
      onPointerDownOutside: (event) => {
        this.pointerDownOutside.emit(event);
        return event.defaultPrevented ? false : undefined;
      },
      onOpenAutoFocus: (event) => this.openAutoFocus.emit(event),
      // (focus returns on the next macrotask: maybe after a destroy)
      onCloseAutoFocus: (event) => {
        if (!this.destroyed) this.closeAutoFocus.emit(event);
      },
      onDismiss: () => this.setOpen(false),
    });
  }

  setOpen(open: boolean): void {
    this.openState.set(open);
  }

  registerTitle(): () => void {
    this.titleCount.update((n) => n + 1);
    return () => this.titleCount.update((n) => n - 1);
  }

  registerTrigger(element: HTMLElement): () => void {
    this.triggers.add(element);
    return () => this.triggers.delete(element);
  }
}

/** Shared host bindings of dialog triggers (`[mnModalTrigger]`...) */
export const DIALOG_TRIGGER_HOST = {
  "aria-haspopup": "dialog",
  "[attr.aria-expanded]": "dialog().isOpen()",
  "[attr.aria-controls]": "dialog().isOpen() ? dialog().contentId : null",
  "[attr.data-state]": "dialog().isOpen() ? 'open' : 'closed'",
  "(click)": "dialog().setOpen(!dialog().isOpen())",
} as const;

/** Registers the host element as a trigger of a dialog */
export function registerTrigger(dialog: () => DialogContext): void {
  const host = inject<ElementRef<HTMLElement>>(ElementRef).nativeElement;
  let unregister: (() => void) | undefined;
  effect((onCleanup) => {
    unregister = dialog().registerTrigger(host);
    onCleanup(() => unregister?.());
  });
}

// packages/lib-core/src/internal/Dialog.tsx
import {
  createContext,
  useCallback,
  useContext,
  useId,
  useLayoutEffect,
  useMemo,
  useRef,
  useState,
  type ComponentPropsWithRef,
  type CSSProperties,
  type HTMLAttributes,
  type ReactNode,
  type Ref,
  type RefObject,
} from "react";
import { composeEventHandlers } from "./composeEventHandlers";
import { useMergedRefs } from "./mergeRefs";
import { Portal } from "./Portal";
import { Slot } from "./Slot";
import { useControllableState } from "./useControllableState";
import { LayerContext, useDismissableLayer } from "./useDismissableLayer";
import { useFocusScope } from "./useFocusScope";
import { useHideOthers } from "./useHideOthers";
import { usePresence } from "./usePresence";
import { useScrollLock } from "./useScrollLock";

/** Open / closed, mirrored in `data-state` for CSS animations. */
export type DialogState = "open" | "closed";

interface DialogContextValue {
  open: boolean;
  setOpen: (open: boolean) => void;
  modal: boolean;
  contentId: string;
  titleId: string;
  descriptionId: string;
  /** Number of mounted `DialogTitle` / `DialogDescription` (ARIA links). */
  titles: number;
  descriptions: number;
  registerTitle: () => () => void;
  registerDescription: () => () => void;
  triggerRef: RefObject<HTMLElement | null>;
  /** Element focused when the dialog opened (focus returns to it). */
  openerRef: RefObject<HTMLElement | null>;
  contentRef: RefObject<HTMLElement | null>;
}

const DialogContext = createContext<DialogContextValue | null>(null);

/** Dialog state of the closest `DialogRoot` (throws outside of one). */
export const useDialogContext = (component: string): DialogContextValue => {
  const context = useContext(DialogContext);
  if (!context) {
    throw new Error(`<${component}> must be used inside its dialog root`);
  }
  return context;
};

/** Props of the `DialogRoot` dialog state owner. */
export interface DialogRootProps {
  /** Controlled open state; leave `undefined` for uncontrolled. */
  open?: boolean;
  /** Initial open state while uncontrolled. @default false */
  defaultOpen?: boolean;
  /** Called with the requested open state. */
  onOpenChange?: (open: boolean) => void;
  /**
   * Modal: focus trap, scroll lock, the rest of the page hidden from
   * assistive technology and inert to the pointer, an overlay. @default true
   */
  modal?: boolean;
  children?: ReactNode;
}

/**
 * Records the element focused when the dialog opens. Rendered as the first
 * child of the root so its layout effect runs before any content mounts
 * (an `autoFocus` field focuses itself during that same commit).
 */
const OpenerCapture = ({
  open,
  openerRef,
  contentRef,
}: {
  open: boolean;
  openerRef: RefObject<HTMLElement | null>;
  contentRef: RefObject<HTMLElement | null>;
}) => {
  const wasOpen = useRef(false);
  useLayoutEffect(() => {
    // Only on the closed -> open transition (StrictMode replays the effect
    // once focus is already inside the content).
    if (open && !wasOpen.current) {
      const active = document.activeElement;
      // Re-opened while the previous content still has focus: keep the opener.
      if (!active || !contentRef.current?.contains(active)) {
        openerRef.current =
          active instanceof HTMLElement && active !== document.body
            ? active
            : null;
      }
    }
    wasOpen.current = open;
  }, [open, openerRef, contentRef]);
  return null;
};

/**
 * DialogRoot: owns the open state (controlled / uncontrolled) and the ids
 * linking trigger, content, title and description. Shared foundation of
 * Modal, Drawer, the AppShell navigation drawer and CommandDialog.
 */
export const DialogRoot = ({
  open: openProp,
  defaultOpen = false,
  onOpenChange,
  modal = true,
  children,
}: DialogRootProps) => {
  const [open, setOpen] = useControllableState({
    value: openProp,
    defaultValue: defaultOpen,
    onChange: onOpenChange,
  });
  const id = useId();
  const [titles, setTitles] = useState(0);
  const [descriptions, setDescriptions] = useState(0);
  const triggerRef = useRef<HTMLElement | null>(null);
  const openerRef = useRef<HTMLElement | null>(null);
  const contentRef = useRef<HTMLElement | null>(null);

  const registerTitle = useCallback(() => {
    setTitles((n) => n + 1);
    return () => setTitles((n) => n - 1);
  }, []);
  const registerDescription = useCallback(() => {
    setDescriptions((n) => n + 1);
    return () => setDescriptions((n) => n - 1);
  }, []);

  const value = useMemo<DialogContextValue>(
    () => ({
      open,
      setOpen,
      modal,
      contentId: `${id}content`,
      titleId: `${id}title`,
      descriptionId: `${id}description`,
      titles,
      descriptions,
      registerTitle,
      registerDescription,
      triggerRef,
      openerRef,
      contentRef,
    }),
    [
      open,
      setOpen,
      modal,
      id,
      titles,
      descriptions,
      registerTitle,
      registerDescription,
    ],
  );

  return (
    <DialogContext.Provider value={value}>
      <OpenerCapture
        open={open}
        openerRef={openerRef}
        contentRef={contentRef}
      />
      {children}
    </DialogContext.Provider>
  );
};

/** Props of `DialogTrigger` / `DialogClose`. */
export interface DialogButtonProps extends ComponentPropsWithRef<"button"> {
  /** Merge onto the single child element instead of rendering a `<button>`. */
  asChild?: boolean;
}

/**
 * Toggles the dialog: `aria-haspopup="dialog"`, `aria-expanded`,
 * `aria-controls` (while open) and `data-state`. Focus returns to it on close
 * when nothing else was focused when opening.
 */
export const DialogTrigger = ({
  asChild = false,
  onClick,
  ref,
  ...rest
}: DialogButtonProps) => {
  const context = useDialogContext("DialogTrigger");
  const { open, setOpen, triggerRef, contentId } = context;
  const mergedRef = useMergedRefs<HTMLElement>(
    triggerRef,
    ref as Ref<HTMLElement>,
  );
  const props = {
    "aria-haspopup": "dialog" as const,
    "aria-expanded": open,
    "aria-controls": open ? contentId : undefined,
    "data-state": open ? "open" : "closed",
    ...rest,
    onClick: composeEventHandlers(onClick, () => setOpen(!open)),
  };
  return asChild ? (
    <Slot ref={mergedRef} {...props} />
  ) : (
    <button
      type="button"
      ref={mergedRef as Ref<HTMLButtonElement>}
      {...props}
    />
  );
};

/** Closes the dialog; a `<button>` or, with `asChild`, the child element. */
export const DialogClose = ({
  asChild = false,
  onClick,
  ...rest
}: DialogButtonProps) => {
  const { setOpen } = useDialogContext("DialogClose");
  const props = {
    ...rest,
    onClick: composeEventHandlers(onClick, () => setOpen(false)),
  };
  return asChild ? <Slot {...props} /> : <button type="button" {...props} />;
};

/** Props of `DialogTitle` / `DialogDescription`. */
export interface DialogTextProps extends HTMLAttributes<HTMLElement> {
  ref?: Ref<HTMLElement>;
  /** Merge onto the single child element instead of rendering an element. */
  asChild?: boolean;
}

/** The dialog's accessible name (`aria-labelledby` of the content). */
export const DialogTitle = ({
  asChild = false,
  ref,
  children,
  ...rest
}: DialogTextProps) => {
  const { titleId, registerTitle } = useDialogContext("DialogTitle");
  useLayoutEffect(registerTitle, [registerTitle]);
  const props = { id: titleId, ...rest };
  return asChild ? (
    <Slot ref={ref} {...props}>
      {children}
    </Slot>
  ) : (
    <h2 ref={ref as Ref<HTMLHeadingElement>} {...props}>
      {children}
    </h2>
  );
};

/**
 * The dialog's accessible description (`aria-describedby` of the content,
 * only set while a description is mounted).
 */
export const DialogDescription = ({
  asChild = false,
  ref,
  ...rest
}: DialogTextProps) => {
  const { descriptionId, registerDescription } =
    useDialogContext("DialogDescription");
  useLayoutEffect(registerDescription, [registerDescription]);
  const props = { id: descriptionId, ...rest };
  return asChild ? (
    <Slot ref={ref} {...props} />
  ) : (
    <p ref={ref as Ref<HTMLParagraphElement>} {...props} />
  );
};

/** Props shared by the dialog-like overlay contents (Modal, Drawer...). */
export interface DialogContentEventProps {
  /**
   * Before focus moves into the content on open; `event.preventDefault()`
   * keeps it where it is (move it yourself).
   */
  onOpenAutoFocus?: (event: Event) => void;
  /**
   * Before focus returns to the opener on close; `event.preventDefault()`
   * skips it (move it yourself).
   */
  onCloseAutoFocus?: (event: Event) => void;
  /** Escape pressed while topmost; `event.preventDefault()` keeps it open. */
  onEscapeKeyDown?: (event: KeyboardEvent) => void;
  /** Pointer pressed outside (e.g. the overlay); `preventDefault()` keeps it open. */
  onPointerDownOutside?: (event: PointerEvent) => void;
  /** Pointer down or focus outside; `preventDefault()` keeps it open. */
  onInteractOutside?: (event: PointerEvent | FocusEvent) => void;
}

/** Props of `DialogContent`. */
export interface DialogContentProps
  extends HTMLAttributes<HTMLDivElement>, DialogContentEventProps {
  ref?: Ref<HTMLDivElement>;
  /** @default "dialog" */
  role?: "dialog" | "alertdialog";
  /** Keep mounted while closed (`data-state="closed"`, no behaviour). */
  forceMount?: boolean;
  /** Class name of the overlay (modal only). */
  overlayClassName?: string;
  /** Inline style of the overlay (modal only). */
  overlayStyle?: CSSProperties;
  /** Portal container; defaults to the theme-scoped one / `document.body`. */
  container?: Element | null;
}

const OVERLAY_STYLE: CSSProperties = { pointerEvents: "auto" };

/**
 * DialogContent: portalled overlay (modal) + the dialog element.
 *
 * - `role="dialog"` (or `alertdialog`), `aria-modal` when modal,
 *   `aria-labelledby` / `aria-describedby` linked to a mounted
 *   `DialogTitle` / `DialogDescription`, `data-state="open|closed"`.
 * - Focus moves to the first tabbable (or the content) on open, is trapped
 *   and loops while modal, and returns to the element focused when it opened
 *   (else the trigger) on close.
 * - Escape (topmost layer only) and pointer down outside (the overlay)
 *   request closing; nested overlays rendered inside are child layers.
 * - Modal: page scroll lock, siblings `aria-hidden`, outside pointer events
 *   disabled. Stays mounted during the `data-state="closed"` exit animation.
 */
export const DialogContent = ({
  ref,
  role = "dialog",
  forceMount = false,
  overlayClassName,
  overlayStyle,
  container,
  onOpenAutoFocus,
  onCloseAutoFocus,
  onEscapeKeyDown,
  onPointerDownOutside,
  onInteractOutside,
  children,
  ...rest
}: DialogContentProps) => {
  const context = useDialogContext("DialogContent");
  const {
    open,
    setOpen,
    modal,
    contentId,
    titleId,
    descriptionId,
    titles,
    descriptions,
    triggerRef,
    openerRef,
    contentRef,
  } = context;
  const [element, setElement] = useState<HTMLDivElement | null>(null);
  const mergedRef = useMergedRefs<HTMLDivElement>(
    useMergedRefs<HTMLDivElement>(
      setElement,
      contentRef as RefObject<HTMLDivElement | null>,
    ),
    ref,
  );
  const present = usePresence(open, element);
  const active = open && !!element;

  useDismissableLayer(element, {
    enabled: active,
    disableOutsidePointerEvents: modal,
    branches: () => [triggerRef.current],
    onEscapeKeyDown,
    onPointerDownOutside,
    // Focus is trapped while modal: never dismiss on focus outside.
    onFocusOutside: modal ? (event) => event.preventDefault() : undefined,
    onInteractOutside,
    onDismiss: () => setOpen(false),
  });
  useFocusScope(element, {
    enabled: active,
    trapped: modal,
    loop: true,
    restoreFocus: () => openerRef.current ?? triggerRef.current,
    onMountAutoFocus: onOpenAutoFocus,
    onUnmountAutoFocus: onCloseAutoFocus,
  });
  useScrollLock(active && modal);
  useHideOthers(element, active && modal);

  if (!present && !forceMount) return null;
  const state: DialogState = open ? "open" : "closed";
  return (
    <Portal container={container}>
      {modal && (
        <div
          className={overlayClassName}
          style={
            overlayStyle ? { ...OVERLAY_STYLE, ...overlayStyle } : OVERLAY_STYLE
          }
          data-state={state}
          aria-hidden="true"
        />
      )}
      <LayerContext.Provider value={element}>
        <div
          ref={mergedRef}
          id={contentId}
          role={role}
          aria-modal={modal || undefined}
          aria-labelledby={titles > 0 ? titleId : undefined}
          aria-describedby={descriptions > 0 ? descriptionId : undefined}
          tabIndex={-1}
          data-state={state}
          {...rest}
        >
          {children}
        </div>
      </LayerContext.Provider>
    </Portal>
  );
};
