// packages/web-components/src/components/pagination/pagination.ts
import {
  css,
  html,
  nothing,
  type PropertyValues,
  type TemplateResult,
} from "lit";
import { property, state } from "lit/decorators.js";
import { classMap } from "lit/directives/class-map.js";
import { repeat } from "lit/directives/repeat.js";
import styles from "@react-styles/components/Pagination/pagination.module.scss?inline";
import {
  canGoToPage,
  createPaginationMachine,
  getPaginationItems,
  getPaginationKeyTarget,
  getPaginationVisibleRange,
  getTotalPages,
  type PaginationMachineEvent,
  type PaginationMachineProps,
} from "@minerva/core";
import { MachineController } from "../../controllers/machine";
import { AriaController } from "../../internal/aria";
import { DEV, devWarn } from "../../internal/dev";
import { getDirection } from "../../internal/dom";
import { itemParts } from "../../internal/styling-hooks";
import {
  IconChevronLeft,
  IconChevronRight,
  IconEllipsis,
} from "../../internal/icons";
import { LocaleController } from "../../internal/locale";
import { MinervaElement, hostStyles } from "../../internal/minerva-element";
import { sharedStyles } from "../../internal/styles";

/** Kind of a pagination item (`itemRender` second argument) */
export type PaginationItemType =
  "page" | "prev" | "next" | "jump-prev" | "jump-next";
export type PaginationSize = "small" | "medium" | "large";
export type PaginationShape = "circle" | "rounded" | "square";
export type PaginationVariant = "solid" | "outline" | "ghost";

/** Content returned by the render callbacks */
export type PaginationRenderResult = string | number | Node | TemplateResult;

/** Detail of `minerva-page-change` */
export interface PaginationChangeDetail {
  page: number;
  pageSize: number;
}

/** Texts of `<minerva-pagination>`; omitted entries use the localized default */
export interface PaginationLabels {
  prev?: string;
  next?: string;
  jumpPrev?: string;
  jumpNext?: string;
  page?: (page: number) => string;
  jumpTo?: string;
  jumpToInput?: string;
  pageSize?: string;
  pageSizeOption?: (size: number) => string;
  currentPage?: string;
  total?: (total: number) => string;
  nav?: string;
}

/** `"10, 20 50"` <-> `[10, 20, 50]` */
const numberListConverter = {
  fromAttribute: (value: string | null) =>
    (value ?? "")
      .split(/[\s,]+/)
      .map((part) => parseInt(part, 10))
      .filter((n) => !isNaN(n) && n > 0),
  toAttribute: (value: number[]) => value.join(","),
};

interface Ripple {
  x: number;
  y: number;
  id: number;
  itemKey: string;
}

interface Item {
  key: string;
  type: PaginationItemType | "ellipsis";
  target: number;
}

/**
 * Page navigation (`<Pagination>` of React): page buttons with jump
 * items or a compact list with gaps, prev / next, a simple mode with a page
 * input, a quick jumper, a native page-size select and a total. Arrow keys
 * (swapped in RTL), Home and End on the page buttons change the page and
 * move focus to it; focus never gets lost when the focused button is
 * disabled or removed by a page change.
 *
 * @summary Page navigation with jumper, page size selector and total.
 * @tag minerva-pagination
 * @slot prev-icon - Icon of the previous-page button
 * @slot next-icon - Icon of the next-page button
 * @slot jump-prev-icon - Icon of the jump-backward item
 * @slot jump-next-icon - Icon of the jump-forward item
 * @csspart root - The `<nav>` landmark
 * @csspart item - A page / previous / next / jump button (the current page has aria-current=page)
 * @csspart item--current - Item state of `item`: current
 * @csspart item--disabled - Item state of `item`: disabled
 * @csspart total - The total text
 * @csspart jumper - The quick jumper label (wraps its input)
 * @csspart size-changer - The page size `<select>`
 * @csspart simple-input - The page input of the simple mode
 * @fires minerva-page-change - The user changed the page or the page size (`detail: { page, pageSize }`); cancelable: `preventDefault()` keeps the current page and size (controlled pattern)
 */
export class MinervaPagination extends MinervaElement {
  static override tagName = "minerva-pagination";
  static override styles = [
    hostStyles,
    css`
      :host {
        display: block;
      }
    `,
    sharedStyles(styles),
  ];

  /** Current page (1-based) */
  @property({ type: Number, reflect: true })
  current = 1;

  /** Total number of items */
  @property({ type: Number })
  total = 0;

  /** Number of items per page */
  @property({ type: Number, reflect: true, attribute: "page-size" })
  pageSize = 10;

  /** Disables the pagination */
  @property({ type: Boolean, reflect: true })
  disabled = false;

  /** Shows an input to jump to a page */
  @property({ type: Boolean, attribute: "show-quick-jumper" })
  showQuickJumper = false;

  /** Shows a page size selector (native `<select>`) */
  @property({ type: Boolean, attribute: "show-size-changer" })
  showSizeChanger = false;

  /** Options of the page size selector (attribute: `"10,20,50"`) */
  @property({ attribute: "page-size-options", converter: numberListConverter })
  pageSizeOptions: number[] = [10, 20, 50, 100];

  /** Shows the total number of items (customize it with `totalRender`) */
  @property({ type: Boolean, attribute: "show-total" })
  showTotal = false;

  /** Custom rendering of the total; `range` is the [first, last] item of the page */
  @property({ attribute: false })
  totalRender?: (
    total: number,
    range: [number, number],
  ) => PaginationRenderResult;

  /** Custom rendering of the page, prev / next and jump items */
  @property({ attribute: false })
  itemRender?: (
    page: number,
    type: PaginationItemType,
  ) => PaginationRenderResult;

  /** Pagination size */
  @property({ reflect: true })
  size: PaginationSize = "medium";

  /** Shape of the page items */
  @property({ reflect: true })
  shape: PaginationShape = "rounded";

  /** Visual style of the page items */
  @property({ reflect: true })
  variant: PaginationVariant = "solid";

  /** Simple mode: prev / next buttons with a page input */
  @property({ type: Boolean, reflect: true })
  simple = false;

  /** Pages on each side of the current one; switches to the compact list */
  @property({ type: Number, attribute: "sibling-count" })
  siblingCount?: number;

  /** Pages always shown at both ends of the compact list */
  @property({ type: Number, attribute: "boundary-count" })
  boundaryCount?: number;

  /** Hides the prev / next buttons */
  @property({ type: Boolean, attribute: "hide-edges" })
  hideEdges = false;

  /** Replaces the page buttons with a "current / total" counter */
  @property({ type: Boolean, attribute: "hide-numbers" })
  hideNumbers = false;

  /** Adapts the layout to small screens */
  @property({ type: Boolean, reflect: true })
  responsive = false;

  /** Custom texts and accessible labels (override the localized defaults) */
  @property({ attribute: false })
  labels?: PaginationLabels;

  @state()
  private jumpValue = "";

  @state()
  private simpleDraft: string | null = null;

  @state()
  private ripples: Ripple[] = [];

  private readonly aria = new AriaController(this);
  private readonly locale = new LocaleController(this);
  private nextRippleId = 0;
  private rippleTimer: ReturnType<typeof setTimeout> | undefined;
  private restoreFocus: { mode: "active" | "if-lost"; page: number } | null =
    null;

  // Page / page size changes go through core's pagination machine; the
  // `current` / `page-size` properties stay the source of truth (controlled
  // values, applied by `request` unless the event is canceled).
  private readonly pagination = new MachineController(
    this,
    createPaginationMachine(this.paginationProps()),
    // the template follows `current` / `page-size` (properties)
    () => false,
  );

  private paginationProps(): PaginationMachineProps {
    return {
      page: this.current,
      pageSize: this.pageSize,
      total: this.total,
      disabled: this.disabled,
      onChange: (page, pageSize) => this.request(page, pageSize),
    };
  }

  private send(event: PaginationMachineEvent) {
    this.pagination.sync(this.paginationProps());
    this.pagination.send(event);
  }

  /** Number of pages (at least 1). */
  get totalPages(): number {
    return getTotalPages(this.total, this.pageSize);
  }

  override disconnectedCallback(): void {
    super.disconnectedCallback();
    clearTimeout(this.rippleTimer);
  }

  /** Asks to change the page / size: emits, then applies unless canceled. */
  private request(page: number, pageSize: number): boolean {
    const detail: PaginationChangeDetail = { page, pageSize };
    if (!this.emit("minerva-page-change", detail, { cancelable: true })) {
      return false;
    }
    this.current = page;
    this.pageSize = pageSize;
    return true;
  }

  private changePage(target: number, focus: "active" | "if-lost" = "if-lost") {
    if (!canGoToPage(this.current, target, this.totalPages, this.disabled)) {
      return;
    }
    this.restoreFocus = { mode: focus, page: target };
    this.send({ type: "GOTO", page: target });
  }

  protected override willUpdate(changed: PropertyValues<this>): void {
    if (DEV && (changed.has("current") || changed.has("total"))) {
      if (this.total > 0 && this.current > this.totalPages) {
        devWarn(
          MinervaPagination.tagName,
          `current (${this.current}) is greater than the number of pages (${this.totalPages}).`,
        );
      }
    }
  }

  protected override updated(): void {
    // Focus management after a page change (the DOM is updated)
    const request = this.restoreFocus;
    this.restoreFocus = null;
    const root = this.shadowRoot;
    if (!request || !root || request.page !== this.current) return;
    const active = root.activeElement as HTMLElement | null;
    const lost = !active || (active as HTMLButtonElement).disabled === true;
    if (request.mode === "active" || lost) {
      const target =
        root.querySelector<HTMLElement>('[aria-current="page"]') ??
        root.querySelector<HTMLElement>("button:not(:disabled), input");
      target?.focus();
    }
  }

  private handleItemClick(target: number, itemKey: string, event: MouseEvent) {
    if (!canGoToPage(this.current, target, this.totalPages, this.disabled)) {
      return;
    }
    // Ripple only for pointer clicks (keyboard-triggered clicks have detail 0)
    if (event.detail > 0) {
      const rect = (event.currentTarget as HTMLElement).getBoundingClientRect();
      this.ripples = [
        ...this.ripples,
        {
          x: event.clientX - rect.left,
          y: event.clientY - rect.top,
          id: this.nextRippleId++,
          itemKey,
        },
      ];
      clearTimeout(this.rippleTimer);
      this.rippleTimer = setTimeout(() => (this.ripples = []), 1000);
    }
    this.changePage(target);
  }

  // Arrow keys / Home / End on the page buttons (inputs keep their keys)
  private handleKeyDown = (event: KeyboardEvent) => {
    let key = event.key;
    if (
      (key === "ArrowLeft" || key === "ArrowRight") &&
      getDirection(this) === "rtl"
    ) {
      key = key === "ArrowLeft" ? "ArrowRight" : "ArrowLeft";
    }
    const destination = getPaginationKeyTarget(
      key,
      this.current,
      this.totalPages,
    );
    if (destination === null) return;
    event.preventDefault();
    this.changePage(destination, "active");
  };

  private handleJump = (event: KeyboardEvent) => {
    if (event.key !== "Enter") return;
    event.preventDefault();
    const value = parseInt(this.jumpValue, 10);
    if (!isNaN(value) && value >= 1 && value <= this.totalPages) {
      this.changePage(value);
      this.jumpValue = "";
      (event.target as HTMLInputElement).value = "";
    }
  };

  private handleSizeChange = (event: Event) => {
    const select = event.target as HTMLSelectElement;
    const newSize = parseInt(select.value, 10);
    this.send({ type: "SET_PAGE_SIZE", pageSize: newSize });
    // canceled: the select shows the current size again
    if (this.pageSize !== newSize) select.value = String(this.pageSize);
  };

  private commitSimpleDraft = () => {
    const draft = this.simpleDraft;
    if (draft === null) return;
    this.simpleDraft = null;
    const value = parseInt(draft, 10);
    if (isNaN(value)) return;
    this.changePage(Math.min(Math.max(value, 1), this.totalPages));
  };

  private label(type: PaginationItemType, target: number): string {
    const labels = this.labels;
    const t = this.locale.t;
    switch (type) {
      case "prev":
        return labels?.prev ?? t("pagination.prev");
      case "next":
        return labels?.next ?? t("pagination.next");
      case "jump-prev":
        return labels?.jumpPrev ?? t("pagination.jumpPrev");
      case "jump-next":
        return labels?.jumpNext ?? t("pagination.jumpNext");
      default:
        return labels?.page?.(target) ?? t("pagination.page", { page: target });
    }
  }

  protected override hookStates() {
    return {
      disabled: this.disabled,
      size: this.size,
      shape: this.shape,
      variant: this.variant,
    };
  }

  private renderItem(item: Item) {
    const { type, target, key } = item;
    if (type === "ellipsis") {
      return html`<span class="ellipsis" aria-hidden="true">…</span>`;
    }
    const page = this.current;
    const isActive = type === "page" && target === page;
    const isDisabled =
      this.disabled ||
      (type === "prev"
        ? page <= 1
        : type === "next"
          ? page >= this.totalPages
          : false);
    let content: unknown;
    switch (type) {
      case "prev":
        content = html`<slot name="prev-icon">${IconChevronLeft}</slot>`;
        break;
      case "next":
        content = html`<slot name="next-icon">${IconChevronRight}</slot>`;
        break;
      case "jump-prev":
      case "jump-next":
        content = html`<span class="jumpWrapper"
          ><slot
            name=${type === "jump-prev" ? "jump-prev-icon" : "jump-next-icon"}
            >${IconEllipsis}</slot
          ><span class="jumpHint" aria-hidden="true"
            >${this.label(type, target)}</span
          ></span
        >`;
        break;
      default:
        content = target;
    }
    if (this.itemRender) content = this.itemRender(target, type);
    return html`<button
      type="button"
      part=${itemParts("item", { current: isActive, disabled: isDisabled })}
      data-key=${key}
      class=${classMap({
        item: true,
        active: isActive,
        disabled: isDisabled,
        prev: type === "prev",
        next: type === "next",
        jump: type === "jump-prev" || type === "jump-next",
      })}
      ?disabled=${isDisabled}
      aria-label=${this.label(type, target)}
      aria-current=${isActive ? "page" : nothing}
      @keydown=${this.handleKeyDown}
      @click=${(e: MouseEvent) => this.handleItemClick(target, key, e)}
    >
      ${content}
      ${this.ripples
        .filter((ripple) => ripple.itemKey === key)
        .map(
          (ripple) =>
            html`<span
              class="ripple"
              style="left:${ripple.x}px;top:${ripple.y}px"
              aria-hidden="true"
            ></span>`,
        )}
    </button>`;
  }

  /** Items of the page list (stable keys: the focused button survives). */
  private items(): Item[] {
    return getPaginationItems({
      page: this.current,
      totalPages: this.totalPages,
      siblingCount: this.siblingCount,
      boundaryCount: this.boundaryCount,
      hideEdges: this.hideEdges,
    }).map(({ key, kind, page }) => ({ key, type: kind, target: page }));
  }

  private renderPageList() {
    const page = this.current;
    const edge = (type: "prev" | "next") =>
      this.hideEdges
        ? nothing
        : this.renderItem({
            key: type,
            type,
            target: type === "prev" ? page - 1 : page + 1,
          });
    if (this.simple) {
      return html`${edge("prev")}
        <div class="simpleInput">
          <input
            part="simple-input"
            .value=${this.simpleDraft ?? String(page)}
            ?disabled=${this.disabled}
            aria-label=${
              this.labels?.currentPage ??
              this.locale.t("pagination.currentPage")
            }
            inputmode="numeric"
            @input=${(e: Event) =>
              (this.simpleDraft = (e.target as HTMLInputElement).value)}
            @keydown=${(e: KeyboardEvent) => {
              if (e.key !== "Enter") return;
              e.preventDefault();
              this.commitSimpleDraft();
            }}
            @blur=${this.commitSimpleDraft}
          />
          <span class="simpleDivider" aria-hidden="true">/</span>
          <span>${this.totalPages}</span>
        </div>
        ${edge("next")}`;
    }
    if (this.hideNumbers) {
      return html`${edge("prev")}
        <span class="counter" aria-live="polite"
          >${page} / ${this.totalPages}</span
        >
        ${edge("next")}`;
    }
    return repeat(
      this.items(),
      (item) => item.key,
      (item) => this.renderItem(item),
    );
  }

  protected override render() {
    const t = this.locale.t;
    const labels = this.labels;
    const total = this.total;
    const pageSize = this.pageSize;
    const visibleRange = getPaginationVisibleRange(
      this.current,
      pageSize,
      total,
    );
    const options = this.pageSizeOptions.includes(pageSize)
      ? this.pageSizeOptions
      : [...this.pageSizeOptions, pageSize].sort((a, b) => a - b);
    const sizeOptionLabel = (size: number) =>
      labels?.pageSizeOption?.(size) ??
      t("pagination.pageSizeOption", { size });

    return html`<nav
      part="root"
      aria-label=${this.aria.label ?? labels?.nav ?? t("pagination.nav")}
      class=${classMap({
        pagination: true,
        disabled: this.disabled,
        small: this.size === "small",
        large: this.size === "large",
        circle: this.shape === "circle",
        square: this.shape === "square",
        [this.variant]: true,
        responsive: this.responsive,
      })}
    >
      ${
        this.showTotal
          ? html`<div
              part="total"
              class="total"
              aria-live="polite"
              aria-atomic="true"
            >
              ${
                this.totalRender
                  ? this.totalRender(total, visibleRange)
                  : (labels?.total?.(total) ?? t("pagination.total", { total }))
              }
            </div>`
          : nothing
      }
      ${this.renderPageList()}
      ${
        this.showQuickJumper
          ? html`<label part="jumper" class="jumper">
              ${labels?.jumpTo ?? t("pagination.jumpTo")}
              <input
                .value=${this.jumpValue}
                ?disabled=${this.disabled}
                inputmode="numeric"
                aria-label=${labels?.jumpToInput ?? t("pagination.jumpToInput")}
                @input=${(e: Event) =>
                  (this.jumpValue = (e.target as HTMLInputElement).value)}
                @keydown=${this.handleJump}
              />
            </label>`
          : nothing
      }
      ${
        this.showSizeChanger
          ? html`<div class="sizeChanger">
              <select
                part="size-changer"
                ?disabled=${this.disabled}
                aria-label=${labels?.pageSize ?? t("pagination.pageSize")}
                @change=${this.handleSizeChange}
              >
                ${options.map(
                  (option) =>
                    html`<option
                      value=${option}
                      .selected=${option === pageSize}
                    >
                      ${sizeOptionLabel(option)}
                    </option>`,
                )}
              </select>
            </div>`
          : nothing
      }
    </nav>`;
  }
}

declare global {
  interface HTMLElementTagNameMap {
    "minerva-pagination": MinervaPagination;
  }
}

// packages/vue/src/components/Pagination/Pagination.vue
<script setup lang="ts">
/**
 * Pagination: page navigation (`<nav>` landmark) with page / prev / next /
 * jump buttons, an optional total, quick jumper, page size selector, simple
 * mode and compact page list. `v-model:current` / `v-model:pageSize`; the
 * `change` event receives (page, pageSize). Attributes fall through to the
 * `<nav>`.
 */
import {
  computed,
  nextTick,
  onBeforeUnmount,
  ref,
  useAttrs,
  watch,
  type FunctionalComponent,
  type VNodeChild,
} from "vue";
import {
  canGoToPage,
  createPaginationMachine,
  getPaginationItems,
  getPaginationKeyTarget,
  getPaginationVisibleRange,
  getTotalPages,
} from "@minerva/core";
import styles from "@react-styles/components/Pagination/pagination.module.scss";
import { hooks } from "../../internal/hooks";
import { useMachine } from "../../internal/machine";
import { logicalArrowKey } from "../../internal/direction";
import {
  IconChevronLeft,
  IconChevronRight,
  IconEllipsis,
} from "../../internal/icons";
import { useI18n } from "../../config/useI18n";
import type { PaginationItemType, PaginationProps } from "./types";

defineOptions({ name: "Pagination", inheritAttrs: false });

const props = withDefaults(defineProps<PaginationProps>(), {
  current: undefined,
  defaultCurrent: undefined,
  total: 0,
  pageSize: undefined,
  defaultPageSize: undefined,
  disabled: false,
  showQuickJumper: false,
  showSizeChanger: false,
  pageSizeOptions: () => [10, 20, 50, 100],
  itemRender: undefined,
  showTotal: false,
  totalRender: undefined,
  size: "medium",
  shape: "rounded",
  variant: "solid",
  simple: false,
  siblingCount: undefined,
  boundaryCount: undefined,
  hideEdges: false,
  hideNumbers: false,
  responsive: false,
  icons: undefined,
  labels: undefined,
});

const emit = defineEmits<{
  "update:current": [page: number];
  "update:pageSize": [pageSize: number];
  /** The page or the page size changed (a page size change resets to page 1) */
  change: [page: number, pageSize: number];
}>();

const slots = defineSlots<{
  /** Content of a page / prev / next / jump item (like `itemRender`) */
  item?: (props: { page: number; type: PaginationItemType }) => unknown;
  /** The total text (like `totalRender`) */
  total?: (props: { total: number; range: [number, number] }) => unknown;
  "prev-icon"?: () => unknown;
  "next-icon"?: () => unknown;
  "jump-prev-icon"?: () => unknown;
  "jump-next-icon"?: () => unknown;
  /** Visible text of the quick jumper (like `labels.jumpTo`) */
  "jump-to"?: () => unknown;
}>();

const attrs = useAttrs();
const { t } = useI18n();
const navRef = ref<HTMLElement | null>(null);

/** Renders a render-prop result (VNode, text, number) */
const Render: FunctionalComponent<{ content: VNodeChild }> = (p) =>
  p.content as never;
Render.props = ["content"];

// Page and page size (each controlled or not): core's pagination machine.
const { state, send } = useMachine(createPaginationMachine, () => ({
  page: props.current,
  defaultPage: props.defaultCurrent ?? 1,
  pageSize: props.pageSize,
  defaultPageSize: props.defaultPageSize ?? 10,
  total: props.total,
  disabled: props.disabled,
  onChange: (page: number, pageSize: number) => {
    if (page !== before.page) emit("update:current", page);
    if (pageSize !== before.pageSize) emit("update:pageSize", pageSize);
    emit("change", page, pageSize);
  },
}));

/** Values before an event (the machine reports the requested ones) */
let before = { ...state.value };
const dispatch = (event: Parameters<typeof send>[0]) => {
  before = { ...state.value };
  send(event);
};

const page = computed(() => state.value.page);
const currentPageSize = computed(() => state.value.pageSize);
// There is always at least one (possibly empty) page
const totalPages = computed(() =>
  getTotalPages(props.total, currentPageSize.value),
);

const jumpValue = ref("");
// Draft text of the simple-mode page input while the user is typing (null
// when not editing, so the input mirrors the current page)
const simpleDraft = ref<string | null>(null);

interface Ripple {
  x: number;
  y: number;
  id: number;
  itemKey: string;
}
const ripples = ref<Ripple[]>([]);
let nextRippleId = 0;
let rippleTimer: ReturnType<typeof setTimeout> | undefined;
watch(ripples, (list) => {
  clearTimeout(rippleTimer);
  if (list.length === 0) return;
  rippleTimer = setTimeout(() => (ripples.value = []), 1000);
});
onBeforeUnmount(() => clearTimeout(rippleTimer));

// Set when a page change should move focus to the active page button
// (keyboard navigation, or the focused button became disabled / removed)
let restoreFocus: { mode: "active" | "if-lost"; page: number } | null = null;

function changePage(target: number, focus: "active" | "if-lost" = "if-lost") {
  if (!canGoToPage(page.value, target, totalPages.value, props.disabled)) {
    return;
  }
  restoreFocus = { mode: focus, page: target };
  dispatch({ type: "GOTO", page: target });
  // A controlled parent that ignores the change: nothing to restore.
  if (page.value !== target) restoreFocus = null;
}

// Focus management after a page change (once the DOM is updated)
watch(
  page,
  () => {
    const request = restoreFocus;
    restoreFocus = null;
    const nav = navRef.value;
    if (!request || !nav || request.page !== page.value) return;
    const active = nav.ownerDocument.activeElement as HTMLElement | null;
    const lost =
      !active ||
      !nav.contains(active) ||
      (active as HTMLButtonElement).disabled === true;
    if (request.mode === "active" || lost) {
      const target =
        nav.querySelector<HTMLElement>('[aria-current="page"]') ??
        nav.querySelector<HTMLElement>("button:not(:disabled), input");
      target?.focus();
    }
  },
  { flush: "post" },
);

function onItemClick(target: number, itemKey: string, event: MouseEvent) {
  if (!canGoToPage(page.value, target, totalPages.value, props.disabled)) {
    return;
  }
  // Ripple only for pointer clicks (keyboard-triggered clicks have detail 0)
  if (event.detail > 0) {
    const rect = (event.currentTarget as HTMLElement).getBoundingClientRect();
    ripples.value = [
      ...ripples.value,
      {
        x: event.clientX - rect.left,
        y: event.clientY - rect.top,
        id: nextRippleId++,
        itemKey,
      },
    ];
  }
  changePage(target);
}

// Arrow keys / Home / End on the page buttons (inputs keep their keys);
// RTL: the previous page is on the right, so ArrowRight goes back.
function onItemKeydown(event: KeyboardEvent) {
  const destination = getPaginationKeyTarget(
    logicalArrowKey(event.key, event.currentTarget as Element),
    page.value,
    totalPages.value,
  );
  if (destination === null) return;
  event.preventDefault();
  changePage(destination, "active");
}

function onJumpKeydown(event: KeyboardEvent) {
  if (event.key !== "Enter") return;
  // Enter in a text input would implicitly submit an enclosing form
  event.preventDefault();
  const value = parseInt(jumpValue.value, 10);
  if (!isNaN(value) && value >= 1 && value <= totalPages.value) {
    changePage(value);
    jumpValue.value = "";
  }
}

async function onSizeChange(event: Event) {
  const select = event.target as HTMLSelectElement;
  dispatch({ type: "SET_PAGE_SIZE", pageSize: parseInt(select.value, 10) });
  // A controlled parent may keep its page size: mirror it again.
  await nextTick();
  select.value = String(currentPageSize.value);
}

// Commits the simple-mode page: valid values clamped, invalid ones reverted
function commitSimpleDraft() {
  if (simpleDraft.value === null) return;
  const value = parseInt(simpleDraft.value, 10);
  simpleDraft.value = null;
  if (isNaN(value)) return;
  changePage(Math.min(Math.max(value, 1), totalPages.value));
}

function onSimpleKeydown(event: KeyboardEvent) {
  if (event.key !== "Enter") return;
  // Do not implicitly submit an enclosing form
  event.preventDefault();
  commitSimpleDraft();
}

function itemLabel(type: PaginationItemType, target: number): string {
  const labels = props.labels;
  switch (type) {
    case "prev":
      return labels?.prev ?? t("pagination.prev");
    case "next":
      return labels?.next ?? t("pagination.next");
    case "jump-prev":
      return labels?.jumpPrev ?? t("pagination.jumpPrev");
    case "jump-next":
      return labels?.jumpNext ?? t("pagination.jumpNext");
    default:
      return labels?.page?.(target) ?? t("pagination.page", { page: target });
  }
}

interface Item {
  key: string;
  type: PaginationItemType;
  page: number;
  active: boolean;
  disabled: boolean;
  label: string;
}

const toItem = (target: number, type: PaginationItemType): Item => ({
  // Stable keys: the focused button must survive page changes
  key: type === "page" ? `page-${target}` : type,
  type,
  page: target,
  active: type === "page" && target === page.value,
  disabled:
    props.disabled ||
    (type === "prev"
      ? page.value <= 1
      : type === "next"
        ? page.value >= totalPages.value
        : false),
  label: itemLabel(type, target),
});

type Entry =
  | ({ kind: "item" } & Item)
  | { kind: "ellipsis" | "simple" | "counter"; key: string };

const edge = (type: "prev" | "next"): Entry[] =>
  props.hideEdges
    ? []
    : [
        {
          kind: "item",
          ...toItem(type === "prev" ? page.value - 1 : page.value + 1, type),
        },
      ];

/** Everything between the total and the jumper, in DOM order */
const entries = computed<Entry[]>(() => {
  if (props.simple || props.hideNumbers) {
    return [
      ...edge("prev"),
      {
        kind: props.simple ? "simple" : "counter",
        key: props.simple ? "simple" : "counter",
      },
      ...edge("next"),
    ];
  }
  return getPaginationItems({
    page: page.value,
    totalPages: totalPages.value,
    siblingCount: props.siblingCount,
    boundaryCount: props.boundaryCount,
    hideEdges: props.hideEdges,
  }).map((item) =>
    item.kind === "ellipsis"
      ? { kind: "ellipsis", key: item.key }
      : { kind: "item", ...toItem(item.page, item.kind) },
  );
});

const iconSlot = (type: PaginationItemType) =>
  type === "prev"
    ? "prev-icon"
    : type === "next"
      ? "next-icon"
      : type === "jump-prev"
        ? "jump-prev-icon"
        : "jump-next-icon";
const iconProp = (type: PaginationItemType): VNodeChild =>
  type === "prev"
    ? props.icons?.prev
    : type === "next"
      ? props.icons?.next
      : type === "jump-prev"
        ? props.icons?.jumpPrev
        : props.icons?.jumpNext;
const defaultIcon = (type: PaginationItemType) =>
  type === "prev"
    ? IconChevronLeft
    : type === "next"
      ? IconChevronRight
      : IconEllipsis;

const visibleRange = computed(() =>
  getPaginationVisibleRange(page.value, currentPageSize.value, props.total),
);
const totalContent = computed<VNodeChild>(() => {
  const range = visibleRange.value;
  if (typeof props.showTotal === "function") {
    return props.showTotal(props.total, range);
  }
  if (props.totalRender) return props.totalRender(props.total, range);
  return (
    props.labels?.total?.(props.total) ??
    t("pagination.total", { total: props.total })
  );
});

const sizeOptions = computed(() =>
  props.pageSizeOptions.includes(currentPageSize.value)
    ? props.pageSizeOptions
    : [...props.pageSizeOptions, currentPageSize.value].sort((a, b) => a - b),
);
const sizeOptionLabel = (size: number) =>
  props.labels?.pageSizeOption?.(size) ??
  t("pagination.pageSizeOption", { size });

const classes = computed(() => [
  styles.pagination,
  props.disabled && styles.disabled,
  props.size === "small" && styles.small,
  props.size === "large" && styles.large,
  props.shape === "circle" && styles.circle,
  props.shape === "square" && styles.square,
  styles[props.variant],
  props.responsive && styles.responsive,
]);

const navAttrs = computed(() => ({
  ...attrs,
  ...hooks("pagination", "root", {
    disabled: props.disabled,
    size: props.size,
    shape: props.shape,
    variant: props.variant,
  }),
}));

const itemClass = (item: Item) => [
  styles.item,
  item.active && styles.active,
  item.disabled && styles.disabled,
  item.type === "prev" && styles.prev,
  item.type === "next" && styles.next,
  (item.type === "jump-prev" || item.type === "jump-next") && styles.jump,
];
const itemHooks = (item: Item) =>
  hooks("pagination", "item", {
    current: item.active,
    disabled: item.disabled,
  });
const ripplesOf = (key: string) =>
  ripples.value.filter((ripple) => ripple.itemKey === key);
</script>

<template>
  <nav
    ref="navRef"
    :aria-label="labels?.nav ?? t('pagination.nav')"
    :class="classes"
    v-bind="navAttrs"
  >
    <div
      v-if="showTotal !== false"
      :class="styles.total"
      aria-live="polite"
      aria-atomic="true"
      v-bind="hooks('pagination', 'total')"
    >
      <slot name="total" :total="total" :range="visibleRange">
        <Render :content="totalContent" />
      </slot>
    </div>

    <template v-for="entry in entries" :key="entry.key">
      <button
        v-if="entry.kind === 'item'"
        type="button"
        :class="itemClass(entry)"
        :disabled="entry.disabled"
        :aria-label="entry.label"
        :aria-current="entry.active ? 'page' : undefined"
        v-bind="itemHooks(entry)"
        @keydown="onItemKeydown"
        @click="onItemClick(entry.page, entry.key, $event)"
      >
        <Render
          v-if="itemRender"
          :content="itemRender(entry.page, entry.type)"
        />
        <slot v-else name="item" :page="entry.page" :type="entry.type">
          <template v-if="entry.type === 'page'">{{ entry.page }}</template>
          <slot
            v-else-if="entry.type === 'prev' || entry.type === 'next'"
            :name="iconSlot(entry.type)"
          >
            <Render
              v-if="iconProp(entry.type)"
              :content="iconProp(entry.type)"
            />
            <component
              :is="defaultIcon(entry.type)"
              v-else
              aria-hidden="true"
            />
          </slot>
          <span v-else :class="styles.jumpWrapper">
            <slot :name="iconSlot(entry.type)">
              <Render
                v-if="iconProp(entry.type)"
                :content="iconProp(entry.type)"
              />
              <component
                :is="defaultIcon(entry.type)"
                v-else
                aria-hidden="true"
              />
            </slot>
            <span :class="styles.jumpHint" aria-hidden="true">{{
              entry.label
            }}</span>
          </span>
        </slot>
        <span
          v-for="ripple in ripplesOf(entry.key)"
          :key="ripple.id"
          :class="styles.ripple"
          :style="{ left: `${ripple.x}px`, top: `${ripple.y}px` }"
          aria-hidden="true"
        />
      </button>
      <span
        v-else-if="entry.kind === 'ellipsis'"
        :class="styles.ellipsis"
        aria-hidden="true"
        >…</span
      >
      <div v-else-if="entry.kind === 'simple'" :class="styles.simpleInput">
        <input
          v-bind="hooks('pagination', 'simple-input')"
          :value="simpleDraft ?? String(page)"
          :disabled="disabled"
          :aria-label="labels?.currentPage ?? t('pagination.currentPage')"
          inputmode="numeric"
          @input="simpleDraft = ($event.target as HTMLInputElement).value"
          @keydown="onSimpleKeydown"
          @blur="commitSimpleDraft"
        />
        <span :class="styles.simpleDivider" aria-hidden="true">/</span>
        <span>{{ totalPages }}</span>
      </div>
      <span v-else :class="styles.counter" aria-live="polite"
        >{{ page }} / {{ totalPages }}</span
      >
    </template>

    <label
      v-if="showQuickJumper"
      :class="styles.jumper"
      v-bind="hooks('pagination', 'jumper')"
    >
      <slot name="jump-to">{{ labels?.jumpTo ?? t("pagination.jumpTo") }}</slot>
      <input
        v-model="jumpValue"
        :disabled="disabled"
        inputmode="numeric"
        :aria-label="labels?.jumpToInput ?? t('pagination.jumpToInput')"
        @keydown="onJumpKeydown"
      />
    </label>

    <div v-if="showSizeChanger" :class="styles.sizeChanger">
      <select
        v-bind="hooks('pagination', 'size-changer')"
        :value="currentPageSize"
        :disabled="disabled"
        :aria-label="labels?.pageSize ?? t('pagination.pageSize')"
        @change="onSizeChange"
      >
        <option v-for="option in sizeOptions" :key="option" :value="option">
          {{ sizeOptionLabel(option) }}
        </option>
      </select>
    </div>
  </nav>
</template>
