// packages/lib-core/src/components/PageTabs/PageTabs.tsx
import { useCallback, useEffect, useRef, useState } from "react";
import { cn } from "../../utils/cn";
import { IconChevronLeft, IconChevronRight } from "../../internal/icons";
import IconButton from "../IconButton/IconButton";
import Tooltip from "../Tooltip/Tooltip";
import useI18n from "../../hooks/useI18n";
import type { PageTabProps, PageTabsProps } from "./types";
import { getDirection } from "../../internal/direction";
import { hooks } from "../../internal/stylingHooks";
import styles from "./pageTabs.module.scss";

const TAB_SELECTOR = `.${styles.pageTab}`;

interface ScrollState {
  overflow: boolean;
  left: boolean;
  right: boolean;
  /** Right-to-left layout: the start (first) scroll button is on the right. */
  rtl: boolean;
}

/**
 * PageTabs: a strip of open application pages (route navigation, not an
 * ARIA tablist). The application owns routes, closing and leave guards.
 * Overflowing items scroll horizontally with optional scroll buttons and the
 * current item is kept in view.
 */
export const PageTabs = ({
  "aria-label": ariaLabel,
  activeValue,
  children,
  actions,
  scrollLeftLabel,
  scrollRightLabel,
  className,
  onFocusCapture,
  onContextMenuCapture,
  ...rest
}: PageTabsProps) => {
  const { t } = useI18n();
  const viewport = useRef<HTMLDivElement>(null);
  const list = useRef<HTMLDivElement>(null);
  const focused = useRef<HTMLElement | null>(null);
  const previousItems = useRef<string | null>(null);
  const leftButton = useRef<HTMLButtonElement>(null);
  const rightButton = useRef<HTMLButtonElement>(null);
  /** Scroll button last used: it may get disabled while it has focus */
  const movedWith = useRef<HTMLButtonElement | null>(null);
  const [scroll, setScroll] = useState<ScrollState>({
    overflow: false,
    left: false,
    right: false,
    rtl: false,
  });

  const measure = useCallback(() => {
    const el = viewport.current;
    if (!el) return;
    // In RTL, scrollLeft runs from 0 (start, right edge) to -(max).
    const rtl = getDirection(el) === "rtl";
    const max = el.scrollWidth - el.clientWidth;
    const next = {
      overflow: el.scrollWidth > el.clientWidth + 1,
      left: rtl ? el.scrollLeft > -max + 1 : el.scrollLeft > 1,
      right: rtl ? el.scrollLeft < -1 : el.scrollLeft < max - 1,
      rtl,
    };
    setScroll((prev) =>
      prev.overflow === next.overflow &&
      prev.left === next.left &&
      prev.right === next.right &&
      prev.rtl === next.rtl
        ? prev
        : next,
    );
  }, []);

  const revealActive = useCallback(() => {
    const el = viewport.current;
    if (!el) return;
    const active = list.current?.querySelector<HTMLElement>(
      `${TAB_SELECTOR}[data-active]`,
    );
    if (active) {
      const view = el.getBoundingClientRect();
      const item = active.getBoundingClientRect();
      // Oversized items always align their start edge
      if (item.width > view.width) el.scrollLeft += item.left - view.left;
      else if (item.left < view.left) el.scrollLeft -= view.left - item.left;
      else if (item.right > view.right)
        el.scrollLeft += item.right - view.right;
    }
    measure();
  }, [measure]);

  // After every render: reveal the active item when the items changed (not on
  // unrelated re-renders, to keep manual scrolling), and give focus back to
  // the current page when the focused item was removed.
  useEffect(() => {
    const items = JSON.stringify([
      activeValue,
      ...Array.from(
        list.current?.querySelectorAll<HTMLElement>(TAB_SELECTOR) ?? [],
        (item) => [item.dataset.value, item.dataset.active],
      ),
    ]);
    if (items !== previousItems.current) {
      previousItems.current = items;
      revealActive();
    }
    if (
      focused.current &&
      !focused.current.isConnected &&
      document.activeElement === document.body
    ) {
      list.current
        ?.querySelector<HTMLButtonElement>('[aria-current="page"]')
        ?.focus({ preventScroll: true });
    }
    // A scroll button activated from the keyboard is disabled once its end
    // is reached, which would drop focus to <body>: hand focus to the
    // opposite scroll button instead.
    const from = movedWith.current;
    if (from?.disabled) {
      movedWith.current = null;
      if (
        document.activeElement === from ||
        document.activeElement === document.body
      ) {
        (from === leftButton.current ? rightButton : leftButton).current?.focus(
          { preventScroll: true },
        );
      }
    }
  });

  useEffect(() => {
    if (typeof ResizeObserver === "undefined") return;
    const observer = new ResizeObserver(() => revealActive());
    if (viewport.current) observer.observe(viewport.current);
    if (list.current) observer.observe(list.current);
    return () => observer.disconnect();
  }, [revealActive]);

  const move = (direction: number) => {
    const el = viewport.current;
    /* v8 ignore next */
    if (!el) return;
    movedWith.current =
      direction < 0 ? leftButton.current : rightButton.current;
    el.scrollLeft += direction * Math.max(1, el.clientWidth * 0.8);
    measure();
  };

  // Physical buttons: the left one always sits on the left edge (it comes
  // last in the DOM in RTL, where the flex row is reversed).
  const scrollLeft = (
    <IconButton
      ref={leftButton}
      className={styles.scroll}
      aria-label={scrollLeftLabel ?? t("pageTabs.scrollLeft")}
      size="small"
      shape="square"
      disabled={!scroll.left}
      onClick={() => move(-1)}
      icon={<IconChevronLeft size={18} aria-hidden="true" />}
    />
  );
  const scrollRight = (
    <IconButton
      ref={rightButton}
      className={styles.scroll}
      aria-label={scrollRightLabel ?? t("pageTabs.scrollRight")}
      size="small"
      shape="square"
      disabled={!scroll.right}
      onClick={() => move(1)}
      icon={<IconChevronRight size={18} aria-hidden="true" />}
    />
  );

  return (
    <nav
      {...rest}
      aria-label={ariaLabel}
      className={cn(styles.pageTabs, className)}
      onFocusCapture={(event) => {
        // Portal events (e.g. a context menu) bubble through the nav: only
        // remember focus that is really inside it.
        if (event.currentTarget.contains(event.target)) {
          focused.current = event.target.closest(TAB_SELECTOR)
            ? event.target
            : null;
        }
        onFocusCapture?.(event);
      }}
      onContextMenuCapture={(event) => {
        const item = (event.target as Element).closest(TAB_SELECTOR);
        if (item) {
          focused.current = item.querySelector<HTMLButtonElement>(
            `.${styles.trigger}`,
          );
        }
        onContextMenuCapture?.(event);
      }}
      {...hooks("page-tabs", "root")}
    >
      {scroll.overflow && (scroll.rtl ? scrollRight : scrollLeft)}
      <div
        ref={viewport}
        className={styles.viewport}
        onScroll={measure}
        {...hooks("page-tabs", "viewport")}
      >
        <div ref={list} className={styles.list} {...hooks("page-tabs", "list")}>
          {children}
        </div>
      </div>
      {scroll.overflow && (scroll.rtl ? scrollLeft : scrollRight)}
      {actions && (
        <div className={styles.actions} {...hooks("page-tabs", "actions")}>
          {actions}
        </div>
      )}
    </nav>
  );
};

/**
 * PageTab: one open page. The label button selects it; `action` (e.g. a
 * close button) is a sibling control, never nested inside the label button.
 * Ref and extra props (e.g. onContextMenu) reach the item wrapper.
 */
export const PageTab = ({
  ref,
  value,
  label,
  active = false,
  disabled = false,
  icon,
  action,
  onSelect,
  className,
  ...rest
}: PageTabProps) => (
  <div
    {...rest}
    ref={ref}
    className={cn(styles.pageTab, className)}
    data-value={value}
    data-active={active || undefined}
    {...hooks("page-tab", "root", { current: active, disabled })}
  >
    <Tooltip
      content={label}
      placement="bottom-start"
      variant="glass"
      disabled={disabled}
      asChild
    >
      <button
        type="button"
        className={styles.trigger}
        {...hooks("page-tab", "trigger")}
        aria-current={active ? "page" : undefined}
        disabled={disabled}
        onClick={onSelect}
      >
        {icon && (
          <span
            className={styles.icon}
            aria-hidden="true"
            {...hooks("page-tab", "icon")}
          >
            {icon}
          </span>
        )}
        <span className={styles.label} {...hooks("page-tab", "label")}>
          {label}
        </span>
      </button>
    </Tooltip>
    {action && (
      <span className={styles.action} {...hooks("page-tab", "action")}>
        {action}
      </span>
    )}
  </div>
);

export default PageTabs;

// packages/lib-web-components/src/components/page-tabs/page-tabs.ts
import { css, html, nothing, type PropertyValues } from "lit";
import { property, query, state } from "lit/decorators.js";
import { classMap } from "lit/directives/class-map.js";
import styles from "@lib-core-styles/components/PageTabs/pageTabs.module.scss?inline";
import iconButtonStyles from "@lib-core-styles/components/IconButton/iconButton.module.scss?inline";
import { AriaController } from "../../internal/aria";
import { DEV, devWarn } from "../../internal/dev";
import { getDirection } from "../../internal/dom";
import { IconChevronLeft, IconChevronRight, IconX } from "../../internal/icons";
import { LocaleController } from "../../internal/locale";
import { MinervaElement, hostStyles } from "../../internal/minerva-element";
import { HasSlotController } from "../../internal/slots";
import { sharedStyles } from "../../internal/styles";

interface ScrollState {
  overflow: boolean;
  left: boolean;
  right: boolean;
  /** Right-to-left layout: the start (first) scroll button is on the right */
  rtl: boolean;
}

/** Classes of lib-core's small square ghost IconButton (scroll / close buttons) */
const iconButtonClasses = (disabled: boolean, extra: string) => ({
  iconButton: true,
  neutral: true,
  "variant-ghost": true,
  small: true,
  square: true,
  disabled,
  [extra]: true,
});

/**
 * A strip of open application pages (`<PageTabs>` of lib-core): route
 * navigation, not an ARIA tablist. The application owns routes, closing and
 * leave guards. Overflowing items scroll horizontally with scroll buttons
 * and the current item (`active-value`) is kept in view; when the focused
 * item is removed, focus goes back to the current page.
 *
 * @summary Strip of open pages with overflow scrolling and closable items.
 * @tag minerva-page-tabs
 * @slot - `<minerva-page-tab>` items
 * @slot actions - Global actions after the scrollable list (e.g. a page menu)
 * @csspart base - The `<nav>` landmark
 * @csspart viewport - The scrolling viewport
 * @csspart list - The item list
 * @csspart scroll-button - The scroll left / right buttons
 * @csspart actions - The actions wrapper
 * @fires minerva-select - Re-dispatched from `<minerva-page-tab>`: a page was chosen (`detail: { value }`)
 * @fires minerva-close - Re-dispatched from `<minerva-page-tab>`: the close button of a page was activated (`detail: { value }`)
 */
export class MinervaPageTabs extends MinervaElement {
  static override tagName = "minerva-page-tabs";
  static override styles = [
    hostStyles,
    css`
      :host {
        display: block;
        min-width: 0;
      }
    `,
    sharedStyles(iconButtonStyles),
    sharedStyles(styles),
  ];

  /**
   * Value of the current route's item: it gets `active` and is scrolled into
   * view when it (or the set of items) changes
   */
  @property({ reflect: true, attribute: "active-value" })
  activeValue?: string;

  /** Accessible label of the "scroll left" button (default localized) */
  @property({ attribute: "scroll-left-label" })
  scrollLeftLabel?: string;

  /** Accessible label of the "scroll right" button (default localized) */
  @property({ attribute: "scroll-right-label" })
  scrollRightLabel?: string;

  @state()
  private scrollState: ScrollState = {
    overflow: false,
    left: false,
    right: false,
    rtl: false,
  };

  @query(".viewport")
  private viewport!: HTMLElement;

  @query(".scroll-left")
  private leftButton?: HTMLButtonElement;

  @query(".scroll-right")
  private rightButton?: HTMLButtonElement;

  private readonly aria = new AriaController(this);
  private readonly locale = new LocaleController(this);
  private readonly slots = new HasSlotController(this);
  private focused: HTMLElement | null = null;
  private previousItems: string | null = null;
  private movedWith: "left" | "right" | null = null;
  private mutations: MutationObserver | null = null;
  private resize: ResizeObserver | null = null;

  /** The `<minerva-page-tab>` items. */
  get items(): MinervaPageTab[] {
    return Array.from(this.children).filter(
      (el): el is MinervaPageTab => el instanceof MinervaPageTab,
    );
  }

  override connectedCallback(): void {
    super.connectedCallback();
    this.addEventListener("focusin", this.handleFocusIn);
    this.addEventListener("minerva-select", this.handleSelect);
    if (typeof MutationObserver !== "undefined") {
      this.mutations = new MutationObserver(() => this.itemsChanged());
      this.mutations.observe(this, {
        childList: true,
        attributes: true,
        attributeFilter: ["value", "active", "disabled"],
        subtree: true,
      });
    }
  }

  override disconnectedCallback(): void {
    super.disconnectedCallback();
    this.removeEventListener("focusin", this.handleFocusIn);
    this.removeEventListener("minerva-select", this.handleSelect);
    this.mutations?.disconnect();
    this.mutations = null;
    this.resize?.disconnect();
    this.resize = null;
  }

  protected override firstUpdated(): void {
    if (typeof ResizeObserver !== "undefined") {
      this.resize = new ResizeObserver(() => this.revealActive());
      this.resize.observe(this.viewport);
    }
  }

  protected override updated(changed: PropertyValues<this>): void {
    if (DEV && !this.aria.label) {
      devWarn(
        MinervaPageTabs.tagName,
        'set aria-label (e.g. "Open pages") to name the navigation landmark.',
      );
    }
    if (changed.has("activeValue")) this.itemsChanged();
    // A scroll button activated from the keyboard is disabled once its end
    // is reached, which would drop focus: hand it to the opposite button.
    const from = this.movedWith;
    if (from) {
      const button = from === "left" ? this.leftButton : this.rightButton;
      if (button?.disabled) {
        this.movedWith = null;
        const active = this.shadowRoot?.activeElement;
        if (!active || active === button) {
          (from === "left" ? this.rightButton : this.leftButton)?.focus({
            preventScroll: true,
          });
        }
      }
    }
  }

  private handleFocusIn = (event: FocusEvent) => {
    const target = event.target as Element;
    this.focused =
      target instanceof MinervaPageTab && this.items.includes(target)
        ? target
        : null;
  };

  private handleSelect = (event: Event) => {
    const item = event.target;
    if (
      !(item instanceof MinervaPageTab) ||
      !this.items.includes(item) ||
      event.defaultPrevented
    ) {
      return;
    }
    // a page tab asks first (cancelable), then the strip follows it
    queueMicrotask(() => {
      if (!event.defaultPrevented) this.activeValue = item.value;
    });
  };

  /** Pushes `active` to the items, reveals the active one, restores focus. */
  private itemsChanged() {
    const items = this.items;
    if (this.activeValue !== undefined) {
      for (const item of items) item.active = item.value === this.activeValue;
    }
    const key = JSON.stringify([
      this.activeValue,
      ...items.map((item) => [item.value, item.active]),
    ]);
    if (key !== this.previousItems) {
      this.previousItems = key;
      this.revealActive();
    }
    const focused = this.focused;
    if (focused && !focused.isConnected) {
      this.focused = null;
      const active = document.activeElement;
      if (!active || active === document.body || !active.isConnected) {
        items.find((item) => item.active)?.focus({ preventScroll: true });
      }
    }
  }

  private measure = () => {
    const el = this.viewport;
    if (!el) return;
    // In RTL, scrollLeft runs from 0 (start, right edge) to -(max).
    const rtl = getDirection(this) === "rtl";
    const max = el.scrollWidth - el.clientWidth;
    const next: ScrollState = {
      overflow: el.scrollWidth > el.clientWidth + 1,
      left: rtl ? el.scrollLeft > -max + 1 : el.scrollLeft > 1,
      right: rtl ? el.scrollLeft < -1 : el.scrollLeft < max - 1,
      rtl,
    };
    const prev = this.scrollState;
    if (
      prev.overflow !== next.overflow ||
      prev.left !== next.left ||
      prev.right !== next.right ||
      prev.rtl !== next.rtl
    ) {
      this.scrollState = next;
    }
  };

  private revealActive() {
    const el = this.viewport;
    if (!el) return;
    const activeItem = this.items.find((item) => item.active);
    const active = activeItem?.surface;
    if (activeItem && !active) {
      // not rendered yet (first render / just added)
      void activeItem.updateComplete.then(() => {
        if (activeItem.surface) this.revealActive();
      });
    }
    if (active) {
      const view = el.getBoundingClientRect();
      const item = active.getBoundingClientRect();
      // Oversized items always align their start edge
      if (item.width > view.width) el.scrollLeft += item.left - view.left;
      else if (item.left < view.left) el.scrollLeft -= view.left - item.left;
      else if (item.right > view.right)
        el.scrollLeft += item.right - view.right;
    }
    this.measure();
  }

  private move(direction: number) {
    const el = this.viewport;
    if (!el) return;
    this.movedWith = direction < 0 ? "left" : "right";
    el.scrollLeft += direction * Math.max(1, el.clientWidth * 0.8);
    this.measure();
  }

  private renderScrollButton(side: "left" | "right") {
    const left = side === "left";
    const label = left
      ? (this.scrollLeftLabel ?? this.locale.t("pageTabs.scrollLeft"))
      : (this.scrollRightLabel ?? this.locale.t("pageTabs.scrollRight"));
    const disabled = left ? !this.scrollState.left : !this.scrollState.right;
    return html`<button
      type="button"
      part="scroll-button"
      class=${classMap({
        ...iconButtonClasses(disabled, "scroll"),
        [`scroll-${side}`]: true,
      })}
      aria-label=${label}
      ?disabled=${disabled}
      tabindex=${disabled ? -1 : 0}
      @click=${() => this.move(left ? -1 : 1)}
    >
      ${left ? IconChevronLeft : IconChevronRight}
    </button>`;
  }

  protected override render() {
    const { overflow, rtl } = this.scrollState;
    const left = () => this.renderScrollButton("left");
    const right = () => this.renderScrollButton("right");
    return html`<nav
      part="base"
      class="pageTabs"
      aria-label=${this.aria.label ?? nothing}
    >
      ${overflow ? (rtl ? right() : left()) : nothing}
      <div part="viewport" class="viewport" @scroll=${this.measure}>
        <div part="list" class="list">
          <slot @slotchange=${() => this.itemsChanged()}></slot>
        </div>
      </div>
      ${overflow ? (rtl ? left() : right()) : nothing}
      ${
        this.slots.test("actions")
          ? html`<div part="actions" class="actions">
              <slot name="actions"></slot>
            </div>`
          : nothing
      }
    </nav>`;
  }
}

/**
 * One open page of `<minerva-page-tabs>` (`<PageTab>` of lib-core). The label
 * button selects it (`aria-current="page"` while `active`); the `action`
 * slot (or the built-in close button of `closable`) is a separate control,
 * never nested inside the label button.
 *
 * @summary An open page of `<minerva-page-tabs>`.
 * @tag minerva-page-tab
 * @slot icon - Icon displayed before the label
 * @slot action - Separate control next to the label (e.g. a close button)
 * @csspart base - The item wrapper
 * @csspart trigger - The label `<button>`
 * @csspart label - The (truncated) label
 * @csspart close-button - The built-in close button (`closable`)
 * @fires minerva-select - The label button was activated (`detail: { value }`); cancelable: `preventDefault()` keeps the strip's `active-value`
 * @fires minerva-close - The built-in close button was activated (`detail: { value }`); remove the element to close the page
 */
export class MinervaPageTab extends MinervaElement {
  static override tagName = "minerva-page-tab";
  static override shadowRootOptions = {
    ...MinervaElement.shadowRootOptions,
    delegatesFocus: true,
  };
  static override styles = [
    hostStyles,
    css`
      :host {
        display: contents;
      }
      .icon ::slotted(svg) {
        width: 16px;
        height: 16px;
      }
    `,
    sharedStyles(iconButtonStyles),
    sharedStyles(styles),
  ];

  /** Identifier of the page */
  @property({ reflect: true })
  value = "";

  /** Title of the page; truncated with an ellipsis (full text in `title`) */
  @property()
  label = "";

  /** Marks the item as the current page (`aria-current="page"`) */
  @property({ type: Boolean, reflect: true })
  active = false;

  /** Disables the label button (the separate action keeps its own state) */
  @property({ type: Boolean, reflect: true })
  disabled = false;

  /** Renders a built-in close button (fires `minerva-close`) */
  @property({ type: Boolean, reflect: true })
  closable = false;

  /** Accessible label of the close button (default localized "Close <label>") */
  @property({ attribute: "close-label" })
  closeLabel?: string;

  @query(".trigger")
  private trigger?: HTMLButtonElement;

  @query(".pageTab")
  private wrapper?: HTMLElement;

  private readonly locale = new LocaleController(this);
  private readonly slots = new HasSlotController(this);

  /** @internal The element carrying the item geometry. */
  get surface(): HTMLElement | null {
    return this.wrapper ?? null;
  }

  /** Focuses the label button. */
  override focus(options?: FocusOptions): void {
    this.trigger?.focus(options);
  }

  private handleSelect() {
    if (this.disabled) return;
    this.emit("minerva-select", { value: this.value }, { cancelable: true });
  }

  private handleClose() {
    this.emit("minerva-close", { value: this.value });
  }

  protected override updated(): void {
    if (DEV && !this.label) {
      devWarn(MinervaPageTab.tagName, "set label to name the page.");
    }
  }

  protected override render() {
    return html`<div
      part="base"
      class="pageTab"
      data-value=${this.value}
      ?data-active=${this.active}
      ?data-disabled=${this.disabled}
    >
      <button
        type="button"
        part="trigger"
        class="trigger"
        title=${this.label || nothing}
        aria-current=${this.active ? "page" : nothing}
        ?disabled=${this.disabled}
        @click=${this.handleSelect}
      >
        ${
          this.slots.test("icon")
            ? html`<span class="icon" aria-hidden="true"
                ><slot name="icon"></slot
              ></span>`
            : nothing
        }
        <span part="label" class="label">${this.label}</span>
      </button>
      ${
        this.closable || this.slots.test("action")
          ? html`<span class="action"
              ><slot name="action"></slot>${
                this.closable
                  ? html`<button
                      type="button"
                      part="close-button"
                      class=${classMap(iconButtonClasses(false, "close"))}
                      aria-label=${
                        this.closeLabel ??
                        this.locale.t("pageTabs.close", {
                          label: this.label,
                          defaultValue: "Close {{label}}",
                        })
                      }
                      @click=${this.handleClose}
                    >
                      ${IconX}
                    </button>`
                  : nothing
              }</span
            >`
          : nothing
      }
    </div>`;
  }
}

declare global {
  interface HTMLElementTagNameMap {
    "minerva-page-tabs": MinervaPageTabs;
    "minerva-page-tab": MinervaPageTab;
  }
}
