// packages/lib-web-components/src/components/badge/badge.ts
import { css, html, nothing } from "lit";
import { property } from "lit/decorators.js";
import { classMap } from "lit/directives/class-map.js";
import { styleMap } from "lit/directives/style-map.js";
import type { ColorScheme } from "@minerva/core";
import styles from "@lib-core-styles/components/Badge/badge.module.scss?inline";
import { AriaController } from "../../internal/aria";
import { DEV, devWarn } from "../../internal/dev";
import { LocaleController } from "../../internal/locale";
import { MinervaElement, hostStyles } from "../../internal/minerva-element";
import { HasSlotController } from "../../internal/slots";
import { sharedStyles } from "../../internal/styles";

export type BadgeVariant = "solid" | "subtle" | "outline";
export type BadgeSize = "small" | "medium" | "large";
export type BadgePosition =
  "top-right" | "top-left" | "bottom-right" | "bottom-left";

/**
 * A small count or status indicator (`<Badge>` of lib-core).
 *
 * - With element children (default slot) the badge is attached to a corner
 *   of them (`position`), inside a relatively positioned wrapper; its text
 *   comes from `content` / the `content` slot (localized "Badge" otherwise).
 * - Without children, or with plain text children, it is a standalone badge
 *   rendered inline (the text is the badge's content).
 *
 * The badge is a polite `role="status"` region by default; set
 * `badge-role="presentation"` when it must not be announced.
 *
 * @summary Count / status indicator, standalone or attached to an element.
 * @tag minerva-badge
 * @slot - Element the badge is attached to, or the text of a standalone badge
 * @slot content - Rich content of the badge (instead of `content`)
 * @slot icon - Icon displayed before the content
 * @csspart base - The root (the badge, or the wrapper when attached)
 * @csspart badge - The badge itself
 * @csspart icon - The icon wrapper
 */
export class MinervaBadge extends MinervaElement {
  static override tagName = "minerva-badge";
  static override styles = [
    hostStyles,
    css`
      :host {
        display: inline-flex;
        vertical-align: middle;
      }
    `,
    sharedStyles(styles),
  ];

  /** Semantic color */
  @property({ reflect: true })
  color: ColorScheme = "primary";

  /** Visual style: solid (filled), subtle (tinted) or outline (bordered) */
  @property({ reflect: true })
  variant: BadgeVariant = "solid";

  /** Badge size */
  @property({ reflect: true })
  size: BadgeSize = "medium";

  /** Text of the badge (count, short text); use the `content` slot for rich content */
  @property()
  content?: string;

  /** Corner of the children the badge is placed on (ignored by standalone badges) */
  @property({ reflect: true })
  position: BadgePosition = "top-right";

  /** Renders a small dot instead of content */
  @property({ type: Boolean, reflect: true })
  dot = false;

  /** Custom border radius (CSS value) */
  @property({ attribute: "border-radius" })
  borderRadius?: string;

  /** Custom border width (CSS value) */
  @property({ attribute: "border-width" })
  borderWidth?: string;

  /** ARIA role of the badge ("presentation" / "none" to stop announcing it) */
  @property({ attribute: "badge-role" })
  badgeRole = "status";

  private readonly locale = new LocaleController(this);
  private readonly aria = new AriaController(this);
  private readonly slots = new HasSlotController(this);

  /** Whether the default slot holds elements (not only text) */
  private hasElementChildren(): boolean {
    return Array.from(this.children).some(
      (child) =>
        !child.hasAttribute("slot") || child.getAttribute("slot") === "",
    );
  }

  protected override updated(): void {
    if (
      DEV &&
      this.dot &&
      !this.aria.label &&
      !["presentation", "none"].includes(this.badgeRole)
    ) {
      devWarn(
        MinervaBadge.tagName,
        'a dot badge has no text: set aria-label (e.g. "New messages") or badge-role="presentation".',
      );
    }
  }

  protected override render() {
    const hasChildren = this.slots.test("[default]");
    const textChildren = hasChildren && !this.hasElementChildren();
    const hasContent =
      (this.content !== undefined && this.content !== null) ||
      this.slots.test("content");
    const standalone = !hasChildren || (textChildren && !hasContent);

    let badgeContent: unknown = nothing;
    if (!this.dot) {
      if (hasContent) {
        badgeContent = html`<slot name="content">${this.content}</slot>`;
      } else if (textChildren) {
        badgeContent = html`<slot></slot>`;
      } else if (hasChildren) {
        badgeContent = this.locale.t("badge.default");
      }
    }

    const badge = html`<span
      part=${standalone ? "base badge" : "badge"}
      class=${classMap({
        badge: true,
        [this.color]: true,
        [this.variant]: true,
        [this.size]: true,
        standalone,
        [this.position]: !standalone,
        dot: this.dot,
      })}
      role=${this.badgeRole || nothing}
      aria-label=${this.aria.label ?? nothing}
      style=${styleMap({
        borderRadius: this.borderRadius,
        borderWidth: this.borderWidth,
      })}
      >${
        this.slots.test("icon")
          ? html`<span class="icon" part="icon"
              ><slot name="icon"></slot
            ></span>`
          : nothing
      }${badgeContent}</span
    >`;

    if (standalone) return badge;
    return html`<div part="base" class="badgeWrapper">
      <div class="content"><slot></slot></div>
      ${badge}
    </div>`;
  }
}

declare global {
  interface HTMLElementTagNameMap {
    "minerva-badge": MinervaBadge;
  }
}

// packages/vue/src/components/Badge/Badge.vue
<script setup lang="ts">
/**
 * Badge: a small count or status indicator.
 *
 * - With element children (default slot) the badge is attached to a corner
 *   of them (`position`), inside a relatively positioned wrapper.
 * - Without children, or with plain text children, it is a standalone badge
 *   rendered inline in the normal flow.
 *
 * Attributes (`aria-label`, `class`, `style`...) go to the badge element.
 */
import { computed, useAttrs, type CSSProperties } from "vue";
import styles from "@react-styles/components/Badge/badge.module.scss";
import { hooks } from "../../internal/hooks";
import { flattenChildren, isTextOnly } from "../../internal/children";
import { useI18n } from "../../config/useI18n";
import type { BadgeProps } from "./types";

defineOptions({ name: "Badge", inheritAttrs: false });

const props = withDefaults(defineProps<BadgeProps>(), {
  color: "primary",
  variant: "solid",
  size: "medium",
  content: undefined,
  position: "top-right",
  dot: false,
  borderRadius: undefined,
  borderWidth: undefined,
  role: "status",
});

const slots = defineSlots<{
  /** Element the badge is attached to, or the text content of a standalone badge */
  default?: () => unknown;
  /** Rich content of the badge (the `content` prop) */
  content?: () => unknown;
  /** Icon displayed before the content */
  icon?: () => unknown;
}>();

const attrs = useAttrs();
const { t } = useI18n();

const hasContentProp = computed(
  () => props.content !== undefined || !!slots.content,
);

/**
 * Standalone without children, or with text children (its own content)
 * and no `content`; attached to element children otherwise.
 */
const isStandalone = (children: unknown) => {
  const nodes = flattenChildren(children);
  return nodes.length === 0 || (isTextOnly(nodes) && !hasContentProp.value);
};

const badgeClasses = (standalone: boolean) => [
  styles.badge,
  styles[props.color],
  styles[props.variant],
  styles[props.size],
  standalone ? styles.standalone : styles[props.position],
  props.dot && styles.dot,
];
const badgeStyle = computed<CSSProperties>(() => ({
  borderRadius: props.borderRadius,
  borderWidth: props.borderWidth,
}));
const states = computed(() => ({
  size: props.size,
  variant: props.variant,
  color: props.color,
}));
const badgeAttrs = (standalone: boolean) => ({
  role: props.role,
  ...attrs,
  ...hooks("badge", standalone ? "root" : "badge", states.value),
});
</script>

<template>
  <span
    v-if="isStandalone($slots.default?.())"
    :class="badgeClasses(true)"
    :style="badgeStyle"
    v-bind="badgeAttrs(true)"
  >
    <span
      v-if="slots.icon"
      :class="styles.icon"
      v-bind="hooks('badge', 'icon')"
    >
      <slot name="icon" />
    </span>
    <template v-if="!dot">
      <slot v-if="hasContentProp" name="content">{{ content }}</slot>
      <slot v-else />
    </template>
  </span>
  <div
    v-else
    :class="styles.badgeWrapper"
    v-bind="hooks('badge', 'root', states)"
  >
    <div :class="styles.content"><slot /></div>
    <span
      :class="badgeClasses(false)"
      :style="badgeStyle"
      v-bind="badgeAttrs(false)"
    >
      <span
        v-if="slots.icon"
        :class="styles.icon"
        v-bind="hooks('badge', 'icon')"
      >
        <slot name="icon" />
      </span>
      <template v-if="!dot">
        <slot v-if="hasContentProp" name="content">{{ content }}</slot>
        <template v-else>{{ t("badge.default") }}</template>
      </template>
    </span>
  </div>
</template>
