// apps/docs/src/docs/pages/button/native/shapes.tsx
import { View } from "react-native";
import { Button } from "minerva-design/native";

export default function ShapesDemo() {
  return (
    <View style={{ flexDirection: "row", flexWrap: "wrap", gap: 8 }}>
      <Button shape="square">Square</Button>
      <Button shape="rounded">Rounded</Button>
      <Button shape="circle" accessibilityLabel="Add">
        +
      </Button>
      <Button style={{ borderRadius: 0 }}>No radius</Button>
      <Button style={{ borderRadius: 12 }}>12px radius</Button>
    </View>
  );
}

// apps/docs/src/docs/pages/button/vue/shapes.vue
<script setup lang="ts">
import { Button, HStack } from "minerva-design/vue";
</script>
<template>
  <HStack :gap="2" wrap
    ><Button shape="square">Square</Button
    ><Button shape="rounded">Rounded</Button
    ><Button shape="circle" aria-label="Add">+</Button
    ><Button border-radius="none">No radius</Button
    ><Button :border-radius="12">12px radius</Button></HStack
  >
</template>
