// packages/vue/src/components/Pagination/Pagination.vue
<script setup lang="ts">
/**
 * Pagination: page navigation (`<nav>` landmark) with page / prev / next /
 * jump buttons, an optional total, quick jumper, page size selector, simple
 * mode and compact page list. `v-model:current` / `v-model:pageSize`; the
 * `change` event receives (page, pageSize). Attributes fall through to the
 * `<nav>`.
 */
import {
  computed,
  nextTick,
  onBeforeUnmount,
  ref,
  useAttrs,
  watch,
  type FunctionalComponent,
  type VNodeChild,
} from "vue";
import {
  canGoToPage,
  createPaginationMachine,
  getPaginationItems,
  getPaginationKeyTarget,
  getPaginationVisibleRange,
  getTotalPages,
} from "@minerva/core";
import styles from "@react-styles/components/Pagination/pagination.module.scss";
import { hooks } from "../../internal/hooks";
import { useMachine } from "../../internal/machine";
import { logicalArrowKey } from "../../internal/direction";
import {
  IconChevronLeft,
  IconChevronRight,
  IconEllipsis,
} from "../../internal/icons";
import { useI18n } from "../../config/useI18n";
import type { PaginationItemType, PaginationProps } from "./types";

defineOptions({ name: "Pagination", inheritAttrs: false });

const props = withDefaults(defineProps<PaginationProps>(), {
  current: undefined,
  defaultCurrent: undefined,
  total: 0,
  pageSize: undefined,
  defaultPageSize: undefined,
  disabled: false,
  showQuickJumper: false,
  showSizeChanger: false,
  pageSizeOptions: () => [10, 20, 50, 100],
  itemRender: undefined,
  showTotal: false,
  totalRender: undefined,
  size: "medium",
  shape: "rounded",
  variant: "solid",
  simple: false,
  siblingCount: undefined,
  boundaryCount: undefined,
  hideEdges: false,
  hideNumbers: false,
  responsive: false,
  icons: undefined,
  labels: undefined,
});

const emit = defineEmits<{
  "update:current": [page: number];
  "update:pageSize": [pageSize: number];
  /** The page or the page size changed (a page size change resets to page 1) */
  change: [page: number, pageSize: number];
}>();

const slots = defineSlots<{
  /** Content of a page / prev / next / jump item (like `itemRender`) */
  item?: (props: { page: number; type: PaginationItemType }) => unknown;
  /** The total text (like `totalRender`) */
  total?: (props: { total: number; range: [number, number] }) => unknown;
  "prev-icon"?: () => unknown;
  "next-icon"?: () => unknown;
  "jump-prev-icon"?: () => unknown;
  "jump-next-icon"?: () => unknown;
  /** Visible text of the quick jumper (like `labels.jumpTo`) */
  "jump-to"?: () => unknown;
}>();

const attrs = useAttrs();
const { t } = useI18n();
const navRef = ref<HTMLElement | null>(null);

/** Renders a render-prop result (VNode, text, number) */
const Render: FunctionalComponent<{ content: VNodeChild }> = (p) =>
  p.content as never;
Render.props = ["content"];

// Page and page size (each controlled or not): core's pagination machine.
const { state, send } = useMachine(createPaginationMachine, () => ({
  page: props.current,
  defaultPage: props.defaultCurrent ?? 1,
  pageSize: props.pageSize,
  defaultPageSize: props.defaultPageSize ?? 10,
  total: props.total,
  disabled: props.disabled,
  onChange: (page: number, pageSize: number) => {
    if (page !== before.page) emit("update:current", page);
    if (pageSize !== before.pageSize) emit("update:pageSize", pageSize);
    emit("change", page, pageSize);
  },
}));

/** Values before an event (the machine reports the requested ones) */
let before = { ...state.value };
const dispatch = (event: Parameters<typeof send>[0]) => {
  before = { ...state.value };
  send(event);
};

const page = computed(() => state.value.page);
const currentPageSize = computed(() => state.value.pageSize);
// There is always at least one (possibly empty) page
const totalPages = computed(() =>
  getTotalPages(props.total, currentPageSize.value),
);

const jumpValue = ref("");
// Draft text of the simple-mode page input while the user is typing (null
// when not editing, so the input mirrors the current page)
const simpleDraft = ref<string | null>(null);

interface Ripple {
  x: number;
  y: number;
  id: number;
  itemKey: string;
}
const ripples = ref<Ripple[]>([]);
let nextRippleId = 0;
let rippleTimer: ReturnType<typeof setTimeout> | undefined;
watch(ripples, (list) => {
  clearTimeout(rippleTimer);
  if (list.length === 0) return;
  rippleTimer = setTimeout(() => (ripples.value = []), 1000);
});
onBeforeUnmount(() => clearTimeout(rippleTimer));

// Set when a page change should move focus to the active page button
// (keyboard navigation, or the focused button became disabled / removed)
let restoreFocus: { mode: "active" | "if-lost"; page: number } | null = null;

function changePage(target: number, focus: "active" | "if-lost" = "if-lost") {
  if (!canGoToPage(page.value, target, totalPages.value, props.disabled)) {
    return;
  }
  restoreFocus = { mode: focus, page: target };
  dispatch({ type: "GOTO", page: target });
  // A controlled parent that ignores the change: nothing to restore.
  if (page.value !== target) restoreFocus = null;
}

// Focus management after a page change (once the DOM is updated)
watch(
  page,
  () => {
    const request = restoreFocus;
    restoreFocus = null;
    const nav = navRef.value;
    if (!request || !nav || request.page !== page.value) return;
    const active = nav.ownerDocument.activeElement as HTMLElement | null;
    const lost =
      !active ||
      !nav.contains(active) ||
      (active as HTMLButtonElement).disabled === true;
    if (request.mode === "active" || lost) {
      const target =
        nav.querySelector<HTMLElement>('[aria-current="page"]') ??
        nav.querySelector<HTMLElement>("button:not(:disabled), input");
      target?.focus();
    }
  },
  { flush: "post" },
);

function onItemClick(target: number, itemKey: string, event: MouseEvent) {
  if (!canGoToPage(page.value, target, totalPages.value, props.disabled)) {
    return;
  }
  // Ripple only for pointer clicks (keyboard-triggered clicks have detail 0)
  if (event.detail > 0) {
    const rect = (event.currentTarget as HTMLElement).getBoundingClientRect();
    ripples.value = [
      ...ripples.value,
      {
        x: event.clientX - rect.left,
        y: event.clientY - rect.top,
        id: nextRippleId++,
        itemKey,
      },
    ];
  }
  changePage(target);
}

// Arrow keys / Home / End on the page buttons (inputs keep their keys);
// RTL: the previous page is on the right, so ArrowRight goes back.
function onItemKeydown(event: KeyboardEvent) {
  const destination = getPaginationKeyTarget(
    logicalArrowKey(event.key, event.currentTarget as Element),
    page.value,
    totalPages.value,
  );
  if (destination === null) return;
  event.preventDefault();
  changePage(destination, "active");
}

function onJumpKeydown(event: KeyboardEvent) {
  if (event.key !== "Enter") return;
  // Enter in a text input would implicitly submit an enclosing form
  event.preventDefault();
  const value = parseInt(jumpValue.value, 10);
  if (!isNaN(value) && value >= 1 && value <= totalPages.value) {
    changePage(value);
    jumpValue.value = "";
  }
}

async function onSizeChange(event: Event) {
  const select = event.target as HTMLSelectElement;
  dispatch({ type: "SET_PAGE_SIZE", pageSize: parseInt(select.value, 10) });
  // A controlled parent may keep its page size: mirror it again.
  await nextTick();
  select.value = String(currentPageSize.value);
}

// Commits the simple-mode page: valid values clamped, invalid ones reverted
function commitSimpleDraft() {
  if (simpleDraft.value === null) return;
  const value = parseInt(simpleDraft.value, 10);
  simpleDraft.value = null;
  if (isNaN(value)) return;
  changePage(Math.min(Math.max(value, 1), totalPages.value));
}

function onSimpleKeydown(event: KeyboardEvent) {
  if (event.key !== "Enter") return;
  // Do not implicitly submit an enclosing form
  event.preventDefault();
  commitSimpleDraft();
}

function itemLabel(type: PaginationItemType, target: number): string {
  const labels = props.labels;
  switch (type) {
    case "prev":
      return labels?.prev ?? t("pagination.prev");
    case "next":
      return labels?.next ?? t("pagination.next");
    case "jump-prev":
      return labels?.jumpPrev ?? t("pagination.jumpPrev");
    case "jump-next":
      return labels?.jumpNext ?? t("pagination.jumpNext");
    default:
      return labels?.page?.(target) ?? t("pagination.page", { page: target });
  }
}

interface Item {
  key: string;
  type: PaginationItemType;
  page: number;
  active: boolean;
  disabled: boolean;
  label: string;
}

const toItem = (target: number, type: PaginationItemType): Item => ({
  // Stable keys: the focused button must survive page changes
  key: type === "page" ? `page-${target}` : type,
  type,
  page: target,
  active: type === "page" && target === page.value,
  disabled:
    props.disabled ||
    (type === "prev"
      ? page.value <= 1
      : type === "next"
        ? page.value >= totalPages.value
        : false),
  label: itemLabel(type, target),
});

type Entry =
  | ({ kind: "item" } & Item)
  | { kind: "ellipsis" | "simple" | "counter"; key: string };

const edge = (type: "prev" | "next"): Entry[] =>
  props.hideEdges
    ? []
    : [
        {
          kind: "item",
          ...toItem(type === "prev" ? page.value - 1 : page.value + 1, type),
        },
      ];

/** Everything between the total and the jumper, in DOM order */
const entries = computed<Entry[]>(() => {
  if (props.simple || props.hideNumbers) {
    return [
      ...edge("prev"),
      {
        kind: props.simple ? "simple" : "counter",
        key: props.simple ? "simple" : "counter",
      },
      ...edge("next"),
    ];
  }
  return getPaginationItems({
    page: page.value,
    totalPages: totalPages.value,
    siblingCount: props.siblingCount,
    boundaryCount: props.boundaryCount,
    hideEdges: props.hideEdges,
  }).map((item) =>
    item.kind === "ellipsis"
      ? { kind: "ellipsis", key: item.key }
      : { kind: "item", ...toItem(item.page, item.kind) },
  );
});

const iconSlot = (type: PaginationItemType) =>
  type === "prev"
    ? "prev-icon"
    : type === "next"
      ? "next-icon"
      : type === "jump-prev"
        ? "jump-prev-icon"
        : "jump-next-icon";
const iconProp = (type: PaginationItemType): VNodeChild =>
  type === "prev"
    ? props.icons?.prev
    : type === "next"
      ? props.icons?.next
      : type === "jump-prev"
        ? props.icons?.jumpPrev
        : props.icons?.jumpNext;
const defaultIcon = (type: PaginationItemType) =>
  type === "prev"
    ? IconChevronLeft
    : type === "next"
      ? IconChevronRight
      : IconEllipsis;

const visibleRange = computed(() =>
  getPaginationVisibleRange(page.value, currentPageSize.value, props.total),
);
const totalContent = computed<VNodeChild>(() => {
  const range = visibleRange.value;
  if (typeof props.showTotal === "function") {
    return props.showTotal(props.total, range);
  }
  if (props.totalRender) return props.totalRender(props.total, range);
  return (
    props.labels?.total?.(props.total) ??
    t("pagination.total", { total: props.total })
  );
});

const sizeOptions = computed(() =>
  props.pageSizeOptions.includes(currentPageSize.value)
    ? props.pageSizeOptions
    : [...props.pageSizeOptions, currentPageSize.value].sort((a, b) => a - b),
);
const sizeOptionLabel = (size: number) =>
  props.labels?.pageSizeOption?.(size) ??
  t("pagination.pageSizeOption", { size });

const classes = computed(() => [
  styles.pagination,
  props.disabled && styles.disabled,
  props.size === "small" && styles.small,
  props.size === "large" && styles.large,
  props.shape === "circle" && styles.circle,
  props.shape === "square" && styles.square,
  styles[props.variant],
  props.responsive && styles.responsive,
]);

const navAttrs = computed(() => ({
  ...attrs,
  ...hooks("pagination", "root", {
    disabled: props.disabled,
    size: props.size,
    shape: props.shape,
    variant: props.variant,
  }),
}));

const itemClass = (item: Item) => [
  styles.item,
  item.active && styles.active,
  item.disabled && styles.disabled,
  item.type === "prev" && styles.prev,
  item.type === "next" && styles.next,
  (item.type === "jump-prev" || item.type === "jump-next") && styles.jump,
];
const itemHooks = (item: Item) =>
  hooks("pagination", "item", {
    current: item.active,
    disabled: item.disabled,
  });
const ripplesOf = (key: string) =>
  ripples.value.filter((ripple) => ripple.itemKey === key);
</script>

<template>
  <nav
    ref="navRef"
    :aria-label="labels?.nav ?? t('pagination.nav')"
    :class="classes"
    v-bind="navAttrs"
  >
    <div
      v-if="showTotal !== false"
      :class="styles.total"
      aria-live="polite"
      aria-atomic="true"
      v-bind="hooks('pagination', 'total')"
    >
      <slot name="total" :total="total" :range="visibleRange">
        <Render :content="totalContent" />
      </slot>
    </div>

    <template v-for="entry in entries" :key="entry.key">
      <button
        v-if="entry.kind === 'item'"
        type="button"
        :class="itemClass(entry)"
        :disabled="entry.disabled"
        :aria-label="entry.label"
        :aria-current="entry.active ? 'page' : undefined"
        v-bind="itemHooks(entry)"
        @keydown="onItemKeydown"
        @click="onItemClick(entry.page, entry.key, $event)"
      >
        <Render
          v-if="itemRender"
          :content="itemRender(entry.page, entry.type)"
        />
        <slot v-else name="item" :page="entry.page" :type="entry.type">
          <template v-if="entry.type === 'page'">{{ entry.page }}</template>
          <slot
            v-else-if="entry.type === 'prev' || entry.type === 'next'"
            :name="iconSlot(entry.type)"
          >
            <Render
              v-if="iconProp(entry.type)"
              :content="iconProp(entry.type)"
            />
            <component
              :is="defaultIcon(entry.type)"
              v-else
              aria-hidden="true"
            />
          </slot>
          <span v-else :class="styles.jumpWrapper">
            <slot :name="iconSlot(entry.type)">
              <Render
                v-if="iconProp(entry.type)"
                :content="iconProp(entry.type)"
              />
              <component
                :is="defaultIcon(entry.type)"
                v-else
                aria-hidden="true"
              />
            </slot>
            <span :class="styles.jumpHint" aria-hidden="true">{{
              entry.label
            }}</span>
          </span>
        </slot>
        <span
          v-for="ripple in ripplesOf(entry.key)"
          :key="ripple.id"
          :class="styles.ripple"
          :style="{ left: `${ripple.x}px`, top: `${ripple.y}px` }"
          aria-hidden="true"
        />
      </button>
      <span
        v-else-if="entry.kind === 'ellipsis'"
        :class="styles.ellipsis"
        aria-hidden="true"
        >…</span
      >
      <div v-else-if="entry.kind === 'simple'" :class="styles.simpleInput">
        <input
          v-bind="hooks('pagination', 'simple-input')"
          :value="simpleDraft ?? String(page)"
          :disabled="disabled"
          :aria-label="labels?.currentPage ?? t('pagination.currentPage')"
          inputmode="numeric"
          @input="simpleDraft = ($event.target as HTMLInputElement).value"
          @keydown="onSimpleKeydown"
          @blur="commitSimpleDraft"
        />
        <span :class="styles.simpleDivider" aria-hidden="true">/</span>
        <span>{{ totalPages }}</span>
      </div>
      <span v-else :class="styles.counter" aria-live="polite"
        >{{ page }} / {{ totalPages }}</span
      >
    </template>

    <label
      v-if="showQuickJumper"
      :class="styles.jumper"
      v-bind="hooks('pagination', 'jumper')"
    >
      <slot name="jump-to">{{ labels?.jumpTo ?? t("pagination.jumpTo") }}</slot>
      <input
        v-model="jumpValue"
        :disabled="disabled"
        inputmode="numeric"
        :aria-label="labels?.jumpToInput ?? t('pagination.jumpToInput')"
        @keydown="onJumpKeydown"
      />
    </label>

    <div v-if="showSizeChanger" :class="styles.sizeChanger">
      <select
        v-bind="hooks('pagination', 'size-changer')"
        :value="currentPageSize"
        :disabled="disabled"
        :aria-label="labels?.pageSize ?? t('pagination.pageSize')"
        @change="onSizeChange"
      >
        <option v-for="option in sizeOptions" :key="option" :value="option">
          {{ sizeOptionLabel(option) }}
        </option>
      </select>
    </div>
  </nav>
</template>

// packages/react/src/components/Pagination/Pagination.tsx
import React, {
  useEffect,
  useRef,
  useState,
  type KeyboardEvent,
  type MouseEvent,
} from "react";
import {
  IconChevronLeft,
  IconChevronRight,
  IconEllipsis,
} from "../../internal/icons";
import {
  canGoToPage,
  createPaginationMachine,
  getPaginationItems,
  getPaginationKeyTarget,
  getPaginationVisibleRange,
  getTotalPages,
} from "@minerva/core";
import { cn } from "../../utils/cn";
import type { PaginationProps } from "./types";
import { logicalArrowKey } from "../../internal/direction";
import styles from "./pagination.module.scss";
import useI18n from "../../hooks/useI18n";
import { useControlledSwitchWarning } from "../../internal/useControllableState";
import { useMachine } from "../../internal/useMachine";
import { warnControlledProps, warnOnce } from "../../internal/devWarnings";
import { useMergedRefs } from "../../internal/mergeRefs";
import { hooks } from "../../internal/stylingHooks";

type PaginationItemType = "page" | "prev" | "next" | "jump-prev" | "jump-next";

const DEFAULT_ICONS = {
  prev: <IconChevronLeft aria-hidden="true" />,
  next: <IconChevronRight aria-hidden="true" />,
  jumpPrev: <IconEllipsis aria-hidden="true" />,
  jumpNext: <IconEllipsis aria-hidden="true" />,
};

interface Ripple {
  x: number;
  y: number;
  id: number;
  itemKey: string;
}

/**
 * Pagination 分页组件
 *
 * @description 用于数据分页展示的导航组件,支持多种样式和交互方式
 *
 * @param current - 当前页（受控）
 * @param defaultCurrent - 默认当前页（非受控）
 * @param total - 总数
 * @param pageSize - 每页显示数量（受控）
 * @param defaultPageSize - 默认每页显示数量（非受控）
 * @param onChange - 页码或每页数量改变回调
 * @param disabled - 是否禁用
 * @param showQuickJumper - 是否显示快速跳转
 * @param showSizeChanger - 是否显示页码大小改变
 * @param pageSizeOptions - 页码大小选项
 * @param itemRender - 页码渲染函数
 * @param className - 组件类名
 * @param style - 组件样式
 * @param showTotal - 是否显示总数
 * @param totalRender - 总数渲染函数
 * @param size - 组件尺寸
 * @param shape - 组件形状
 * @param variant - 组件样式
 * @param simple - 是否简单模式
 * @param responsive - 是否响应式
 * @param icons - 组件图标
 * @param siblingCount - 紧凑页码列表中当前页两侧的页数
 * @param boundaryCount - 紧凑页码列表首尾保留的页数
 * @param hideEdges - 隐藏上一页 / 下一页
 * @param hideNumbers - 用「当前 / 总数」计数代替页码按钮
 * @param labels - 自定义文案（覆盖本地化的默认文案）
 * @param ref - 根 <nav> 元素的 ref
 */
const Pagination = ({
  current,
  defaultCurrent,
  total = 0,
  pageSize,
  defaultPageSize,
  onChange,
  disabled = false,
  showQuickJumper = false,
  showSizeChanger = false,
  pageSizeOptions = [10, 20, 50, 100],
  itemRender,
  className,
  style,
  showTotal = false,
  totalRender,
  size = "medium",
  shape = "rounded",
  variant = "solid",
  simple = false,
  responsive = false,
  icons,
  labels,
  siblingCount,
  boundaryCount,
  hideEdges = false,
  hideNumbers = false,
  ref,
  ...rest
}: PaginationProps) => {
  const { t } = useI18n();
  const navRef = useRef<HTMLElement>(null);
  const mergedRef = useMergedRefs(navRef, ref);

  if (process.env.NODE_ENV !== "production") {
    warnControlledProps("Pagination", {
      prop: "current",
      value: current,
      defaultProp: "defaultCurrent",
      defaultValue: defaultCurrent,
      handlerProp: "onChange",
      handler: onChange,
      locked: disabled,
      lockHint: "set `disabled`",
    });
  }
  useControlledSwitchWarning(current !== undefined, "Pagination", "current");
  if (process.env.NODE_ENV !== "production") {
    warnControlledProps("Pagination", {
      prop: "pageSize",
      value: pageSize,
      defaultProp: "defaultPageSize",
      defaultValue: defaultPageSize,
      handlerProp: "onChange",
      handler: onChange,
      locked: disabled || !showSizeChanger,
    });
  }
  useControlledSwitchWarning(pageSize !== undefined, "Pagination", "pageSize");
  // Page and page size (each controlled or not): core's pagination machine.
  const [{ page, pageSize: currentPageSize }, send] = useMachine(
    createPaginationMachine,
    {
      page: current,
      defaultPage: defaultCurrent ?? 1,
      pageSize,
      defaultPageSize: defaultPageSize ?? 10,
      total,
      disabled,
      onChange,
    },
  );

  const [jumpValue, setJumpValue] = useState("");
  // Draft text of the simple-mode page input while the user is typing
  // (null when not editing, so the input mirrors the current page)
  const [simpleDraft, setSimpleDraft] = useState<string | null>(null);
  const [ripples, setRipples] = useState<Ripple[]>([]);
  const nextRippleId = useRef(0);
  // Set when a page change should move focus to the active page button
  // (keyboard navigation, or the focused button became disabled / removed)
  const restoreFocus = useRef<{
    mode: "active" | "if-lost";
    page: number;
  } | null>(null);

  const mergedIcons = { ...DEFAULT_ICONS, ...icons };
  // There is always at least one (possibly empty) page
  const totalPages = getTotalPages(total, currentPageSize);

  if (process.env.NODE_ENV !== "production") {
    // `total = 0` usually means "not loaded yet": only out-of-range pages of
    // a known total are reported.
    if (
      !Number.isInteger(page) ||
      page < 1 ||
      (total > 0 && page > totalPages)
    ) {
      warnOnce(
        "Pagination:range",
        `[minerva] Pagination: the current page (${page}) is out of range 1..${totalPages} ` +
          `(total ${total}, page size ${currentPageSize}). Clamp \`current\` / \`defaultCurrent\` to a valid page.`,
      );
    }
  }

  const changePage = (
    target: number,
    focus: "active" | "if-lost" = "if-lost",
  ) => {
    if (!canGoToPage(page, target, totalPages, disabled)) return;
    restoreFocus.current = { mode: focus, page: target };
    send({ type: "GOTO", page: target });
  };

  // Focus management after a page change (runs after the DOM is updated)
  useEffect(() => {
    const request = restoreFocus.current;
    restoreFocus.current = null;
    const nav = navRef.current;
    // Skip when a controlled parent did not accept the change
    if (!request || !nav || request.page !== page) return;
    const active = nav.ownerDocument.activeElement as HTMLElement | null;
    const lost =
      !active ||
      !nav.contains(active) ||
      (active as HTMLButtonElement).disabled === true;
    if (request.mode === "active" || lost) {
      const target =
        nav.querySelector<HTMLElement>('[aria-current="page"]') ??
        nav.querySelector<HTMLElement>("button:not(:disabled), input");
      target?.focus();
    }
  });

  const handleItemClick = (
    target: number,
    itemKey: string,
    event: MouseEvent<HTMLButtonElement>,
  ) => {
    if (!canGoToPage(page, target, totalPages, disabled)) return;
    // Ripple only for pointer clicks (keyboard-triggered clicks have detail 0)
    if (event.detail > 0) {
      const rect = event.currentTarget.getBoundingClientRect();
      const ripple: Ripple = {
        x: event.clientX - rect.left,
        y: event.clientY - rect.top,
        id: nextRippleId.current++,
        itemKey,
      };
      setRipples((prev) => [...prev, ripple]);
    }
    changePage(target);
  };

  // 清理水波纹效果
  useEffect(() => {
    if (ripples.length === 0) return;
    const timer = setTimeout(() => setRipples([]), 1000);
    return () => clearTimeout(timer);
  }, [ripples]);

  // 快速跳转
  const handleJump = (e: KeyboardEvent<HTMLInputElement>) => {
    if (e.key !== "Enter") return;
    // Enter in a text input would implicitly submit an enclosing form
    e.preventDefault();
    const value = parseInt(jumpValue, 10);
    if (!isNaN(value) && value >= 1 && value <= totalPages) {
      changePage(value);
      setJumpValue("");
    }
  };

  // 页码大小改变: 回到第一页
  const handleSizeChange = (value: string) => {
    send({ type: "SET_PAGE_SIZE", pageSize: parseInt(value, 10) });
  };

  // 提交简单模式输入框的页码: 有效值夹取到合法范围, 无效值还原
  const commitSimpleDraft = () => {
    if (simpleDraft === null) return;
    setSimpleDraft(null);
    const value = parseInt(simpleDraft, 10);
    if (isNaN(value) || totalPages < 1) return;
    changePage(Math.min(Math.max(value, 1), totalPages));
  };

  const itemLabel = (type: PaginationItemType, target: number) => {
    switch (type) {
      case "prev":
        return labels?.prev ?? t("pagination.prev");
      case "next":
        return labels?.next ?? t("pagination.next");
      case "jump-prev":
        return labels?.jumpPrev ?? t("pagination.jumpPrev");
      case "jump-next":
        return labels?.jumpNext ?? t("pagination.jumpNext");
      default:
        return labels?.page?.(target) ?? t("pagination.page", { page: target });
    }
  };

  const renderItem = (target: number, type: PaginationItemType) => {
    const isActive = type === "page" && target === page;
    const isDisabled =
      disabled ||
      (type === "prev"
        ? page <= 1
        : type === "next"
          ? page >= totalPages
          : false);
    // Stable keys: the focused button must survive page changes
    const itemKey = type === "page" ? `page-${target}` : type;

    let content: React.ReactNode;
    switch (type) {
      case "prev":
        content = mergedIcons.prev;
        break;
      case "next":
        content = mergedIcons.next;
        break;
      case "jump-prev":
      case "jump-next":
        content = (
          <span className={styles.jumpWrapper}>
            {type === "jump-prev" ? mergedIcons.jumpPrev : mergedIcons.jumpNext}
            <span className={styles.jumpHint} aria-hidden="true">
              {itemLabel(type, target)}
            </span>
          </span>
        );
        break;
      default:
        content = target;
    }
    if (itemRender) {
      content = itemRender(target, type);
    }

    return (
      <button
        key={itemKey}
        type="button"
        onKeyDown={handleKeyDown}
        className={cn(styles.item, {
          [styles.active]: isActive,
          [styles.disabled]: isDisabled,
          [styles.prev]: type === "prev",
          [styles.next]: type === "next",
          [styles.jump]: type === "jump-prev" || type === "jump-next",
        })}
        disabled={isDisabled}
        onClick={(e) => handleItemClick(target, itemKey, e)}
        aria-label={itemLabel(type, target)}
        aria-current={isActive ? "page" : undefined}
        {...hooks("pagination", "item", {
          current: isActive,
          disabled: isDisabled,
        })}
      >
        {content}
        {ripples
          .filter((ripple) => ripple.itemKey === itemKey)
          .map((ripple) => (
            <span
              key={ripple.id}
              className={styles.ripple}
              style={{ left: ripple.x, top: ripple.y }}
              aria-hidden="true"
            />
          ))}
      </button>
    );
  };

  const renderEdge = (type: "prev" | "next") =>
    hideEdges ? null : renderItem(type === "prev" ? page - 1 : page + 1, type);

  const renderPageList = () => {
    if (simple) {
      return (
        <>
          {renderEdge("prev")}
          <div className={styles.simpleInput}>
            <input
              {...hooks("pagination", "simple-input")}
              value={simpleDraft ?? String(page)}
              disabled={disabled}
              aria-label={labels?.currentPage ?? t("pagination.currentPage")}
              inputMode="numeric"
              onChange={(e) => setSimpleDraft(e.target.value)}
              onKeyDown={(e) => {
                if (e.key !== "Enter") return;
                // Do not implicitly submit an enclosing form
                e.preventDefault();
                commitSimpleDraft();
              }}
              onBlur={commitSimpleDraft}
            />
            <span className={styles.simpleDivider} aria-hidden="true">
              /
            </span>
            <span>{totalPages}</span>
          </div>
          {renderEdge("next")}
        </>
      );
    }

    if (hideNumbers) {
      return (
        <>
          {renderEdge("prev")}
          <span className={styles.counter} aria-live="polite">
            {page} / {totalPages}
          </span>
          {renderEdge("next")}
        </>
      );
    }

    return getPaginationItems({
      page,
      totalPages,
      siblingCount,
      boundaryCount,
      hideEdges,
    }).map((item) =>
      item.kind === "ellipsis" ? (
        <span key={item.key} className={styles.ellipsis} aria-hidden="true">
          …
        </span>
      ) : (
        renderItem(item.page, item.kind)
      ),
    );
  };

  // 键盘导航 (on the page buttons only, so inputs / selects keep their own
  // keys): 方向键 / Home / End, 焦点随之移动到当前页
  // (disabled pagination: the buttons are disabled and receive no keys)
  const handleKeyDown = (e: KeyboardEvent<HTMLElement>) => {
    // RTL: the previous page is on the right, so ArrowRight goes back.
    const destination = getPaginationKeyTarget(
      logicalArrowKey(e.key, e.currentTarget),
      page,
      totalPages,
    );
    if (destination === null) return;
    e.preventDefault();
    changePage(destination, "active");
  };

  const visibleRange = getPaginationVisibleRange(page, currentPageSize, total);

  const sizeLabel = labels?.pageSize ?? t("pagination.pageSize");
  const sizeOptionLabel = (size: number) =>
    labels?.pageSizeOption?.(size) ?? t("pagination.pageSizeOption", { size });

  const sizeOptions = pageSizeOptions.includes(currentPageSize)
    ? pageSizeOptions
    : [...pageSizeOptions, currentPageSize].sort((a, b) => a - b);

  const componentClassName = cn(
    styles.pagination,
    disabled && styles.disabled,
    size === "small" && styles.small,
    size === "large" && styles.large,
    shape === "circle" && styles.circle,
    shape === "square" && styles.square,
    styles[variant],
    responsive && styles.responsive,
    className,
  );

  return (
    <nav
      aria-label={labels?.nav ?? t("pagination.nav")}
      {...rest}
      ref={mergedRef}
      className={componentClassName}
      style={style}
      {...hooks("pagination", "root", { disabled, size, shape, variant })}
    >
      {showTotal !== false && (
        <div
          className={styles.total}
          aria-live="polite"
          aria-atomic="true"
          {...hooks("pagination", "total")}
        >
          {typeof showTotal === "function"
            ? showTotal(total, visibleRange)
            : totalRender
              ? totalRender(total, visibleRange)
              : (labels?.total?.(total) ?? t("pagination.total", { total }))}
        </div>
      )}

      {renderPageList()}

      {showQuickJumper && (
        <label className={styles.jumper} {...hooks("pagination", "jumper")}>
          {labels?.jumpTo ?? t("pagination.jumpTo")}
          <input
            value={jumpValue}
            disabled={disabled}
            inputMode="numeric"
            onChange={(e) => setJumpValue(e.target.value)}
            onKeyDown={handleJump}
            aria-label={labels?.jumpToInput ?? t("pagination.jumpToInput")}
          />
        </label>
      )}

      {showSizeChanger && (
        <div className={styles.sizeChanger}>
          <select
            {...hooks("pagination", "size-changer")}
            value={currentPageSize}
            disabled={disabled}
            onChange={(e) => handleSizeChange(e.target.value)}
            aria-label={sizeLabel}
          >
            {sizeOptions.map((option) => (
              <option key={option} value={option}>
                {sizeOptionLabel(option)}
              </option>
            ))}
          </select>
        </div>
      )}
    </nav>
  );
};

export default Pagination;
