// packages/lib-core/src/components/Alert/Alert.tsx
import React, { useCallback, useId, useState } from "react";
import { cn } from "../../utils/cn";
import {
  IoInformationCircle,
  IoCheckmarkCircle,
  IoWarning,
  IoCloseCircle,
  IoClose,
  IoChevronDown,
  IoChevronUp,
} from "react-icons/io5";
import type { AlertProps } from "./types";
import useI18n from "../../hooks/useI18n";
import { useControllableState } from "../../internal/useControllableState";
import styles from "./alert.module.scss";

const iconMap = {
  info: <IoInformationCircle />,
  success: <IoCheckmarkCircle />,
  warning: <IoWarning />,
  danger: <IoCloseCircle />,
};

const ANIMATION_NAMES = ["slideIn", "fadeIn", "bounce", "zoom"] as const;

/**
 * Alert 警告提示组件
 * @description 用于页面中展示重要的提示信息，适用于系统级通知、操作反馈等场景
 * @param {string} color - 警告提示的语义颜色（决定图标与 role），可选值：info、success、warning、danger
 * @param {string} variant - 警告提示的视觉样式，可选值：subtle、outline、solid
 * @param {AlertSize} size - 警告提示的尺寸，可选值：small、medium、large
 * @param {boolean} showIcon - 是否显示图标
 * @param {ReactNode} icon - 自定义图标
 * @param {boolean} closable - 是否可关闭
 * @param {ReactNode} closeIcon - 自定义关闭图标
 * @param {function} onClose - 关闭时的回调函数
 * @param {boolean} animation - 是否显示动画效果
 * @param {AnimationName} animationName - 动画类型，可选值：slideIn、fadeIn、bounce、zoom
 * @param {boolean} elevation - 是否显示阴影
 * @param {boolean} rounded - 是否圆角
 * @param {number|string} borderRadius - 自定义圆角大小
 * @param {boolean} collapsible - 是否可以展开收起
 * @param {boolean} expanded - 是否展开（受控）
 * @param {boolean} defaultExpanded - 默认是否展开（非受控）
 * @param {function} onExpand - 展开收起的回调函数
 * @param {string} closeLabel - 关闭按钮的无障碍名称（默认本地化）
 * @param {string} expandLabel - 展开按钮的无障碍名称（默认本地化）
 * @param {string} collapseLabel - 收起按钮的无障碍名称（默认本地化）
 * @param {string} iconLabel - 图标的无障碍名称（默认本地化）
 * @param {Ref} ref - 根元素的 ref
 */
const Alert = ({
  title,
  children,
  color = "info",
  variant = "subtle",
  size = "medium",
  showIcon = true,
  icon,
  closable = false,
  closeIcon,
  onClose,
  animation = true,
  animationName = "slideIn",
  className,
  style,
  action,
  banner = false,
  elevation = false,
  rounded = true,
  borderRadius,
  collapsible = false,
  expanded: expandedProp,
  defaultExpanded = true,
  onExpand,
  closeLabel,
  expandLabel,
  collapseLabel,
  iconLabel,
  role,
  ref,
  ...rest
}: AlertProps) => {
  const { t } = useI18n();
  const [visible, setVisible] = useState(true);
  const [expanded, setExpanded] = useControllableState({
    value: expandedProp,
    defaultValue: defaultExpanded,
    onChange: onExpand,
  });
  const contentId = useId();
  // The toggle lives in the title, so without a title nothing can be collapsed
  const isCollapsible = collapsible && Boolean(title);

  const handleClose = useCallback(
    (e: React.MouseEvent<HTMLButtonElement>) => {
      setVisible(false);
      onClose?.(e);
    },
    [onClose],
  );

  // onExpand is called by the setter itself, never inside a state updater,
  // so StrictMode's double-invoked updaters cannot call it twice.
  const handleExpand = useCallback(() => {
    setExpanded((prev) => !prev);
  }, [setExpanded]);

  if (!visible) return null;

  const classes = cn(
    styles.alert,
    styles[color],
    styles[variant],
    styles[size],
    {
      [styles.withIcon]: showIcon,
      [styles.withTitle]: title,
      [styles.banner]: banner,
      [styles.withAnimation]: animation,
      [styles[`animation-${animationName}`]]:
        animation && ANIMATION_NAMES.includes(animationName),
      [styles.withElevation]: elevation,
      [styles.rounded]: rounded,
      [styles.expanded]: expanded,
      [styles.collapsible]: isCollapsible,
    },
    className,
  );
  const hasContent =
    children !== undefined &&
    children !== null &&
    children !== false &&
    children !== "";

  const customStyle = {
    ...style,
    ...(borderRadius != null && { borderRadius }),
  };

  return (
    <div
      {...rest}
      ref={ref}
      className={classes}
      style={customStyle}
      // Danger and warning interrupt (alert); info and success are polite
      role={
        role ?? (color === "danger" || color === "warning" ? "alert" : "status")
      }
    >
      {showIcon && (
        <span
          className={styles.icon}
          role="img"
          aria-label={iconLabel ?? t(`alert.icon.${color}`)}
        >
          {icon || iconMap[color]}
        </span>
      )}

      <div className={styles.content}>
        {title && (
          <div className={styles.title}>
            {title}
            {isCollapsible && (
              <button
                type="button"
                className={styles.expandButton}
                onClick={handleExpand}
                aria-label={
                  expanded
                    ? (collapseLabel ?? t("alert.collapse"))
                    : (expandLabel ?? t("alert.expand"))
                }
                aria-expanded={expanded}
                aria-controls={expanded && hasContent ? contentId : undefined}
              >
                {expanded ? <IoChevronUp /> : <IoChevronDown />}
              </button>
            )}
          </div>
        )}
        {hasContent && (!isCollapsible || expanded) && (
          <div id={contentId} className={styles.message}>
            {children}
          </div>
        )}
      </div>

      {action && <div className={styles.action}>{action}</div>}

      {closable && (
        <button
          className={styles.closeButton}
          onClick={handleClose}
          aria-label={closeLabel ?? t("alert.close")}
          type="button"
        >
          {closeIcon || <IoClose />}
        </button>
      )}
    </div>
  );
};

export default Alert;

// packages/uni/src/Alert.vue
<script setup lang="ts">
import { ref, computed, useSlots, nextTick } from "vue";
import { useI18n } from "./i18n";
const props = withDefaults(
  defineProps<{
    title?: string;
    description?: string;
    color?: "info" | "success" | "warning" | "danger";
    status?: string;
    variant?: "subtle" | "outline" | "solid";
    size?: "small" | "medium" | "large";
    showIcon?: boolean;
    icon?: string;
    closeIcon?: string;
    closable?: boolean;
    animation?: boolean;
    animationName?: "slideIn" | "fadeIn" | "bounce" | "zoom";
    banner?: boolean;
    elevation?: boolean;
    rounded?: boolean;
    borderRadius?: number | string;
    collapsible?: boolean;
    expanded?: boolean;
    defaultExpanded?: boolean;
    closeLabel?: string;
    expandLabel?: string;
    collapseLabel?: string;
    iconLabel?: string;
    role?: string;
    returnFocus?: unknown;
  }>(),
  {
    variant: "subtle",
    size: "medium",
    showIcon: true,
    animation: true,
    animationName: "slideIn",
    rounded: true,
    expanded: undefined,
    defaultExpanded: true,
  },
);
const { t } = useI18n();
const slots = useSlots();
const emit = defineEmits<{
  close: [event: Event];
  expand: [expanded: boolean];
  "update:expanded": [expanded: boolean];
}>();
const visible = ref(true),
  local = ref(props.defaultExpanded),
  element = ref<any>();
const color = computed(
    () =>
      props.color ??
      (props.status === "error" ? "danger" : props.status) ??
      "info",
  ),
  expanded = computed(() => props.expanded ?? local.value);
const collapsible = computed(
  () => props.collapsible && !!(props.title || slots.title),
);
const role = computed(
  () =>
    props.role ??
    (["danger", "warning"].includes(color.value) ? "alert" : "status"),
);
const icon = computed(
  () =>
    ({ info: "ⓘ", success: "✓", warning: "!", danger: "×" })[color.value] ??
    "ⓘ",
);
function toggle() {
  const value = !expanded.value;
  if (props.expanded === undefined) local.value = value;
  emit("expand", value);
  emit("update:expanded", value);
}
function close(event: Event) {
  emit("close", event);
  const el = element.value?.$el ?? element.value;
  let target =
    typeof props.returnFocus === "function"
      ? props.returnFocus()
      : props.returnFocus;
  target = target?.value ?? target?.current ?? target;
  if (!target && typeof document !== "undefined" && el) {
    const controls = Array.from(
      document.querySelectorAll<HTMLElement>(
        'button:not([disabled]),a[href],input:not([disabled]),[tabindex="0"]',
      ),
    );
    const at = controls.findIndex((node) => el.contains(node));
    target =
      controls.slice(at + 1).find((node) => !el.contains(node)) ??
      controls
        .slice(0, at)
        .reverse()
        .find((node) => !el.contains(node)) ??
      el.parentElement;
  }
  visible.value = false;
  nextTick(() => {
    if (
      typeof document === "undefined" ||
      !document.activeElement ||
      document.activeElement === document.body ||
      el?.contains(document.activeElement)
    ) {
      target?.focus?.();
    }
  });
}
</script>
<template>
  <view
    v-if="visible"
    ref="element"
    class="mn-alert mn-uni-alert"
    :class="[
      `mn-alert-${color}`,
      `mn-alert-${variant}`,
      `mn-alert-${size}`,
      {
        'mn-alert-banner': banner,
        'mn-alert-elevated': elevation,
        'mn-alert-rounded': rounded,
        'mn-alert-collapsible': collapsible,
      },
      animation ? `mn-alert-${animationName}` : '',
    ]"
    :role="role"
    :style="{
      borderRadius:
        typeof borderRadius === 'number' ? `${borderRadius}px` : borderRadius,
    }"
  >
    <view
      v-if="showIcon"
      data-alert-icon
      class="mn-uni-alert-icon"
      role="img"
      :aria-label="iconLabel ?? t(`alert.icon.${color}`)"
      ><slot name="icon">{{ props.icon ?? icon }}</slot></view
    ><view class="mn-uni-alert-body"
      ><text v-if="title || $slots.title" class="mn-title"
        ><slot name="title">{{ title }}</slot></text
      ><view
        data-alert-content
        v-show="!collapsible || expanded"
        class="mn-uni-alert-content"
        ><text v-if="description">{{ description }}</text
        ><slot /></view></view
    ><view v-if="$slots.action" class="mn-uni-alert-action"
      ><slot name="action"
    /></view>
    <button
      v-if="collapsible"
      class="mn-close"
      :aria-label="
        expanded
          ? (collapseLabel ?? t('alert.collapse'))
          : (expandLabel ?? t('alert.expand'))
      "
      :aria-expanded="expanded"
      @tap="toggle"
    >
      {{ expanded ? "⌃" : "⌄" }}</button
    ><button
      v-if="closable"
      class="mn-close"
      :aria-label="closeLabel ?? t('alert.close')"
      @tap="close"
    >
      <slot name="close-icon">{{ closeIcon ?? "×" }}</slot>
    </button>
  </view>
</template>
