// packages/lib-core/src/components/Avatar/Avatar.tsx
import React, { useState } from "react";
import classNames from "classnames";
import type { AvatarProps } from "./types";
import styles from "./avatar.module.scss";
import useI18n from "../../hooks/useI18n";

/** Short size names used by the stable `ui-avatar-size-*` styling hooks */
const SIZE_HOOK = {
  xsmall: "xs",
  small: "sm",
  medium: "md",
  large: "lg",
  xlarge: "xl",
  xxlarge: "2xl",
} as const;

const CJK = /[\u3400-\u9fff\uf900-\ufaff]/;

/**
 * Initials of a name: the first CJK character, otherwise the uppercased first
 * letters of the first two words ("Ada Lovelace" -> "AL", "张三" -> "张").
 */
function getAvatarInitials(name?: string): string {
  const trimmed = name?.trim() ?? "";
  if (!trimmed) return "";
  if (CJK.test(trimmed[0])) return trimmed[0];
  return trimmed
    .split(/\s+/)
    .slice(0, 2)
    .map((word) => word[0].toUpperCase())
    .join("");
}

/**
 * Avatar: a picture of a person, falling back to their initials (or custom
 * fallback content) when there is no image or it fails to load.
 */
const Avatar = ({
  src,
  name = "",
  alt,
  ariaLabel,
  fallback,
  children,
  shape = "circle",
  size = "medium",
  className = "",
  stacked = false,
  style,
  ref,
  ...rest
}: AvatarProps) => {
  const { t } = useI18n();
  // The src that failed to load; derived instead of reset in an effect so a
  // new src is tried again automatically.
  const [failedSrc, setFailedSrc] = useState<string | undefined>(undefined);
  const showImage = Boolean(src) && failedSrc !== src;
  const label = ariaLabel ?? (name || t("avatar.default"));
  const numericSize = typeof size === "number";

  const rootProps = {
    ...rest,
    ref,
    className: classNames(
      styles.avatar,
      styles[shape],
      !numericSize && styles[size],
      stacked && styles.stacked,
      // Stable styling hooks (not used for styling by the library)
      "ui-avatar",
      !numericSize && `ui-avatar-size-${SIZE_HOOK[size]}`,
      shape !== "circle" && "ui-avatar-shape-square",
      className,
    ),
    style: numericSize
      ? ({
          "--avatar-size": `${size}px`,
          width: size,
          height: size,
          ...style,
        } as React.CSSProperties)
      : style,
  };

  if (showImage) {
    return (
      <span {...rootProps}>
        <img
          alt={alt ?? label}
          className={classNames(styles.avatarImg, "ui-avatar-img")}
          src={src}
          draggable={false}
          onError={() => setFailedSrc(src)}
        />
      </span>
    );
  }

  const content = fallback ?? (getAvatarInitials(name) || children);

  // The fallback is exposed as a single image named after the person, so
  // screen readers announce "Alice" instead of the letter "A".
  return (
    <span role="img" aria-label={label} {...rootProps}>
      <span className={styles.avatarText} aria-hidden="true">
        {content}
      </span>
    </span>
  );
};

export default React.memo(Avatar);

// packages/uni/src/Avatar.vue
<script setup lang="ts">
import { ref, watch, computed } from "vue";
import { useI18n } from "./i18n";
const props = withDefaults(
  defineProps<{
    src?: string;
    name?: string;
    alt?: string;
    fallback?: string;
    size?: number | string;
    shape?: "circle" | "square" | "rounded";
    stacked?: boolean;
    ariaLabel?: string;
  }>(),
  { size: "medium", shape: "circle" },
);
const { t } = useI18n();
const failed = ref(false);
watch(
  () => props.src,
  () => (failed.value = false),
);
const pixels = computed(() =>
  typeof props.size === "number"
    ? `${props.size}px`
    : ({
        xsmall: 24,
        small: 32,
        medium: 48,
        large: 64,
        xlarge: 80,
        xxlarge: 96,
      }[props.size] ?? props.size) +
      (/^\d+$/.test(
        String(
          {
            xsmall: 24,
            small: 32,
            medium: 48,
            large: 64,
            xlarge: 80,
            xxlarge: 96,
          }[props.size] ?? props.size,
        ),
      )
        ? "px"
        : ""),
);
const initials = computed(() => {
  const name = props.name?.trim() ?? "";
  if (/[\u3400-\u9fff]/.test(name[0] ?? "")) return name[0];
  return name
    .split(/\s+/)
    .slice(0, 2)
    .map((s) => s[0] ?? "")
    .join("")
    .toUpperCase();
});
const label = computed(
  () => props.ariaLabel ?? props.name ?? t("avatar.default"),
);
</script>
<template>
  <view
    class="mn-avatar mn-uni-avatar"
    :class="[`mn-shape-${shape}`, { 'mn-avatar-stacked': stacked }]"
    role="img"
    :aria-label="alt === '' ? undefined : label"
    :aria-hidden="alt === '' || undefined"
    :style="{
      width: pixels,
      height: pixels,
      fontSize: `calc(${pixels} * .36)`,
    }"
    ><image
      v-if="src && !failed"
      class="mn-avatar-image"
      :src="src"
      :alt="alt ?? label"
      mode="aspectFill"
      @error="failed = true"
    /><text v-else
      ><slot name="fallback"
        >{{ fallback ?? initials
        }}<slot v-if="!fallback && !initials">?</slot></slot
      ></text
    ></view
  >
</template>
