// packages/lib-core/src/components/Badge/Badge.tsx
import React from "react";
import { cn } from "../../utils/cn";
import type { BadgeProps } from "./types";
import styles from "./badge.module.scss";
import useI18n from "../../hooks/useI18n";

const isTextLike = (node: React.ReactNode): node is string | number =>
  typeof node === "string" || typeof node === "number";

/**
 * Badge: a small count or status indicator.
 *
 * - With element children the badge is attached to a corner of them
 *   (`position`), inside a relatively positioned wrapper.
 * - Without children, or with plain text / number children, it is a
 *   standalone badge rendered inline in the normal flow.
 */
export const Badge = ({
  children,
  color = "primary",
  variant = "solid",
  size = "medium",
  className = "",
  "aria-label": ariaLabel,
  icon,
  content,
  position = "top-right",
  dot = false,
  borderRadius,
  borderWidth,
  role = "status",
  style,
  ref,
  ...rest
}: BadgeProps) => {
  const { t } = useI18n();
  const hasChildren =
    children !== undefined && children !== null && children !== false;
  // Text children are the badge's own content (rendered once, inline).
  const textChildren = hasChildren && isTextLike(children);
  const standalone = !hasChildren || (textChildren && content === undefined);

  let badgeContent: React.ReactNode = null;
  if (!dot) {
    if (content !== undefined) badgeContent = content;
    else if (textChildren) badgeContent = children;
    else if (hasChildren) badgeContent = t("badge.default");
  }

  const badge = (
    <span
      ref={standalone ? (ref as React.Ref<HTMLSpanElement>) : undefined}
      className={cn(
        styles.badge,
        styles[color],
        styles[variant],
        styles[size],
        standalone ? styles.standalone : styles[position],
        dot && styles.dot,
        className,
      )}
      aria-label={ariaLabel}
      role={role}
      {...rest}
      style={{
        borderRadius,
        borderWidth,
        ...style,
      }}
    >
      {icon && <span className={styles.icon}>{icon}</span>}
      {badgeContent}
    </span>
  );

  if (standalone) return badge;

  return (
    <div ref={ref as React.Ref<HTMLDivElement>} className={styles.badgeWrapper}>
      <div className={styles.content}>{children}</div>
      {badge}
    </div>
  );
};

export default React.memo(Badge);

// packages/uni/src/Badge.vue
<script setup lang="ts">
import { isVueComment } from "./host";
import { computed, useSlots, Text as VueText, Fragment } from "vue";
import { useI18n } from "./i18n";
const props = withDefaults(
  defineProps<{
    count?: number;
    max?: number;
    dot?: boolean;
    status?: string;
    showZero?: boolean;
    color?: string;
    variant?: "solid" | "subtle" | "outline";
    size?: "small" | "medium" | "large";
    content?: string | number;
    position?: "top-right" | "top-left" | "bottom-right" | "bottom-left";
    borderRadius?: string;
    borderWidth?: string;
    icon?: string;
    role?: string;
    ariaLabel?: string;
  }>(),
  {
    max: 99,
    color: "primary",
    variant: "solid",
    size: "medium",
    position: "top-right",
    role: "status",
  },
);
const slots = useSlots();
const { t } = useI18n();
const children = computed(
  () => slots.default?.().filter((v) => !isVueComment(v.type)) ?? [],
);
function plain(nodes: any[]): boolean {
  return nodes.every(
    (node) =>
      node.type === VueText ||
      (typeof node.children === "string" && node.type === VueText) ||
      (node.type === Fragment && plain(node.children ?? [])),
  );
}
const attached = computed(
  () => children.value.length > 0 && !plain(children.value),
);
const color = computed(() =>
  props.status
    ? props.status === "error"
      ? "danger"
      : props.status
    : props.color,
);
const content = computed(
  () =>
    props.content ??
    (props.count === undefined
      ? undefined
      : props.count > props.max
        ? `${props.max}+`
        : props.count),
);
const visible = computed(
  () =>
    props.dot ||
    props.content !== undefined ||
    props.count === undefined ||
    props.count !== 0 ||
    props.showZero,
);
</script>
<template>
  <view class="mn-badge mn-uni-badge" :class="{ 'mn-badge-attached': attached }"
    ><slot v-if="attached" /><text
      v-if="visible"
      data-badge
      :role="role"
      :aria-label="props.ariaLabel ?? (dot ? t('badge.default') : undefined)"
      :data-position="position"
      :data-color="color"
      class="mn-uni-badge-indicator"
      :class="[
        `mn-tone-${color}`,
        `mn-position-${position}`,
        `mn-badge-${variant}`,
        `mn-badge-${size}`,
        { 'mn-badge-dot': dot },
      ]"
      :style="{ borderRadius, borderWidth }"
      ><template v-if="!dot"
        ><slot name="icon"
          ><text v-if="icon">{{ icon }}</text></slot
        ><slot name="content"
          >{{ content
          }}<slot
            v-if="!attached && content === undefined" /></slot></template></text
  ></view>
</template>
