// packages/lib-core/src/components/JsonField/JsonField.tsx
import { useId, useState } from "react";
import { applyEdits, createScanner, format } from "jsonc-parser";
import { LuBraces, LuCircleAlert, LuCircleCheck } from "react-icons/lu";
import { cn } from "../../utils/cn";
import useI18n from "../../hooks/useI18n";
import { useControllableState } from "../../internal/useControllableState";
import { useFormControlContext } from "../FormControl/context";
import { IconButton } from "../IconButton";
import { Textarea } from "../Textarea/Textarea";
import type { JsonFieldProps } from "./types";
import styles from "./jsonField.module.scss";

type Validation =
  { status: "empty" | "valid" } | { status: "invalid"; error: string };

function validate(value: string): Validation {
  if (!value.trim()) return { status: "empty" };
  try {
    JSON.parse(value);
    return { status: "valid" };
  } catch (error) {
    return {
      status: "invalid",
      error: error instanceof Error ? error.message : String(error),
    };
  }
}

/**
 * Re-indents with jsonc-parser text edits, so numeric lexemes, escapes,
 * duplicate keys and key order are preserved (no JSON.parse round trip).
 */
function formatJson(value: string, indent: number): string {
  const spaces = Math.min(10, Math.max(0, Math.trunc(indent) || 0));
  if (spaces > 0) {
    return applyEdits(
      value,
      format(value, undefined, {
        tabSize: spaces,
        insertSpaces: true,
        eol: "\n",
      }),
    );
  }
  // Compact: concatenate the tokens, dropping whitespace between them.
  const scanner = createScanner(value, true);
  const tokens: string[] = [];
  while (scanner.getPosition() < value.length) {
    scanner.scan();
    const offset = scanner.getTokenOffset();
    tokens.push(value.slice(offset, offset + scanner.getTokenLength()));
  }
  return tokens.join("");
}

/**
 * JsonField: strict-JSON textarea with a format button and accessible syntax
 * feedback (withheld while focused, re-checked on blur). FormControl-aware;
 * `ref` reaches the <textarea>, `className` the wrapper.
 */
export const JsonField = ({
  value,
  defaultValue = "",
  onChange,
  rows = 8,
  hideToolbar = false,
  indent = 2,
  className,
  formatLabel,
  validLabel,
  invalidLabel,
  disabled: disabledProp,
  readOnly: readOnlyProp,
  required: requiredProp,
  invalid = false,
  onFocus,
  onBlur,
  "aria-describedby": describedBy,
  "aria-invalid": ariaInvalid,
  spellCheck = false,
  ...rest
}: JsonFieldProps) => {
  const { t } = useI18n();
  const field = useFormControlContext();
  const disabled = Boolean(disabledProp || field?.disabled);
  const readOnly = Boolean(readOnlyProp || field?.readOnly);
  const required = Boolean(requiredProp || field?.required);
  const statusId = `json-status-${useId()}`;
  const [text, setText] = useControllableState({
    value,
    defaultValue,
    onChange,
  });
  const [focused, setFocused] = useState(false);
  const validation: Validation = focused ? { status: "empty" } : validate(text);
  const syntaxInvalid = validation.status === "invalid";

  const formatNow = () => {
    if (disabled || readOnly || validate(text).status !== "valid") return;
    setText(formatJson(text, indent));
  };

  return (
    <div className={cn(styles.root, className)}>
      {!hideToolbar && (
        <div className={styles.toolbar}>
          <IconButton
            type="button"
            label={formatLabel ?? t("jsonField.format")}
            size="small"
            shape="square"
            icon={<LuBraces size={18} aria-hidden />}
            disabled={disabled || readOnly || !text.trim()}
            onClick={formatNow}
          />
        </div>
      )}
      <Textarea
        {...rest}
        rows={rows}
        value={text}
        disabled={disabled}
        readOnly={readOnly}
        required={required}
        spellCheck={spellCheck}
        className={styles.textarea}
        aria-invalid={
          syntaxInvalid || invalid
            ? true
            : ariaInvalid === "false"
              ? false
              : ariaInvalid
        }
        aria-describedby={
          [describedBy, syntaxInvalid ? statusId : undefined]
            .filter(Boolean)
            .join(" ") || undefined
        }
        onChange={(event) => {
          if (!disabled && !readOnly) setText(event.target.value);
        }}
        onFocus={(event) => {
          setFocused(true);
          onFocus?.(event);
        }}
        onBlur={(event) => {
          setFocused(false);
          onBlur?.(event);
        }}
      />
      <div
        id={statusId}
        role="status"
        aria-live="polite"
        className={cn(styles.status, syntaxInvalid && styles.statusInvalid)}
      >
        {validation.status === "valid" && (
          <>
            <LuCircleCheck size={16} aria-hidden />
            <span>{validLabel ?? t("jsonField.valid")}</span>
          </>
        )}
        {validation.status === "invalid" && (
          <>
            <LuCircleAlert size={16} aria-hidden />
            <span>
              {invalidLabel ?? t("jsonField.invalid")}: {validation.error}
            </span>
          </>
        )}
      </div>
    </div>
  );
};

export default JsonField;

// packages/uni/src/JsonField.vue
<script setup lang="ts">
import { computed, ref } from "vue";
import { useNativeId as useId } from "./native-id";
import { applyEdits, createScanner, format } from "jsonc-parser";
import { inheritForm } from "./form-context";
import { useI18n } from "./i18n";
import Textarea from "./Textarea.vue";
defineOptions({ inheritAttrs: false });
const raw = withDefaults(
  defineProps<{
    value?: string;
    modelValue?: string;
    defaultValue?: string;
    disabled?: boolean;
    readOnly?: boolean;
    invalid?: boolean;
    required?: boolean;
    hideToolbar?: boolean;
    indent?: number;
    formatLabel?: string;
    validLabel?: string;
    invalidLabel?: string;
    rows?: number;
    id?: string;
    name?: string;
    ariaLabel?: string;
    ariaLabelledby?: string;
    ariaDescribedby?: string;
    placeholder?: string;
    maxLength?: number;
    variant?: "outline" | "filled" | "unstyled";
    size?: "small" | "medium" | "large";
  }>(),
  { indent: 2, rows: 8 },
);
const props = inheritForm(raw);
const { t } = useI18n();
const local = ref(props.defaultValue ?? ""),
  focused = ref(false);
const text = computed(() => props.modelValue ?? props.value ?? local.value);
const statusId = `mn-json-${useId().replace(/[^a-z0-9]/gi, "")}`;
function validation(value: string) {
  if (!value.trim()) return { status: "empty" };
  try {
    JSON.parse(value);
    return { status: "valid" };
  } catch (error) {
    return {
      status: "invalid",
      error: error instanceof Error ? error.message : String(error),
    };
  }
}
const status = computed(() =>
    focused.value ? { status: "empty" } : validation(text.value),
  ),
  invalid = computed(() => props.invalid || status.value.status === "invalid");
const emit = defineEmits<{
  change: [text: string];
  "update:modelValue": [text: string];
  error: [message: string];
  focus: [event: unknown];
  blur: [event: unknown];
}>();
function change(value: string) {
  if (props.disabled || props.readOnly) return;
  if (props.value === undefined && props.modelValue === undefined)
    local.value = value;
  emit("change", value);
  emit("update:modelValue", value);
  const result = validation(value);
  if (result.status === "invalid")
    emit("error", result.error ?? t("jsonField.invalid"));
}
function formatNow() {
  if (
    props.disabled ||
    props.readOnly ||
    validation(text.value).status !== "valid"
  )
    return;
  const spaces = Math.min(10, Math.max(0, Math.trunc(props.indent) || 0));
  if (spaces) {
    change(
      applyEdits(
        text.value,
        format(text.value, undefined, {
          tabSize: spaces,
          insertSpaces: true,
          eol: "\n",
        }),
      ),
    );
    return;
  }
  const scanner = createScanner(text.value, true),
    tokens: string[] = [];
  while (scanner.getPosition() < text.value.length) {
    scanner.scan();
    tokens.push(
      text.value.slice(
        scanner.getTokenOffset(),
        scanner.getTokenOffset() + scanner.getTokenLength(),
      ),
    );
  }
  change(tokens.join(""));
}
</script>
<template>
  <view class="mn-json-field"
    ><view v-if="!hideToolbar" class="mn-uni-json-toolbar"
      ><button
        class="mn-close"
        :aria-label="formatLabel ?? t('jsonField.format')"
        :disabled="props.disabled || props.readOnly || !text.trim()"
        @tap="formatNow"
      >
        { }
      </button></view
    ><Textarea
      v-bind="$attrs"
      :value="text"
      :rows="rows"
      :disabled="props.disabled"
      :read-only="props.readOnly"
      :invalid="invalid"
      :required="props.required"
      :id="id"
      :name="name"
      :aria-label="ariaLabel"
      :aria-labelledby="ariaLabelledby"
      :aria-describedby="[ariaDescribedby, statusId].filter(Boolean).join(' ')"
      :placeholder="placeholder"
      :max-length="maxLength"
      :variant="variant"
      :size="size"
      class="mn-code"
      @change="change"
      @focus="
        focused = true;
        emit('focus', $event);
      "
      @blur="
        focused = false;
        emit('blur', $event);
      "
    /><view
      :id="statusId"
      role="status"
      aria-live="polite"
      class="mn-json-status"
      :class="{ 'mn-error': status.status === 'invalid' }"
      ><template v-if="status.status === 'valid'">{{
        validLabel ?? t("jsonField.valid")
      }}</template
      ><template v-else-if="status.status === 'invalid'"
        >{{ invalidLabel ?? t("jsonField.invalid") }}:
        {{ status.error }}</template
      ></view
    ></view
  >
</template>
