// packages/lib-core/src/components/Radio/Radio.tsx
import React, { useContext, useId } from "react";
import { cn } from "../../utils/cn";
import { IconCircleInfoFilled } from "../../internal/icons";
import { pickDataAttributes } from "../../internal/dataAttributes";
import { hooks } from "../../internal/stylingHooks";
import styles from "./radio.module.scss";
import type { RadioProps } from "./types";
import { RadioGroupContext } from "./RadioGroup";
import { useFormControlContext } from "../FormControl/context";

/**
 * Radio: a native radio input. Inside a RadioGroup, the group drives its
 * checked state, name, size, color and disabled state. `ref` reaches the
 * <input>.
 */
const Radio = ({
  checked,
  defaultChecked,
  disabled,
  name,
  value,
  onChange,
  size = "medium",
  label,
  children,
  "aria-label": ariaLabel,
  "aria-labelledby": ariaLabelledBy,
  id,
  "aria-describedby": ariaDescribedBy,
  className = "",
  style,
  color = "primary",
  required = false,
  error = false,
  errorIcon = <IconCircleInfoFilled />,
  errorMessage,
  helperText,
  ref,
  ...rest
}: RadioProps) => {
  const group = useContext(RadioGroupContext);
  const fc = useFormControlContext();
  const helperId = useId();
  // An explicit `disabled` wins over an enclosing FormControl's state.
  const ownDisabled = disabled ?? fc?.disabled ?? false;

  const handleChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    if (ownDisabled) return;

    if (group) {
      if (value !== undefined) group.onChange(value, e);
    } else {
      onChange?.(e.target.checked, e);
    }
  };

  const isChecked = group
    ? group.value !== undefined && group.value === value
    : checked;
  const isDisabled = group ? group.disabled || ownDisabled : ownDisabled;
  const radioName = group ? group.name : name;
  const radioSize = group ? group.size || size : size;
  const radioColor = group?.color ?? color;
  const helper = error ? errorMessage : helperText;
  const content = label ?? children;

  return (
    <div
      className={cn(
        styles.radioWrapper,
        styles[radioSize],
        styles[radioColor],
        error && styles.error,
        className,
      )}
      style={style}
      {...pickDataAttributes(rest)}
      {...hooks("radio", "root", {
        // An uncontrolled radio outside a group: the DOM holds the state
        state:
          isChecked === undefined
            ? undefined
            : isChecked
              ? "checked"
              : "unchecked",
        disabled: isDisabled,
        invalid: error,
        size: radioSize,
        color: radioColor,
      })}
    >
      <label className={cn(styles.radio, isDisabled && styles.disabled)}>
        <input
          type="radio"
          ref={ref}
          name={radioName}
          value={value}
          checked={isChecked}
          defaultChecked={group ? undefined : defaultChecked}
          disabled={isDisabled}
          onChange={handleChange}
          required={required}
          aria-label={ariaLabel}
          aria-labelledby={ariaLabelledBy}
          id={id}
          // Consumer descriptions are merged with the helper / error text.
          aria-describedby={
            [helper ? helperId : null, ariaDescribedBy]
              .filter(Boolean)
              .join(" ") || undefined
          }
          className={styles.input}
          {...hooks("radio", "input")}
        />
        <span className={styles.radioMark} {...hooks("radio", "control")} />
        {content != null && content !== false && content !== "" && (
          <span className={styles.label} {...hooks("radio", "label")}>
            {content}
          </span>
        )}
      </label>
      {helper && (
        <div className={styles.helperTextWrapper}>
          {error && errorMessage && (
            <span className={styles.errorIcon} aria-hidden>
              {errorIcon}
            </span>
          )}
          <span
            id={helperId}
            className={cn(styles.helperText, error && styles.errorText)}
            {...hooks("radio", "helper-text")}
          >
            {helper}
          </span>
        </div>
      )}
    </div>
  );
};

export default React.memo(Radio);

// packages/uni/src/Radio.vue
<script setup lang="ts">
import { inject, computed, ref, onBeforeUnmount } from "vue";
import { useNativeId as useId } from "./native-id";
import { inheritForm } from "./form-context";
import type { RadioContext } from "./radio-context";
const raw = withDefaults(
  defineProps<{
    checked?: boolean;
    defaultChecked?: boolean;
    disabled?: boolean;
    readOnly?: boolean;
    label?: string;
    value?: string | number;
    name?: string;
    id?: string;
    size?: "small" | "medium" | "large";
    color?: "primary" | "success" | "warning" | "danger";
    required?: boolean;
    invalid?: boolean;
    error?: boolean;
    errorMessage?: string;
    helperText?: string;
    errorIcon?: string;
    ariaLabel?: string;
    ariaLabelledby?: string;
    ariaDescribedby?: string;
  }>(),
  {
    checked: undefined,
    disabled: undefined,
    readOnly: undefined,
    error: undefined,
  },
);
const props = inheritForm(raw),
  group = inject<RadioContext | undefined>("minerva:radio", undefined);
const local = ref(props.defaultChecked ?? false),
  helpId = `mn-radio-${useId().replace(/[^a-z0-9]/gi, "")}`;
const chosen = computed(() =>
    group ? group.value.value === props.value : (props.checked ?? local.value),
  ),
  disabled = computed(() => !!group?.disabled.value || props.disabled),
  readOnly = computed(() => !!group?.readOnly.value || props.readOnly),
  invalid = computed(
    () => group?.error.value ?? props.error ?? props.invalid ?? false,
  ),
  size = computed(() => group?.size.value ?? props.size ?? "medium"),
  color = computed(() => group?.color.value ?? props.color ?? "primary"),
  help = computed(() =>
    invalid.value && props.errorMessage ? props.errorMessage : props.helperText,
  ),
  described = computed(
    () =>
      [
        props.ariaDescribedby,
        group?.describedBy.value,
        help.value ? helpId : undefined,
      ]
        .filter(Boolean)
        .join(" ") || undefined,
  );
if (group) {
  const unregister = group.register(
    helpId,
    computed(() => props.value),
    disabled,
  );
  onBeforeUnmount(unregister);
}
const emit = defineEmits<{
  change: [checked: boolean, event?: unknown];
  "update:checked": [checked: boolean];
}>();
function choose(event?: unknown) {
  if (disabled.value || readOnly.value || chosen.value) return;
  if (group) {
    if (props.value !== undefined) group.select(props.value, event);
    return;
  }
  if (props.checked === undefined) local.value = true;
  emit("update:checked", true);
  emit("change", true, event);
}
</script>
<template>
  <view
    class="mn-choice mn-uni-radio"
    :class="[
      `mn-radio-${size}`,
      `mn-choice-size-${size}`,
      `mn-choice-color-${color}`,
      { 'mn-disabled': disabled, 'mn-invalid': invalid },
    ]"
    role="radio"
    :id="id"
    :name="group?.name.value ?? name"
    :value="value"
    :aria-label="props.ariaLabel ?? label"
    :aria-labelledby="props.ariaLabelledby"
    :aria-describedby="described"
    :aria-checked="chosen"
    :aria-disabled="disabled"
    :aria-readonly="readOnly"
    :aria-required="group?.required.value ?? props.required"
    :aria-invalid="invalid"
    :tabindex="disabled ? -1 : group ? (group.tabStop(helpId) ? 0 : -1) : 0"
    @tap="choose"
    @keydown.space.prevent="choose($event)"
    ><input
      v-if="!group && name && chosen"
      class="mn-uni-visually-hidden"
      :name="name"
      :value="value ?? 'on'"
      :disabled="disabled"
      aria-hidden="true"
      :tabindex="-1"
    /><text
      class="mn-choice-indicator mn-radio"
      :class="{ 'mn-active': chosen }"
      aria-hidden="true"
      >{{ chosen ? "●" : "" }}</text
    ><view class="mn-choice-content"
      ><text v-if="label">{{ label }}</text
      ><slot v-else /></view
    ><text
      v-if="help"
      :id="helpId"
      class="mn-choice-helper"
      :class="{ 'mn-error': invalid }"
      ><slot v-if="invalid" name="error-icon">{{ errorIcon ?? "ⓘ" }}</slot
      >{{ help }}</text
    ></view
  >
</template>
