// packages/lib-core/src/components/Skeleton/SkeletonText.tsx
import { cn } from "../../utils/cn";
import { resolveSpace } from "@minerva/core";
import Skeleton from "./Skeleton";
import type { SkeletonTextProps } from "./types";
import styles from "./skeleton.module.scss";

/**
 * SkeletonText: a decorative block of text-line placeholders (the last line is
 * shortened to 70% by default). Hidden from assistive technologies; expose the
 * busy state on the surrounding container.
 */
export const SkeletonText = ({
  lines = 3,
  lineHeight = "1em",
  gap = 2,
  shrinkLast = true,
  animation = "pulse",
  className,
  style,
  ref,
  ...rest
}: SkeletonTextProps) => {
  const count = Number.isFinite(lines) ? Math.max(0, Math.floor(lines)) : 0;
  return (
    <div
      ref={ref}
      aria-hidden="true"
      {...rest}
      className={cn(styles.skeletonText, className)}
      style={{ gap: resolveSpace(gap), ...style }}
    >
      {Array.from({ length: count }, (_, index) => (
        <Skeleton
          key={index}
          decorative
          variant="text"
          animation={animation}
          height={lineHeight}
          width={shrinkLast && index === count - 1 ? "70%" : "100%"}
        />
      ))}
    </div>
  );
};

export default SkeletonText;

// packages/uni/src/SkeletonText.vue
<script setup lang="ts">
import { computed } from "vue";
import Skeleton from "./Skeleton.vue";
import { lineCount, spacing } from "./primitives";
const props = withDefaults(
  defineProps<{
    lines?: number;
    lineHeight?: string | number;
    gap?: string | number;
    lastLineWidth?: string;
    animated?: boolean;
    shrinkLast?: boolean;
    animation?: "pulse" | "wave" | "false";
  }>(),
  {
    lines: 3,
    lineHeight: "1em",
    gap: 2,
    shrinkLast: true,
    animated: undefined,
  },
);
const count = computed(() => lineCount(props.lines));
</script>
<template>
  <view
    class="mn-skeleton-text"
    :style="{ gap: spacing(gap) }"
    aria-hidden="true"
    ><Skeleton
      v-for="line in count"
      :key="line"
      decorative
      :height="lineHeight"
      :width="line === count && shrinkLast ? (lastLineWidth ?? '70%') : '100%'"
      :animation="animation ?? (animated === false ? 'false' : 'pulse')"
      data-part="line"
  /></view>
</template>
