// packages/native/src/components/Table/index.tsx
import type { ReactNode } from "react";
import {
  ActivityIndicator,
  Pressable,
  ScrollView,
  Text,
  View,
  type ViewProps,
} from "react-native";
import {
  getColumnCompare,
  nextSortState,
  type TableSortState,
} from "@minerva/core";
import { useI18n, useTheme } from "../../theme/MinervaProvider";
import { textStyle } from "../../internal/styles";
import { useControllable } from "../../internal/useControllable";
import { Checkbox } from "../Checkbox";
import { Button } from "../Button";
import { Pagination, type PaginationProps } from "../Pagination";
export type { TableSortState } from "@minerva/core";
export type TableRowKey = string | number;
export interface TableColumn<T> {
  key: string;
  header: ReactNode;
  render?: (row: T, index: number) => ReactNode;
  width?: number;
  align?: "left" | "center" | "right";
  ellipsis?: boolean;
  sortable?: boolean | ((a: T, b: T) => number);
}
export interface TableRowSelection<T> {
  selectedRowKeys?: TableRowKey[];
  defaultSelectedRowKeys?: TableRowKey[];
  onChange?: (keys: TableRowKey[], rows: T[]) => void;
  getCheckboxProps?: (row: T) => { disabled?: boolean };
  getRowLabel?: (row: T, index: number) => string;
}
export interface TableProps<T> extends Omit<ViewProps, "children"> {
  columns: TableColumn<T>[];
  data: T[];
  rowKey?: (row: T, index: number) => TableRowKey;
  emptyText?: ReactNode;
  /** @default false */
  loading?: boolean;
  /** @default "medium" */
  size?: "small" | "medium" | "large";
  /** @default "simple" */
  variant?: "simple" | "striped" | "bordered";
  scroll?: { x?: number; y?: number };
  sortState?: TableSortState | null;
  /** @default null */
  defaultSortState?: TableSortState | null;
  onSortChange?: (state: TableSortState) => void;
  /** @default false */
  manualSort?: boolean;
  rowSelection?: TableRowSelection<T>;
}
function Content({ children }: { children: ReactNode }) {
  const { tokens } = useTheme();
  return typeof children === "string" || typeof children === "number" ? (
    <Text style={textStyle(tokens)}>{children}</Text>
  ) : (
    children
  );
}
export function TableRoot({ children, ...props }: ViewProps) {
  return (
    <View {...props} role="table">
      {children}
    </View>
  );
}
export function TableHead(props: ViewProps) {
  return <View {...props} role="rowgroup" />;
}
export const TableBody = TableHead;
export function TableRow({ style, ...props }: ViewProps) {
  return (
    <View {...props} role="row" style={[{ flexDirection: "row" }, style]} />
  );
}
export function TableHeader({ children, ...props }: ViewProps) {
  return (
    <View {...props} role="columnheader">
      <Content>{children}</Content>
    </View>
  );
}
export function TableCell({ children, ...props }: ViewProps) {
  return (
    <View {...props} role="cell">
      <Content>{children}</Content>
    </View>
  );
}
/** Horizontally scrollable native table; row keys keep selection stable through sorting. */
export function Table<T>({
  columns,
  data,
  rowKey = (_, i) => i,
  emptyText,
  loading = false,
  size = "medium",
  variant = "simple",
  scroll,
  sortState,
  defaultSortState = null,
  onSortChange,
  manualSort = false,
  rowSelection,
  style,
  ...props
}: TableProps<T>) {
  const { tokens: t } = useTheme();
  const { t: translate } = useI18n();
  const [sort, setSort] = useControllable(
    sortState,
    defaultSortState,
    (next) => {
      if (next) onSortChange?.(next);
    },
  );
  const [selected, setSelected] = useControllable(
    rowSelection?.selectedRowKeys,
    rowSelection?.defaultSelectedRowKeys ?? [],
    (keys) =>
      rowSelection?.onChange?.(
        keys,
        data.filter((row, index) => keys.includes(rowKey(row, index))),
      ),
  );
  const indexed = data.map((row, index) => ({
    row,
    index,
    key: rowKey(row, index),
  }));
  const comparator = columns.find((c) => c.key === sort?.key);
  const compare = comparator && getColumnCompare(comparator);
  if (!manualSort && compare && sort?.order)
    indexed.sort(
      (a, b) => (sort.order === "descend" ? -1 : 1) * compare(a.row, b.row),
    );
  const enabled = indexed
    .filter(({ row }) => !rowSelection?.getCheckboxProps?.(row).disabled)
    .map((r) => r.key);
  const all = enabled.length > 0 && enabled.every((k) => selected.includes(k));
  const padding =
    t.space[size === "small" ? "2" : size === "large" ? "4" : "3"];
  const cell = (column: TableColumn<T>) => ({
    width: column.width ?? 160,
    padding,
    borderRightWidth: variant === "bordered" ? 1 : 0,
    borderColor: t.colors["border-color"],
    justifyContent: "center" as const,
  });
  const body = (
    <TableRoot
      {...props}
      style={[
        { minWidth: scroll?.x, backgroundColor: t.colors["surface-color"] },
        style,
      ]}
      accessibilityState={{ busy: loading }}
    >
      <TableHead>
        <TableRow style={{ backgroundColor: t.colors["surface-muted-color"] }}>
          {rowSelection && (
            <View style={{ width: 52, padding }}>
              <Checkbox
                accessibilityLabel={translate("table.selectAll")}
                checked={all}
                indeterminate={
                  !all && enabled.some((k) => selected.includes(k))
                }
                disabled={!enabled.length}
                onChange={() =>
                  setSelected(
                    all
                      ? selected.filter((k) => !enabled.includes(k))
                      : [...new Set([...selected, ...enabled])],
                  )
                }
              />
            </View>
          )}
          {columns.map((column) => (
            <TableHeader key={column.key} style={cell(column)}>
              {column.sortable ? (
                <Pressable
                  accessibilityRole="button"
                  accessibilityLabel={
                    typeof column.header === "string"
                      ? column.header
                      : column.key
                  }
                  accessibilityHint={
                    sort?.key === column.key
                      ? (sort.order ?? "unsorted")
                      : "unsorted"
                  }
                  onPress={() => setSort(nextSortState(sort, column.key))}
                >
                  <Content>{column.header}</Content>
                  {sort?.key === column.key && sort.order && (
                    <Text style={textStyle(t)}>
                      {sort.order === "ascend" ? "↑" : "↓"}
                    </Text>
                  )}
                </Pressable>
              ) : (
                column.header
              )}
            </TableHeader>
          ))}
        </TableRow>
      </TableHead>
      <TableBody>
        {loading ? (
          <ActivityIndicator
            accessibilityLabel={translate("loadingState.label")}
            color={t.colors["primary-color"]}
          />
        ) : indexed.length === 0 ? (
          <View style={{ padding }}>
            <Content>{emptyText ?? translate("table.empty")}</Content>
          </View>
        ) : (
          indexed.map(({ row, index, key }, position) => (
            <TableRow
              key={key}
              style={{
                borderBottomWidth: 1,
                borderColor: t.colors["border-color"],
                backgroundColor:
                  variant === "striped" && position % 2
                    ? t.colors["surface-muted-color"]
                    : undefined,
              }}
            >
              {rowSelection && (
                <View style={{ width: 52, padding }}>
                  <Checkbox
                    accessibilityLabel={translate("table.selectRow", {
                      row: String(
                        rowSelection.getRowLabel?.(row, index) ?? key,
                      ),
                    })}
                    checked={selected.includes(key)}
                    disabled={rowSelection.getCheckboxProps?.(row).disabled}
                    onChange={() =>
                      setSelected(
                        selected.includes(key)
                          ? selected.filter((k) => k !== key)
                          : [...selected, key],
                      )
                    }
                  />
                </View>
              )}
              {columns.map((column) => (
                <TableCell key={column.key} style={cell(column)}>
                  {column.render ? (
                    column.render(row, index)
                  ) : (
                    <Text
                      numberOfLines={column.ellipsis ? 1 : undefined}
                      style={[textStyle(t), { textAlign: column.align }]}
                    >
                      {String(
                        (row as Record<string, unknown>)[column.key] ?? "",
                      )}
                    </Text>
                  )}
                </TableCell>
              ))}
            </TableRow>
          ))
        )}
      </TableBody>
    </TableRoot>
  );
  return (
    <ScrollView horizontal nestedScrollEnabled style={{ flexGrow: 0 }}>
      <ScrollView
        nestedScrollEnabled
        style={{ maxHeight: scroll?.y, flexGrow: 0 }}
      >
        {body}
      </ScrollView>
    </ScrollView>
  );
}
export interface DataTableProps<T> extends TableProps<T> {
  pagination?: PaginationProps;
  error?: ReactNode;
  onRetry?: () => void;
  retryLabel?: string;
}
export function DataTable<T>({
  pagination,
  error,
  onRetry,
  retryLabel,
  ...props
}: DataTableProps<T>) {
  const { t: translate } = useI18n();
  return error ? (
    <View accessibilityRole="alert">
      <Content>{error}</Content>
      {onRetry && (
        <Button onPress={onRetry}>
          {retryLabel ?? translate("table.retry")}
        </Button>
      )}
    </View>
  ) : (
    <View>
      <Table {...props} />
      {pagination && <Pagination {...pagination} />}
    </View>
  );
}

// packages/uni/src/Table.vue
<script setup lang="ts">
import { useI18n } from "./i18n";
const { t } = useI18n();
import { computed, ref } from "vue";
import type { Key, Row, Column, TableProps } from "./table-types";
const props = withDefaults(defineProps<TableProps>(), {
  columns: () => [],
  data: () => [],
  rowKey: "id",
  size: "medium",
  variant: "simple",
  defaultCurrent: 1,
});
const emit = defineEmits([
  "sortChange",
  "selectionChange",
  "rowClick",
  "filterChange",
  "pageChange",
]);
const sort = ref<{ key: string; order: string | null } | null>(
  props.defaultSortState ?? null,
);
const selection = ref<Key[]>(props.rowSelection?.defaultSelectedRowKeys ?? []);
const localFilters = ref<Record<string, string[]>>({});
const localPage = ref(props.defaultCurrent);
const selected = computed(
  () =>
    props.rowSelection?.selectedRowKeys ??
    props.selectedRowKeys ??
    selection.value,
);
const active = computed(() =>
  props.sortState === undefined ? sort.value : props.sortState,
);
const filtering = computed(() => props.filters ?? localFilters.value);
const selectionEnabled = computed(
  () => props.selectable || !!props.rowSelection,
);
const allRows = computed(() =>
  props.data.map((row, i) => ({
    row,
    key:
      typeof props.rowKey === "function"
        ? props.rowKey(row, i)
        : typeof row[props.rowKey] === "string" ||
            typeof row[props.rowKey] === "number"
          ? (row[props.rowKey] as Key)
          : i,
    disabled: !!(
      props.rowSelection?.getCheckboxProps?.(row).disabled ?? row.disabled
    ),
  })),
);
const ordered = computed(() => {
  let r = allRows.value.filter(
    (e) =>
      props.manualFilter ||
      Object.entries(filtering.value).every(
        ([key, values]) =>
          !values.length || values.includes(String(e.row[key])),
      ),
  );
  if (props.manualSort || !active.value?.order) return r;
  const { key, order } = active.value;
  const compare = props.columns.find((c) => c.key === key)?.sortable;
  return [...r].sort((a, b) => {
    if (typeof compare === "function")
      return compare(a.row, b.row) * (order === "ascend" ? 1 : -1);
    const av = a.row[key],
      bv = b.row[key];
    if (av == null) return bv == null ? 0 : 1;
    if (bv == null) return -1;
    return (
      (typeof av === "number" && typeof bv === "number"
        ? av - bv
        : String(av).localeCompare(String(bv), undefined, { numeric: true })) *
      (order === "ascend" ? 1 : -1)
    );
  });
});
const pages = computed(() =>
  props.pageSize
    ? Math.max(1, Math.ceil(ordered.value.length / props.pageSize))
    : 1,
);
const page = computed(() =>
  Math.max(1, Math.min(pages.value, props.current ?? localPage.value)),
);
const rows = computed(() =>
  props.pageSize
    ? ordered.value.slice(
        (page.value - 1) * props.pageSize,
        page.value * props.pageSize,
      )
    : ordered.value,
);
const enabled = computed(() => rows.value.filter((r) => !r.disabled));
const allChecked = computed(
  () =>
    enabled.value.length > 0 &&
    enabled.value.every((r) => selected.value.includes(r.key)),
);
const someChecked = computed(() =>
  enabled.value.some((r) => selected.value.includes(r.key)),
);
function order(c: Column) {
  if (!c.sortable || props.disabled || props.readOnly) return;
  sort.value = {
    key: c.key,
    order:
      active.value?.key !== c.key || active.value.order === null
        ? "ascend"
        : active.value.order === "ascend"
          ? "descend"
          : null,
  };
  emit("sortChange", sort.value);
}
function changeSelection(keys: Key[]) {
  selection.value = keys;
  const records = allRows.value
    .filter((r) => keys.includes(r.key))
    .map((r) => r.row);
  emit("selectionChange", keys, records);
  props.rowSelection?.onChange?.(keys, records);
}
function select(key: Key) {
  if (
    props.disabled ||
    props.readOnly ||
    allRows.value.find((r) => r.key === key)?.disabled
  )
    return;
  changeSelection(
    selected.value.includes(key)
      ? selected.value.filter((k) => k !== key)
      : [...selected.value, key],
  );
}
function selectAll() {
  if (props.disabled || props.readOnly) return;
  const keys = enabled.value.map((r) => r.key);
  changeSelection(
    allChecked.value
      ? selected.value.filter((k) => !keys.includes(k))
      : [...new Set([...selected.value, ...keys])],
  );
}
function filter(key: string, value: string) {
  if (props.disabled || props.readOnly) return;
  const old = filtering.value[key] ?? [];
  localFilters.value = {
    ...filtering.value,
    [key]: old.includes(value)
      ? old.filter((v) => v !== value)
      : [...old, value],
  };
  localPage.value = 1;
  emit("filterChange", localFilters.value);
  emit("pageChange", 1, props.pageSize);
}
function turn(n: number) {
  if (props.disabled || n < 1 || n > pages.value) return;
  localPage.value = n;
  emit("pageChange", n, props.pageSize);
}
function length(v?: number | string) {
  return typeof v === "number" ? `${v}px` : v;
}
function cellStyle(c: Column) {
  let offset = 0;
  if (c.fixed) {
    const list =
      c.fixed === "left" ? props.columns : [...props.columns].reverse();
    for (const col of list) {
      if (col.key === c.key) break;
      if (col.fixed === c.fixed)
        offset += typeof col.width === "number" ? col.width : 120;
    }
  }
  return {
    textAlign: (c.align ?? "left") as any,
    minWidth: length(c.width),
    width: length(c.width),
    position: c.fixed ? ("sticky" as const) : undefined,
    left: c.fixed === "left" ? `${offset}px` : undefined,
    right: c.fixed === "right" ? `${offset}px` : undefined,
    zIndex: c.fixed ? 2 : undefined,
  };
}
</script>
<template>
  <view class="mn-table-container"
    ><scroll-view
      scroll-x
      :scroll-y="!!scroll?.y"
      class="mn-table-scroll"
      :style="{ maxHeight: length(scroll?.y) }"
      ><view
        class="mn-table"
        :class="[
          `mn-table-${variant}`,
          `mn-table-${size}`,
          { 'mn-table-hoverable': hoverable },
        ]"
        :style="{ minWidth: length(scroll?.x) }"
        ><view class="mn-table-row mn-table-head"
          ><button
            v-if="selectionEnabled"
            class="mn-table-cell"
            data-action="select-all"
            :class="{ 'mn-disabled': disabled || readOnly || !enabled.length }"
            :disabled="disabled || readOnly || !enabled.length"
            @tap="selectAll"
          >
            {{ allChecked ? "☑" : someChecked ? "⊟" : "☐" }}</button
          ><view
            v-for="c in columns"
            :key="c.key"
            class="mn-table-cell"
            :style="cellStyle(c)"
            ><button
              class="mn-option"
              :data-sort="c.key"
              :class="{ 'mn-disabled': !c.sortable || disabled || readOnly }"
              :disabled="!c.sortable || disabled || readOnly"
              @tap="order(c)"
            >
              <slot name="header" :column="c">{{ c.header }}</slot>
              {{
                active?.key === c.key
                  ? active.order === "ascend"
                    ? "↑"
                    : active.order === "descend"
                      ? "↓"
                      : ""
                  : ""
              }}</button
            ><view v-if="c.filters" class="mn-table-filters"
              ><button
                v-for="option in c.filters"
                :key="option.value"
                class="mn-tag"
                :data-filter="`${c.key}:${option.value}`"
                :class="[
                  { 'mn-active': filtering[c.key]?.includes(option.value) },
                  { 'mn-disabled': disabled || readOnly },
                ]"
                :disabled="disabled || readOnly"
                @tap="filter(c.key, option.value)"
              >
                {{ option.text }}
              </button></view
            ></view
          ></view
        ><text v-if="loading" class="mn-muted"
          ><slot name="loading">{{ t("common.loading") }}</slot></text
        ><view v-else-if="!rows.length" class="mn-empty"
          ><slot name="empty">{{ emptyText ?? t("table.empty") }}</slot></view
        ><view
          v-for="entry in loading ? [] : rows"
          :key="entry.key"
          class="mn-table-row"
          :class="{ 'mn-row-selected': selected.includes(entry.key) }"
          @tap="emit('rowClick', entry.row)"
          ><button
            v-if="selectionEnabled"
            class="mn-table-cell mn-select-row"
            :data-select="entry.key"
            :class="{ 'mn-disabled': disabled || readOnly || entry.disabled }"
            :disabled="disabled || readOnly || entry.disabled"
            @tap.stop="select(entry.key)"
          >
            {{ selected.includes(entry.key) ? "☑" : "☐" }}</button
          ><view
            v-for="c in columns"
            :key="c.key"
            class="mn-table-cell"
            :class="{ 'mn-ellipsis': c.ellipsis }"
            data-part="cell"
            :style="cellStyle(c)"
            ><slot name="cell" :row="entry.row" :column="c">{{
              entry.row[c.key]
            }}</slot></view
          ></view
        ><slot name="footer" /></view></scroll-view
    ><view v-if="pageSize" class="mn-pagination"
      ><button
        class="mn-button mn-variant-outline"
        data-action="previous-page"
        :class="{ 'mn-disabled': disabled || page <= 1 }"
        :disabled="disabled || page <= 1"
        @tap="turn(page - 1)"
      >
        Previous</button
      ><text>{{ page }} / {{ pages }}</text
      ><button
        class="mn-button mn-variant-outline"
        data-action="next-page"
        :class="{ 'mn-disabled': disabled || page >= pages }"
        :disabled="disabled || page >= pages"
        @tap="turn(page + 1)"
      >
        Next
      </button></view
    ></view
  >
</template>
