// packages/lib-web-components/src/components/key-value-editor/key-value-editor.ts
import { css, html, nothing } from "lit";
import { property } from "lit/decorators.js";
import { repeat } from "lit/directives/repeat.js";
import iconButtonStyles from "@lib-core-styles/components/IconButton/iconButton.module.scss?inline";
import styles from "@lib-core-styles/components/KeyValueEditor/keyValueEditor.module.scss?inline";
import { AriaController } from "../../internal/aria";
import { DEV, devWarn } from "../../internal/dev";
import {
  FormAssociatedElement,
  type ValidityResult,
} from "../../internal/form";
import { IconPlus, IconX } from "../../internal/icons";
import { LocaleController } from "../../internal/locale";
import { hostStyles } from "../../internal/minerva-element";
import { MinervaButton } from "../button/button";
import { MinervaFormControl } from "../form-control/form-control";
import { MinervaTextarea } from "../textarea/textarea";
import { sharedStyles } from "../../internal/styles";

/** One row of a `<minerva-key-value-editor>` */
export interface KeyValueEntry {
  /** Stable id of the row (error lookup, focus); generated when omitted */
  id: string;
  /** Key text (whitespace and newlines are preserved) */
  key: string;
  /** Value text (whitespace and newlines are preserved) */
  value: string;
}

/** Field errors of one row */
export interface KeyValueEntryErrors {
  /** Error message of the key field */
  key?: string;
  /** Error message of the value field */
  value?: string;
}

let nextEditor = 0;

/**
 * Ordered list of editable string pairs (`<KeyValueEditor>` of lib-core):
 * multi-line keys and values with add / remove actions. Rows are tracked by
 * their stable `id`, so duplicate keys and reordering are safe. Focus
 * follows the actions: adding a row focuses its key field; removing one
 * focuses the next row's remove button (else the previous one, else the add
 * button).
 *
 * `value` is a JS array of `{ id, key, value }` entries (property). The
 * `value` attribute sets the initial rows (restored by `form.reset()`) as
 * JSON: an array of `{ key, value }` objects or a `{ "key": "value" }`
 * object.
 *
 * Form-associated: submits the rows under `name` as a JSON string — an
 * array of `{ "key", "value" }` objects in row order (ids are not
 * submitted), e.g. `[{"key":"a","value":"1"}]`. `required` makes an editor
 * without rows invalid (`valueMissing`). Validation of the texts belongs to
 * the consumer (`errors`, `setCustomValidity()`).
 *
 * @summary Editable list of key / value pairs.
 * @tag minerva-key-value-editor
 * @csspart root - The container
 * @csspart row - Each row (key field, value field and remove button)
 * @csspart remove-button - The remove button of a row (web components only: React renders an IconButton, styled with its own hooks)
 * @csspart add-button - The add button (web components only: React renders a Button, styled with its own hooks)
 * @fires minerva-input - A key or value is being typed; `detail: { value }` (the entries)
 * @fires change - A row was committed (field blur), added or removed
 * @fires minerva-change - A row was committed (field blur), added or removed; `detail: { value }`
 */
export class MinervaKeyValueEditor extends FormAssociatedElement {
  static override tagName = "minerva-key-value-editor";
  static override dependencies = [
    MinervaButton,
    MinervaFormControl,
    MinervaTextarea,
  ];
  static override styles = [
    hostStyles,
    css`
      :host {
        display: block;
        width: 100%;
        min-width: 0;
      }
    `,
    sharedStyles(iconButtonStyles),
    sharedStyles(styles),
    css`
      /* lib-core sizes the key <textarea>; reach it through its variable */
      .key {
        --textarea-min-height: var(
          --key-value-editor-control-height,
          var(--control-height-sm)
        );
      }
    `,
  ];

  /** Rows (property; the `value` attribute sets `defaultValue`) */
  @property({ attribute: false })
  value: KeyValueEntry[] = [];

  /** Initial rows, restored by `form.reset()` (the `value` attribute, JSON) */
  @property({
    attribute: "value",
    converter: { fromAttribute: (text: string | null) => parseEntries(text) },
  })
  defaultValue: KeyValueEntry[] = [];

  /** Label of the key fields (followed by the row number for screen readers) */
  @property({ attribute: "key-label" })
  keyLabel?: string;

  /** Label of the value fields */
  @property({ attribute: "value-label" })
  valueLabel?: string;

  /** Text of the add button */
  @property({ attribute: "add-label" })
  addLabel?: string;

  /** Accessible label of the remove buttons (followed by the row number) */
  @property({ attribute: "remove-label" })
  removeLabel?: string;

  /** Field errors by entry id */
  @property({ attribute: false })
  errors?: Record<string, KeyValueEntryErrors>;

  private readonly editorId = `kv-${nextEditor++}`;
  private nextId = 0;
  private dirty = false;
  private pendingFocus:
    | { kind: "add"; id: string }
    | { kind: "remove"; id: string; nextId?: string }
    | null = null;
  private readonly locale = new LocaleController(this);
  private readonly aria = new AriaController(this, () => this.labels);

  /** Focuses the first key field (else the add button) */
  override focus(options?: FocusOptions): void {
    const target =
      this.renderRoot.querySelector<HTMLElement>("minerva-textarea") ??
      this.renderRoot.querySelector<HTMLElement>("minerva-button");
    target?.focus(options);
  }

  protected getFormValue(): string {
    return JSON.stringify(this.value.map(({ key, value }) => ({ key, value })));
  }

  protected override getValidity(): ValidityResult {
    if (this.required && this.value.length === 0) {
      return {
        flags: { valueMissing: true },
        message: this.locale.t("validation.valueMissing"),
        anchor:
          this.renderRoot.querySelector<HTMLElement>("minerva-button") ?? null,
      };
    }
    return { flags: {}, message: "" };
  }

  protected resetFormValue(): void {
    this.dirty = false;
    this.value = this.defaultValue;
  }

  protected override restoreFormState(state: unknown): void {
    if (typeof state === "string") this.value = parseEntries(state);
  }

  protected override willUpdate(changed: Map<PropertyKey, unknown>): void {
    // first update: rows set before connecting win over the default
    // unless the value attribute is present
    if (
      changed.has("defaultValue") &&
      !this.dirty &&
      (this.hasUpdated || this.hasAttribute("value"))
    ) {
      this.value = this.defaultValue;
    }
    if (changed.has("value")) {
      // entries without an id get one (rows are tracked by id)
      if (this.value.some((entry) => !entry.id)) {
        this.value = this.value.map((entry) =>
          entry.id ? entry : { ...entry, id: this.newId() },
        );
      }
      if (DEV) {
        const ids = this.value.map((entry) => entry.id);
        if (new Set(ids).size !== ids.length) {
          devWarn(
            MinervaKeyValueEditor.tagName,
            "entries have duplicate ids: rows are tracked by id, make them unique.",
          );
        }
      }
    }
  }

  protected override updated(changed: Map<PropertyKey, unknown>): void {
    super.updated(changed);
    const pending = this.pendingFocus;
    if (!pending) return;
    this.pendingFocus = null;
    const has = (id?: string) => this.value.some((entry) => entry.id === id);
    const row = (id?: string) =>
      Array.from(
        this.renderRoot.querySelectorAll<HTMLElement>("[data-entry-id]"),
      ).find((el) => id !== undefined && el.dataset.entryId === id) ?? null;
    if (pending.kind === "add") {
      const key = has(pending.id)
        ? row(pending.id)?.querySelector<MinervaTextarea>(".key")
        : null;
      // the new field renders its <textarea> in its own (next) update
      if (key) void key.updateComplete.then(() => key.focus());
    } else if (!has(pending.id)) {
      const next = row(pending.nextId)?.querySelector<HTMLElement>(".remove");
      (
        next ?? this.renderRoot.querySelector<HTMLElement>("minerva-button")
      )?.focus();
    }
  }

  private newId(): string {
    let id: string;
    do {
      id = `${this.editorId}-${this.nextId++}`;
    } while (this.value.some((entry) => entry.id === id));
    return id;
  }

  private commit(next: KeyValueEntry[]) {
    this.dirty = true;
    this.value = next;
    this.dispatchEvent(new Event("change", { bubbles: true }));
    this.emit("minerva-change", { value: next });
  }

  private add() {
    if (this.isDisabled) return;
    const id = this.newId();
    this.pendingFocus = { kind: "add", id };
    this.commit([...this.value, { id, key: "", value: "" }]);
  }

  private removeEntry(id: string) {
    if (this.isDisabled) return;
    const index = this.value.findIndex((entry) => entry.id === id);
    const neighbour = this.value[index + 1] ?? this.value[index - 1];
    this.pendingFocus = { kind: "remove", id, nextId: neighbour?.id };
    this.commit(this.value.filter((entry) => entry.id !== id));
  }

  private handleInput(event: Event, id: string, field: "key" | "value") {
    // the inner textarea's own minerva-* events stop here
    event.stopPropagation();
    if (this.isDisabled) return;
    const text = (event.target as MinervaTextarea).value;
    this.dirty = true;
    this.value = this.value.map((entry) =>
      entry.id === id ? { ...entry, [field]: text } : entry,
    );
    this.emit("minerva-input", { value: this.value });
  }

  private handleFieldChange(event: Event) {
    event.stopPropagation();
    this.dispatchEvent(new Event("change", { bubbles: true }));
    this.emit("minerva-change", { value: this.value });
  }

  private renderField(
    entry: KeyValueEntry,
    index: number,
    field: "key" | "value",
    label: string,
  ) {
    const error = this.errors?.[entry.id]?.[field];
    return html`<minerva-form-control
      ?disabled=${this.isDisabled}
      ?invalid=${!!error}
      error-message=${error ?? ""}
    >
      <span slot="label"
        >${label}<span class="srOnly"> ${index + 1}</span></span
      >
      <minerva-textarea
        class=${field === "key" ? "key" : ""}
        size="small"
        rows=${field === "key" ? 1 : 2}
        .value=${entry[field]}
        @minerva-input=${(event: Event) =>
          this.handleInput(event, entry.id, field)}
        @minerva-change=${this.handleFieldChange}
      ></minerva-textarea>
    </minerva-form-control>`;
  }

  protected override hookStates() {
    return { disabled: this.isDisabled };
  }

  protected override render() {
    const { t } = this.locale;
    const keyText = this.keyLabel ?? t("keyValueEditor.key");
    const valueText = this.valueLabel ?? t("keyValueEditor.value");
    const removeText = this.removeLabel ?? t("keyValueEditor.remove");
    const disabled = this.isDisabled;
    const label = this.aria.label;
    return html`<div
      class="root"
      part="root"
      role=${label ? "group" : nothing}
      aria-label=${label ?? nothing}
      aria-description=${this.aria.description ?? nothing}
    >
      ${repeat(
        this.value,
        (entry) => entry.id,
        (entry, index) =>
          html`<div class="row" part="row" data-entry-id=${entry.id}>
            ${this.renderField(entry, index, "key", keyText)}
            ${this.renderField(entry, index, "value", valueText)}
            <button
              part="remove-button"
              type="button"
              class="remove iconButton neutral variant-ghost small square ${
                disabled ? "disabled" : ""
              }"
              aria-label=${`${removeText} ${index + 1}`}
              ?disabled=${disabled}
              @click=${() => this.removeEntry(entry.id)}
            >
              ${IconX}
            </button>
          </div>`,
      )}
      <minerva-button
        part="add-button"
        class="add"
        color="neutral"
        variant="outline"
        size="small"
        ?disabled=${disabled}
        @click=${this.add}
      >
        <span slot="start">${IconPlus}</span>
        <span>${this.addLabel ?? t("keyValueEditor.add")}</span>
      </minerva-button>
    </div>`;
  }
}

/** Rows from JSON: `[{ key, value, id? }]` or `{ "key": "value" }`. */
function parseEntries(text: string | null): KeyValueEntry[] {
  if (!text) return [];
  try {
    const data: unknown = JSON.parse(text);
    if (Array.isArray(data)) {
      return data
        .filter((item) => item && typeof item === "object")
        .map((item: Record<string, unknown>) => ({
          id: typeof item.id === "string" ? item.id : "",
          key: String(item.key ?? ""),
          value: String(item.value ?? ""),
        }));
    }
    if (data && typeof data === "object") {
      return Object.entries(data).map(([key, value]) => ({
        id: "",
        key,
        value: typeof value === "string" ? value : JSON.stringify(value),
      }));
    }
  } catch {
    // not JSON: no rows
  }
  return [];
}

declare global {
  interface HTMLElementTagNameMap {
    "minerva-key-value-editor": MinervaKeyValueEditor;
  }
}

// packages/vue/src/components/KeyValueEditor/KeyValueEditor.vue
<script setup lang="ts">
/**
 * KeyValueEditor: ordered list of editable string pairs (multi-line keys and
 * values), with add / remove actions. Rows are tracked by their stable `id`,
 * so duplicate keys and reordering are safe. Keyboard focus follows the
 * actions: adding a row focuses its key field; removing one focuses the next
 * row's remove button (else the previous one, else the add button).
 * `v-model` (or `defaultValue`); attributes fall through to the container.
 */
import {
  computed,
  onBeforeUpdate,
  onUpdated,
  ref,
  useAttrs,
  useId,
  watch,
  type ComponentPublicInstance,
} from "vue";
import styles from "@react-styles/components/KeyValueEditor/keyValueEditor.module.scss";
import { hooks } from "../../internal/hooks";
import { useControllable } from "../../internal/controllable";
import { IconPlus, IconX } from "../../internal/icons";
import { useI18n } from "../../config/useI18n";
import { Button } from "../Button";
import { FormField } from "../FormControl";
import { IconButton } from "../IconButton";
import { Textarea } from "../Textarea";
import type { KeyValueEditorProps, KeyValueEntry } from "./types";

defineOptions({ name: "KeyValueEditor", inheritAttrs: false });

const props = withDefaults(defineProps<KeyValueEditorProps>(), {
  modelValue: undefined,
  defaultValue: undefined,
  disabled: false,
  keyLabel: undefined,
  valueLabel: undefined,
  addLabel: undefined,
  removeLabel: undefined,
  errors: undefined,
});

const emit = defineEmits<{
  /** The next rows (v-model) */
  "update:modelValue": [entries: KeyValueEntry[]];
  /** Called with the next rows after an edit, an addition or a removal */
  change: [entries: KeyValueEntry[]];
}>();

const attrs = useAttrs();
const { t } = useI18n();
const editorId = useId();
let nextId = 0;

const entries = useControllable<KeyValueEntry[]>(props, "modelValue", {
  defaultProp: "defaultValue",
  fallback: [],
  name: "KeyValueEditor",
  onChange: (next) => emit("change", next),
});

const keyText = computed(() => props.keyLabel ?? t("keyValueEditor.key"));
const valueText = computed(() => props.valueLabel ?? t("keyValueEditor.value"));
const removeText = computed(
  () => props.removeLabel ?? t("keyValueEditor.remove"),
);

// Focus management: without it, removing a row drops focus to <body> (the
// focused remove button unmounts) and a new row has to be found by hand.
type Target = Element | ComponentPublicInstance | null;
const elementOf = (target: Target): HTMLElement | null =>
  target instanceof HTMLElement
    ? target
    : ((target as ComponentPublicInstance | null)?.$el ?? null);
const keyFields = new Map<string, HTMLElement>();
const removeButtons = new Map<string, HTMLElement>();
let addButton: HTMLElement | null = null;
const track =
  (map: Map<string, HTMLElement>, id: string) => (target: Target) => {
    const el = elementOf(target);
    if (el) map.set(id, el);
    else map.delete(id);
  };
const setAddButton = (target: Target) => {
  addButton = elementOf(target);
};

// Reordered rows are moved in the DOM, which blurs a focused field: keep
// focus on it (React keeps it as it moves the other rows).
const root = ref<HTMLElement | null>(null);
let focused: HTMLElement | null = null;
onBeforeUpdate(() => {
  const active = document.activeElement as HTMLElement | null;
  focused = active && root.value?.contains(active) ? active : null;
});
onUpdated(() => {
  const el = focused;
  focused = null;
  if (el?.isConnected && document.activeElement !== el) {
    const active = document.activeElement;
    if (!active || active === document.body) el.focus();
  }
});

let pendingFocus:
  | { kind: "add"; id: string }
  | { kind: "remove"; id: string; nextId?: string }
  | null = null;

watch(
  entries,
  (list) => {
    const pending = pendingFocus;
    if (!pending) return;
    // Settled once the entries change (a controlled parent may reject it).
    pendingFocus = null;
    const has = (id?: string) => list.some((entry) => entry.id === id);
    if (pending.kind === "add") {
      if (has(pending.id)) keyFields.get(pending.id)?.focus();
    } else if (!has(pending.id)) {
      const next = pending.nextId && removeButtons.get(pending.nextId);
      (next || addButton)?.focus();
    }
  },
  { flush: "post" },
);

function add() {
  if (props.disabled) return;
  const list = entries.value;
  let id: string;
  do {
    id = `key-value-${editorId}-${nextId++}`;
  } while (list.some((entry) => entry.id === id));
  pendingFocus = { kind: "add", id };
  entries.value = [...list, { id, key: "", value: "" }];
}

function update(id: string, field: "key" | "value", text: string) {
  if (props.disabled) return;
  entries.value = entries.value.map((entry) =>
    entry.id === id ? { ...entry, [field]: text } : entry,
  );
}

function remove(id: string) {
  if (props.disabled) return;
  const list = entries.value;
  const index = list.findIndex((entry) => entry.id === id);
  const neighbour = list[index + 1] ?? list[index - 1];
  pendingFocus = { kind: "remove", id, nextId: neighbour?.id };
  entries.value = list.filter((entry) => entry.id !== id);
}

const rootAttrs = computed(() => ({
  ...attrs,
  ...hooks("key-value-editor", "root", { disabled: props.disabled }),
}));
</script>

<template>
  <div ref="root" :class="styles.root" v-bind="rootAttrs">
    <div
      v-for="(entry, index) in entries"
      :key="entry.id"
      :class="styles.row"
      v-bind="
        hooks('key-value-editor', 'row', {
          invalid: !!(errors?.[entry.id]?.key || errors?.[entry.id]?.value),
        })
      "
    >
      <FormField
        :disabled="disabled"
        :invalid="!!errors?.[entry.id]?.key"
        :error-message="errors?.[entry.id]?.key"
      >
        <template #label>
          {{ keyText }}<span :class="styles.srOnly">{{ ` ${index + 1}` }}</span>
        </template>
        <Textarea
          :ref="track(keyFields, entry.id)"
          :class="styles.key"
          size="small"
          :rows="1"
          :model-value="entry.key"
          @update:model-value="(text: string) => update(entry.id, 'key', text)"
        />
      </FormField>
      <FormField
        :disabled="disabled"
        :invalid="!!errors?.[entry.id]?.value"
        :error-message="errors?.[entry.id]?.value"
      >
        <template #label>
          {{ valueText
          }}<span :class="styles.srOnly">{{ ` ${index + 1}` }}</span>
        </template>
        <Textarea
          size="small"
          :rows="2"
          :model-value="entry.value"
          @update:model-value="
            (text: string) => update(entry.id, 'value', text)
          "
        />
      </FormField>
      <IconButton
        :ref="track(removeButtons, entry.id)"
        :class="styles.remove"
        type="button"
        :label="`${removeText} ${index + 1}`"
        size="small"
        shape="square"
        :disabled="disabled"
        @click="remove(entry.id)"
      >
        <IconX :size="16" aria-hidden="true" />
      </IconButton>
    </div>
    <Button
      :ref="setAddButton"
      :class="styles.add"
      type="button"
      color="neutral"
      variant="outline"
      size="small"
      :disabled="disabled"
      @click="add"
    >
      <IconPlus :size="16" aria-hidden="true" />
      <span>{{ addLabel ?? t("keyValueEditor.add") }}</span>
    </Button>
  </div>
</template>
