// packages/vue/src/components/TagInput/TagInput.vue
<script setup lang="ts">
/**
 * TagInput: free-form tags with suggestions. Enter / the add button / blur
 * add the trimmed draft; typed or pasted `separators` split text into tags;
 * arrow keys pick a suggestion; Escape discards the draft; Backspace in an
 * empty draft removes the last tag. IME composition never commits. The tags
 * are the `v-model` (or `defaultValue`). FormControl-aware.
 */
import { computed, ref, useAttrs, useId, watch } from "vue";
import { DEFAULT_TAG_SEPARATORS, splitBySeparators } from "@minerva/core";
import styles from "@react-styles/components/TagInput/tagInput.module.scss";
import { hooks } from "../../internal/hooks";
import { IconPlus, IconX } from "../../internal/icons";
import { useControllable } from "../../internal/controllable";
import { unrefElement } from "../../internal/Slot";
import { useFormControlContext } from "../../internal/form-control";
import { useI18n } from "../../config/useI18n";
import { IconButton } from "../IconButton";
import { Input } from "../Input";
import { Tag } from "../Tag";
import type { TagInputProps } from "./types";

defineOptions({ name: "TagInput", inheritAttrs: false });

const ENTER = "Enter";
const LINE_BREAKS = ["\r\n", "\n", "\r"];

interface Suggestion {
  /** The tag added when selected */
  tag: string;
  label: string;
  /** Text matched against the draft */
  filterValue: string;
}

const props = withDefaults(defineProps<TagInputProps>(), {
  modelValue: undefined,
  defaultValue: undefined,
  options: () => [],
  commitOnBlur: true,
  separators: () => DEFAULT_TAG_SEPARATORS,
  id: undefined,
  name: undefined,
  placeholder: undefined,
  ariaLabel: undefined,
  ariaLabelledby: undefined,
  ariaDescribedby: undefined,
  disabled: false,
  readOnly: false,
  invalid: false,
  size: "medium",
  emptyText: undefined,
  addLabel: undefined,
  clearLabel: undefined,
  removeLabel: undefined,
  createLabel: undefined,
});
const emit = defineEmits<{
  "update:modelValue": [value: string[]];
  /** The next tags after an addition, a removal or clearing */
  change: [value: string[]];
}>();

const attrs = useAttrs();
const { t } = useI18n();
const field = useFormControlContext();
const disabled = computed(() => props.disabled || !!field?.disabled.value);
const readOnly = computed(() => props.readOnly || !!field?.readOnly.value);
const blocked = computed(() => disabled.value || readOnly.value);
const inputComponent = ref<unknown>(null);
const inputEl = (): HTMLInputElement | null =>
  unrefElement(inputComponent.value)?.querySelector("input") ?? null;
let composing = false;
// An explicit arrow-key choice wins over "Enter adds the draft".
let navigating = false;
const listId = useId();

const tags = useControllable<readonly string[]>(props, "modelValue", {
  defaultProp: "defaultValue",
  fallback: [],
  name: "TagInput",
  onChange: (value) => emit("change", value as string[]),
});
const setTags = (next: string[]) => {
  tags.value = next;
};
const draft = ref("");
const requestedOpen = ref(false);
const highlight = ref(0);
const open = computed(() => requestedOpen.value && !blocked.value);
const trimmed = computed(() => draft.value.trim());

const filtered = computed<Suggestion[]>(() => {
  const current = tags.value;
  const candidates = [
    ...new Set(props.options.map((option) => option.trim()).filter(Boolean)),
  ].filter((option) => !current.includes(option));
  const suggestions: Suggestion[] = candidates.map((tag) => ({
    tag,
    label: tag,
    filterValue: tag,
  }));
  const typed = trimmed.value;
  if (typed && !current.includes(typed) && !candidates.includes(typed)) {
    suggestions.unshift({
      tag: typed,
      label: props.createLabel
        ? props.createLabel(typed)
        : t("tagInput.create", { tag: typed }),
      filterValue: typed,
    });
  }
  const query = typed.toLowerCase();
  return query
    ? suggestions.filter((s) => s.filterValue.toLowerCase().includes(query))
    : suggestions;
});

// Reset the highlight when the list changes.
watch(
  () => `${filtered.value.length}\u0000${draft.value}`,
  () => {
    highlight.value = 0;
  },
  { flush: "sync" },
);

const enterCommits = computed(() => props.separators.includes(ENTER));
// Literal separators: typing one commits the text before it.
const splitters = computed(() =>
  props.separators.filter((sep) => sep !== ENTER && sep !== ""),
);
// Pasted text also splits on line breaks when Enter commits.
const pasteSplitters = computed(() =>
  enterCommits.value ? [...splitters.value, ...LINE_BREAKS] : splitters.value,
);

/** Adds every (trimmed, non-empty, new) text as a tag in one update. */
function commitAll(texts: readonly string[], nextDraft = "") {
  if (blocked.value || composing) return;
  const next = [...tags.value];
  for (const text of texts) {
    const tag = text.trim();
    if (tag && !next.includes(tag)) next.push(tag);
  }
  if (next.length !== tags.value.length) setTags(next);
  navigating = false;
  draft.value = nextDraft;
}

const commit = (text: string) => commitAll([text]);

function select(suggestion: Suggestion) {
  commit(suggestion.tag);
  requestedOpen.value = false;
}

function onDraftInput(value: string | number) {
  if (blocked.value) return;
  navigating = false;
  const text = String(value);
  const parts =
    composing || splitters.value.length === 0
      ? [text]
      : splitBySeparators(text, splitters.value);
  if (parts.length > 1) {
    // Typed a separator: commit what precedes it, keep the rest.
    commitAll(parts.slice(0, -1), parts[parts.length - 1]);
  } else {
    draft.value = text;
  }
  requestedOpen.value = true;
}

function onPaste(event: ClipboardEvent) {
  if (blocked.value || composing) return;
  const pasted = event.clipboardData?.getData("text") ?? "";
  if (!pasteSplitters.value.some((sep) => pasted.includes(sep))) return;
  event.preventDefault();
  const el = event.currentTarget as HTMLInputElement;
  const start = el.selectionStart ?? draft.value.length;
  const end = el.selectionEnd ?? draft.value.length;
  const text = draft.value.slice(0, start) + pasted + draft.value.slice(end);
  commitAll(splitBySeparators(text, pasteSplitters.value));
  requestedOpen.value = false;
}

function onKeyDown(event: KeyboardEvent) {
  if (
    blocked.value ||
    composing ||
    event.isComposing ||
    event.keyCode === 229
  ) {
    return;
  }
  const list = filtered.value;
  const count = list.length;
  switch (event.key) {
    case "ArrowDown":
    case "ArrowUp":
      event.preventDefault();
      navigating = true;
      requestedOpen.value = true;
      if (count > 0) {
        const delta = event.key === "ArrowDown" ? 1 : -1;
        highlight.value = (highlight.value + delta + count) % count;
      }
      break;
    case "Enter":
      // Never submit the enclosing form from the tag field.
      event.preventDefault();
      if (!enterCommits.value) {
        // Enter only picks an explicitly highlighted suggestion.
        if (navigating && open.value && list[highlight.value]) {
          select(list[highlight.value]);
        }
      } else if (
        !navigating &&
        (!trimmed.value || tags.value.includes(trimmed.value))
      ) {
        commit(draft.value);
      } else if (open.value && list[highlight.value]) {
        select(list[highlight.value]);
      } else {
        commit(draft.value);
        requestedOpen.value = false;
      }
      break;
    case "Escape":
      navigating = false;
      draft.value = "";
      if (open.value) {
        event.preventDefault();
        requestedOpen.value = false;
      }
      break;
    case "Backspace":
      // Keyboard removal of the last tag (common tag-field convention):
      // only from an empty draft, so normal text editing is unaffected.
      if (draft.value === "" && tags.value.length > 0) {
        event.preventDefault();
        setTags(tags.value.slice(0, -1));
      }
      break;
  }
}

function setComposing(value: boolean) {
  composing = value;
}

function onFocusOrClick() {
  if (!blocked.value) requestedOpen.value = true;
}

function onBlur() {
  requestedOpen.value = false;
  if (props.commitOnBlur) commit(draft.value);
}

function removeAt(index: number) {
  if (blocked.value) return;
  setTags(tags.value.filter((_, position) => position !== index));
  inputEl()?.focus();
}

function onAdd() {
  commit(draft.value);
  inputEl()?.focus();
}

function onClear() {
  draft.value = "";
  setTags([]);
  inputEl()?.focus();
}

const removeText = (tag: string) =>
  props.removeLabel ? props.removeLabel(tag) : t("tagInput.remove", { tag });
const optionId = (index: number) => `${listId}-option-${index}`;
const activeOption = computed(() =>
  open.value ? filtered.value[highlight.value] : undefined,
);

const rootAttrs = computed(() => ({
  ...attrs,
  class: [styles.root, attrs.class],
  ...hooks("tag-input", "root", {
    state: open.value ? "open" : "closed",
    disabled: disabled.value,
    invalid: props.invalid || !!field?.invalid.value,
    readonly: readOnly.value,
    required: !!field?.required.value,
    size: props.size,
  }),
}));

defineExpose({
  /** The text `<input>` (the React `ref`) */
  input: computed(inputEl),
  focus: () => inputEl()?.focus(),
});
</script>

<template>
  <div v-bind="rootAttrs">
    <div
      v-if="tags.length > 0"
      :class="styles.values"
      v-bind="hooks('tag-input', 'tags')"
    >
      <Tag
        v-for="(tag, index) in tags"
        :key="`${index}-${tag}`"
        :class="styles.tag"
        size="large"
        :disabled="disabled"
        :closable="!readOnly"
        :close-label="removeText(tag)"
        @close="removeAt(index)"
      >
        <span :class="styles.label">{{ tag }}</span>
      </Tag>
    </div>
    <div :class="styles.entry">
      <div :class="styles.combobox">
        <Input
          ref="inputComponent"
          :id="id"
          :size="size"
          :invalid="invalid"
          type="text"
          role="combobox"
          :aria-label="ariaLabel"
          :aria-labelledby="ariaLabelledby"
          :aria-describedby="ariaDescribedby"
          :aria-expanded="String(open)"
          :aria-controls="open ? listId : undefined"
          aria-autocomplete="list"
          :aria-activedescendant="
            activeOption ? optionId(highlight) : undefined
          "
          autocomplete="off"
          spellcheck="false"
          :placeholder="placeholder"
          :model-value="draft"
          :disabled="disabled"
          :read-only="readOnly"
          @update:model-value="onDraftInput"
          @focus="onFocusOrClick"
          @click="onFocusOrClick"
          @blur="onBlur"
          @compositionstart="setComposing(true)"
          @compositionend="setComposing(false)"
          @keydown="onKeyDown"
          @paste="onPaste"
        />
        <ul
          v-if="open"
          :id="listId"
          role="listbox"
          :aria-label="ariaLabel"
          :aria-labelledby="ariaLabelledby"
          :class="styles.list"
          v-bind="hooks('tag-input', 'list')"
        >
          <li
            v-if="filtered.length === 0"
            :class="styles.empty"
            role="presentation"
            v-bind="hooks('tag-input', 'empty')"
          >
            {{ emptyText ?? t("tagInput.empty") }}
          </li>
          <li
            v-for="(suggestion, index) in filtered"
            :id="optionId(index)"
            :key="`${suggestion.label}-${suggestion.tag}`"
            role="option"
            :aria-selected="index === highlight"
            tabindex="-1"
            :class="styles.option"
            v-bind="
              hooks('tag-input', 'option', {
                highlighted: index === highlight,
              })
            "
            @mousedown.prevent="select(suggestion)"
            @mouseenter="highlight = index"
          >
            {{ suggestion.label }}
          </li>
        </ul>
      </div>
      <template v-if="!readOnly">
        <IconButton
          :label="addLabel ?? t('tagInput.add')"
          shape="square"
          :disabled="disabled || !trimmed || tags.includes(trimmed)"
          @mousedown.prevent
          @click="onAdd"
        >
          <IconPlus aria-hidden="true" />
        </IconButton>
        <IconButton
          :label="clearLabel ?? t('tagInput.clear')"
          shape="square"
          :disabled="disabled || tags.length === 0"
          @mousedown.prevent
          @click="onClear"
        >
          <IconX aria-hidden="true" />
        </IconButton>
      </template>
    </div>
    <template v-if="name">
      <input
        v-for="(tag, index) in tags"
        :key="`${index}-${tag}`"
        type="hidden"
        :name="name"
        :value="tag"
        :disabled="disabled"
      />
    </template>
  </div>
</template>

// packages/angular/src/components/tag-input/tag-input.ts
import {
  ChangeDetectionStrategy,
  Component,
  ElementRef,
  ViewEncapsulation,
  booleanAttribute,
  computed,
  input,
  linkedSignal,
  model,
  output,
  signal,
  viewChild,
} from "@angular/core";
import { DEFAULT_TAG_SEPARATORS, cn, splitBySeparators } from "@minerva/core";
import { injectScope } from "../../config/scope";
import { classOf } from "../../internal/classes";
import {
  MnFormValueControl,
  fieldWiring,
  injectFormField,
  provideValueAccessor,
} from "../../internal/forms";
import { MnHook } from "../../internal/hooks";
import { MnIcon } from "../../internal/icon";
import { injectId } from "../../internal/ids";
import {
  iconButtonStyles as ib,
  inputStyles as inp,
  tagInputStyles as s,
  tagStyles as tg,
  tooltipStyles as tt,
} from "../../internal/styles";

export type TagInputSize = "small" | "medium" | "large";

const EMPTY: readonly string[] = [];
const ENTER = "Enter";
const LINE_BREAKS = ["\r\n", "\n", "\r"];

interface Suggestion {
  /** The tag added when selected */
  tag: string;
  label: string;
  /** Text matched against the draft */
  filterValue: string;
}

/**
 * TagInput: free-form tags with suggestions. Enter / the add button / blur
 * add the trimmed draft; typed or pasted `separators` split text into tags;
 * arrow keys pick a suggestion; Escape discards the draft; Backspace in an
 * empty draft removes the last tag. IME composition never commits. Same DOM,
 * classes and styling hooks as React's TagInput (the host element is the
 * wrapper; the tags, the text field and the add / clear buttons render the
 * DOM of React's Tag, Input and IconButton).
 *
 * Two-way binding: `[(value)]`, `ngModel` or a Reactive Forms control
 * (ControlValueAccessor). Inside `<mn-form-control>` it takes the field's id,
 * description, invalid / required / read-only / disabled states.
 *
 * @example
 * <mn-tag-input aria-label="Tags" [options]="['Vue', 'React']" [(value)]="tags" />
 * <mn-tag-input formControlName="tags" name="tags" />
 */
@Component({
  selector: "mn-tag-input",
  exportAs: "mnTagInput",
  imports: [MnHook, MnIcon],
  encapsulation: ViewEncapsulation.None,
  changeDetection: ChangeDetectionStrategy.OnPush,
  providers: [provideValueAccessor(() => MnTagInput)],
  host: {
    "[class]": "s.root",
    "data-minerva": "tag-input",
    "data-part": "root",
    "[attr.data-state]": "open() ? 'open' : 'closed'",
    "[attr.data-disabled]": "isDisabled() ? '' : null",
    "[attr.data-invalid]": "rootInvalid() ? '' : null",
    "[attr.data-readonly]": "isReadOnly() ? '' : null",
    "[attr.data-required]": "field.required() ? '' : null",
    "[attr.data-size]": "size()",
    // inputs moved to the inner <input>: not attributes of the wrapper
    "[attr.id]": "null",
    "[attr.name]": "null",
    "[attr.placeholder]": "null",
    "[attr.aria-label]": "null",
    "[attr.aria-labelledby]": "null",
    "[attr.aria-describedby]": "null",
    "[attr.disabled]": "null",
    "[attr.readonly]": "null",
    "[attr.invalid]": "null",
    "[attr.required]": "null",
    "[attr.size]": "null",
  },
  template: `
    @if (tags().length > 0) {
      <div [class]="s.values" mnHook="tag-input" mnPart="tags">
        @for (tag of tags(); track $index + ":" + tag; let index = $index) {
          <div
            [class]="tagClasses()"
            data-component="tag"
            mnHook="tag"
            [mnStates]="tagStates()"
          >
            <span [class]="tg.content" mnHook="tag" mnPart="label">
              <span [class]="s.label">{{ tag }}</span>
            </span>
            @if (!isReadOnly()) {
              <button
                type="button"
                [class]="tg.closeIcon"
                [disabled]="isDisabled()"
                [attr.aria-label]="removeText(tag)"
                [attr.title]="removeText(tag)"
                (click)="onRemove($event, index)"
                mnHook="tag"
                mnPart="close-button"
              >
                <svg mnIcon="X"></svg>
              </button>
            }
          </div>
        }
      </div>
    }
    <div [class]="s.entry">
      <div [class]="s.combobox">
        <div
          [class]="inputClasses()"
          data-component="input"
          mnHook="input"
          [mnStates]="inputStates()"
        >
          <input
            #input
            [class]="inp.field"
            type="text"
            role="combobox"
            [attr.id]="field.id()"
            [attr.aria-label]="ariaLabel() ?? null"
            [attr.aria-labelledby]="ariaLabelledby() ?? null"
            [attr.aria-describedby]="field.describedBy()"
            [attr.aria-invalid]="field.invalid() ? 'true' : null"
            [attr.aria-required]="fieldContext?.required() ? 'true' : null"
            [attr.aria-readonly]="fieldContext?.readOnly() ? 'true' : null"
            [attr.aria-expanded]="open()"
            [attr.aria-controls]="open() ? listId : null"
            aria-autocomplete="list"
            [attr.aria-activedescendant]="activeDescendant()"
            autocomplete="off"
            spellcheck="false"
            [attr.placeholder]="placeholder() ?? null"
            [value]="draft()"
            [disabled]="isDisabled()"
            [readOnly]="isReadOnly()"
            (input)="onInput(input)"
            (focus)="onFocus()"
            (click)="onFocus()"
            (blur)="onBlur()"
            (compositionstart)="composing = true"
            (compositionend)="composing = false"
            (keydown)="onKeyDown($event)"
            (paste)="onPaste($event, input)"
            mnHook="input"
            mnPart="input"
          />
        </div>
        @if (open()) {
          <ul
            [attr.id]="listId"
            role="listbox"
            [attr.aria-label]="ariaLabel() ?? null"
            [attr.aria-labelledby]="ariaLabelledby() ?? null"
            [class]="s.list"
            mnHook="tag-input"
            mnPart="list"
          >
            @if (filtered().length === 0) {
              <li
                [class]="s.empty"
                role="presentation"
                mnHook="tag-input"
                mnPart="empty"
              >
                {{ emptyText() ?? scope.t("tagInput.empty") }}
              </li>
            }
            @for (
              suggestion of filtered();
              track suggestion.label + "-" + suggestion.tag;
              let index = $index
            ) {
              <li
                [attr.id]="optionId(index)"
                role="option"
                [attr.aria-selected]="index === highlight()"
                tabindex="-1"
                [class]="s.option"
                (mousedown)="onOptionMouseDown($event, suggestion)"
                (mouseenter)="highlight.set(index)"
                mnHook="tag-input"
                mnPart="option"
                [mnStates]="{ highlighted: index === highlight() }"
              >
                {{ suggestion.label }}
              </li>
            }
          </ul>
        }
      </div>
      @if (!isReadOnly()) {
        <div
          [class]="tt.tooltipTrigger"
          mnHook="tooltip"
          mnPart="trigger"
          [mnStates]="{ state: 'closed', disabled: addDisabled() }"
        >
          <button
            type="button"
            [class]="buttonClasses(addDisabled())"
            [disabled]="addDisabled()"
            [attr.tabindex]="addDisabled() ? -1 : 0"
            [attr.aria-label]="addLabel() ?? scope.t('tagInput.add')"
            (mousedown)="$event.preventDefault()"
            (click)="onAdd()"
            mnHook="icon-button"
            [mnStates]="buttonStates(addDisabled())"
          >
            <span
              [class]="ib.glyph"
              aria-hidden="true"
              mnHook="icon-button"
              mnPart="icon"
            >
              <svg mnIcon="Plus"></svg>
            </span>
          </button>
        </div>
        <div
          [class]="tt.tooltipTrigger"
          mnHook="tooltip"
          mnPart="trigger"
          [mnStates]="{ state: 'closed', disabled: clearDisabled() }"
        >
          <button
            type="button"
            [class]="buttonClasses(clearDisabled())"
            [disabled]="clearDisabled()"
            [attr.tabindex]="clearDisabled() ? -1 : 0"
            [attr.aria-label]="clearLabel() ?? scope.t('tagInput.clear')"
            (mousedown)="$event.preventDefault()"
            (click)="onClear()"
            mnHook="icon-button"
            [mnStates]="buttonStates(clearDisabled())"
          >
            <span
              [class]="ib.glyph"
              aria-hidden="true"
              mnHook="icon-button"
              mnPart="icon"
            >
              <svg mnIcon="X"></svg>
            </span>
          </button>
        </div>
      }
    </div>
    @if (name()) {
      @for (tag of tags(); track $index + ":" + tag) {
        <input
          type="hidden"
          [attr.name]="name()"
          [value]="tag"
          [disabled]="isDisabled()"
        />
      }
    }
  `,
})
export class MnTagInput extends MnFormValueControl<string[]> {
  /** Selected tags (two-way: `[(value)]`); `defaultValue` when not bound */
  readonly value = model<string[] | undefined>(undefined);
  /**
   * Initial tags when `value` is not bound
   * @default []
   */
  readonly defaultValue = input<readonly string[]>(EMPTY);
  /**
   * Suggestions; already selected tags are hidden and duplicates merged
   * @default []
   */
  readonly options = input<readonly string[]>(EMPTY);
  /**
   * Adds the typed draft as a tag when the input loses focus
   * @default true
   */
  readonly commitOnBlur = input(true, { transform: booleanAttribute });
  /**
   * Keys that commit the draft: a literal string (e.g. "," or ";") splits the
   * typed or pasted text into tags; "Enter" commits on the Enter key (and also
   * splits pasted text on line breaks)
   * @default [",", "Enter"]
   */
  readonly separators = input<readonly string[]>(DEFAULT_TAG_SEPARATORS);
  /** Id of the text input (defaults to the form control's id) */
  readonly id = input<string | undefined>(undefined);
  /** Submits every selected tag under this name (hidden inputs); the draft is not submitted */
  readonly name = input<string | undefined>(undefined);
  /** Placeholder of the text input */
  readonly placeholder = input<string | undefined>(undefined);
  /** Accessible name of the text input when there is no form control label */
  readonly ariaLabel = input<string | undefined>(undefined, {
    alias: "aria-label",
  });
  /** Ids of the elements labelling the text input */
  readonly ariaLabelledby = input<string | undefined>(undefined, {
    alias: "aria-labelledby",
  });
  /** Extra ids describing the text input */
  readonly ariaDescribedby = input<string | undefined>(undefined, {
    alias: "aria-describedby",
  });
  /**
   * Disables the field (also set by the form / `<mn-form-control>`)
   * @default false
   */
  readonly disabled = input(false, { transform: booleanAttribute });
  /**
   * Shows the tags without editing controls (also set by `<mn-form-control>`)
   * @default false
   */
  readonly readOnly = input(false, { transform: booleanAttribute });
  /**
   * Error state (also set by an invalid form control / `<mn-form-control>`)
   * @default false
   */
  readonly invalid = input(false, { transform: booleanAttribute });
  /**
   * Marks the field as required (aria-required, `data-required`; also set
   * by `<mn-form-control>`)
   * @default false
   */
  readonly required = input(false, { transform: booleanAttribute });
  /**
   * Size of the text input
   * @default "medium"
   */
  readonly size = input<TagInputSize>("medium");
  /**
   * Text of the suggestion list when nothing matches
   * @default "No matches" (localized)
   */
  readonly emptyText = input<string | undefined>(undefined);
  /**
   * Accessible label of the add button
   * @default "Add tag" (localized)
   */
  readonly addLabel = input<string | undefined>(undefined);
  /**
   * Accessible label of the clear button
   * @default "Clear tags" (localized)
   */
  readonly clearLabel = input<string | undefined>(undefined);
  /**
   * Accessible label of a tag's remove button
   * @default tag => `Remove ${tag}` (localized)
   */
  readonly removeLabel = input<((tag: string) => string) | undefined>(
    undefined,
  );
  /**
   * Text of the "create this tag" suggestion
   * @default tag => `Add "${tag}"` (localized)
   */
  readonly createLabel = input<((tag: string) => string) | undefined>(
    undefined,
  );

  /** The typed text (draft) changed (web components' `minerva-input`) */
  readonly draftChange = output<string>();
  /** The suggestion list opened / closed (web components' `minerva-open-change`) */
  readonly openChange = output<boolean>();
  /** The clear button removed every tag (web components' `minerva-clear`) */
  readonly clear = output<void>();

  protected readonly s = s;
  protected readonly tg = tg;
  protected readonly inp = inp;
  protected readonly ib = ib;
  protected readonly tt = tt;
  protected readonly scope = injectScope();
  protected readonly listId = injectId("tag-input-list");
  protected readonly fieldContext = injectFormField();
  protected readonly field = fieldWiring(this.fieldContext, {
    id: () => this.id(),
    describedBy: () => this.ariaDescribedby(),
    invalid: () => this.invalid() || this.controlInvalid(),
    required: () => this.required(),
    readOnly: () => this.readOnly(),
    disabled: () => this.disabled() || this.formDisabled(),
  });
  protected readonly isDisabled = this.field.disabled;
  protected readonly isReadOnly = this.field.readOnly;
  protected readonly rootInvalid = this.field.invalid;
  protected readonly blocked = computed(
    () => this.isDisabled() || this.isReadOnly(),
  );

  private readonly inputRef = viewChild<ElementRef<HTMLInputElement>>("input");
  /** IME composition in progress */
  protected composing = false;
  /** An explicit arrow-key choice wins over "Enter adds the draft" */
  private navigating = false;

  /** The tags shown (the bound value, else the default) */
  protected readonly tags = computed<readonly string[]>(
    () => this.value() ?? this.defaultValue(),
  );
  protected readonly draft = signal("");
  private readonly requestedOpen = signal(false);
  protected readonly open = computed(
    () => this.requestedOpen() && !this.blocked(),
  );
  private readonly trimmed = computed(() => this.draft().trim());

  protected readonly filtered = computed<Suggestion[]>(() => {
    const tags = this.tags();
    const trimmed = this.trimmed();
    const candidates = [
      ...new Set(
        this.options()
          .map((option) => option.trim())
          .filter(Boolean),
      ),
    ].filter((option) => !tags.includes(option));
    const suggestions: Suggestion[] = candidates.map((tag) => ({
      tag,
      label: tag,
      filterValue: tag,
    }));
    if (trimmed && !tags.includes(trimmed) && !candidates.includes(trimmed)) {
      const create = this.createLabel();
      suggestions.unshift({
        tag: trimmed,
        label: create
          ? create(trimmed)
          : this.scope.t("tagInput.create", { tag: trimmed }),
        filterValue: trimmed,
      });
    }
    const query = trimmed.toLowerCase();
    return query
      ? suggestions.filter((s) => s.filterValue.toLowerCase().includes(query))
      : suggestions;
  });

  /** Highlighted suggestion; back to the first one when the list changes */
  protected readonly highlight = linkedSignal({
    source: () => `${this.filtered().length}\u0000${this.draft()}`,
    computation: () => 0,
  });

  private readonly enterCommits = computed(() =>
    this.separators().includes(ENTER),
  );
  /** Literal separators: typing one commits the text before it */
  private readonly splitters = computed(() =>
    this.separators().filter((sep) => sep !== ENTER && sep !== ""),
  );
  /** Pasted text also splits on line breaks when Enter commits */
  private readonly pasteSplitters = computed(() =>
    this.enterCommits()
      ? [...this.splitters(), ...LINE_BREAKS]
      : this.splitters(),
  );

  protected readonly activeDescendant = computed(() =>
    this.open() && this.filtered()[this.highlight()]
      ? this.optionId(this.highlight())
      : null,
  );
  protected readonly addDisabled = computed(
    () =>
      this.isDisabled() ||
      !this.trimmed() ||
      this.tags().includes(this.trimmed()),
  );
  protected readonly clearDisabled = computed(
    () => this.isDisabled() || this.tags().length === 0,
  );

  protected readonly tagClasses = computed(() =>
    cn(
      tg.tag,
      tg.neutral,
      classOf(tg, "subtle"),
      tg.large,
      tg.rounded,
      this.isDisabled() && tg.disabled,
      s.tag,
    ),
  );
  protected readonly tagStates = computed(() => ({
    state: "inactive",
    disabled: this.isDisabled(),
    size: "large",
    variant: "subtle",
    color: "neutral",
    shape: "rounded",
  }));
  protected readonly inputClasses = computed(() =>
    cn(
      inp.root,
      inp.outline,
      classOf(inp, this.size()),
      this.field.invalid() && inp.invalid,
      this.isDisabled() && inp.disabled,
    ),
  );
  protected readonly inputStates = computed(() => ({
    disabled: this.isDisabled(),
    invalid: this.field.invalid(),
    readonly: this.isReadOnly(),
    required: this.field.required(),
    size: this.size(),
    variant: "outline",
  }));

  override writeValue(value: string[] | null | undefined): void {
    this.value.set(value ? [...value] : []);
  }

  protected optionId(index: number): string {
    return `${this.listId}-option-${index}`;
  }

  protected removeText(tag: string): string {
    const label = this.removeLabel();
    return label ? label(tag) : this.scope.t("tagInput.remove", { tag });
  }

  protected buttonClasses(disabled: boolean): string {
    return cn(
      ib.iconButton,
      ib.neutral,
      ib["variant-ghost"],
      ib.medium,
      ib.square,
      disabled && ib.disabled,
    );
  }

  protected buttonStates(disabled: boolean) {
    return {
      state: "inactive",
      disabled,
      size: "medium",
      variant: "ghost",
      color: "neutral",
      shape: "square",
    };
  }

  private setOpen(next: boolean): void {
    if (this.requestedOpen() === next) return;
    this.requestedOpen.set(next);
    this.openChange.emit(next);
  }

  private setTags(next: string[]): void {
    this.value.set(next);
    this.notifyChange(next);
  }

  private setDraft(next: string): void {
    // the input may show text the state already had (e.g. a lone separator)
    const el = this.inputRef()?.nativeElement;
    if (el && el.value !== next) el.value = next;
    if (this.draft() === next) return;
    this.draft.set(next);
    this.draftChange.emit(next);
  }

  /** Adds every (trimmed, non-empty, new) text as a tag in one update */
  private commitAll(texts: readonly string[], nextDraft = ""): void {
    if (this.blocked() || this.composing) return;
    const tags = this.tags();
    const next = [...tags];
    for (const text of texts) {
      const tag = text.trim();
      if (tag && !next.includes(tag)) next.push(tag);
    }
    if (next.length !== tags.length) this.setTags(next);
    this.navigating = false;
    this.setDraft(nextDraft);
  }

  private commit(text: string): void {
    this.commitAll([text]);
  }

  private select(suggestion: Suggestion): void {
    this.commit(suggestion.tag);
    this.setOpen(false);
  }

  private focusInput(): void {
    this.inputRef()?.nativeElement.focus();
  }

  protected onInput(el: HTMLInputElement): void {
    if (this.blocked()) {
      el.value = this.draft();
      return;
    }
    this.navigating = false;
    const text = el.value;
    const splitters = this.splitters();
    const parts =
      this.composing || splitters.length === 0
        ? [text]
        : splitBySeparators(text, splitters);
    if (parts.length > 1) {
      // Typed a separator: commit what precedes it, keep the rest.
      this.commitAll(parts.slice(0, -1), parts[parts.length - 1]);
    } else {
      this.setDraft(text);
    }
    this.setOpen(true);
  }

  protected onFocus(): void {
    if (!this.blocked()) this.setOpen(true);
  }

  protected onBlur(): void {
    this.setOpen(false);
    if (this.commitOnBlur()) this.commit(this.draft());
    this.notifyTouched();
  }

  protected onPaste(event: ClipboardEvent, el: HTMLInputElement): void {
    if (this.blocked() || this.composing) return;
    const pasted = event.clipboardData?.getData("text") ?? "";
    const splitters = this.pasteSplitters();
    if (!splitters.some((sep) => pasted.includes(sep))) return;
    event.preventDefault();
    const draft = this.draft();
    const start = el.selectionStart ?? draft.length;
    const end = el.selectionEnd ?? draft.length;
    const text = draft.slice(0, start) + pasted + draft.slice(end);
    this.commitAll(splitBySeparators(text, splitters));
    this.setOpen(false);
  }

  protected onKeyDown(event: KeyboardEvent): void {
    if (
      this.blocked() ||
      this.composing ||
      event.isComposing ||
      event.keyCode === 229
    ) {
      return;
    }
    const filtered = this.filtered();
    const count = filtered.length;
    const draft = this.draft();
    const trimmed = this.trimmed();
    const tags = this.tags();
    switch (event.key) {
      case "ArrowDown":
      case "ArrowUp":
        event.preventDefault();
        this.navigating = true;
        this.setOpen(true);
        if (count > 0) {
          const delta = event.key === "ArrowDown" ? 1 : -1;
          this.highlight.update((h) => (h + delta + count) % count);
        }
        break;
      case "Enter": {
        // Never submit the enclosing form from the tag field.
        event.preventDefault();
        const highlighted = filtered[this.highlight()];
        if (!this.enterCommits()) {
          // Enter only picks an explicitly highlighted suggestion.
          if (this.navigating && this.open() && highlighted) {
            this.select(highlighted);
          }
        } else if (!this.navigating && (!trimmed || tags.includes(trimmed))) {
          this.commit(draft);
        } else if (this.open() && highlighted) {
          this.select(highlighted);
        } else {
          this.commit(draft);
          this.setOpen(false);
        }
        break;
      }
      case "Escape":
        this.navigating = false;
        this.setDraft("");
        if (this.open()) {
          event.preventDefault();
          this.setOpen(false);
        }
        break;
      case "Backspace":
        // Keyboard removal of the last tag, only from an empty draft.
        if (draft === "" && tags.length > 0) {
          event.preventDefault();
          this.setTags(tags.slice(0, -1));
        }
        break;
    }
  }

  protected onOptionMouseDown(event: MouseEvent, suggestion: Suggestion): void {
    // mousedown runs before the input blurs: keep focus in the input.
    event.preventDefault();
    this.select(suggestion);
  }

  protected onRemove(event: MouseEvent, index: number): void {
    event.stopPropagation();
    if (this.blocked()) return;
    this.setTags(this.tags().filter((_, position) => position !== index));
    this.focusInput();
  }

  protected onAdd(): void {
    this.commit(this.draft());
    this.focusInput();
  }

  protected onClear(): void {
    this.setDraft("");
    this.setTags([]);
    this.clear.emit();
    this.focusInput();
  }

  /** Focuses the text input */
  focus(options?: FocusOptions): void {
    this.inputRef()?.nativeElement.focus(options);
  }
}
