// packages/lib-web-components/src/components/avatar/avatar.ts
import { css, html, nothing, type PropertyValues } from "lit";
import { property, state } from "lit/decorators.js";
import { classMap } from "lit/directives/class-map.js";
import { styleMap } from "lit/directives/style-map.js";
import styles from "@lib-core-styles/components/Avatar/avatar.module.scss?inline";
import groupStyles from "@lib-core-styles/components/Avatar/avatarGroup.module.scss?inline";
import { AriaController } from "../../internal/aria";
import { DEV, devWarn } from "../../internal/dev";
import { LocaleController } from "../../internal/locale";
import { MinervaElement, hostStyles } from "../../internal/minerva-element";
import { HasSlotController } from "../../internal/slots";
import { sharedStyles } from "../../internal/styles";

/** Preset size of an avatar (24 / 32 / 48 / 64 / 80 / 96 px) */
export type AvatarSizePreset =
  "xsmall" | "small" | "medium" | "large" | "xlarge" | "xxlarge";
/** Preset size of an avatar, or a size in pixels */
export type AvatarSize = AvatarSizePreset | number;
export type AvatarShape = "circle" | "square" | "rounded";

const SIZE_PRESETS: readonly string[] = [
  "xsmall",
  "small",
  "medium",
  "large",
  "xlarge",
  "xxlarge",
];

const CJK = /[㐀-鿿豈-﫿]/;

/**
 * Initials of a name: the first CJK character, otherwise the uppercased
 * first letters of the first two words ("Ada Lovelace" -> "AL").
 */
function getAvatarInitials(name?: string): string {
  const trimmed = name?.trim() ?? "";
  if (!trimmed) return "";
  if (CJK.test(trimmed[0])) return trimmed[0];
  return trimmed
    .split(/\s+/)
    .slice(0, 2)
    .map((word) => word[0].toUpperCase())
    .join("");
}

/** Numeric sizes may come from the attribute as strings ("40"). */
const sizeConverter = {
  fromAttribute: (value: string | null): AvatarSize =>
    value && /^\d+(\.\d+)?$/.test(value)
      ? Number(value)
      : ((value ?? "medium") as AvatarSize),
  toAttribute: (value: AvatarSize) => String(value),
};

/**
 * A picture of a person, falling back to their initials (or custom fallback
 * content) when there is no image or it fails to load (`<Avatar>` of
 * lib-core). The fallback is exposed as a single image (`role="img"`) named
 * after the person, so screen readers announce "Ada Lovelace" rather than
 * the letters "AL".
 *
 * @summary Picture of a person with an initials / icon fallback.
 * @tag minerva-avatar
 * @slot - Fallback content used when there is no name (e.g. an icon)
 * @slot fallback - Custom fallback content shown instead of the initials
 * @csspart base - The avatar root
 * @csspart image - The `<img>`
 * @csspart text - The initials / fallback wrapper
 */
export class MinervaAvatar extends MinervaElement {
  static override tagName = "minerva-avatar";
  static override styles = [
    hostStyles,
    css`
      :host {
        display: inline-block;
        flex-shrink: 0;
        vertical-align: middle;
        line-height: 0;
      }
      .avatarText {
        line-height: 1;
      }
    `,
    sharedStyles(styles),
  ];

  /** Image URL; the initials of `name` are shown without it or when it fails to load */
  @property()
  src?: string;

  /** Name of the person: initials, alt text and accessible label */
  @property()
  name = "";

  /** Alternative text of the image ("" for a decorative avatar); defaults to the label */
  @property()
  alt?: string;

  /** Avatar shape */
  @property({ reflect: true })
  shape: AvatarShape = "circle";

  /** Size preset, or a number of pixels */
  @property({ reflect: true, converter: sizeConverter })
  size: AvatarSize = "medium";

  /** Uses tighter margins for overlapping avatars */
  @property({ type: Boolean, reflect: true })
  stacked = false;

  /** The src that failed to load (a new src is tried again) */
  @state()
  private failedSrc?: string;

  private readonly locale = new LocaleController(this);
  private readonly aria = new AriaController(this);
  // re-renders when the fallback slots change
  private readonly slots = new HasSlotController(this);

  protected override updated(changed: PropertyValues<this>): void {
    if (
      DEV &&
      changed.has("size") &&
      typeof this.size !== "number" &&
      !SIZE_PRESETS.includes(this.size)
    ) {
      devWarn(
        MinervaAvatar.tagName,
        `unknown size "${this.size}": use a preset (${SIZE_PRESETS.join(", ")}) or a number of pixels.`,
      );
    }
  }

  protected override render() {
    const showImage = !!this.src && this.failedSrc !== this.src;
    const label =
      this.aria.label ?? (this.name || this.locale.t("avatar.default"));
    const numericSize = typeof this.size === "number";
    const classes = classMap({
      avatar: true,
      [this.shape]: true,
      [String(this.size)]: !numericSize,
      stacked: this.stacked,
    });
    const style = styleMap(
      numericSize
        ? {
            "--avatar-size": `${this.size}px`,
            width: `${this.size}px`,
            height: `${this.size}px`,
          }
        : {},
    );

    if (showImage) {
      return html`<span part="base" class=${classes} style=${style}
        ><img
          part="image"
          class="avatarImg"
          alt=${this.alt ?? label}
          src=${this.src!}
          draggable="false"
          @error=${() => (this.failedSrc = this.src)}
      /></span>`;
    }

    const initials = getAvatarInitials(this.name);
    const fallback = this.slots.test("fallback")
      ? html`<slot name="fallback"></slot>`
      : initials || html`<slot></slot>`;
    return html`<span
      part="base"
      role="img"
      aria-label=${label}
      class=${classes}
      style=${style}
      ><span part="text" class="avatarText" aria-hidden="true"
        >${fallback}</span
      ></span
    >`;
  }
}

/**
 * Overlapping avatars with an optional "+N" indicator (`<AvatarGroup>` of
 * lib-core). `max` limits the visible avatars (the hidden ones are added to
 * the indicator); `count` adds avatars that are not rendered at all.
 *
 * Each child element is wrapped in its own item box inside the shadow root
 * (manual slot assignment), exactly like the React component, so the
 * overlap / hover styles of lib-core apply unchanged.
 *
 * @summary Overlapping group of avatars with a "+N" indicator.
 * @tag minerva-avatar-group
 * @slot - `<minerva-avatar>` elements
 * @csspart base - The group root (`role="group"`)
 * @csspart item - The wrapper of each visible avatar
 * @csspart count - The "+N" indicator
 */
export class MinervaAvatarGroup extends MinervaElement {
  static override tagName = "minerva-avatar-group";
  static override shadowRootOptions: ShadowRootInit = {
    ...MinervaElement.shadowRootOptions,
    slotAssignment: "manual",
  };
  static override styles = [
    hostStyles,
    css`
      :host {
        display: flex;
      }
      .avatarGroup {
        flex: 1 1 auto;
        min-width: 0;
      }
    `,
    sharedStyles(groupStyles),
  ];

  /** Number of additional avatars, shown in the "+N" indicator */
  @property({ type: Number })
  count?: number;

  /** Maximum number of avatars displayed; the others are counted in "+N" */
  @property({ type: Number })
  max?: number;

  private readonly locale = new LocaleController(this);
  private readonly aria = new AriaController(this);
  // re-renders when avatars are added / removed
  private readonly slots = new HasSlotController(this);

  private visibleAvatars(): Element[] {
    const avatars = Array.from(this.children);
    return this.max === undefined || this.max === null
      ? avatars
      : avatars.slice(0, Math.max(0, this.max));
  }

  protected override updated(changed: PropertyValues<this>): void {
    const visible = this.visibleAvatars();
    const slots = Array.from(
      this.renderRoot.querySelectorAll<HTMLSlotElement>("slot[data-item]"),
    );
    slots.forEach((slot, index) => {
      const avatar = visible[index];
      if (avatar && typeof slot.assign === "function") slot.assign(avatar);
    });
    if (
      DEV &&
      changed.has("max") &&
      this.max !== undefined &&
      this.max !== null &&
      !(Number.isInteger(this.max) && this.max >= 0)
    ) {
      devWarn(
        MinervaAvatarGroup.tagName,
        `max must be a non-negative integer (got ${this.max}).`,
      );
    }
  }

  protected override render() {
    void this.slots;
    const total = this.children.length;
    const visible = this.visibleAvatars();
    const extra = (Number(this.count) || 0) + total - visible.length;
    const label =
      this.aria.label ??
      (extra > 0
        ? this.locale.t("avatar.groupWithMore", { count: extra })
        : this.locale.t("avatar.group"));
    return html`<div
      part="base"
      role="group"
      class="avatarGroup"
      aria-label=${label}
    >
      ${visible.map(
        () =>
          html`<div part="item" class="avatarGroupItem">
            <slot data-item></slot>
          </div>`,
      )}
      ${
        extra > 0
          ? html`<div part="count" class="count" aria-hidden="true">
              +${extra}
            </div>`
          : nothing
      }
    </div>`;
  }
}

declare global {
  interface HTMLElementTagNameMap {
    "minerva-avatar": MinervaAvatar;
    "minerva-avatar-group": MinervaAvatarGroup;
  }
}

// packages/native/src/components/Avatar/Avatar.tsx
import {
  Children,
  createContext,
  isValidElement,
  useContext,
  useMemo,
  useState,
  type ReactNode,
} from "react";
import {
  Image,
  Text,
  View,
  type ImageSourcePropType,
  type StyleProp,
  type ViewProps,
  type ViewStyle,
} from "react-native";
import type { ResolvedTokens } from "@minerva/core";
import { useI18n, useTheme } from "../../theme/MinervaProvider";
import { part } from "../../internal/parts";
import { colorRole, weight, type SemanticColor } from "../../internal/styles";

export type AvatarShape = "circle" | "rounded" | "square";
export type AvatarSizeName =
  "xsmall" | "small" | "medium" | "large" | "xlarge" | "xxlarge";
export type AvatarSize = AvatarSizeName | number;

export interface AvatarProps extends Omit<ViewProps, "style" | "children"> {
  /**
   * Image: a URL or an `Image` source (`require("./me.png")`). When
   * omitted (or when it fails to load), the initials of `name` are shown
   */
  src?: string | ImageSourcePropType;
  /**
   * Name of the person: initials (first letters of the first two words, or
   * the first CJK character), the accessible label and the fallback color
   * @default ""
   */
  name?: string;
  /** Alternative text of the image; pass "" for a decorative avatar */
  alt?: string;
  /** Accessible label of the avatar (alias of `accessibilityLabel`) */
  "aria-label"?: string;
  /** Custom fallback content shown instead of the initials */
  fallback?: ReactNode;
  /**
   * Avatar shape
   * @default "circle"
   */
  shape?: AvatarShape;
  /**
   * A preset (xsmall 24, small 32, medium 48, large 64, xlarge 80, xxlarge
   * 96) or a number of dp
   * @default "medium"
   */
  size?: AvatarSize;
  /**
   * Color of the initials fallback; picked from the name when omitted
   * (the same name always gets the same color)
   */
  color?: SemanticColor;
  /** Fallback content when there is neither an image nor a name */
  children?: ReactNode;
  /** Style of the avatar */
  style?: StyleProp<ViewStyle>;
}

export interface AvatarGroupProps extends Omit<
  ViewProps,
  "style" | "children"
> {
  /** The Avatar elements */
  children?: ReactNode;
  /**
   * Maximum number of avatars to display; the others are counted in the
   * "+N" avatar
   */
  max?: number;
  /** Number of additional avatars (not rendered), added to the "+N" avatar */
  count?: number;
  /**
   * Size of every avatar of the group
   * @default "medium"
   */
  size?: AvatarSize;
  /**
   * Shape of every avatar of the group
   * @default "circle"
   */
  shape?: AvatarShape;
  /** Overlap between avatars in dp @default a quarter of the avatar size */
  spacing?: number;
  /** Accessible label of the group (alias of `accessibilityLabel`) */
  "aria-label"?: string;
  /** Style of the group */
  style?: StyleProp<ViewStyle>;
}

const CJK = /[㐀-鿿豈-﫿가-힯]/;

/** Initials of a name ("Ada Lovelace" -> "AL", "张三" -> "张") */
export function getAvatarInitials(name?: string): string {
  const trimmed = name?.trim() ?? "";
  if (!trimmed) return "";
  if (CJK.test(trimmed[0])) return trimmed[0];
  return trimmed
    .split(/\s+/)
    .slice(0, 2)
    .map((word) => word[0].toUpperCase())
    .join("");
}

const FALLBACK_COLORS: readonly SemanticColor[] = [
  "primary",
  "success",
  "warning",
  "danger",
  "info",
];

/** Color of a name's initials (stable string hash) */
export function getAvatarColor(name: string): SemanticColor {
  let hash = 0;
  for (let i = 0; i < name.length; i++) {
    hash = (hash * 31 + name.charCodeAt(i)) | 0;
  }
  return FALLBACK_COLORS[Math.abs(hash) % FALLBACK_COLORS.length];
}

const SIZE_SPACE: Record<AvatarSizeName, string> = {
  xsmall: "6",
  small: "8",
  medium: "12",
  large: "16",
  xlarge: "20",
  xxlarge: "24",
};

const avatarPx = (t: ResolvedTokens, size: AvatarSize): number =>
  typeof size === "number" ? size : t.space[SIZE_SPACE[size]];

const avatarRadius = (t: ResolvedTokens, shape: AvatarShape, px: number) =>
  shape === "circle"
    ? px / 2
    : shape === "square"
      ? t.radius.sm
      : px <= 32
        ? t.radius.md
        : t.radius.lg;

interface AvatarGroupContextValue {
  size: AvatarSize;
  shape: AvatarShape;
  /** Ring color separating overlapped avatars */
  ring: string;
}

const AvatarGroupContext = createContext<AvatarGroupContextValue | null>(null);

/**
 * Avatar: a picture of a person, falling back to their initials on a
 * deterministic token color (or custom fallback content) when there is no
 * image or it fails to load. Announced as one image named after the person.
 */
export function Avatar({
  src,
  name = "",
  alt,
  "aria-label": ariaLabel,
  accessibilityLabel,
  fallback,
  shape: shapeProp,
  size: sizeProp,
  color,
  children,
  style,
  ...rest
}: AvatarProps) {
  const { tokens: t, fonts } = useTheme();
  const { t: tr } = useI18n();
  const group = useContext(AvatarGroupContext);
  const size = sizeProp ?? group?.size ?? "medium";
  const shape = shapeProp ?? group?.shape ?? "circle";
  const px = avatarPx(t, size);
  const radius = avatarRadius(t, shape, px);

  // The source that failed to load: derived, so a new src is tried again
  const [failed, setFailed] = useState<unknown>(undefined);
  const source = useMemo<ImageSourcePropType | undefined>(
    () => (typeof src === "string" ? (src ? { uri: src } : undefined) : src),
    [src],
  );
  const showImage = source !== undefined && failed !== src;

  const label =
    accessibilityLabel ?? ariaLabel ?? (alt || name || tr("avatar.default"));
  const decorative = alt === "" && !ariaLabel && !accessibilityLabel;
  const initials = getAvatarInitials(name);
  const role = colorRole(t, color ?? getAvatarColor(name));

  return (
    <View
      accessible={!decorative}
      accessibilityRole={decorative ? undefined : "image"}
      accessibilityLabel={decorative ? undefined : label}
      importantForAccessibility={decorative ? "no-hide-descendants" : undefined}
      {...part("avatar", "root", {
        size: typeof size === "number" ? undefined : size,
        shape,
      })}
      {...rest}
      style={[
        {
          width: px,
          height: px,
          borderRadius: radius,
          overflow: "hidden",
          alignItems: "center",
          justifyContent: "center",
          backgroundColor: showImage
            ? t.colors["surface-muted-color"]
            : fallback !== undefined || !initials
              ? t.colors["surface-muted-color"]
              : role.subtle,
        },
        group && {
          borderWidth: Math.max(2, Math.round(px / 24)),
          borderColor: group.ring,
        },
        style,
      ]}
    >
      {showImage ? (
        <Image
          source={source}
          accessibilityIgnoresInvertColors
          onError={() => setFailed(src)}
          resizeMode="cover"
          style={{ width: "100%", height: "100%" }}
          {...part("avatar", "image")}
        />
      ) : fallback !== undefined ? (
        fallback
      ) : initials ? (
        <Text
          allowFontScaling={false}
          numberOfLines={1}
          style={{
            color: role.text,
            fontSize: Math.max(
              10,
              Math.round(px * (initials.length > 1 ? 0.38 : 0.44)),
            ),
            fontWeight: weight(t, "semibold"),
            ...(fonts.sans ? { fontFamily: fonts.sans } : null),
          }}
          {...part("avatar", "fallback")}
        >
          {initials}
        </Text>
      ) : typeof children === "string" ? (
        <Text
          allowFontScaling={false}
          style={{
            color: t.colors["text-secondary-color"],
            fontSize: Math.round(px * 0.4),
            ...(fonts.sans ? { fontFamily: fonts.sans } : null),
          }}
          {...part("avatar", "fallback")}
        >
          {children}
        </Text>
      ) : children !== undefined ? (
        children
      ) : (
        <PersonGlyph px={px} color={t.colors["text-muted-color"]} />
      )}
    </View>
  );
}

/** Default silhouette of an anonymous avatar (head + shoulders) */
function PersonGlyph({ px, color }: { px: number; color: string }) {
  const head = px * 0.36;
  const body = px * 0.72;
  return (
    <View
      {...part("avatar", "fallback")}
      style={{ width: px, height: px, alignItems: "center" }}
    >
      <View
        style={{
          marginTop: px * 0.2,
          width: head,
          height: head,
          borderRadius: head / 2,
          backgroundColor: color,
        }}
      />
      <View
        style={{
          marginTop: px * 0.06,
          width: body,
          height: body,
          borderRadius: body / 2,
          backgroundColor: color,
        }}
      />
    </View>
  );
}

/**
 * AvatarGroup: overlapping avatars of one size and shape with a "+N"
 * avatar for those over `max` (and `count`). A labelled group (not an
 * accessibility element itself).
 */
export function AvatarGroup({
  children,
  max,
  count,
  size = "medium",
  shape = "circle",
  spacing,
  "aria-label": ariaLabel,
  accessibilityLabel,
  style,
  ...rest
}: AvatarGroupProps) {
  const { tokens: t, fonts } = useTheme();
  const { t: tr } = useI18n();
  const avatars = Children.toArray(children);
  const visible =
    max === undefined ? avatars : avatars.slice(0, Math.max(0, max));
  const extra = (count ?? 0) + avatars.length - visible.length;
  const px = avatarPx(t, size);
  const overlap = spacing ?? Math.round(px / 4);
  const ctx = useMemo(
    () => ({ size, shape, ring: t.colors["surface-color"] }),
    [size, shape, t],
  );
  const label =
    accessibilityLabel ??
    ariaLabel ??
    (extra > 0
      ? tr("avatar.groupWithMore", { count: extra })
      : tr("avatar.group"));

  return (
    <AvatarGroupContext.Provider value={ctx}>
      <View
        role="group"
        accessibilityLabel={label}
        {...part("avatar-group", "root")}
        {...rest}
        style={[{ flexDirection: "row", alignItems: "center" }, style]}
      >
        {visible.map((child, index) => (
          <View
            key={isValidElement(child) ? (child.key ?? index) : index}
            {...part("avatar-group", "item")}
            style={{
              marginLeft: index === 0 ? 0 : -overlap,
              zIndex: visible.length - index,
            }}
          >
            {child}
          </View>
        ))}
        {extra > 0 ? (
          <View
            accessibilityElementsHidden
            importantForAccessibility="no-hide-descendants"
            {...part("avatar-group", "count")}
            style={{
              marginLeft: visible.length ? -overlap : 0,
              width: px,
              height: px,
              borderRadius: avatarRadius(t, shape, px),
              borderWidth: Math.max(2, Math.round(px / 24)),
              borderColor: t.colors["surface-color"],
              backgroundColor: t.colors["surface-muted-color"],
              alignItems: "center",
              justifyContent: "center",
            }}
          >
            <Text
              allowFontScaling={false}
              style={{
                color: t.colors["text-secondary-color"],
                fontSize: Math.max(10, Math.round(px * 0.34)),
                fontWeight: weight(t, "semibold"),
                ...(fonts.sans ? { fontFamily: fonts.sans } : null),
              }}
            >
              +{extra}
            </Text>
          </View>
        ) : null}
      </View>
    </AvatarGroupContext.Provider>
  );
}
