// packages/angular/src/testing/styling-hooks/autocomplete.ts
import { Component } from "@angular/core";
import {
  MnAutoComplete,
  type AutoCompleteOption,
} from "../../components/auto-complete";
import type { HookScenario } from "../types";

const options: AutoCompleteOption[] = [
  { label: "Apple", value: "apple", group: "Fruits" },
  { label: "Carrot", value: "carrot", group: "" },
];

const open: HookScenario["setup"] = async ({ user, root }) => {
  await user.click(root.querySelector("input")!);
};

@Component({
  imports: [MnAutoComplete],
  template: `<mn-auto-complete label="Food" [options]="options" />`,
})
class Closed {
  options = options;
}

@Component({
  imports: [MnAutoComplete],
  template: `<mn-auto-complete
    label="Food"
    [options]="options"
    [groupBy]="groupBy"
  />`,
})
class Grouped {
  options = options;
  groupBy = (option: AutoCompleteOption) => option.group ?? "";
}

@Component({
  imports: [MnAutoComplete],
  template: `<mn-auto-complete label="Food" [options]="options" />`,
})
class Keyboard {
  options: AutoCompleteOption[] = [
    { label: "Apple", value: "apple" },
    { label: "Apricot", value: "apricot", disabled: true },
  ];
}

@Component({
  imports: [MnAutoComplete],
  template: `<mn-auto-complete
    label="Food"
    [options]="options"
    defaultValue="zzz"
  />`,
})
class Empty {
  options = options;
}

@Component({
  imports: [MnAutoComplete],
  template: `<mn-auto-complete label="Food" [options]="options" loading />`,
})
class Loading {
  options = options;
}

@Component({
  imports: [MnAutoComplete],
  template: `<mn-auto-complete label="Food" [options]="options" disabled />`,
})
class Disabled {
  options = options;
}

@Component({
  imports: [MnAutoComplete],
  template: `<mn-auto-complete label="Food" [options]="options" readOnly />`,
})
class ReadOnly {
  options = options;
}

export default [
  { name: "closed, label", component: Closed },
  { name: "open, grouped", component: Grouped, setup: open },
  {
    name: "keyboard: highlighted item, disabled item",
    component: Keyboard,
    setup: async ({ user, root }) => {
      await user.click(root.querySelector("input")!);
      await user.keyboard("{ArrowDown}");
    },
  },
  { name: "open, empty", component: Empty, setup: open },
  { name: "open, loading", component: Loading, setup: open },
  { name: "disabled", component: Disabled },
  { name: "read-only", component: ReadOnly },
] satisfies HookScenario[];

// packages/lib-core/src/test-utils/styling-hooks/autocomplete.tsx
import { AutoComplete } from "../../components/AutoComplete";
import type { HookScenario } from "./types";

const options = [
  { label: "Apple", value: "apple", group: "Fruits" },
  { label: "Carrot", value: "carrot", group: "" },
];

const open: HookScenario["setup"] = async ({ user, container }) => {
  await user.click(container.querySelector("input")!);
};

export default [
  {
    name: "closed, label",
    element: <AutoComplete label="Food" options={options} />,
  },
  {
    name: "open, grouped",
    element: (
      <AutoComplete
        label="Food"
        options={options}
        groupBy={(option) => option.group ?? ""}
      />
    ),
    setup: open,
  },
  {
    name: "keyboard: highlighted item, disabled item",
    element: (
      <AutoComplete
        label="Food"
        options={[
          { label: "Apple", value: "apple" },
          { label: "Apricot", value: "apricot", disabled: true },
        ]}
      />
    ),
    setup: async ({ user, container }) => {
      await user.click(container.querySelector("input")!);
      await user.keyboard("{ArrowDown}");
    },
  },
  {
    name: "open, empty",
    element: <AutoComplete label="Food" options={options} defaultValue="zzz" />,
    setup: open,
  },
  {
    name: "open, loading",
    element: <AutoComplete label="Food" options={options} loading />,
    setup: open,
  },
  {
    name: "disabled",
    element: (
      <AutoComplete
        label="Food"
        options={options}
        inputProps={{ disabled: true }}
      />
    ),
  },
  {
    name: "read-only",
    element: (
      <AutoComplete
        label="Food"
        options={options}
        inputProps={{ readOnly: true }}
      />
    ),
  },
] satisfies HookScenario[];
