// packages/angular/src/testing/styling-hooks/badge.ts
import { Component } from "@angular/core";
import { MnBadge } from "../../components/foundations";
import type { HookScenario } from "../types";
@Component({
  imports: [MnBadge],
  template: `<mn-badge value="10" icon="★" attached>Content</mn-badge>`,
})
class Fixture {}
export default [
  { name: "content and states", component: Fixture },
] satisfies HookScenario[];

// packages/lib-core/src/test-utils/styling-hooks/badge.tsx
import { Badge } from "../../components/Badge";
import type { HookScenario } from "./types";

export default [
  { name: "standalone", element: <Badge icon={<svg />}>5</Badge> },
  {
    name: "attached, every key",
    element: (
      <Badge content="3" size="small" variant="outline" color="danger">
        <button type="button">Inbox</button>
      </Badge>
    ),
  },
] satisfies HookScenario[];
