// packages/angular/src/testing/styling-hooks/description-list.ts
import { Component } from "@angular/core";
import { MnDescriptionList } from "../../components/foundations";
import type { HookScenario } from "../types";
@Component({
  imports: [MnDescriptionList],
  template: `<mn-description-list
    [items]="[{ term: 'Name', description: 'Ada' }]"
  />`,
})
class Fixture {}
export default [
  { name: "content and states", component: Fixture },
] satisfies HookScenario[];

// packages/lib-core/src/test-utils/styling-hooks/description-list.tsx
import { DescriptionList } from "../../components/DescriptionList";
import type { HookScenario } from "./types";

export default [
  {
    name: "rows",
    element: (
      <DescriptionList
        items={[
          { key: "a", label: "Status", value: "Active" },
          { key: "b", label: "Owner", value: "Ada" },
        ]}
      />
    ),
  },
] satisfies HookScenario[];
