// packages/angular/src/testing/styling-hooks/form-layout.ts
import { Component } from "@angular/core";
import { MnFormLayout } from "../../components/form-layout";
import type { HookScenario } from "../types";

@Component({
  imports: [MnFormLayout],
  template: `<form mnFormLayout [columns]="{ base: 1, md: 2 }">
    <input aria-label="Name" />
  </form>`,
})
class Default {}

export default [
  { name: "default", component: Default },
] satisfies HookScenario[];

// packages/lib-core/src/test-utils/styling-hooks/form-layout.tsx
import { FormLayout } from "../../components/FormLayout";
import type { HookScenario } from "./types";

export default [
  {
    name: "default",
    element: (
      <FormLayout columns={{ base: 1, md: 2 }}>
        <input aria-label="Name" />
      </FormLayout>
    ),
  },
] satisfies HookScenario[];
