// packages/angular/src/testing/styling-hooks/input.ts
import { Component } from "@angular/core";
import { MnInput } from "../../components/input";
import type { HookScenario } from "../types";

@Component({
  imports: [MnInput],
  template: `<mn-input
    aria-label="Name"
    prefix="@"
    suffix="kg"
    clearable
    defaultValue="Ada"
    showCharCount
    [maxLength]="10"
    size="small"
    variant="filled"
    required
  />`,
})
class Addons {}

@Component({
  imports: [MnInput],
  template: `<mn-input
    aria-label="Password"
    type="password"
    invalid
    readOnly
  />`,
})
class Password {}

@Component({
  imports: [MnInput],
  template: `<mn-input aria-label="Name" disabled />`,
})
class Disabled {}

export default [
  { name: "addons, clear button, counter, every key", component: Addons },
  { name: "password, invalid, read-only", component: Password },
  { name: "disabled", component: Disabled },
] satisfies HookScenario[];

// packages/lib-core/src/test-utils/styling-hooks/input.tsx
import { Input } from "../../components/Input";
import type { HookScenario } from "./types";

export default [
  {
    name: "addons, clear button, counter, every key",
    element: (
      <Input
        aria-label="Name"
        prefix="@"
        suffix="kg"
        clearable
        defaultValue="Ada"
        showCharCount
        maxLength={10}
        size="small"
        variant="filled"
        required
      />
    ),
  },
  {
    name: "password, invalid, read-only",
    element: <Input aria-label="Password" type="password" invalid readOnly />,
  },
  { name: "disabled", element: <Input aria-label="Name" disabled /> },
] satisfies HookScenario[];
