// packages/angular/src/testing/styling-hooks/page-section.ts
import { Component } from "@angular/core";
import { MnPageSection } from "../../components/foundations";
import type { HookScenario } from "../types";
@Component({
  imports: [MnPageSection],
  template: `<mn-page-section title="Title" description="Description" icon="★"
    >Content</mn-page-section
  >`,
})
class Fixture {}
export default [
  { name: "content and states", component: Fixture },
] satisfies HookScenario[];

// packages/lib-core/src/test-utils/styling-hooks/page-section.tsx
import { PageSection } from "../../components/Page";
import type { HookScenario } from "./types";

export default [
  {
    name: "full",
    element: (
      <PageSection
        title="Title"
        description="Description"
        icon={<svg />}
        actions={<span>Action</span>}
      >
        Content
      </PageSection>
    ),
  },
] satisfies HookScenario[];
