// packages/angular/src/testing/styling-hooks/page-header.ts
import { Component } from "@angular/core";
import { MnPageHeader } from "../../components/foundations";
import type { HookScenario } from "../types";
@Component({
  imports: [MnPageHeader],
  template: `<mn-page-header title="Title" description="Description"
    >Actions</mn-page-header
  >`,
})
class Fixture {}
export default [
  { name: "content and states", component: Fixture },
] satisfies HookScenario[];

// packages/lib-core/src/test-utils/styling-hooks/page-header.tsx
import { PageHeader } from "../../components/Page";
import type { HookScenario } from "./types";

export default [
  {
    name: "full",
    element: (
      <PageHeader
        title="Title"
        description="Description"
        actions={<span>Action</span>}
      />
    ),
  },
  { name: "title only", element: <PageHeader title="Title" /> },
] satisfies HookScenario[];
