// packages/angular/src/testing/styling-hooks/palette-toggle.ts
import { Component } from "@angular/core";
import { MnPaletteToggle } from "../../components/navigation";
import type { HookScenario } from "../types";
@Component({ imports: [MnPaletteToggle], template: `<mn-palette-toggle />` })
class Fixture {}
export default [
  { name: "content and states", component: Fixture },
] satisfies HookScenario[];

// packages/lib-core/src/test-utils/styling-hooks/palette-toggle.tsx
import { ThemeProvider } from "../../contexts/ThemeProvider";
import { PaletteToggle } from "../../components/ThemeToggle";
import type { HookScenario } from "./types";

export default [
  {
    name: "default",
    element: (
      <ThemeProvider>
        <PaletteToggle />
      </ThemeProvider>
    ),
  },
] satisfies HookScenario[];
