// packages/angular/src/testing/styling-hooks/radio-group.ts
import { Component } from "@angular/core";
import { MnRadio, MnRadioGroup } from "../../components/radio";
import type { HookScenario } from "../types";

@Component({
  imports: [MnRadio, MnRadioGroup],
  template: `<mn-radio-group
    label="Payment"
    helperText="Pick one"
    direction="horizontal"
    size="small"
    color="success"
    required
    defaultValue="card"
  >
    <mn-radio value="card" label="Card" />
    <mn-radio value="cash" label="Cash" />
  </mn-radio-group>`,
})
class Labelled {}

@Component({
  imports: [MnRadio, MnRadioGroup],
  template: `<mn-radio-group aria-label="Payment" error disabled>
    <mn-radio value="card" label="Card" />
  </mn-radio-group>`,
})
class Invalid {}

export default [
  { name: "label, helper text, every key", component: Labelled },
  { name: "vertical, invalid, disabled", component: Invalid },
] satisfies HookScenario[];

// packages/lib-core/src/test-utils/styling-hooks/radio-group.tsx
import { Radio, RadioGroup } from "../../components/Radio";
import type { HookScenario } from "./types";

export default [
  {
    name: "label, helper text, every key",
    element: (
      <RadioGroup
        label="Payment"
        helperText="Pick one"
        direction="horizontal"
        size="small"
        color="success"
        required
        defaultValue="card"
      >
        <Radio value="card" label="Card" />
        <Radio value="cash" label="Cash" />
      </RadioGroup>
    ),
  },
  {
    name: "vertical, invalid, disabled",
    element: (
      <RadioGroup aria-label="Payment" error disabled>
        <Radio value="card" label="Card" />
      </RadioGroup>
    ),
  },
] satisfies HookScenario[];
