// packages/angular/src/testing/styling-hooks/split-layout.ts
import { Component } from "@angular/core";
import { MnSplitLayout } from "../../components/foundations";
import type { HookScenario } from "../types";
@Component({
  imports: [MnSplitLayout],
  template: `<mn-split-layout
    >Main
    <aside mnAside>Aside</aside></mn-split-layout
  >`,
})
class Fixture {}
export default [
  { name: "content and states", component: Fixture },
] satisfies HookScenario[];

// packages/lib-core/src/test-utils/styling-hooks/split-layout.tsx
import { SplitLayout } from "../../components/SplitLayout";
import type { HookScenario } from "./types";

export default [
  {
    name: "with aside",
    element: <SplitLayout aside="Aside">Main</SplitLayout>,
  },
  {
    name: "without aside",
    element: <SplitLayout aside={null}>Main</SplitLayout>,
  },
] satisfies HookScenario[];
