// packages/angular/src/testing/styling-hooks/stat-card.ts
import { Component } from "@angular/core";
import { MnStatCard } from "../../components/foundations";
import type { HookScenario } from "../types";
@Component({
  imports: [MnStatCard],
  template: `<mn-stat-card
    label="Total"
    value="42"
    icon="★"
    description="Records"
  />`,
})
class Fixture {}
export default [
  { name: "content and states", component: Fixture },
] satisfies HookScenario[];

// packages/lib-core/src/test-utils/styling-hooks/stat-card.tsx
import { StatCard } from "../../components/Page";
import type { HookScenario } from "./types";

export default [
  {
    name: "full",
    element: (
      <StatCard
        label="Users"
        value={42}
        icon={<svg />}
        description="Last 30 days"
      />
    ),
  },
] satisfies HookScenario[];
