// packages/angular/src/testing/styling-hooks/switch.ts
import { Component } from "@angular/core";
import { MnSwitch } from "../../components/switch";
import type { HookScenario } from "../types";

@Component({
  imports: [MnSwitch],
  template: ` <ng-template #icon><svg aria-hidden="true"></svg></ng-template>
    <mn-switch
      label="Wi-Fi"
      [icon]="icon"
      defaultChecked
      size="small"
      color="success"
      shape="square"
    />`,
})
class Labelled {}

@Component({
  imports: [MnSwitch],
  template: ` <ng-template #icon><svg aria-hidden="true"></svg></ng-template>
    <mn-switch
      aria-label="Mode"
      offLabel="Off"
      onLabel="On"
      [icon]="icon"
      iconPlacement="end"
      loading
    />`,
})
class Sides {}

@Component({
  imports: [MnSwitch],
  template: `<mn-switch aria-label="Wi-Fi" disabled />`,
})
class Disabled {}

@Component({
  imports: [MnSwitch],
  template: `<mn-switch
    aria-label="Read only"
    variant="segmented"
    offLabel="Off"
    onLabel="On"
    invalid
    required
    readOnly
  />`,
})
class SegmentedField {}

export default [
  { name: "segmented and field states", component: SegmentedField },
  { name: "label, icon in the thumb, checked, every key", component: Labelled },
  { name: "side labels, icon after the slider, loading", component: Sides },
  { name: "disabled", component: Disabled },
] satisfies HookScenario[];

// packages/lib-core/src/test-utils/styling-hooks/switch.tsx
import { FormControl } from "../../components/FormControl";
import { Switch } from "../../components/Switch";
import type { HookScenario } from "./types";

const Icon = () => <svg aria-hidden="true" />;

export default [
  {
    name: "label, icon in the thumb, checked, every key",
    element: (
      <Switch
        label="Wi-Fi"
        icon={<Icon />}
        defaultChecked
        size="small"
        color="success"
        shape="square"
      />
    ),
  },
  {
    name: "side labels, icon after the slider, loading",
    element: (
      <Switch
        aria-label="Mode"
        offLabel="Off"
        onLabel="On"
        icon={<Icon />}
        iconPlacement="end"
        loading
      />
    ),
  },
  {
    name: "segmented, invalid, required, read-only",
    element: (
      <FormControl invalid required readOnly>
        <Switch
          aria-label="Source"
          variant="segmented"
          offLabel="A"
          onLabel="B"
        />
      </FormControl>
    ),
  },
  { name: "disabled", element: <Switch aria-label="Wi-Fi" disabled /> },
] satisfies HookScenario[];
