// packages/angular/src/testing/styling-hooks/text-link.ts
import { Component } from "@angular/core";
import { MnTextLink } from "../../components/foundations";
import type { HookScenario } from "../types";
@Component({
  imports: [MnTextLink],
  template: `<a mnTextLink href="/">Home</a>`,
})
class Fixture {}
export default [
  { name: "content and states", component: Fixture },
] satisfies HookScenario[];

// packages/lib-core/src/test-utils/styling-hooks/text-link.tsx
import { TextLink } from "../../components/TextLink";
import type { HookScenario } from "./types";

export default [
  { name: "default", element: <TextLink href="/docs">Docs</TextLink> },
  {
    name: "subtle",
    element: (
      <TextLink href="/docs" variant="subtle">
        Docs
      </TextLink>
    ),
  },
  {
    name: "action, asChild",
    element: (
      <TextLink variant="action" asChild>
        <a href="/docs">Docs</a>
      </TextLink>
    ),
  },
] satisfies HookScenario[];
