// apps/docs/src/docs/pages/form-control/vue/form.vue
<script setup lang="ts">
import { ref } from "vue";
import { FormField, Input, Button, VStack } from "minerva-design/vue";
const name = ref("Minerva");
const saved = ref(false);
</script>
<template>
  <form @submit.prevent="saved = true">
    <VStack :gap="3"
      ><FormField label="Project name" required
        ><Input v-model="name" required /></FormField
      ><Button type="submit">Save project</Button
      ><output v-if="saved">Saved {{ name }}</output></VStack
    >
  </form>
</template>

// apps/docs/src/docs/pages/modal/demos/form.tsx
import { useState } from "react";
import {
  Button,
  Input,
  FormField,
  Modal,
  ModalBody,
  ModalFooter,
} from "minerva-design";

export default function FormDemo() {
  const [open, setOpen] = useState(false);
  const [name, setName] = useState("Quarterly report");
  return (
    <>
      <Button onClick={() => setOpen(true)}>Rename “{name}”</Button>
      <Modal open={open} onOpenChange={setOpen} title="Rename document">
        <form
          onSubmit={(event) => {
            event.preventDefault();
            setName(new FormData(event.currentTarget).get("name") as string);
            setOpen(false);
          }}
        >
          <ModalBody>
            <FormField label="Name">
              <Input name="name" defaultValue={name} />
            </FormField>
          </ModalBody>
          <ModalFooter>
            <Button type="submit">Save</Button>
          </ModalFooter>
        </form>
      </Modal>
    </>
  );
}
