// packages/vue/src/components/Menu/ContextMenu.vue
<script setup lang="ts">
/**
 * ContextMenu: the Menu entries opened at the pointer on right click (long
 * press on touch); Shift+F10 or the ContextMenu key open it at the area
 * (the single child of the default slot). A right click while open moves
 * the menu. Focus moves to the first item and returns to the area (or the
 * element focused in it) on close.
 *
 * Attributes (`class`, `style`, `data-*`...) go to the menu panel.
 */
import {
  computed,
  onBeforeUnmount,
  shallowRef,
  useId,
  type CSSProperties,
} from "vue";
import type { Placement, VirtualElement } from "@minerva/dom";
import { useInheritedDirection } from "../../internal/direction";
import { useLayerParent } from "../../internal/scope";
import { unrefElement } from "../../internal/Slot";
import { MenuRoot, TriggerSlot, type FocusIntent } from "./MenuItems";
import { LONG_PRESS_DELAY } from "./constants";
import type { ContextMenuProps, MenuAction } from "./types";

defineOptions({ name: "ContextMenu", inheritAttrs: false });

const props = withDefaults(defineProps<ContextMenuProps>(), {
  closeOnSelect: true,
  size: "medium",
  disabled: false,
  modal: true,
  loop: true,
  dir: undefined,
  ariaLabel: undefined,
});
const emit = defineEmits<{
  /** The menu opens or closes */
  openChange: [open: boolean];
  /** An action was selected (the original item object) */
  select: [item: MenuAction];
}>();
defineSlots<{
  /** The area opening the menu (its single child gets the listeners) */
  default?: () => unknown;
}>();

interface Position {
  anchor: Element | VirtualElement;
  placement: Placement;
  offset: { mainAxis: number; crossAxis: number };
}

const AT_POINTER = { mainAxis: 2, crossAxis: 0 };
const AT_ELEMENT = { mainAxis: 4, crossAxis: 0 };

/** A zero-size anchor at a viewport point (the pointer). */
const pointAnchor = (
  x: number,
  y: number,
  contextElement: Element,
): VirtualElement => ({
  contextElement,
  getBoundingClientRect: () => ({
    x,
    y,
    left: x,
    top: y,
    right: x,
    bottom: y,
    width: 0,
    height: 0,
  }),
});

// Uncontrolled only, like React (`openChange` reports the changes).
const open = shallowRef(false);
const area = shallowRef<HTMLElement | null>(null);
const setArea = (value: unknown) => {
  area.value = unrefElement(value);
};
// Without `dir`, the menu follows the direction inherited by the area.
const inheritedDir = useInheritedDirection(area, () => props.dir === undefined);
const dir = computed(() => props.dir ?? inheritedDir.value);
const position = shallowRef<Position | null>(null);
const tabContainer = useLayerParent();
const contentId = useId();
let restoreTarget: HTMLElement | null = null;
let longPress: ReturnType<typeof setTimeout> | undefined;

const clearLongPress = () => {
  clearTimeout(longPress);
  longPress = undefined;
};
onBeforeUnmount(clearLongPress);

const setOpen = (value: boolean) => {
  if (open.value === value) return;
  open.value = value;
  emit("openChange", value);
};
const openAt = (el: HTMLElement, next: Position) => {
  if (!open.value) {
    const focused = el.ownerDocument.activeElement;
    restoreTarget =
      focused instanceof HTMLElement && el.contains(focused) ? focused : el;
  }
  position.value = next;
  setOpen(true);
};
const openAtPoint = (el: HTMLElement, x: number, y: number) =>
  openAt(el, {
    anchor: pointAnchor(x, y, el),
    placement: dir.value === "rtl" ? "left-start" : "right-start",
    offset: AT_POINTER,
  });

const onContextmenu = (event: MouseEvent) => {
  const el = area.value;
  if (props.disabled || event.defaultPrevented || !el) return;
  event.preventDefault();
  clearLongPress();
  openAtPoint(el, event.clientX, event.clientY);
};

const onKeydown = (event: KeyboardEvent) => {
  const el = area.value;
  if (props.disabled || event.defaultPrevented || !el) return;
  if (event.key === "ContextMenu" || (event.shiftKey && event.key === "F10")) {
    event.preventDefault();
    openAt(el, {
      anchor: el,
      placement: dir.value === "rtl" ? "bottom-end" : "bottom-start",
      offset: AT_ELEMENT,
    });
  }
};

const onPointerdown = (event: PointerEvent) => {
  const el = area.value;
  if (props.disabled || event.pointerType !== "touch" || !el) return;
  clearLongPress();
  const { clientX, clientY } = event;
  longPress = setTimeout(() => {
    longPress = undefined;
    openAtPoint(el, clientX, clientY);
  }, LONG_PRESS_DELAY);
};
const onTouchEnd = (event: PointerEvent) => {
  if (event.pointerType === "touch") clearLongPress();
};

const consumeIntent = (): FocusIntent => "first";
const getRestoreTarget = () => restoreTarget;
const selectItem = (item: MenuAction) => emit("select", item);
const onPointerDownOutside = (event: PointerEvent) => {
  // A right click in the area moves the menu instead of closing it.
  if (
    event.button === 2 &&
    event.target instanceof Node &&
    area.value?.contains(event.target)
  ) {
    event.preventDefault();
  }
};

const areaStyle = computed<CSSProperties | undefined>(() =>
  props.disabled
    ? undefined
    : {
        WebkitTouchCallout: "none",
        // Keep right clicks reaching the area while a modal menu disables
        // pointer events on the page (they move the menu).
        ...(open.value && props.modal ? { pointerEvents: "auto" } : {}),
      },
);
</script>

<template>
  <TriggerSlot
    :ref="setArea"
    hook-component="context-menu"
    :hook-open="open"
    :hook-disabled="disabled"
    :style="areaStyle"
    @contextmenu="onContextmenu"
    @keydown="onKeydown"
    @pointerdown="onPointerdown"
    @pointermove="onTouchEnd"
    @pointerup="onTouchEnd"
    @pointercancel="onTouchEnd"
  >
    <slot />
  </TriggerSlot>
  <MenuRoot
    component="context-menu"
    :items="items"
    :close-on-select="closeOnSelect"
    :size="size"
    :loop="loop"
    :dir="dir"
    :modal="modal"
    :aria-label="ariaLabel"
    :open="open && !disabled && !!position"
    :set-open="setOpen"
    :select-item="selectItem"
    :anchor="position?.anchor ?? null"
    :placement="position?.placement ?? 'right-start'"
    :offset="position?.offset ?? AT_POINTER"
    :content-id="contentId"
    :trigger="null"
    :get-restore-target="getRestoreTarget"
    :consume-intent="consumeIntent"
    :pointer-down-outside="onPointerDownOutside"
    :tab-container="tabContainer ?? null"
    :panel-attrs="$attrs"
  />
</template>

// packages/lib-core/src/components/Menu/ContextMenu.tsx
import {
  useCallback,
  useEffect,
  useId,
  useRef,
  useState,
  type CSSProperties,
  type KeyboardEvent as ReactKeyboardEvent,
  type MouseEvent as ReactMouseEvent,
  type PointerEvent as ReactPointerEvent,
} from "react";
import type { Placement, VirtualElement } from "@minerva/core";
import { Slot } from "../../internal/Slot";
import { useInheritedDirection } from "../../internal/direction";
import { useControllableState } from "../../internal/useControllableState";
import { useLayerParent } from "../../internal/useDismissableLayer";
import { MenuRoot, type FocusIntent } from "./MenuItems";
import type { ContextMenuProps } from "./types";

/** Touch long press duration that opens the menu (ms). */
export const LONG_PRESS_DELAY = 700;

interface Position {
  anchor: Element | VirtualElement;
  placement: Placement;
  offset: { mainAxis: number; crossAxis: number };
}

/** A zero-size anchor at a viewport point (the pointer). */
const pointAnchor = (
  x: number,
  y: number,
  contextElement: Element,
): VirtualElement => ({
  contextElement,
  getBoundingClientRect: () => ({
    x,
    y,
    left: x,
    top: y,
    right: x,
    bottom: y,
    width: 0,
    height: 0,
  }),
});

const AT_POINTER = { mainAxis: 2, crossAxis: 0 };
const AT_ELEMENT = { mainAxis: 4, crossAxis: 0 };

/**
 * ContextMenu: the Menu entries opened at the pointer on right click (long
 * press on touch); Shift+F10 or the ContextMenu key open it at the area.
 * A right click while open moves the menu. Focus moves to the first item
 * and returns to the area (or the element focused in it) on close.
 */
const ContextMenu = ({
  children,
  items,
  onSelect,
  closeOnSelect = true,
  size = "medium",
  onOpenChange,
  disabled = false,
  modal = true,
  loop = true,
  dir: dirProp,
  className,
  "aria-label": ariaLabel,
}: ContextMenuProps) => {
  const [open, setOpen] = useControllableState({
    defaultValue: false,
    onChange: onOpenChange,
    name: "ContextMenu",
    prop: "open",
  });
  const [area, setArea] = useState<HTMLElement | null>(null);
  // Without `dir`, the menu follows the direction inherited by the area.
  const inheritedDir = useInheritedDirection(area, dirProp === undefined);
  const dir = dirProp ?? inheritedDir;
  const [position, setPosition] = useState<Position | null>(null);
  const tabContainer = useLayerParent();
  const contentId = useId();
  const restoreTarget = useRef<HTMLElement | null>(null);
  const longPress = useRef<ReturnType<typeof setTimeout> | undefined>(
    undefined,
  );

  const clearLongPress = () => {
    clearTimeout(longPress.current);
    longPress.current = undefined;
  };
  useEffect(() => () => clearTimeout(longPress.current), []);

  const openAt = (next: Position) => {
    if (!area) return;
    if (!open) {
      const focused = area.ownerDocument.activeElement;
      restoreTarget.current =
        focused instanceof HTMLElement && area.contains(focused)
          ? focused
          : area;
    }
    setPosition(next);
    setOpen(true);
  };
  const openAtPoint = (x: number, y: number) =>
    area &&
    openAt({
      anchor: pointAnchor(x, y, area),
      placement: dir === "rtl" ? "left-start" : "right-start",
      offset: AT_POINTER,
    });

  const onContextMenu = (event: ReactMouseEvent<HTMLElement>) => {
    if (disabled || event.defaultPrevented) return;
    event.preventDefault();
    clearLongPress();
    openAtPoint(event.clientX, event.clientY);
  };

  const onKeyDown = (event: ReactKeyboardEvent<HTMLElement>) => {
    if (disabled || event.defaultPrevented || !area) return;
    if (
      event.key === "ContextMenu" ||
      (event.shiftKey && event.key === "F10")
    ) {
      event.preventDefault();
      openAt({
        anchor: area,
        placement: dir === "rtl" ? "bottom-end" : "bottom-start",
        offset: AT_ELEMENT,
      });
    }
  };

  const onPointerDown = (event: ReactPointerEvent<HTMLElement>) => {
    if (disabled || event.pointerType !== "touch") return;
    clearLongPress();
    const { clientX, clientY } = event;
    longPress.current = setTimeout(() => {
      longPress.current = undefined;
      openAtPoint(clientX, clientY);
    }, LONG_PRESS_DELAY);
  };
  const onTouchEnd = (event: ReactPointerEvent<HTMLElement>) => {
    if (event.pointerType === "touch") clearLongPress();
  };

  const consumeIntent = useCallback((): FocusIntent => "first", []);
  const getRestoreTarget = useCallback(() => restoreTarget.current, []);

  const style: CSSProperties | undefined = disabled
    ? undefined
    : {
        WebkitTouchCallout: "none",
        // Keep right clicks reaching the area while a modal menu disables
        // pointer events on the page (they move the menu).
        ...(open && modal ? { pointerEvents: "auto" } : {}),
      };

  return (
    <>
      <Slot
        ref={setArea}
        // No state hook on the area: the child (often a Minerva component)
        // keeps its own hooks.
        style={style}
        onContextMenu={onContextMenu}
        onKeyDown={onKeyDown}
        onPointerDown={onPointerDown}
        onPointerMove={onTouchEnd}
        onPointerUp={onTouchEnd}
        onPointerCancel={onTouchEnd}
      >
        {children}
      </Slot>
      <MenuRoot
        component="context-menu"
        items={items}
        onSelect={onSelect}
        closeOnSelect={closeOnSelect}
        size={size}
        loop={loop}
        dir={dir}
        modal={modal}
        className={className}
        aria-label={ariaLabel}
        open={open && !disabled && !!position}
        setOpen={setOpen}
        anchor={position?.anchor ?? null}
        placement={position?.placement ?? "right-start"}
        offset={position?.offset ?? AT_POINTER}
        contentId={contentId}
        trigger={null}
        getRestoreTarget={getRestoreTarget}
        consumeIntent={consumeIntent}
        onPointerDownOutside={(event) => {
          // A right click in the area moves the menu instead of closing it.
          if (
            event.button === 2 &&
            area &&
            event.target instanceof Node &&
            area.contains(event.target)
          ) {
            event.preventDefault();
          }
        }}
        tabContainer={tabContainer}
      />
    </>
  );
};

export default ContextMenu;
