// packages/vue/src/components/TimePicker/TimePicker.vue
<script setup lang="ts">
/**
 * TimePicker: type a time or pick hours / minutes / seconds from a panel.
 * `v-model` (a `Date`, `null` = no time) or uncontrolled (`defaultValue`).
 * Inside a FormControl the input picks up the field's id, label,
 * description, invalid, required, disabled and read-only state (explicit
 * props win). `class`, `style` and `data-*` attributes go to the root.
 */
import { computed, onMounted, provide, ref, shallowRef, unref } from "vue";
import {
  formatHasSeconds,
  formatTime,
  parseTimeInput,
  resolveTimeFormat,
  startOfToday,
} from "@minerva/core";
import styles from "@react-styles/components/TimePicker/timePicker.module.scss";
import iconButtonStyles from "@react-styles/components/IconButton/iconButton.module.scss";
import { hooks } from "../../internal/hooks";
import { IconClock, IconX } from "../../internal/icons";
import { useControllable } from "../../internal/controllable";
import FloatingPanel from "../../internal/FloatingPanel.vue";
import { useLayerParent } from "../../internal/scope";
import {
  FORM_CONTROL_KEY,
  useFormControlContext,
  useFormControlProps,
} from "../../internal/form-control";
import { useI18n } from "../../config/useI18n";
import { Input } from "../Input";
import TimePickerPanel from "./TimePickerPanel.vue";
import { adjacentTabbable, tabLeavesPanel } from "./tabbing";
import type { TimePickerEmits, TimePickerProps, TimeUnitKind } from "./types";

defineOptions({ name: "TimePicker", inheritAttrs: false });

const props = withDefaults(defineProps<TimePickerProps>(), {
  modelValue: undefined,
  defaultValue: undefined,
  format: "HH:mm:ss",
  use12Hours: false,
  placeholder: undefined,
  label: undefined,
  ariaLabel: undefined,
  ariaLabelledby: undefined,
  ariaDescribedby: undefined,
  id: undefined,
  required: undefined,
  readOnly: undefined,
  invalid: undefined,
  name: "time-picker",
  disabled: undefined,
  clearable: true,
  size: "medium",
  minTime: undefined,
  maxTime: undefined,
  showSecond: true,
  hourStep: 1,
  minuteStep: 1,
  secondStep: 1,
});
const emit = defineEmits<TimePickerEmits>();

const { t } = useI18n();
const fc = useFormControlContext();
// The field state is resolved here (explicit props win over the
// FormControl), so the inner Input must not merge it again.
provide(FORM_CONTROL_KEY, null as never);
const fieldProps = useFormControlProps(() => ({
  id: props.id,
  "aria-describedby": props.ariaDescribedby,
}));

// One source of truth: the format in use decides the seconds column
const format = computed(() =>
  resolveTimeFormat(props.format, props.showSecond),
);
const showSecond = computed(() => formatHasSeconds(format.value));
const disabled = computed(() => props.disabled ?? fc?.disabled.value ?? false);
const readOnly = computed(() => props.readOnly ?? fc?.readOnly.value ?? false);
const required = computed(() => props.required ?? fc?.required.value ?? false);
const invalid = computed(() => props.invalid ?? fc?.invalid.value ?? false);
const accessibleName = computed(
  () => props.label ?? props.ariaLabel ?? t("timePicker.label"),
);
// A FormLabel names the input unless `label` / `aria-label` is given; the
// aria-label stays as fallback (aria-labelledby wins when its target
// exists, and is ignored when it does not).
const labelledBy = computed(
  () =>
    props.ariaLabelledby ??
    (fc && !props.label && !props.ariaLabel ? fc.labelId.value : undefined),
);

const current = useControllable<Date | null>(props, "modelValue", {
  defaultProp: "defaultValue",
  fallback: null,
  name: "TimePicker",
});
const open = ref(false);
const setOpen = (next: boolean) => {
  if (next === open.value) return;
  open.value = next;
  emit("openChange", next);
};
const panelOpen = computed(
  () => open.value && !disabled.value && !readOnly.value,
);

// Text being typed; `null` = show the formatted value
const draft = ref<string | null>(null);
const field = ref<HTMLDivElement | null>(null);
const input = shallowRef<HTMLInputElement | null>(null);
const floating = ref<InstanceType<typeof FloatingPanel> | null>(null);
// Tab moves on within the enclosing layer (e.g. a Modal), else the page.
const tabContainer = useLayerParent();
// Opened from the keyboard: the panel moves focus into its first column.
const focusPanelOnOpen = ref(false);

onMounted(() => {
  input.value = field.value?.querySelector("input") ?? null;
});

function commit(next: Date | null) {
  current.value = next;
  emit("change", next ?? undefined);
}

function handleTimeChange(type: TimeUnitKind, val: number) {
  const next = new Date(current.value ?? startOfToday());
  if (type === "hour") next.setHours(val);
  else if (type === "minute") next.setMinutes(val);
  else if (type === "second") next.setSeconds(val);
  else {
    const hours = next.getHours() % 12;
    next.setHours(val === 1 ? hours + 12 : hours);
  }
  draft.value = null;
  commit(next);
}

function handleInputChange(text: string | number) {
  const value = String(text);
  draft.value = value;
  const parsed = parseTimeInput(value, format.value, {
    strict: true,
    base: current.value ?? undefined,
  });
  if (parsed) commit(parsed);
}

function handleInputBlur() {
  const text = draft.value;
  if (text === null) return;
  if (text.trim() === "") {
    if (current.value) commit(null);
  } else {
    const parsed = parseTimeInput(text, format.value, {
      strict: false,
      base: current.value ?? undefined,
    });
    if (parsed && parsed.getTime() !== current.value?.getTime()) commit(parsed);
  }
  draft.value = null;
}

function handleClear() {
  draft.value = null;
  commit(null);
  input.value?.focus();
}

function toggle() {
  if (disabled.value || readOnly.value) return;
  focusPanelOnOpen.value = false;
  setOpen(!open.value);
}

// Clicking the input toggles the panel. The handler only reacts to clicks
// on the inner <input>, which has its own keyboard support (ArrowDown opens
// the panel; Escape closes it), so the wrapper is not a control.
function handleRootClick(event: MouseEvent) {
  if (input.value && event.target === input.value) toggle();
}

function handleInputKeyDown(event: KeyboardEvent) {
  // ArrowDown (also Alt+ArrowDown) opens the panel and moves focus into it;
  // the portalled panel is otherwise unreachable by Tab.
  if (event.key !== "ArrowDown") return;
  event.preventDefault();
  if (!open.value) {
    focusPanelOnOpen.value = true;
    setOpen(true);
  } else {
    unref(floating.value?.element)
      ?.querySelector<HTMLElement>('[role="option"][tabindex="0"]')
      ?.focus();
  }
}

// The portalled panel sits after the input in the Tab order: Tab past its
// last column continues after the input (its clear button, then the rest of
// the page); Shift+Tab before its first column returns to the input.
function handlePanelKeyDown(event: KeyboardEvent) {
  const panel = event.currentTarget as HTMLElement;
  const el = input.value;
  if (
    !el ||
    event.key !== "Tab" ||
    event.altKey ||
    event.ctrlKey ||
    event.metaKey ||
    !tabLeavesPanel(panel, event.target as Element, event.shiftKey)
  )
    return;
  event.preventDefault();
  const next = event.shiftKey
    ? el
    : (adjacentTabbable(
        el,
        tabContainer?.value ?? el.ownerDocument.body,
        false,
      ) ?? el);
  next.focus();
  setOpen(false);
}

const displayValue = computed(
  () =>
    draft.value ??
    (current.value ? formatTime(current.value, format.value) : ""),
);
const showClear = computed(
  () =>
    props.clearable && !!current.value && !disabled.value && !readOnly.value,
);

defineExpose({
  /** The native `<input>` (the React `ref`) */
  input,
  focus: () => input.value?.focus(),
  blur: () => input.value?.blur(),
});
</script>

<template>
  <div
    ref="field"
    :class="styles.timePicker"
    v-bind="{
      ...$attrs,
      ...hooks('time-picker', 'root', {
        state: panelOpen ? 'open' : 'closed',
        disabled,
        readonly: readOnly,
        invalid,
        size,
      }),
    }"
    @click="handleRootClick"
  >
    <Input
      :model-value="displayValue"
      :placeholder="placeholder ?? t('timePicker.placeholder')"
      :id="fieldProps.id"
      :aria-label="accessibleName"
      :aria-labelledby="labelledBy"
      :aria-describedby="fieldProps['aria-describedby']"
      :aria-invalid="invalid || undefined"
      :aria-readonly="readOnly || undefined"
      :required="required"
      :read-only="readOnly"
      :name="name"
      :disabled="disabled"
      :size="size"
      @update:model-value="handleInputChange"
      @blur="handleInputBlur"
      @keydown="handleInputKeyDown"
    >
      <template #suffix>
        <button
          v-if="showClear"
          type="button"
          :class="[
            iconButtonStyles.iconButton,
            iconButtonStyles.neutral,
            iconButtonStyles['variant-ghost'],
            iconButtonStyles.small,
            iconButtonStyles.circle,
            styles.clearButton,
          ]"
          tabindex="0"
          :aria-label="t('timePicker.clear')"
          v-bind="
            hooks('icon-button', 'root', {
              state: 'inactive',
              disabled: false,
              loading: false,
              size: 'small',
              variant: 'ghost',
              color: 'neutral',
              shape: 'circle',
            })
          "
          @click="handleClear"
        >
          <span
            :class="iconButtonStyles.glyph"
            aria-hidden="true"
            v-bind="hooks('icon-button', 'icon')"
          >
            <IconX />
          </span>
        </button>
        <span
          v-else
          :class="styles.clockIcon"
          aria-hidden="true"
          v-bind="hooks('time-picker', 'icon')"
        >
          <IconClock />
        </span>
      </template>
    </Input>
    <FloatingPanel
      ref="floating"
      :open="panelOpen"
      :anchor="input"
      placement="bottom-start"
      :branches="() => [field]"
      :return-focus-on-escape="() => input"
      focusable
      role="dialog"
      tabindex="-1"
      :aria-label="accessibleName"
      :aria-labelledby="labelledBy"
      :class="styles.popup"
      v-bind="hooks('time-picker', 'content', { state: 'open' })"
      @dismiss="setOpen(false)"
      @keydown="handlePanelKeyDown"
    >
      <TimePickerPanel
        :value="current ?? startOfToday()"
        :has-value="current !== null"
        :format="format"
        :use12-hours="use12Hours"
        :show-second="showSecond"
        :hour-step="hourStep"
        :minute-step="minuteStep"
        :second-step="secondStep"
        :min-time="minTime"
        :max-time="maxTime"
        :visible="open"
        :focus-on-open="focusPanelOnOpen"
        @time-change="handleTimeChange"
      />
    </FloatingPanel>
  </div>
</template>

// packages/lib-core/src/components/TimePicker/TimePicker.tsx
import React, { useRef, useState } from "react";
import { cn } from "../../utils/cn";
import { IconClock, IconX } from "../../internal/icons";
import { Input } from "../Input";
import { IconButton } from "../IconButton";
import TimePickerPanel from "./TimePickerPanel";
import type { TimePickerProps } from "./types";
import {
  formatHasSeconds,
  formatTime,
  parseTimeInput,
  resolveTimeFormat,
  startOfToday,
} from "@minerva/core";
import { FloatingPanel } from "../../internal/FloatingPanel";
import { useLayerParent } from "../../internal/useDismissableLayer";
import { adjacentTabbable, tabLeavesPanel } from "../../internal/tabbing";
import { useControllableState } from "../../internal/useControllableState";
import { warnControlledProps } from "../../internal/devWarnings";
import { useMergedRefs } from "../../internal/mergeRefs";
import useI18n from "../../hooks/useI18n";
import { pickDataAttributes } from "../../internal/dataAttributes";
import {
  FormControlContext,
  useFormControlContext,
  useFormControlProps,
} from "../FormControl/context";
import { hooks } from "../../internal/stylingHooks";
import styles from "./timePicker.module.scss";

/**
 * TimePicker: type a time or pick hours / minutes / seconds from a panel.
 * Works controlled (`value` + `onChange`) or uncontrolled (`defaultValue`).
 * Inside a FormControl the input picks up the field's id, label,
 * description, invalid, required, disabled and read-only state (explicit
 * props win).
 */
const TimePicker = ({
  ref,
  value,
  defaultValue,
  onChange,
  format: formatProp = "HH:mm:ss",
  use12Hours = false,
  placeholder,
  label,
  "aria-label": ariaLabel,
  "aria-labelledby": ariaLabelledBy,
  "aria-describedby": ariaDescribedBy,
  id,
  required: requiredProp,
  readOnly: readOnlyProp,
  invalid: invalidProp,
  name = "time-picker",
  disabled: disabledProp,
  clearable = true,
  size = "medium",
  className = "",
  style,
  minTime,
  maxTime,
  showSecond: showSecondProp = true,
  hourStep = 1,
  minuteStep = 1,
  secondStep = 1,
  onOpenChange,
  ...rest
}: TimePickerProps) => {
  // One source of truth: the format in use decides the seconds column
  const format = resolveTimeFormat(formatProp, showSecondProp);
  const showSecond = formatHasSeconds(format);
  const { t } = useI18n();
  const fc = useFormControlContext();
  const fieldProps = useFormControlProps({
    id,
    "aria-describedby": ariaDescribedBy,
  });
  const disabled = disabledProp ?? fc?.disabled ?? false;
  const readOnly = readOnlyProp ?? fc?.readOnly ?? false;
  const required = requiredProp ?? fc?.required ?? false;
  const invalid = invalidProp ?? fc?.invalid ?? false;
  const accessibleName = label ?? ariaLabel ?? t("timePicker.label");
  // A FormLabel names the input unless `label` / `aria-label` is given; the
  // aria-label stays as fallback (aria-labelledby wins when its target
  // exists, and is ignored when it does not).
  const labelledBy =
    ariaLabelledBy ?? (fc && !label && !ariaLabel ? fc.labelId : undefined);
  if (process.env.NODE_ENV !== "production") {
    warnControlledProps("TimePicker", {
      prop: "value",
      value,
      defaultProp: "defaultValue",
      defaultValue,
      handlerProp: "onChange",
      handler: onChange,
      locked: disabled || readOnly,
      lockHint: "set `disabled` / `readOnly`",
    });
  }
  const [current, setCurrent] = useControllableState<Date | null>({
    value,
    defaultValue: defaultValue ?? null,
    name: "TimePicker",
  });
  const [open, setOpen] = useControllableState({
    defaultValue: false,
    onChange: onOpenChange,
    name: "TimePicker",
    prop: "open",
  });
  // Text being typed; `null` = show the formatted value
  const [draft, setDraft] = useState<string | null>(null);
  const [input, setInput] = useState<HTMLInputElement | null>(null);
  const [field, setField] = useState<HTMLDivElement | null>(null);
  const setInputRef = useMergedRefs<HTMLInputElement>(setInput, ref);
  const panelRef = useRef<HTMLDivElement>(null);
  // Tab moves on within the enclosing layer (e.g. a Modal), else the page.
  const tabContainer = useLayerParent();
  // Opened from the keyboard: the panel moves focus into its first column.
  const [focusPanelOnOpen, setFocusPanelOnOpen] = useState(false);

  const commit = (next: Date | null) => {
    setCurrent(next);
    onChange?.(next ?? undefined);
  };

  const handleTimeChange = (
    type: "hour" | "minute" | "second" | "ampm",
    val: number,
  ) => {
    const next = new Date(current ?? startOfToday());
    if (type === "hour") next.setHours(val);
    else if (type === "minute") next.setMinutes(val);
    else if (type === "second") next.setSeconds(val);
    else {
      const hours = next.getHours() % 12;
      next.setHours(val === 1 ? hours + 12 : hours);
    }
    setDraft(null);
    commit(next);
  };

  const handleInputChange = (text: string) => {
    setDraft(text);
    const parsed = parseTimeInput(text, format, {
      strict: true,
      base: current ?? undefined,
    });
    if (parsed) commit(parsed);
  };

  const handleInputBlur = () => {
    if (draft === null) return;
    if (draft.trim() === "") {
      if (current) commit(null);
    } else {
      const parsed = parseTimeInput(draft, format, {
        strict: false,
        base: current ?? undefined,
      });
      if (parsed && parsed.getTime() !== current?.getTime()) commit(parsed);
    }
    setDraft(null);
  };

  const handleClear = () => {
    setDraft(null);
    commit(null);
    input?.focus();
  };

  const toggle = () => {
    if (disabled || readOnly) return;
    setFocusPanelOnOpen(false);
    setOpen((prev) => !prev);
  };

  // The portalled panel sits after the input in the Tab order: Tab past its
  // last column continues after the input (its clear button, then the rest
  // of the page); Shift+Tab before its first column returns to the input.
  const handlePanelKeyDown = (event: React.KeyboardEvent<HTMLDivElement>) => {
    const panel = event.currentTarget;
    if (
      !input ||
      event.key !== "Tab" ||
      event.altKey ||
      event.ctrlKey ||
      event.metaKey ||
      !tabLeavesPanel(panel, event.target as Element, event.shiftKey)
    )
      return;
    event.preventDefault();
    const next = event.shiftKey
      ? input
      : (adjacentTabbable(
          input,
          tabContainer ?? input.ownerDocument.body,
          false,
        ) ?? input);
    next.focus();
    setOpen(false);
  };

  const displayValue = draft ?? (current ? formatTime(current, format) : "");

  return (
    // Clicking the input toggles the panel. The handler only reacts to clicks
    // on the inner <input>, which has its own keyboard support (ArrowDown
    // opens the panel; Escape closes it), so the wrapper is not a control.
    // eslint-disable-next-line jsx-a11y/click-events-have-key-events, jsx-a11y/no-static-element-interactions
    <div
      {...pickDataAttributes(rest)}
      ref={setField}
      className={cn(styles.timePicker, className)}
      style={style}
      onClick={(e) => {
        if (e.target === input) toggle();
      }}
      {...hooks("time-picker", "root", {
        state: open && !disabled && !readOnly ? "open" : "closed",
        disabled,
        readonly: readOnly,
        invalid,
        size,
      })}
    >
      {/* The field state is resolved here (explicit props win over the
          FormControl), so the inner Input must not merge it again. */}
      <FormControlContext.Provider value={null}>
        <Input
          ref={setInputRef}
          value={displayValue}
          placeholder={placeholder ?? t("timePicker.placeholder")}
          id={fieldProps.id}
          aria-label={accessibleName}
          aria-labelledby={labelledBy}
          aria-describedby={fieldProps["aria-describedby"]}
          aria-invalid={invalid || undefined}
          aria-readonly={readOnly || undefined}
          required={required}
          readOnly={readOnly}
          onChange={(e) => handleInputChange(e.target.value)}
          onBlur={handleInputBlur}
          onKeyDown={(e) => {
            // ArrowDown (also Alt+ArrowDown) opens the panel and moves focus
            // into it; the portalled panel is otherwise unreachable by Tab.
            if (e.key !== "ArrowDown") return;
            e.preventDefault();
            if (!open) {
              setFocusPanelOnOpen(true);
              setOpen(true);
            } else {
              panelRef.current
                ?.querySelector<HTMLElement>('[role="option"][tabindex="0"]')
                ?.focus();
            }
          }}
          name={name}
          disabled={disabled}
          size={size}
          suffix={
            clearable && current && !disabled && !readOnly ? (
              <IconButton
                icon={<IconX aria-hidden focusable={false} />}
                size="small"
                aria-label={t("timePicker.clear")}
                onClick={handleClear}
                className={styles.clearButton}
              />
            ) : (
              <span
                className={styles.clockIcon}
                aria-hidden="true"
                {...hooks("time-picker", "icon")}
              >
                <IconClock />
              </span>
            )
          }
        />
      </FormControlContext.Provider>
      <FloatingPanel
        ref={panelRef}
        open={open && !disabled && !readOnly}
        anchor={input}
        placement="bottom-start"
        // the field (input + clear button) is part of the popup layer
        branches={() => [field]}
        onDismiss={() => setOpen(false)}
        returnFocusOnEscape={() => input}
        focusable
        role="dialog"
        tabIndex={-1}
        aria-label={accessibleName}
        aria-labelledby={labelledBy}
        className={styles.popup}
        onKeyDown={handlePanelKeyDown}
        {...hooks("time-picker", "content", { state: "open" })}
      >
        <TimePickerPanel
          value={current ?? startOfToday()}
          hasValue={current !== null}
          format={format}
          use12Hours={use12Hours}
          showSecond={showSecond}
          hourStep={hourStep}
          minuteStep={minuteStep}
          secondStep={secondStep}
          minTime={minTime}
          maxTime={maxTime}
          onTimeChange={handleTimeChange}
          visible={open}
          focusOnOpen={focusPanelOnOpen}
        />
      </FloatingPanel>
    </div>
  );
};

export default React.memo(TimePicker);
