// packages/lib-web-components/src/components/command/command.ts
import { css, html, nothing, type PropertyValues } from "lit";
import { property, query, state } from "lit/decorators.js";
import { live } from "lit/directives/live.js";
import modalStyles from "@lib-core-styles/components/Modal/modal.module.scss?inline";
import styles from "@lib-core-styles/components/Command/command.module.scss?inline";
import { DismissableLayerController } from "../../controllers/dismissable-layer";
import { popoverResetStyles } from "../../controllers/floating-layer";
import { FocusScopeController } from "../../controllers/focus-scope";
import { ModalController } from "../../controllers/modal";
import { DEV, devWarn } from "../../internal/dev";
import { hideTopLayer, showTopLayer } from "../../internal/dom";
import { LocaleController } from "../../internal/locale";
import { MinervaElement, hostStyles } from "../../internal/minerva-element";
import { PresenceController } from "../../internal/presence";
import {
  commandSearchText,
  isEditableTarget,
  matchesShortcut,
  normalizeSearchText,
  normalizeShortcuts,
} from "@minerva/core";

export { matchesShortcut, normalizeShortcuts };
/** Keyboard event fields read by `matchesShortcut`. */
export type { ShortcutEvent as CommandShortcutEvent } from "@minerva/core";
import { sharedStyles } from "../../internal/styles";

/** One entry of the command palette (same shape as lib-core's `CommandItem`). */
export interface CommandItem {
  /** Unique id, passed back as `value` in `minerva-select` */
  id: string;
  /** Main label */
  title: string;
  /** Secondary line below the title */
  description?: string;
  /** Group name, shown as a badge and matched by the search */
  group?: string;
  /** Extra search terms (not displayed) */
  keywords?: string;
  /** Hides the item from the results */
  disabled?: boolean;
}

/** Why the palette asked to open / close (`minerva-open-change` detail) */
export type CommandOpenChangeReason =
  "shortcut" | "select" | "escape" | "outside";

/** `shortcut` attribute: comma-separated list ("mod+k, /"). */
const shortcutConverter = {
  fromAttribute: (value: string | null) =>
    value === null
      ? undefined
      : value
          .split(",")
          .map((part) => part.trim())
          .filter(Boolean),
  toAttribute: (value: string | string[] | undefined) =>
    Array.isArray(value) ? value.join(", ") : value,
};

/**
 * Command palette (`<CommandDialog>` of lib-core): a searchable list of
 * commands in a modal dialog. Type to filter (title, description, group and
 * keywords), move with ArrowUp / ArrowDown (Home / End while the query is
 * empty) over the results (combobox + listbox with `aria-activedescendant`),
 * choose with Enter or a click; Escape (topmost layer only) or an overlay
 * click closes it. Focus moves to the search input, is trapped, and returns
 * to the opener on close. An optional global `shortcut` (e.g. "mod+k")
 * opens it.
 *
 * @summary Searchable command palette in a modal, with a global shortcut.
 * @tag minerva-command-dialog
 * @csspart overlay - The backdrop
 * @csspart panel - The dialog panel (`role="dialog"`)
 * @csspart header - The title row
 * @csspart description - The description
 * @csspart search - The search field wrapper
 * @csspart input - The search input (`role="combobox"`)
 * @csspart listbox - The results list (`role="listbox"`)
 * @csspart item - A result (`role="option"`)
 * @csspart empty - The empty state
 * @fires minerva-select - A command was chosen (`detail: { value, item }`, `value` = the item's `id`); the palette then closes
 * @fires minerva-open-change - The user asked to open (shortcut) / close (`detail: { open, reason }`); cancelable: `preventDefault()` keeps the current state
 * @fires minerva-after-open - The palette is open and focus moved to the search input
 * @fires minerva-after-close - The palette finished closing (after its exit animation)
 */
export class MinervaCommandDialog extends MinervaElement {
  static override tagName = "minerva-command-dialog";
  static override styles = [
    hostStyles,
    popoverResetStyles,
    css`
      :host {
        display: contents;
      }
    `,
    sharedStyles(modalStyles),
    sharedStyles(styles),
  ];

  /** Whether the palette is open */
  @property({ type: Boolean, reflect: true })
  open = false;

  /** Commands to search (disabled items are never shown) */
  @property({ attribute: false })
  items: CommandItem[] = [];

  /** Title of the dialog (default: localized "Command palette") */
  @property()
  label?: string;

  /** Description of the palette (default: a localized hint) */
  @property()
  description?: string;

  /** Placeholder (and accessible name) of the search input (default: a localized hint) */
  @property()
  placeholder?: string;

  /** Text shown when nothing matches (default: localized "No matching results") */
  @property({ attribute: "empty-text" })
  emptyText?: string;

  /** Shortcut hint rendered as `<kbd>` next to the title, e.g. "⌘K" */
  @property({ attribute: "shortcut-label" })
  shortcutLabel?: string;

  /**
   * Global keyboard shortcut(s) that open the palette, e.g. "mod+k" (Cmd+K
   * on macOS, Ctrl+K elsewhere). Modifiers: mod, ctrl, meta/cmd, shift,
   * alt/option. The attribute takes a comma-separated list ("mod+k, /").
   */
  @property({ converter: shortcutConverter })
  shortcut?: string | string[];

  /** Maximum number of results shown */
  @property({ type: Number, attribute: "max-results" })
  maxResults = 12;

  /** Accessible label of the results list (default: localized "Command results") */
  @property({ attribute: "results-label" })
  resultsLabel?: string;

  /** Key hint at the end of the search input (default: localized "Enter") */
  @property({ attribute: "enter-label" })
  enterLabel?: string;

  @state()
  private query = "";

  @state()
  private activeIndex = 0;

  @query(".content")
  private panel?: HTMLElement;

  @query(".overlay")
  private overlay?: HTMLElement;

  private readonly locale = new LocaleController(this);
  private readonly presence = new PresenceController(this, () => this.panel);
  private readonly modal = new ModalController(this);
  private readonly focusScope = new FocusScopeController(this, () => ({
    trapped: true,
    loop: true,
    restoreFocus: true,
  }));
  private readonly layer = new DismissableLayerController(this, () => ({
    disableOutsidePointerEvents: true,
    // Focus is trapped: never dismiss on focus outside (`focusin` is not
    // cancelable, so preventDefault() would not stop the dismissal).
    onFocusOutside: () => false,
    onEscapeKeyDown: () => {
      this.reason = "escape";
    },
    onPointerDownOutside: () => {
      this.reason = "outside";
    },
    onDismiss: () => this.requestOpenChange(false, this.reason),
  }));
  private reason: CommandOpenChangeReason = "outside";
  private wasPresent = false;

  /** Opens the palette */
  show(): void {
    this.open = true;
  }

  /** Closes the palette */
  hide(): void {
    this.open = false;
  }

  /** The visible results: enabled items matching the query, capped at `maxResults`. */
  private get results(): CommandItem[] {
    const q = normalizeSearchText(this.query);
    return (Array.isArray(this.items) ? this.items : [])
      .filter((item) => !item.disabled)
      .filter(
        (item) =>
          !q || normalizeSearchText(commandSearchText(item)).includes(q),
      )
      .slice(0, Math.max(0, this.maxResults));
  }

  /** Asks to change `open`; listeners can cancel `minerva-open-change`. */
  private requestOpenChange(open: boolean, reason: CommandOpenChangeReason) {
    if (open === this.open) return;
    const allowed = this.emit(
      "minerva-open-change",
      { open, reason },
      { cancelable: true },
    );
    if (allowed) this.open = open;
  }

  private select(item: CommandItem) {
    this.emit("minerva-select", { value: item.id, item });
    this.requestOpenChange(false, "select");
  }

  /** Global shortcut (capture phase, like lib-core). */
  private readonly handleShortcut = (event: KeyboardEvent) => {
    const shortcuts = normalizeShortcuts(this.shortcut);
    if (shortcuts.length === 0) return;
    // A shortcut without Ctrl / Meta / Alt (e.g. "/") is a printable key:
    // while typing in a text field (including the palette's own search, in
    // a shadow root: hence the composed path) it must reach the field.
    const target = event.composedPath()[0] ?? event.target;
    const editable =
      isEditableTarget(target) &&
      !event.ctrlKey &&
      !event.metaKey &&
      !event.altKey;
    if (editable || event.isComposing) return;
    if (!shortcuts.some((value) => matchesShortcut(event, value))) return;
    event.preventDefault();
    event.stopPropagation();
    this.requestOpenChange(true, "shortcut");
  };

  private handleKeyDown(event: KeyboardEvent) {
    const results = this.results;
    const last = Math.max(results.length - 1, 0);
    const moves: Record<string, (index: number) => number> = {
      ArrowDown: (index) => Math.min(index + 1, last),
      ArrowUp: (index) => Math.max(index - 1, 0),
      Home: () => 0,
      End: () => last,
    };
    const move = moves[event.key];
    if (move && (event.key.startsWith("Arrow") || !this.query)) {
      event.preventDefault();
      this.activeIndex = move(Math.min(this.activeIndex, last));
      return;
    }
    const active = results[this.activeIndex];
    if (event.key === "Enter" && active && !event.isComposing) {
      event.preventDefault();
      this.select(active);
    }
  }

  private handleInput(event: Event) {
    this.query = (event.target as HTMLInputElement).value;
    this.activeIndex = 0;
  }

  override connectedCallback(): void {
    super.connectedCallback();
    document.addEventListener("keydown", this.handleShortcut, true);
  }

  override disconnectedCallback(): void {
    super.disconnectedCallback();
    document.removeEventListener("keydown", this.handleShortcut, true);
    hideTopLayer(this.panel);
    hideTopLayer(this.overlay);
  }

  protected override willUpdate(changed: PropertyValues<this>): void {
    if (changed.has("open")) {
      this.presence.sync(this.open);
      // Every opening starts with an empty query and the first result.
      if (this.open) {
        this.query = "";
        this.activeIndex = 0;
      }
    }
    if (changed.has("items") && DEV) this.checkItems();
    const count = this.results.length;
    if (this.activeIndex > 0 && this.activeIndex >= count) {
      this.activeIndex = Math.max(count - 1, 0);
    }
  }

  private checkItems() {
    if (!Array.isArray(this.items)) {
      devWarn(
        MinervaCommandDialog.tagName,
        "`items` must be an array of { id, title, ... } objects.",
      );
      return;
    }
    const seen = new Set<string>();
    for (const item of this.items) {
      if (seen.has(item.id)) {
        devWarn(
          MinervaCommandDialog.tagName,
          `duplicate item id "${item.id}": ids identify the chosen command in minerva-select and must be unique.`,
        );
      }
      seen.add(item.id);
    }
  }

  protected override updated(changed: PropertyValues): void {
    const present = this.open || this.presence.present;
    if (changed.has("open")) {
      const panel = this.panel;
      if (this.open && panel) {
        showTopLayer(this.overlay);
        showTopLayer(panel);
        this.modal.activate(this);
        this.layer.activate(panel);
        this.focusScope.activate(panel);
        this.emit("minerva-after-open");
      } else if (!this.open) {
        this.focusScope.deactivate();
        this.layer.deactivate();
        this.modal.deactivate();
      }
    }
    if (this.open && (changed.has("activeIndex") || changed.has("query"))) {
      this.renderRoot
        .querySelector(`#option-${this.activeIndex}`)
        ?.scrollIntoView?.({ block: "nearest" });
    }
    if (this.wasPresent && !present) this.afterClose();
    this.wasPresent = present;
  }

  private afterClose() {
    hideTopLayer(this.panel);
    hideTopLayer(this.overlay);
    this.emit("minerva-after-close");
  }

  protected override render() {
    const present = this.open || this.presence.present;
    if (!present) return nothing;
    const t = this.locale.t;
    const state = this.open ? "open" : "closed";
    const results = this.results;
    const activeId = results[this.activeIndex]
      ? `option-${this.activeIndex}`
      : undefined;
    const placeholder = this.placeholder ?? t("command.placeholder");
    return html`<div
        part="overlay"
        class="overlay"
        popover="manual"
        data-state=${state}
        aria-hidden="true"
      ></div>
      <div
        part="panel"
        class="content large dialog"
        popover="manual"
        role="dialog"
        aria-modal="true"
        aria-labelledby="title"
        aria-describedby="description"
        tabindex="-1"
        data-state=${state}
      >
        <p id="description" class="description" part="description">
          ${this.description ?? t("command.description")}
        </p>
        <div id="title" class="header" part="header">
          <span>${this.label ?? t("command.title")}</span>
          ${
            this.shortcutLabel
              ? html`<kbd class="kbd">${this.shortcutLabel}</kbd>`
              : nothing
          }
        </div>
        <div class="search" part="search">
          <span class="searchIcon" aria-hidden="true">⌕</span>
          <input
            part="input"
            class="input"
            type="text"
            role="combobox"
            aria-label=${placeholder}
            aria-autocomplete="list"
            aria-expanded="true"
            aria-controls="results"
            aria-activedescendant=${activeId ?? nothing}
            autocomplete="off"
            spellcheck="false"
            placeholder=${placeholder}
            .value=${live(this.query)}
            @input=${this.handleInput}
            @keydown=${this.handleKeyDown}
          />
          <kbd class="enterHint" aria-hidden="true"
            >${this.enterLabel ?? t("command.enter")}</kbd
          >
        </div>
        <div
          id="results"
          part="listbox"
          class="results"
          role="listbox"
          aria-label=${this.resultsLabel ?? t("command.results")}
        >
          ${
            results.length === 0
              ? html`<div class="empty" part="empty">
                  ${this.emptyText ?? t("command.empty")}
                </div>`
              : results.map((item, index) => {
                  const active = index === this.activeIndex;
                  return html`<button
                    id=${`option-${index}`}
                    part="item"
                    type="button"
                    role="option"
                    tabindex="-1"
                    aria-selected=${active ? "true" : "false"}
                    data-active=${active ? "true" : nothing}
                    class="item"
                    @mouseenter=${() => (this.activeIndex = index)}
                    @click=${() => this.select(item)}
                  >
                    <span class="copy"
                      ><strong>${item.title}</strong>${
                        item.description
                          ? html`<small>${item.description}</small>`
                          : nothing
                      }</span
                    >${
                      item.group
                        ? html`<span class="group">${item.group}</span>`
                        : nothing
                    }
                  </button>`;
                })
          }
        </div>
      </div>`;
  }
}

declare global {
  interface HTMLElementTagNameMap {
    "minerva-command-dialog": MinervaCommandDialog;
  }
}

// packages/lib-core/src/components/Command/Command.tsx
import {
  useEffect,
  useId,
  useMemo,
  useState,
  type KeyboardEvent as ReactKeyboardEvent,
  type ReactNode,
} from "react";
import {
  commandSearchText,
  isEditableTarget,
  matchesShortcut,
  normalizeSearchText,
  normalizeShortcuts,
} from "@minerva/core";
import useI18n from "../../hooks/useI18n";
import { useControllableState } from "../../internal/useControllableState";
import { warnControlledProps } from "../../internal/devWarnings";
import { cn } from "../../utils/cn";
import {
  DialogContent,
  DialogDescription,
  DialogRoot,
  DialogTitle,
} from "../../internal/Dialog";
import { hooks } from "../../internal/stylingHooks";
import modalStyles from "../Modal/modal.module.scss";
import type { CommandDialogProps, CommandItem } from "./types";
import styles from "./command.module.scss";

export { matchesShortcut, normalizeShortcuts };

interface CommandPanelProps {
  items: CommandItem[];
  maxResults: number;
  filter?: CommandDialogProps["filter"];
  placeholder: string;
  emptyText: ReactNode;
  resultsLabel: string;
  enterLabel: ReactNode;
  onSelect: (item: CommandItem) => void;
}

/**
 * Search input + results. Mounted only while the dialog is open, so every
 * opening starts with an empty query and the first result active.
 */
const CommandPanel = ({
  items,
  maxResults,
  filter,
  placeholder,
  emptyText,
  resultsLabel,
  enterLabel,
  onSelect,
}: CommandPanelProps) => {
  const [query, setQuery] = useState("");
  const [activeIndex, setActiveIndex] = useState(0);
  const baseId = useId();
  const listId = `${baseId}-results`;

  const results = useMemo(() => {
    const enabled = items.filter((item) => !item.disabled);
    const trimmed = query.trim();
    if (!trimmed) return enabled.slice(0, maxResults);
    if (filter) return filter(enabled, trimmed).slice(0, maxResults);
    const q = normalizeSearchText(trimmed);
    return enabled
      .filter((item) =>
        normalizeSearchText(commandSearchText(item)).includes(q),
      )
      .slice(0, maxResults);
  }, [filter, items, maxResults, query]);

  const optionId = (index: number) => `${baseId}-option-${index}`;
  const activeId = results[activeIndex] ? optionId(activeIndex) : undefined;

  useEffect(() => {
    if (!activeId) return;
    document.getElementById(activeId)?.scrollIntoView?.({ block: "nearest" });
  }, [activeId]);

  const onKeyDown = (event: ReactKeyboardEvent<HTMLInputElement>) => {
    const last = Math.max(results.length - 1, 0);
    const moves: Record<string, (index: number) => number> = {
      ArrowDown: (index) => Math.min(index + 1, last),
      ArrowUp: (index) => Math.max(index - 1, 0),
      Home: () => 0,
      End: () => last,
    };
    const move = moves[event.key];
    if (move && (event.key.startsWith("Arrow") || !query)) {
      event.preventDefault();
      setActiveIndex(move);
      return;
    }
    if (event.key === "Enter" && results[activeIndex]) {
      event.preventDefault();
      onSelect(results[activeIndex]);
    }
  };

  return (
    <>
      <div className={styles.search} {...hooks("command-dialog", "search")}>
        <span className={styles.searchIcon} aria-hidden="true">
          ⌕
        </span>
        <input
          className={styles.input}
          type="text"
          role="combobox"
          aria-label={placeholder}
          aria-autocomplete="list"
          aria-expanded
          aria-controls={listId}
          aria-activedescendant={activeId}
          autoComplete="off"
          spellCheck={false}
          value={query}
          placeholder={placeholder}
          onChange={(event) => {
            setQuery(event.target.value);
            setActiveIndex(0);
          }}
          onKeyDown={onKeyDown}
          {...hooks("command-dialog", "input")}
        />
        <kbd className={styles.enterHint} aria-hidden="true">
          {enterLabel}
        </kbd>
      </div>
      <div
        id={listId}
        className={styles.results}
        role="listbox"
        aria-label={resultsLabel}
        {...hooks("command-dialog", "list")}
      >
        {results.length === 0 ? (
          <div className={styles.empty} {...hooks("command-dialog", "empty")}>
            {emptyText}
          </div>
        ) : (
          results.map((item, index) => {
            const active = index === activeIndex;
            return (
              <button
                id={optionId(index)}
                key={item.id}
                type="button"
                role="option"
                // Keyboard navigation happens in the combobox input.
                tabIndex={-1}
                aria-selected={active}
                data-active={active || undefined}
                className={styles.item}
                onMouseEnter={() => setActiveIndex(index)}
                onClick={() => onSelect(item)}
                {...hooks("command-dialog", "item")}
              >
                <span className={styles.copy}>
                  <strong>{item.title}</strong>
                  {item.description && <small>{item.description}</small>}
                </span>
                {item.group && (
                  <span className={styles.group}>{item.group}</span>
                )}
              </button>
            );
          })
        )}
      </div>
    </>
  );
};

/**
 * CommandDialog: a searchable command palette in a modal. Filter with the
 * input, move with ArrowUp / ArrowDown, choose with Enter or a click. An
 * optional global `shortcut` (e.g. "mod+k") opens it.
 */
export const CommandDialog = ({
  open: openProp,
  defaultOpen,
  onOpenChange,
  items,
  onSelect,
  title,
  description,
  placeholder,
  emptyText,
  shortcutLabel,
  shortcut,
  maxResults = 12,
  filter,
  resultsLabel,
  enterLabel,
  className,
}: CommandDialogProps) => {
  const { t } = useI18n();
  if (process.env.NODE_ENV !== "production") {
    warnControlledProps("CommandDialog", {
      prop: "open",
      value: openProp,
      defaultProp: "defaultOpen",
      defaultValue: defaultOpen,
      handlerProp: "onOpenChange",
      handler: onOpenChange,
    });
  }
  const [open, setOpen] = useControllableState({
    value: openProp,
    defaultValue: defaultOpen ?? false,
    onChange: onOpenChange,
    name: "CommandDialog",
    prop: "open",
  });

  // Stable key so an inline array literal does not re-register the listener.
  const shortcutKey = normalizeShortcuts(shortcut).join("\n");
  useEffect(() => {
    if (!shortcutKey) return;
    const shortcuts = shortcutKey.split("\n");
    const onKeyDown = (event: KeyboardEvent) => {
      // A shortcut without Ctrl / Meta / Alt (e.g. "/") is a printable key:
      // while typing in a text field (including the palette's own search)
      // it must reach the field instead of being swallowed.
      const editable =
        isEditableTarget(event.target) &&
        !event.ctrlKey &&
        !event.metaKey &&
        !event.altKey;
      if (editable || event.isComposing) return;
      if (!shortcuts.some((value) => matchesShortcut(event, value))) return;
      event.preventDefault();
      event.stopPropagation();
      setOpen(true);
    };
    document.addEventListener("keydown", onKeyDown, { capture: true });
    return () => document.removeEventListener("keydown", onKeyDown, true);
  }, [setOpen, shortcutKey]);

  const select = (item: CommandItem) => {
    onSelect(item);
    setOpen(false);
  };

  return (
    // The markup of a large <Modal> without close button (same styles),
    // with its own hooks.
    <DialogRoot
      componentName="CommandDialog"
      open={open}
      onOpenChange={setOpen}
    >
      <DialogContent
        overlayClassName={modalStyles.overlay}
        overlayAttributes={hooks("command-dialog", "overlay")}
        className={cn(
          modalStyles.content,
          modalStyles.large,
          styles.dialog,
          className,
        )}
        {...hooks("command-dialog", "content")}
      >
        <DialogDescription
          className={modalStyles.description}
          {...hooks("command-dialog", "description")}
        >
          {description ?? t("command.description")}
        </DialogDescription>
        <DialogTitle asChild>
          <div
            className={cn(modalStyles.header, styles.header)}
            {...hooks("command-dialog", "header")}
          >
            <span>{title ?? t("command.title")}</span>
            {shortcutLabel && <kbd className={styles.kbd}>{shortcutLabel}</kbd>}
          </div>
        </DialogTitle>
        <CommandPanel
          items={items}
          maxResults={maxResults}
          filter={filter}
          placeholder={placeholder ?? t("command.placeholder")}
          emptyText={emptyText ?? t("command.empty")}
          resultsLabel={resultsLabel ?? t("command.results")}
          enterLabel={enterLabel ?? t("command.enter")}
          onSelect={select}
        />
      </DialogContent>
    </DialogRoot>
  );
};

export default CommandDialog;
