// packages/vue/src/components/ResponsiveGrid/GridItem.vue
<script setup lang="ts">
/**
 * GridItem: a cell of a ResponsiveGrid (or any CSS grid). `fullWidth` spans
 * the whole row; `asChild` applies the item to its single child without a
 * wrapper.
 */
import { computed, useAttrs } from "vue";
import styles from "@react-styles/components/ResponsiveGrid/responsiveGrid.module.scss";
import { hooks } from "../../internal/hooks";
import { Slot } from "../../internal/Slot";
import type { GridItemProps } from "./types";

defineOptions({ name: "GridItem", inheritAttrs: false });

const props = withDefaults(defineProps<GridItemProps>(), {
  fullWidth: false,
  asChild: false,
});

defineSlots<{ default?: () => unknown }>();

const attrs = useAttrs();
const classes = computed(() => [
  styles.item,
  props.fullWidth && styles.fullWidth,
]);
const rootAttrs = computed(() => ({ ...attrs, ...hooks("grid-item", "root") }));
</script>

<template>
  <component :is="asChild ? Slot : 'div'" :class="classes" v-bind="rootAttrs">
    <slot />
  </component>
</template>

// packages/lib-core/src/components/ResponsiveGrid/GridItem.tsx
import { Slot } from "../../internal/Slot";
import { cn } from "../../utils/cn";
import type { GridItemProps } from "./types";
import styles from "./responsiveGrid.module.scss";
import { hooks } from "../../internal/stylingHooks";

/**
 * GridItem: a cell of a ResponsiveGrid (or any CSS grid). `fullWidth` spans the
 * whole row; `asChild` applies the item to its single child without a wrapper.
 */
const GridItem = ({
  fullWidth = false,
  asChild = false,
  className,
  ...rest
}: GridItemProps) => {
  const Component = asChild ? Slot : "div";
  return (
    <Component
      className={cn(styles.item, fullWidth && styles.fullWidth, className)}
      {...rest}
      {...hooks("grid-item", "root")}
    />
  );
};

export default GridItem;
