// packages/angular/src/components/drawer/drawer.ts
import { NgTemplateOutlet } from "@angular/common";
import {
  ChangeDetectionStrategy,
  Component,
  DestroyRef,
  Directive,
  ViewEncapsulation,
  booleanAttribute,
  computed,
  forwardRef,
  inject,
  input,
  output,
} from "@angular/core";
import { cn } from "@minerva/core";
import { hasContent, templateOf, type MnContent } from "../../internal/content";
import {
  DIALOG_TRIGGER_HOST,
  MN_DIALOG,
  MnDialogBase,
  registerTrigger,
  type DialogContext,
} from "../../internal/dialog";
import { dialogLifecycle } from "../../internal/dialog-lifecycle";
import { MnHook } from "../../internal/hooks";
import { MnIcon } from "../../internal/icon";
import { MnPortal } from "../../internal/portal";
import { drawerStyles as s } from "../../internal/styles";

/** Edge of the viewport the drawer slides in from */
export type DrawerSide = "left" | "right" | "top" | "bottom";

/** Size preset: width for left / right drawers, height for top / bottom ones */
export type DrawerSize = "small" | "medium" | "large" | "full";

/**
 * Drawer: a side panel dialog sliding in from one edge, with title,
 * description and close button. The panel is portalled (theme-scoped) over
 * an overlay: focus moves in and is trapped, Escape (topmost dialog only)
 * and an overlay click close it, page scroll is locked, the rest of the page
 * is hidden from assistive technology, and focus returns to the opener on
 * close. Renders nothing on the server.
 *
 * Content: usually `<mn-drawer-body>` + `<mn-drawer-footer>`;
 * `<mn-drawer-header>` for a rich title. Open it with `[(open)]` or a
 * `[mnDrawerTrigger]` button; `[modal]="false"` makes it non-modal (no
 * overlay, closes on outside click / focus). Without `description` a
 * visually hidden generic description is rendered.
 *
 * @example
 * <button mnButton [mnDrawerTrigger]="drawer">Filters</button>
 * <mn-drawer #drawer="mnDrawer" title="Filters" side="left">
 *   <mn-drawer-body>...</mn-drawer-body>
 *   <mn-drawer-footer><button mnButton mnDrawerClose>Done</button></mn-drawer-footer>
 * </mn-drawer>
 */
@Component({
  selector: "mn-drawer",
  exportAs: "mnDrawer",
  imports: [MnHook, MnIcon, MnPortal, NgTemplateOutlet],
  encapsulation: ViewEncapsulation.None,
  changeDetection: ChangeDetectionStrategy.OnPush,
  providers: [{ provide: MN_DIALOG, useExisting: forwardRef(() => MnDrawer) }],
  host: {
    style: "display: contents",
    "[attr.title]": "null",
    "[attr.role]": "null",
  },
  template: `
    @if (mounted()) {
      <ng-container *mnPortal>
        @if (modal()) {
          <div
            [class]="overlayClass()"
            style="pointer-events: auto"
            aria-hidden="true"
            mnHook="drawer"
            mnPart="overlay"
            [mnStates]="{ state: state() }"
          ></div>
        }
        <div
          #panel
          [attr.id]="contentId"
          [attr.role]="role()"
          [attr.aria-modal]="modal() ? 'true' : null"
          [attr.aria-labelledby]="
            hasTitle() || hasContent(title()) ? titleId : null
          "
          [attr.aria-describedby]="descriptionId"
          tabindex="-1"
          [class]="contentClass()"
          mnHook="drawer"
          mnPart="content"
          [mnStates]="{ state: state(), side: side(), size: size() }"
        >
          <p
            [attr.id]="descriptionId"
            [class]="
              hasContent(description()) ? s.description : s.visuallyHidden
            "
            mnHook="drawer"
            mnPart="description"
          >
            @if (templateOf(description()); as tpl) {
              <ng-container [ngTemplateOutlet]="tpl" />
            } @else if (hasContent(description())) {
              {{ description() }}
            } @else {
              {{ hiddenDescription() ?? scope.t("drawer.description") }}
            }
          </p>
          @if (hasContent(title())) {
            <div
              [attr.id]="titleId"
              [class]="s.header"
              mnHook="drawer"
              mnPart="header"
            >
              @if (templateOf(title()); as tpl) {
                <ng-container [ngTemplateOutlet]="tpl" />
              } @else {
                {{ title() }}
              }
            </div>
          }
          <ng-content />
          @if (!hideCloseButton()) {
            <button
              type="button"
              [class]="s.close"
              [attr.aria-label]="closeLabel() ?? scope.t('drawer.close')"
              (click)="setOpen(false)"
              mnHook="drawer"
              mnPart="close-button"
            >
              <svg mnIcon="X" size="16" aria-hidden="true"></svg>
            </button>
          }
        </div>
      </ng-container>
    }
  `,
})
export class MnDrawer extends MnDialogBase {
  /**
   * Edge the panel slides in from
   * @default "right"
   */
  readonly side = input<DrawerSide>("right");
  /**
   * Size preset
   * @default "medium"
   */
  readonly size = input<DrawerSize>("medium");
  /** Title, the drawer's accessible name (string or template) */
  readonly title = input<MnContent>(undefined);
  /**
   * Visible description below the title (accessible description). Without
   * it a visually hidden generic description is rendered.
   */
  readonly description = input<MnContent>(undefined);
  /**
   * Text of the visually hidden description rendered when `description` is
   * not set (default: the localized "Drawer content")
   */
  readonly hiddenDescription = input<string | undefined>(undefined);
  /**
   * Hides the close (×) button
   * @default false
   */
  readonly hideCloseButton = input(false, { transform: booleanAttribute });
  /** Accessible label of the close button (default: the localized "Close") */
  readonly closeLabel = input<string | undefined>(undefined);
  /**
   * ARIA role of the panel
   * @default "dialog"
   */
  readonly role = input<"dialog" | "alertdialog">("dialog");
  /** Extra class of the panel (React's `className`) */
  readonly panelClass = input<string | undefined>(undefined);
  /** Extra class of the overlay (backdrop) */
  readonly overlayClassName = input<string | undefined>(undefined);

  /** The drawer is open and focus moved in */
  readonly afterOpen = output<void>();
  /** The drawer finished closing (after its exit animation) */
  readonly afterClose = output<void>();

  protected readonly s = s;
  protected readonly hasContent = hasContent;
  protected readonly templateOf = templateOf;
  protected readonly contentClass = computed(() =>
    cn(s.content, s[this.side()], s[this.size()], this.panelClass()),
  );
  protected readonly overlayClass = computed(() =>
    cn(s.overlay, this.overlayClassName()),
  );

  constructor() {
    super();
    dialogLifecycle({
      isOpen: this.isOpen,
      mounted: this.mounted,
      afterOpen: () => this.afterOpen.emit(),
      afterClose: () => this.afterClose.emit(),
    });
  }
}

/** The drawer title (accessible name), for a rich header */
@Component({
  selector: "mn-drawer-header",
  encapsulation: ViewEncapsulation.None,
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: {
    "[class]": "s.header",
    "[attr.id]": "dialog.titleId",
    "data-minerva": "drawer",
    "data-part": "header",
  },
  template: `<ng-content />`,
})
export class MnDrawerHeader {
  protected readonly s = s;
  protected readonly dialog = inject(MN_DIALOG);

  constructor() {
    inject(DestroyRef).onDestroy(this.dialog.registerTitle());
  }
}

/** The scrollable content area of a drawer */
@Component({
  selector: "mn-drawer-body",
  encapsulation: ViewEncapsulation.None,
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: { "[class]": "s.body", "data-minerva": "drawer", "data-part": "body" },
  template: `<ng-content />`,
})
export class MnDrawerBody {
  protected readonly s = s;
}

/** The right-aligned, wrapping action row of a drawer */
@Component({
  selector: "mn-drawer-footer",
  encapsulation: ViewEncapsulation.None,
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: {
    "[class]": "s.footer",
    "data-minerva": "drawer",
    "data-part": "footer",
  },
  template: `<ng-content />`,
})
export class MnDrawerFooter {
  protected readonly s = s;
}

/**
 * Opens / closes a drawer from any element (usually a button):
 * `aria-haspopup="dialog"`, `aria-expanded`, `aria-controls`; focus returns
 * to it on close.
 *
 * @example <button mnButton [mnDrawerTrigger]="drawer">Open</button>
 */
@Directive({
  selector: "[mnDrawerTrigger]",
  exportAs: "mnDrawerTrigger",
  host: DIALOG_TRIGGER_HOST,
})
export class MnDrawerTrigger {
  /** The drawer it controls (`#drawer="mnDrawer"`) */
  readonly mnDrawerTrigger = input.required<DialogContext>();
  protected readonly dialog = this.mnDrawerTrigger;

  constructor() {
    registerTrigger(this.mnDrawerTrigger);
  }
}

/** Closes the enclosing drawer on click */
@Directive({
  selector: "[mnDrawerClose]",
  exportAs: "mnDrawerClose",
  host: { "(click)": "dialog?.setOpen(false)" },
})
export class MnDrawerClose {
  protected readonly dialog = inject(MN_DIALOG, { optional: true });
}

// packages/lib-web-components/src/components/drawer/drawer.ts
import { css, html, nothing, type PropertyValues } from "lit";
import { property, query } from "lit/decorators.js";
import { classMap } from "lit/directives/class-map.js";
import styles from "@lib-core-styles/components/Drawer/drawer.module.scss?inline";
import { DismissableLayerController } from "../../controllers/dismissable-layer";
import { popoverResetStyles } from "../../controllers/floating-layer";
import { FocusScopeController } from "../../controllers/focus-scope";
import { ModalController } from "../../controllers/modal";
import { AriaController } from "../../internal/aria";
import { DEV, devWarn } from "../../internal/dev";
import { hideTopLayer, showTopLayer } from "../../internal/dom";
import { IconX } from "../../internal/icons";
import { LocaleController } from "../../internal/locale";
import { MinervaElement, hostStyles } from "../../internal/minerva-element";
import { PresenceController } from "../../internal/presence";
import { HasSlotController } from "../../internal/slots";
import { sharedStyles } from "../../internal/styles";

/** Edge of the viewport the drawer slides in from */
export type DrawerSide = "left" | "right" | "top" | "bottom";

/** Size preset: width for left / right drawers, height for top / bottom ones */
export type DrawerSize = "small" | "medium" | "large" | "full";

/** Why the drawer asked to open / close (`minerva-open-change` detail) */
export type DrawerChangeReason =
  "close-button" | "escape" | "outside" | "trigger" | "close-slot";

const SIDES: readonly DrawerSide[] = ["left", "right", "top", "bottom"];

/**
 * Side panel (`<Drawer>` of lib-core) sliding in from an edge of the
 * viewport over an overlay. Same behaviour as `<minerva-modal>` (WAI-ARIA
 * dialog): focus moves in and is trapped (Tab loops), Escape (topmost layer
 * only) and an overlay click close it, page scroll is locked, the rest of the
 * page is hidden from assistive technologies and focus returns to the opener.
 * `non-modal` drawers keep the page interactive and close on outside
 * interaction instead.
 *
 * The panel is shown in the top layer (Popover API) but stays in the DOM
 * where the element is, so it inherits the theme of its scope. Without a
 * `description`, a visually hidden localized description ("Drawer content")
 * describes the dialog, like lib-core.
 *
 * Any light DOM element with `data-drawer-close` closes the drawer when
 * clicked (lib-core's `DrawerClose`).
 *
 * @summary Side panel dialog with focus trap, Escape / overlay dismissal and focus return.
 * @tag minerva-drawer
 * @slot - Body content
 * @slot header - Title (alternative to the `label` attribute)
 * @slot footer - Actions row
 * @slot trigger - Element that opens the drawer when clicked
 * @csspart overlay - The backdrop
 * @csspart content - The dialog panel (`role="dialog"`)
 * @csspart header - The title (accessible name of the dialog)
 * @csspart description - The description below the title (visually hidden when no description is given)
 * @csspart body - The scrollable body
 * @csspart footer - The actions row
 * @csspart close-button - The close (×) button
 * @fires minerva-open-change - The user asked to open / close (`detail: { open, reason }`); cancelable: `preventDefault()` keeps the current state
 * @fires minerva-after-open - The drawer is open and focus moved in
 * @fires minerva-after-close - The drawer finished closing (after its exit animation)
 */
export class MinervaDrawer extends MinervaElement {
  static override tagName = "minerva-drawer";
  static override styles = [
    hostStyles,
    popoverResetStyles,
    css`
      :host {
        display: contents;
      }
    `,
    sharedStyles(styles),
  ];

  /** Whether the drawer is open */
  @property({ type: Boolean, reflect: true })
  open = false;

  /** Title text (or use the `header` slot); names the dialog */
  @property()
  label = "";

  /** Visible description below the title (accessible description) */
  @property()
  description = "";

  /**
   * Text of the visually hidden description used when `description` is not
   * set (default: localized "Drawer content")
   */
  @property({ attribute: "hidden-description" })
  hiddenDescription?: string;

  /** Edge the panel slides in from */
  @property({ reflect: true })
  side: DrawerSide = "right";

  /** Size preset (width of left / right drawers, height of top / bottom ones) */
  @property({ reflect: true })
  size: DrawerSize = "medium";

  /** Hides the close (×) button */
  @property({ type: Boolean, attribute: "hide-close-button" })
  hideCloseButton = false;

  /** Accessible label of the close button (default: localized "Close") */
  @property({ attribute: "close-label" })
  closeLabel?: string;

  /** ARIA role of the panel */
  @property({ attribute: "dialog-role" })
  dialogRole: "dialog" | "alertdialog" = "dialog";

  /**
   * Non-modal drawer: no overlay, no focus trap, no scroll lock; closes on
   * outside pointer down / focus (lib-core `DrawerRoot modal={false}`)
   */
  @property({ type: Boolean, reflect: true, attribute: "non-modal" })
  nonModal = false;

  @query(".content")
  private panel?: HTMLElement;

  @query(".overlay")
  private overlay?: HTMLElement;

  private readonly locale = new LocaleController(this);
  private readonly aria = new AriaController(this);
  private readonly slots = new HasSlotController(this);
  private readonly presence = new PresenceController(this, () => this.panel);
  private readonly modal = new ModalController(this);
  private readonly focusScope = new FocusScopeController(this, () => ({
    trapped: !this.nonModal,
    loop: true,
    restoreFocus: true,
  }));
  private readonly layer = new DismissableLayerController(this, () => ({
    disableOutsidePointerEvents: !this.nonModal,
    branches: () => [this.triggerElement()],
    // Focus is trapped while modal: never dismiss on focus outside
    // (`focusin` is not cancelable, so return false).
    onFocusOutside: () => this.nonModal,
    onEscapeKeyDown: () => {
      this.reason = "escape";
    },
    onPointerDownOutside: () => {
      this.reason = "outside";
    },
    onDismiss: () => this.requestOpenChange(false, this.reason),
  }));
  private reason: DrawerChangeReason = "outside";
  private wasPresent = false;

  /** Opens the drawer */
  show(): void {
    this.open = true;
  }

  /** Closes the drawer */
  hide(): void {
    this.open = false;
  }

  private triggerElement(): Element | null {
    return this.querySelector(":scope > [slot='trigger']");
  }

  private requestOpenChange(open: boolean, reason: DrawerChangeReason) {
    if (open === this.open) return;
    const allowed = this.emit(
      "minerva-open-change",
      { open, reason },
      { cancelable: true },
    );
    if (allowed) this.open = open;
  }

  private readonly handleClick = (event: MouseEvent) => {
    if (event.defaultPrevented) return;
    const path = event.composedPath();
    const trigger = this.triggerElement();
    if (trigger && path.includes(trigger)) {
      this.requestOpenChange(!this.open, "trigger");
      return;
    }
    const closer = path.find(
      (node): node is Element =>
        node instanceof Element && node.hasAttribute("data-drawer-close"),
    );
    if (closer && this.contains(closer)) {
      this.requestOpenChange(false, "close-slot");
    }
  };

  override connectedCallback(): void {
    super.connectedCallback();
    this.addEventListener("click", this.handleClick);
  }

  protected override willUpdate(changed: PropertyValues<this>): void {
    if (changed.has("open")) this.presence.sync(this.open);
    if (DEV && changed.has("side") && !SIDES.includes(this.side)) {
      devWarn(
        MinervaDrawer.tagName,
        `invalid side "${this.side}" (expected left, right, top or bottom).`,
      );
    }
  }

  protected override hookStates() {
    return {
      state: this.open ? "open" : "closed",
      side: SIDES.includes(this.side) ? this.side : "right",
      size: this.size,
    };
  }

  protected override updated(changed: PropertyValues<this>): void {
    const present = this.open || this.presence.present;
    if (changed.has("open") || (changed.has("nonModal") && this.open)) {
      const panel = this.panel;
      if (this.open && panel) {
        if (changed.has("nonModal") && !changed.has("open")) {
          // modality changed while open: rebuild the layers
          this.focusScope.deactivate();
          this.layer.deactivate();
          this.modal.deactivate();
        }
        showTopLayer(this.overlay);
        showTopLayer(panel);
        if (!this.nonModal) this.modal.activate(this);
        this.layer.activate(panel);
        this.focusScope.activate(panel);
        if (changed.has("open")) this.emit("minerva-after-open");
      } else if (!this.open) {
        this.focusScope.deactivate();
        this.layer.deactivate();
        this.modal.deactivate();
      }
    }
    if (this.wasPresent && !present) this.afterClose();
    this.wasPresent = present;
  }

  override disconnectedCallback(): void {
    super.disconnectedCallback();
    this.removeEventListener("click", this.handleClick);
    hideTopLayer(this.panel);
    hideTopLayer(this.overlay);
  }

  private afterClose() {
    hideTopLayer(this.panel);
    hideTopLayer(this.overlay);
    this.emit("minerva-after-close");
  }

  protected override render() {
    const present = this.open || this.presence.present;
    const state = this.open ? "open" : "closed";
    const hasHeader = !!this.label || this.slots.test("header");
    const visibleDescription = this.description || this.aria.description;
    const side = SIDES.includes(this.side) ? this.side : "right";
    return html`<slot name="trigger"></slot> ${
        present
          ? html`${
                this.nonModal
                  ? nothing
                  : html`<div
                      part="overlay"
                      class="overlay"
                      popover="manual"
                      data-state=${state}
                      aria-hidden="true"
                    ></div>`
              }
              <div
                part="content"
                class=${classMap({
                  content: true,
                  [side]: true,
                  [this.size]: true,
                })}
                popover="manual"
                role=${this.dialogRole}
                aria-modal=${this.nonModal ? nothing : "true"}
                aria-labelledby=${hasHeader ? "title" : nothing}
                aria-label=${!hasHeader ? (this.aria.label ?? nothing) : nothing}
                aria-describedby="description"
                tabindex="-1"
                data-state=${state}
              >
                <p
                  id="description"
                  part="description"
                  class=${visibleDescription ? "description" : "visuallyHidden"}
                >
                  ${
                    visibleDescription ||
                    this.hiddenDescription ||
                    this.locale.t("drawer.description")
                  }
                </p>
                ${
                  hasHeader
                    ? html`<div id="title" class="header" part="header">
                        <slot name="header">${this.label}</slot>
                      </div>`
                    : nothing
                }
                <div class="body" part="body"><slot></slot></div>
                ${
                  this.slots.test("footer")
                    ? html`<div class="footer" part="footer">
                        <slot name="footer"></slot>
                      </div>`
                    : nothing
                }
                ${
                  this.hideCloseButton
                    ? nothing
                    : html`<button
                        type="button"
                        class="close"
                        part="close-button"
                        aria-label=${this.closeLabel ?? this.locale.t("drawer.close")}
                        @click=${() => this.requestOpenChange(false, "close-button")}
                      >
                        ${IconX}
                      </button>`
                }
              </div>`
          : nothing
      }`;
  }
}

declare global {
  interface HTMLElementTagNameMap {
    "minerva-drawer": MinervaDrawer;
  }
}
