// packages/sample/src/docs/pages/command/demos/custom-filter.tsx
import { useState } from "react";
import { Button, CommandDialog, type CommandItem } from "@minerva/lib-core";

const ITEMS: CommandItem[] = [
  { id: "billing", title: "Billing history", keywords: "invoice" },
  { id: "invoices", title: "Invoices", group: "Billing" },
  { id: "new-invoice", title: "New invoice", keywords: "create" },
  { id: "tax", title: "Tax settings", description: "Invoice numbering" },
];

// Rank: title starts with the query > a title word does > anywhere else
const rank = (item: CommandItem, query: string) => {
  const title = item.title.toLowerCase();
  if (title.startsWith(query)) return 0;
  if (title.split(" ").some((word) => word.startsWith(query))) return 1;
  return 2;
};

const filter = (items: CommandItem[], raw: string) => {
  const query = raw.toLowerCase();
  return items
    .filter((item) =>
      [item.title, item.description, item.group, item.keywords]
        .join(" ")
        .toLowerCase()
        .includes(query),
    )
    .sort((a, b) => rank(a, query) - rank(b, query));
};

export default function CustomFilterDemo() {
  const [open, setOpen] = useState(false);
  const [last, setLast] = useState("—");
  return (
    <div style={{ display: "flex", gap: 12, alignItems: "center" }}>
      <Button onClick={() => setOpen(true)}>Search “invoice”…</Button>
      <span>Selected: {last}</span>
      <CommandDialog
        open={open}
        onOpenChange={setOpen}
        items={ITEMS}
        filter={filter}
        onSelect={(item) => setLast(item.title)}
      />
    </div>
  );
}

// apps/docs/src/docs/pages/command/vue/custom-filter.vue
<script setup lang="ts">
import { ref } from "vue";
import { CommandDialog, Button } from "minerva-design/vue";
const open = ref(false);
const result = ref("");
const items = [
  {
    id: "new",
    title: "New project",
    description: "Start a new workspace",
    group: "Projects",
    keywords: "create",
  },
  {
    id: "settings",
    title: "Open settings",
    group: "Account",
    keywords: "preferences",
  },
  { id: "disabled", title: "Unavailable command", disabled: true },
];
function filter(
  items: import("minerva-design/vue").CommandItem[],
  query: string,
) {
  return items.filter((item) =>
    item.title.toLowerCase().startsWith(query.toLowerCase()),
  );
}
</script>
<template>
  <Button @click="open = true">Search by title prefix</Button
  ><CommandDialog
    v-model:open="open"
    :items="items"
    :filter="filter"
    placeholder="Type the start of a title…"
    @select="(item) => (result = item.title)"
  /><output>{{ result }}</output>
</template>
