// packages/react/src/test-utils/styling-hooks/avatar.tsx
import { Avatar } from "../../components/Avatar";
import type { HookScenario } from "./types";

export default [
  { name: "image", element: <Avatar src="a.png" name="Ada Lovelace" /> },
  {
    name: "initials, every key",
    element: <Avatar name="Ada Lovelace" size="small" shape="square" />,
  },
  { name: "pixel size", element: <Avatar name="Ada" size={40} /> },
] satisfies HookScenario[];

// packages/angular/src/testing/styling-hooks/avatar.ts
import { Component } from "@angular/core";
import { MnAvatar } from "../../components/foundations";
import type { HookScenario } from "../types";
@Component({
  imports: [MnAvatar],
  template: `<mn-avatar name="Ada Lovelace" /><mn-avatar
      name="Grace Hopper"
      src="/avatar.png"
    />`,
})
class Fixture {}
export default [
  { name: "content and states", component: Fixture },
] satisfies HookScenario[];
