// packages/lib-core/src/test-utils/styling-hooks/avatar-group.tsx
import { Avatar, AvatarGroup } from "../../components/Avatar";
import type { HookScenario } from "./types";

export default [
  {
    name: "with +N",
    element: (
      <AvatarGroup max={1}>
        <Avatar name="Ada" />
        <Avatar name="Alan" />
      </AvatarGroup>
    ),
  },
] satisfies HookScenario[];

// packages/angular/src/testing/styling-hooks/avatar-group.ts
import { Component } from "@angular/core";
import { MnAvatarGroup } from "../../components/foundations";
import type { HookScenario } from "../types";
@Component({
  imports: [MnAvatarGroup],
  template: `<mn-avatar-group
    [items]="[{ name: 'Ada' }, { name: 'Grace' }]"
    [max]="1"
  />`,
})
class Fixture {}
export default [
  { name: "content and states", component: Fixture },
] satisfies HookScenario[];
