// packages/react/src/test-utils/styling-hooks/card.tsx
import { Card } from "../../components/Card";
import type { HookScenario } from "./types";

export default [
  { name: "default", element: <Card>Content</Card> },
  {
    name: "disabled button card",
    element: (
      <Card as="button" variant="elevated" disabled>
        Content
      </Card>
    ),
  },
] satisfies HookScenario[];

// packages/angular/src/testing/styling-hooks/card.ts
import { Component } from "@angular/core";
import { MnCard } from "../../components/foundations";
import type { HookScenario } from "../types";
@Component({
  imports: [MnCard],
  template: `<mn-card disabled>Content</mn-card>`,
})
class Fixture {}
export default [
  { name: "content and states", component: Fixture },
] satisfies HookScenario[];
