// packages/lib-core/src/test-utils/styling-hooks/checkbox.tsx
import { Checkbox } from "../../components/Checkbox";
import { FormControl } from "../../components/FormControl";
import type { HookScenario } from "./types";

export default [
  {
    name: "label, helper text, checked, every key",
    element: (
      <Checkbox
        label="Accept"
        helperText="Required"
        defaultChecked
        required
        size="small"
        color="success"
        shape="rounded"
      />
    ),
  },
  {
    name: "indeterminate, invalid",
    element: <Checkbox aria-label="All" indeterminate error />,
  },
  {
    name: "unchecked, read-only",
    element: (
      <FormControl readOnly>
        <Checkbox aria-label="Accept" />
      </FormControl>
    ),
  },
  { name: "disabled", element: <Checkbox aria-label="Accept" disabled /> },
] satisfies HookScenario[];

// packages/angular/src/testing/styling-hooks/checkbox.ts
import { Component } from "@angular/core";
import { MnCheckbox } from "../../components/checkbox";
import { MnFormControl } from "../../components/form-control";
import type { HookScenario } from "../types";

@Component({
  imports: [MnCheckbox],
  template: `<mn-checkbox
    label="Accept"
    helperText="Required"
    defaultChecked
    required
    size="small"
    color="success"
    shape="rounded"
  />`,
})
class Labelled {}

@Component({
  imports: [MnCheckbox],
  template: `<mn-checkbox aria-label="All" indeterminate error />`,
})
class Indeterminate {}

@Component({
  imports: [MnCheckbox, MnFormControl],
  template: `<mn-form-control readOnly>
    <mn-checkbox aria-label="Accept" />
  </mn-form-control>`,
})
class ReadOnly {}

@Component({
  imports: [MnCheckbox],
  template: `<mn-checkbox aria-label="Accept" disabled />`,
})
class Disabled {}

export default [
  { name: "label, helper text, checked, every key", component: Labelled },
  { name: "indeterminate, invalid", component: Indeterminate },
  { name: "unchecked, read-only", component: ReadOnly },
  { name: "disabled", component: Disabled },
] satisfies HookScenario[];
