// packages/lib-core/src/test-utils/styling-hooks/data-table.tsx
import { DataTable } from "../../components/Table";
import type { HookScenario } from "./types";

const columns = [
  { key: "name", header: "Name", sortable: true },
  { key: "age", header: "Age" },
];
const data = [
  { name: "Ada", age: 36 },
  { name: "Alan", age: 41 },
];

export default [
  {
    name: "sortable, selectable, paginated",
    element: (
      <DataTable
        columns={columns}
        data={data}
        size="small"
        variant="bordered"
        rowSelection={{ defaultSelectedRowKeys: [0] }}
        pagination={{ total: 20 }}
      />
    ),
  },
  { name: "empty", element: <DataTable columns={columns} data={[]} /> },
  {
    name: "loading",
    element: (
      <DataTable columns={columns} data={[]} loading variant="striped" />
    ),
  },
  {
    name: "error",
    element: (
      <DataTable
        columns={columns}
        data={data}
        size="large"
        error="Failed"
        onRetry={() => {}}
      />
    ),
  },
] satisfies HookScenario[];

// packages/angular/src/testing/styling-hooks/data-table.ts
import { Component } from "@angular/core";
import { MnDataTable } from "../../components/application";
import type { HookScenario } from "../types";
@Component({
  imports: [MnDataTable],
  template: `<mn-data-table
      [columns]="columns"
      [rows]="rows"
      selectable
      [selection]="['1']"
      [sort]="{ key: 'name', direction: 'ascending' }"
    /><mn-data-table
      [columns]="columns"
      [rows]="rows"
      [sort]="{ key: 'name', direction: 'descending' }"
    /><mn-data-table [columns]="columns" loading /><mn-data-table
      [columns]="columns"
      error="Unable to load"
    /><mn-data-table [columns]="columns" />`,
})
class Fixture {
  readonly columns = [
    { key: "name", header: "Name", sortable: true },
    { key: "id", header: "ID" },
  ];
  readonly rows = [{ id: "1", name: "Ada" }];
}
export default [
  { name: "content and states", component: Fixture },
] satisfies HookScenario[];
