// packages/lib-core/src/test-utils/styling-hooks/grid-item.tsx
import { GridItem } from "../../components/ResponsiveGrid";
import type { HookScenario } from "./types";

export default [
  { name: "default", element: <GridItem fullWidth>A</GridItem> },
  {
    name: "asChild",
    element: (
      <GridItem asChild>
        <section>A</section>
      </GridItem>
    ),
  },
] satisfies HookScenario[];

// packages/angular/src/testing/styling-hooks/grid-item.ts
import { Component } from "@angular/core";
import { MnGridItem } from "../../components/foundations";
import type { HookScenario } from "../types";
@Component({
  imports: [MnGridItem],
  template: `<mn-grid-item fullWidth>Content</mn-grid-item>`,
})
class Fixture {}
export default [
  { name: "content and states", component: Fixture },
] satisfies HookScenario[];
