// packages/lib-core/src/test-utils/styling-hooks/key-value-editor.tsx
import { KeyValueEditor } from "../../components/KeyValueEditor";
import type { HookScenario } from "./types";

export default [
  {
    name: "rows",
    element: (
      <KeyValueEditor
        aria-label="Headers"
        defaultEntries={[{ id: "a", key: "Accept", value: "*/*" }]}
      />
    ),
  },
  {
    name: "disabled",
    element: <KeyValueEditor aria-label="Headers" disabled />,
  },
] satisfies HookScenario[];

// packages/angular/src/testing/styling-hooks/key-value-editor.ts
import { Component } from "@angular/core";
import { MnKeyValueEditor } from "../../components/data";
import type { HookScenario } from "../types";
@Component({
  imports: [MnKeyValueEditor],
  template: `<mn-key-value-editor
    [value]="[
      { key: 'duplicate', value: '1' },
      { key: 'duplicate', value: '2' },
    ]"
    disabled
  />`,
})
class Fixture {
  readonly date = new Date(2026, 9, 1);
}
export default [
  { name: "content and states", component: Fixture },
] satisfies HookScenario[];
