// packages/lib-core/src/test-utils/styling-hooks/month-calendar.tsx
import { MonthCalendar } from "../../components/MonthCalendar";
import type { HookScenario } from "./types";

const month = new Date(2026, 0, 1);
const events = [{ id: "1", date: "2026-01-05", title: "Launch" }];

export default [
  {
    name: "selected day with events",
    element: (
      <MonthCalendar
        defaultMonth={month}
        defaultValue="2026-01-05"
        events={events}
        onEventClick={() => {}}
      />
    ),
  },
  {
    name: "selected day without events, disabled",
    element: (
      <MonthCalendar
        defaultMonth={month}
        defaultValue="2026-01-06"
        events={events}
        disabled
      />
    ),
  },
] satisfies HookScenario[];

// packages/angular/src/testing/styling-hooks/month-calendar.ts
import { Component } from "@angular/core";
import { MnMonthCalendar } from "../../components/data";
import type { HookScenario } from "../types";
@Component({
  imports: [MnMonthCalendar],
  template: `<mn-month-calendar
      [month]="date"
      value="2026-10-09"
      today="2026-10-09"
      [events]="[{ id: '1', date: '2026-10-09', title: 'Meeting' }]"
    /><mn-month-calendar [month]="date" disabled />`,
})
class Fixture {
  readonly date = new Date(2026, 9, 1);
}
export default [
  { name: "content and states", component: Fixture },
] satisfies HookScenario[];
