// packages/react/src/test-utils/styling-hooks/number-input.tsx
import { NumberInput } from "../../components/NumberInput";
import type { HookScenario } from "./types";

export default [
  {
    name: "stepper, every key, required",
    element: (
      <NumberInput
        aria-label="Qty"
        defaultValue={1}
        showStepper
        size="small"
        required
      />
    ),
  },
  {
    name: "invalid, read-only",
    element: <NumberInput aria-label="Qty" invalid readOnly />,
  },
  { name: "disabled", element: <NumberInput aria-label="Qty" disabled /> },
] satisfies HookScenario[];

// packages/angular/src/testing/styling-hooks/number-input.ts
import { Component } from "@angular/core";
import { MnNumberInput } from "../../components/number-input";
import type { HookScenario } from "../types";

@Component({
  imports: [MnNumberInput],
  template: `<mn-number-input
    aria-label="Qty"
    [defaultValue]="1"
    showStepper
    size="small"
    required
  />`,
})
class Stepper {}

@Component({
  imports: [MnNumberInput],
  template: `<mn-number-input aria-label="Qty" invalid readOnly />`,
})
class InvalidReadOnly {}

@Component({
  imports: [MnNumberInput],
  template: `<mn-number-input aria-label="Qty" disabled />`,
})
class Disabled {}

export default [
  { name: "stepper, every key, required", component: Stepper },
  { name: "invalid, read-only", component: InvalidReadOnly },
  { name: "disabled", component: Disabled },
] satisfies HookScenario[];
