// packages/react/src/test-utils/styling-hooks/page-tab.tsx
import { PageTab, PageTabs } from "../../components/PageTabs";
import type { HookScenario } from "./types";

export default [
  {
    name: "current, disabled, icon, action",
    element: (
      <PageTabs aria-label="Open pages" activeValue="a">
        <PageTab value="a" label="A" active icon={<svg />} />
        <PageTab
          value="b"
          label="B"
          disabled
          action={<button type="button">x</button>}
        />
      </PageTabs>
    ),
  },
] satisfies HookScenario[];

// packages/angular/src/testing/styling-hooks/page-tab.ts
import { Component } from "@angular/core";
import { MnPageTabs, MnPageTab } from "../../components/navigation";
import type { HookScenario } from "../types";
@Component({
  imports: [MnPageTabs, MnPageTab],
  template: `<mn-page-tabs
    ><mn-page-tab label="Home" href="/" current icon="★" /><mn-page-tab
      label="Disabled"
      disabled
  /></mn-page-tabs>`,
})
class Fixture {}
export default [
  { name: "content and states", component: Fixture },
] satisfies HookScenario[];
