// packages/react/src/test-utils/styling-hooks/pagination.tsx
import { Pagination } from "../../components/Pagination";
import type { HookScenario } from "./types";

export default [
  {
    name: "total, jumper, size changer",
    element: (
      <Pagination
        total={100}
        showTotal
        showQuickJumper
        showSizeChanger
        size="small"
        shape="circle"
        variant="outline"
      />
    ),
  },
  {
    name: "simple, disabled",
    element: <Pagination total={50} simple disabled />,
  },
] satisfies HookScenario[];

// packages/angular/src/testing/styling-hooks/pagination.ts
import { Component } from "@angular/core";
import { MnPagination } from "../../components/navigation";
import type { HookScenario } from "../types";
@Component({
  imports: [MnPagination],
  template: `<mn-pagination
      [total]="100"
      simple
      showJumper
      showSizeChanger
    /><mn-pagination [total]="100" disabled />`,
})
class Fixture {}
export default [
  { name: "content and states", component: Fixture },
] satisfies HookScenario[];
