// packages/lib-core/src/test-utils/styling-hooks/radio.tsx
import { Radio } from "../../components/Radio";
import type { HookScenario } from "./types";

export default [
  {
    name: "label, helper text, checked, every key",
    element: (
      <Radio
        label="Card"
        helperText="Visa, Mastercard"
        checked
        onChange={() => {}}
        size="small"
        color="success"
      />
    ),
  },
  {
    name: "unchecked, invalid",
    element: (
      <Radio
        aria-label="Cash"
        checked={false}
        onChange={() => {}}
        error
        errorMessage="Pick one"
      />
    ),
  },
  { name: "disabled", element: <Radio aria-label="Cash" disabled /> },
] satisfies HookScenario[];

// packages/angular/src/testing/styling-hooks/radio.ts
import { Component } from "@angular/core";
import { MnRadio } from "../../components/radio";
import type { HookScenario } from "../types";

@Component({
  imports: [MnRadio],
  template: `<mn-radio
    label="Card"
    helperText="Visa, Mastercard"
    [checked]="true"
    size="small"
    color="success"
  />`,
})
class Labelled {}

@Component({
  imports: [MnRadio],
  template: `<mn-radio
    aria-label="Cash"
    [checked]="false"
    error
    errorMessage="Pick one"
  />`,
})
class Invalid {}

@Component({
  imports: [MnRadio],
  template: `<mn-radio aria-label="Cash" disabled />`,
})
class Disabled {}

export default [
  { name: "label, helper text, checked, every key", component: Labelled },
  { name: "unchecked, invalid", component: Invalid },
  { name: "disabled", component: Disabled },
] satisfies HookScenario[];
