// packages/react/src/test-utils/styling-hooks/select.tsx
import {
  Select,
  SelectGroup,
  SelectItem,
  SelectLabel,
  SelectSeparator,
} from "../../components/Select";
import type { HookScenario } from "./types";

const options = (
  <>
    <SelectGroup>
      <SelectLabel>Fruits</SelectLabel>
      <SelectItem value="apple">Apple</SelectItem>
      <SelectItem value="pear" disabled>
        Pear
      </SelectItem>
    </SelectGroup>
    <SelectSeparator />
    <SelectItem value="carrot">Carrot</SelectItem>
  </>
);

/** Shared by the option, option-group, select-label and select-separator fixtures */
export const openSelect = (
  <Select aria-label="Food" defaultOpen defaultValue="apple">
    {options}
  </Select>
);

export default [
  {
    name: "closed, placeholder",
    element: (
      <Select aria-label="Food" placeholder="Pick one">
        {options}
      </Select>
    ),
  },
  { name: "open", element: openSelect },
  {
    name: "disabled, invalid, required, small",
    element: (
      <Select aria-label="Food" disabled invalid required size="small">
        {options}
      </Select>
    ),
  },
] satisfies HookScenario[];

// packages/angular/src/testing/styling-hooks/select.ts
import { Component } from "@angular/core";
import {
  MnSelect,
  MnSelectGroup,
  MnSelectItem,
  MnSelectLabel,
  MnSelectSeparator,
} from "../../components/select";
import type { HookScenario } from "../types";

const OPTIONS = `
  <mn-select-group>
    <mn-select-label>Fruits</mn-select-label>
    <mn-select-item value="apple">Apple</mn-select-item>
    <mn-select-item value="pear" disabled>Pear</mn-select-item>
  </mn-select-group>
  <mn-select-separator />
  <mn-select-item value="carrot">Carrot</mn-select-item>
`;

const imports = [
  MnSelect,
  MnSelectGroup,
  MnSelectItem,
  MnSelectLabel,
  MnSelectSeparator,
];

@Component({
  imports,
  template: `<mn-select aria-label="Food" placeholder="Pick one"
    >${OPTIONS}</mn-select
  >`,
})
class Closed {}

/** Shared by the option, option-group, select-label and select-separator fixtures */
@Component({
  imports,
  template: `<mn-select aria-label="Food" defaultOpen defaultValue="apple"
    >${OPTIONS}</mn-select
  >`,
})
export class OpenSelect {}

@Component({
  imports,
  template: `<mn-select aria-label="Food" disabled invalid required size="small"
    >${OPTIONS}</mn-select
  >`,
})
class Disabled {}

export default [
  { name: "closed, placeholder", component: Closed },
  { name: "open", component: OpenSelect },
  { name: "disabled, invalid, required, small", component: Disabled },
] satisfies HookScenario[];
