// packages/lib-core/src/test-utils/styling-hooks/steps.tsx
import { Steps } from "../../components/Steps";
import type { HookScenario } from "./types";

const items = [
  { value: "a", label: "A" },
  { value: "b", label: "B", disabled: true },
];

export default [
  { name: "read-only", element: <Steps items={items} value="a" /> },
  {
    name: "navigable",
    element: <Steps items={items} defaultValue="a" onChange={() => {}} />,
  },
] satisfies HookScenario[];

// packages/angular/src/testing/styling-hooks/steps.ts
import { Component } from "@angular/core";
import { MnSteps } from "../../components/navigation";
import type { HookScenario } from "../types";
@Component({
  imports: [MnSteps],
  template: `<mn-steps
    [items]="[
      { label: 'First' },
      { label: 'Second' },
      { label: 'Third', disabled: true },
    ]"
    [current]="1"
    readOnly
  />`,
})
class Fixture {}
export default [
  { name: "content and states", component: Fixture },
] satisfies HookScenario[];
