// packages/lib-core/src/test-utils/styling-hooks/table-cell-content.tsx
import { TableCellContent } from "../../components/Table";
import type { HookScenario } from "./types";

export default [
  { name: "primary only", element: <TableCellContent primary="Ada" /> },
  {
    name: "monospace, secondary",
    element: <TableCellContent primary="a1b2" secondary="Commit" monospace />,
  },
] satisfies HookScenario[];

// packages/angular/src/testing/styling-hooks/table-cell-content.ts
import { Component } from "@angular/core";
import { MnTableCellContent } from "../../components/foundations";
import type { HookScenario } from "../types";
@Component({
  imports: [MnTableCellContent],
  template: `<mn-table-cell-content primary="Item" secondary="Details" />`,
})
class Fixture {}
export default [
  { name: "content and states", component: Fixture },
] satisfies HookScenario[];
