// packages/react/src/test-utils/styling-hooks/tabs.tsx
import { Tab, TabList, TabPanel, Tabs } from "../../components/Tabs";
import type { HookScenario } from "./types";

export default [
  {
    name: "default",
    element: (
      <Tabs defaultValue="a">
        <TabList>
          <Tab value="a">A</Tab>
          <Tab value="b">B</Tab>
        </TabList>
        <TabPanel value="a">Panel A</TabPanel>
      </Tabs>
    ),
  },
  {
    name: "vertical pills, colored",
    element: (
      <Tabs
        defaultValue="a"
        orientation="vertical"
        variant="pills"
        color="danger"
      >
        <TabList>
          <Tab value="a">A</Tab>
        </TabList>
      </Tabs>
    ),
  },
] satisfies HookScenario[];

// packages/angular/src/testing/styling-hooks/tabs.ts
import { Component } from "@angular/core";
import { MnTabs, MnTab, MnTabPanel } from "../../components/navigation";
import type { HookScenario } from "../types";
@Component({
  imports: [MnTabs, MnTab, MnTabPanel],
  template: `<mn-tabs value="one"
    ><mn-tab value="one">One</mn-tab><mn-tab value="two" disabled>Two</mn-tab
    ><mn-tab-panel value="one">First</mn-tab-panel
    ><mn-tab-panel value="two">Second</mn-tab-panel></mn-tabs
  >`,
})
class Fixture {}
export default [
  { name: "content and states", component: Fixture },
] satisfies HookScenario[];
