// packages/react/src/test-utils/styling-hooks/tag.tsx
import { Tag } from "../../components/Tag";
import type { HookScenario } from "./types";

export default [
  {
    name: "icon, avatar, closable",
    element: (
      <Tag icon={<svg />} avatar={<img alt="" />} closable>
        Label
      </Tag>
    ),
  },
  {
    name: "pressed toggle, every key",
    element: (
      <Tag
        clickable
        pressed
        size="small"
        variant="solid"
        color="danger"
        shape="circle"
      >
        Filter
      </Tag>
    ),
  },
  {
    name: "unpressed toggle, disabled",
    element: (
      <Tag clickable pressed={false} disabled>
        Filter
      </Tag>
    ),
  },
  { name: "loading", element: <Tag loading>Saving</Tag> },
] satisfies HookScenario[];

// packages/angular/src/testing/styling-hooks/tag.ts
import { Component } from "@angular/core";
import { MnTag } from "../../components/foundations";
import type { HookScenario } from "../types";
@Component({
  imports: [MnTag],
  template: `<mn-tag
      label="Item"
      icon="★"
      avatar="A"
      clickable
      closable
    /><mn-tag label="Busy" loading disabled [active]="true" />`,
})
class Fixture {}
export default [
  { name: "content and states", component: Fixture },
] satisfies HookScenario[];
