// packages/react/src/test-utils/styling-hooks/theme-toggle.tsx
import { ThemeProvider } from "../../contexts/ThemeProvider";
import { ThemeToggle } from "../../components/ThemeToggle";
import type { HookScenario } from "./types";

export default [
  {
    name: "default",
    element: (
      <ThemeProvider>
        <ThemeToggle />
      </ThemeProvider>
    ),
  },
] satisfies HookScenario[];

// packages/angular/src/testing/styling-hooks/theme-toggle.ts
import { Component } from "@angular/core";
import { MnThemeToggle } from "../../components/navigation";
import type { HookScenario } from "../types";
@Component({ imports: [MnThemeToggle], template: `<mn-theme-toggle />` })
class Fixture {}
export default [
  { name: "content and states", component: Fixture },
] satisfies HookScenario[];
