// packages/vue/src/components/Empty/Empty.vue
<script setup lang="ts">
/**
 * Empty: the empty state of a page or a section (`role="status"`), with an
 * icon or illustration, a title naming the region, a description, actions
 * and a footer (default slot).
 */
import { computed, useAttrs, useId, type CSSProperties } from "vue";
import styles from "@react-styles/components/Empty/empty.module.scss";
import { hooks } from "../../internal/hooks";
import { IconInbox } from "../../internal/icons";
import { useI18n } from "../../config/useI18n";
import type { EmptyProps } from "./types";

defineOptions({ name: "Empty", inheritAttrs: false });

const props = withDefaults(defineProps<EmptyProps>(), {
  icon: undefined,
  title: undefined,
  description: undefined,
  size: undefined,
  useSvg: false,
  width: undefined,
  height: undefined,
  showShadow: false,
});

const slots = defineSlots<{
  /** Footer content, e.g. an action button */
  default?: () => unknown;
  /** Custom icon, replacing the default one */
  icon?: () => unknown;
  /** Heading (the `title` prop) */
  title?: () => unknown;
  /** Description (the `description` prop) */
  description?: () => unknown;
  /** Primary call to action (a Button, a link or a group of them) */
  action?: () => unknown;
  /** Secondary action rendered after `action` */
  "secondary-action"?: () => unknown;
}>();

const attrs = useAttrs();
const { t } = useI18n();
const titleId = useId();
const descriptionId = useId();

const px = (value: string | number | undefined) =>
  typeof value === "number" ? `${value}px` : value;

// Only an omitted description falls back to the default (null hides it)
const description = computed(() =>
  props.description === undefined ? t("empty.description") : props.description,
);
const hasTitle = computed(() => !!slots.title || !!props.title);
const hasDescription = computed(
  () => !!slots.description || !!description.value,
);
const hideIcon = computed(() => props.icon === null || props.icon === false);
const hasActions = computed(
  () => !!slots.action || !!slots["secondary-action"],
);

const sizeStyle = computed<CSSProperties>(() => ({
  width: px(props.width),
  height: px(props.height),
}));
const rootAttrs = computed(() => ({
  role: "status",
  // Named by the visible title (or the description) unless the consumer
  // names the region explicitly
  "aria-labelledby":
    attrs["aria-label"] !== undefined
      ? undefined
      : hasTitle.value
        ? titleId
        : hasDescription.value
          ? descriptionId
          : undefined,
  "aria-describedby":
    hasTitle.value && hasDescription.value ? descriptionId : undefined,
  ...attrs,
  ...hooks("empty", "root", { size: props.size }),
}));
</script>

<template>
  <div
    :class="[
      styles.empty,
      showShadow && styles.showShadow,
      size && styles.sized,
      size && styles[`size-${size}`],
    ]"
    :style="sizeStyle"
    v-bind="rootAttrs"
  >
    <div
      v-if="!hideIcon"
      :class="styles.iconWrapper"
      v-bind="hooks('empty', 'icon')"
    >
      <slot name="icon">
        <svg
          v-if="useSvg"
          :class="styles.defaultIcon"
          aria-hidden="true"
          focusable="false"
          width="64"
          height="41"
          viewBox="0 0 64 41"
          xmlns="http://www.w3.org/2000/svg"
        >
          <g transform="translate(0 1)" fill="none" fill-rule="evenodd">
            <ellipse
              style="fill: var(--surface-muted-color)"
              cx="32"
              cy="33"
              rx="32"
              ry="7"
            />
            <g fill-rule="nonzero" style="stroke: var(--border-strong-color)">
              <path
                d="M55 12.76L44.854 1.258C44.367.474 43.656 0 42.907 0H21.093c-.749 0-1.46.474-1.947 1.257L9 12.761V22h46v-9.24z"
              />
              <path
                d="M41.613 15.931c0-1.605.994-2.93 2.227-2.931H55v18.137C55 33.26 53.68 35 52.05 35h-40.1C10.32 35 9 33.259 9 31.137V13h11.16c1.233 0 2.227 1.323 2.227 2.928v.022c0 1.605 1.005 2.901 2.237 2.901h14.752c1.232 0 2.237-1.308 2.237-2.913v-.007z"
                style="fill: var(--surface-color)"
              />
            </g>
          </g>
        </svg>
        <IconInbox
          v-else
          :size="40"
          :class="styles.defaultIcon"
          aria-hidden="true"
        />
      </slot>
    </div>
    <div
      v-if="hasTitle"
      :id="titleId"
      :class="styles.title"
      v-bind="hooks('empty', 'title')"
    >
      <slot name="title">{{ title }}</slot>
    </div>
    <div
      v-if="hasDescription"
      :id="descriptionId"
      :class="styles.description"
      v-bind="hooks('empty', 'description')"
    >
      <slot name="description">{{ description }}</slot>
    </div>
    <div
      v-if="hasActions"
      :class="styles.actions"
      v-bind="hooks('empty', 'actions')"
    >
      <slot name="action" />
      <slot name="secondary-action" />
    </div>
    <div
      v-if="slots.default"
      :class="styles.footer"
      v-bind="hooks('empty', 'footer')"
    >
      <slot />
    </div>
  </div>
</template>

// packages/lib-web-components/src/components/empty/empty.ts
import { css, html, nothing, svg } from "lit";
import { property } from "lit/decorators.js";
import { classMap } from "lit/directives/class-map.js";
import { styleMap } from "lit/directives/style-map.js";
import styles from "@lib-core-styles/components/Empty/empty.module.scss?inline";
import { AriaController } from "../../internal/aria";
import { DEV, devWarn } from "../../internal/dev";
import { LocaleController } from "../../internal/locale";
import { MinervaElement, hostStyles } from "../../internal/minerva-element";
import { HasSlotController } from "../../internal/slots";
import { sharedStyles } from "../../internal/styles";

/** Size preset of the unframed layout */
export type EmptySize = "small" | "medium" | "large";

/** Default icon (lib-core's IconInbox at 40px); decorative. */
const DefaultIcon = svg`<svg class="defaultIcon" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="40" height="40" fill="currentColor" fill-rule="evenodd" clip-rule="evenodd" stroke="none" aria-hidden="true" focusable="false"><path d="M4 3h16a1 1 0 0 1 1 1v16a1 1 0 0 1-1 1H4a1 1 0 0 1-1-1V4a1 1 0 0 1 1-1ZM5 5v9h4a3 3 0 0 0 6 0h4V5ZM5 16v3h14v-3h-2.54a5 5 0 0 1-8.92 0Z" /></svg>`;

/** Built-in illustration (decorative). */
const DefaultSvg = svg`<svg class="defaultIcon" aria-hidden="true" focusable="false" width="64" height="41" viewBox="0 0 64 41" xmlns="http://www.w3.org/2000/svg"><g transform="translate(0 1)" fill="none" fill-rule="evenodd"><ellipse style="fill: var(--surface-muted-color)" cx="32" cy="33" rx="32" ry="7" /><g fill-rule="nonzero" style="stroke: var(--border-strong-color)"><path d="M55 12.76L44.854 1.258C44.367.474 43.656 0 42.907 0H21.093c-.749 0-1.46.474-1.947 1.257L9 12.761V22h46v-9.24z" /><path d="M41.613 15.931c0-1.605.994-2.93 2.227-2.931H55v18.137C55 33.26 53.68 35 52.05 35h-40.1C10.32 35 9 33.259 9 31.137V13h11.16c1.233 0 2.227 1.323 2.227 2.928v.022c0 1.605 1.005 2.901 2.237 2.901h14.752c1.232 0 2.237-1.308 2.237-2.913v-.007z" style="fill: var(--surface-color)" /></g></g></svg>`;

const toCss = (value: string | undefined) =>
  value && /^\d+(\.\d+)?$/.test(value) ? `${value}px` : value;

/**
 * Empty state (`<Empty>` of lib-core): an icon, an optional heading, a
 * description (localized "No Data" by default), actions and footer
 * content. It is a `role="status"` region named by its heading (or its
 * description) unless `aria-label` is set.
 *
 * @summary Empty state with icon, heading, description and actions.
 * @tag minerva-empty
 * @slot - Footer content
 * @slot icon - Custom icon replacing the default one
 * @slot heading - Heading (alternative to the `heading` attribute)
 * @slot description - Description (alternative to the `description` attribute)
 * @slot action - Primary call to action
 * @slot secondary-action - Secondary action, after `action`
 * @csspart root - The region (role=status); size only for the unframed sized layout
 * @csspart icon - The icon wrapper
 * @csspart title - The title (accessible name of the region)
 * @csspart description - The description
 * @csspart actions - The actions row
 * @csspart footer - The footer content
 */
export class MinervaEmpty extends MinervaElement {
  static override tagName = "minerva-empty";
  static override styles = [
    hostStyles,
    css`
      :host {
        display: block;
      }
    `,
    sharedStyles(styles),
  ];

  /** Heading of the empty state; also its accessible name (lib-core's `title`) */
  @property()
  heading = "";

  /** Description text (default: localized "No Data") */
  @property()
  description?: string;

  /** Hides the description (lib-core's `description={null}`) */
  @property({ type: Boolean, attribute: "hide-description" })
  hideDescription = false;

  /** Renders no icon at all (lib-core's `icon={null}`) */
  @property({ type: Boolean, attribute: "hide-icon" })
  hideIcon = false;

  /** Unframed sized layout; omit for the classic surface layout */
  @property({ reflect: true })
  size?: EmptySize;

  /** Uses the built-in SVG illustration instead of the default icon */
  @property({ type: Boolean, attribute: "use-svg" })
  useSvg = false;

  /** Width of the container (CSS value, numbers are pixels) */
  @property()
  width?: string;

  /** Height of the container (CSS value, numbers are pixels) */
  @property()
  height?: string;

  /** Adds a drop shadow */
  @property({ type: Boolean, attribute: "show-shadow" })
  showShadow = false;

  private readonly locale = new LocaleController(this);
  private readonly aria = new AriaController(this);
  private readonly slots = new HasSlotController(this);

  protected override hookStates() {
    return { size: this.size };
  }

  protected override updated(): void {
    if (DEV && this.hideDescription && this.description) {
      devWarn(
        MinervaEmpty.tagName,
        "description is ignored while hide-description is set.",
      );
    }
  }

  protected override render() {
    const hasTitle = !!this.heading || this.slots.test("heading");
    const hasDescriptionSlot = this.slots.test("description");
    const description = this.description ?? this.locale.t("empty.description");
    const hasDescription =
      !this.hideDescription && (hasDescriptionSlot || description !== "");
    const hasActions =
      this.slots.test("action") || this.slots.test("secondary-action");
    const label = this.aria.label;

    return html`<div
      part="root"
      class=${classMap({
        empty: true,
        showShadow: this.showShadow,
        sized: !!this.size,
        [`size-${this.size}`]: !!this.size,
      })}
      style=${styleMap({
        width: toCss(this.width),
        height: toCss(this.height),
      })}
      role="status"
      aria-label=${label ?? nothing}
      aria-labelledby=${
        label
          ? nothing
          : hasTitle
            ? "title"
            : hasDescription
              ? "description"
              : nothing
      }
      aria-describedby=${hasTitle && hasDescription ? "description" : nothing}
    >
      ${
        this.hideIcon
          ? nothing
          : html`<div part="icon" class="iconWrapper">
              <slot name="icon">${this.useSvg ? DefaultSvg : DefaultIcon}</slot>
            </div>`
      }
      ${
        hasTitle
          ? html`<div id="title" part="title" class="title">
              <slot name="heading">${this.heading}</slot>
            </div>`
          : nothing
      }
      ${
        hasDescription
          ? html`<div id="description" part="description" class="description">
              <slot name="description">${description}</slot>
            </div>`
          : nothing
      }
      ${
        hasActions
          ? html`<div part="actions" class="actions">
              <slot name="action"></slot><slot name="secondary-action"></slot>
            </div>`
          : nothing
      }
      ${
        this.slots.test("[default]")
          ? html`<div part="footer" class="footer"><slot></slot></div>`
          : nothing
      }
    </div>`;
  }
}

declare global {
  interface HTMLElementTagNameMap {
    "minerva-empty": MinervaEmpty;
  }
}
