// packages/vue/src/components/Skeleton/Skeleton.vue
<script setup lang="ts">
/**
 * Skeleton: a placeholder shown where content is loading (lines, avatar,
 * title, paragraph or a card), announced as a busy status region; renders
 * the default slot once `loading` is false. `decorative` renders one bare
 * `aria-hidden` block to compose custom layouts.
 */
import { computed, useAttrs, type CSSProperties, type StyleValue } from "vue";
import styles from "@react-styles/components/Skeleton/skeleton.module.scss";
import { hooks } from "../../internal/hooks";
import { useI18n } from "../../config/useI18n";
import type { SkeletonProps } from "./types";

defineOptions({ name: "Skeleton", inheritAttrs: false });

const props = withDefaults(defineProps<SkeletonProps>(), {
  variant: "text",
  animation: "pulse",
  decorative: false,
  size: undefined,
  width: undefined,
  height: undefined,
  loading: true,
  borderRadius: undefined,
  lines: 1,
  avatar: false,
  avatarSize: 40,
  avatarShape: "circle",
  active: false,
  paragraph: false,
  title: false,
});

defineSlots<{
  /** Real content, rendered once loading is false */
  default?: () => unknown;
}>();

const toCss = (value: number | string | undefined) =>
  typeof value === "number" ? `${value}px` : value;

const attrs = useAttrs();
const { t } = useI18n();

const animationClass = computed(() => styles[`animation-${props.animation}`]);
/** Attributes without `style` (applied to the lines / decorative block) */
const otherAttrs = computed(() => {
  const { style: _style, ...rest } = attrs;
  return rest;
});

const decorativeAttrs = computed(() => {
  const dim =
    props.variant === "circular"
      ? toCss(props.size ?? props.width ?? 32)
      : undefined;
  return {
    "aria-hidden": "true",
    ...otherAttrs.value,
    class: [
      styles.skeleton,
      styles.decorative,
      styles[props.variant],
      animationClass.value,
      attrs.class,
    ],
    style: [
      {
        width: dim ?? toCss(props.width),
        height: dim ?? toCss(props.height),
        borderRadius: toCss(props.borderRadius),
      },
      attrs.style as StyleValue,
    ],
    ...hooks("skeleton", "root", { variant: props.variant }),
  };
});

const lineCount = computed(() =>
  props.paragraph || props.title
    ? 0
    : // Guard against negative / fractional / NaN counts
      Number.isFinite(props.lines)
      ? Math.max(0, Math.floor(props.lines))
      : 0,
);
const lineClass = computed(() => [
  styles.skeleton,
  styles[props.variant],
  animationClass.value,
]);
const lineStyle = computed<StyleValue>(() => [
  {
    width: toCss(props.width),
    height: toCss(props.height),
    borderRadius: toCss(props.borderRadius),
  },
  attrs.style as StyleValue,
]);
const avatarStyle = computed<CSSProperties>(() => ({
  width: toCss(props.avatarSize),
  height: toCss(props.avatarSize),
}));
const paragraphLines = [
  { width: "100%", height: "16px" },
  { width: "100%", height: "16px" },
  { width: "92%", height: "16px" },
  { width: "60%", height: "16px" },
];

const rootAttrs = computed(() => ({
  role: "status",
  "aria-busy": "true",
  "aria-label": t("common.loading"),
  ...otherAttrs.value,
  class: [styles.skeletonRoot, props.avatar && styles.withAvatar, attrs.class],
  ...hooks("skeleton", "root", { variant: props.variant }),
}));
</script>

<template>
  <slot v-if="!loading" />
  <span v-else-if="decorative" v-bind="decorativeAttrs" />
  <div v-else v-bind="rootAttrs">
    <div
      v-if="variant === 'card'"
      :class="[styles.card, active && styles.active]"
    >
      <div
        v-if="avatar"
        :class="[
          styles.skeleton,
          styles.avatar,
          animationClass,
          styles[`avatar-${avatarShape}`],
        ]"
        :style="avatarStyle"
        v-bind="hooks('skeleton', 'avatar')"
      />
      <div :class="styles.cardContent">
        <div
          v-if="title"
          :class="[styles.skeleton, styles.title, animationClass]"
          v-bind="hooks('skeleton', 'title')"
        />
        <div v-if="paragraph" :class="styles.paragraph">
          <div
            v-for="(line, index) in paragraphLines"
            :key="`p-${index}`"
            :class="[styles.skeleton, animationClass]"
            :style="line"
            v-bind="hooks('skeleton', 'line')"
          />
        </div>
      </div>
    </div>
    <template v-else>
      <div
        v-if="avatar"
        :class="[
          styles.skeleton,
          styles.avatar,
          animationClass,
          styles[`avatar-${avatarShape}`],
        ]"
        :style="avatarStyle"
        v-bind="hooks('skeleton', 'avatar')"
      />
      <div :class="styles.content">
        <div
          v-if="title"
          :class="[styles.skeleton, styles.title, animationClass]"
          v-bind="hooks('skeleton', 'title')"
        />
        <div
          v-for="index in lineCount"
          :key="index"
          :class="lineClass"
          :style="lineStyle"
          v-bind="hooks('skeleton', 'line')"
        />
        <div v-if="paragraph" :class="styles.paragraph">
          <div
            v-for="(line, index) in paragraphLines"
            :key="`p-${index}`"
            :class="[styles.skeleton, animationClass]"
            :style="line"
            v-bind="hooks('skeleton', 'line')"
          />
        </div>
      </div>
    </template>
  </div>
</template>

// packages/lib-core/src/components/Skeleton/Skeleton.tsx
import React from "react";
import { cn } from "../../utils/cn";
import type { SkeletonProps } from "./types";
import styles from "./skeleton.module.scss";
import useI18n from "../../hooks/useI18n";

/**
 * @name Skeleton 骨架屏
 * @description 在需要等待加载内容的位置提供一个占位图形组合
 * @param SkeletonVariant variant - 组件类型 可选值：text、avatar、card、button、image、rectangular、rounded
 * @param SkeletonAnimation animation - 动画类型 可选值：pulse、wave、false
 * @param number | string width - 宽度
 * @param number | string height - 高度
 * @param string className - 自定义类名
 * @param React.ReactNode children - 子元素
 * @param boolean loading - 是否加载中
 * @param number | string borderRadius - 圆角大小
 * @param React.CSSProperties style - 自定义样式
 * @param number lines - 行数
 * @param boolean avatar - 是否显示头像
 * @param number | string avatarSize - 头像大小
 * @param string avatarShape - 头像形状 可选值：circle、square
 * @param boolean active - 是否激活交互态
 * @param boolean paragraph - 是否显示段落
 * @param boolean title - 是否显示标题
 * @param string aria-label - 加载中区域的无障碍名称
 * @param boolean decorative - 只渲染单个装饰性占位块（aria-hidden span）
 * @param number | string size - 装饰性圆形占位的边长
 * @param Ref ref - 根元素的 ref (仅在 loading 时渲染)
 */
const toCss = (value: number | string | undefined) =>
  typeof value === "number" ? `${value}px` : value;

const Skeleton = ({
  variant = "text",
  animation = "pulse",
  width,
  height,
  className,
  children,
  loading = true,
  borderRadius,
  style,
  lines = 1,
  avatar = false,
  avatarSize = 40,
  avatarShape = "circle",
  active = false,
  paragraph = false,
  title = false,
  "aria-label": ariaLabel,
  decorative = false,
  size,
  ref,
  ...rest
}: SkeletonProps) => {
  const { t } = useI18n();
  if (!loading) {
    return <>{children}</>;
  }

  if (decorative) {
    const dim = variant === "circular" ? toCss(size ?? width ?? 32) : undefined;
    return (
      <span
        ref={ref}
        aria-hidden="true"
        {...rest}
        className={cn(
          styles.skeleton,
          styles.decorative,
          styles[variant],
          styles[`animation-${animation}`],
          className,
        )}
        style={{
          width: dim ?? toCss(width),
          height: dim ?? toCss(height),
          borderRadius,
          ...style,
        }}
      />
    );
  }

  const renderLines = () => {
    if (paragraph || title) return null;

    // Guard against negative / fractional / NaN counts (Array(-1) throws)
    const count = Number.isFinite(lines) ? Math.max(0, Math.floor(lines)) : 0;
    return Array(count)
      .fill(null)
      .map((_, index) => (
        <div
          key={index}
          className={cn(
            styles.skeleton,
            styles[variant],
            styles[`animation-${animation}`],
          )}
          style={{
            width: typeof width === "number" ? `${width}px` : width,
            height: typeof height === "number" ? `${height}px` : height,
            borderRadius,
            ...style,
          }}
        />
      ));
  };

  const renderAvatar = () => {
    if (!avatar) return null;

    return (
      <div
        className={cn(
          styles.skeleton,
          styles.avatar,
          styles[`animation-${animation}`],
          styles[`avatar-${avatarShape}`],
        )}
        style={{
          width:
            typeof avatarSize === "number" ? `${avatarSize}px` : avatarSize,
          height:
            typeof avatarSize === "number" ? `${avatarSize}px` : avatarSize,
        }}
      />
    );
  };

  const renderParagraph = () => {
    if (!paragraph) return null;

    const paragraphLines = [
      { width: "100%", height: "16px" },
      { width: "100%", height: "16px" },
      { width: "92%", height: "16px" },
      { width: "60%", height: "16px" },
    ];

    return (
      <div className={styles.paragraph}>
        {paragraphLines.map((line, index) => (
          <div
            key={`p-${index}`}
            className={cn(styles.skeleton, styles[`animation-${animation}`])}
            style={{
              width: line.width,
              height: line.height,
            }}
          />
        ))}
      </div>
    );
  };

  const renderTitle = () => {
    if (!title) return null;

    return (
      <div
        className={cn(
          styles.skeleton,
          styles.title,
          styles[`animation-${animation}`],
        )}
      />
    );
  };

  const renderContent = () => {
    if (variant === "card") {
      return (
        <div className={cn(styles.card, { [styles.active]: active })}>
          {renderAvatar()}
          <div className={styles.cardContent}>
            {renderTitle()}
            {renderParagraph()}
          </div>
        </div>
      );
    }

    return (
      <>
        {renderAvatar()}
        <div className={styles.content}>
          {renderTitle()}
          {renderLines()}
          {renderParagraph()}
        </div>
      </>
    );
  };

  return (
    <div
      ref={ref as React.Ref<HTMLDivElement>}
      role="status"
      aria-busy="true"
      aria-label={ariaLabel ?? t("common.loading")}
      className={cn(
        styles.skeletonRoot,
        avatar && styles.withAvatar,
        className,
      )}
      {...rest}
    >
      {renderContent()}
    </div>
  );
};

export default Skeleton;
