// packages/web-components/src/components/autocomplete/autocomplete.ts
import {
  css,
  html,
  nothing,
  type PropertyValues,
  type TemplateResult,
} from "lit";
import { property, query, state } from "lit/decorators.js";
import { classMap } from "lit/directives/class-map.js";
import { parsePlacement } from "@minerva/dom";
import { live } from "lit/directives/live.js";
import { styleMap } from "lit/directives/style-map.js";
import inputStyles from "@react-styles/components/Input/input.module.scss?inline";
import styles from "@react-styles/components/AutoComplete/autoComplete.module.scss?inline";
import {
  FloatingLayerController,
  popoverResetStyles,
} from "../../controllers/floating-layer";
import { AriaController } from "../../internal/aria";
import { DEV, devWarn } from "../../internal/dev";
import {
  FormAssociatedElement,
  type ValidityResult,
} from "../../internal/form";
import { IconInbox, IconSpinner } from "../../internal/icons";
import { LocaleController } from "../../internal/locale";
import { hostStyles } from "../../internal/minerva-element";
import { HasSlotController } from "../../internal/slots";
import { itemParts } from "../../internal/styling-hooks";
import { sharedStyles } from "../../internal/styles";

/** Content a render callback may return */
export type AutoCompleteRenderResult = string | Node | TemplateResult;

/** An option of the AutoComplete dropdown */
export interface AutoCompleteOption {
  /** Text displayed for the option and written to the input when selected */
  label: string;
  /** Unique value of the option */
  value: string | number;
  /** Prevents the option from being selected */
  disabled?: boolean;
  /** Highlights the option (e.g. as a recommendation) */
  highlight?: boolean;
  /** Icon displayed before the label (basic mode) */
  icon?: AutoCompleteRenderResult;
  /** Secondary text displayed under the label (basic mode) */
  description?: string;
  /** Free-form group identifier, typically read by groupBy */
  group?: string;
  /** Inline styles of the option */
  style?: Record<string, string>;
}

export type AutoCompleteMode = "basic" | "custom";
export type AutoCompletePlacement = "top" | "bottom" | "left" | "right";
export type AutoCompleteGroupMode = "first" | "adjacent";
export type AutoCompleteSize = "small" | "medium" | "large";
export type AutoCompleteVariant = "outline" | "filled" | "unstyled";

const PLACEMENT = {
  top: "top-start",
  bottom: "bottom-start",
  left: "left-start",
  right: "right-start",
} as const;

/**
 * Text input (combobox) suggesting options from a list (`<AutoComplete>` of
 * React): filtering, grouping, custom rendering and async loading.
 * Focus stays in the input; the active option is exposed with
 * `aria-activedescendant` (the listbox lives in the same shadow root).
 *
 * Keyboard (WAI-ARIA combobox): ArrowDown / ArrowUp open the list and move
 * the active option (wrapping, disabled options skipped), Enter picks the
 * active option (or fires `minerva-submit` with the typed text when none is
 * active), Escape closes the open list (topmost layer only) and, on a
 * closed list, clears the text (without closing an enclosing modal).
 *
 * Form-associated: submits the input text under `name`; `required` makes an
 * empty text invalid; `form.reset()` restores the `value` attribute.
 *
 * @summary Text input with a filtered suggestion list.
 * @tag minerva-autocomplete
 * @slot prefix - Content before the text (icon)
 * @slot suffix - Content after the text
 * @csspart root - The root wrapper (label, field and anchor of the dropdown)
 * @csspart label - The visible label
 * @csspart field - The input box
 * @csspart input - The native `<input role=combobox>`
 * @csspart content - The positioned dropdown
 * @csspart list - The `role=listbox` list
 * @csspart item - An option
 * @csspart item--highlighted - Item state of `item`: highlighted
 * @csspart item--disabled - Item state of `item`: disabled
 * @csspart group-label - A group heading
 * @csspart empty - The empty state (no matching option)
 * @csspart loading - The loading state (while loading)
 * @fires minerva-input - The input text changed (typing, picking an option, Escape clearing) (`detail: { value }`)
 * @fires minerva-change - The text was committed: an option filled it in, Escape cleared it, or the native change (blur) (`detail: { value }`)
 * @fires minerva-select - An option was picked with the mouse or the keyboard (`detail: { value, option }`)
 * @fires minerva-submit - Enter was pressed with no active option and non-blank text (`detail: { value }`, trimmed)
 * @fires minerva-open-change - The dropdown opens / closes (`detail: { open }`); cancelable: `preventDefault()` keeps the current state
 */
export class MinervaAutocomplete extends FormAssociatedElement {
  static override tagName = "minerva-autocomplete";
  static override shadowRootOptions = {
    ...FormAssociatedElement.shadowRootOptions,
    delegatesFocus: true,
  };
  static override styles = [
    hostStyles,
    popoverResetStyles,
    sharedStyles(inputStyles),
    sharedStyles(styles),
    css`
      :host {
        display: block;
        width: 100%;
      }
      /* Input's .disabled shares the class name of disabled options */
      .optionItem.disabled:not(.active):not(.highlight) {
        background-color: transparent;
      }
      .popup .dropdown .optionList .loading svg {
        font-size: 1.5em;
        animation: minerva-autocomplete-spin 1s linear infinite;
      }
      .empty svg {
        display: block;
        margin: 0 auto var(--space-2);
        font-size: 40px;
        color: var(--text-muted-color);
      }
      @keyframes minerva-autocomplete-spin {
        to {
          transform: rotate(360deg);
        }
      }
      @media (prefers-reduced-motion: reduce) {
        .popup .dropdown .optionList .loading svg {
          animation: none;
        }
      }
    `,
  ];

  /** Input text (property; the `value` attribute sets `defaultValue`) */
  @property({ attribute: false })
  value = "";

  /** Initial text, restored by `form.reset()` (the `value` attribute) */
  @property({ attribute: "value" })
  defaultValue = "";

  /** Options to suggest */
  @property({ attribute: false })
  options: AutoCompleteOption[] = [];

  /** Whether the dropdown is open */
  @property({ type: Boolean, reflect: true })
  open = false;

  /** Visible label of the input (also names the listbox) */
  @property()
  label = "";

  /** Placeholder of the input */
  @property()
  placeholder = "";

  /** "basic" renders icon / label / description; "custom" uses `renderOption` */
  @property({ reflect: true })
  mode: AutoCompleteMode = "basic";

  /** Size of the input */
  @property({ reflect: true })
  size: AutoCompleteSize = "medium";

  /** Visual style of the input */
  @property({ reflect: true })
  variant: AutoCompleteVariant = "outline";

  /** Error state; sets aria-invalid */
  @property({ type: Boolean, reflect: true })
  invalid = false;

  /** Read-only: focusable and submitted, no dropdown */
  @property({ type: Boolean, reflect: true, attribute: "readonly" })
  readOnly = false;

  /** Shows a loading indicator instead of the options */
  @property({ type: Boolean, reflect: true })
  loading = false;

  /** Preferred dropdown side (aligned with the input's start edge) */
  @property({ reflect: true })
  placement: AutoCompletePlacement = "bottom";

  /**
   * Dropdown offset in px: for top / bottom `y` is the gap and `x` the
   * shift, for left / right the reverse
   */
  @property({ attribute: false })
  offset: { x: number; y: number } = { x: 0, y: 4 };

  /** Disables the opening animation */
  @property({ type: Boolean, attribute: "no-animation" })
  noAnimation = false;

  /** Makes the first enabled option active whenever the dropdown opens */
  @property({ type: Boolean, attribute: "auto-highlight" })
  autoHighlight = false;

  /** Keeps the typed text when an option is picked (no fill-in) */
  @property({ type: Boolean, attribute: "no-fill-on-select" })
  noFillOnSelect = false;

  /** How `groupBy` groups options: at first appearance, or runs of adjacent options */
  @property({ attribute: "group-mode" })
  groupMode: AutoCompleteGroupMode = "first";

  /** Custom filter (default: label contains the text, case-insensitive) */
  @property({ attribute: false })
  filterOption?: (inputValue: string, option: AutoCompleteOption) => boolean;

  /** Compare function sorting the filtered options */
  @property({ attribute: false })
  sortOption?: (a: AutoCompleteOption, b: AutoCompleteOption) => number;

  /** Group name of an option; options are grouped under headings ("" = none) */
  @property({ attribute: false })
  groupBy?: (option: AutoCompleteOption) => string;

  /** Custom option renderer (used when `mode` is "custom") */
  @property({ attribute: false })
  renderOption?: (option: AutoCompleteOption) => AutoCompleteRenderResult;

  /** Custom content shown when no option matches */
  @property({ attribute: false })
  renderEmpty?: () => AutoCompleteRenderResult;

  @state()
  private focusedIndex = -1;

  @state()
  private hoveredIndex = -1;

  @query("input")
  private input?: HTMLInputElement;

  @query(".autoComplete")
  private container?: HTMLElement;

  @query(".popup")
  private popup?: HTMLElement;

  private readonly locale = new LocaleController(this);
  private readonly aria = new AriaController(this, () => this.labels);
  private readonly slots = new HasSlotController(this);
  private readonly floating = new FloatingLayerController(this, () => {
    const vertical = this.placement === "top" || this.placement === "bottom";
    const offset = this.offset ?? { x: 0, y: 4 };
    return {
      anchor: () => this.container,
      floating: () => this.popup,
      placement: PLACEMENT[this.placement] ?? "bottom-start",
      offset: {
        mainAxis: vertical ? offset.y : offset.x,
        crossAxis: vertical ? offset.x : offset.y,
      },
      matchAnchorWidth: "min",
      // the field (label, input, suffix) is part of the dropdown layer
      branches: () => [this.container],
      onEscapeKeyDown: (event) => {
        // Escape during IME composition cancels the composition only
        if (this.composing || event.isComposing) event.preventDefault();
      },
      onDismiss: () => this.close(),
      returnFocusOnEscape: () => this.input,
      onPosition: () => this.syncHookStates(),
    };
  });
  /** IME composition in progress: Enter / arrows belong to the IME. */
  private composing = false;
  private dirty = false;

  override focus(options?: FocusOptions): void {
    this.input?.focus(options);
  }

  override blur(): void {
    this.input?.blur();
  }

  /** Whether the input accepts no interaction (disabled / read-only). */
  private get blocked(): boolean {
    return this.isDisabled || this.readOnly;
  }

  /** The dropdown is rendered (open and interactive). */
  private get shown(): boolean {
    return this.open && !this.blocked;
  }

  protected getFormValue(): string {
    return this.value;
  }

  protected override getValidity(): ValidityResult {
    return this.required && this.value === ""
      ? {
          flags: { valueMissing: true },
          message: this.locale.t("validation.valueMissing"),
          anchor: this.input,
        }
      : { flags: {}, message: "" };
  }

  protected resetFormValue(): void {
    this.dirty = false;
    this.value = this.defaultValue;
    this.focusedIndex = -1;
  }

  protected override restoreFormState(state: unknown): void {
    if (typeof state === "string") this.value = state;
  }

  /** Filtered (and sorted) options. */
  private get processedOptions(): AutoCompleteOption[] {
    const text = this.value;
    const search = text.toLowerCase();
    const result = (this.options ?? []).filter((option) =>
      this.filterOption
        ? this.filterOption(text, option)
        : option.label.toLowerCase().includes(search),
    );
    return this.sortOption ? [...result].sort(this.sortOption) : result;
  }

  /** Groups in order of first appearance, or runs of adjacent options. */
  private groupOptions(
    options: AutoCompleteOption[],
  ): Array<[string, AutoCompleteOption[]]> | null {
    const groupBy = this.groupBy;
    if (!groupBy) return null;
    if (this.groupMode === "adjacent") {
      const runs: Array<[string, AutoCompleteOption[]]> = [];
      for (const option of options) {
        const group = groupBy(option);
        const last = runs[runs.length - 1];
        if (last && last[0] === group) last[1].push(option);
        else runs.push([group, [option]]);
      }
      return runs;
    }
    const groups = new Map<string, AutoCompleteOption[]>();
    for (const option of options) {
      const group = groupBy(option);
      const list = groups.get(group);
      if (list) list.push(option);
      else groups.set(group, [option]);
    }
    return Array.from(groups.entries());
  }

  /** Options in display order; keyboard / hover indexes refer to this list. */
  private get navigableOptions(): AutoCompleteOption[] {
    const processed = this.processedOptions;
    const grouped = this.groupOptions(processed);
    return grouped ? grouped.flatMap(([, list]) => list) : processed;
  }

  private activeIndex(navigable: AutoCompleteOption[]): number {
    if (this.focusedIndex >= 0) return this.focusedIndex;
    return this.autoHighlight && this.shown
      ? navigable.findIndex((option) => !option.disabled)
      : -1;
  }

  /** Asks to open / close; listeners can cancel `minerva-open-change`. */
  private requestOpen(open: boolean): boolean {
    if (open === this.open) return true;
    const allowed = this.emit(
      "minerva-open-change",
      { open },
      { cancelable: true },
    );
    if (allowed) this.open = open;
    return allowed;
  }

  private openDropdown() {
    if (!this.blocked) this.requestOpen(true);
  }

  private close() {
    this.requestOpen(false);
    this.focusedIndex = -1;
  }

  private setText(next: string, commit: boolean) {
    if (next === this.value) return;
    this.value = next;
    this.emit("minerva-input", { value: next });
    if (commit) this.emit("minerva-change", { value: next });
  }

  private moveFocus(step: 1 | -1) {
    const navigable = this.navigableOptions;
    const count = navigable.length;
    if (count === 0) return;
    // from "nothing focused", ArrowDown starts at the first option and
    // ArrowUp at the last one
    const active = this.activeIndex(navigable);
    let index = active >= 0 ? active : step === 1 ? -1 : count;
    for (let i = 0; i < count; i += 1) {
      index = (index + step + count) % count;
      if (!navigable[index].disabled) {
        this.focusedIndex = index;
        return;
      }
    }
  }

  private selectOption(option: AutoCompleteOption) {
    if (option.disabled) return;
    if (!this.noFillOnSelect) this.setText(option.label, true);
    this.close();
    this.emit("minerva-select", { value: option.value, option });
  }

  private handleKeyDown(event: KeyboardEvent) {
    if (
      this.blocked ||
      this.composing ||
      event.isComposing ||
      event.keyCode === 229
    ) {
      return;
    }
    switch (event.key) {
      case "ArrowDown":
      case "ArrowUp": {
        event.preventDefault();
        // open first: the active index depends on the open state
        if (!this.open) this.openDropdown();
        this.moveFocus(event.key === "ArrowDown" ? 1 : -1);
        break;
      }
      case "Enter": {
        const navigable = this.navigableOptions;
        const option = this.shown
          ? navigable[this.activeIndex(navigable)]
          : undefined;
        const text = this.value.trim();
        if (option) {
          event.preventDefault();
          this.selectOption(option);
        } else if (text) {
          // No active option: submit the typed text (e.g. a search).
          event.preventDefault();
          this.emit("minerva-submit", { value: text });
          this.close();
        }
        break;
      }
      case "Escape":
        // Open: the dropdown's dismissable layer closes it (topmost only).
        // Closed: clears the text (APG combobox). The layer's document
        // listener may already have closed it during this very keydown.
        if (!this.shown && !this.floating.isOpen && this.value !== "") {
          event.preventDefault();
          this.setText("", true);
          this.focusedIndex = -1;
        }
        break;
      default:
        break;
    }
  }

  private handleInput() {
    this.setText(this.input!.value, false);
    this.focusedIndex = -1;
    this.openDropdown();
  }

  private handleChange() {
    this.value = this.input!.value;
    // `change` is not composed: re-dispatch it from the host
    this.dispatchEvent(new Event("change", { bubbles: true }));
    this.emit("minerva-change", { value: this.value });
  }

  private handleBlur(event: FocusEvent) {
    const next = event.relatedTarget as Node | null;
    if (
      next &&
      (this.popup?.contains(next) || this.container?.contains(next))
    ) {
      return;
    }
    this.close();
  }

  private handleOptionClick(option: AutoCompleteOption) {
    if (option.disabled || this.composing) return;
    this.selectOption(option);
    this.input?.focus();
  }

  protected override willUpdate(changed: PropertyValues): void {
    if (changed.has("value") && changed.get("value") !== undefined) {
      this.dirty = this.value !== this.defaultValue || this.dirty;
    }
    // first update: a value set before connecting wins over the default
    // unless the value attribute is present
    if (
      changed.has("defaultValue") &&
      !this.dirty &&
      (this.hasUpdated || this.hasAttribute("value"))
    ) {
      this.value = this.defaultValue;
    }
    // A disabled / read-only field never keeps the dropdown.
    if (this.open && this.blocked) {
      this.open = false;
      this.focusedIndex = -1;
    }
  }

  protected override hookStates() {
    const placement =
      this.shown && this.floating.isOpen
        ? this.floating.position.placement
        : undefined;
    const { side, align } = placement
      ? parsePlacement(placement)
      : { side: undefined, align: undefined };
    return {
      state: this.shown ? "open" : "closed",
      disabled: this.isDisabled,
      readonly: this.readOnly,
      loading: this.loading,
      side,
      align,
      placement,
    };
  }

  protected override updated(changed: PropertyValues): void {
    super.updated(changed);
    this.floating.sync(this.shown);
    // Keep the keyboard-focused option scrolled into view
    if (changed.has("focusedIndex") && this.focusedIndex >= 0) {
      this.shadowRoot
        ?.getElementById(`option-${this.focusedIndex}`)
        ?.scrollIntoView?.({ block: "nearest" });
    }
    if (DEV && changed.has("options")) {
      const seen = new Set<string | number>();
      for (const option of this.options ?? []) {
        if (seen.has(option.value)) {
          devWarn(
            MinervaAutocomplete.tagName,
            `several options have the value "${option.value}"; option values must be unique.`,
          );
          break;
        }
        seen.add(option.value);
      }
    }
  }

  private renderOptionContent(option: AutoCompleteOption) {
    if (this.mode === "custom" && this.renderOption) {
      return this.renderOption(option);
    }
    return html`<div class="basicOption">
      ${option.icon ? html`<span class="icon">${option.icon}</span>` : nothing}
      <div class="content">
        <div class="label">${option.label}</div>
        ${
          option.description
            ? html`<div class="description">${option.description}</div>`
            : nothing
        }
      </div>
    </div>`;
  }

  private renderOptionItem(
    option: AutoCompleteOption,
    index: number,
    activeIndex: number,
  ) {
    const active = activeIndex === index;
    const highlighted = this.hoveredIndex === index || active;
    const disabled = !!option.disabled;
    return html`<div
      part=${itemParts("item", { highlighted, disabled })}
      class=${classMap({
        optionItem: true,
        disabled,
        highlight: !!option.highlight,
        active: highlighted,
      })}
      style=${option.style ? styleMap(option.style) : nothing}
      role="option"
      tabindex="-1"
      id=${`option-${index}`}
      aria-selected=${String(active)}
      aria-disabled=${option.disabled ? "true" : nothing}
      @mousedown=${(event: MouseEvent) => event.preventDefault()}
      @click=${() => this.handleOptionClick(option)}
      @keydown=${(event: KeyboardEvent) => {
        if (event.key !== "Enter" && event.key !== " ") return;
        event.preventDefault();
        event.stopPropagation();
        this.handleOptionClick(option);
      }}
      @mouseenter=${() => (this.hoveredIndex = index)}
      @mouseleave=${() => (this.hoveredIndex = -1)}
    >
      ${this.renderOptionContent(option)}
    </div>`;
  }

  private renderList() {
    const { t } = this.locale;
    if (this.loading) {
      return html`<div role="presentation" class="loading" part="loading">
        <span role="progressbar" aria-label=${t("common.loading")}
          >${IconSpinner}</span
        >
      </div>`;
    }
    const processed = this.processedOptions;
    if (processed.length === 0) {
      return html`<div role="presentation" class="empty" part="empty">
        ${
          this.renderEmpty?.() ||
          html`${IconInbox}<span>${t("empty.description")}</span>`
        }
      </div>`;
    }
    const grouped = this.groupOptions(processed);
    const navigable = grouped ? grouped.flatMap(([, list]) => list) : processed;
    const activeIndex = this.activeIndex(navigable);
    if (!grouped) {
      return processed.map((option, index) =>
        this.renderOptionItem(option, index, activeIndex),
      );
    }
    return grouped.map(([group, list]) => {
      const items = list.map((option) =>
        this.renderOptionItem(option, navigable.indexOf(option), activeIndex),
      );
      return group === ""
        ? items
        : html`<div class="optionGroup" role="group" aria-label=${group}>
            <div class="groupLabel" part="group-label" aria-hidden="true">
              ${group}
            </div>
            ${items}
          </div>`;
    });
  }

  protected override render() {
    const shown = this.shown;
    const disabled = this.isDisabled;
    const navigable = shown ? this.navigableOptions : [];
    const activeIndex = shown ? this.activeIndex(navigable) : -1;
    const activeId =
      shown && activeIndex >= 0 && activeIndex < navigable.length
        ? `option-${activeIndex}`
        : undefined;
    const label = this.label ? undefined : this.aria.label;
    // data-minerva-escape-consumer (core's ESCAPE_CONSUMER_ATTRIBUTE): on a
    // closed list with text, Escape clears it instead of closing an
    // enclosing modal / drawer / popover.
    return html`<div
      part="root"
      class="autoComplete"
      @compositionstart=${() => (this.composing = true)}
      @compositionend=${() => (this.composing = false)}
    >
      ${
        this.label
          ? html`<label for="input" class="label" part="label"
              >${this.label}</label
            >`
          : nothing
      }
      <div
        part="field"
        class=${classMap({
          root: true,
          [this.variant]: true,
          [this.size]: true,
          invalid: this.invalid,
          disabled,
        })}
        data-component="input"
      >
        ${
          this.slots.test("prefix")
            ? html`<span class="addon start"><slot name="prefix"></slot></span>`
            : nothing
        }
        <input
          id="input"
          part="input"
          class="field"
          type="text"
          role="combobox"
          aria-autocomplete="list"
          aria-expanded=${String(shown)}
          aria-controls=${shown ? "listbox" : nothing}
          aria-activedescendant=${activeId ?? nothing}
          aria-label=${label ?? nothing}
          aria-description=${this.aria.description ?? nothing}
          aria-required=${this.required ? "true" : nothing}
          aria-invalid=${
            this.invalid || this.aria.attr("aria-invalid") === "true"
              ? "true"
              : nothing
          }
          data-minerva-escape-consumer=${
            !shown && this.value !== "" ? "" : nothing
          }
          autocomplete="off"
          .value=${live(this.value)}
          placeholder=${this.placeholder || nothing}
          ?disabled=${disabled}
          ?readonly=${this.readOnly}
          @input=${this.handleInput}
          @change=${this.handleChange}
          @focus=${() => this.openDropdown()}
          @click=${() => {
            if (!this.open) this.openDropdown();
          }}
          @blur=${this.handleBlur}
          @keydown=${this.handleKeyDown}
        />
        ${
          this.slots.test("suffix")
            ? html`<span class="addon end"><slot name="suffix"></slot></span>`
            : nothing
        }
      </div>
      ${
        shown
          ? html`<div class="popup" part="content" popover="manual">
              <div
                class=${classMap({
                  dropdown: true,
                  animated: !this.noAnimation,
                })}
              >
                <div
                  class="optionList"
                  part="list"
                  role="listbox"
                  id="listbox"
                  aria-label=${this.label || label || nothing}
                  aria-busy=${this.loading ? "true" : nothing}
                >
                  ${this.renderList()}
                </div>
              </div>
            </div>`
          : nothing
      }
    </div>`;
  }
}

declare global {
  interface HTMLElementTagNameMap {
    "minerva-autocomplete": MinervaAutocomplete;
  }
}

// packages/vue/src/components/AutoComplete/AutoComplete.vue
<script setup lang="ts">
/**
 * AutoComplete: a text input (combobox) that suggests options from a list.
 * Supports grouping, custom rendering (`option` slot) and async loading; the
 * input text is `v-model` (or `defaultValue`). Focus stays in the input
 * (`aria-activedescendant`). For picking several values use `TagInput`.
 */
import {
  computed,
  getCurrentInstance,
  h,
  onMounted,
  ref,
  shallowRef,
  useAttrs,
  useId,
  watch,
  type FunctionalComponent,
  type VNodeChild,
} from "vue";
import { ESCAPE_CONSUMER_ATTRIBUTE } from "@minerva/dom";
import styles from "@react-styles/components/AutoComplete/autoComplete.module.scss";
import FloatingPanel from "../../internal/FloatingPanel.vue";
import { hooks } from "../../internal/hooks";
import { useControllable } from "../../internal/controllable";
import { useFormControlProps } from "../../internal/form-control";
import { Input } from "../Input";
import { Empty } from "../Empty";
import { ProgressIndicator } from "../ProgressIndicator";
import type { AutoCompleteOption, AutoCompleteProps } from "./types";

defineOptions({ name: "AutoComplete", inheritAttrs: false });

const props = withDefaults(defineProps<AutoCompleteProps>(), {
  name: undefined,
  label: undefined,
  mode: "basic",
  modelValue: undefined,
  options: () => [],
  defaultValue: undefined,
  groupBy: undefined,
  loading: false,
  inputProps: undefined,
  emptyProps: undefined,
  dropdownClassName: undefined,
  placement: "bottom",
  offset: () => ({ x: 0, y: 4 }),
  animation: true,
  filterOption: undefined,
  sortOption: undefined,
  autoHighlight: false,
  fillOnSelect: true,
  groupMode: "first",
});

const emit = defineEmits<{
  "update:modelValue": [value: string];
  /** The input text changed (typing or selecting an option) */
  change: [value: string];
  /** An option was picked (mouse or keyboard) */
  select: [option: AutoCompleteOption];
  /** An option was clicked with the mouse */
  optionClick: [option: AutoCompleteOption];
  /** The dropdown opened or closed */
  dropdownVisibleChange: [visible: boolean];
  /**
   * Enter was pressed while no option is active, with the trimmed text
   * (e.g. to run a search); the dropdown closes
   */
  submit: [value: string];
}>();

const slots = defineSlots<{
  /** Custom option content (`mode="custom"`, React `renderOption`) */
  option?: (props: { option: AutoCompleteOption }) => unknown;
  /** Custom content shown when no option matches (React `renderEmpty`) */
  empty?: () => unknown;
}>();

const PLACEMENT = {
  top: "top-start",
  bottom: "bottom-start",
  left: "left-start",
  right: "right-start",
} as const;

const attrs = useAttrs();
const instance = getCurrentInstance();
/** Whether a `submit` listener is bound (React: `onSubmit` is set) */
const hasSubmitListener = () => !!instance?.vnode.props?.onSubmit;
const inputValue = useControllable<string>(props, "modelValue", {
  defaultProp: "defaultValue",
  fallback: "",
  onChange: (next) => emit("change", next),
  name: "AutoComplete",
});

const visible = ref(false);
const setVisible = (next: boolean) => {
  if (visible.value === next) return;
  visible.value = next;
  emit("dropdownVisibleChange", next);
};
const focusedIndex = ref(-1);
const hoveredIndex = ref(-1);
const container = shallowRef<HTMLDivElement | null>(null);
const input = shallowRef<HTMLInputElement | null>(null);
const panel = ref<{ element: HTMLElement | null } | null>(null);
const vertical = computed(
  () => props.placement === "top" || props.placement === "bottom",
);

const baseId = useId();
const listboxId = `${baseId}-listbox`;
// IME composition in progress: Enter / arrows belong to the IME.
let composing = false;
const setComposing = (value: boolean) => {
  composing = value;
};

const inputReadOnly = () =>
  (props.inputProps?.readOnly ?? props.inputProps?.readonly) as
    boolean | undefined;

// FormControl wiring (id, disabled / read-only state). The input's own
// disabled / readOnly props still apply.
const field = useFormControlProps(() => ({
  id: props.inputProps?.id as string | undefined,
  disabled: props.inputProps?.disabled as boolean | undefined,
  readOnly: inputReadOnly(),
}));
const inputId = computed(() => field.value.id ?? `${baseId}-input`);
const blocked = computed(() => field.value.disabled || field.value.readOnly);
// A disabled / read-only field never shows (or keeps) the dropdown.
const shown = computed(() => visible.value && !blocked.value);

function open() {
  if (!blocked.value) setVisible(true);
}
function close() {
  setVisible(false);
  focusedIndex.value = -1;
}

const processedOptions = computed(() => {
  const value = inputValue.value;
  const search = value.toLowerCase();
  const result = props.options.filter((option) =>
    props.filterOption
      ? props.filterOption(value, option)
      : option.label.toLowerCase().includes(search),
  );
  return props.sortOption ? [...result].sort(props.sortOption) : result;
});

/** Groups in order of first appearance, or runs of adjacent options */
const groupedOptions = computed<[string, AutoCompleteOption[]][] | null>(() => {
  const groupBy = props.groupBy;
  if (!groupBy) return null;
  if (props.groupMode === "adjacent") {
    const runs: [string, AutoCompleteOption[]][] = [];
    processedOptions.value.forEach((option) => {
      const group = groupBy(option);
      const last = runs[runs.length - 1];
      if (last && last[0] === group) last[1].push(option);
      else runs.push([group, [option]]);
    });
    return runs;
  }
  const groups = new Map<string, AutoCompleteOption[]>();
  processedOptions.value.forEach((option) => {
    const group = groupBy(option);
    const list = groups.get(group);
    if (list) list.push(option);
    else groups.set(group, [option]);
  });
  return Array.from(groups.entries());
});

/** Options in display order; keyboard / hover indexes refer to this list */
const navigableOptions = computed(() =>
  groupedOptions.value
    ? groupedOptions.value.flatMap(([, list]) => list)
    : processedOptions.value,
);

// With autoHighlight the first enabled option is active until the user
// moves the highlight.
const activeIndex = computed(() =>
  focusedIndex.value >= 0
    ? focusedIndex.value
    : props.autoHighlight && shown.value
      ? navigableOptions.value.findIndex((option) => !option.disabled)
      : -1,
);

function moveFocus(step: 1 | -1) {
  const list = navigableOptions.value;
  const count = list.length;
  if (count === 0) return;
  // from "nothing focused", ArrowDown starts at the first option and
  // ArrowUp at the last one
  let index =
    activeIndex.value >= 0 ? activeIndex.value : step === 1 ? -1 : count;
  for (let i = 0; i < count; i += 1) {
    index = (index + step + count) % count;
    if (!list[index].disabled) {
      focusedIndex.value = index;
      return;
    }
  }
}

function handleOptionSelect(option: AutoCompleteOption) {
  if (option.disabled) return;
  if (props.fillOnSelect) inputValue.value = option.label;
  close();
  emit("select", option);
}

function handleKeyDown(event: KeyboardEvent) {
  if (
    blocked.value ||
    composing ||
    event.isComposing ||
    event.keyCode === 229
  ) {
    return;
  }
  switch (event.key) {
    case "ArrowDown":
      event.preventDefault();
      if (!visible.value) open();
      moveFocus(1);
      break;
    case "ArrowUp":
      event.preventDefault();
      if (!visible.value) open();
      moveFocus(-1);
      break;
    case "Enter": {
      const option = shown.value
        ? navigableOptions.value[activeIndex.value]
        : undefined;
      const text = inputValue.value.trim();
      if (option) {
        event.preventDefault();
        handleOptionSelect(option);
      } else if (hasSubmitListener() && text) {
        // No active option: submit the typed text (e.g. a search).
        event.preventDefault();
        emit("submit", text);
        close();
      }
      break;
    }
    case "Escape":
      // Open: the dropdown's dismissable layer closes it (topmost only).
      // Closed: clears the text (APG combobox), `change("")`.
      if (event !== closingEscape && !shown.value && inputValue.value !== "") {
        event.preventDefault();
        inputValue.value = "";
        focusedIndex.value = -1;
      }
      break;
    default:
      break;
  }
}

function handleInputChange(next: string) {
  inputValue.value = next;
  focusedIndex.value = -1;
  open();
}

function handleBlur(event: FocusEvent) {
  const next = event.relatedTarget as Node | null;
  const dropdown = panel.value?.element;
  if (next && (dropdown?.contains(next) || container.value?.contains(next))) {
    return;
  }
  close();
}

function handleOptionClick(option: AutoCompleteOption) {
  if (option.disabled || composing) return;
  handleOptionSelect(option);
  emit("optionClick", option);
  input.value?.focus();
}

function onOptionKeyDown(event: KeyboardEvent, option: AutoCompleteOption) {
  if (event.key !== "Enter" && event.key !== " ") return;
  event.preventDefault();
  handleOptionClick(option);
}

// Clicking the still-focused input (after a pick or Escape) reopens the
// dropdown; focus alone does not fire again.
function onInputClick() {
  if (!visible.value) open();
}

onMounted(() => {
  input.value = container.value?.querySelector("input") ?? null;
});

const optionId = (index: number) => `${listboxId}-option-${index}`;
const activeOptionId = computed(() =>
  shown.value && activeIndex.value >= 0
    ? optionId(activeIndex.value)
    : undefined,
);

// Keep the keyboard-focused option scrolled into view
watch(
  activeOptionId,
  (id) => {
    if (!id) return;
    const el = container.value?.ownerDocument.getElementById(id);
    el?.scrollIntoView?.({ block: "nearest" });
  },
  { flush: "post" },
);

/** Combobox semantics on the inner <input> (after `inputProps`: they win) */
const inputBindings = computed(() => ({
  ...props.inputProps,
  id: inputId.value,
  disabled: field.value.disabled,
  readOnly: field.value.readOnly,
  name: props.name,
  modelValue: inputValue.value,
  "onUpdate:modelValue": handleInputChange,
  role: "combobox",
  "aria-autocomplete": "list",
  "aria-expanded": String(shown.value),
  "aria-controls": shown.value ? listboxId : undefined,
  "aria-activedescendant": activeOptionId.value,
  // Closed with text: Escape clears it instead of closing an enclosing
  // Modal / Drawer / Popover
  [ESCAPE_CONSUMER_ATTRIBUTE]:
    !shown.value && inputValue.value !== "" ? "" : undefined,
}));

const panelOffset = computed(() => ({
  mainAxis: vertical.value ? props.offset.y : props.offset.x,
  crossAxis: vertical.value ? props.offset.x : props.offset.y,
}));

/**
 * The Escape that closed the dropdown (the layer handles it before the
 * input's own listener, and Vue state updates synchronously): it must not
 * also clear the text.
 */
let closingEscape: KeyboardEvent | null = null;
function onEscapeKeyDown(event: KeyboardEvent) {
  closingEscape = event;
  // Escape during IME composition cancels the composition only
  if (composing || event.isComposing) event.preventDefault();
}

const rootAttrs = computed(() => ({
  ...attrs,
  ...hooks("autocomplete", "root", {
    state: shown.value ? "open" : "closed",
    disabled: field.value.disabled,
    readonly: field.value.readOnly,
    loading: props.loading,
  }),
}));

/** Sections of the list: groups (with a heading unless "") or every option */
const sections = computed(() => {
  const groups = groupedOptions.value;
  if (!groups) {
    return [
      {
        key: "all",
        group: "",
        items: processedOptions.value.map((option, index) => ({
          option,
          index,
        })),
      },
    ];
  }
  const order = navigableOptions.value;
  return groups.map(([group, list], groupIndex) => ({
    key: `${groupIndex}-${group}`,
    group,
    items: list.map((option) => ({ option, index: order.indexOf(option) })),
  }));
});

/** An option of the listbox (`index` in display order) */
const OptionRow: FunctionalComponent<{
  option: AutoCompleteOption;
  index: number;
}> = ({ option, index }) => {
  const active = activeIndex.value === index;
  const highlighted = hoveredIndex.value === index || active;
  const icon = option.icon;
  const content =
    props.mode === "custom" && slots.option
      ? slots.option({ option })
      : h("div", { class: styles.basicOption }, [
          icon
            ? h(
                "span",
                { class: styles.icon },
                (typeof icon === "function"
                  ? (icon as () => VNodeChild)()
                  : icon) as never,
              )
            : null,
          h("div", { class: styles.content }, [
            h("div", { class: styles.label }, option.label),
            option.description
              ? h("div", { class: styles.description }, option.description)
              : null,
          ]),
        ]);
  return h(
    "div",
    {
      class: [
        styles.optionItem,
        option.disabled && styles.disabled,
        option.highlight && styles.highlight,
        highlighted && styles.active,
      ],
      style: option.style,
      role: "option",
      // Focus stays in the input (aria-activedescendant); -1 keeps the
      // option out of the tab order while making it programmatically
      // focusable.
      tabindex: -1,
      id: optionId(index),
      "aria-selected": active,
      "aria-disabled": option.disabled || undefined,
      // keep focus (and the open dropdown) in the input while clicking
      onMousedown: (event: MouseEvent) => event.preventDefault(),
      onClick: () => handleOptionClick(option),
      onKeydown: (event: KeyboardEvent) => onOptionKeyDown(event, option),
      onMouseenter: () => (hoveredIndex.value = index),
      onMouseleave: () => (hoveredIndex.value = -1),
      ...hooks("autocomplete", "item", {
        highlighted,
        disabled: option.disabled,
      }),
    },
    content as never,
  );
};
OptionRow.props = ["option", "index"];
</script>

<template>
  <div
    ref="container"
    :class="styles.autoComplete"
    v-bind="rootAttrs"
    @compositionstart="setComposing(true)"
    @compositionend="setComposing(false)"
  >
    <label
      v-if="label"
      :for="inputId"
      :class="styles.label"
      v-bind="hooks('autocomplete', 'label')"
    >
      {{ label }}
    </label>
    <Input
      v-bind="inputBindings"
      @focus="open"
      @blur="handleBlur"
      @keydown="handleKeyDown"
      @click="onInputClick"
    />

    <FloatingPanel
      ref="panel"
      :open="shown"
      :anchor="container"
      :placement="PLACEMENT[placement]"
      :offset="panelOffset"
      match-anchor-width="min"
      :branches="() => [container]"
      :return-focus-on-escape="() => input"
      :class="[styles.popup, dropdownClassName]"
      v-bind="hooks('autocomplete', 'content', { state: 'open' })"
      @escape-key-down="onEscapeKeyDown"
      @dismiss="close"
    >
      <div :class="[styles.dropdown, animation && styles.animated]">
        <!-- While open the listbox always exists (aria-controls target);
             loading / empty states are presentational rows inside it. -->
        <div
          :id="listboxId"
          :class="styles.optionList"
          role="listbox"
          :aria-label="label"
          :aria-busy="loading || undefined"
          v-bind="hooks('autocomplete', 'list')"
        >
          <div
            v-if="loading"
            role="presentation"
            :class="styles.loading"
            v-bind="hooks('autocomplete', 'loading')"
          >
            <ProgressIndicator />
          </div>
          <template v-else-if="processedOptions.length > 0">
            <template v-for="section in sections" :key="section.key">
              <!-- ungrouped options: no heading -->
              <template v-if="section.group === ''">
                <OptionRow
                  v-for="item in section.items"
                  :key="item.option.value"
                  :option="item.option"
                  :index="item.index"
                />
              </template>
              <div
                v-else
                :class="styles.optionGroup"
                role="group"
                :aria-label="section.group"
              >
                <div
                  :class="styles.groupLabel"
                  aria-hidden="true"
                  v-bind="hooks('autocomplete', 'group-label')"
                >
                  {{ section.group }}
                </div>
                <OptionRow
                  v-for="item in section.items"
                  :key="item.option.value"
                  :option="item.option"
                  :index="item.index"
                />
              </div>
            </template>
          </template>
          <div
            v-else
            role="presentation"
            :class="styles.empty"
            v-bind="hooks('autocomplete', 'empty')"
          >
            <slot name="empty"><Empty v-bind="emptyProps" /></slot>
          </div>
        </div>
      </div>
    </FloatingPanel>
  </div>
</template>
