// packages/lib-web-components/src/components/menu/menu.ts
import { html, type PropertyValues } from "lit";
import { property } from "lit/decorators.js";
import { toPlacement, type Placement } from "@minerva/core";
import { DEV, devWarn } from "../../internal/dev";
import { MenuBase } from "./menu-base";
import {
  MinervaMenuCheckboxItem,
  MinervaMenuGroup,
  MinervaMenuItem,
  MinervaMenuLabel,
  MinervaMenuRadioItem,
  MinervaMenuSeparator,
} from "./menu-items";

export * from "./menu-items";
export {
  SUBMENU_OPEN_DELAY,
  type FocusIntent,
  type MenuChangeReason,
  type MenuSize,
} from "./menu-base";

/** Side of the trigger on which the menu opens */
export type MenuSide = "top" | "right" | "bottom" | "left";

/** Alignment of the menu against the trigger */
export type MenuAlign = "start" | "center" | "end";

const OFFSET = { mainAxis: 6, crossAxis: 0 };

/** Sets / removes an attribute only when it changes (no mutation noise). */
export function setAttr(el: Element, name: string, value: string | null) {
  if (value === null) {
    if (el.hasAttribute(name)) el.removeAttribute(name);
  } else if (el.getAttribute(name) !== value) {
    el.setAttribute(name, value);
  }
}

/**
 * Action menu opened from a trigger button (`<Menu>` of lib-core, WAI-ARIA
 * menu button). Entries come from declarative child elements
 * (`<minerva-menu-item>`, `<minerva-menu-checkbox-item>`,
 * `<minerva-menu-radio-item>`, `<minerva-menu-group>`,
 * `<minerva-menu-separator>`, `<minerva-menu-label>`; nesting items makes
 * submenus) or from the `items` property (lib-core's `MenuEntry` shape).
 *
 * - Trigger: click, Enter, Space or ArrowDown open the menu and focus the
 *   first item (a pointer click focuses the panel); ArrowUp focuses the last.
 * - Inside: arrows (wrapping unless `no-loop`), Home / End, typeahead,
 *   Enter / Space activate; Escape closes the topmost (sub)menu only and
 *   returns focus; Tab closes the menu and moves on from the trigger.
 * - Submenus open with ArrowRight (ArrowLeft in RTL), Enter, Space or hover
 *   (after a short delay) and stay open while the pointer moves towards
 *   them (core pointer grace).
 * - Modal (default): outside pointer events disabled, focus trapped, scroll
 *   locked, the rest of the page hidden from assistive technologies.
 *
 * The panels live in the shadow root in the top layer (`popover="manual"`),
 * so they inherit the theme of the element's scope. The reading direction
 * comes from the closest `dir` attribute (set `dir="rtl"` on the menu or an
 * ancestor).
 *
 * @summary Dropdown action menu with submenus, checkbox / radio items and typeahead.
 * @tag minerva-menu
 * @slot trigger - The button opening the menu (gets `aria-haspopup="menu"`, `aria-expanded`, `data-state`)
 * @csspart menu - A menu panel (root menu and submenus)
 * @csspart item - A menu item
 * @csspart icon - The icon of an item
 * @csspart label - A group / section label
 * @csspart separator - A separator
 * @fires minerva-open-change - The user asked to open / close (`detail: { open, reason }`); cancelable: `preventDefault()` keeps the current state
 * @fires minerva-select - An action item was chosen (`detail: { value, item }`, `value` = the item key / `value`); cancelable: `preventDefault()` keeps the menu open
 * @fires minerva-change - A checkbox item was toggled (`detail: { value, checked, item }`) or a radio option chosen (`detail: { value, group, item }`); cancelable: `preventDefault()` keeps the previous state
 */
export class MinervaMenu extends MenuBase {
  static override tagName = "minerva-menu";
  static override dependencies = [
    MinervaMenuItem,
    MinervaMenuCheckboxItem,
    MinervaMenuRadioItem,
    MinervaMenuGroup,
    MinervaMenuSeparator,
    MinervaMenuLabel,
  ];

  /** Preferred side; the menu flips when there is not enough room */
  @property({ reflect: true })
  side: MenuSide = "bottom";

  /** Alignment of the menu against the trigger */
  @property({ reflect: true })
  align: MenuAlign = "end";

  /** Disabled attribute added to the trigger by the menu */
  private disabledTrigger: Element | null = null;

  private triggerElement(): HTMLElement | null {
    return this.querySelector<HTMLElement>(":scope > [slot='trigger']");
  }

  protected override anchorElement() {
    return this.triggerElement();
  }

  override rootPlacement(): Placement {
    return toPlacement(this.side, this.align);
  }

  override rootOffset() {
    return OFFSET;
  }

  protected override restoreTarget() {
    return this.triggerElement();
  }

  protected override branches() {
    return [this.triggerElement()];
  }

  protected override rootLabel() {
    const own = this.getAttribute("aria-label");
    if (own) return own;
    const trigger = this.triggerElement();
    return (
      trigger?.getAttribute("aria-label") ??
      (trigger?.textContent?.trim() || undefined)
    );
  }

  protected override syncTrigger() {
    const trigger = this.triggerElement();
    if (!trigger) return;
    setAttr(trigger, "aria-haspopup", "menu");
    setAttr(trigger, "aria-expanded", String(this.open));
    setAttr(trigger, "data-state", this.open ? "open" : "closed");
    setAttr(trigger, "data-disabled", this.disabled ? "" : null);
    if (this.disabled && !trigger.hasAttribute("disabled")) {
      trigger.setAttribute("disabled", "");
      this.disabledTrigger = trigger;
    } else if (!this.disabled && this.disabledTrigger === trigger) {
      trigger.removeAttribute("disabled");
      this.disabledTrigger = null;
    }
  }

  private fromTrigger(event: Event): boolean {
    const trigger = this.triggerElement();
    return !!trigger && event.composedPath().includes(trigger);
  }

  private readonly handleKeyDown = (event: KeyboardEvent) => {
    if (this.disabled || event.defaultPrevented || !this.fromTrigger(event)) {
      return;
    }
    switch (event.key) {
      case "Enter":
      case " ":
        event.preventDefault();
        if (this.open) this.requestOpenChange(false, "trigger");
        else this.openWith("first", "keyboard");
        break;
      case "ArrowDown":
        event.preventDefault();
        this.openWith("first", "keyboard");
        break;
      case "ArrowUp":
        event.preventDefault();
        this.openWith("last", "keyboard");
        break;
    }
  };

  private readonly handleClick = (event: MouseEvent) => {
    if (this.disabled || event.defaultPrevented || !this.fromTrigger(event)) {
      return;
    }
    if (this.open) this.requestOpenChange(false, "trigger");
    // detail 0: a keyboard / programmatic click
    else this.openWith(event.detail === 0 ? "first" : "content", "trigger");
  };

  override connectedCallback(): void {
    super.connectedCallback();
    this.addEventListener("keydown", this.handleKeyDown);
    this.addEventListener("click", this.handleClick);
  }

  override disconnectedCallback(): void {
    super.disconnectedCallback();
    this.removeEventListener("keydown", this.handleKeyDown);
    this.removeEventListener("click", this.handleClick);
  }

  protected override firstUpdated(changed: PropertyValues): void {
    super.firstUpdated(changed);
    if (DEV && !this.triggerElement()) {
      devWarn(
        MinervaMenu.tagName,
        'no slot="trigger" element: nothing opens the menu (add e.g. <button slot="trigger">).',
      );
    }
  }

  protected override render() {
    return html`<slot name="trigger"></slot>${this.renderPanels()}`;
  }
}

declare global {
  interface HTMLElementTagNameMap {
    "minerva-menu": MinervaMenu;
  }
}

// packages/vue/src/components/Menu/Menu.vue
<script setup lang="ts">
/**
 * Menu: an action menu opened from a trigger button (WAI-ARIA menu button).
 * Supports icons, shortcuts, separators, groups, checkbox items, radio
 * groups, submenus, typeahead and full keyboard navigation. For a
 * select-like list of options see Select.
 *
 * - Trigger (the single child of the `trigger` slot, or of the default
 *   slot): click, Enter, Space or ArrowDown open the menu and focus the
 *   first item (a pointer click focuses the panel); ArrowUp focuses the last.
 * - Inside: arrows (wrapping with `loop`), Home / End, typeahead, Enter /
 *   Space activate; Escape closes (a submenu only) and returns focus; Tab
 *   closes the menu and moves on from the trigger.
 * - Submenus open with ArrowRight (ArrowLeft in RTL), Enter, Space or hover,
 *   and stay open while the pointer moves towards them.
 * - `modal` (default): outside pointer events disabled, focus trapped,
 *   scroll locked, the rest of the page hidden from assistive technology.
 *
 * Attributes (`class`, `style`, `data-*`...) go to the menu panel.
 */
import { computed, shallowRef, useId } from "vue";
import { toPlacement } from "@minerva/dom";
import { useControllable } from "../../internal/controllable";
import { useInheritedDirection } from "../../internal/direction";
import { useLayerParent } from "../../internal/scope";
import { unrefElement } from "../../internal/Slot";
import { MenuRoot, TriggerSlot, type FocusIntent } from "./MenuItems";
import type { MenuAction, MenuProps } from "./types";

defineOptions({ name: "Menu", inheritAttrs: false });

const props = withDefaults(defineProps<MenuProps>(), {
  closeOnSelect: true,
  size: "medium",
  align: "end",
  side: "bottom",
  open: undefined,
  defaultOpen: undefined,
  disabled: false,
  modal: true,
  loop: true,
  dir: undefined,
  ariaLabel: undefined,
});
const emit = defineEmits<{
  "update:open": [open: boolean];
  /** The menu opens or closes */
  openChange: [open: boolean];
  /** An action was selected (the original item object) */
  select: [item: MenuAction];
}>();
defineSlots<{
  /** The trigger element (its single child gets the trigger props) */
  trigger?: () => unknown;
  /** Alternative to the `trigger` slot */
  default?: () => unknown;
}>();

const OFFSET = { mainAxis: 6, crossAxis: 0 };

const open = useControllable<boolean>(props, "open", {
  fallback: false,
  name: "Menu",
  onChange: (value) => emit("openChange", value),
});
const trigger = shallowRef<HTMLElement | null>(null);
const setTrigger = (value: unknown) => {
  trigger.value = unrefElement(value);
};
// Without `dir`, the menu (teleported out of the trigger's subtree) follows
// the reading direction inherited by the trigger, read when it opens.
const inheritedDir = useInheritedDirection(
  trigger,
  () => open.value && props.dir === undefined,
);
const dir = computed(() => props.dir ?? inheritedDir.value);
const tabContainer = useLayerParent();
const generatedId = useId();
const contentId = useId();
const placement = computed(() => toPlacement(props.side, props.align));

let intent: FocusIntent = "content";
const consumeIntent = () => {
  const value = intent;
  intent = "content";
  return value;
};
const getRestoreTarget = () => trigger.value;
const setOpen = (value: boolean) => {
  open.value = value;
};
const openWith = (next: FocusIntent) => {
  intent = next;
  setOpen(true);
};

const onKeydown = (event: KeyboardEvent) => {
  if (props.disabled || event.defaultPrevented) return;
  switch (event.key) {
    case "Enter":
    case " ":
      event.preventDefault();
      if (open.value) setOpen(false);
      else openWith("first");
      break;
    case "ArrowDown":
      event.preventDefault();
      openWith("first");
      break;
    case "ArrowUp":
      event.preventDefault();
      openWith("last");
      break;
  }
};

const onClick = (event: MouseEvent) => {
  if (props.disabled || event.defaultPrevented) return;
  if (open.value) setOpen(false);
  // detail 0: a keyboard / programmatic click
  else openWith(event.detail === 0 ? "first" : "content");
};

const selectItem = (item: MenuAction) => emit("select", item);
</script>

<template>
  <TriggerSlot
    :ref="setTrigger"
    hook-component="menu"
    :hook-open="open"
    :hook-disabled="disabled"
    :id="generatedId"
    aria-haspopup="menu"
    :aria-expanded="open ? 'true' : 'false'"
    :aria-controls="open ? contentId : undefined"
    :disabled="disabled || undefined"
    @keydown="onKeydown"
    @click="onClick"
  >
    <slot name="trigger"><slot /></slot>
  </TriggerSlot>
  <MenuRoot
    component="menu"
    :items="items"
    :close-on-select="closeOnSelect"
    :size="size"
    :loop="loop"
    :dir="dir"
    :modal="modal"
    :aria-label="ariaLabel"
    :labelled-by="trigger?.id || generatedId"
    :open="open && !disabled"
    :set-open="setOpen"
    :select-item="selectItem"
    :anchor="trigger"
    :placement="placement"
    :offset="OFFSET"
    :content-id="contentId"
    :trigger="trigger"
    :get-restore-target="getRestoreTarget"
    :consume-intent="consumeIntent"
    :tab-container="tabContainer ?? null"
    :panel-attrs="$attrs"
  />
</template>
