// packages/vue/src/components/CodeBlock/CodeBlock.vue
<script setup lang="ts">
/**
 * CodeBlock: a read-only block of preformatted text (logs, payloads,
 * config). It is a named, keyboard-focusable region so its overflow can be
 * scrolled without a mouse (WCAG 2.1.1, axe scrollable-region-focusable).
 * With `copyable`, a copy button (top-right) writes the text to the
 * clipboard and a visually hidden polite live region announces the result.
 */
import { computed, onBeforeUnmount, ref, useAttrs, type StyleValue } from "vue";
import styles from "@react-styles/components/CodeBlock/codeBlock.module.scss";
import { hooks } from "../../internal/hooks";
import { IconCheck, IconCopy, IconX } from "../../internal/icons";
import { useI18n } from "../../config/useI18n";
import { IconButton } from "../IconButton";
import type { CodeBlockProps } from "./types";

defineOptions({ name: "CodeBlock", inheritAttrs: false });

const props = withDefaults(defineProps<CodeBlockProps>(), {
  code: undefined,
  wrap: true,
  maxHeight: "24rem",
  copyable: false,
});

const emit = defineEmits<{
  /** The copy button wrote the text to the clipboard (not on failure) */
  copied: [text: string];
}>();

const slots = defineSlots<{
  /** Source text (when the `code` prop is not set) */
  default?: () => unknown;
}>();

/** How long the "Copied" / "Copy failed" feedback stays visible (ms). */
const COPY_FEEDBACK_MS = 2000;

const attrs = useAttrs();
const { t } = useI18n();
const status = ref<"idle" | "copied" | "failed">("idle");
const pre = ref<HTMLPreElement | null>(null);
let timer: ReturnType<typeof setTimeout> | undefined;
let mounted = true;
onBeforeUnmount(() => {
  mounted = false;
  clearTimeout(timer);
});

const showStatus = (next: "copied" | "failed") => {
  if (!mounted) return;
  clearTimeout(timer);
  status.value = next;
  timer = setTimeout(() => {
    status.value = "idle";
  }, COPY_FEEDBACK_MS);
};

/** The verbatim text: the `code` prop, else the rendered slot text */
const sourceText = () =>
  props.code ?? pre.value?.querySelector("code")?.textContent ?? "";

const copy = async () => {
  const text = sourceText();
  const clipboard =
    typeof navigator === "undefined" ? undefined : navigator.clipboard;
  if (typeof clipboard?.writeText !== "function") {
    showStatus("failed");
    return;
  }
  try {
    await clipboard.writeText(text);
  } catch {
    showStatus("failed");
    return;
  }
  showStatus("copied");
  emit("copied", text);
};

const REGION_ATTRS = [
  "aria-label",
  "aria-labelledby",
  "aria-describedby",
  "tabindex",
  "tabIndex",
];
const regionAttrs = computed(() => {
  const ariaLabelledBy = attrs["aria-labelledby"];
  return {
    role: "region",
    tabindex: attrs.tabindex ?? attrs.tabIndex ?? 0,
    "aria-label":
      attrs["aria-label"] ??
      (ariaLabelledBy !== undefined ? undefined : t("codeBlock.label")),
    "aria-labelledby": ariaLabelledBy,
    "aria-describedby": attrs["aria-describedby"],
    "data-wrap": String(props.wrap),
  };
});
const otherAttrs = computed(() => {
  const rest: Record<string, unknown> = {};
  for (const [key, value] of Object.entries(attrs)) {
    if (!REGION_ATTRS.includes(key) && key !== "style") rest[key] = value;
  }
  return rest;
});
const boxStyle = computed<StyleValue>(() => [
  {
    maxHeight:
      typeof props.maxHeight === "number"
        ? `${props.maxHeight}px`
        : props.maxHeight,
  },
  attrs.style as StyleValue,
]);
const statusText = computed(() =>
  status.value === "copied"
    ? t("codeBlock.copied")
    : status.value === "failed"
      ? t("codeBlock.copyFailed")
      : "",
);
const buttonColor = computed(() =>
  status.value === "failed"
    ? "danger"
    : status.value === "copied"
      ? "success"
      : "neutral",
);
</script>

<template>
  <pre
    v-if="!copyable"
    ref="pre"
    :class="styles.codeBlock"
    :style="boxStyle"
    v-bind="{
      ...regionAttrs,
      ...otherAttrs,
      ...hooks('code-block', 'region'),
    }"
  ><code v-bind="hooks('code-block', 'code')"><template v-if="code !== undefined">{{ code }}</template><slot v-else-if="slots.default" /></code></pre>
  <div
    v-else
    v-bind="{ ...otherAttrs, ...hooks('code-block', 'root') }"
    :class="styles.root"
    :style="boxStyle"
  >
    <pre
      ref="pre"
      v-bind="{ ...regionAttrs, ...hooks('code-block', 'region') }"
      :class="[styles.codeBlock, styles.copyable]"
    ><code v-bind="hooks('code-block', 'code')"><template v-if="code !== undefined">{{ code }}</template><slot v-else-if="slots.default" /></code></pre>
    <div :class="styles.actions">
      <IconButton
        type="button"
        :label="statusText || t('codeBlock.copy')"
        size="small"
        shape="square"
        :color="buttonColor"
        @click="copy"
      >
        <IconCheck v-if="status === 'copied'" :size="16" />
        <IconX v-else-if="status === 'failed'" :size="16" />
        <IconCopy v-else :size="16" />
      </IconButton>
    </div>
    <span :class="styles.visuallyHidden" aria-live="polite">{{
      statusText
    }}</span>
  </div>
</template>

// packages/lib-web-components/src/components/code-block/code-block.ts
import { css, html, nothing, unsafeCSS } from "lit";
import { property, state } from "lit/decorators.js";
import { classMap } from "lit/directives/class-map.js";
import { styleMap } from "lit/directives/style-map.js";
import styles from "@lib-core-styles/components/CodeBlock/codeBlock.module.scss?inline";
import iconButtonStyles from "@lib-core-styles/components/IconButton/iconButton.module.scss?inline";
import { AriaController } from "../../internal/aria";
import { DEV, devWarn } from "../../internal/dev";
import { IconCheck, IconCopy, IconX } from "../../internal/icons";
import { LocaleController } from "../../internal/locale";
import { MinervaElement, hostStyles } from "../../internal/minerva-element";
import { HasSlotController } from "../../internal/slots";

/** How long the "Copied" / "Copy failed" feedback stays visible (ms). */
const COPY_FEEDBACK_MS = 2000;

/** Result of the last copy */
export type CodeBlockCopyStatus = "idle" | "copied" | "failed";

const toCss = (value: string | number | undefined) =>
  value === undefined || value === ""
    ? undefined
    : typeof value === "number" || /^\d+(\.\d+)?$/.test(value)
      ? `${value}px`
      : value;

/**
 * A read-only block of preformatted text: logs, payloads, configuration
 * (`<CodeBlock>` of lib-core). It is a named, keyboard-focusable region so
 * its overflow can be scrolled without a mouse.
 *
 * The text is the `code` property, else the element's text content
 * (rendered verbatim, never parsed as HTML; escape `<` in markup or set
 * `code`). `language` shows a small language label and sets
 * `class="language-<x>"` / `data-language` on the `<code>`. With
 * `copyable`, a copy button writes the text to the clipboard; its label
 * switches to "Copied" / "Copy failed" for two seconds and the result is
 * announced through a polite live region.
 *
 * @summary Read-only, scrollable code region with optional copy button.
 * @tag minerva-code-block
 * @csspart base - The outer wrapper (copyable / labelled blocks)
 * @csspart region - The `<pre>` region
 * @csspart code - The `<code>` element
 * @csspart language - The language label
 * @csspart copy-button - The copy button
 * @fires minerva-copy - The copy button was used (`detail: { value, success }`)
 */
export class MinervaCodeBlock extends MinervaElement {
  static override tagName = "minerva-code-block";
  static override styles = [
    hostStyles,
    css`
      :host {
        display: block;
        min-width: 0;
        max-width: 100%;
      }
      .actions {
        align-items: center;
        gap: var(--space-2);
      }
      .language {
        color: var(--text-muted-color);
        font-family: var(--font-family-mono);
        font-size: var(--font-size-xs);
        line-height: 1;
        user-select: none;
      }
      .iconButton svg {
        width: 16px;
        height: 16px;
      }
    `,
    unsafeCSS(iconButtonStyles),
    unsafeCSS(styles),
  ];

  /** Source text (default: the element's text content) */
  @property()
  code?: string;

  /** Language of the code, shown as a label (e.g. "json", "bash") */
  @property({ reflect: true })
  language?: string;

  /** Scrolls long lines horizontally instead of wrapping them (lib-core's `wrap={false}`) */
  @property({ type: Boolean, attribute: "no-wrap", reflect: true })
  noWrap = false;

  /** Maximum height before the block scrolls (CSS value, numbers are pixels) */
  @property({ attribute: "max-height" })
  maxHeight = "24rem";

  /** Shows a copy button writing the text to the clipboard */
  @property({ type: Boolean, reflect: true })
  copyable = false;

  @state()
  private status: CodeBlockCopyStatus = "idle";

  private timer?: ReturnType<typeof setTimeout>;
  private readonly locale = new LocaleController(this);
  private readonly aria = new AriaController(this);
  // re-renders when the text content changes
  private readonly slots = new HasSlotController(this);

  /** The text shown (and copied) */
  get text(): string {
    return this.code ?? this.textContent ?? "";
  }

  /** Copies the text to the clipboard; resolves with whether it worked */
  async copy(): Promise<boolean> {
    const text = this.text;
    const clipboard =
      typeof navigator === "undefined" ? undefined : navigator.clipboard;
    let success = false;
    if (typeof clipboard?.writeText === "function") {
      try {
        await clipboard.writeText(text);
        success = true;
      } catch {
        success = false;
      }
    }
    if (!this.isConnected) return success;
    this.showStatus(success ? "copied" : "failed");
    this.emit("minerva-copy", { value: text, success });
    return success;
  }

  private showStatus(next: CodeBlockCopyStatus) {
    clearTimeout(this.timer);
    this.status = next;
    this.timer = setTimeout(() => (this.status = "idle"), COPY_FEEDBACK_MS);
  }

  override disconnectedCallback(): void {
    super.disconnectedCallback();
    clearTimeout(this.timer);
    this.status = "idle";
  }

  protected override updated(): void {
    if (DEV && this.copyable && !this.text.trim()) {
      devWarn(
        MinervaCodeBlock.tagName,
        "copyable is set but there is no text to copy (set code or the text content).",
      );
    }
  }

  protected override render() {
    void this.slots;
    const t = this.locale.t;
    const label = this.aria.label ?? t("codeBlock.label");
    const maxHeight = toCss(this.maxHeight);
    const wrapped = this.copyable || !!this.language;
    const region = html`<pre
      part="region"
      role="region"
      tabindex="0"
      aria-label=${label}
      aria-description=${this.aria.description ?? nothing}
      data-wrap=${String(!this.noWrap)}
      class=${classMap({ codeBlock: true, copyable: wrapped })}
      style=${styleMap(wrapped ? {} : { maxHeight })}
    ><code
        part="code"
        class=${this.language ? `language-${this.language}` : nothing}
        data-language=${this.language ?? nothing}
      >${this.text}</code></pre>`;

    if (!wrapped) return region;

    const status = this.status;
    const statusText =
      status === "copied"
        ? t("codeBlock.copied")
        : status === "failed"
          ? t("codeBlock.copyFailed")
          : "";
    const buttonLabel = statusText || t("codeBlock.copy");
    const color =
      status === "failed"
        ? "danger"
        : status === "copied"
          ? "success"
          : "neutral";

    return html`<div part="base" class="root" style=${styleMap({ maxHeight })}>
      ${region}
      <div class="actions">
        ${
          this.language
            ? html`<span part="language" class="language" aria-hidden="true"
                >${this.language}</span
              >`
            : nothing
        }
        ${
          this.copyable
            ? html`<button
                type="button"
                part="copy-button"
                class="iconButton ${color} variant-ghost small square"
                aria-label=${buttonLabel}
                title=${buttonLabel}
                @click=${() => void this.copy()}
              >
                ${
                  status === "copied"
                    ? IconCheck
                    : status === "failed"
                      ? IconX
                      : IconCopy
                }
              </button>`
            : nothing
        }
      </div>
      ${
        this.copyable
          ? html`<span class="visuallyHidden" aria-live="polite"
              >${statusText}</span
            >`
          : nothing
      }
    </div>`;
  }
}

declare global {
  interface HTMLElementTagNameMap {
    "minerva-code-block": MinervaCodeBlock;
  }
}
