// packages/angular/monaco/index.ts
/** Optional Monaco entry: importing the standard Angular entry never loads Monaco. */
import {
  ChangeDetectionStrategy,
  Component,
  DestroyRef,
  ElementRef,
  afterNextRender,
  effect,
  inject,
  input,
  model,
  output,
  signal,
  viewChild,
} from "@angular/core";
import type * as Monaco from "monaco-editor";
import { injectMinerva } from "@minerva/angular";
export type MonacoModule = typeof Monaco;
export type MonacoLoader = () => Promise<MonacoModule>;
export const MONACO_ENTRY = "minerva-design/angular/monaco";

@Component({
  selector: "mn-monaco-code-editor",
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: {
    "data-minerva": "code-editor",
    "data-part": "root",
    "[attr.data-disabled]": "disabled() ? '' : null",
    "[attr.data-loading]": "loading() ? '' : null",
  },
  template: `<span data-minerva="code-editor" data-part="label">{{
      label()
    }}</span>
    <div
      #surface
      data-minerva="code-editor"
      data-part="surface"
      [style.height]="height()"
      [hidden]="!ready()"
      [attr.aria-label]="label()"
    ></div>
    @if (!ready()) {
      <textarea
        data-minerva="code-editor"
        data-part="fallback"
        [attr.aria-label]="label()"
        [value]="value()"
        [disabled]="disabled()"
        [readOnly]="readOnly()"
        (input)="editFallback($event)"
        [style.height]="height()"
      ></textarea>
    }
    @if (loading()) {
      <span data-minerva="code-editor" data-part="loading" role="status">
        {{ loadingLabel() ?? scope.t("monacoCodeEditor.loading") }}
      </span>
    }
    @if (error()) {
      <div data-minerva="code-editor" data-part="error" role="alert">
        {{ error() }}
        <button
          type="button"
          (click)="load()"
          [attr.aria-label]="
            retryLabel() ?? scope.t('monacoCodeEditor.retryLabel')
          "
        >
          {{ retryLabel() ?? scope.t("monacoCodeEditor.retry") }}
        </button>
      </div>
    }`,
})
export class MnMonacoCodeEditor {
  readonly monaco = input<MonacoModule>();
  readonly theme = input<string>();
  readonly value = model("");
  readonly language = input("plaintext");
  readonly label = input("Code editor");
  /** Accessible status while the engine loads; defaults to the scoped locale. */
  readonly loadingLabel = input<string>();
  /** Retry action label after an engine error; defaults to the scoped locale. */
  readonly retryLabel = input<string>();
  readonly height = input("300px");
  readonly disabled = input(false);
  readonly readOnly = input(false);
  readonly options = input<Monaco.editor.IStandaloneEditorConstructionOptions>(
    {},
  );
  readonly loader = input<MonacoLoader>(() => import("monaco-editor"));
  readonly editorReady = output<Monaco.editor.IStandaloneCodeEditor>();
  readonly loadError = output<unknown>();
  protected readonly surface =
    viewChild.required<ElementRef<HTMLElement>>("surface");
  protected readonly loading = signal(true);
  protected readonly ready = signal(false);
  protected readonly error = signal("");
  private instance: Monaco.editor.IStandaloneCodeEditor | undefined;
  private engine: MonacoModule | undefined;
  protected readonly scope = injectMinerva();
  private subscription: Monaco.IDisposable | undefined;
  private generation = 0;
  private destroyed = false;
  constructor() {
    afterNextRender(() => void this.load());
    effect(() => {
      const ready = this.ready();
      const theme =
        this.theme() ??
        (this.scope.resolvedMode() === "dark" ? "vs-dark" : "vs");
      const value = this.value();
      const language = this.language();
      const ariaLabel = this.label();
      const options = this.options();
      const readOnly = this.disabled() || this.readOnly();
      if (ready && this.instance) {
        this.engine?.editor.setTheme(theme);
        if (this.instance.getValue() !== value) this.instance.setValue(value);
        this.instance.updateOptions({
          ...options,
          readOnly,
          domReadOnly: readOnly,
          ariaLabel,
        });
        const model = this.instance.getModel();
        if (model) this.engine?.editor.setModelLanguage(model, language);
      }
    });
    inject(DestroyRef).onDestroy(() => {
      this.destroyed = true;
      this.generation++;
      this.dispose();
    });
  }
  private dispose() {
    this.subscription?.dispose();
    const model = this.instance?.getModel();
    this.instance?.dispose();
    model?.dispose();
    this.instance = undefined;
    this.ready.set(false);
  }
  async load() {
    const generation = ++this.generation;
    this.dispose();
    this.loading.set(true);
    this.error.set("");
    try {
      const monaco = this.monaco() ?? (await this.loader()());
      if (this.destroyed || generation !== this.generation) return;
      this.engine = monaco;
      this.instance = monaco.editor.create(this.surface().nativeElement, {
        ...this.options(),
        value: this.value(),
        language: this.language(),
        theme:
          this.theme() ??
          (this.scope.resolvedMode() === "dark" ? "vs-dark" : "vs"),
        readOnly: this.disabled() || this.readOnly(),
        domReadOnly: this.disabled() || this.readOnly(),
        automaticLayout: true,
        ariaLabel: this.label(),
      });
      this.subscription = this.instance.onDidChangeModelContent(() => {
        if (!this.disabled() && !this.readOnly())
          this.value.set(this.instance!.getValue());
      });
      this.ready.set(true);
      this.editorReady.emit(this.instance);
    } catch (error) {
      if (this.destroyed || generation !== this.generation) return;
      this.error.set(error instanceof Error ? error.message : String(error));
      this.loadError.emit(error);
    } finally {
      if (!this.destroyed && generation === this.generation)
        this.loading.set(false);
    }
  }
  protected editFallback(event: Event) {
    if (!this.disabled() && !this.readOnly())
      this.value.set((event.target as HTMLTextAreaElement).value);
  }
}

// packages/taro/src/monaco.tsx
import { useEffect, useRef, useState, useId } from "react";
import type * as Monaco from "monaco-editor";
import { useI18n, useOptionalTheme } from "./theme";
import { Button } from "./components";
export interface MonacoCodeEditorProps {
  monaco?: typeof Monaco;
  value: string;
  onChange?: (value: string) => void;
  label: string;
  language?: string;
  height?: number;
  minHeight?: number;
  maxHeight?: number;
  disabled?: boolean;
  theme?: "light" | "dark";
  loadTimeout?: number;
  unavailableText?: string;
  retryText?: string;
  retryLabel?: string;
  loadingLabel?: string;
  className?: string;
  style?: React.CSSProperties;
}
const positive = (n: number, fallback: number) =>
  Number.isFinite(n) && n > 0 ? n : fallback;
/** Optional H5 entry. The application supplies its local Monaco engine and worker configuration. */
export function MonacoCodeEditor({
  monaco,
  value,
  onChange,
  label,
  language = "plaintext",
  height = 420,
  minHeight = 160,
  maxHeight = 800,
  disabled = false,
  theme,
  loadTimeout = 10000,
  unavailableText,
  retryText,
  retryLabel,
  loadingLabel,
  className,
  style,
}: MonacoCodeEditorProps) {
  const { t } = useI18n(),
    config = useOptionalTheme(),
    id = useId();
  const root = useRef<HTMLDivElement>(null),
    host = useRef<HTMLDivElement>(null),
    editor = useRef<Monaco.editor.IStandaloneCodeEditor | null>(null),
    subscription = useRef<Monaco.IDisposable | undefined>(),
    syncing = useRef(false);
  const [attempt, retry] = useState(0),
    [state, setState] = useState<"loading" | "ready" | "error">("loading"),
    [pageTheme, setPageTheme] = useState<"light" | "dark">("light");
  const resolvedTheme = theme ?? config?.resolvedTheme ?? pageTheme;
  const latest = useRef({
    value,
    onChange,
    disabled,
    language,
    label,
    resolvedTheme,
  });
  latest.current = {
    value,
    onChange,
    disabled,
    language,
    label,
    resolvedTheme,
  };
  const dispose = () => {
    subscription.current?.dispose();
    subscription.current = undefined;
    const model = editor.current?.getModel();
    editor.current?.dispose();
    editor.current = null;
    model?.dispose();
  };
  const fail = () => {
    dispose();
    setState("error");
  };
  useEffect(() => {
    const read = () =>
      setPageTheme(
        root.current?.closest("[data-theme]")?.getAttribute("data-theme") ===
          "dark"
          ? "dark"
          : "light",
      );
    read();
    const observer = new MutationObserver(read);
    observer.observe(document.documentElement, {
      attributes: true,
      subtree: true,
      attributeFilter: ["data-theme"],
    });
    return () => observer.disconnect();
  }, []);
  useEffect(() => {
    let active = true;
    dispose();
    setState("loading");
    const timer = setTimeout(
      () => {
        if (active && !editor.current) fail();
      },
      positive(loadTimeout, 10000),
    );
    if (monaco && host.current) {
      try {
        const p = latest.current;
        editor.current = monaco.editor.create(host.current, {
          value: p.value,
          language: p.language,
          readOnly: p.disabled,
          domReadOnly: p.disabled,
          theme: p.resolvedTheme === "dark" ? "vs-dark" : "vs",
          automaticLayout: true,
          ariaLabel: p.label,
          minimap: { enabled: false },
          wordWrap: "on",
          scrollBeyondLastLine: false,
        });
        subscription.current = editor.current.onDidChangeModelContent(() => {
          if (!syncing.current && !latest.current.disabled)
            latest.current.onChange?.(editor.current!.getValue());
        });
        host.current.querySelector("textarea")?.setAttribute("id", id);
        setState("ready");
        clearTimeout(timer);
      } catch {
        clearTimeout(timer);
        fail();
      }
    }
    return () => {
      active = false;
      clearTimeout(timer);
      dispose();
    };
  }, [monaco, attempt, loadTimeout, id]);
  useEffect(() => {
    if (!editor.current || editor.current.getValue() === value) return;
    syncing.current = true;
    try {
      editor.current.setValue(value);
    } catch {
      fail();
    } finally {
      syncing.current = false;
    }
  }, [value]);
  useEffect(() => {
    const e = editor.current;
    if (!e) return;
    try {
      e.updateOptions({
        readOnly: disabled,
        domReadOnly: disabled,
        ariaLabel: label,
      });
      const model = e.getModel();
      if (model) monaco?.editor.setModelLanguage(model, language);
      monaco?.editor.setTheme(resolvedTheme === "dark" ? "vs-dark" : "vs");
    } catch {
      fail();
    }
  }, [disabled, label, language, resolvedTheme, monaco]);
  if (typeof document === "undefined")
    throw new Error(
      "MonacoCodeEditor requires an H5 browser host. Use Textarea for native source editing.",
    );
  const min = positive(minHeight, 160),
    frameHeight = Math.min(
      Math.max(min, positive(maxHeight, 800)),
      Math.max(min, positive(height, 420)),
    );
  return (
    <div
      ref={root}
      className={["mn-monaco-root", className].filter(Boolean).join(" ")}
      style={style}
      role="group"
      aria-label={label}
      data-minerva="code-editor"
      data-part="root"
    >
      <label
        htmlFor={id}
        className="mn-monaco-label"
        onClick={() => editor.current?.focus()}
      >
        {label}
      </label>
      <div
        className="mn-monaco-surface"
        style={{ height: frameHeight }}
        aria-busy={state === "loading"}
      >
        <div
          ref={host}
          style={{
            height: "100%",
            width: "100%",
            display: state === "error" ? "none" : undefined,
          }}
        />
        {state === "loading" && (
          <span className="mn-monaco-loading" role="status">
            {loadingLabel ?? t("monacoCodeEditor.loading")}
          </span>
        )}
        {state === "error" && (
          <>
            <div className="mn-monaco-error">
              <p className="mn-monaco-message" role="alert">
                {unavailableText ?? t("monacoCodeEditor.unavailable")}
              </p>
              <Button
                color="neutral"
                variant="outline"
                size="small"
                aria-label={retryLabel ?? t("monacoCodeEditor.retryLabel")}
                onClick={() => retry((v) => v + 1)}
              >
                {retryText ?? t("monacoCodeEditor.retry")}
              </Button>
            </div>
            <textarea
              id={id}
              className="mn-monaco-fallback"
              aria-label={label}
              value={value}
              disabled={disabled}
              spellCheck={false}
              onChange={(event) => {
                if (!disabled) onChange?.(event.currentTarget.value);
              }}
            />
          </>
        )}
      </div>
    </div>
  );
}
