// packages/angular/src/testing/styling-hooks/button.ts
import { Component } from "@angular/core";
import { MnButton } from "../../components/button";
import type { HookScenario } from "../types";

@Component({
  imports: [MnButton],
  template: ` <ng-template #icon><svg aria-hidden="true"></svg></ng-template>
    <button
      mnButton
      [startIcon]="icon"
      [endIcon]="icon"
      size="small"
      variant="outline"
      color="danger"
      shape="circle"
      active
    >
      Save
    </button>
    <button mnButton disabled>Off</button>
    <button mnButton loading>Busy</button>`,
})
class Every {}

export default [
  { name: "icons, every key, active, disabled, loading", component: Every },
] satisfies HookScenario[];

// packages/react/src/test-utils/styling-hooks/button.tsx
import { Button } from "../../components/Button";
import type { HookScenario } from "./types";

const Icon = () => <svg aria-hidden="true" />;

export default [
  { name: "default", element: <Button>Save</Button> },
  {
    name: "icons, active, every key",
    element: (
      <Button
        active
        shape="rounded"
        size="small"
        variant="ghost"
        color="danger"
        startIcon={<Icon />}
        endIcon={<Icon />}
      >
        Delete
      </Button>
    ),
  },
  { name: "loading", element: <Button loading>Saving</Button> },
  { name: "disabled", element: <Button disabled>Save</Button> },
] satisfies HookScenario[];
