// packages/angular/src/testing/styling-hooks/code-block.ts
import { Component } from "@angular/core";
import { MnCodeBlock } from "../../components/data";
import type { HookScenario } from "../types";
@Component({
  imports: [MnCodeBlock],
  template: `<mn-code-block
    code="const x = 1;"
    language="typescript"
    copyable
  />`,
})
class Fixture {
  readonly date = new Date(2026, 9, 1);
}
export default [
  { name: "content and states", component: Fixture },
] satisfies HookScenario[];

// packages/react/src/test-utils/styling-hooks/code-block.tsx
import { CodeBlock } from "../../components/CodeBlock";
import type { HookScenario } from "./types";

export default [
  { name: "plain", element: <CodeBlock>{"const a = 1;"}</CodeBlock> },
  {
    name: "copyable",
    element: <CodeBlock copyable>{"const a = 1;"}</CodeBlock>,
  },
] satisfies HookScenario[];
