// packages/angular/src/testing/styling-hooks/json-field.ts
import { Component } from "@angular/core";
import { MnJsonField } from "../../components/data";
import type { HookScenario } from "../types";
@Component({
  imports: [MnJsonField],
  template: `<mn-json-field value="broken" disabled readOnly required />`,
})
class Fixture {
  readonly date = new Date(2026, 9, 1);
}
export default [
  { name: "content and states", component: Fixture },
] satisfies HookScenario[];

// packages/react/src/test-utils/styling-hooks/json-field.tsx
import { JsonField } from "../../components/JsonField";
import type { HookScenario } from "./types";

export default [
  {
    name: "toolbar, invalid JSON, required",
    element: <JsonField aria-label="Config" defaultValue="{" required />,
  },
  {
    name: "disabled, read-only",
    element: (
      <JsonField aria-label="Config" defaultValue="{}" disabled readOnly />
    ),
  },
] satisfies HookScenario[];
