// packages/angular/src/testing/styling-hooks/modal.ts
import { Component } from "@angular/core";
import { MnModal, MnModalBody, MnModalFooter } from "../../components/modal";
import type { HookScenario } from "../types";
@Component({
  imports: [MnModal, MnModalBody, MnModalFooter],
  template: `<mn-modal [open]="true" title="Dialog" description="Details"
    ><mn-modal-body>Body</mn-modal-body
    ><mn-modal-footer>Footer</mn-modal-footer></mn-modal
  >`,
})
class Open {}
@Component({
  imports: [MnModal],
  template: `<mn-modal forceMount title="Dialog" />`,
})
class Closed {}
export default [
  { name: "open", component: Open },
  { name: "closed", component: Closed },
] satisfies HookScenario[];

// packages/react/src/test-utils/styling-hooks/modal.tsx
import {
  Modal,
  ModalBody,
  ModalContent,
  ModalFooter,
  ModalHeader,
  ModalRoot,
} from "../../components/Modal";
import type { HookScenario } from "./types";

export default [
  {
    name: "open",
    element: (
      <Modal open title="Title" description="Description" size="large">
        Body
      </Modal>
    ),
  },
  {
    name: "compound, closing (kept mounted)",
    element: (
      <ModalRoot open={false}>
        <ModalContent forceMount hideCloseButton>
          <ModalHeader>Title</ModalHeader>
          <ModalBody>Body</ModalBody>
          <ModalFooter>Footer</ModalFooter>
        </ModalContent>
      </ModalRoot>
    ),
  },
] satisfies HookScenario[];
