// packages/angular/src/testing/styling-hooks/prose.ts
import { Component } from "@angular/core";
import { MnProse } from "../../components/foundations";
import type { HookScenario } from "../types";
@Component({
  imports: [MnProse],
  template: `<article mnProse>
    <h1>Title</h1>
    <p>Content</p>
  </article>`,
})
class Fixture {}
export default [
  { name: "content and states", component: Fixture },
] satisfies HookScenario[];

// packages/react/src/test-utils/styling-hooks/prose.tsx
import { Prose } from "../../components/Prose";
import type { HookScenario } from "./types";

export default [
  {
    name: "default",
    element: (
      <Prose>
        <p>Text</p>
      </Prose>
    ),
  },
  {
    name: "asChild",
    element: (
      <Prose asChild>
        <article>Text</article>
      </Prose>
    ),
  },
] satisfies HookScenario[];
