// packages/angular/src/testing/styling-hooks/rating-scale.ts
import { Component } from "@angular/core";
import { MnRatingScale } from "../../components/rating";
import type { HookScenario } from "../types";

const dimensions = [
  { key: "plot", label: "Plot", value: 8 },
  { key: "writing", label: "Writing", value: 6 },
];

@Component({
  imports: [MnRatingScale],
  template: `<mn-rating-scale [dimensions]="dimensions" size="large" />`,
})
class Display {
  dimensions = dimensions;
}

@Component({
  imports: [MnRatingScale],
  template: `<mn-rating-scale [dimensions]="dimensions" interactive />`,
})
class Interactive {
  dimensions = dimensions;
}

export default [
  { name: "display-only, every key", component: Display },
  { name: "interactive", component: Interactive },
] satisfies HookScenario[];

// packages/react/src/test-utils/styling-hooks/rating-scale.tsx
import { RatingScale } from "../../components/Rating";
import type { HookScenario } from "./types";

const dimensions = [
  { key: "plot", label: "Plot", value: 8 },
  { key: "writing", label: "Writing", value: 6 },
];

export default [
  {
    name: "display-only, every key",
    element: <RatingScale dimensions={dimensions} size="large" />,
  },
  {
    name: "interactive",
    element: <RatingScale dimensions={dimensions} onChange={() => {}} />,
  },
] satisfies HookScenario[];
