// packages/angular/src/testing/styling-hooks/skeleton.ts
import { Component } from "@angular/core";
import { MnSkeleton } from "../../components/foundations";
import type { HookScenario } from "../types";
@Component({
  imports: [MnSkeleton],
  template: `<mn-skeleton variant="card" />`,
})
class Fixture {}
export default [
  { name: "content and states", component: Fixture },
] satisfies HookScenario[];

// packages/react/src/test-utils/styling-hooks/skeleton.tsx
import { Skeleton } from "../../components/Skeleton";
import type { HookScenario } from "./types";

export default [
  { name: "lines, avatar", element: <Skeleton lines={2} avatar /> },
  { name: "card", element: <Skeleton variant="card" avatar title paragraph /> },
  {
    name: "decorative",
    element: <Skeleton decorative variant="circular" />,
  },
] satisfies HookScenario[];
