// packages/angular/src/testing/styling-hooks/stack.ts
import { Component } from "@angular/core";
import { MnStack } from "../../components/foundations";
import type { HookScenario } from "../types";
@Component({
  imports: [MnStack],
  template: `<mn-stack direction="row">Content</mn-stack>`,
})
class Fixture {}
export default [
  { name: "content and states", component: Fixture },
] satisfies HookScenario[];

// packages/react/src/test-utils/styling-hooks/stack.tsx
import { Stack } from "../../components/Stack";
import type { HookScenario } from "./types";

export default [
  { name: "column", element: <Stack gap={2}>A</Stack> },
  {
    name: "row, separator",
    element: (
      <Stack direction="row-reverse" separator="·">
        <span>A</span>
        <span>B</span>
      </Stack>
    ),
  },
] satisfies HookScenario[];
