// packages/angular/src/testing/styling-hooks/textarea.ts
import { Component } from "@angular/core";
import { MnTextarea } from "../../components/textarea";
import type { HookScenario } from "../types";

@Component({
  imports: [MnTextarea],
  template: `<textarea
    mnTextarea
    aria-label="Bio"
    size="large"
    variant="filled"
    required
  ></textarea>`,
})
class Keys {}

@Component({
  imports: [MnTextarea],
  template: `<textarea
    mnTextarea
    aria-label="Bio"
    invalid
    readOnly
  ></textarea>`,
})
class Invalid {}

@Component({
  imports: [MnTextarea],
  template: `<textarea mnTextarea aria-label="Bio" disabled></textarea>`,
})
class Disabled {}

export default [
  { name: "every key, required", component: Keys },
  { name: "invalid, read-only", component: Invalid },
  { name: "disabled", component: Disabled },
] satisfies HookScenario[];

// packages/react/src/test-utils/styling-hooks/textarea.tsx
import { Textarea } from "../../components/Textarea";
import type { HookScenario } from "./types";

export default [
  {
    name: "every key, required",
    element: (
      <Textarea aria-label="Bio" size="large" variant="filled" required />
    ),
  },
  {
    name: "invalid, read-only",
    element: <Textarea aria-label="Bio" invalid readOnly />,
  },
  { name: "disabled", element: <Textarea aria-label="Bio" disabled /> },
] satisfies HookScenario[];
