// packages/vue/src/components/Card/Card.vue
<script setup lang="ts">
/**
 * Card: a content container composed of CardHeader, CardContent and
 * CardFooter (omit a section to leave it out). `padding` switches to the
 * padded layout (the card pads itself), `interactive` adds hover / focus
 * feedback and `as` changes the root element (e.g. a link).
 */
import { computed, useAttrs } from "vue";
import { linkRel } from "@minerva/core";
import styles from "@react-styles/components/Card/card.module.scss";
import { hooks } from "../../internal/hooks";
import { safeHref } from "../../internal/safe-url";
import type { CardProps } from "./types";

defineOptions({ name: "Card", inheritAttrs: false });

const props = withDefaults(defineProps<CardProps>(), {
  variant: "default",
  padding: undefined,
  interactive: false,
  as: "div",
  type: undefined,
});

defineSlots<{
  /** Card content, usually CardHeader, CardContent and CardFooter */
  default?: () => unknown;
}>();

const attrs = useAttrs();

const classes = computed(() => [
  styles.card,
  styles[props.variant],
  props.padding && styles.padded,
  props.padding && styles[`pad-${props.padding}`],
  props.interactive && styles.interactive,
]);
const rootAttrs = computed(() => {
  const isButton = props.as === "button";
  const disabled = attrs.disabled;
  const link =
    props.as === "a"
      ? {
          href: safeHref("Card", attrs.href),
          rel: linkRel(
            attrs.target as string | undefined,
            attrs.rel as string | undefined,
          ),
        }
      : undefined;
  return {
    type: isButton ? (props.type ?? "button") : undefined,
    ...attrs,
    ...link,
    ...hooks("card", "root", {
      variant: props.variant,
      disabled:
        isButton &&
        disabled !== undefined &&
        disabled !== null &&
        disabled !== false,
    }),
  };
});
</script>

<template>
  <component :is="as" :class="classes" v-bind="rootAttrs">
    <slot />
  </component>
</template>

// packages/lib-core/src/components/Card/Card.tsx
import React from "react";
import { linkRel } from "@minerva/core";
import { cn } from "../../utils/cn";
import { safeHref } from "../../internal/safeUrl";
import type {
  CardProps,
  CardHeaderProps,
  CardTitleProps,
  CardDescriptionProps,
  CardContentProps,
  CardFooterProps,
  CardPadding,
} from "./types";
import styles from "./card.module.scss";
import { hooks } from "../../internal/stylingHooks";

/** Module class of a padding override */
const paddingClass = (padding: CardPadding | undefined) =>
  padding && styles[`pad-${padding}`];

/**
 * Card: a content container composed of CardHeader, CardContent and CardFooter
 * (omit a section to leave it out). `padding` switches to the padded layout (the card pads itself), `interactive`
 * adds hover / focus feedback and `as` changes the root element (e.g. a link).
 */
export const Card = ({
  children,
  variant = "default",
  padding,
  interactive = false,
  as,
  type,
  className = "",
  ref,
  ...rest
}: CardProps) => {
  const Tag: React.ElementType = as ?? "div";
  const link =
    Tag === "a"
      ? {
          href: safeHref("Card", rest.href),
          rel: linkRel(rest.target, rest.rel),
        }
      : undefined;
  return (
    <Tag
      ref={ref}
      type={Tag === "button" ? (type ?? "button") : undefined}
      className={cn(
        styles.card,
        styles[variant],
        padding && styles.padded,
        paddingClass(padding),
        interactive && styles.interactive,
        className,
      )}
      {...rest}
      {...link}
      {...hooks("card", "root", {
        variant,
        disabled: Tag === "button" && !!rest.disabled,
      })}
    >
      {children}
    </Tag>
  );
};

/**
 * CardHeader: top section, usually holding CardTitle and CardDescription.
 */
export const CardHeader = ({
  children,
  className = "",
  padding,
  ref,
  ...rest
}: CardHeaderProps) => {
  return (
    <div
      ref={ref}
      className={cn(styles.cardHeader, paddingClass(padding), className)}
      {...rest}
      {...hooks("card-header", "root")}
    >
      {children}
    </div>
  );
};

/**
 * CardTitle: heading of the card (h3 by default).
 */
export const CardTitle = ({
  children,
  as: Heading = "h3",
  className = "",
  ref,
  ...rest
}: CardTitleProps) => {
  return (
    <Heading
      ref={ref}
      className={cn(styles.cardTitle, className)}
      {...rest}
      {...hooks("card-title", "root")}
    >
      {children}
    </Heading>
  );
};

/**
 * CardDescription: secondary text shown below the title.
 */
export const CardDescription = ({
  children,
  className = "",
  ref,
  ...rest
}: CardDescriptionProps) => {
  return (
    <p
      ref={ref}
      className={cn(styles.cardDescription, className)}
      {...rest}
      {...hooks("card-description", "root")}
    >
      {children}
    </p>
  );
};

/**
 * CardContent: main body of the card.
 */
export const CardContent = ({
  children,
  className = "",
  animation,
  padding,
  ref,
  ...rest
}: CardContentProps) => {
  return (
    <div
      ref={ref}
      className={cn(
        styles.cardContent,
        animation && styles[animation],
        paddingClass(padding),
        className,
      )}
      {...rest}
      {...hooks("card-content", "root")}
    >
      {children}
    </div>
  );
};

/**
 * CardFooter: bottom section, e.g. for actions.
 */
export const CardFooter = ({
  children,
  className = "",
  padding,
  ref,
  ...rest
}: CardFooterProps) => {
  return (
    <div
      ref={ref}
      className={cn(styles.cardFooter, paddingClass(padding), className)}
      {...rest}
      {...hooks("card-footer", "root")}
    >
      {children}
    </div>
  );
};

export default React.memo(Card);
