// packages/angular/src/testing/contract-driver.ts
import {
  Component,
  signal,
  reflectComponentType,
  type Type,
} from "@angular/core";
import { TestBed, type ComponentFixture } from "@angular/core/testing";
import { compile } from "sass";
import { join } from "node:path";
import { readdirSync } from "node:fs";
import * as Minerva from "../index";
import { render, settle, user } from "./index";
import * as dom from "../../../../tests/contracts/harness/dom";
import {
  contractOf,
  isNative,
  REPO_ROOT,
} from "../../../../tests/contracts/harness/contracts";
import type {
  Driver,
  Spec,
  EmittedEvent,
} from "../../../../tests/contracts/harness/types";

const exports = Minerva as unknown as Record<string, Type<unknown>>;
let active: ComponentFixture<unknown> | undefined;
const escape = (text: string) =>
  text
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;")
    .replaceAll("{", "&#123;");
export const nativeAngular: Driver = {
  platform: "angular",
  async render(spec, options = {}) {
    const log: EmittedEvent[] = [];
    const nodes: Spec[] = [];
    const imports: Type<unknown>[] = [Minerva.MnConfig];
    function template(spec: Spec | string): string {
      if (typeof spec === "string") return escape(spec);
      if (spec.component === "TabList")
        return spec.children.map(template).join("");
      const id = nodes.push(spec) - 1;
      let tag = spec.component;
      let selectorAttrs = "";
      let type: Type<unknown> | undefined;
      if (!isNative(spec)) {
        type =
          exports[
            spec.component === "ToastProvider"
              ? "MnToastRegion"
              : `Mn${spec.component}`
          ];
        if (!type)
          throw new Error(`No Angular component for ${spec.component}`);
        imports.push(type);
        const selector = reflectComponentType(type)!.selector.split(",")[0];
        tag = selector.match(/^[\w-]+/)?.[0] ?? "div";
        selectorAttrs = [...selector.matchAll(/\[([\w-]+)\]/g)]
          .map((m) => m[1])
          .join(" ");
      }
      const meta = type ? reflectComponentType(type) : null;
      const inputs = meta?.inputs.map((p) => p.templateName) ?? [];
      const outputs = meta?.outputs.map((p) => p.templateName) ?? [];
      const propName = (name: string) =>
        name === "current"
          ? "page"
          : name === "defaultValue" && !inputs.includes(name)
            ? "value"
            : name;
      let attributes = Object.keys(spec.props)
        .filter((name) => !name.startsWith("on"))
        .map((name) => {
          const target = propName(name);
          return inputs.includes(target)
            ? `[${target}]="nodes()[${id}].props['${name}']"`
            : `[attr.${target}]="nodes()[${id}].props['${name}']"`;
        })
        .join(" ");
      if (type) {
        for (const event of contractOf(spec.component).events) {
          const field = event.detail?.[0];
          const output =
            event.react === "onClick" ? "click" : field ? `${field}Change` : "";
          if (output === "click" || outputs.includes(output))
            attributes += ` (${output})="emit(${id}, '${event.name}', '${field ?? ""}', $event)"`;
        }
      }
      return `<${tag} ${selectorAttrs} ${attributes}>${spec.children.map(template).join("")}</${tag}>`;
    }
    const html = template(spec);
    class ContractHost {
      nodes = signal(nodes);
      emit(id: number, name: string, field: string, value: unknown) {
        log.push({
          component: nodes[id].component,
          name,
          detail: field ? { [field]: value } : {},
        });
      }
    }
    Component({
      imports: [...new Set(imports)],
      template: `<mn-config locale="${options.locale ?? "en"}">${html}</mn-config>`,
    })(ContractHost);
    const fixture = await render(ContractHost);
    active = fixture;
    return {
      root: fixture.nativeElement,
      events: log,
      emitted: (name, component) =>
        log.filter(
          (e) => e.name === name && (!component || component === e.component),
        ),
      async setProps(props) {
        if (typeof spec !== "string") {
          Object.assign(spec.props, props);
          fixture.componentInstance.nodes.set([...nodes]);
          await settle(fixture);
        }
      },
      async unmount() {
        fixture.destroy();
        if (active === fixture) active = undefined;
      },
    };
  },
  async settle(ms = 0) {
    if (active) await settle(active, ms);
    else await dom.wait(ms);
  },
  queryAllByRole: dom.queryAllByRole,
  queryByRole: (role, options) => dom.queryAllByRole(role, options)[0] ?? null,
  getByRole(role, options) {
    const result = dom.queryAllByRole(role, options)[0];
    if (!result) throw new Error(`Missing ${role} ${options?.name ?? ""}`);
    return result;
  },
  queryByTestId: dom.queryByTestId,
  queryByText: dom.queryByText,
  queryPart: (name, within = document.body) =>
    within.querySelector(`[data-part="${name}"]`),
  async press(target) {
    await user().click(target);
    await this.settle();
  },
  async type(target, text) {
    await user().type(target, text);
    await this.settle();
  },
  async keyboard(keys) {
    await user().keyboard(keys);
    await this.settle();
  },
  isChecked: dom.isChecked,
  classes: (el) => Array.from(el.classList),
  tokenVar: dom.tokenVar,
  stylesheet(component) {
    const folder = join(REPO_ROOT, "packages/react/src/components", component);
    return readdirSync(folder)
      .filter((name) => name.endsWith(".scss"))
      .map((name) => compile(join(folder, name)).css)
      .join("\n");
  },
  services: {
    toast: {
      show(title, options) {
        TestBed.inject(Minerva.MnToastService).show({ title, ...options });
      },
      reset() {
        TestBed.inject(Minerva.MnToastService).clear();
      },
    },
  },
};

// packages/taro/src/testing/contract-driver.tsx
// Taro H5 driver runs the SAME interaction contracts as the web renderers.
// It uses real Taro host components, with framework APIs handled by its test
// environment; this is host validation, not a device simulator.
import { readFileSync } from "node:fs";
import { join } from "node:path";
import { createElement, Fragment, type ReactNode } from "react";
import { act, render } from "@testing-library/react";
import userEvent from "@testing-library/user-event";
import * as Minerva from "../index";
import { type ComponentContract } from "../../../core/src/contracts";
import * as dom from "../../../../tests/contracts/harness/dom";
import type {
  Driver,
  EmittedEvent,
  Handle,
  RenderOptions,
  Spec,
} from "../../../../tests/contracts/harness/types";
import {
  REPO_ROOT,
  contractOf,
  detailOf,
  isNative,
} from "../../../../tests/contracts/harness/contracts";

const components = Minerva as unknown as Record<
  string,
  Parameters<typeof createElement>[0]
>;

const user = () => userEvent.setup({ pointerEventsCheck: 0 });

function toReact(
  spec: Spec | string,
  log: EmittedEvent[],
  key?: number,
): ReactNode {
  if (typeof spec === "string") return spec;
  if (isNative(spec))
    return createElement(
      spec.component,
      { ...spec.props, key },
      ...spec.children.map((child, i) => toReact(child, log, i)),
    );
  const contract: ComponentContract = contractOf(spec.component);
  const children = spec.children.map((child, i) => toReact(child, log, i));
  if (contract.platforms.taro.status === "n/a")
    return createElement(Fragment, { key }, ...children);
  const type = components[contract.name];
  if (!type) throw new Error(`minerva-design exports no ${contract.name}`);
  const props: Record<string, unknown> = { ...spec.props, key };
  for (const event of contract.events) {
    if (!event.react) continue;
    const own = spec.props[event.react] as
      ((...args: unknown[]) => unknown) | undefined;
    props[event.react] = (...args: unknown[]) => {
      log.push({
        component: contract.name,
        name: event.name,
        detail: detailOf(event, args),
      });
      return own?.(...args);
    };
  }
  return createElement(type, props, ...children);
}

export const taroDriver: Driver = {
  platform: "taro",

  async render(input: Spec | string, options: RenderOptions = {}) {
    let spec = input;
    const log: EmittedEvent[] = [];
    const tree = () => {
      const node = toReact(spec, log);
      return options.locale ? (
        <Minerva.ConfigProvider locale={options.locale}>
          {node}
        </Minerva.ConfigProvider>
      ) : (
        node
      );
    };
    const result = render(<>{tree()}</>);
    await taroDriver.settle();
    const handle: Handle = {
      root: result.container.firstElementChild ?? result.container,
      events: log,
      emitted: (name, component) =>
        log.filter(
          (e) => e.name === name && (!component || e.component === component),
        ),
      async setProps(props) {
        if (typeof spec === "string") return;
        spec = { ...spec, props: { ...spec.props, ...props } };
        result.rerender(<>{tree()}</>);
        await taroDriver.settle();
      },
      async unmount() {
        result.unmount();
      },
    };
    return handle;
  },

  async settle(ms = 0) {
    await act(() => dom.wait(ms));
  },

  queryAllByRole: dom.queryAllByRole,
  queryByRole: (role, options) => dom.queryAllByRole(role, options)[0] ?? null,
  getByRole(role, options) {
    const found = dom.queryAllByRole(role, options)[0];
    if (!found) throw new Error(`No ${role} ${options?.name ?? ""}`);
    return found;
  },
  queryByTestId: dom.queryByTestId,
  queryByText: dom.queryByText,
  queryPart: (name, within = document.body) =>
    within.querySelector(`[data-part="${name}"]`),

  async press(target) {
    await user().click(target);
    await taroDriver.settle();
  },
  async type(target, text) {
    await user().type(target, text);
    await taroDriver.settle();
  },
  async keyboard(keys) {
    await user().keyboard(keys);
    await taroDriver.settle();
  },

  isChecked: dom.isChecked,
  classes: (el) => Array.from(el.classList),
  tokenVar: dom.tokenVar,
  stylesheet() {
    return ["mini-controls.css", "taro-components.css"]
      .map((name) =>
        readFileSync(join(REPO_ROOT, "tools/styles", name), "utf8"),
      )
      .join("\n");
  },

  services: {
    toast: {
      show(title, options) {
        act(() => {
          Minerva.toast.info(title, options);
        });
      },
      reset() {
        act(() => Minerva.toast.clear());
      },
    },
  },
};
