// packages/vue/src/components/Drawer/Drawer.vue
<script setup lang="ts">
/**
 * Drawer: a side panel with title, description and close button in one
 * component. Controlled (`v-model:open`) or uncontrolled (`defaultOpen`,
 * `trigger` slot). Restores focus to the opener after closing. Attributes
 * (class, style...) fall through to the panel.
 */
import DrawerRoot from "./DrawerRoot.vue";
import DrawerTrigger from "./DrawerTrigger.vue";
import DrawerContent from "./DrawerContent.vue";
import DrawerHeader from "./DrawerHeader.vue";
import type { DrawerProps } from "./types";

defineOptions({ name: "Drawer", inheritAttrs: false });

withDefaults(defineProps<DrawerProps>(), {
  open: undefined,
  defaultOpen: undefined,
  side: "right",
  size: "medium",
  title: undefined,
  description: undefined,
  hideCloseButton: false,
  closeLabel: undefined,
  hiddenDescription: undefined,
});
const emit = defineEmits<{
  "update:open": [open: boolean];
  /** Open state requested to change (trigger, Escape, overlay, close) */
  openChange: [open: boolean];
}>();
const slots = defineSlots<{
  /** Content: usually `DrawerBody` + `DrawerFooter` */
  default?: () => unknown;
  /** Element opening the drawer (its single child gets the trigger props) */
  trigger?: () => unknown;
  title?: () => unknown;
  description?: () => unknown;
}>();
</script>

<template>
  <DrawerRoot
    :open="open"
    :default-open="defaultOpen"
    @update:open="emit('update:open', $event)"
    @open-change="emit('openChange', $event)"
  >
    <DrawerTrigger v-if="slots.trigger" as-child>
      <slot name="trigger" />
    </DrawerTrigger>
    <DrawerContent
      v-bind="$attrs"
      :side="side"
      :size="size"
      :hide-close-button="hideCloseButton"
      :close-label="closeLabel"
      :description="description"
      :hidden-description="hiddenDescription"
    >
      <template v-if="slots.description" #description>
        <slot name="description" />
      </template>
      <DrawerHeader v-if="title || slots.title">
        <slot name="title">{{ title }}</slot>
      </DrawerHeader>
      <slot />
    </DrawerContent>
  </DrawerRoot>
</template>

// packages/lib-core/src/components/Drawer/Drawer.tsx
import { LuX } from "react-icons/lu";
import useI18n from "../../hooks/useI18n";
import {
  DialogClose,
  DialogContent,
  DialogDescription,
  DialogRoot,
  DialogTitle,
  DialogTrigger,
} from "../../internal/Dialog";
import { cn } from "../../utils/cn";
import type {
  DrawerContentProps,
  DrawerProps,
  DrawerRootProps,
  DrawerSectionProps,
  DrawerTriggerProps,
} from "./types";
import styles from "./drawer.module.scss";

/** Owns the open state of a compound drawer. */
export const DrawerRoot = (props: DrawerRootProps) => <DialogRoot {...props} />;

/** Opens the drawer; a `<button>` or, with `asChild`, the child element. */
export const DrawerTrigger = (props: DrawerTriggerProps) => (
  <DialogTrigger {...props} />
);

/** Closes the drawer; a `<button>` or, with `asChild`, the child element. */
export const DrawerClose = (props: DrawerTriggerProps) => (
  <DialogClose {...props} />
);

/**
 * DrawerContent: portalled overlay + a panel sliding in from one edge, on the
 * internal dialog foundation (focus trap, Escape / overlay click dismissal,
 * scroll lock, rest of the page hidden, focus returned to the opener).
 */
export const DrawerContent = ({
  side = "right",
  size = "medium",
  hideCloseButton = false,
  closeLabel,
  description,
  hiddenDescription,
  overlayClassName,
  className,
  children,
  ...rest
}: DrawerContentProps) => {
  const { t } = useI18n();
  return (
    <DialogContent
      overlayClassName={cn(styles.overlay, overlayClassName)}
      className={cn(styles.content, styles[side], styles[size], className)}
      {...rest}
    >
      <DialogDescription
        className={description ? styles.description : styles.visuallyHidden}
      >
        {description ?? hiddenDescription ?? t("drawer.description")}
      </DialogDescription>
      {children}
      {!hideCloseButton && (
        <DialogClose
          className={styles.close}
          aria-label={closeLabel ?? t("drawer.close")}
        >
          <LuX size={16} aria-hidden="true" />
        </DialogClose>
      )}
    </DialogContent>
  );
};

/** DrawerHeader: the drawer title (accessible name). */
export const DrawerHeader = ({
  className,
  ref,
  ...rest
}: DrawerSectionProps) => (
  <DialogTitle asChild>
    <div ref={ref} className={cn(styles.header, className)} {...rest} />
  </DialogTitle>
);

/** DrawerBody: the scrollable content area. */
export const DrawerBody = ({ className, ref, ...rest }: DrawerSectionProps) => (
  <div ref={ref} className={cn(styles.body, className)} {...rest} />
);

/** DrawerFooter: right-aligned, wrapping action row. */
export const DrawerFooter = ({
  className,
  ref,
  ...rest
}: DrawerSectionProps) => (
  <div ref={ref} className={cn(styles.footer, className)} {...rest} />
);

/**
 * Drawer: a side panel with title, description and close button in one
 * component. Controlled (`open` + `onOpenChange`) or uncontrolled
 * (`defaultOpen`, `trigger`). Restores focus to the opener after closing.
 */
export const Drawer = ({
  open,
  defaultOpen = false,
  onOpenChange,
  trigger,
  side,
  size,
  title,
  description,
  hideCloseButton,
  closeLabel,
  hiddenDescription,
  className,
  ref,
  children,
}: DrawerProps) => (
  <DrawerRoot open={open} defaultOpen={defaultOpen} onOpenChange={onOpenChange}>
    {trigger && <DrawerTrigger asChild>{trigger}</DrawerTrigger>}
    <DrawerContent
      ref={ref}
      side={side}
      size={size}
      description={description}
      hideCloseButton={hideCloseButton}
      closeLabel={closeLabel}
      hiddenDescription={hiddenDescription}
      className={className}
    >
      {title && <DrawerHeader>{title}</DrawerHeader>}
      {children}
    </DrawerContent>
  </DrawerRoot>
);

export default Drawer;
