// packages/vue/src/components/Tag/Tag.vue
<script setup lang="ts">
/**
 * Tag: a small label for marking and categorizing.
 *
 * The root is a plain (non-interactive) element. When `clickable`, the
 * content is rendered as a native <button> (which also draws the ripple);
 * when `closable`, the close control is a sibling <button>, so interactive
 * elements are never nested. With `pressed` a clickable tag is a toggle
 * (aria-pressed), e.g. a selectable filter. Attributes go to the root.
 */
import {
  computed,
  onBeforeUnmount,
  ref,
  useAttrs,
  type CSSProperties,
} from "vue";
import styles from "@react-styles/components/Tag/tag.module.scss";
import { hooks } from "../../internal/hooks";
import { IconX } from "../../internal/icons";
import { textOf } from "../../internal/children";
import { useI18n } from "../../config/useI18n";
import type { TagProps } from "./types";

defineOptions({ name: "Tag", inheritAttrs: false });

const props = withDefaults(defineProps<TagProps>(), {
  color: "neutral",
  variant: "subtle",
  size: "medium",
  shape: "rounded",
  closable: false,
  clickable: false,
  pressed: undefined,
  loading: false,
  elevation: false,
  disabled: false,
  closeLabel: undefined,
  ripple: true,
});

const emit = defineEmits<{
  /** The tag was activated (clickable, not disabled / loading) */
  click: [event: MouseEvent];
  /** The close button was clicked (not while disabled) */
  close: [event: MouseEvent];
}>();

const slots = defineSlots<{
  /** Content of the tag */
  default?: () => unknown;
  /** Icon displayed before the content */
  icon?: () => unknown;
  /** Avatar (e.g. a small Avatar or image) displayed before the content */
  avatar?: () => unknown;
  /** Custom close icon */
  "close-icon"?: () => unknown;
}>();

const RIPPLE_DURATION = 600;

const attrs = useAttrs();
const { t } = useI18n();

interface Ripple {
  id: number;
  style: CSSProperties;
}
const ripples = ref<Ripple[]>([]);
let nextRippleId = 0;
const timers = new Set<ReturnType<typeof setTimeout>>();
onBeforeUnmount(() => {
  timers.forEach(clearTimeout);
  timers.clear();
});

const inactive = computed(() => props.disabled || props.loading);

/** The close button names the tag it removes: "Remove {label}" */
const closeLabelOf = (children: unknown) => {
  const label = textOf(children);
  if (typeof props.closeLabel === "function") return props.closeLabel(label);
  return (
    props.closeLabel ??
    (label ? t("tag.closeWithLabel", { label }) : t("tag.close"))
  );
};

// The ripple is drawn over the whole tag, from where its main action (the
// native button) was pressed.
const addRipple = (event: MouseEvent) => {
  if (!props.ripple) return;
  const tag = (event.currentTarget as HTMLElement).parentElement as HTMLElement;
  const rect = tag.getBoundingClientRect();
  // keyboard-activated clicks (detail === 0) ripple from the center
  const fromKeyboard = event.detail === 0;
  const diameter = Math.max(rect.width, rect.height);
  const radius = diameter / 2;
  const id = nextRippleId++;
  ripples.value.push({
    id,
    style: {
      width: `${diameter}px`,
      height: `${diameter}px`,
      left: `${fromKeyboard ? rect.width / 2 - radius : event.clientX - rect.left - radius}px`,
      top: `${fromKeyboard ? rect.height / 2 - radius : event.clientY - rect.top - radius}px`,
    },
  });
  const timer = setTimeout(() => {
    timers.delete(timer);
    ripples.value = ripples.value.filter((r) => r.id !== id);
  }, RIPPLE_DURATION);
  timers.add(timer);
};

const onClick = (event: MouseEvent) => {
  if (inactive.value) return;
  addRipple(event);
  emit("click", event);
};

const onClose = (event: MouseEvent) => {
  // The close button is not part of the tag's main action / ripple.
  event.stopPropagation();
  if (!props.disabled) emit("close", event);
};

const classes = computed(() => [
  styles.tag,
  styles[props.color],
  styles[props.variant],
  styles[props.size],
  styles[props.shape],
  props.clickable && !inactive.value && styles.clickable,
  props.clickable && props.pressed && styles.pressed,
  props.elevation && styles.elevation,
  props.disabled && styles.disabled,
  props.loading && styles.loading,
]);
const rootAttrs = computed(() => ({
  ...attrs,
  ...hooks("tag", "root", {
    state: props.clickable && props.pressed ? "active" : "inactive",
    disabled: props.disabled,
    loading: props.loading,
    size: props.size,
    variant: props.variant,
    color: props.color,
    shape: props.shape,
  }),
}));
</script>

<template>
  <div
    :class="classes"
    :aria-busy="loading || undefined"
    data-component="tag"
    v-bind="rootAttrs"
  >
    <button
      v-if="clickable"
      type="button"
      :class="styles.action"
      :disabled="inactive"
      :aria-pressed="pressed"
      v-bind="hooks('tag', 'action')"
      @click="onClick"
    >
      <span
        v-if="loading"
        :class="styles.spinner"
        aria-hidden="true"
        v-bind="hooks('tag', 'spinner')"
      />
      <template v-else>
        <span
          v-if="slots.icon"
          :class="styles.icon"
          v-bind="hooks('tag', 'icon')"
        >
          <slot name="icon" />
        </span>
        <span
          v-if="slots.avatar"
          :class="styles.avatar"
          v-bind="hooks('tag', 'avatar')"
        >
          <slot name="avatar" />
        </span>
      </template>
      <span :class="styles.content" v-bind="hooks('tag', 'label')">
        <slot />
      </span>
    </button>
    <template v-else>
      <span
        v-if="loading"
        :class="styles.spinner"
        aria-hidden="true"
        v-bind="hooks('tag', 'spinner')"
      />
      <template v-else>
        <span
          v-if="slots.icon"
          :class="styles.icon"
          v-bind="hooks('tag', 'icon')"
        >
          <slot name="icon" />
        </span>
        <span
          v-if="slots.avatar"
          :class="styles.avatar"
          v-bind="hooks('tag', 'avatar')"
        >
          <slot name="avatar" />
        </span>
      </template>
      <span :class="styles.content" v-bind="hooks('tag', 'label')">
        <slot />
      </span>
    </template>
    <template v-if="closable && !loading">
      <button
        v-for="closeName in [closeLabelOf($slots.default?.())]"
        key="close"
        type="button"
        :class="styles.closeIcon"
        :disabled="disabled"
        :aria-label="closeName"
        :title="closeName"
        v-bind="hooks('tag', 'close-button')"
        @click="onClose"
      >
        <slot name="close-icon">
          <IconX aria-hidden="true" focusable="false" />
        </slot>
      </button>
    </template>
    <span
      v-for="r in ripples"
      :key="r.id"
      :class="styles.ripple"
      :style="r.style"
    />
  </div>
</template>

// packages/lib-core/src/components/Tag/Tag.tsx
import React, {
  Children,
  isValidElement,
  useEffect,
  useRef,
  useState,
  type ReactNode,
} from "react";
import { cn } from "../../utils/cn";
import { IconX } from "../../internal/icons";
import type { TagProps } from "./types";
import styles from "./tag.module.scss";
import useI18n from "../../hooks/useI18n";
import { hooks } from "../../internal/stylingHooks";

const RIPPLE_DURATION = 600;

/** Plain text of `node` (strings / numbers, also inside elements). */
const textOf = (node: ReactNode): string =>
  Children.toArray(node)
    .map((child) => {
      if (typeof child === "string" || typeof child === "number") {
        return String(child);
      }
      if (isValidElement<{ children?: ReactNode }>(child)) {
        return textOf(child.props.children);
      }
      return "";
    })
    .join("")
    .replace(/\s+/g, " ")
    .trim();

interface Ripple {
  id: number;
  style: React.CSSProperties;
}

/**
 * Tag: a small label for marking and categorizing.
 *
 * The root is a plain (non-interactive) element. When `clickable`, the content
 * is rendered as a native <button> (which also draws the ripple); when
 * `closable`, the close control is a sibling <button>, so interactive
 * elements are never nested. With `pressed` a clickable tag is a toggle
 * (aria-pressed), e.g. a selectable filter. Native attributes are forwarded
 * to the root.
 */
const Tag = ({
  children,
  color = "neutral",
  variant = "subtle",
  size = "medium",
  shape = "rounded",
  closable = false,
  onClose,
  clickable = false,
  onClick,
  pressed,
  icon,
  avatar,
  loading = false,
  elevation = false,
  className,
  style,
  disabled = false,
  closeIcon,
  closeLabel,
  ripple = true,
  ref,
  ...rest
}: TagProps) => {
  const { t } = useI18n();
  const [ripples, setRipples] = useState<Ripple[]>([]);
  const nextRippleId = useRef(0);
  const rippleTimers = useRef(new Set<ReturnType<typeof setTimeout>>());

  useEffect(() => {
    const timers = rippleTimers.current;
    return () => {
      timers.forEach(clearTimeout);
      timers.clear();
    };
  }, []);

  const handleClose = (e: React.MouseEvent<HTMLButtonElement>) => {
    // The close button is not part of the tag's main action / ripple.
    e.stopPropagation();
    if (!disabled) onClose?.(e);
  };

  const inactive = disabled || loading;

  // The close button names the tag it removes: "Remove {label}"
  const label = closable ? textOf(children) : "";
  const resolvedCloseLabel =
    typeof closeLabel === "function"
      ? closeLabel(label)
      : (closeLabel ??
        (label ? t("tag.closeWithLabel", { label }) : t("tag.close")));

  const handleClick = (e: React.MouseEvent<HTMLButtonElement>) => {
    if (inactive) return;
    addRipple(e);
    onClick?.(e);
  };

  // The ripple is drawn over the whole tag, from where its main action (the
  // native button) was pressed.
  const addRipple = (e: React.MouseEvent<HTMLButtonElement>) => {
    if (!ripple) return;
    const tag = e.currentTarget.parentElement as HTMLElement;
    const rect = tag.getBoundingClientRect();
    // keyboard-activated clicks (detail === 0) ripple from the center
    const fromKeyboard = e.detail === 0;
    const diameter = Math.max(rect.width, rect.height);
    const radius = diameter / 2;
    const id = nextRippleId.current++;
    const next: Ripple = {
      id,
      style: {
        width: diameter,
        height: diameter,
        left: fromKeyboard
          ? rect.width / 2 - radius
          : e.clientX - rect.left - radius,
        top: fromKeyboard
          ? rect.height / 2 - radius
          : e.clientY - rect.top - radius,
      },
    };
    setRipples((prev) => [...prev, next]);

    const timer = setTimeout(() => {
      rippleTimers.current.delete(timer);
      setRipples((prev) => prev.filter((r) => r.id !== id));
    }, RIPPLE_DURATION);
    rippleTimers.current.add(timer);
  };

  const content = (
    <>
      {loading ? (
        <span
          className={styles.spinner}
          aria-hidden="true"
          {...hooks("tag", "spinner")}
        />
      ) : (
        <>
          {icon && (
            <span className={styles.icon} {...hooks("tag", "icon")}>
              {icon}
            </span>
          )}
          {avatar && (
            <span className={styles.avatar} {...hooks("tag", "avatar")}>
              {avatar}
            </span>
          )}
        </>
      )}
      <span className={styles.content} {...hooks("tag", "label")}>
        {children}
      </span>
    </>
  );

  return (
    <div
      {...rest}
      ref={ref}
      className={cn(
        styles.tag,
        styles[color],
        styles[variant],
        styles[size],
        styles[shape],
        {
          [styles.clickable]: clickable && !inactive,
          [styles.pressed]: clickable && pressed,
          [styles.elevation]: elevation,
          [styles.disabled]: disabled,
          [styles.loading]: loading,
        },
        className,
      )}
      style={style}
      aria-busy={loading || undefined}
      // Lets layouts such as PageSection keep the tag's width (page.module.scss)
      data-component="tag"
      {...hooks("tag", "root", {
        state: clickable && pressed ? "active" : "inactive",
        disabled,
        loading,
        size,
        variant,
        color,
        shape,
      })}
    >
      {clickable ? (
        <button
          type="button"
          className={styles.action}
          onClick={handleClick}
          disabled={inactive}
          aria-pressed={pressed}
          {...hooks("tag", "action")}
        >
          {content}
        </button>
      ) : (
        content
      )}
      {closable && !loading && (
        <button
          type="button"
          className={styles.closeIcon}
          onClick={handleClose}
          disabled={disabled}
          aria-label={resolvedCloseLabel}
          title={resolvedCloseLabel}
          {...hooks("tag", "close-button")}
        >
          {closeIcon || <IconX aria-hidden focusable={false} />}
        </button>
      )}
      {ripples.map((r) => (
        <span key={r.id} className={styles.ripple} style={r.style} />
      ))}
    </div>
  );
};

export default Tag;
