// packages/lib-web-components/src/components/badge/badge.ts
import { css, html, nothing } from "lit";
import { property } from "lit/decorators.js";
import { classMap } from "lit/directives/class-map.js";
import { styleMap } from "lit/directives/style-map.js";
import type { ColorScheme } from "@minerva/core";
import styles from "@lib-core-styles/components/Badge/badge.module.scss?inline";
import { AriaController } from "../../internal/aria";
import { DEV, devWarn } from "../../internal/dev";
import { LocaleController } from "../../internal/locale";
import { MinervaElement, hostStyles } from "../../internal/minerva-element";
import { HasSlotController } from "../../internal/slots";
import { sharedStyles } from "../../internal/styles";

export type BadgeVariant = "solid" | "subtle" | "outline";
export type BadgeSize = "small" | "medium" | "large";
export type BadgePosition =
  "top-right" | "top-left" | "bottom-right" | "bottom-left";

/**
 * A small count or status indicator (`<Badge>` of lib-core).
 *
 * - With element children (default slot) the badge is attached to a corner
 *   of them (`position`), inside a relatively positioned wrapper; its text
 *   comes from `content` / the `content` slot (localized "Badge" otherwise).
 * - Without children, or with plain text children, it is a standalone badge
 *   rendered inline (the text is the badge's content).
 *
 * The badge is a polite `role="status"` region by default; set
 * `badge-role="presentation"` when it must not be announced.
 *
 * @summary Count / status indicator, standalone or attached to an element.
 * @tag minerva-badge
 * @slot - Element the badge is attached to, or the text of a standalone badge
 * @slot content - Rich content of the badge (instead of `content`)
 * @slot icon - Icon displayed before the content
 * @csspart base - The root (the badge, or the wrapper when attached)
 * @csspart badge - The badge itself
 * @csspart icon - The icon wrapper
 */
export class MinervaBadge extends MinervaElement {
  static override tagName = "minerva-badge";
  static override styles = [
    hostStyles,
    css`
      :host {
        display: inline-flex;
        vertical-align: middle;
      }
    `,
    sharedStyles(styles),
  ];

  /** Semantic color */
  @property({ reflect: true })
  color: ColorScheme = "primary";

  /** Visual style: solid (filled), subtle (tinted) or outline (bordered) */
  @property({ reflect: true })
  variant: BadgeVariant = "solid";

  /** Badge size */
  @property({ reflect: true })
  size: BadgeSize = "medium";

  /** Text of the badge (count, short text); use the `content` slot for rich content */
  @property()
  content?: string;

  /** Corner of the children the badge is placed on (ignored by standalone badges) */
  @property({ reflect: true })
  position: BadgePosition = "top-right";

  /** Renders a small dot instead of content */
  @property({ type: Boolean, reflect: true })
  dot = false;

  /** Custom border radius (CSS value) */
  @property({ attribute: "border-radius" })
  borderRadius?: string;

  /** Custom border width (CSS value) */
  @property({ attribute: "border-width" })
  borderWidth?: string;

  /** ARIA role of the badge ("presentation" / "none" to stop announcing it) */
  @property({ attribute: "badge-role" })
  badgeRole = "status";

  private readonly locale = new LocaleController(this);
  private readonly aria = new AriaController(this);
  private readonly slots = new HasSlotController(this);

  /** Whether the default slot holds elements (not only text) */
  private hasElementChildren(): boolean {
    return Array.from(this.children).some(
      (child) =>
        !child.hasAttribute("slot") || child.getAttribute("slot") === "",
    );
  }

  protected override updated(): void {
    if (
      DEV &&
      this.dot &&
      !this.aria.label &&
      !["presentation", "none"].includes(this.badgeRole)
    ) {
      devWarn(
        MinervaBadge.tagName,
        'a dot badge has no text: set aria-label (e.g. "New messages") or badge-role="presentation".',
      );
    }
  }

  protected override render() {
    const hasChildren = this.slots.test("[default]");
    const textChildren = hasChildren && !this.hasElementChildren();
    const hasContent =
      (this.content !== undefined && this.content !== null) ||
      this.slots.test("content");
    const standalone = !hasChildren || (textChildren && !hasContent);

    let badgeContent: unknown = nothing;
    if (!this.dot) {
      if (hasContent) {
        badgeContent = html`<slot name="content">${this.content}</slot>`;
      } else if (textChildren) {
        badgeContent = html`<slot></slot>`;
      } else if (hasChildren) {
        badgeContent = this.locale.t("badge.default");
      }
    }

    const badge = html`<span
      part=${standalone ? "base badge" : "badge"}
      class=${classMap({
        badge: true,
        [this.color]: true,
        [this.variant]: true,
        [this.size]: true,
        standalone,
        [this.position]: !standalone,
        dot: this.dot,
      })}
      role=${this.badgeRole || nothing}
      aria-label=${this.aria.label ?? nothing}
      style=${styleMap({
        borderRadius: this.borderRadius,
        borderWidth: this.borderWidth,
      })}
      >${
        this.slots.test("icon")
          ? html`<span class="icon" part="icon"
              ><slot name="icon"></slot
            ></span>`
          : nothing
      }${badgeContent}</span
    >`;

    if (standalone) return badge;
    return html`<div part="base" class="badgeWrapper">
      <div class="content"><slot></slot></div>
      ${badge}
    </div>`;
  }
}

declare global {
  interface HTMLElementTagNameMap {
    "minerva-badge": MinervaBadge;
  }
}

// packages/native/src/components/Badge/Badge.tsx
import type { ReactNode } from "react";
import {
  Text,
  View,
  type StyleProp,
  type TextStyle,
  type ViewProps,
  type ViewStyle,
} from "react-native";
import { useI18n, useTheme } from "../../theme/MinervaProvider";
import { part } from "../../internal/parts";
import { colorRole, weight, type NativeColor } from "../../internal/styles";

export type BadgeVariant = "solid" | "subtle" | "outline";
export type BadgeSize = "small" | "medium" | "large";
export type BadgePosition =
  "top-right" | "top-left" | "bottom-right" | "bottom-left";

export interface BadgeProps extends Omit<ViewProps, "style" | "children"> {
  /**
   * Content of the badge: a count (capped at `max`) or a short text. When
   * omitted, `children` is the badge content of a standalone badge
   */
  content?: ReactNode;
  /**
   * Counts above it show as `{max}+`
   * @default 99
   */
  max?: number;
  /**
   * Renders a small dot instead of content
   * @default false
   */
  dot?: boolean;
  /**
   * Shows the badge when the count is 0
   * @default false
   */
  showZero?: boolean;
  /**
   * Semantic color of the badge
   * @default "primary"
   */
  color?: NativeColor;
  /**
   * Visual style: `solid` (filled), `subtle` (tinted background) or
   * `outline` (bordered)
   * @default "solid"
   */
  variant?: BadgeVariant;
  /**
   * Badge size
   * @default "medium"
   */
  size?: BadgeSize;
  /**
   * Corner of the children the badge is placed on (ignored by standalone
   * badges)
   * @default "top-right"
   */
  position?: BadgePosition;
  /** Extra offset `[x, y]` of an attached badge, in dp (x moves inwards) */
  offset?: [number, number];
  /** Icon displayed before the content */
  icon?: ReactNode;
  /**
   * The element the badge is attached to. Without `content` / `dot`, a
   * string child is the content of a standalone badge
   */
  children?: ReactNode;
  /** Accessible label of the badge, e.g. "5 unread messages" */
  "aria-label"?: string;
  /** Style of the root view */
  style?: StyleProp<ViewStyle>;
  /** Style of the badge itself */
  badgeStyle?: StyleProp<ViewStyle>;
  /** Style of the content text */
  textStyle?: StyleProp<TextStyle>;
}

const isText = (node: ReactNode) =>
  typeof node === "string" || typeof node === "number";

/**
 * Badge: a count, short text or dot, standalone or on a corner of its
 * children (an icon, an avatar...). Announced as a status with its content
 * (dots: the localized "Badge").
 */
export function Badge({
  content,
  max = 99,
  dot = false,
  showZero = false,
  color = "primary",
  variant = "solid",
  size = "medium",
  position = "top-right",
  offset,
  icon,
  children,
  "aria-label": ariaLabel,
  accessibilityLabel,
  style,
  badgeStyle,
  textStyle,
  ...rest
}: BadgeProps) {
  const { tokens: t, fonts } = useTheme();
  const { t: tr } = useI18n();
  const role = colorRole(t, color);

  // `<Badge>New</Badge>`: standalone badge whose content is the text child
  const standalone =
    children === undefined ||
    children === null ||
    (content === undefined && !dot && isText(children));
  const value = content === undefined && standalone ? children : content;

  const display = typeof value === "number" && value > max ? `${max}+` : value;
  const hidden =
    !dot &&
    (value === undefined ||
      value === null ||
      value === false ||
      value === "" ||
      (value === 0 && !showZero));

  const height =
    size === "small"
      ? t.space["4"]
      : size === "large"
        ? t.space["6"]
        : t.space["5"];
  const dotSize =
    size === "small"
      ? t.space["1-5"]
      : size === "large"
        ? t.space["2-5"]
        : t.space["2"];
  const fontSize =
    size === "small"
      ? Math.round(t.fontSize.xs * 0.85)
      : size === "large"
        ? t.fontSize.sm
        : t.fontSize.xs;

  const colors: ViewStyle =
    variant === "solid"
      ? { backgroundColor: role.solid, borderColor: role.solid }
      : variant === "subtle"
        ? { backgroundColor: role.subtle, borderColor: role.subtle }
        : {
            backgroundColor: t.colors["surface-color"],
            borderColor: role.border,
          };
  const foreground =
    variant === "solid"
      ? role.onSolid
      : color === "neutral"
        ? t.colors["text-color"]
        : role.text;

  const label =
    accessibilityLabel ??
    ariaLabel ??
    (dot || !isText(display) ? tr("badge.default") : String(display));

  const attached = !standalone;
  const vertical = position.startsWith("top") ? "top" : "bottom";
  const horizontal = position.endsWith("right") ? "right" : "left";
  const anchor = (dot ? dotSize : height) / 2;
  const [dx, dy] = offset ?? [0, 0];
  const placement: ViewStyle | null = attached
    ? {
        position: "absolute",
        zIndex: 1,
        [vertical]: -anchor + dy,
        [horizontal]: -anchor + dx,
        // a ring separating a filled badge from the element below
        ...(variant === "outline"
          ? null
          : { borderColor: t.colors["surface-color"] }),
      }
    : null;

  const badge = hidden ? null : (
    <View
      role="status"
      accessible
      accessibilityLabel={label}
      {...part("badge", "badge", {
        color,
        variant,
        size,
        dot,
        position: attached ? position : undefined,
      })}
      {...(attached ? null : rest)}
      style={[
        dot
          ? { width: dotSize, height: dotSize, borderRadius: dotSize }
          : {
              minWidth: height,
              height,
              borderRadius: height,
              paddingHorizontal: t.space[size === "large" ? "2" : "1-5"],
              flexDirection: "row",
              alignItems: "center",
              justifyContent: "center",
              gap: t.space["1"],
            },
        { borderWidth: 1 },
        colors,
        placement,
        !attached && { alignSelf: "flex-start" },
        badgeStyle,
        !attached && style,
      ]}
    >
      {dot ? null : (
        <>
          {icon}
          {isText(display) ? (
            <Text
              numberOfLines={1}
              allowFontScaling={false}
              style={[
                {
                  color: foreground,
                  fontSize,
                  lineHeight: Math.round(fontSize * 1.2),
                  fontWeight: weight(t, "semibold"),
                  fontVariant: ["tabular-nums"],
                  ...(fonts.sans ? { fontFamily: fonts.sans } : null),
                },
                textStyle,
              ]}
              {...part("badge", "content")}
            >
              {display}
            </Text>
          ) : (
            display
          )}
        </>
      )}
    </View>
  );

  if (!attached) return badge;
  return (
    <View
      {...part("badge", "root", { position })}
      {...rest}
      style={[{ position: "relative", alignSelf: "flex-start" }, style]}
    >
      {children}
      {badge}
    </View>
  );
}
