// packages/lib-web-components/src/components/textarea/textarea.ts
import { css, html, nothing } from "lit";
import { property, query } from "lit/decorators.js";
import { classMap } from "lit/directives/class-map.js";
import { live } from "lit/directives/live.js";
import styles from "@lib-core-styles/components/Textarea/textarea.module.scss?inline";
import { AriaController } from "../../internal/aria";
import { DEV, devWarn } from "../../internal/dev";
import {
  FormAssociatedElement,
  type ValidityResult,
  validityFlags,
} from "../../internal/form";
import { LocaleController } from "../../internal/locale";
import { hostStyles } from "../../internal/minerva-element";
import { sharedStyles } from "../../internal/styles";

export type TextareaVariant = "outline" | "filled" | "unstyled";
export type TextareaSize = "small" | "medium" | "large";

/**
 * Multi-line text field sharing the input's look (`<Textarea>` of lib-core).
 * Manual resizing is disabled, as in lib-core: set `rows` or size the
 * element instead.
 *
 * Form-associated: submits `value` under `name`, supports `required`,
 * `minlength` / `maxlength` validation (the browser's messages, from the
 * inner `<textarea>`), `form.reset()` and `<fieldset disabled>`. Name it with
 * `<label for>`, a wrapping `<label>`, `aria-label` or `aria-labelledby`.
 *
 * @summary Multi-line text field.
 * @tag minerva-textarea
 * @csspart root - The native `<textarea>`
 * @fires input - The value changed (each keystroke; native, composed)
 * @fires change - The value was committed (blur), re-dispatched from the inner textarea
 * @fires minerva-input - Same as `input`, with `detail: { value }`
 * @fires minerva-change - Same as `change`, with `detail: { value }`
 */
export class MinervaTextarea extends FormAssociatedElement {
  static override tagName = "minerva-textarea";
  static override shadowRootOptions = {
    ...FormAssociatedElement.shadowRootOptions,
    delegatesFocus: true,
  };
  static override styles = [
    hostStyles,
    css`
      :host {
        display: block;
        width: 100%;
        min-width: 0;
      }
    `,
    sharedStyles(styles),
  ];

  /** Current value (property; the `value` attribute sets `defaultValue`) */
  @property({ attribute: false })
  value = "";

  /**
   * Initial value, restored by `form.reset()` (the `value` attribute). Like
   * `<textarea>`, changing it also changes `value` until the user edits it
   */
  @property({ attribute: "value" })
  defaultValue = "";

  /** Visual style */
  @property({ reflect: true })
  variant: TextareaVariant = "outline";

  /** Font size and minimum height */
  @property({ reflect: true })
  size: TextareaSize = "medium";

  /** Error state; sets aria-invalid */
  @property({ type: Boolean, reflect: true })
  invalid = false;

  /** Placeholder text */
  @property()
  placeholder = "";

  /** Read-only: focusable and submitted, not editable */
  @property({ type: Boolean, reflect: true, attribute: "readonly" })
  readOnly = false;

  /** Visible text lines */
  @property({ type: Number })
  rows?: number;

  /** Minimum length */
  @property({ type: Number, attribute: "minlength" })
  minLength?: number;

  /** Maximum length */
  @property({ type: Number, attribute: "maxlength" })
  maxLength?: number;

  /** Autocomplete hint */
  @property()
  autocomplete?: string;

  /** Text wrapping when submitted ("soft" / "hard" / "off") */
  @property()
  wrap?: "soft" | "hard" | "off";

  @query("textarea")
  private textarea!: HTMLTextAreaElement;

  private readonly locale = new LocaleController(this);
  private readonly aria = new AriaController(this, () => this.labels);

  /** The user (or a script setting `value`) changed the value */
  private dirty = false;

  override focus(options?: FocusOptions): void {
    this.textarea?.focus(options);
  }

  override blur(): void {
    this.textarea?.blur();
  }

  /** Selects the text */
  select(): void {
    this.textarea?.select();
  }

  protected getFormValue(): string {
    return this.value;
  }

  protected override getValidity(): ValidityResult {
    const textarea = this.textarea;
    if (!textarea) {
      return this.required && !this.value
        ? {
            flags: { valueMissing: true },
            message: this.locale.t("validation.valueMissing"),
          }
        : { flags: {}, message: "" };
    }
    return {
      flags: validityFlags(textarea.validity),
      message: textarea.validationMessage,
      anchor: textarea,
    };
  }

  protected resetFormValue(): void {
    this.dirty = false;
    this.value = this.defaultValue;
  }

  protected override restoreFormState(state: unknown): void {
    if (typeof state === "string") this.value = state;
  }

  protected override willUpdate(changed: Map<PropertyKey, unknown>): void {
    if (changed.has("value") && changed.get("value") !== undefined) {
      this.dirty = this.value !== this.defaultValue || this.dirty;
    }
    // first update: a value set before connecting wins over the default
    // unless the value attribute is present
    if (
      changed.has("defaultValue") &&
      !this.dirty &&
      (this.hasUpdated || this.hasAttribute("value"))
    ) {
      this.value = this.defaultValue;
    }
    if (
      DEV &&
      (changed.has("minLength") || changed.has("maxLength")) &&
      this.minLength !== undefined &&
      this.maxLength !== undefined &&
      this.minLength > this.maxLength
    ) {
      devWarn(
        MinervaTextarea.tagName,
        `minlength (${this.minLength}) is greater than maxlength (${this.maxLength}): no value can be valid.`,
      );
    }
  }

  private handleInput() {
    this.value = String(this.textarea.value);
    this.emit("minerva-input", { value: this.value });
  }

  private handleChange() {
    this.value = String(this.textarea.value);
    // `change` is not composed: re-dispatch it from the host
    this.dispatchEvent(new Event("change", { bubbles: true }));
    this.emit("minerva-change", { value: this.value });
  }

  protected override hookStates() {
    return {
      disabled: this.isDisabled,
      invalid: this.invalid || this.aria.attr("aria-invalid") === "true",
      readonly: this.readOnly,
      required: this.required,
      size: this.size,
      variant: this.variant,
    };
  }

  protected override render() {
    const invalid = this.invalid || this.aria.attr("aria-invalid") === "true";
    return html`<textarea
      part="root"
      class=${classMap({
        textarea: true,
        [this.variant]: true,
        [this.size]: true,
        invalid,
      })}
      style="resize: none"
      .value=${live(this.value)}
      name=${this.name || nothing}
      placeholder=${this.placeholder || nothing}
      rows=${this.rows ?? nothing}
      ?disabled=${this.isDisabled}
      ?readonly=${this.readOnly}
      ?required=${this.required}
      minlength=${this.minLength ?? nothing}
      maxlength=${this.maxLength ?? nothing}
      autocomplete=${(this.autocomplete as never) ?? nothing}
      wrap=${this.wrap ?? nothing}
      aria-label=${this.aria.label ?? nothing}
      aria-description=${this.aria.description ?? nothing}
      aria-invalid=${invalid ? "true" : nothing}
      aria-required=${this.aria.attr("aria-required") ?? nothing}
      aria-readonly=${this.aria.attr("aria-readonly") ?? nothing}
      @input=${this.handleInput}
      @change=${this.handleChange}
    ></textarea>`;
  }
}

declare global {
  interface HTMLElementTagNameMap {
    "minerva-textarea": MinervaTextarea;
  }
}

// packages/angular/src/components/textarea/textarea.ts
import {
  ChangeDetectionStrategy,
  Component,
  ElementRef,
  ViewEncapsulation,
  booleanAttribute,
  computed,
  inject,
  input,
  model,
} from "@angular/core";
import { cn } from "@minerva/core";
import { classOf } from "../../internal/classes";
import {
  MnFormValueControl,
  fieldWiring,
  injectFormField,
  provideValueAccessor,
} from "../../internal/forms";
import { textareaStyles as s } from "../../internal/styles";

export type TextareaVariant = "outline" | "filled" | "unstyled";
export type TextareaSize = "small" | "medium" | "large";

/**
 * Textarea: a multi-line text field sharing Input's look. An attribute
 * component, so the host IS the native `<textarea>` (native attributes such
 * as `rows`, `placeholder`, `maxlength` and the native `input` / `change`
 * events apply as usual). Manual resizing is disabled (set `rows` or layout
 * dimensions instead).
 *
 * Two-way binding: `[(value)]`, `ngModel` or a Reactive Forms control
 * (ControlValueAccessor). Inside `<mn-form-control>` it takes the field's id,
 * description, invalid / required / read-only / disabled states.
 *
 * @example
 * <textarea mnTextarea aria-label="Bio" rows="4" [(value)]="bio"></textarea>
 * <textarea mnTextarea formControlName="comment"></textarea>
 */
@Component({
  selector: "textarea[mnTextarea]",
  exportAs: "mnTextarea",
  encapsulation: ViewEncapsulation.None,
  changeDetection: ChangeDetectionStrategy.OnPush,
  providers: [provideValueAccessor(() => MnTextarea)],
  host: {
    "[class]": "classes()",
    "[style.resize]": "'none'",
    "[attr.id]": "field.id()",
    "[value]": "current()",
    "[disabled]": "field.disabled()",
    "[readOnly]": "field.readOnly()",
    "[required]": "required()",
    "[attr.aria-describedby]": "field.describedBy()",
    "[attr.aria-invalid]": "field.invalid() ? 'true' : null",
    "[attr.aria-required]": "fieldContext?.required() ? 'true' : null",
    "[attr.aria-readonly]": "fieldContext?.readOnly() ? 'true' : null",
    "data-minerva": "textarea",
    "data-part": "root",
    "[attr.data-disabled]": "field.disabled() ? '' : null",
    "[attr.data-invalid]": "field.invalid() ? '' : null",
    "[attr.data-readonly]": "field.readOnly() ? '' : null",
    "[attr.data-required]": "field.required() ? '' : null",
    "[attr.data-size]": "size()",
    "[attr.data-variant]": "variant()",
    "(input)": "onInput()",
    "(blur)": "notifyTouched()",
  },
  template: ``,
})
export class MnTextarea extends MnFormValueControl<string> {
  /** Current text (two-way: `[(value)]`) */
  readonly value = model<string | undefined>(undefined);
  /**
   * Initial text when `value` is not bound (like `<textarea>`, changing it
   * also changes the text until the user edits it)
   * @default ""
   */
  readonly defaultValue = input<string>("");
  /** Visual style @default "outline" */
  readonly variant = input<TextareaVariant>("outline");
  /** Font size and minimum height @default "medium" */
  readonly size = input<TextareaSize>("medium");
  /** Error state (also set by an invalid FormControl); sets aria-invalid @default false */
  readonly invalid = input(false, { transform: booleanAttribute });
  /** Disables the control @default false */
  readonly disabled = input(false, { transform: booleanAttribute });
  /** Read-only: focusable and submitted, not editable @default false */
  readonly readOnly = input(false, { transform: booleanAttribute });
  /** The control must have a value for the form to be submitted @default false */
  readonly required = input(false, { transform: booleanAttribute });
  /** id of the textarea (default: the field's) */
  readonly id = input<string | undefined>(undefined);
  /** Extra ids of elements describing the textarea */
  readonly ariaDescribedby = input<string | undefined>(undefined, {
    alias: "aria-describedby",
  });

  private readonly host = inject<ElementRef<HTMLTextAreaElement>>(ElementRef);
  protected readonly fieldContext = injectFormField();
  protected readonly field = fieldWiring(this.fieldContext, {
    id: () => this.id(),
    describedBy: () => this.ariaDescribedby(),
    invalid: () => this.invalid() || this.controlInvalid(),
    required: () => this.required(),
    readOnly: () => this.readOnly(),
    disabled: () => this.disabled() || this.formDisabled(),
  });
  protected readonly current = computed(
    () => this.value() ?? this.defaultValue() ?? "",
  );
  protected readonly classes = computed(() =>
    cn(
      s.textarea,
      classOf(s, this.variant()),
      classOf(s, this.size()),
      this.field.invalid() && s.invalid,
    ),
  );

  override writeValue(value: string | null | undefined): void {
    this.value.set(value == null ? "" : String(value));
  }

  protected onInput(): void {
    const next = this.host.nativeElement.value;
    this.value.set(next);
    this.notifyChange(next);
  }
}
