// packages/lib-web-components/src/components/toast/toast.ts
import { css, html, nothing, type PropertyValues } from "lit";
import { property, query, state } from "lit/decorators.js";
import { classMap } from "lit/directives/class-map.js";
import { repeat } from "lit/directives/repeat.js";
import { styleMap } from "lit/directives/style-map.js";
import {
  contains,
  focusElement,
  formatHotkey,
  getActiveElement,
  getAdjacentTabbable,
  getTabbables,
  matchesHotkey,
} from "@minerva/core";
import styles from "@lib-core-styles/components/Toast/toast.module.scss?inline";
import { popoverResetStyles } from "../../controllers/floating-layer";
import { AriaController } from "../../internal/aria";
import { DEV, devWarn } from "../../internal/dev";
import { getDirection, hideTopLayer, showTopLayer } from "../../internal/dom";
import {
  IconCircleCheck,
  IconCircleX,
  IconInfo,
  IconSpinner,
  IconTriangleAlert,
  IconX,
} from "../../internal/icons";
import { LocaleController } from "../../internal/locale";
import { MinervaElement, hostStyles } from "../../internal/minerva-element";
import { itemParts } from "../../internal/styling-hooks";
import {
  TOAST_REGION_TAG,
  createToast,
  toastRegions,
  toastStore,
  type ToastApi,
  type ToastCloseReason,
  type ToastColor,
  type ToastItem,
  type ToastLifecycleEvent,
  type ToastPosition,
} from "./toast-store";
import { sharedStyles } from "../../internal/styles";

const ICONS: Record<ToastColor, unknown> = {
  info: IconInfo,
  success: IconCircleCheck,
  warning: IconTriangleAlert,
  danger: IconCircleX,
};

const POSITIONS: readonly ToastPosition[] = [
  "top-right",
  "top-left",
  "top-center",
  "bottom-right",
  "bottom-left",
  "bottom-center",
];

const DEFAULT_HOTKEY = ["F8"];
/** The open toasts of the viewport (public item part `toast--open`) */
const OPEN_TOAST_CHILD = ':scope > [part~="toast--open"]';
/** The close button of a toast (public part) */
const CLOSE_BUTTON_CHILD = ':scope > [part~="close-button"]';

/** `hotkey` attribute: keys separated by spaces, commas or "+"; "" disables. */
const hotkeyConverter = {
  fromAttribute: (value: string | null): string[] =>
    value === null
      ? DEFAULT_HOTKEY
      : value
          .split(/[\s,+]+/)
          .map((key) => key.trim())
          .filter(Boolean),
};

/** One document keydown listener (hotkeys) shared by every region. */
let hotkeyUsers = 0;
const onDocumentKeyDown = (event: KeyboardEvent) => {
  for (const region of toastRegions.ordered()) {
    if (region instanceof MinervaToastRegion && region.handleHotkey(event)) {
      return;
    }
  }
};

/**
 * Toast region (lib-core's `ToastProvider` viewport): renders the toasts
 * shown with the `toast()` API, stacked at `position`, with the same DOM,
 * classes, roles and keyboard behaviour as lib-core.
 *
 * - Each toast is a live region: `role="status"`, or `role="alert"` for
 *   danger toasts (loading toasts stay a polite status). The stack is a
 *   `role="region"` labelled "Notifications (F8)" (localized).
 * - Toasts close after `duration` (default 4000 ms; loading toasts stay
 *   open); the countdown pauses while a toast is hovered or holds focus.
 * - The hotkey (F8 by default) moves focus to the region; Escape closes the
 *   focused toast; closing a focused toast moves focus to the next toast,
 *   else back where it came from (never to `<body>`).
 * - Toasts without an explicit region render in the first connected region
 *   (document order); `toast.region(el)` / `{ region }` target another one,
 *   e.g. inside a `<minerva-config>` scope (its theme and language apply).
 *   When `toast()` runs with no region on the page, one is appended to
 *   `<body>` (and removed again when a page region connects).
 * - The stack is shown in the top layer (Popover API, `popover="manual"`)
 *   and raised again when a toast appears or a Minerva overlay opens, so
 *   toasts stay above modals and stay clickable. Like lib-core's
 *   `ToastProvider` viewport, the region is treated like any other page
 *   content by a modal's hide-others: while a modal dialog (modal, drawer,
 *   confirm, command, modal popover / menu) is open, the region (or its
 *   ancestor next to the dialog) gets `aria-hidden="true"` and assistive
 *   technologies only see the dialog; it is exposed again when the dialog
 *   closes. Opt out on a given region with the `data-minerva-keep-visible`
 *   attribute (core's hide-others never hides such elements).
 *
 * @summary Toast stack (viewport) rendering the toasts of the `toast()` API.
 * @tag minerva-toast-region
 * @csspart root - The fixed stack (`role="region"`)
 * @csspart toast - A toast (`role="status"`, or `alert` for danger)
 * @csspart toast--open - Item state of `toast`: open
 * @csspart toast--closed - Item state of `toast`: closed
 * @csspart toast--color-info - Item state of `toast`: color info
 * @csspart toast--color-success - Item state of `toast`: color success
 * @csspart toast--color-warning - Item state of `toast`: color warning
 * @csspart toast--color-danger - Item state of `toast`: color danger
 * @csspart toast--loading - Item state of `toast`: loading
 * @csspart icon - The icon of a toast (spinner while loading)
 * @csspart title - The title of a toast
 * @csspart description - The description of a toast
 * @csspart action - The action button of a toast
 * @csspart close-button - The close (×) button of a toast
 * @csspart progress - The countdown bar of a timed toast
 * @fires minerva-close - A toast of this region started closing (`detail: { id, reason }`; reason: "timeout" | "close-button" | "action" | "escape" | "dismiss" | "overflow")
 * @fires minerva-after-close - A toast of this region was removed after its exit animation (`detail: { id }`)
 */
export class MinervaToastRegion extends MinervaElement {
  static override tagName = TOAST_REGION_TAG;
  static override styles = [
    hostStyles,
    popoverResetStyles,
    css`
      :host {
        display: contents;
      }
      /* lib-core renders a decorative <ProgressIndicator variant="spinner"
         size="small" color="current"> in loading toasts */
      .progressIndicator {
        display: inline-flex;
        width: 100%;
        height: 100%;
        color: currentColor;
      }
      .spinner {
        display: inline-flex;
        width: 100%;
        height: 100%;
        animation: spin 1s linear infinite;
      }
      @keyframes spin {
        to {
          transform: rotate(360deg);
        }
      }
      @media (prefers-reduced-motion: reduce) {
        .spinner {
          animation-duration: 2s;
        }
      }
    `,
    sharedStyles(styles),
  ];

  /** Where the toasts are stacked */
  @property({ reflect: true })
  position: ToastPosition = "top-right";

  /** Maximum number of toasts shown at once; the oldest close first */
  @property({ type: Number })
  max = Infinity;

  /** Keeps the countdown running while a toast is hovered or focused */
  @property({ type: Boolean, attribute: "no-pause-on-hover" })
  noPauseOnHover = false;

  /** Accessible label of the close buttons (default: localized "Close") */
  @property({ attribute: "close-label" })
  closeLabel?: string;

  /**
   * Keys pressed together to focus the region: key codes (`F8`, `KeyT`),
   * keys or modifiers (`altKey`, `ctrlKey`, `metaKey`, `shiftKey`). The
   * attribute separates them with spaces / commas / "+" (`hotkey="altKey KeyT"`);
   * an empty value disables it. Shown in the default region label
   */
  @property({ attribute: "hotkey", converter: hotkeyConverter })
  hotkey: string[] = DEFAULT_HOTKEY;

  @state()
  private items: ToastItem[] = [];

  @query(".viewport")
  private viewport?: HTMLElement;

  private readonly locale = new LocaleController(this);
  private readonly aria = new AriaController(this);
  private cleanups: Array<() => void> = [];
  /** Element focused before focus entered the region */
  private returnFocus: HTMLElement | null = null;
  private boundApi?: ToastApi;

  /**
   * The toast API bound to this region:
   * `region.toast.success("Saved")` renders in this element.
   */
  get toast(): ToastApi {
    this.boundApi ??= createToast(toastStore, this);
    return this.boundApi;
  }

  override connectedCallback(): void {
    super.connectedCallback();
    this.cleanups = [
      toastStore.subscribe(() => this.refresh()),
      toastRegions.subscribe(() => this.refresh()),
      toastStore.subscribeLifecycle(this.onLifecycle),
    ];
    const doc = this.ownerDocument;
    doc.addEventListener("minerva-after-open", this.raise);
    this.cleanups.push(() =>
      doc.removeEventListener("minerva-after-open", this.raise),
    );
    if (hotkeyUsers++ === 0) {
      doc.addEventListener("keydown", onDocumentKeyDown);
    }
    this.cleanups.push(() => {
      if (--hotkeyUsers === 0) {
        doc.removeEventListener("keydown", onDocumentKeyDown);
      }
    });
    toastRegions.register(this);
    this.refresh();
    if (this.hasUpdated) showTopLayer(this.viewport);
  }

  override disconnectedCallback(): void {
    super.disconnectedCallback();
    for (const cleanup of this.cleanups) cleanup();
    this.cleanups = [];
    toastRegions.unregister(this);
    hideTopLayer(this.viewport);
  }

  /** Toasts rendered here: explicit ones, plus the default ones when owner. */
  private refresh = () => {
    if (!this.isConnected) return;
    const seen = new Set<ToastItem["id"]>();
    const mine: ToastItem[] = [];
    const all = toastStore.getSnapshot();
    for (let i = all.length - 1; i >= 0; i -= 1) {
      const item = all[i];
      if (seen.has(item.id) || toastRegions.regionOf(item) !== this) continue;
      seen.add(item.id);
      mine.unshift(item);
    }
    // Over `max`: the oldest open toasts close (onClose runs as usual)
    const open = mine.filter((item) => item.state === "open");
    const overflow = open.slice(0, Math.max(0, open.length - this.max));
    if (overflow.length > 0) {
      for (const item of overflow) toastStore.dismiss(item.id, "overflow");
      return;
    }
    const known = new Set(this.items.map((item) => item.id));
    const added = mine.some((item) => !known.has(item.id));
    this.items = mine;
    if (added) this.raise();
  };

  /** Puts the stack back on top of the top layer (unless focus is inside). */
  private raise = () => {
    const viewport = this.viewport;
    if (!viewport || contains(viewport, getActiveElement())) return;
    hideTopLayer(viewport);
    showTopLayer(viewport);
  };

  private onLifecycle = (event: ToastLifecycleEvent) => {
    if (toastRegions.regionOf(event.item) !== this) return;
    if (event.type === "close") {
      this.emit("minerva-close", { id: event.item.id, reason: event.reason });
    } else {
      this.emit("minerva-after-close", { id: event.item.id });
    }
  };

  /**
   * Hotkey handling (called by the shared document listener): focuses the
   * region when `event` matches its hotkey and it holds open toasts.
   * @internal
   */
  handleHotkey(event: KeyboardEvent): boolean {
    const viewport = this.viewport;
    if (!viewport || !matchesHotkey(event, this.hotkey)) return false;
    if (!viewport.querySelector(OPEN_TOAST_CHILD)) return false;
    event.preventDefault();
    const active = getActiveElement() as HTMLElement | null;
    if (
      active &&
      active !== this.ownerDocument.body &&
      !contains(viewport, active)
    ) {
      this.returnFocus = active;
    }
    viewport.setAttribute("tabindex", "-1");
    focusElement(viewport);
    return true;
  }

  /** Moves focus to the region (as the hotkey does). */
  override focus(options?: FocusOptions): void {
    const viewport = this.viewport;
    if (!viewport) return;
    viewport.setAttribute("tabindex", "-1");
    viewport.focus(options);
  }

  protected override willUpdate(changed: PropertyValues<this>): void {
    if (DEV && changed.has("position") && !POSITIONS.includes(this.position)) {
      devWarn(
        TOAST_REGION_TAG,
        `invalid position "${this.position}" (expected ${POSITIONS.join(" | ")}).`,
      );
    }
  }

  protected override firstUpdated(): void {
    showTopLayer(this.viewport);
  }

  protected override updated(changed: PropertyValues<this>): void {
    if (changed.has("max") && changed.get("max") !== undefined) {
      queueMicrotask(() => this.refresh());
    }
  }

  /**
   * Moves focus out of the toast `el` before it closes: the close button
   * (else first tabbable) of the next open toast, else the element focused
   * before focus entered the region, else the nearest tabbable outside the
   * region, else the region itself. Never <body>.
   */
  private moveFocusFrom(el: HTMLElement) {
    const viewport = this.viewport;
    if (!viewport) return;
    const others = Array.from(
      viewport.querySelectorAll<HTMLElement>(OPEN_TOAST_CHILD),
    ).filter((other) => other !== el);
    const next =
      others.find(
        (other) =>
          el.compareDocumentPosition(other) & Node.DOCUMENT_POSITION_FOLLOWING,
      ) ?? others[others.length - 1];
    if (next) {
      const target =
        next.querySelector<HTMLElement>(CLOSE_BUTTON_CHILD) ??
        getTabbables(next)[0];
      if (focusElement(target)) return;
    }
    const previous = this.returnFocus;
    if (
      previous?.isConnected &&
      !contains(viewport, previous) &&
      focusElement(previous)
    ) {
      return;
    }
    if (focusElement(getAdjacentTabbable(this))) return;
    viewport.setAttribute("tabindex", "-1");
    focusElement(viewport, { preventScroll: true });
  }

  /** Dismisses a toast, first moving focus out of it when it is inside. */
  private close(item: ToastItem, el: HTMLElement, reason: ToastCloseReason) {
    if (contains(el, getActiveElement())) this.moveFocusFrom(el);
    toastStore.dismiss(item.id, reason);
  }

  private pause(item: ToastItem) {
    if (!this.noPauseOnHover) toastStore.pause(item.id);
  }

  private resume(item: ToastItem) {
    if (!this.noPauseOnHover) toastStore.resume(item.id);
  }

  private onViewportFocusIn = (event: FocusEvent) => {
    // Remember where focus came from to give it back once the toasts close
    const from = event.relatedTarget as HTMLElement | null;
    const viewport = event.currentTarget as HTMLElement;
    if (from && !contains(viewport, from)) this.returnFocus = from;
  };

  private onViewportFocusOut = (event: FocusEvent) => {
    // The region is only programmatically focusable while focus is in it
    const viewport = event.currentTarget as HTMLElement;
    if (!contains(viewport, event.relatedTarget as Node | null)) {
      viewport.removeAttribute("tabindex");
    }
  };

  private renderIcon(item: ToastItem) {
    if (item.icon === null) return nothing;
    const icon =
      item.icon !== undefined
        ? item.icon
        : item.loading
          ? html`<div class="progressIndicator current" aria-hidden="true">
              <span class="spinner small">${IconSpinner}</span>
            </div>`
          : ICONS[item.color];
    return html`<span class="icon" part="icon" aria-hidden="true"
      >${icon}</span
    >`;
  }

  private renderItem(item: ToastItem) {
    const closing = item.state === "closing";
    const toastEl = (event: Event) =>
      (event.currentTarget as HTMLElement).closest<HTMLElement>(".toast")!;
    const states = {
      state: closing ? "closed" : "open",
      color: item.color,
      loading: item.loading,
    };
    return html`<div
      part=${itemParts("toast", states)}
      class=${classMap({ toast: true, [item.color]: true })}
      data-state=${states.state}
      role=${item.color === "danger" && !item.loading ? "alert" : "status"}
      style=${styleMap(
        item.duration > 0 ? { "--toast-duration": `${item.duration}ms` } : {},
      )}
      @mouseenter=${() => this.pause(item)}
      @mouseleave=${() => this.resume(item)}
      @focusin=${() => this.pause(item)}
      @focusout=${(event: FocusEvent) => {
        if (!contains(toastEl(event), event.relatedTarget as Node | null)) {
          this.resume(item);
        }
      }}
      @keydown=${(event: KeyboardEvent) => {
        // Escape dismisses the toast holding focus (and only that one)
        if (event.key !== "Escape" || closing || event.isComposing) return;
        event.preventDefault();
        event.stopPropagation();
        this.close(item, toastEl(event), "escape");
      }}
    >
      ${this.renderIcon(item)}
      <div class="content">
        ${
          item.title
            ? html`<div class="title" part="title">${item.title}</div>`
            : nothing
        }
        ${
          item.description
            ? html`<div class="description" part="description">
                ${item.description}
              </div>`
            : nothing
        }
      </div>
      ${
        item.action
          ? html`<button
              type="button"
              class="action"
              part="action"
              @click=${(event: MouseEvent) => {
                item.action?.onClick();
                this.close(item, toastEl(event), "action");
              }}
            >
              ${item.action.label}
            </button>`
          : nothing
      }
      ${
        item.closable
          ? html`<button
              type="button"
              class="close"
              part="close-button"
              aria-label=${this.closeLabel ?? this.locale.t("toast.close")}
              @click=${(event: MouseEvent) =>
                this.close(item, toastEl(event), "close-button")}
            >
              ${IconX}
            </button>`
          : nothing
      }
      ${
        item.duration > 0 && !closing
          ? html`<span
              class="progress"
              part="progress"
              aria-hidden="true"
            ></span>`
          : nothing
      }
    </div>`;
  }

  protected override render() {
    const hotkeyLabel = formatHotkey(this.hotkey);
    const label =
      this.aria.label ??
      (hotkeyLabel
        ? this.locale.t("toast.regionWithHotkey", { hotkey: hotkeyLabel })
        : this.locale.t("toast.region"));
    const position = POSITIONS.includes(this.position)
      ? this.position
      : "top-right";
    return html`<div
      part="root"
      class=${classMap({ viewport: true, [position]: true })}
      popover="manual"
      role="region"
      aria-label=${label}
      dir=${getDirection(this)}
      @focusin=${this.onViewportFocusIn}
      @focusout=${this.onViewportFocusOut}
    >
      ${repeat(
        this.items,
        (item) => item.id,
        (item) => this.renderItem(item),
      )}
    </div>`;
  }
}

declare global {
  interface HTMLElementTagNameMap {
    "minerva-toast-region": MinervaToastRegion;
  }
}

// packages/react/src/components/Toast/Toast.tsx
import {
  useEffect,
  useMemo,
  useRef,
  useState,
  useSyncExternalStore,
  type CSSProperties,
  type ReactNode,
} from "react";
import { createPortal } from "react-dom";
import { cn } from "../../utils/cn";
import { hooks } from "../../internal/stylingHooks";
import {
  IconCircleCheck,
  IconCircleX,
  IconInfo,
  IconTriangleAlert,
  IconX,
} from "../../internal/icons";
import useI18n from "../../hooks/useI18n";
import { ProgressIndicator } from "../ProgressIndicator";
import { useIsClient } from "../../internal/useIsClient";
import {
  focusElement,
  formatHotkey,
  getAdjacentTabbable,
  getTabbables,
  matchesHotkey,
} from "@minerva/core";
import {
  createToast,
  toast,
  toastProviders,
  toastScopeOf,
  toastStore,
  type ToastItem,
} from "./store";
import type { ToastApi, ToastProviderProps } from "./types";
import styles from "./toast.module.scss";
import {
  ThemeScopeContext,
  usePortalContainer,
  useThemeScope,
  type ThemeScope,
} from "../../internal/themeScope";

const ICONS: Record<ToastItem["color"], ReactNode> = {
  info: <IconInfo aria-hidden="true" />,
  success: <IconCircleCheck aria-hidden="true" />,
  warning: <IconTriangleAlert aria-hidden="true" />,
  danger: <IconCircleX aria-hidden="true" />,
};

const SPINNER = (
  <ProgressIndicator
    variant="spinner"
    size="small"
    color="current"
    decorative
  />
);

const NO_TOASTS: ToastItem[] = [];
/** The open toasts of a viewport (public item hooks) */
const OPEN_TOAST_CHILD =
  ':scope > [data-minerva="toast-region"][data-part="toast"][data-state="open"]';
/** The close button of a toast (public part) */
const CLOSE_BUTTON_CHILD =
  ':scope > [data-minerva="toast-region"][data-part="close-button"]';
const DEFAULT_HOTKEY = ["F8"];

/**
 * Focus bookkeeping shared by the viewports of a provider: the element
 * focused before focus entered a toast region.
 */
interface ToastFocusTracker {
  /** Element to give focus back to once the toasts close */
  getReturnFocus: () => HTMLElement | null;
  setReturnFocus: (el: HTMLElement) => void;
  /** Registers the viewport element of a portal key (hotkey target) */
  registerViewport: (key: string, el: HTMLDivElement | null) => void;
}

/**
 * Moves focus out of the toast `el` before it closes: the close button (else
 * first button) of the next open toast, else the element focused before
 * focus entered the region, else the nearest tabbable outside the region,
 * else the region itself. Never <body>.
 */
const moveFocusFromToast = (el: HTMLElement, tracker: ToastFocusTracker) => {
  const viewport = el.parentElement;
  if (!viewport) return;
  const others = Array.from(
    viewport.querySelectorAll<HTMLElement>(OPEN_TOAST_CHILD),
  ).filter((other) => other !== el);
  const next =
    others.find(
      (other) =>
        el.compareDocumentPosition(other) & Node.DOCUMENT_POSITION_FOLLOWING,
    ) ?? others[others.length - 1];
  if (next) {
    const target =
      next.querySelector<HTMLElement>(CLOSE_BUTTON_CHILD) ??
      getTabbables(next)[0];
    if (focusElement(target)) return;
  }
  const previous = tracker.getReturnFocus();
  if (
    previous?.isConnected &&
    !viewport.contains(previous) &&
    focusElement(previous)
  ) {
    return;
  }
  if (focusElement(getAdjacentTabbable(viewport))) return;
  viewport.setAttribute("tabindex", "-1");
  focusElement(viewport, { preventScroll: true });
};
const getServerToasts = () => NO_TOASTS;
const getServerOwner = () => null;
const noopSubscribe = () => () => {};

/**
 * Returns the toast API bound to the calling component's scope: toasts shown
 * with it follow the nearest ConfigProvider (rendered into its portal host,
 * so its theme / palette / tokens apply, and labelled in its language). The
 * owning ToastProvider still renders them, with its position, max and
 * labels. Outside any nested scope it returns the `toast` export itself.
 *
 * Use it inside components; use `toast()` from code outside React (event
 * buses, API clients...), which uses the ToastProvider's (root) scope.
 */
export const useToast = (): ToastApi => {
  const scope = toastScopeOf(useThemeScope());
  return useMemo(
    () => (scope ? createToast(toastStore, scope) : toast),
    [scope],
  );
};

interface ToastViewItemProps {
  item: ToastItem;
  pauseOnHover: boolean;
  /** Explicit close label of the provider; localized in the item's scope otherwise */
  closeLabel?: string;
  tracker: ToastFocusTracker;
}

const ToastViewItem = ({
  item,
  pauseOnHover,
  closeLabel: closeLabelProp,
  tracker,
}: ToastViewItemProps) => {
  const { t } = useI18n();
  const rootRef = useRef<HTMLDivElement>(null);
  /** Dismisses the toast, first moving focus out of it when it is inside. */
  const close = () => {
    const el = rootRef.current;
    if (el?.contains(el.ownerDocument.activeElement)) {
      moveFocusFromToast(el, tracker);
    }
    toastStore.dismiss(item.id);
  };
  const closeLabel = closeLabelProp ?? t("toast.close");
  const pause = () => {
    if (pauseOnHover) toastStore.pause(item.id);
  };
  const resume = () => {
    if (pauseOnHover) toastStore.resume(item.id);
  };
  const closing = item.state === "closing";
  return (
    <div
      ref={rootRef}
      className={cn(styles.toast, styles[item.color])}
      // A pending (loading) toast is a polite status even when danger
      role={item.color === "danger" && !item.loading ? "alert" : "status"}
      style={
        item.duration > 0
          ? ({ "--toast-duration": `${item.duration}ms` } as CSSProperties)
          : undefined
      }
      onMouseEnter={pause}
      onMouseLeave={resume}
      onFocus={pause}
      onBlur={(e) => {
        if (!e.currentTarget.contains(e.relatedTarget as Node | null)) resume();
      }}
      onKeyDown={(e) => {
        // Escape dismisses the toast holding focus (and only that one)
        if (e.key !== "Escape" || closing || e.nativeEvent.isComposing) return;
        e.preventDefault();
        e.stopPropagation();
        close();
      }}
      {...hooks("toast-region", "toast", {
        state: closing ? "closed" : "open",
        color: item.color,
        loading: item.loading,
      })}
    >
      {item.icon !== null && (
        <span
          className={styles.icon}
          aria-hidden="true"
          {...hooks("toast-region", "icon")}
        >
          {item.icon === undefined
            ? item.loading
              ? SPINNER
              : ICONS[item.color]
            : item.icon}
        </span>
      )}
      <div className={styles.content}>
        {item.title && (
          <div className={styles.title} {...hooks("toast-region", "title")}>
            {item.title}
          </div>
        )}
        {item.description && (
          <div
            className={styles.description}
            {...hooks("toast-region", "description")}
          >
            {item.description}
          </div>
        )}
      </div>
      {item.action && (
        <button
          type="button"
          className={styles.action}
          {...hooks("toast-region", "action")}
          onClick={() => {
            item.action?.onClick();
            close();
          }}
        >
          {item.action.label}
        </button>
      )}
      {item.closable && (
        <button
          type="button"
          className={styles.close}
          aria-label={closeLabel}
          onClick={close}
          {...hooks("toast-region", "close-button")}
        >
          <IconX aria-hidden="true" />
        </button>
      )}
      {item.duration > 0 && !closing && (
        <span
          className={styles.progress}
          aria-hidden="true"
          {...hooks("toast-region", "progress")}
        />
      )}
    </div>
  );
};

/** Wraps `node` in the theme scope of the toast caller, when it has one. */
const withScope = (
  scope: ThemeScope | undefined,
  node: ReactNode,
  key?: string | number,
) =>
  scope ? (
    <ThemeScopeContext.Provider key={key} value={scope}>
      {node}
    </ThemeScopeContext.Provider>
  ) : (
    node
  );

interface ToastViewportProps {
  items: ToastItem[];
  position: NonNullable<ToastProviderProps["position"]>;
  pauseOnHover: boolean;
  "aria-label"?: string;
  closeLabel?: string;
  /** Formatted hotkey, appended to the default region label */
  hotkeyLabel: string;
  tracker: ToastFocusTracker;
  /** Portal key of the viewport */
  viewportKey: string;
}

const ToastViewport = ({
  items,
  position,
  pauseOnHover,
  "aria-label": ariaLabel,
  closeLabel,
  hotkeyLabel,
  tracker,
  viewportKey,
}: ToastViewportProps) => {
  const { t } = useI18n();
  return (
    <div
      ref={(el) => {
        tracker.registerViewport(viewportKey, el);
        return () => tracker.registerViewport(viewportKey, null);
      }}
      className={cn(styles.viewport, styles[position])}
      {...hooks("toast-region", "root")}
      role="region"
      aria-label={
        ariaLabel ??
        (hotkeyLabel
          ? t("toast.regionWithHotkey", { hotkey: hotkeyLabel })
          : t("toast.region"))
      }
      onFocus={(e) => {
        // Remember where focus came from to give it back once the toasts
        // it moved through close
        const from = e.relatedTarget as HTMLElement | null;
        if (from && !e.currentTarget.contains(from)) {
          tracker.setReturnFocus(from);
        }
      }}
      onBlur={(e) => {
        // The region is only programmatically focusable while focus is in it
        if (!e.currentTarget.contains(e.relatedTarget as Node | null)) {
          e.currentTarget.removeAttribute("tabindex");
        }
      }}
    >
      {items.map((item) =>
        withScope(
          item.scope,
          <ToastViewItem
            key={item.id}
            item={item}
            pauseOnHover={pauseOnHover}
            closeLabel={closeLabel}
            tracker={tracker}
          />,
          item.id,
        ),
      )}
    </div>
  );
};

/** Stable portal keys of the scoped containers */
const containerKeys = new WeakMap<HTMLElement, number>();
let containerKeyCounter = 0;
const containerKey = (container: HTMLElement): string => {
  let key = containerKeys.get(container);
  if (key === undefined) {
    key = ++containerKeyCounter;
    containerKeys.set(container, key);
  }
  return `scope-${key}`;
};

/**
 * Renders the toasts shown with `toast()` / `useToast()`. Place it once near
 * the root of the app, around the content or on its own. When several
 * providers are mounted only the outermost / first one renders the toasts
 * (with its own position, max, labels and portal container); another one
 * takes over when it unmounts.
 *
 * Toasts shown with `useToast()` inside a nested ConfigProvider are grouped
 * per scope: each scope gets its own viewport in its portal host (same
 * position, max and labels), so the scoped theme and language apply.
 */
const ToastProvider = ({
  position = "top-right",
  children,
  max = Infinity,
  pauseOnHover = true,
  "aria-label": ariaLabel,
  closeLabel,
  hotkey = DEFAULT_HOTKEY,
}: ToastProviderProps) => {
  const [order] = useState(toastProviders.nextOrder);
  useEffect(() => toastProviders.register(order), [order]);
  const isOwner =
    useSyncExternalStore(
      toastProviders.subscribe,
      toastProviders.getOwner,
      getServerOwner,
    ) === order;
  // Non-owners do not subscribe to the toasts at all
  const items = useSyncExternalStore(
    isOwner ? toastStore.subscribe : noopSubscribe,
    isOwner ? toastStore.getSnapshot : getServerToasts,
    getServerToasts,
  );
  // SSR / hydration render nothing (the portal needs document.body)
  const isClient = useIsClient();
  const portalContainer = usePortalContainer();
  /** Viewport elements in render order (own one first) */
  const viewportsRef = useRef(new Map<string, HTMLDivElement>());
  const returnFocusRef = useRef<HTMLElement | null>(null);
  const tracker = useMemo<ToastFocusTracker>(
    () => ({
      getReturnFocus: () => returnFocusRef.current,
      setReturnFocus: (el) => {
        returnFocusRef.current = el;
      },
      registerViewport: (key, el) => {
        if (el) viewportsRef.current.set(key, el);
        else viewportsRef.current.delete(key);
      },
    }),
    [],
  );
  const hotkeyLabel = formatHotkey(hotkey);
  const hotkeyKey = hotkey.join("\u0000");

  // The hotkey moves focus to the first region holding toasts
  useEffect(() => {
    if (!isOwner || !hotkeyKey) return;
    const keys = hotkeyKey.split("\u0000");
    const onKeyDown = (event: KeyboardEvent) => {
      if (!matchesHotkey(event, keys)) return;
      // The provider's own viewport first, then the scoped ones
      const viewports = viewportsRef.current;
      const own = viewports.get("own");
      const viewport = [
        ...(own ? [own] : []),
        ...[...viewports.values()].filter((el) => el !== own),
      ].find((el) => el.isConnected && el.querySelector(OPEN_TOAST_CHILD));
      if (!viewport) return;
      event.preventDefault();
      const doc = viewport.ownerDocument;
      const active = doc.activeElement as HTMLElement | null;
      if (active && active !== doc.body && !viewport.contains(active)) {
        tracker.setReturnFocus(active);
      }
      viewport.setAttribute("tabindex", "-1");
      focusElement(viewport);
    };
    document.addEventListener("keydown", onKeyDown);
    return () => document.removeEventListener("keydown", onKeyDown);
  }, [isOwner, hotkeyKey, tracker]);

  // Defensive render-time de-duplication (the latest toast of an id wins) so
  // React keys never collide.
  const seen = new Set<ToastItem["id"]>();
  const unique: ToastItem[] = [];
  for (let i = items.length - 1; i >= 0; i -= 1) {
    if (seen.has(items[i].id)) continue;
    seen.add(items[i].id);
    unique.unshift(items[i]);
  }

  // Over `max`: the oldest open toasts close (and animate out), so their
  // onClose runs as with any other dismissal.
  const open = unique.filter((item) => item.state === "open");
  const overflowCount = Math.max(0, open.length - max);
  const overflowKey = open
    .slice(0, overflowCount)
    .map((item) => String(item.id))
    .join("\u0000");
  useEffect(() => {
    if (!isOwner || !overflowKey) return;
    const current = toastStore
      .getSnapshot()
      .filter((item) => item.state === "open");
    for (const item of current.slice(0, Math.max(0, current.length - max))) {
      toastStore.dismiss(item.id);
    }
  }, [isOwner, overflowKey, max]);

  const renderViewports = () => {
    const ownContainer = portalContainer ?? document.body;
    // One viewport per portal container; the provider's own one always
    // exists (the region stays mounted for screen readers).
    const groups = new Map<
      HTMLElement,
      { scope: ThemeScope | undefined; items: ToastItem[] }
    >([[ownContainer, { scope: undefined, items: [] }]]);
    for (const item of unique) {
      const scoped = item.scope?.portalContainer;
      // A scope that went away (provider unmounted) falls back to ours
      const container = scoped?.isConnected ? scoped : ownContainer;
      let group = groups.get(container);
      if (!group) {
        group = { scope: item.scope, items: [] };
        groups.set(container, group);
      }
      group.items.push(item);
    }
    return [...groups].map(([container, group]) => {
      const key = container === ownContainer ? "own" : containerKey(container);
      return createPortal(
        withScope(
          group.scope,
          <ToastViewport
            items={group.items}
            position={position}
            pauseOnHover={pauseOnHover}
            aria-label={ariaLabel}
            closeLabel={closeLabel}
            hotkeyLabel={hotkeyLabel}
            tracker={tracker}
            viewportKey={key}
          />,
        ),
        container,
        key,
      );
    });
  };

  return (
    <>
      {children}
      {isClient && isOwner && renderViewports()}
    </>
  );
};

export default ToastProvider;
