// packages/vue/src/components/Divider/Divider.vue
<script setup lang="ts">
/**
 * Divider: a horizontal or vertical separator line, optionally with text
 * (default slot, horizontal only). Without text it is a native <hr> (an
 * implicit separator); with text a `role="separator"` div. The line color
 * reads the `--divider-color` CSS custom property.
 */
import { computed, useAttrs, type CSSProperties } from "vue";
import styles from "@react-styles/components/Divider/divider.module.scss";
import { hooks } from "../../internal/hooks";
import { flattenChildren } from "../../internal/children";
import type { DividerProps } from "./types";

defineOptions({ name: "Divider", inheritAttrs: false });

const props = withDefaults(defineProps<DividerProps>(), {
  variant: "solid",
  orientation: "horizontal",
  thickness: 1,
  length: undefined,
  spacing: 16,
  textAlign: "center",
  elevation: false,
  flexItem: false,
});

defineSlots<{
  /** Text rendered inside a horizontal divider (ignored when vertical) */
  default?: () => unknown;
}>();

const attrs = useAttrs();
const px = (value: number | string) =>
  typeof value === "number" ? `${value}px` : value;

// The text is only rendered by horizontal dividers.
const hasTextOf = (children: unknown) =>
  props.orientation === "horizontal" && flattenChildren(children).length > 0;

const dividerStyle = computed<CSSProperties>(() => {
  const horizontal = props.orientation === "horizontal";
  return {
    ...(props.thickness != null && { borderWidth: px(props.thickness) }),
    ...(!horizontal && props.length != null && { height: px(props.length) }),
    ...(horizontal && props.length != null && { width: px(props.length) }),
    ...(props.spacing != null && {
      marginTop: horizontal ? px(props.spacing) : 0,
      marginBottom: horizontal ? px(props.spacing) : 0,
      marginLeft: horizontal ? 0 : px(props.spacing),
      marginRight: horizontal ? 0 : px(props.spacing),
    }),
  };
});

const classes = (hasText: boolean) => [
  styles.divider,
  styles[props.variant],
  styles[props.orientation],
  hasText && styles.withText,
  hasText &&
    styles[
      `text${props.textAlign.charAt(0).toUpperCase()}${props.textAlign.slice(1)}`
    ],
  props.elevation && styles.elevation,
  props.flexItem && styles.flexItem,
];
// Without text, a native <hr> (an implicit separator).
// The generated declarations win over the `style` attribute (like React)
const rootAttrs = (hasText: boolean) => ({
  "aria-orientation": props.orientation,
  ...(hasText && { role: "separator" }),
  ...attrs,
  class: [classes(hasText), attrs.class],
  style: [attrs.style as CSSProperties, dividerStyle.value],
  ...hooks("divider", "root", {
    orientation: props.orientation,
    variant: props.variant,
    align: hasText ? props.textAlign : undefined,
  }),
});
</script>

<template>
  <div v-if="hasTextOf($slots.default?.())" v-bind="rootAttrs(true)">
    <span :class="styles.text" v-bind="hooks('divider', 'label')">
      <slot />
    </span>
  </div>
  <hr v-else v-bind="rootAttrs(false)" />
</template>

// packages/lib-core/src/components/Divider/Divider.tsx
import React from "react";
import { cn } from "../../utils/cn";
import type { DividerProps } from "./types";
import { hooks } from "../../internal/stylingHooks";
import styles from "./divider.module.scss";

/**
 * Divider 分割线组件。线条颜色读取 CSS 自定义属性 `--divider-color`
 * (默认 `var(--border-color)`)，可通过 className / style 覆盖
 * @param variant - 分割线的样式变体
 * @param orientation - 分割线方向
 * @param thickness - 分割线粗细
 * @param length - 分割线长度
 * @param spacing - 分割线两端间距
 * @param children - 分割线中的文字内容
 * @param textAlign - 文字对齐方式
 * @param elevation - 是否带投影
 * @param flexItem - 在 flex 容器中拉伸的竖向分割线
 * @param className - 自定义类名
 * @param style - 自定义样式
 * @param ref - 根元素的 ref
 */
const Divider = ({
  variant = "solid",
  orientation = "horizontal",
  thickness = 1,
  length,
  spacing = 16,
  children,
  textAlign = "center",
  elevation = false,
  flexItem = false,
  className,
  style,
  ref,
  ...rest
}: DividerProps) => {
  // `0` is a valid thickness / spacing / text, so only skip null-ish values.
  // Text is only rendered by horizontal dividers.
  const hasText =
    orientation === "horizontal" &&
    children != null &&
    children !== false &&
    children !== "";
  const dividerStyle: React.CSSProperties = {
    ...style,
    ...(thickness != null && { borderWidth: thickness }),
    ...(orientation === "vertical" && length != null && { height: length }),
    ...(orientation === "horizontal" && length != null && { width: length }),
    ...(spacing != null && {
      marginTop: orientation === "horizontal" ? spacing : 0,
      marginBottom: orientation === "horizontal" ? spacing : 0,
      marginLeft: orientation === "vertical" ? spacing : 0,
      marginRight: orientation === "vertical" ? spacing : 0,
    }),
  };

  const dividerClasses = cn(
    styles.divider,
    styles[variant],
    styles[orientation],
    hasText && styles.withText,
    hasText &&
      styles[`text${textAlign.charAt(0).toUpperCase() + textAlign.slice(1)}`],
    elevation && styles.elevation,
    flexItem && styles.flexItem,
    className,
  );

  const rootHooks = hooks("divider", "root", {
    orientation,
    variant,
    align: hasText ? textAlign : undefined,
  });

  if (hasText) {
    return (
      <div
        ref={ref as React.Ref<HTMLDivElement>}
        role="separator"
        aria-orientation={orientation}
        {...rest}
        className={dividerClasses}
        style={dividerStyle}
        {...rootHooks}
      >
        <span className={styles.text} {...hooks("divider", "label")}>
          {children}
        </span>
      </div>
    );
  }

  // A native <hr> is an implicit separator
  return (
    <hr
      ref={ref as React.Ref<HTMLHRElement>}
      aria-orientation={orientation}
      {...rest}
      className={dividerClasses}
      style={dividerStyle}
      {...rootHooks}
    />
  );
};

export default React.memo(Divider);
