// packages/angular/src/components/checkbox/checkbox.ts
import { NgTemplateOutlet } from "@angular/common";
import {
  ChangeDetectionStrategy,
  Component,
  ElementRef,
  ViewEncapsulation,
  booleanAttribute,
  computed,
  input,
  output,
  viewChild,
} from "@angular/core";
import { cn, createCheckboxMachine, type ColorScheme } from "@minerva/core";
import { classOf } from "../../internal/classes";
import { hasContent, templateOf, type MnContent } from "../../internal/content";
import { emptyContent } from "../../internal/empty-content";
import {
  MnFormValueControl,
  fieldWiring,
  injectFormField,
  provideValueAccessor,
} from "../../internal/forms";
import { MnHook } from "../../internal/hooks";
import { MnIcon } from "../../internal/icon";
import { injectId } from "../../internal/ids";
import { connectMachine } from "../../internal/machine";
import { checkboxStyles as s } from "../../internal/styles";

export type CheckboxSize = "small" | "medium" | "large";
export type CheckboxShape = "square" | "circle" | "rounded";
export type CheckboxColor = Extract<
  ColorScheme,
  "primary" | "success" | "info" | "warning" | "danger"
>;
export type CheckboxLabelPlacement = "start" | "end" | "top" | "bottom";

const optionalBoolean = (value: unknown): boolean | undefined =>
  value === undefined || value === null ? undefined : booleanAttribute(value);

const capitalize = (value: string) =>
  value.charAt(0).toUpperCase() + value.slice(1);

/**
 * Checkbox: a native checkbox with a label, helper text and an indeterminate
 * (mixed) state. Same DOM, classes and styling hooks as React's Checkbox: the
 * host is the wrapper, the native `<input type="checkbox">` sits in a
 * `<label>` with the visual box and the label text (`label` input or the
 * projected content). Space toggles (native checkbox); the native `change`
 * event bubbles to the host.
 *
 * Two-way binding: `[(checked)]`, `ngModel` or a Reactive Forms control
 * (ControlValueAccessor). Inside `<mn-form-control>` it takes the field's id,
 * description, invalid / required / read-only / disabled states.
 *
 * @example
 * <mn-checkbox label="Accept the terms" [(checked)]="accepted" />
 * <mn-checkbox formControlName="newsletter">Send me news</mn-checkbox>
 */
@Component({
  selector: "mn-checkbox",
  exportAs: "mnCheckbox",
  imports: [MnHook, MnIcon, NgTemplateOutlet],
  encapsulation: ViewEncapsulation.None,
  changeDetection: ChangeDetectionStrategy.OnPush,
  providers: [provideValueAccessor(() => MnCheckbox)],
  host: {
    "[class]": "rootClasses()",
    "data-minerva": "checkbox",
    "data-part": "root",
    "[attr.data-state]": "dataState()",
    "[attr.data-disabled]": "isDisabled() ? '' : null",
    "[attr.data-invalid]": "isError() ? '' : null",
    "[attr.data-readonly]": "field.readOnly() ? '' : null",
    "[attr.data-required]": "isRequired() ? '' : null",
    "[attr.data-size]": "size()",
    "[attr.data-color]": "color()",
    "[attr.data-shape]": "shape()",
    "[attr.id]": "null",
    "[attr.aria-label]": "null",
    "[attr.aria-labelledby]": "null",
    "[attr.aria-describedby]": "null",
    "[attr.name]": "null",
    "[attr.value]": "null",
    "[attr.required]": "null",
    "[attr.disabled]": "null",
  },
  template: `
    <label [class]="labelClasses()">
      <input
        #input
        type="checkbox"
        [class]="s.input"
        [attr.id]="field.id()"
        [attr.value]="value() ?? null"
        [attr.name]="name() ?? null"
        [checked]="state().checked"
        [indeterminate]="state().indeterminate"
        [disabled]="isDisabled()"
        [required]="isRequired()"
        [attr.aria-checked]="state().indeterminate ? 'mixed' : null"
        [attr.aria-label]="ariaLabel() ?? null"
        [attr.aria-labelledby]="ariaLabelledby() ?? null"
        [attr.aria-invalid]="isError() ? 'true' : null"
        [attr.aria-readonly]="fieldContext?.readOnly() ? 'true' : null"
        [attr.aria-describedby]="field.describedBy()"
        (click)="onClick($event)"
        (change)="onInputChange(input)"
        (blur)="notifyTouched()"
        mnHook="checkbox"
        mnPart="input"
      />
      <span [class]="s.checkmark" mnHook="checkbox" mnPart="control">
        @if (hasContent(icon()) && state().checked && !state().indeterminate) {
          @if (templateOf(icon()); as tpl) {
            <ng-container [ngTemplateOutlet]="tpl" />
          } @else {
            {{ icon() }}
          }
        }
      </span>
      <span
        #labelText
        [class]="s.label"
        [hidden]="labelEmpty()"
        mnHook="checkbox"
        mnPart="label"
      >
        @if (templateOf(label()); as tpl) {
          <ng-container [ngTemplateOutlet]="tpl" />
        } @else if (hasContent(label())) {
          {{ label() }}
        } @else {
          <ng-content />
        }
      </span>
    </label>
    @if (hasContent(helperText())) {
      <div [class]="s.helperTextWrapper">
        @if (isError()) {
          <span [class]="s.errorIcon" aria-hidden="true">
            @if (templateOf(errorIcon()); as tpl) {
              <ng-container [ngTemplateOutlet]="tpl" />
            } @else if (hasContent(errorIcon())) {
              {{ errorIcon() }}
            } @else {
              <svg mnIcon="CircleInfoFilled"></svg>
            }
          </span>
        }
        <span
          [attr.id]="helperId"
          [class]="helperClasses()"
          mnHook="checkbox"
          mnPart="helper-text"
        >
          @if (templateOf(helperText()); as tpl) {
            <ng-container [ngTemplateOutlet]="tpl" />
          } @else {
            {{ helperText() }}
          }
        </span>
      </div>
    }
  `,
})
export class MnCheckbox extends MnFormValueControl<boolean> {
  /** Checked state (two-way: `[(checked)]`; emits the user's toggles) */
  readonly checked = input<boolean | undefined>(undefined);
  readonly checkedChange = output<boolean>();
  /** Initial checked state when `checked` is not bound @default false */
  readonly defaultChecked = input(false, { transform: booleanAttribute });
  /**
   * Disables the checkbox. Inherited from an enclosing FormControl when not
   * set; an explicit `false` overrides the FormControl
   * @default false
   */
  readonly disabled = input<boolean | undefined, unknown>(undefined, {
    transform: optionalBoolean,
  });
  /**
   * Shows the indeterminate (partially checked) state. It stays applied until
   * this input changes, also after the user toggles the box
   * @default false
   */
  readonly indeterminate = input(false, { transform: booleanAttribute });
  /** Name of the input, used in forms */
  readonly name = input<string | undefined>(undefined);
  /** Box shape @default "square" */
  readonly shape = input<CheckboxShape>("square");
  /** Checkbox size @default "medium" */
  readonly size = input<CheckboxSize>("medium");
  /** Label content (string or template); the projected content otherwise */
  readonly label = input<MnContent>(undefined);
  /**
   * Semantic color of the checked / indeterminate box
   * @default "primary"
   */
  readonly color = input<CheckboxColor>("primary");
  /** id of the input (defaults to the enclosing FormControl's id) */
  readonly id = input<string | undefined>(undefined);
  /** Value submitted with the form when checked */
  readonly value = input<string | undefined>(undefined);
  /** Extra ids of elements describing the checkbox (aria-describedby) */
  readonly ariaDescribedby = input<string | undefined>(undefined, {
    alias: "aria-describedby",
  });
  /** Accessible label, required when there is no visible label */
  readonly ariaLabel = input<string | undefined>(undefined, {
    alias: "aria-label",
  });
  /** id(s) of the element(s) labelling the checkbox */
  readonly ariaLabelledby = input<string | undefined>(undefined, {
    alias: "aria-labelledby",
  });
  /** Custom icon shown when checked (string or template) */
  readonly icon = input<MnContent>(undefined);
  /**
   * Marks the input as required (inherited from an enclosing FormControl
   * when not set)
   * @default false
   */
  readonly required = input<boolean | undefined, unknown>(undefined, {
    transform: optionalBoolean,
  });
  /**
   * Shows the error state (also set by an invalid enclosing FormControl or
   * an invalid bound form control)
   * @default false
   */
  readonly error = input(false, { transform: booleanAttribute });
  /** Icon shown before the helper text in the error state @default a filled info-circle icon */
  readonly errorIcon = input<MnContent>(undefined);
  /** Helper or error text shown below the checkbox (linked with aria-describedby) */
  readonly helperText = input<MnContent>(undefined);
  /** Position of the label relative to the box @default "end" */
  readonly labelPlacement = input<CheckboxLabelPlacement>("end");
  /** Read-only: focusable and submitted, but the user cannot toggle it @default false */
  readonly readOnly = input(false, { transform: booleanAttribute });

  protected readonly s = s;
  protected readonly templateOf = templateOf;
  protected readonly hasContent = hasContent;
  protected readonly helperId = injectId("checkbox-helper");
  protected readonly fieldContext = injectFormField();
  protected readonly field = fieldWiring(this.fieldContext, {
    id: () => this.id(),
    describedBy: () =>
      [
        hasContent(this.helperText()) ? this.helperId : null,
        this.ariaDescribedby(),
      ]
        .filter(Boolean)
        .join(" ") || null,
    readOnly: () => this.readOnly(),
  });
  protected readonly isDisabled = computed(
    () =>
      this.disabled() ??
      (this.formDisabled() || (this.fieldContext?.disabled() ?? false)),
  );
  protected readonly isRequired = computed(
    () => this.required() ?? this.fieldContext?.required() ?? false,
  );
  protected readonly isError = computed(
    () =>
      this.error() ||
      this.controlInvalid() ||
      (this.fieldContext?.invalid() ?? false),
  );

  private readonly machine = connectMachine(
    () =>
      createCheckboxMachine({
        defaultChecked: this.defaultChecked(),
        onCheckedChange: (checked) => {
          this.checkedChange.emit(checked);
          this.notifyChange(checked);
        },
      }),
    () => ({
      checked: this.checked() ?? this.formValue(),
      indeterminate: this.indeterminate(),
      disabled: this.isDisabled(),
      readOnly: this.field.readOnly(),
    }),
  );
  protected readonly state = this.machine.state;

  private readonly inputRef = viewChild<ElementRef<HTMLInputElement>>("input");
  private readonly labelRef = viewChild<ElementRef<HTMLElement>>("labelText");
  protected readonly labelEmpty = emptyContent(
    () => this.labelRef(),
    () => this.label(),
  );

  protected readonly dataState = computed(() =>
    this.state().indeterminate
      ? "indeterminate"
      : this.state().checked
        ? "checked"
        : "unchecked",
  );
  protected readonly rootClasses = computed(() =>
    cn(s.checkboxWrapper, this.isError() && s.error),
  );
  protected readonly labelClasses = computed(() =>
    cn(
      s.checkbox,
      classOf(s, this.size()),
      classOf(s, this.shape()),
      classOf(s, `label${capitalize(this.labelPlacement())}`),
      this.color() !== "primary" &&
        classOf(s, `color${capitalize(this.color())}`),
      this.isDisabled() && s.disabled,
      this.isError() && s.error,
    ),
  );
  protected readonly helperClasses = computed(() =>
    cn(s.helperText, this.isError() && s.errorText),
  );

  protected override fromForm(value: unknown): boolean {
    return !!value;
  }

  protected onClick(event: MouseEvent): void {
    // A read-only checkbox keeps its state
    if (this.field.readOnly()) event.preventDefault();
  }

  protected onInputChange(input: HTMLInputElement): void {
    if (!this.field.readOnly())
      this.machine.send({ type: "SET", checked: input.checked });
    // show the kept state (indeterminate input, blocked change)
    input.checked = this.state().checked;
    input.indeterminate = this.state().indeterminate;
  }

  /** Focuses the native checkbox */
  focus(options?: FocusOptions): void {
    this.inputRef()?.nativeElement.focus(options);
  }
}

// packages/lib-web-components/src/components/checkbox/checkbox.ts
import { css, html, nothing } from "lit";
import { property, query } from "lit/decorators.js";
import { classMap } from "lit/directives/class-map.js";
import { live } from "lit/directives/live.js";
import type { ColorScheme } from "@minerva/core";
import styles from "@lib-core-styles/components/Checkbox/checkbox.module.scss?inline";
import { AriaController } from "../../internal/aria";
import { DEV, devWarn } from "../../internal/dev";
import {
  FormAssociatedElement,
  type ValidityResult,
} from "../../internal/form";
import { IconCircleInfoFilled } from "../../internal/icons";
import { LocaleController } from "../../internal/locale";
import { hostStyles } from "../../internal/minerva-element";
import { HasSlotController } from "../../internal/slots";
import { sharedStyles } from "../../internal/styles";

export type CheckboxShape = "square" | "circle" | "rounded";
export type CheckboxSize = "small" | "medium" | "large";
export type CheckboxLabelPlacement = "start" | "end" | "top" | "bottom";
export type CheckboxColor = Extract<
  ColorScheme,
  "primary" | "success" | "info" | "warning" | "danger"
>;

const capitalize = (s: string) => s.charAt(0).toUpperCase() + s.slice(1);

/**
 * A checkbox with label, helper text and indeterminate state (`<Checkbox>`
 * of lib-core), rendering a native `<input type="checkbox">` in its shadow
 * root (Space toggles it; Enter does nothing, as natively).
 *
 * Form-associated: when checked, submits `value` (default `"on"`) under
 * `name`; `required` makes it invalid until checked (`valueMissing`, with
 * the localized "check this box" message); supports `form.reset()` (restores
 * the `checked` attribute), `<fieldset disabled>` and state restoration.
 * `indeterminate` stays applied until it is changed (as in lib-core), also
 * after the user toggles the box.
 *
 * @summary Checkbox with label, helper text and indeterminate state.
 * @tag minerva-checkbox
 * @slot - Label content (alternative to the `label` attribute)
 * @slot icon - Custom icon shown inside the box when checked
 * @csspart root - The wrapper (the clickable row and the helper text)
 * @csspart input - The native `<input type="checkbox">`
 * @csspart control - The visual box (draws the checkmark)
 * @csspart label - The label text
 * @csspart helper-text - The helper / error text
 * @fires change - The checked state changed (re-dispatched from the inner input)
 * @fires minerva-change - The user toggled the box; `detail: { checked, value }`
 */
export class MinervaCheckbox extends FormAssociatedElement {
  static override tagName = "minerva-checkbox";
  static override shadowRootOptions = {
    ...FormAssociatedElement.shadowRootOptions,
    delegatesFocus: true,
  };
  static override styles = [
    hostStyles,
    css`
      :host {
        display: inline-flex;
        vertical-align: middle;
      }
      .checkmark ::slotted(*) {
        position: relative;
        z-index: 1;
        display: inline-flex;
        color: var(--checkbox-checkmark-color, var(--text-inverse-color));
      }
    `,
    sharedStyles(styles),
  ];

  /** Checked state (property; the `checked` attribute sets `defaultChecked`) */
  @property({ attribute: false })
  checked = false;

  /**
   * Initial checked state, restored by `form.reset()` (the `checked`
   * attribute). Changing it also changes `checked` until the user toggles
   */
  @property({ type: Boolean, attribute: "checked", reflect: true })
  defaultChecked = false;

  /** Shows the indeterminate (partially checked) state (aria-checked="mixed") */
  @property({ type: Boolean, reflect: true })
  indeterminate = false;

  /** Value submitted with the form when checked */
  @property()
  value = "on";

  /** Label text (alternative to the default slot) */
  @property()
  label = "";

  /** Box shape */
  @property({ reflect: true })
  shape: CheckboxShape = "square";

  /** Checkbox size */
  @property({ reflect: true })
  size: CheckboxSize = "medium";

  /** Semantic color of the checked / indeterminate box */
  @property({ reflect: true })
  color: CheckboxColor = "primary";

  /** Position of the label relative to the box */
  @property({ attribute: "label-placement", reflect: true })
  labelPlacement: CheckboxLabelPlacement = "end";

  /** Shows the error state (sets aria-invalid) */
  @property({ type: Boolean, reflect: true })
  error = false;

  /** Helper or error text shown below the checkbox (describes it) */
  @property({ attribute: "helper-text" })
  helperText = "";

  /** Read-only: focusable and submitted, but the user cannot toggle it */
  @property({ type: Boolean, reflect: true, attribute: "readonly" })
  readOnly = false;

  @query("input")
  private input!: HTMLInputElement;

  private readonly locale = new LocaleController(this);
  private readonly aria = new AriaController(this, () => this.labels);
  private readonly slots = new HasSlotController(this);
  private dirty = false;

  override focus(options?: FocusOptions): void {
    this.input?.focus(options);
  }

  override blur(): void {
    this.input?.blur();
  }

  override click(): void {
    this.input?.click();
  }

  protected getFormValue(): string | null {
    return this.checked ? this.value : null;
  }

  protected override getValidity(): ValidityResult {
    if (this.required && !this.checked) {
      return {
        flags: { valueMissing: true },
        message: this.locale.t("validation.checkMissing"),
        anchor: this.input,
      };
    }
    return { flags: {}, message: "" };
  }

  protected resetFormValue(): void {
    this.dirty = false;
    this.checked = this.defaultChecked;
  }

  protected override restoreFormState(state: unknown): void {
    this.checked = state !== null && state !== undefined && state !== "";
  }

  protected override willUpdate(changed: Map<PropertyKey, unknown>): void {
    // first update: a state set before connecting wins over the default
    // unless the checked attribute is present
    if (
      changed.has("defaultChecked") &&
      !this.dirty &&
      (this.hasUpdated || this.hasAttribute("checked"))
    ) {
      this.checked = this.defaultChecked;
    }
  }

  protected override updated(changed: Map<PropertyKey, unknown>): void {
    super.updated(changed);
    // `indeterminate` only exists as a DOM property; a click clears it
    if (this.input) this.input.indeterminate = this.indeterminate;
    if (DEV && !this.aria.label && !this.label && !this.textContent?.trim()) {
      devWarn(
        MinervaCheckbox.tagName,
        "no label: set the label attribute, slot a label, or use aria-label / <label for>.",
      );
    }
  }

  private handleClick(event: MouseEvent) {
    if (this.readOnly) event.preventDefault();
  }

  private handleChange() {
    if (this.readOnly) return;
    this.dirty = true;
    this.input.indeterminate = this.indeterminate;
    this.checked = this.input.checked;
    this.dispatchEvent(new Event("change", { bubbles: true }));
    this.emit("minerva-change", { checked: this.checked, value: this.value });
  }

  protected override hookStates() {
    return {
      state: this.indeterminate
        ? "indeterminate"
        : this.checked
          ? "checked"
          : "unchecked",
      disabled: this.isDisabled,
      invalid: this.error || this.aria.attr("aria-invalid") === "true",
      readonly: this.readOnly,
      required: this.required,
      size: this.size,
      color: this.color,
      shape: this.shape,
    };
  }

  protected override render() {
    const disabled = this.isDisabled;
    const hasLabel = !!this.label || this.slots.test("[default]");
    const description = [this.helperText, this.aria.description]
      .filter(Boolean)
      .join(" ");
    const invalid = this.error || this.aria.attr("aria-invalid") === "true";
    return html`<div
      part="root"
      class=${classMap({ checkboxWrapper: true, error: invalid })}
    >
      <label
        class=${classMap({
          checkbox: true,
          [this.size]: true,
          [this.shape]: true,
          [`label${capitalize(this.labelPlacement)}`]: true,
          [`color${capitalize(this.color)}`]: this.color !== "primary",
          disabled,
          error: invalid,
        })}
      >
        <input
          part="input"
          type="checkbox"
          class="input"
          .checked=${live(this.checked)}
          ?disabled=${disabled}
          ?required=${this.required}
          aria-checked=${this.indeterminate ? "mixed" : nothing}
          aria-label=${this.aria.label ?? nothing}
          aria-description=${description || nothing}
          aria-invalid=${invalid ? "true" : nothing}
          aria-readonly=${this.readOnly ? "true" : nothing}
          @click=${this.handleClick}
          @change=${this.handleChange}
        />
        <span class="checkmark" part="control"
          >${
            this.checked && !this.indeterminate
              ? html`<slot name="icon"></slot>`
              : nothing
          }</span
        >
        ${
          hasLabel
            ? html`<span class="label" part="label"
                >${this.label || html`<slot></slot>`}</span
              >`
            : nothing
        }
      </label>
      ${
        this.helperText
          ? html`<div class="helperTextWrapper">
              ${
                invalid
                  ? html`<span class="errorIcon" aria-hidden="true"
                      >${IconCircleInfoFilled}</span
                    >`
                  : nothing
              }
              <span
                part="helper-text"
                class=${classMap({ helperText: true, errorText: invalid })}
                >${this.helperText}</span
              >
            </div>`
          : nothing
      }
    </div>`;
  }
}

declare global {
  interface HTMLElementTagNameMap {
    "minerva-checkbox": MinervaCheckbox;
  }
}
