// packages/lib-core/src/components/Popover/Popover.tsx
import * as RadixPopover from "@radix-ui/react-popover";
import { cn } from "../../utils/cn";
import type {
  PopoverAnchorProps,
  PopoverContentProps,
  PopoverProps,
  PopoverTriggerProps,
} from "./types";
import styles from "./popover.module.scss";

/**
 * Popover: a click-triggered, interactive floating panel (Radix Popover).
 * Unlike Tooltip it holds focusable content; unlike Popper it manages its own
 * trigger, focus, Escape and outside-click dismissal.
 */
export const Popover = (props: PopoverProps) => (
  <RadixPopover.Root {...props} />
);

/** Toggles the popover; a `<button>` or, with `asChild`, the child element. */
export const PopoverTrigger = (props: PopoverTriggerProps) => (
  <RadixPopover.Trigger {...props} />
);

/** Positions the popover against this element instead of the trigger. */
export const PopoverAnchor = (props: PopoverAnchorProps) => (
  <RadixPopover.Anchor {...props} />
);

/** Closes the popover; a `<button>` or, with `asChild`, the child element. */
export const PopoverClose = (props: PopoverTriggerProps) => (
  <RadixPopover.Close {...props} />
);

/** PopoverContent: the anchored panel; flips / shifts to stay in view. */
export const PopoverContent = ({
  className,
  children,
  arrow = false,
  portal = true,
  sideOffset = 6,
  collisionPadding = 8,
  ...rest
}: PopoverContentProps) => {
  const content = (
    <RadixPopover.Content
      sideOffset={sideOffset}
      collisionPadding={collisionPadding}
      className={cn(styles.content, className)}
      {...rest}
    >
      {children}
      {arrow && <RadixPopover.Arrow className={styles.arrow} />}
    </RadixPopover.Content>
  );
  return portal ? (
    <RadixPopover.Portal>{content}</RadixPopover.Portal>
  ) : (
    content
  );
};

export default Popover;

// packages/vue/src/components/Popover/Popover.vue
<script setup lang="ts">
/**
 * Popover: a click-triggered, interactive floating panel anchored to its
 * trigger (or a `PopoverAnchor`). The primary component for anchored panels:
 * unlike Tooltip it holds focusable content and manages focus, Escape and
 * outside-click dismissal itself. Owns the open state (`v-model:open`).
 */
import { computed, provide, shallowRef, useId } from "vue";
import { useControllable } from "../../internal/controllable";
import { POPOVER_KEY } from "./context";
import type { PopoverProps } from "./types";

defineOptions({ name: "Popover" });

const props = withDefaults(defineProps<PopoverProps>(), {
  open: undefined,
  defaultOpen: undefined,
  modal: false,
});
const emit = defineEmits<{
  "update:open": [open: boolean];
  /** Requested open state (trigger, Escape, outside click, `PopoverClose`) */
  openChange: [open: boolean];
}>();
defineSlots<{
  /** `PopoverTrigger` / `PopoverAnchor` and `PopoverContent` */
  default?: () => unknown;
}>();

const open = useControllable<boolean>(props, "open", {
  fallback: false,
  name: "Popover",
  onChange: (value) => emit("openChange", value),
});

provide(POPOVER_KEY, {
  open: computed(() => open.value),
  setOpen: (value: boolean) => {
    open.value = value;
  },
  modal: computed(() => props.modal),
  contentId: useId(),
  trigger: shallowRef<HTMLElement | null>(null),
  anchor: shallowRef<HTMLElement | null>(null),
});
</script>

<template>
  <slot />
</template>
