// packages/lib-web-components/src/components/button/button.ts
import { css, html, nothing } from "lit";
import { property, query } from "lit/decorators.js";
import { classMap } from "lit/directives/class-map.js";
import { styleMap } from "lit/directives/style-map.js";
import type { ColorScheme } from "@minerva/core";
import styles from "@lib-core-styles/components/Button/button.module.scss?inline";
import { AriaController } from "../../internal/aria";
import { DEV, devWarn } from "../../internal/dev";
import { attachInternals } from "../../internal/form";
import { MinervaElement, hostStyles } from "../../internal/minerva-element";
import { HasSlotController } from "../../internal/slots";
import { sharedStyles } from "../../internal/styles";

export type ButtonVariant = "solid" | "outline" | "ghost" | "link";
export type ButtonSize = "xsmall" | "small" | "medium" | "large" | "xlarge";
export type ButtonShape = "square" | "rounded" | "circle";
export type ButtonBorderRadius =
  "none" | "small" | "medium" | "large" | "circle" | "square";

const radiusClass = (value: string) =>
  `borderRadius${value.charAt(0).toUpperCase()}${value.slice(1)}`;

/**
 * A button with a semantic `color`, a visual `variant`, sizes, shapes, icons
 * and a loading state (`<Button>` of lib-core). Renders a native `<button>`
 * in its shadow root; `type="submit"` / `"reset"` act on the owning form
 * (the element is form-associated).
 *
 * @summary Button with colors, variants, sizes, icons and a loading state.
 * @tag minerva-button
 * @slot - Label
 * @slot start - Icon before the label
 * @slot end - Icon after the label
 * @slot loading - Text shown instead of the label while `loading`
 * @csspart root - The native `<button>`
 * @csspart label - The label wrapper
 * @csspart start-icon - The icon before the label
 * @csspart end-icon - The icon after the label
 * @csspart spinner - The loading spinner (while loading)
 */
export class MinervaButton extends MinervaElement {
  static override tagName = "minerva-button";
  static formAssociated = true;
  static override styles = [
    hostStyles,
    css`
      :host {
        display: inline-flex;
        max-width: 100%;
        vertical-align: middle;
      }
      :host([full-width]) {
        display: flex;
        width: 100%;
      }
    `,
    sharedStyles(styles),
  ];

  /** Semantic color */
  @property({ reflect: true })
  color: ColorScheme = "primary";

  /** Visual style: solid (filled), outline, ghost or link */
  @property({ reflect: true })
  variant: ButtonVariant = "solid";

  /** Button size */
  @property({ reflect: true })
  size: ButtonSize = "medium";

  /** Preset shape */
  @property({ reflect: true })
  shape?: ButtonShape;

  /** Corner radius preset, or a number of pixels */
  @property({ attribute: "border-radius" })
  borderRadius?: ButtonBorderRadius | number;

  /** Disables the button */
  @property({ type: Boolean, reflect: true })
  disabled = false;

  /**
   * Shows a spinner and blocks activation (aria-busy / aria-disabled); the
   * button stays focusable
   */
  @property({ type: Boolean, reflect: true })
  loading = false;

  /** Stretches the button to the full width of its container */
  @property({ type: Boolean, reflect: true, attribute: "full-width" })
  fullWidth = false;

  /** Renders the button in its pressed / active state */
  @property({ type: Boolean, reflect: true })
  active = false;

  /**
   * What the button does in its form: nothing ("button"), submit it
   * (through `requestSubmit()`, so validation runs) or reset it
   */
  @property({ reflect: true })
  type: "button" | "submit" | "reset" = "button";

  @query("button")
  private button!: HTMLButtonElement;

  private readonly internals = attachInternals(this);

  private readonly aria = new AriaController(this);
  private readonly slots = new HasSlotController(this);

  /** The form owning the button */
  get form(): HTMLFormElement | null {
    return this.internals?.form ?? null;
  }

  override focus(options?: FocusOptions): void {
    this.button?.focus(options);
  }

  override blur(): void {
    this.button?.blur();
  }

  override click(): void {
    this.button?.click();
  }

  private handleClick(event: MouseEvent) {
    if (this.loading || this.disabled) {
      event.preventDefault();
      event.stopImmediatePropagation();
      return;
    }
    const form = this.form;
    if (!form) return;
    if (this.type === "submit") form.requestSubmit();
    else if (this.type === "reset") form.reset();
  }

  /** Clicks on the host while disabled / loading never reach listeners. */
  private readonly blockInactiveClicks = (event: MouseEvent) => {
    if (this.disabled || this.loading) {
      event.preventDefault();
      event.stopImmediatePropagation();
    }
  };

  override connectedCallback(): void {
    super.connectedCallback();
    this.addEventListener("click", this.blockInactiveClicks, true);
  }

  override disconnectedCallback(): void {
    super.disconnectedCallback();
    this.removeEventListener("click", this.blockInactiveClicks, true);
  }

  protected override hookStates() {
    return {
      state: this.active ? "active" : "inactive",
      disabled: this.disabled,
      loading: this.loading,
      size: this.size,
      variant: this.variant,
      color: this.color,
      shape: this.shape,
    };
  }

  protected override updated(): void {
    if (DEV && this.shape === "circle" && !this.aria.label) {
      const text = this.textContent?.trim();
      if (!text) {
        devWarn(
          MinervaButton.tagName,
          'shape="circle" buttons usually only contain an icon: set aria-label to give them an accessible name.',
        );
      }
    }
  }

  protected override render() {
    const radius = this.borderRadius;
    const numericRadius =
      typeof radius === "number" ||
      (typeof radius === "string" && /^\d+(\.\d+)?$/.test(radius));
    const hasLoadingText = this.loading && this.slots.test("loading");
    const hidden = this.loading && !hasLoadingText;
    const spinner = html`<span
      class="loadingSpinner"
      part="spinner"
      aria-hidden="true"
    ></span>`;

    return html`<button
      part="root"
      type="button"
      class=${classMap({
        customButton: true,
        [this.color]: true,
        [`variant-${this.variant}`]: true,
        [this.size]: true,
        [this.shape ?? ""]: !!this.shape,
        [radiusClass(String(radius ?? ""))]: !!radius && !numericRadius,
        fullWidth: this.fullWidth,
        active: this.active,
        loading: this.loading,
      })}
      style=${styleMap(
        numericRadius ? { borderRadius: `${Number(radius)}px` } : {},
      )}
      ?disabled=${this.disabled}
      aria-label=${this.aria.label ?? nothing}
      aria-description=${this.aria.description ?? nothing}
      aria-pressed=${this.aria.attr("aria-pressed") ?? nothing}
      aria-expanded=${this.aria.attr("aria-expanded") ?? nothing}
      aria-haspopup=${this.aria.attr("aria-haspopup") ?? nothing}
      aria-busy=${this.loading ? "true" : nothing}
      aria-disabled=${this.loading ? "true" : nothing}
      @click=${this.handleClick}
    >
      ${
        hasLoadingText
          ? html`${spinner}<span class="label" part="label"
                ><slot name="loading"></slot
              ></span>`
          : html`${this.loading ? spinner : nothing}
              ${
                this.slots.test("start")
                  ? html`<span
                      class=${classMap({ icon: true, hidden })}
                      part="start-icon"
                      ><slot name="start"></slot
                    ></span>`
                  : nothing
              }
              <span class=${classMap({ label: true, hidden })} part="label"
                ><slot></slot
              ></span>
              ${
                this.slots.test("end")
                  ? html`<span
                      class=${classMap({ icon: true, hidden })}
                      part="end-icon"
                      ><slot name="end"></slot
                    ></span>`
                  : nothing
              }`
      }
    </button>`;
  }
}

declare global {
  interface HTMLElementTagNameMap {
    "minerva-button": MinervaButton;
  }
}

// packages/angular/src/components/button/button.ts
import { NgTemplateOutlet } from "@angular/common";
import {
  ChangeDetectionStrategy,
  Component,
  ElementRef,
  ViewEncapsulation,
  booleanAttribute,
  computed,
  inject,
  input,
} from "@angular/core";
import { cn, type ColorScheme } from "@minerva/core";
import { templateOf, type MnContent } from "../../internal/content";
import { MnHook } from "../../internal/hooks";
import { buttonStyles as s } from "../../internal/styles";

export type ButtonVariant = "solid" | "outline" | "ghost" | "link";
export type ButtonSize = "xsmall" | "small" | "medium" | "large" | "xlarge";
export type ButtonShape = "square" | "rounded" | "circle";
export type ButtonRadius =
  "none" | "small" | "medium" | "large" | "circle" | "square" | number;

const RADIUS_CLASS = {
  none: s.borderRadiusNone,
  small: s.borderRadiusSmall,
  medium: s.borderRadiusMedium,
  large: s.borderRadiusLarge,
  circle: s.borderRadiusCircle,
  square: s.borderRadiusSquare,
} as const;

/**
 * Button: a native `<button>` (or `<a>`) with a semantic `color`, a visual
 * `variant` (solid, outline, ghost, link), sizes, shapes, icons and a loading
 * state. An attribute component, so the host IS the native element: every
 * native attribute, event, `form` / `type="submit"` and focus behaviour
 * applies as usual. `type` defaults to "button" (never submits a form by
 * accident).
 *
 * While `loading` the button stays focusable (aria-busy / aria-disabled) but
 * activation is blocked: `(click)` listeners do not run and a submit button
 * does not submit.
 *
 * @example
 * <button mnButton color="danger" (click)="remove()">Delete</button>
 * <a mnButton variant="link" href="/docs">Docs</a>
 */
@Component({
  selector: "button[mnButton], a[mnButton]",
  exportAs: "mnButton",
  imports: [MnHook, NgTemplateOutlet],
  encapsulation: ViewEncapsulation.None,
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: {
    "[class]": "classes()",
    "[style.border-radius]": "radiusStyle()",
    "[attr.type]": "isAnchor ? null : type()",
    "[attr.disabled]": "!isAnchor && disabled() ? '' : null",
    "[attr.aria-disabled]":
      "loading() || (isAnchor && disabled()) ? 'true' : null",
    "[attr.aria-busy]": "loading() ? 'true' : null",
    "[attr.tabindex]": "isAnchor && disabled() ? '-1' : null",
    "data-minerva": "button",
    "data-part": "root",
    "[attr.data-state]": "active() ? 'active' : 'inactive'",
    "[attr.data-disabled]": "disabled() ? '' : null",
    "[attr.data-loading]": "loading() ? '' : null",
    "[attr.data-size]": "size()",
    "[attr.data-variant]": "variant()",
    "[attr.data-color]": "color()",
    "[attr.data-shape]": "shape() ?? null",
  },
  template: `
    @if (loading() && loadingText() != null) {
      <span
        [class]="s.loadingSpinner"
        aria-hidden="true"
        mnHook="button"
        mnPart="spinner"
      ></span>
      <span [class]="s.label" mnHook="button" mnPart="label">{{
        loadingText()
      }}</span>
    } @else {
      @if (loading()) {
        <span
          [class]="s.loadingSpinner"
          aria-hidden="true"
          mnHook="button"
          mnPart="spinner"
        ></span>
      }
      @if (startIcon(); as icon) {
        <span [class]="iconClass()" mnHook="button" mnPart="start-icon">
          @if (templateOf(icon); as tpl) {
            <ng-container [ngTemplateOutlet]="tpl" />
          } @else {
            {{ icon }}
          }
        </span>
      }
      <span [class]="labelClass()" mnHook="button" mnPart="label"
        ><ng-content
      /></span>
      @if (endIcon(); as icon) {
        <span [class]="iconClass()" mnHook="button" mnPart="end-icon">
          @if (templateOf(icon); as tpl) {
            <ng-container [ngTemplateOutlet]="tpl" />
          } @else {
            {{ icon }}
          }
        </span>
      }
    }
  `,
})
export class MnButton {
  /**
   * Native button type ("button" unlike the HTML default "submit")
   * @default "button"
   */
  readonly type = input<"button" | "submit" | "reset">("button");
  /** Semantic color @default "primary" */
  readonly color = input<ColorScheme>("primary");
  /** Visual style @default "solid" */
  readonly variant = input<ButtonVariant>("solid");
  /** Button size @default "medium" */
  readonly size = input<ButtonSize>("medium");
  /** Disables the button @default false */
  readonly disabled = input(false, { transform: booleanAttribute });
  /** Shows a spinner and blocks activation (stays focusable) @default false */
  readonly loading = input(false, { transform: booleanAttribute });
  /** Text shown instead of the content while loading */
  readonly loadingText = input<string | undefined>(undefined);
  /** Icon before the content (string or template) */
  readonly startIcon = input<MnContent>(undefined);
  /** Icon after the content (string or template) */
  readonly endIcon = input<MnContent>(undefined);
  /** Stretches the button to the full width of its container @default false */
  readonly fullWidth = input(false, { transform: booleanAttribute });
  /** Pressed / active state @default false */
  readonly active = input(false, { transform: booleanAttribute });
  /** Preset shape */
  readonly shape = input<ButtonShape | undefined>(undefined);
  /** Corner radius: a preset or a number of pixels */
  readonly borderRadius = input<ButtonRadius | undefined>(undefined);

  protected readonly s = s;
  protected readonly templateOf = templateOf;
  private readonly host =
    inject<ElementRef<HTMLElement>>(ElementRef).nativeElement;
  protected readonly isAnchor = this.host.localName === "a";

  protected readonly classes = computed(() => {
    const radius = this.borderRadius();
    return cn(
      s.customButton,
      s[this.color() as keyof typeof s],
      s[`variant-${this.variant()}` as keyof typeof s],
      s[this.size() as keyof typeof s],
      typeof radius === "string" && RADIUS_CLASS[radius],
      this.shape() && s[this.shape()!],
      this.fullWidth() && s.fullWidth,
      this.active() && s.active,
      this.loading() && s.loading,
    );
  });
  protected readonly radiusStyle = computed(() => {
    const radius = this.borderRadius();
    return typeof radius === "number" ? `${radius}px` : null;
  });
  protected readonly iconClass = computed(() =>
    cn(s.icon, this.loading() && s.hidden),
  );
  protected readonly labelClass = computed(() =>
    cn(s.label, this.loading() && s.hidden),
  );

  constructor() {
    // Registered before any (click) listener of the template using the
    // button (and in the capture phase), so it can stop them.
    this.host.addEventListener?.(
      "click",
      (event: Event) => {
        if (this.loading() || (this.isAnchor && this.disabled())) {
          // busy (or disabled link): no activation, no submit, no (click)
          event.preventDefault();
          event.stopImmediatePropagation();
        }
      },
      { capture: true },
    );
  }
}
