// packages/vue/src/components/VirtualList/VirtualList.vue
<script setup lang="ts" generic="T extends VirtualListItem">
/**
 * VirtualList: a scrolling list that only renders the rows in (and around)
 * the visible area, with an optional measured row height, infinite loading
 * (`@load-more`) and clickable rows (`@item-click`). The scroll container is
 * a focusable, labelled region; rows expose their real position
 * (`aria-setsize` / `aria-posinset`) and the focused row stays mounted when
 * it is scrolled out of the window. Attributes fall through to the root.
 */
import {
  computed,
  getCurrentInstance,
  onBeforeUnmount,
  onMounted,
  ref,
  shallowRef,
  useAttrs,
  type CSSProperties,
  type StyleValue,
  type VNodeChild,
} from "vue";
import { getVirtualRange } from "@minerva/core";
import styles from "@react-styles/components/VirtualList/virtualList.module.scss";
import progressStyles from "@react-styles/components/ProgressIndicator/progressIndicator.module.scss";
import { hooks } from "../../internal/hooks";
import { IconWaveSquare } from "../../internal/icons";
import { useI18n } from "../../config/useI18n";
import type { VirtualItem, VirtualListItem, VirtualListProps } from "./types";

defineOptions({ name: "VirtualList", inheritAttrs: false });

const props = withDefaults(defineProps<VirtualListProps<T>>(), {
  itemHeight: undefined,
  itemPadding: 8,
  overscan: 5,
  renderItem: undefined,
  onLoadMore: undefined,
  loadMoreThreshold: 100,
  highPerformance: false,
  loading: false,
  "aria-label": undefined,
});

const emit = defineEmits<{
  /**
   * A row was clicked, or activated with Enter / Space while the row itself
   * has focus. Listening makes the rows clickable: focusable and shown with
   * a pointer cursor
   */
  itemClick: [item: T, index: number, event: MouseEvent | KeyboardEvent];
}>();

const slots = defineSlots<{
  /** Content of one row (wins over `renderItem`) */
  default?: (props: { item: T; index: number }) => unknown;
}>();

const attrs = useAttrs();
// `aria-label` is a declared prop: Vue stores it camelized
const ariaLabel = computed(
  () => (props as unknown as { ariaLabel?: string }).ariaLabel,
);
const instance = getCurrentInstance();
const { t } = useI18n();

// The loading row renders the DOM of the React <ProgressIndicator
// variant="wave" size="small" /> (same classes and hooks).

/** Renders the result of a render function (`renderItem`) */
const RenderContent = (p: { render: () => VNodeChild }) => p.render();
RenderContent.props = ["render"];

// Clickable rows (an @item-click listener) stay list items for the list
// semantics, made focusable and activatable with Enter / Space so the click
// handler is not pointer-only.
// (read while rendering: listeners are not reactive)
const isClickable = () => {
  const vnodeProps = instance?.vnode.props ?? {};
  return !!(vnodeProps.onItemClick || vnodeProps.onItemClickOnce);
};

const scrollTop = ref(0);
const containerHeight = ref(0);
let lastScrollTop = 0;
let isLoadingMore = false;
let rafId: number | undefined;
let idleId: number | undefined;
// Id of the item containing focus: it stays mounted when it is scrolled out
// of the window, otherwise unmounting it would drop focus to <body>
// (WCAG 2.4.3). Tracked by id so it follows the item when the data changes.
const focusedId = ref<VirtualListItem["id"] | null>(null);
const focusedIndex = computed(() =>
  focusedId.value === null
    ? null
    : props.items.findIndex((item) => item.id === focusedId.value),
);

// Measured content height (without padding); the padding is added when
// rendering so that itemPadding changes apply without measuring again.
// 0 = not measured yet.
const measuredContentHeight = ref(0);
const needsMeasure = computed(
  () =>
    !props.itemHeight &&
    measuredContentHeight.value === 0 &&
    props.items.length > 0,
);

// Container height: read on mount and observed while mounted
const root = shallowRef<HTMLDivElement | null>(null);
let containerObserver: ResizeObserver | undefined;
onMounted(() => {
  const node = root.value!;
  containerHeight.value = node.clientHeight;
  if (typeof ResizeObserver === "undefined") return;
  containerObserver = new ResizeObserver((entries) => {
    for (const entry of entries)
      containerHeight.value = entry.contentRect.height;
  });
  containerObserver.observe(node);
});

// Height of the first item. The measuring element is only mounted while
// needed (also when items arrive later) and removed once measured, which
// disconnects its observer.
let measureNode: HTMLElement | null = null;
let measureObserver: ResizeObserver | undefined;
const measureItem = (el: unknown) => {
  const node = (el as HTMLElement | null) ?? null;
  if (node === measureNode) return;
  measureObserver?.disconnect();
  measureObserver = undefined;
  measureNode = node;
  if (!node) return;
  const measure = () => {
    const height = node.offsetHeight;
    if (height > 0) measuredContentHeight.value = height;
  };
  measure();
  if (typeof ResizeObserver === "undefined") return;
  measureObserver = new ResizeObserver(measure);
  measureObserver.observe(node);
};

// Fixed or measured row height
const finalItemHeight = computed(
  () =>
    props.itemHeight ||
    (measuredContentHeight.value > 0
      ? measuredContentHeight.value + props.itemPadding * 2
      : 0),
);

const visibleRange = computed(() => {
  // Before the first row is measured, render one row to measure it.
  if (!finalItemHeight.value) return { start: 0, end: 1, visibleCount: 1 };
  return getVirtualRange({
    scrollTop: scrollTop.value,
    viewportHeight: containerHeight.value,
    itemHeight: finalItemHeight.value,
    itemCount: props.items.length,
    overscan: props.overscan,
  });
});

const virtualItems = computed(() => {
  const height = finalItemHeight.value;
  const { start, end } = visibleRange.value;
  const result: VirtualItem[] = [];
  for (let i = start; i < end; i++) {
    result.push({ index: i, start: i * height, height });
  }
  // Keep the focused item rendered (at its real position) outside the window
  const focused = focusedIndex.value;
  if (focused !== null && focused >= 0 && (focused < start || focused >= end)) {
    const item = { index: focused, start: focused * height, height };
    if (focused < start) result.unshift(item);
    else result.push(item);
  }
  return result;
});

// Cancels the pending RAF / idle callbacks
function cancelScheduled() {
  if (rafId !== undefined) {
    cancelAnimationFrame(rafId);
    rafId = undefined;
  }
  if (idleId !== undefined) {
    if ("cancelIdleCallback" in window) cancelIdleCallback(idleId);
    idleId = undefined;
  }
}

function scheduleUpdate(callback: () => void) {
  if (!props.highPerformance) {
    callback();
    return;
  }
  // Only the latest scroll position matters: drop pending work
  cancelScheduled();
  rafId = requestAnimationFrame(() => {
    rafId = undefined;
    if ("requestIdleCallback" in window) {
      idleId = requestIdleCallback(
        () => {
          idleId = undefined;
          callback();
        },
        { timeout: 100 },
      );
    } else {
      callback();
    }
  });
}

function onScroll(event: Event) {
  const {
    scrollTop: top,
    scrollHeight,
    clientHeight,
  } = event.currentTarget as HTMLDivElement;
  const isScrollingDown = top > lastScrollTop;
  lastScrollTop = top;
  scheduleUpdate(() => {
    scrollTop.value = top;
    const onLoadMore = props.onLoadMore;
    if (
      isScrollingDown &&
      onLoadMore &&
      !isLoadingMore &&
      !props.loading &&
      scrollHeight - top - clientHeight < props.loadMoreThreshold &&
      // no load-more for content that does not scroll
      scrollHeight > clientHeight
    ) {
      isLoadingMore = true;
      // Tolerate callbacks that do not return a promise
      Promise.resolve(onLoadMore()).finally(() => {
        isLoadingMore = false;
      });
    }
  });
}

onBeforeUnmount(() => {
  cancelScheduled();
  containerObserver?.disconnect();
  measureItem(null);
});

function onItemKeydown(event: KeyboardEvent, index: number) {
  // Only the row itself: keys of its content are theirs
  if (event.target !== event.currentTarget) return;
  if (event.key !== "Enter" && event.key !== " ") return;
  event.preventDefault();
  emit("itemClick", props.items[index], index, event);
}

function onItemFocusout(event: FocusEvent) {
  const row = event.currentTarget as HTMLElement;
  if (!row.contains(event.relatedTarget as Node | null)) focusedId.value = null;
}

const rootAttrs = computed(() => {
  const { class: className, style, ...rest } = attrs;
  return {
    ...rest,
    // Scrollable region: focusable so keyboard users can scroll it
    role: "region",
    "aria-label": ariaLabel.value,
    tabindex: 0,
    "aria-busy": props.loading || undefined,
    class: [styles.virtualList, className],
    style: [
      style as StyleValue,
      {
        maxHeight: `${props.maxHeight}px`,
        overflow: "auto",
        position: "relative",
      } satisfies CSSProperties,
    ],
    ...hooks("virtual-list", "root", { loading: props.loading }),
  };
});

const contentStyle = computed<CSSProperties>(() => ({
  height: finalItemHeight.value
    ? `${props.items.length * finalItemHeight.value}px`
    : "auto",
  position: "relative",
  willChange: "transform",
}));

const itemStyle = (start: number): CSSProperties => ({
  position: "absolute",
  top: 0,
  transform: `translateY(${start}px)`,
  width: "100%",
  height: `${finalItemHeight.value}px`,
  willChange: "transform",
  padding: `${props.itemPadding}px`,
});
</script>

<template>
  <div ref="root" v-bind="rootAttrs" @scroll="onScroll">
    <div
      v-if="needsMeasure"
      :ref="measureItem"
      :class="styles.measureItem"
      aria-hidden="true"
    >
      <slot v-if="slots.default" :item="items[0]" :index="0" />
      <RenderContent
        v-else-if="renderItem"
        :render="() => renderItem!(items[0], 0)"
      />
    </div>
    <div
      :style="contentStyle"
      :class="styles.virtualListContent"
      role="list"
      :aria-label="ariaLabel"
      v-bind="hooks('virtual-list', 'list')"
    >
      <template v-if="finalItemHeight > 0">
        <div
          v-for="virtualItem in virtualItems"
          :key="items[virtualItem.index].id"
          :style="itemStyle(virtualItem.start)"
          :class="[styles.virtualListItem, isClickable() && styles.clickable]"
          :tabindex="isClickable() ? 0 : undefined"
          role="listitem"
          v-bind="hooks('virtual-list', 'item')"
          :aria-setsize="items.length"
          :aria-posinset="virtualItem.index + 1"
          @click="
            isClickable() &&
            emit(
              'itemClick',
              items[virtualItem.index],
              virtualItem.index,
              $event,
            )
          "
          @keydown="isClickable() && onItemKeydown($event, virtualItem.index)"
          @focusin="focusedId = items[virtualItem.index].id"
          @focusout="onItemFocusout"
        >
          <slot
            v-if="slots.default"
            :item="items[virtualItem.index]"
            :index="virtualItem.index"
          />
          <RenderContent
            v-else-if="renderItem"
            :render="
              () => renderItem!(items[virtualItem.index], virtualItem.index)
            "
          />
        </div>
      </template>
    </div>
    <div
      v-if="loading"
      :class="styles.loadingWrapper"
      v-bind="hooks('virtual-list', 'loading')"
    >
      <div
        :class="[progressStyles.progressIndicator, progressStyles.primary]"
        role="progressbar"
        :aria-label="t('common.loading')"
        v-bind="
          hooks('progress', 'root', {
            variant: 'wave',
            size: 'small',
            color: 'primary',
          })
        "
      >
        <div
          :class="[progressStyles.waveContainer, progressStyles.small]"
          v-bind="hooks('progress', 'indicator')"
        >
          <IconWaveSquare :class="progressStyles.wave" aria-hidden="true" />
        </div>
      </div>
    </div>
  </div>
</template>

// packages/web-components/src/components/virtual-list/virtual-list.ts
import {
  css,
  html,
  nothing,
  type PropertyValues,
  type TemplateResult,
} from "lit";
import { property, query, state } from "lit/decorators.js";
import { classMap } from "lit/directives/class-map.js";
import { repeat } from "lit/directives/repeat.js";
import { styleMap } from "lit/directives/style-map.js";
import styles from "@react-styles/components/VirtualList/virtualList.module.scss?inline";
import progressStyles from "@react-styles/components/ProgressIndicator/progressIndicator.module.scss?inline";
import { getVirtualRange } from "@minerva/core";
import { AriaController } from "../../internal/aria";
import { DEV, devWarn } from "../../internal/dev";
import { IconWaveSquare } from "../../internal/icons";
import { LocaleController } from "../../internal/locale";
import { MinervaElement, hostStyles } from "../../internal/minerva-element";
import { sharedStyles } from "../../internal/styles";

/** An item of a virtual list */
export interface VirtualListItem {
  /** Unique key of the item */
  id: string | number;
  /** Arbitrary data for renderItem */
  metadata?: Record<string, string | number | boolean>;
}

/** Renders the content of one row */
export type VirtualListRenderItem = (
  item: VirtualListItem,
  index: number,
) => string | Node | TemplateResult | null | undefined;

interface WindowItem {
  index: number;
  start: number;
}

/**
 * A windowed (virtualized) list: only the rows in view (plus `overscan`
 * rows above and below) are in the DOM (`<VirtualList>` of React). Rows
 * have a fixed height (`item-height`, or measured from the first item).
 *
 * - Data: set the `items` property (`{ id, metadata? }[]`) and a
 *   `renderItem(item, index)` function property returning text, a Node or a
 *   Lit template. Rows are rendered in the shadow root: style their content
 *   with inline styles / your own elements, or through `::part(item)`.
 * - The scroll container is a focusable `region` (keyboard scrolling) named
 *   by `aria-label`; rows are `listitem`s exposing their real position
 *   (`aria-setsize` / `aria-posinset`). The row holding focus stays rendered
 *   when scrolled out of the window (focus is never dropped).
 * - `clickable` (React: passing `onItemClick`) makes rows focusable and
 *   activatable with Enter / Space: `minerva-item-click`.
 * - Scrolling near the bottom fires `minerva-load-more` (once until `items`
 *   or `loading` change).
 *
 * @summary Windowed list rendering only the visible rows.
 * @tag minerva-virtual-list
 * @csspart root - The scroll container (`role="region"`)
 * @csspart list - The list (`role="list"`) sized to all the rows
 * @csspart item - A rendered row (`role="listitem"`)
 * @csspart loading - The loading indicator row (while loading)
 * @fires minerva-item-click - A clickable row was clicked or activated with Enter / Space (`detail: { item, index }`)
 * @fires minerva-load-more - The list was scrolled within `load-more-threshold` px of the bottom
 */
export class MinervaVirtualList extends MinervaElement {
  static override tagName = "minerva-virtual-list";
  static override styles = [
    hostStyles,
    css`
      :host {
        display: block;
      }
      .wave {
        display: inline-flex;
      }
    `,
    sharedStyles(progressStyles),
    sharedStyles(styles),
  ];

  /** Items to render */
  @property({ attribute: false })
  items: VirtualListItem[] = [];

  /** Renders the content of one row (text, Node or Lit template) */
  @property({ attribute: false })
  renderItem?: VirtualListRenderItem;

  /** Fixed row height in pixels; measured from the first item when omitted */
  @property({ type: Number, attribute: "item-height" })
  itemHeight?: number;

  /** Padding of each row in pixels */
  @property({ type: Number, attribute: "item-padding" })
  itemPadding = 8;

  /** Number of rows rendered above and below the visible area */
  @property({ type: Number })
  overscan = 5;

  /** Maximum height of the scroll container in pixels */
  @property({ type: Number, attribute: "max-height" })
  maxHeight?: number;

  /** Distance from the bottom (px) at which `minerva-load-more` fires */
  @property({ type: Number, attribute: "load-more-threshold" })
  loadMoreThreshold = 100;

  /** Batches scroll updates with requestAnimationFrame and requestIdleCallback */
  @property({ type: Boolean, attribute: "high-performance" })
  highPerformance = false;

  /** Shows a loading indicator at the bottom of the list (aria-busy) */
  @property({ type: Boolean, reflect: true })
  loading = false;

  /** Rows are clickable: focusable, pointer cursor, `minerva-item-click` */
  @property({ type: Boolean, reflect: true })
  clickable = false;

  @state()
  private scrollOffset = 0;

  @state()
  private containerHeight = 0;

  /** Measured content height of a row (without padding); 0 = not measured */
  @state()
  private measuredHeight = 0;

  @state()
  private focusedId: VirtualListItem["id"] | null = null;

  @query(".virtualList")
  private container?: HTMLElement;

  @query(".measureItem")
  private measureElement?: HTMLElement;

  private readonly aria = new AriaController(this);
  private readonly locale = new LocaleController(this);
  private resizeObserver: ResizeObserver | null = null;
  private measureObserver: ResizeObserver | null = null;
  private lastScrollTop = 0;
  private loadingMore = false;
  private raf?: number;
  private idle?: number;

  /** The scroll container (e.g. to scroll programmatically) */
  get scrollContainer(): HTMLElement | null {
    return this.container ?? null;
  }

  /** Scrolls so that the row at `index` is at the top of the list */
  scrollToIndex(index: number): void {
    const container = this.container;
    const height = this.rowHeight;
    if (!container || !height) return;
    container.scrollTop = Math.max(0, index) * height;
    this.updateScroll(container.scrollTop);
  }

  private get rowHeight(): number {
    if (this.itemHeight) return this.itemHeight;
    return this.measuredHeight > 0
      ? this.measuredHeight + this.itemPadding * 2
      : 0;
  }

  private get needsMeasure(): boolean {
    return (
      !this.itemHeight && this.measuredHeight === 0 && this.items.length > 0
    );
  }

  override disconnectedCallback(): void {
    super.disconnectedCallback();
    this.resizeObserver?.disconnect();
    this.resizeObserver = null;
    this.measureObserver?.disconnect();
    this.measureObserver = null;
    this.cancelScheduled();
  }

  protected override firstUpdated(): void {
    this.observeContainer();
  }

  protected override reconnectedCallback(): void {
    super.reconnectedCallback();
    this.observeContainer();
  }

  /** Tracks the height of the scroll container. */
  private observeContainer() {
    const container = this.container;
    if (!container) return;
    this.containerHeight = container.clientHeight;
    if (this.resizeObserver || typeof ResizeObserver === "undefined") return;
    this.resizeObserver = new ResizeObserver((entries) => {
      for (const entry of entries) {
        this.containerHeight = entry.contentRect.height;
      }
    });
    this.resizeObserver.observe(container);
  }

  protected override willUpdate(changed: PropertyValues<this>): void {
    // New data / loading state: a new load-more request may happen
    if (changed.has("items") || changed.has("loading")) {
      this.loadingMore = false;
    }
    if (
      this.focusedId !== null &&
      changed.has("items") &&
      !this.items.some((item) => item.id === this.focusedId)
    ) {
      this.focusedId = null;
    }
  }

  protected override updated(): void {
    this.syncMeasure();
    if (DEV && this.items.length > 0 && !this.renderItem) {
      devWarn(
        MinervaVirtualList.tagName,
        "set the renderItem property (a function returning the content of a row); rows show the item id meanwhile.",
      );
    }
    if (DEV && this.maxHeight === undefined) {
      devWarn(
        MinervaVirtualList.tagName,
        "set max-height (pixels): without a bounded height the list cannot scroll, so every row is rendered.",
      );
    }
  }

  /** Measures the first item while no row height is known. */
  private syncMeasure() {
    const node = this.needsMeasure ? this.measureElement : undefined;
    if (!node) {
      this.measureObserver?.disconnect();
      this.measureObserver = null;
      return;
    }
    const measure = () => {
      const height = node.offsetHeight;
      if (height > 0) this.measuredHeight = height;
    };
    measure();
    if (this.measureObserver || typeof ResizeObserver === "undefined") return;
    this.measureObserver = new ResizeObserver(measure);
    this.measureObserver.observe(node);
  }

  private cancelScheduled() {
    if (this.raf !== undefined) {
      cancelAnimationFrame(this.raf);
      this.raf = undefined;
    }
    if (this.idle !== undefined) {
      if (typeof cancelIdleCallback === "function")
        cancelIdleCallback(this.idle);
      this.idle = undefined;
    }
  }

  private schedule(callback: () => void) {
    if (!this.highPerformance) {
      callback();
      return;
    }
    // Only the latest scroll position matters: drop pending work
    this.cancelScheduled();
    this.raf = requestAnimationFrame(() => {
      this.raf = undefined;
      if (typeof requestIdleCallback === "function") {
        this.idle = requestIdleCallback(
          () => {
            this.idle = undefined;
            callback();
          },
          { timeout: 100 },
        );
      } else {
        callback();
      }
    });
  }

  private updateScroll(scrollTop: number) {
    this.scrollOffset = scrollTop;
  }

  private handleScroll(event: Event) {
    const { scrollTop, scrollHeight, clientHeight } =
      event.currentTarget as HTMLElement;
    const scrollingDown = scrollTop > this.lastScrollTop;
    this.lastScrollTop = scrollTop;
    this.schedule(() => {
      this.updateScroll(scrollTop);
      if (
        scrollingDown &&
        !this.loadingMore &&
        !this.loading &&
        scrollHeight - scrollTop - clientHeight < this.loadMoreThreshold &&
        scrollHeight > clientHeight
      ) {
        this.loadingMore = true;
        this.emit("minerva-load-more");
      }
    });
  }

  private visibleWindow(): WindowItem[] {
    const height = this.rowHeight;
    if (!height) return [];
    const { start, end } = getVirtualRange({
      scrollTop: this.scrollOffset,
      viewportHeight: this.containerHeight,
      itemHeight: height,
      itemCount: this.items.length,
      overscan: this.overscan,
    });
    const rows: WindowItem[] = [];
    for (let i = start; i < end; i++)
      rows.push({ index: i, start: i * height });
    // Keep the focused row rendered (at its real position) outside the window
    if (this.focusedId !== null) {
      const index = this.items.findIndex((item) => item.id === this.focusedId);
      if (index >= 0 && (index < start || index >= end)) {
        const row = { index, start: index * height };
        if (index < start) rows.unshift(row);
        else rows.push(row);
      }
    }
    return rows;
  }

  private renderContent(item: VirtualListItem, index: number) {
    return this.renderItem ? this.renderItem(item, index) : String(item.id);
  }

  private activate(item: VirtualListItem, index: number) {
    this.emit("minerva-item-click", { item, index });
  }

  private handleRowKeyDown(
    event: KeyboardEvent,
    item: VirtualListItem,
    index: number,
  ) {
    // Only the row itself: keys of its content are theirs
    if (event.composedPath()[0] !== event.currentTarget) return;
    if (event.key !== "Enter" && event.key !== " ") return;
    event.preventDefault();
    this.activate(item, index);
  }

  private handleRowFocusOut(event: FocusEvent) {
    const row = event.currentTarget as HTMLElement;
    const next = event.relatedTarget as Node | null;
    if (!next || !row.contains(next)) this.focusedId = null;
  }

  protected override hookStates() {
    return { loading: this.loading };
  }

  protected override render() {
    const height = this.rowHeight;
    const label = this.aria.label ?? nothing;
    const rows = this.visibleWindow();
    const total = this.items.length;
    return html`<div
      class="virtualList"
      part="root"
      role="region"
      tabindex="0"
      aria-label=${label}
      aria-busy=${this.loading ? "true" : nothing}
      style=${styleMap({
        maxHeight:
          this.maxHeight !== undefined ? `${this.maxHeight}px` : undefined,
        overflow: "auto",
        position: "relative",
      })}
      @scroll=${this.handleScroll}
    >
      ${
        this.needsMeasure
          ? html`<div class="measureItem" aria-hidden="true">
              ${this.renderContent(this.items[0], 0)}
            </div>`
          : nothing
      }
      <div
        class="virtualListContent"
        part="list"
        role="list"
        aria-label=${label}
        style=${styleMap({
          height: height ? `${total * height}px` : "auto",
          position: "relative",
          willChange: "transform",
        })}
      >
        ${repeat(
          rows,
          (row) => this.items[row.index].id,
          (row) => {
            const item = this.items[row.index];
            return html`<div
              part="item"
              role="listitem"
              class=${classMap({
                virtualListItem: true,
                clickable: this.clickable,
              })}
              style=${styleMap({
                position: "absolute",
                top: "0",
                transform: `translateY(${row.start}px)`,
                width: "100%",
                height: `${height}px`,
                willChange: "transform",
                padding: `${this.itemPadding}px`,
              })}
              tabindex=${this.clickable ? "0" : nothing}
              aria-setsize=${total}
              aria-posinset=${row.index + 1}
              @click=${this.clickable ? () => this.activate(item, row.index) : nothing}
              @keydown=${
                this.clickable
                  ? (event: KeyboardEvent) =>
                      this.handleRowKeyDown(event, item, row.index)
                  : nothing
              }
              @focusin=${() => (this.focusedId = item.id)}
              @focusout=${this.handleRowFocusOut}
            >
              ${this.renderContent(item, row.index)}
            </div>`;
          },
        )}
      </div>
      ${
        this.loading
          ? html`<div class="loadingWrapper" part="loading">
              <div
                class="progressIndicator primary"
                role="progressbar"
                aria-label=${this.locale.t("common.loading")}
              >
                <div class="waveContainer small">
                  <span class="wave" aria-hidden="true">${IconWaveSquare}</span>
                </div>
              </div>
            </div>`
          : nothing
      }
    </div>`;
  }
}

declare global {
  interface HTMLElementTagNameMap {
    "minerva-virtual-list": MinervaVirtualList;
  }
}
